### ISSUE TITLE
Rework iOS build instructions

### ISSUE THREAD

**Issue by MikePall** [LuaJIT/LuaJIT#1]
The iOS build instructions need to be reworked. Changing the iOS SDK version in the docs every now and then is not a maintainable solution.

Also, for the 2.1 branch, build instructions for iOS ARM64 need to be added before the final release.

**Comment by mraleph** [comment]
To avoid hard-coding iOS SDK version into build instructions we could resolve paths through `xcrun`

```
ICC=$(xcrun --sdk iphoneos --find clang)
ISDKF="-arch armv7 -isysroot $(xcrun --sdk iphoneos --show-sdk-path)"
make CC=$ICC HOST_CC="clang -m32 -arch i386"  TARGET_FLAGS="$ISDKF" \
     TARGET_SYS=iOS
```

@slime73 Alex, you seem to know a lot more about iOS development than I do - any opinion on this?

**Comment by MikePall** [comment]
Fixed.
