### ISSUE TITLE
JIT bug: Stuck / hang / 100% CPU load in pairs on MIPSel

### ISSUE THREAD

**Issue by Bartel-C8** [LuaJIT/LuaJIT#1000]
Hi,

Recently we upstepped buildroot on our 32-bit MIPS / MIPSEL platform (embedded hardware), which involved a newer version of luajit.
In our, quite complex, project, at some point it always got stuck in the `pairs` method while iterating over a table.

Some bug reports that were fixed that were somewhat similar:
https://github.com/LuaJIT/LuaJIT/issues/610
https://github.com/LuaJIT/LuaJIT/issues/744
https://github.com/LuaJIT/LuaJIT/issues/494
But all above were fixed and thus not valid anymore.

I managed to strip our project - somewhat - down in order to get a reproducible case.

[jitBug.zip](https://github.com/LuaJIT/LuaJIT/files/11565123/jitBug.zip)

cd into the extracted folder and execute `run.sh` (which is a iterating wrapper, running luajit).
Strangely, the bug is more quickly reproducible when executing `luajit testBug.lua` multiple times in a row, opposed to looping inside the script itself.

It has some varying number of times it needs to run before hanging: 6 times, 30 times, ... In this case I never had it not-failing in, let's say, 100 times.
You should see multiple logs like this:

```
DEVICES	table: 0x77a04818
Loading root device external address1
```

When it stops logging, you can sigint with CTRL + C on which it prints the count on how many times it ran.

Some requirements:

- luajit: currently testing on HEAD, where the issue is present
- lsqlite3 luarocks module (https://luarocks.org/modules/dougcurrie/lsqlite3) for loading a lua table stored in a database
- DLUAJIT_ENABLE_LUA52COMPAT build, because a file: `store.lua` is dependent to support `__pairs` metamethod.
- lluv luarocks module (https://luarocks.org/modules/moteus/lluv) . It is an alternative to the more known `luv` (https://luarocks.org/modules/creationix/luv). But with `lluv` the issue is easier to reproduce in this minimal repro case.
In our project we replaced `lluv` with `luv`, to test, and the bug also appeared. So actually it's unrelated.
- We relied on luaprompt/prompt to print tables (https://luarocks.org/modules/dpapavas/luaprompt) but I stubbed it with a pure lua function.
- catch assert to not crash/stop when asserted, wrapped in a pcall with logging

General note: most of dependencies above cannot be stripped unfortunately, as it caused the bug not to trigger anymore, or very less frequent (number of times to run it increases).

When running with `-joff` (you can verify it as well with `run.sh -joff`) the issue does not appear. So presumably a JIT-issue only.

The issue is also reproducible on a mipsel QEMU. For practicality (with all the dependencies), I prepared a QEMU image and rootfs containing the repro case.

[vmlinux.tar.gz](https://github.com/LuaJIT/LuaJIT/files/11565176/vmlinux.tar.gz)
[rootfs.ext2.tar.gz](https://github.com/LuaJIT/LuaJIT/files/11565177/rootfs.ext2.tar.gz)

To run:

```
qemu-system-mipsel -M malta -kernel vmlinux  -drive file=rootfs.ext2,format=raw -append "rootwait root=/dev/sda" -net nic,model=pcnet -net user -nographic
```

Login: root
password: root

```
cd jitBug
./run.sh
```

Same procedure to check if it's hanging as above.

I also tested it on a ARM64/AARCH64 QEMU , but was not able to reproduce it. Nor on my macOS (x64)... So presumably a MIPS issue only.

Looking at the history of the `src/lj_asm_mips.h` file, I traced some commits (from old to newer)

1a4ff1311740aa6c85f7a9101b6aa9bfaafa3f8e - works
71db0cf04357391beb01732af691a4df25298911 - works
bb0f24101565d34ea8b70fdec4dd3f3b35a70e7b - hangs very early, does not even run once!
d3294fa63b344173db68dd612c6d3801631e28d4 - fixes the revision above, and always works
4a70bd71ac18ccd57a335a4f5b8cbdefbbd4931b - hangs (which I didn’t expected, as it seems a minor change)
1cdff194cfa22cfe5bfc0e908b909e2dea40aa70 - hangs
224129a8e64bfa219d35cd03055bf03952f167f6 - hangs (current HEAD)

Many thanks in advance.
Please let me know if I can provide more useful info/logging.

**Comment by MikePall** [comment]
Sorry, but this is still way too big and has too many external dependencies.
You need to reduce it to an isolated testcase or contract someone to do it for you (I'm not available at this time).

**Comment by Bartel-C8** [comment]
@MikePall Thanks for looking at this and your quick reply. Suspected already that it would be way to big.

Any hints/clues on how to reduce this to an isolated test case? Which tools/debug info could give some more insight?/
Thanks!

**Comment by MikePall** [comment]
Run with: `-jdump=+rsx,dump.txt`
Look at the generated machine code for the last few traces which are related to the pairs loop.
Attach a debugger to the process and break/continue to find the machine code addresses it's looping over. Cross-ref with the dump.
Compare with the equivalent machine code generated for ARM64 (because it's quite similar).
Compare the source code generating these machine code instructions in `lj_asm_*.h` and `lj_emit_*.h`.

**Comment by corsix** [comment]
If I'm reading `lj_asm_mips.h` correctly, `lj_asm_patchexit` therein can _sometimes_ end up doing nothing:
https://github.com/LuaJIT/LuaJIT/blob/8635cbabf3094c4d8bd00578c7d812bea87bb2d3/src/lj_asm_mips.h#L2793

If I patch `lj_trace.c` and remove the call to `lj_asm_patchexit`, then this should give the same behaviour of doing nothing. With said patch in place, a simple pairs loop can cause an infinite loop (on any architecture with JIT):
```lua
local t = {}
for i=1,80 do t[i] = i end
t[60] = true
for k,v in pairs(t) do assert(v, k) end
```
This suggests that it is not correct for `lj_asm_patchexit` to do nothing.

-----

As additional evidence, what follows is an excerpt from a `dump.txt` in which the hang is observed. Firstly we have trace 85:
```
---- TRACE 85 start util.lua:70
0034  ITERN    5   3   3
0005  GGET     7   1      ; "type"
0006  MOV      8   6
0007  CALL     7   2   2
0000  . FUNCC               ; type
0008  ISNES    7   2      ; "table"
0009  JMP      7 => 0031
0010  GGET     7   1      ; "type"
0011  TGETV    8   0   5
0012  IST          8
0013  JMP      9 => 0015
0014  KPRI     8   1
0015  CALL     7   2   2
0000  . FUNCC               ; type
0016  ISNES    7   2      ; "table"
0017  JMP      7 => 0029
0029  TSETV    6   0   5
0030  JMP      7 => 0034
0034  ITERN    5   3   3
---- TRACE 85 IR
....              SNAP   #0   [ ---- ---- ---- ---- ---- ---- ]
....              SNAP   #1   [ ---- ---- ---- ---- ---- ---- ]
0002 [20]  >  tab SLOAD  #4    T
0003 r5    >  int SLOAD  #5    TK
0005 r2       p32 CALLL  lj_vm_next  (0002 0003)
0006 [18]   + int HIOP   0005  0005
0007 r22   >+ str VLOAD  0005  #1
0008 r23   >+ tab VLOAD  0005  #0
....              SNAP   #2   [ ---- ---- ---- ---- ---- 0006 0007 0008 ]
0009 r2       fun SLOAD  #0    R
0010 [14]     tab FLOAD  0009  func.env
0011 r3       int FLOAD  0010  tab.hmask
0012       >  int EQ     0011  +127
0013 r3       p32 FLOAD  0010  tab.node
0014       >  p32 HREFK  0013  "type" @47
0015 r2    >  fun HLOAD  0014
0016       >  fun EQ     0015  type
0017 [1c]  >  tab SLOAD  #1    T
0018 r24      p32 HREF   0017  0007
0019       >  p32 EQ     0018  [0x77d21298]
0020 r1       tab FLOAD  0017  tab.meta
0021       >  tab EQ     0020  NULL
0022 r2       p32 NEWREF 0017  0007
0023          tab HSTORE 0022  0008
0024          nil TBAR   0017
0025          p32 FREF   0017  tab.nomm
0026          u8  FSTORE 0025  +0
....              SNAP   #3   [ ---- ---- ---- ---- ---- 0006 0007 0008 ]
0027 ------------ LOOP ------------
....              SNAP   #4   [ ---- ---- ---- ---- ---- 0006 ]
0029 r21      p32 CALLL  lj_vm_next  (0002 0006)
0030 [10]   + int HIOP   0029  0029
0031 r22   >+ str VLOAD  0029  #1
0032 r23   >+ tab VLOAD  0029  #0
....              SNAP   #5   [ ---- ---- ---- ---- ---- 0030 0031 0032 ]
0033 r21      int FLOAD  0010  tab.hmask
0034       >  int EQ     0033  +127
0035 r20      p32 FLOAD  0010  tab.node
0036       >  p32 HREFK  0035  "type" @47
0037 r21   >  fun HLOAD  0036
0038       >  fun EQ     0037  type
0039 r24      p32 HREF   0017  0031
0040       >  p32 EQ     0039  [0x77d21298]
0041 r2       p32 NEWREF 0017  0031
0042          tab HSTORE 0041  0032
0043 r3       int PHI    0006  0030
0044 r22      str PHI    0007  0031
0045 r23      tab PHI    0008  0032
---- TRACE 85 mcode 656
779a2310  addiu   sp, sp, -24
779a2314  lui     r25, 30679
779a2318  ori     r25, r25, 57012
779a231c  li      r19, -9
779a2320  addiu   r18, r30, -22384
779a2324  li      r17, -5
779a2328  li      r2, -12
779a232c  lui     r1, 65534
779a2330  ori     r1, r1, 32767
779a2334  lw      ra, 28(r16)
779a2338  lw      r4, 24(r16)
779a233c  bne     ra, r2, 0x779a25a0    ->exit
779a2340  li      ra, 1
779a2344  sw      r4, 32(sp)
779a2348  lw      ra, 36(r16)
779a234c  lw      r5, 32(r16)
779a2350  bne     ra, r1, 0x779a25a0    ->exit
779a2354  li      ra, 1
779a2358  jal     0x77d7deb4    ->lj_vm_next
779a235c  nop
779a2360  sw      r3, 24(sp)
779a2364  lui     r25, 30683
779a2368  ori     r25, r25, 25216
779a236c  li      r5, 127
779a2370  lw      r4, -32524(r30)
779a2374  li      r1, -12
779a2378  lw      ra, 12(r2)
779a237c  lw      r22, 8(r2)
779a2380  bne     ra, r17, 0x779a25a0   ->exit
779a2384  li      ra, 1
779a2388  lw      ra, 4(r2)
779a238c  lw      r23, 0(r2)
779a2390  bne     ra, r1, 0x779a25a0    ->exit
779a2394  li      ra, 1
779a2398  lw      r2, -8(r16)
779a239c  lw      r2, 8(r2)
779a23a0  sw      r2, 20(sp)
779a23a4  lw      r3, 28(r2)
779a23a8  bne     r3, r5, 0x779a25a0    ->exit
779a23ac  li      ra, 2
...
779a2598  j       0x779a2494    ->LOOP
779a259c  nop
---- TRACE 85 stop -> loop
```

Trace 85 exit 1 gets taken enough times to be compiled as trace 86:
```
---- TRACE 86 start 85/1 util.lua:70
0034  ITERN    5   3   3
0036  RET1     0   2
0028  JMP      7 => 0034
0034  JLOOP    6  85
---- TRACE 86 IR
....              SNAP   #0   [ ---- ---- ---- ---- ---- ---- ]
....              SNAP   #1   [ ---- ---- ---- ---- ---- ---- ]
0002 r4    >  tab SLOAD  #4    T
0003 r5    >  int SLOAD  #5    TK
0005 r2       p32 CALLL  lj_vm_next  (0002 0003)
0006          int HIOP   0005  0005
0007       >  nil VLOAD  0005  #1
....              SNAP   #2   [ ---- ---- ---- ]
0008       >  tab SLOAD  #1    T
....              SNAP   #3   [ ---- ---- ---- ]
0009       >  p32 RETF   proto: 0x77a7d988  [0x77a7da38]
....              SNAP   #4   [ ---- ---- ---- ---- ---- ---- ---- ]
---- TRACE 86 mcode 132
779a2280  lw      r16, -32520(r30)
779a2284  lui     r25, 30679
779a2288  ori     r25, r25, 57012
779a228c  li      r18, -12
779a2290  lui     r17, 65534
779a2294  ori     r17, r17, 32767
779a2298  lw      ra, 28(r16)
779a229c  lw      r4, 24(r16)
779a22a0  bne     ra, r18, 0x779a2304   ->exit
779a22a4  li      ra, 1
779a22a8  lw      ra, 36(r16)
779a22ac  lw      r5, 32(r16)
779a22b0  bne     ra, r17, 0x779a2304   ->exit
779a22b4  li      ra, 1
779a22b8  jal     0x77d7deb4    ->lj_vm_next
779a22bc  nop
779a22c0  li      r3, -1
779a22c4  lui     r1, 30631
779a22c8  ori     r1, r1, 55864
779a22cc  lw      ra, 12(r2)
779a22d0  bne     ra, r3, 0x779a2304    ->exit
779a22d4  li      ra, 1
779a22d8  li      r2, -12
779a22dc  lw      ra, 4(r16)
779a22e0  bne     ra, r2, 0x779a2304    ->exit
779a22e4  li      ra, 2
...
779a22fc  j       0x779a2310
779a2300  addiu   sp, sp, 24
---- TRACE 86 stop -> 85
```

Some time later, trace 86 exit 1 gets taken enough times to be compiled as trace 161:
```
---- TRACE 161 start 86/1 util.lua:70
0034  ITERN    5   3   3
0005  GGET     7   1      ; "type"
0006  MOV      8   6
0007  CALL     7   2   2
0000  . FUNCC               ; type
0008  ISNES    7   2      ; "table"
0009  JMP      7 => 0031
0031  ISEQP    5   0
0032  JMP      7 => 0034
0033  TSETV    6   0   5
0034  JLOOP    6  85
---- TRACE 161 IR
....              SNAP   #0   [ ---- ---- ---- ---- ---- ---- ]
....              SNAP   #1   [ ---- ---- ---- ---- ---- ---- ]
0002 r4    >  tab SLOAD  #4    T
0003 r5    >  int SLOAD  #5    TK
0005 r2       p32 CALLL  lj_vm_next  (0002 0003)
0006 [10]     int HIOP   0005  0005
0007 r23   >  str VLOAD  0005  #1
0008       >  tru VLOAD  0005  #0
....              SNAP   #2   [ ---- ---- ---- ---- ---- 0006 0007 true ]
0009 r22      fun SLOAD  #0    R
0010 r22      tab FLOAD  0009  func.env
0011 r20      int FLOAD  0010  tab.hmask
0012       >  int EQ     0011  +127
0013 r20      p32 FLOAD  0010  tab.node
0014       >  p32 HREFK  0013  "type" @47
0015 r22   >  fun HLOAD  0014
0016       >  fun EQ     0015  type
....              SNAP   #3   [ ---- ---- ---- ---- ---- 0006 0007 true ]
0017 r22   >  tab SLOAD  #1    T
0018 r24      p32 HREF   0017  0007
0019       >  p32 EQ     0018  [0x77d21298]
0020 r21      tab FLOAD  0017  tab.meta
0021       >  tab EQ     0020  NULL
0022 r2       p32 NEWREF 0017  0007
0023          tru HSTORE 0022  true
0024          p32 FREF   0017  tab.nomm
0025          u8  FSTORE 0024  +0
....              SNAP   #4   [ ---- ---- ---- ---- ---- 0006 0007 ]
---- TRACE 161 mcode 372
778f7424  lw      r16, -32520(r30)
...
778f7590  j       0x779a2310
778f7594  addiu   sp, sp, 24
---- TRACE 161 stop -> 85
```

Interestingly, after this, the remainder of `dump.txt` is exclusively repitions of:
```
---- TRACE 86 exit 1
---- TRACE 86 exit 1
---- TRACE 86 exit 1
---- TRACE 86 exit 1
---- TRACE 86 exit 1
---- TRACE 86 exit 1
---- TRACE 86 exit 1
---- TRACE 86 exit 1
---- TRACE 86 exit 1
---- TRACE 86 exit 1
---- TRACE 86 exit 1
```

This suggests that trace 86 exit 1 didn't get patched to become a jump to trace 161 (c.f. `lj_asm_patchexit` therein can _sometimes_ end up doing nothing)

**Comment by corsix** [comment]
Potentially there are two different paths to fixing things here:
1. Ensure forward progress is always made after taking a trace exit: when exiting to an `ITERN` instruction (especially from exit number 1), at least one meaningful bytecode instruction should be executed by the interpreter before re-entering a trace.
2. Ensure `lj_asm_patchexit` always attaches the child trace (bringing MIPS in line with every other backend).

I've put a prototype for (2) at https://github.com/corsix/LuaJIT/commits/mips-patchexit - the resultant generated code isn't a paragon of speed at runtime, but hopefully it is rare for the exit jump to be long-range _and_ to have run out of spare jump slots.

I've not investigated how easy (1) would be, but either path should fix this (and there's no harm in doing both).

**Comment by corsix** [comment]
Possible implementation of (1) at https://github.com/corsix/LuaJIT/commits/itern-exit.

**Comment by Bartel-C8** [comment]
I did retry my (bulky) reproduction case from above (didn't knew if you did, @corsix ).
With the latest v2.1 branch HEAD, 8635cbabf3094c4d8bd00578c7d812bea87bb2d3 , somehow it took longer to reproduce than before (186 runs and 338 runs)

With both your suggestions, I wasn't able to reproduce it.
done 825 runs for https://github.com/corsix/LuaJIT/commit/e2d25b5a5330792c65d8cf7408608ff213068815
and 547 runs for https://github.com/corsix/LuaJIT/commit/6e5c9dbc9938e1a6c9802f544f609b611fe1ed54

So it seems like I indeed was hitting the "theoretical" case @corsix described.
Maybe there is a better, minimal, reproduction test case possible now. But that's beyond my knowledge unfortunately.

So thank you very much for your work on this @corsix . Any suggestion on which (or both) patches to prefer?
And @MikePall if you agree on either/both to consider merging them?

Many thanks.

**Comment by corsix** [comment]
Yes, I reproduced the issue using your bulk, albeit only taking the shell and Lua components as-is, and building a QEMU image + lsqlite3 + lluv from scratch. The trace logs in my comments above are from this. That same setup was used to take the potential fixes for a spin, getting to 1000+ iterations without hanging.

**Comment by MikePall** [comment]
I found a simpler solution to force a static dispatch by extending `lj_vm_exit_interp` for this case. This solves #1045, too.
Thanks to Peter for the analysis!

**Comment by corsix** [comment]
Can said extension to `lj_vm_exit_interp` also be used to address the conceptual NYI in `asm_tail_link`?
```diff
diff --git a/src/lj_asm.c b/src/lj_asm.c
index 71079b30b8..f383858eef 100644
--- a/src/lj_asm.c
+++ b/src/lj_asm.c
@@ -2087,12 +2087,8 @@ static void asm_tail_link(ASMState *as)
   if (as->T->link == 0) {
     /* Setup fixed registers for exit to interpreter. */
     const BCIns *pc = snap_pc(&as->T->snapmap[snap->mapofs + snap->nent]);
+    const BCIns *retpc;
     int32_t mres;
-    if (bc_op(*pc) == BC_JLOOP) {  /* NYI: find a better way to do this. */
-      BCIns *retpc = &traceref(as->J, bc_d(*pc))->startins;
-      if (bc_isret(bc_op(*retpc)))
-       pc = retpc;
-    }
 #if LJ_GC64
     emit_loadu64(as, RID_LPC, u64ptr(pc));
 #else
@@ -2105,9 +2101,13 @@ static void asm_tail_link(ASMState *as)
       mres -= (int32_t)(1 + LJ_FR2 + bc_a(*pc) + bc_c(*pc)); break;
     case BC_RETM: mres -= (int32_t)(bc_a(*pc) + bc_d(*pc)); break;
     case BC_TSETM: mres -= (int32_t)bc_a(*pc); break;
+    case BC_JLOOP:
+      retpc = &traceref(as->J, bc_d(*pc))->startins;
+      mres = (bc_isret(bc_op(*retpc)) || bc_op(*retpc) == BC_ITERN) ? -17 : 0;
+      break;
     default: if (bc_op(*pc) < BC_FUNCF) mres = 0; break;
     }
-    ra_allockreg(as, mres, RID_RET);  /* Return MULTRES or 0. */
+    ra_allockreg(as, mres, RID_RET);  /* Return MULTRES or 0 or -17. */
   } else if (baseslot) {
     /* Save modified BASE for linking to trace with higher start frame. */
     emit_setgl(as, RID_BASE, jit_base);
```
