### ISSUE TITLE
Luajit print error "cannot load incompatible bytecode"

### ISSUE THREAD

**Issue by fengyd2006** [LuaJIT/LuaJIT#1001]
Hi,

I pulled the latest code v2.1 https://github.com/LuaJIT/LuaJIT.git and compiled the code to generate the program luajit with the command "make".
The compiling environment is Linux e32d1d5e2d53 5.4.0-148-generic #165-Ubuntu SMP Tue Apr 18 08:53:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux.

The test steps:
1. Creat a simple lua script test.lua, which only contains the following code.
print("OK")
2. luajit -b -g test.lua testbytecode.lua
3. Upload testbytecode.lua to my ARM server
4.  Run "luajit testbytecode.lua" on ARM server, it print error "cannot load incompatible bytecode".

I tried to trace the cause,  and found that the value of **flags** is 8.
Some extra options need to be added during compiling?

389 static int bcread_header(LexState *ls)
390 {
391   uint32_t flags;
392   bcread_want(ls, 3+5+5);
393   if (bcread_byte(ls) != BCDUMP_HEAD2 ||
394       bcread_byte(ls) != BCDUMP_HEAD3 ||
395       bcread_byte(ls) != BCDUMP_VERSION) return 0;
396   bcread_flags(ls) = **flags** = bcread_uleb128(ls);
397   if ((flags & ~(BCDUMP_F_KNOWN)) != 0) return 0;
398   if ((flags & BCDUMP_F_FR2) != LJ_FR2*BCDUMP_F_FR2) return 0;
399   if ((flags & BCDUMP_F_FFI)) {
400 #if LJ_HASFFI
401     lua_State *L = ls->L;
402     ctype_loadffi(L);
403 #else
404     return 0;
405 #endif
406   }
407   if ((flags & BCDUMP_F_STRIP)) {
408     ls->chunkname = lj_str_newz(ls->L, ls->chunkarg);
409   } else {
410     MSize len = bcread_uleb128(ls);
411     bcread_need(ls, len);
412     ls->chunkname = lj_str_new(ls->L, (const char *)bcread_mem(ls, len), len);
413   }
414   return 1;  /* Ok. */

ARM server info:
processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 49.50
Features        : half thumb fastmult edsp java tls
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7

**Comment by MikePall** [comment]
Quoting the docs:
| Note: `LJ_GC64` mode requires a different frame layout, which implies a different, incompatible bytecode format for all 64 bit ports.

You need to generate the bytecode from a host LuaJIT built with `LUAJIT_DISABLE_GC64`.

**Comment by fengyd2006** [comment]
@MikePall
Now, it works.

Thanks.
