### ISSUE TITLE
Pointer trunc in JIT codegen w/ lj_tab_newkey.

### ISSUE THREAD

**Issue by can1357** [LuaJIT/LuaJIT#1002]
asm_newref seems to end up generating this code:
```asm
48 8B D7                       mov         rdx,rdi  
48 B8 D0 DF A5 14 F7 7F 00 00  mov         rax,offset lj_tab_newkey (07FF714A5DFD0h)  
FF D0                          call        rax  
8B E8                          mov         ebp,eax  <----
48 8B 93 08 F2 FF FF           mov         rdx,qword ptr [rbx-0DF8h]  
48 89 75 00                    mov         qword ptr [rbp],rsi  <---
81 65 04 FF 7F 00 00           and         dword ptr [rbp+4],7FFFh  
81 4D 04 00 80 F9 FF           or          dword ptr [rbp+4],0FFF98000h  
F6 47 08 04                    test        byte ptr [rdi+8],4  
74 16                          je          000001FF3825DB8C  
80 67 08 FB                    and         byte ptr [rdi+8],0FBh  
48 8B B3 D0 F0 FF FF           mov         rsi,qword ptr [rbx-0F30h]  
48 89 BB D0 F0 FF FF           mov         qword ptr [rbx-0F30h],rdi  
48 89 77 18                    mov         qword ptr [rdi+18h],rsi  
81 7A 14 00 00 F9 FF           cmp         dword ptr [rdx+14h],0FFF90000h  
0F 83 FB 24 FF FF              jae         000001FF38250094  
F2 0F 10 7A 10                 movsd       xmm7,mmword ptr [rdx+10h]  
F2 0F 58 FE                    addsd       xmm7,xmm6  
F2 0F 11 7A 10                 movsd       mmword ptr [rdx+10h],xmm7  
```

Operation is IR_NEWREF and type seems to be IRT_P32, I've tracked it down to commit [c7db825](https://github.com/LuaJIT/LuaJIT/commit/c7db8255e1eb59f933fac7bc9322f0e4f8ddc6e6), specifically this line:
https://github.com/LuaJIT/LuaJIT/blob/c7db8255e1eb59f933fac7bc9322f0e4f8ddc6e6/src/lj_record.c#L1261

Return type is IRT_PCG, marking it as IRT_P32 causes asm_setupresult to call into if RAX cannot be allocated as an alias:
https://github.com/LuaJIT/LuaJIT/blob/c7db8255e1eb59f933fac7bc9322f0e4f8ddc6e6/src/lj_asm.c#L664-L673
https://github.com/LuaJIT/LuaJIT/blob/c7db8255e1eb59f933fac7bc9322f0e4f8ddc6e6/src/lj_emit_x86.h#L426-L433

Since type is P32, REX_64IR skips the REX prefix required.

**Comment by MikePall** [comment]
1. You have not indicated which version of LuaJIT you are using. 
2. You failed to provide an isolated pure Lua test case.

The above machine code is not generated by any version of LuaJIT I know of, e.g. the `mov` + `and` + `or` sequence.

The machine code looks like GC64 mode, but the referenced source code is part of LuaJIT v2.0. v2.0 doesn't have this mode and all internal memory pointers are 32 bit.
Also, the referenced commit does not include any changes to that line.

**Comment by can1357** [comment]
For some reason my local fork's merge for  https://github.com/LuaJIT/LuaJIT/commit/8bbd58e534522a7e1ab9ee2c0d7fb723741dd089 pulled P32 from v2.0, my apologies.

I was of course on master, wouldn't have created an issue for an older version.
