### ISSUE TITLE
dis_mips64r6.lua and dis_mips64r6el.lua files missing in make install

### ISSUE THREAD

**Issue by FractalU** [LuaJIT/LuaJIT#1010]
The `FILES_JITLIB` variable in the Makefile has `dis_mips64r6.lua` and `dis_mips64r6el.lua` files missing. When typing `make install` to install luajit, those files won't get installed in the `share\luajit-2.1.0-beta3\jit` directory.

In Makefile at line 92
```
FILES_JITLIB= bc.lua bcsave.lua dump.lua p.lua v.lua zone.lua \
	      dis_x86.lua dis_x64.lua dis_arm.lua dis_arm64.lua \
	      dis_arm64be.lua dis_ppc.lua dis_mips.lua dis_mipsel.lua \
	      dis_mips64.lua dis_mips64el.lua vmdef.lua
```
should be instead
```
FILES_JITLIB= bc.lua bcsave.lua dump.lua p.lua v.lua zone.lua \
	      dis_x86.lua dis_x64.lua dis_arm.lua dis_arm64.lua \
	      dis_arm64be.lua dis_ppc.lua dis_mips.lua dis_mipsel.lua \
	      dis_mips64.lua dis_mips64el.lua dis_mips64r6.lua dis_mips64r6el.lua \
	      vmdef.lua
```

Im using the up-to-date v2.1 branch of 64 bit luajit on msys2 windows. I also checked the v2.0 branch and this issue doesn't apply there, because the v2.0 branch does't have a MIPS64 R6 port.

**Comment by MikePall** [comment]
Fixed. Thanks!
