### ISSUE TITLE
Can't turn on the JIT

### ISSUE THREAD

**Issue by LittleBread69** [LuaJIT/LuaJIT#1011]
It only gives this:

![Capture d’écran 2023-06-12 à 00 00 06](https://github.com/LuaJIT/LuaJIT/assets/111202841/9e378e2b-af14-4520-96aa-03f6dafb3fbe)

My LuaJIT version:
![Capture d’écran 2023-06-12 à 00 01 38](https://github.com/LuaJIT/LuaJIT/assets/111202841/f766f38a-da66-4a73-8db7-d2bb9501d8f5)

Platform: Mac OS X
Arch: Arm64

**Comment by MikePall** [comment]
1. Do not report an issue, if you're not using the latest version from the git repository.
2. Never post screenshots, when the text could just be cut'n'pasted.
