### ISSUE TITLE
Can I use lua_sethook across threads?

### ISSUE THREAD

**Issue by libing0526** [LuaJIT/LuaJIT#1012]
I want to stop the execution of the luajit virtual machine in another thread. I found a description in the source code:
```
  /* Regularly check for instruction/line hooks from compiled code and
  ** exit to the interpreter if the hooks are set.
  **
  ** This is a compile-time option and disabled by default, since the
  ** hook checks may be quite expensive in tight loops.
  **
  ** Note this is only useful if hooks are *not* set most of the time.
  ** Use this only if you want to *asynchronously* interrupt the execution.
  **
  ** You can set the instruction hook via lua_sethook() with a count of 1
  ** from a signal handler or another native thread. Please have a look
  ** at the first few functions in luajit.c for an example (Ctrl-C handler).
  */
```
"or another native thread" does it means I can use lua_sethook in another thread to interrupt luajit？code like this:
```
static void lstop(lua_State *L, lua_Debug *ar)
{
  (void)ar;  /* unused arg. */
  lua_sethook(L, NULL, 0, 0);
  /* Avoid luaL_error -- a C hook doesn't add an extra frame. */
  luaL_where(L, 0);
  lua_pushfstring(L, "%sinterrupted!", lua_tostring(L, -1));
  lua_error(L);
}
void another_thread_func(lua_State *L)
{
   lua_sethook(globalL, lstop, LUA_MASKCALL | LUA_MASKRET | LUA_MASKCOUNT, 1);
}
```

**Comment by XmiliaH** [comment]
The comment in the source is wrong. Take a look at the comment from Mike here https://github.com/LuaJIT/LuaJIT/issues/824#issuecomment-1084710118

**Comment by libing0526** [comment]
@XmiliaH signal is not a suitable solution.It may cause unknown exceptions. I Iwould like to follow hook's example and add a flag that can be set through multiple threads and then directly lua_error internally. So How do you do this: abort luajit execution in multithreading?

**Comment by XmiliaH** [comment]
I am not aware of a way to do this without signals or without modifying LuaJIT. What should be safe is to suspend the thread, then set the hook and resume the thread, but there is no portable way to suspend threads and for Linux this seems to also rely on signals.

**Comment by libing0526** [comment]
Yes, I also tried to ensure the security of multithreaded set_hook by suspending the thread, which is OK under windows. However, threads cannot be paused and resumed under linux (without the use of mutex, similar to Windows SuspendThread and ResumeThread). But with signals, there may be more unknown problems. I can only try to modify the Luajit code to see if I can stop Luajit execution by setting the flag bit.

**Comment by libing0526** [comment]
There seems to be no feasible way. If anyone has a good idea, thank you for sharing it
