### ISSUE TITLE
numistrueint() relies on undefined behavior

### ISSUE THREAD

**Issue by Myriachan** [LuaJIT/LuaJIT#1015]
The [`numistrueint()`](https://github.com/LuaJIT/LuaJIT/blob/ff6c496ba1b51ed360065cbc5259f62becd70daa/src/lj_ir.c#L252) function in `lj_ir.c` relies on undefined behavior.  Specifically, it checks whether the result of [`lj_num2int()`](https://github.com/LuaJIT/LuaJIT/blob/ff6c496ba1b51ed360065cbc5259f62becd70daa/src/lj_obj.h#L997) survives a trip back into `lua_Number`.  If the number is, in fact, outside the range of `int32_t`, the behavior is undefined per C standard 6.3.1.4(1):

> When a finite value of standard floating type is converted to an integer type other than `bool`, the fractional part is discarded (i.e., the value is truncated toward zero). If the value of the integral part cannot be represented by the integer type, the behavior is undefined.

The `numistrueint()` function seems to rely on such a cast being an unspecified result, then detecting that, but it's actually undefined behavior.

This can be seen in the assembly output of a simple program in Clang with `-fsanitize=undefined`: https://gcc.godbolt.org/z/GdGjTn5v1

A better solution would be something like this.  Note that we don't need to check for e.g. +2147483647.6, which truncates to `INT_MAX` and is thus in range, because the check whether the result is exactly an integer would fail later.

```c
/* Check whether a number is int and return it. -0 is NOT considered an int. */
static int numistrueint(lua_Number n, int32_t *kp)
{
  /* need to check this, else undefined behavior occurs upon conversion */
  if (!isfinite(n) || (n < INT32_MIN) || (n > INT32_MAX))
    return 0;
  /* what you have now */
  ...
}
```

**Comment by Myriachan** [comment]
I noticed this because the JITter was calling `numistrueint()` on the value `(double)((UINT64_C(1) << 52) + 1)`, whose origin I don't know.

**Comment by MikePall** [comment]
As long as the 'undefined behaviour' just means an 'undefined result', the current code is perfectly fine. Because the following comparison masks any undefined result (it could even be random). And it just so happens this is the case for all compilers on all supported platforms of LuaJIT.
