### ISSUE TITLE
Crash FindNextFile without error messages

### ISSUE THREAD

**Issue by KionX** [LuaJIT/LuaJIT#1018]
Tried A, W, x32, x64, new and old LuaJIT. Build MSVC 2022.

```
ffi = require('ffi')
ffi.cdef[[
  typedef uint32_t DWORD;
  typedef uint16_t WORD;
  typedef char CHAR;
  typedef void* HANDLE;
  typedef uint32_t BOOL;
  typedef const char* LPCSTR;

  typedef struct _FILETIME {
    DWORD dwLowDateTime;
    DWORD dwHighDateTime;
  } FILETIME, *PFILETIME, *LPFILETIME;

  typedef struct _WIN32_FIND_DATAA {
    DWORD    dwFileAttributes;
    FILETIME ftCreationTime;
    FILETIME ftLastAccessTime;
    FILETIME ftLastWriteTime;
    DWORD    nFileSizeHigh;
    DWORD    nFileSizeLow;
    DWORD    dwReserved0;
    DWORD    dwReserved1;
    CHAR     cFileName[260];
    CHAR     cAlternateFileName[14];
  } WIN32_FIND_DATAA, *PWIN32_FIND_DATAA, *LPWIN32_FIND_DATAA;

  HANDLE FindFirstFileA(LPCSTR lpFileName, LPWIN32_FIND_DATAA lpFindFileData);
  BOOL FindNextFileA(HANDLE hFindFile, LPWIN32_FIND_DATAA lpFindFileData);
]]
```
This works:
```
s = ffi.new('WIN32_FIND_DATAA')
print(ffi.sizeof('WIN32_FIND_DATAA'))
h = ffi.C.FindFirstFileA([[C:\Windows]],s)
print(h)
print(ffi.C.FindNextFileA(h, s))
```
With local not works:
```
local s = ffi.new('WIN32_FIND_DATAA')
print(ffi.sizeof('WIN32_FIND_DATAA'))
local h = ffi.C.FindFirstFileA([[C:\Windows]],s)
print(h)
print(ffi.C.FindNextFileA(h, s))
```
if exec with local after not local then also works.

**Comment by XmiliaH** [comment]
You should look into [the documentation](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-findnextfilea) as you seem to use the `FindNextFileA` function wrong. The first parameter needs to be a return from the `FindFirstFile[Ex]` function and the second parameter a pointer to a `WIN32_FIND_DATA` structure and not a null pointer.

**Comment by KionX** [comment]
This is the minimum code. I know how to use FindNextFile. Should LuaJIT crash without error messages?

**Comment by XmiliaH** [comment]
> Should LuaJIT crash without error messages?

If you use the FFI wrong, including calling C functions with wrong parameters, [YES](https://luajit.org/ext_ffi_semantics.html#policy).

> If you make a mistake, your application might crash, just like equivalent C code would.

**Comment by KionX** [comment]
Updated. Crash for some reason is associated with local variables.

**Comment by KionX** [comment]
I figured it out. locals confused me. do ... the end was missing.

**Comment by vanc** [comment]
Just a friendly reminder. If you don't call `FindClose` over the handle returned from `FindFirstFileA`, you would have a handle and associated memory leak.
