### ISSUE TITLE
Segment fault on tonumber call

### ISSUE THREAD

**Issue by fengyd2006** [LuaJIT/LuaJIT#1019]
Here's a segmentation fault related to tonumber call.

According to backtrace,  the parameter for tonumber is a string? 
It's not cdata?
Then under what situation a string will be released?

> (gdb) bt
> #0  0x00038ddc in lj_strscan_number (str=0x8, o=o@entry=0x754d52e0)
>     at lj_strscan.c:546
> #1  0x0005c37c in lj_strscan_numberobj (o=0x754d52e0) at lib_base.c:313
> #2  lj_ffh_tonumber (L=0x759529e8) at lib_base.c:268
> #3  0x00032570 in lj_fff_fallback ()
> #4  0x00031998 in lj_ff_coroutine_resume ()
> #5  0x00031998 in lj_ff_coroutine_resume ()
> #6  0x00031998 in lj_ff_coroutine_resume ()
> #7  0x00031998 in lj_ff_coroutine_resume ()
> #8  0x0001ed98 in lua_pcall (L=L@entry=0x76d281c8, nargs=nargs@entry=0,
>     nresults=nresults@entry=-1, errfunc=errfunc@entry=2) at lj_api.c:1145
> #9  0x00013e9c in docall (L=0x76d281c8, narg=0, clear=0) at luajit.c:122
> #10 0x00014c60 in handle_script (argx=<optimized out>, L=0x76d281c8)
>     at luajit.c:292
> #11 pmain (L=0x76d281c8) at luajit.c:550
> #12 0x00030e0c in lj_BC_FUNCC ()
> #13 0x0001edc8 in lua_cpcall (L=L@entry=0x76d281c8,
>     func=func@entry=0x144a4 <pmain>, ud=ud@entry=0x0) at lj_api.c:1173
> #14 0x000139b8 in main (argc=2, argv=0x7ecffe44) at luajit.c:581

Thanks

**Comment by MikePall** [comment]
All of your reports are similarly useless. You never show code, you never show a reproducible test case. It's very clear you are unable to write correct code for the FFI, since you haven't even grasped the basics of Lua (see #1017). You don't even know how to properly quote code or backtraces here on Github. Good bye.
