### ISSUE TITLE
Unprotected panic error on arm64-macos when used with C++

### ISSUE THREAD

**Issue by JCash** [LuaJIT/LuaJIT#1020]
I cannot seem to get luajit arm64-macos version to work with my C++ code as it throws the `PANIC: unprotected error in call to Lua API` error and exits the app.

It works if I remove the `-fno-exceptions` from the command line.

This is on latest version `ff6c496b`.

Repro:
```
MACOSX_DEPLOYMENT_TARGET=10.13 make clean
MACOSX_DEPLOYMENT_TARGET=10.13 make -j8

clang++ \
    -std=c++11 \
    -g \
    -fno-exceptions \
    -I./src \
    -lluajit \
    -L./src \
    ./test.cpp \
    -o./test_cpp
    
./test_cpp
```

test.cpp:
```
extern "C"
{
    #include <lua.h>
    #include <lauxlib.h>
    #include <lualib.h>
}

static int custom_func(lua_State* L)
{
    return luaL_error(L, "Error from func!");
}

int main(int argc, char **argv)
{
    lua_State* L = luaL_newstate();
    luaL_openlibs(L);

    int status = lua_cpcall(L, &custom_func, 0);
    if (status) {
        fprintf(stderr, "Caught error: %s\n", lua_tostring(L, -1));
        return 1;
    }
    return 0;
}
```

Output:
```
PANIC: unprotected error in call to Lua API (Error from func!)
```

**Comment by MikePall** [comment]
Well ... what do you expect to happen when you use `-fno-exceptions`, but then you _do_ throw an exception?

Throwing a Lua error in LuaJIT is equivalent to throwing a C++ exception (on all modern platforms). That's called exception interoperability and the v2.1 docs have a really nice table that explains what happens.

**Comment by JCash** [comment]
I'm sorry, but I didn't think I _was_ throwing an exception.
I didn't interpret the line "LuaJIT has built-in support for interoperating with C++ exceptions" as that Lua errors themselves are actually exceptions (I was thinking more like longjmp) ([doc](https://luajit.org/extensions.html))

The fact that we've been using the `pcall()` + `-fno-exception` for so long I guess made me look no further.
Also we're using clang++ for arm64 android, which also threw me off.

In any case, I guess my options are limited. Either turn on exception handling (increases code size), or use vanilla Lua (slower).
