### ISSUE TITLE
"error" function does not work when passed no arguments or nil

### ISSUE THREAD

**Issue by BAKAOLC** [LuaJIT/LuaJIT#1021]
When I execute the following code in Luajit, this function does not perform any behavior and cannot throw an error normally:

```lua
error() -- no effect
error(nil) -- no effect
error("error!") -- throw a error with message "error!"
```

In Lua's original behavior, it should look like this:

```lua
error()
-- it should throw an error message like this:
--[[
(error object is a nil value)
stack traceback:
        [C]: in function 'error'
        stdin:1: in main chunk
        [C]: in ?
--]]
```

I want to ask if this is by design? Because the error reporting of empty messages is a behavior with little meaning, a normal and reasonable design should provide detailed error information instead of simply throwing an exception directly.

**Comment by MikePall** [comment]
LuaJIT is compatible with Lua 5.1. The behaviour is the same there.
In both cases a `nil` error is actually thrown. But the 5.1-compatible `report()` function (in the Lua/LuaJIT executable) ignores `nil` errors. It _does_ exit the process with an error code, though.
With your own executable or a `pcall()` around your code you can change that behaviour.
