### ISSUE TITLE
Possible to move `ffi.cast` to c side?

### ISSUE THREAD

**Issue by bear24rw** [LuaJIT/LuaJIT#1027]
My application is currently bottlenecked on this stack:

```
lua_pcall
ffi_checkctype
cp_next
lj_str_new
```

I believe this is from my usage of `ffi.cast`.

Lua code:

```lua
local ffi = require "ffi"
function foo(dst_p, src_p, size)
    local dst = ffi.cast("double*", dst_p);
    local src = ffi.cast("double*", src_p);
    for i = 0, size-1 do
        dst[i] = src[i] * 1000
    end
end
```

C code:

```c
              double dst[1000];
              double src[1000];

              // Fill out src

              lua_getglobal(m_lua, "foo");
              lua_pushlightuserdata(m_lua, (void*)dst);
              lua_pushlightuserdata(m_lua, (void*)src);
              lua_pushinteger(m_lua, 1000);
              if (lua_pcall(m_lua, 3, 0, 0) != LUA_OK) {
                 printf("Failed %s\n",  lua_tostring(m_lua, -1));
                  lua_pop(m_lua, -1);
                  return;
              }
```

Is it possible to move the casting to the c side somehow (where i can maybe cache it?) so that i don't have to re-cast it inside of lua every time?

**Comment by bear24rw** [comment]
I believe using `ffi.typeof` allows me to cache the type parsing, im getting much better performance now with

```lua
local ffi = require "ffi"
local double_ptr_t = ffi.typeof("double*")
function foo(dst_p, src_p, size)
    local dst = ffi.cast(double_ptr_t, dst_p);
    local src = ffi.cast(double_ptr_t, src_p);
    for i = 0, size-1 do
        dst[i] = src[i] * 1000
    end
end
```

Is there any additional performance improvements that could be made beyond this?

**Comment by MikePall** [comment]
First: Repeatedly calling into the VM from C code is expensive. You should minimize this by running inside Lua code most of the time and only calling out to C code via the FFI, where needed.

That said, you could try to create a callback function: cast the Lua function to a C function pointer once and pass it to the C code. This already creates the right types, no cast needed. Also you don't need to mess with the classic Lua/C API, you can just call the C function pointer.

**Comment by bear24rw** [comment]
Oh wow I didn't realize you could get a function pointer to the lua function! Is that documented explicitly anywhere? Virtually every result on google is talking about the other direction (getting function pointer to a c function from within lua).

Here's what I came up with, seems to work!

Lua:
```lua
local ffi = require "ffi"
ffi.cdef[[
    typedef void (*MyFunction)(double*, double*, uint32_t);
    void register_foo(MyFunction);
]]
local my_function_t = ffi.typeof(MyFunction)

function foo(dst, src, size)
    for i = 0, size-1 do
        dst[i] = src[i] * 1000
    end
end
local foo_ptr = ffi.cast(my_function_t, foo)
ffi.C.register_foo(foo_ptr)
```

C:
```c
typedef void (*MyFunction)(double*, const double*, uint32_t);
MyFunction foo;
void register_foo(MyFunction f) {
    foo = f;
}

double dst[1000];
double src[1000];
// Fill out src
foo(dst, src, 1000);
```
