### ISSUE TITLE
Expensive unwinding from lj_trace_err

### ISSUE THREAD

**Issue by bobrik** [LuaJIT/LuaJIT#1029]
Some time ago we updated from Debian Bullseye to Debian Bookworm and one of our services (nginx + luajit) became considerably slower. We traced it down to libunwind changes in Debian that caused more expensive unwinding:

<img width="1552" alt="image" src="https://github.com/LuaJIT/LuaJIT/assets/89186/d7da97c4-8347-44c7-bc88-8ea7fe677a17">

We fixed it by switching back to our internal build that uses libgcc for unwinding, which fixed the issue.

However, this made me wonder why we need to unwind at all. Even with faster unwinding it was still very much visible in flamegraphs, taking 1-2% of CPU time of the service. Here's a couple of common paths:

<img width="1552" alt="image" src="https://github.com/LuaJIT/LuaJIT/assets/89186/3134a65a-fb07-418f-8680-6c14b8772e16">

<img width="1552" alt="image" src="https://github.com/LuaJIT/LuaJIT/assets/89186/75445d44-cffb-4e39-84c3-dc3483682550">

I checked the reasons why errors were thrown, here's the annotated list:

```
$ sudo bpftrace -e 'uprobe:/usr/local/bin/service:lj_trace_err { @errors[arg1]++ } interval:s:10 { exit() }'
    Attaching 2 probes...

    @errors[13]:    1       LJ_TRERR_CUNROLL    call unroll limit reached
    @errors[30]:    4       LJ_TRERR_SPILLOV    too many spill slots
    @errors[22]:    4       LJ_TRERR_NYICONV    NYI: unsupported C type conversion
    @errors[4]:     8       LJ_TRERR_SNAPOV     too many snapshots
    @errors[26]:    13      LJ_TRERR_TYPEINS    persistent type instability
    @errors[14]:    17      LJ_TRERR_DOWNREC    down-recursion, restarting
    @errors[29]:    93      LJ_TRERR_MCODELM    hit mcode limit (retrying)
    @errors[2]:     101     LJ_TRERR_TRACEOV    trace too long
    @errors[12]:    674     LJ_TRERR_CJITOFF    JIT compilation disabled for function
    @errors[34]:    1519    LJ_TRERR_NYICOAL    NYI: register coalescing too complex
    @errors[23]:    18924   LJ_TRERR_NYICALL    NYI: unsupported C function type
    @errors[16]:    19685   LJ_TRERR_NYIRETL    NYI: return to lower frame
    @errors[9]:     30154   LJ_TRERR_LINNER     inner loop in root trace
    @errors[8]:     51098   LJ_TRERR_LLEAVE     leaving loop in root trace
    @errors[5]:     68818   LJ_TRERR_BLACKL     blacklisted
```

We don't use `luaL_error`, so we don't expect unwinding to do anything useful for RAII (C++ or Rust):

* https://stackoverflow.com/questions/4005865/stack-unwinding-in-c-when-using-lua

We don't throw exceptions across C++ and Lua borders either.

This problem is very much x86_64 specific. On aarch64 machines where internal unwinding is used instead of libunwind/libgcc we see a lot less time spent in unwinding. Through some trial and error I figured out that x86_64 does not support internal unwinding.

Given that we presumably don't benefit from unwinding in our setup, my next option was to disable it completely, so I've tried building luajit with `-DLUAJIT_NO_UNWIND`. Unfortunately, this broke stack unwinding in `perf`, which broke our flamegraphs.

I made the following patch to keep perf working, but disable unwinding in luajit:

```diff
diff --git a/src/lj_err.c b/src/lj_err.c
index 83118551..9217d26b 100644
--- a/src/lj_err.c
+++ b/src/lj_err.c
@@ -184,6 +184,12 @@ static void *err_unwind(lua_State *L, void *stopcf, int errcode)
 
 /* -- External frame unwinding -------------------------------------------- */
 
+LJ_FUNCA int lj_err_unwind_dwarf(int version, int actions,
+  uint64_t uexclass, void *uex, void *ctx)
+{
+  return 0;
+}
+
 #if defined(__GNUC__) && !LJ_NO_UNWIND && !LJ_ABI_WIN
 
 /*
diff --git a/src/vm_x64.dasc b/src/vm_x64.dasc
index a003fb4f..41159fad 100644
--- a/src/vm_x64.dasc
+++ b/src/vm_x64.dasc
@@ -4733,7 +4733,7 @@ static void emit_asm_debug(BuildCtx *ctx)
 	"\t.align 8\n"
 	".LEFDE1:\n\n", (int)ctx->codesz - fcofs);
 #endif
-#if !LJ_NO_UNWIND
+#if 1
 #if (defined(__sun__) && defined(__svr4__))
     fprintf(ctx->fp, "\t.section .eh_frame,\"a\",@unwind\n");
 #else
@@ -4806,7 +4806,7 @@ static void emit_asm_debug(BuildCtx *ctx)
 #endif
 #endif
     break;
-#if !LJ_NO_UNWIND
+#if 1
   /* Mental note: never let Apple design an assembler.
   ** Or a linker. Or a plastic case. But I digress.
   */

```

I'm by no means expert in this, so I made a dummy version of `lj_err_unwind_dwarf` to make it compile. There is probably a better way to achieve this.

In my production testing I was able to see ~2% uplift in throughput in a synthetic test. It gets a bit murkier with production data, but I can definitely see at least 1% increase in requests per consumed CPU with no apparent adverse effects.

My questions are:

1. Is it expected that so much time is spent unwinding trace errors?
2. Is `-DLUAJIT_NO_UNWIND` safe in my setup (no exceptions across FFI border, no `luaL_error`)? It would be good to have some documentation explaining the need for unwinding and what happens if you have it disabled.
3. Can luajit provide a build flag to achieve what I've done in a supported way? Something like `-DLUAJIT_KEEP_EH_FRAME`.

**Comment by MikePall** [comment]
Improving unwinding speed is only trying to alleviate the symptoms. I think it would be helpful to try to find the actual cause, which is in your Lua code.

It's not normal if the JIT compiler spends that much time a) compiling and b) aborting traces. The whole JIT engine should be close to invisible in those graphs.

The high number of BLACKL are suspicious, because they should be finite -- there's only so much code that can be blacklisted (once). A couple LINNER, LLEAVE and some NYI can be normal, but they should converge to a stable state after the initial compiling frenzy.

Also check for any changes that OpenResty made vs. the LuaJIT upstream. I always have to undo them before any OpenResty install.

**Comment by bobrik** [comment]
> Improving unwinding speed is only trying to alleviate the symptoms. I think it would be helpful to try to find the actual cause, which is in your Lua code.

That's certainly one way of approaching this. However, I am also interested in having the answers for my second and third question. Having working `perf` and luajit that does not unwind by itself seems like a reasonable thing.

> It's not normal if the JIT compiler spends that much time a) compiling and b) aborting traces. The whole JIT engine should be close to invisible in those graphs.
> The high number of BLACKL are suspicious, because they should be finite -- there's only so much code that can be blacklisted (once). A couple LINNER, LLEAVE and some NYI can be normal, but they should converge to a stable state after the initial compiling frenzy.

I completely agree. Is there a document describing how to debug this sort of issue? I'm a bit lost on how to approach this.

> Also check for any changes that OpenResty made vs. the LuaJIT upstream. I always have to undo them before any OpenResty install.

We are not using OpenResty LuaJIT, but our internal fork is somewhat out of date. I'm checking if we can do a rebase to minimize the difference to see if it improves anything here.
