### ISSUE TITLE
openwert  Error: pointer size mismatch in cross-build.

### ISSUE THREAD

**Issue by vpei** [LuaJIT/LuaJIT#1035]
make[3]: Entering directory '/home/openwrt-5-x86/feeds/packages/lang/luajit'
rm -f /home/openwrt-5-x86/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/.built
touch /home/openwrt-5-x86/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/.built_check
make -j1 -C /home/openwrt-5-x86/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3 HOST_CC="gcc -O2 -I/home/openwrt-5-x86/staging_dir/host/include -I/home/openwrt-5-x86/staging_dir/hostpkg/include -I/home/openwrt-5-x86/staging_dir/target-x86_64_musl/host/include " CROSS="x86_64-openwrt-linux-musl-" DPREFIX=/home/openwrt-5-x86/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/ipkg-install/usr PREFIX=/usr TARGET_SYS=Linux TARGET_CFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/home/openwrt-5-x86/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3=LuaJIT-2.1.0-beta3 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" BUILDMODE=dynamic
make[4]: Entering directory '/home/openwrt-5-x86/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3'
==== Building LuaJIT 2.1.0-beta3 ====
make -C src
make[5]: Entering directory '/home/openwrt-5-x86/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/src'
BUILDVM   lj_vm.S
Error: pointer size mismatch in cross-build.
Try: make HOST_CC="gcc -m32" CROSS=...

make[5]: *** [Makefile:646: lj_vm.S] Error 1
make[5]: Leaving directory '/home/openwrt-5-x86/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/src'
make[4]: *** [Makefile:113: default] Error 2
make[4]: Leaving directory '/home/openwrt-5-x86/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3'
make[3]: *** [Makefile:92: /home/openwrt-5-x86/build_dir/target-x86_64_musl/LuaJIT-2.1.0-beta3/.built] Error 2
make[3]: Leaving directory '/home/openwrt-5-x86/feeds/packages/lang/luajit'
time: package/feeds/packages/luajit/compile#1.49#1.18#2.29
    ERROR: package/feeds/packages/luajit failed to build.
make[2]: *** [package/Makefile:120: package/feeds/packages/luajit/compile] Error 1
make[2]: Leaving directory '/home/openwrt-5-x86'
make[1]: *** [package/Makefile:114: /home/openwrt-5-x86/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/openwrt-5-x86'
make: *** [/home/openwrt-5-x86/include/toplevel.mk:232：world] Error 2

**Comment by sindrom91** [comment]
Your host is 32 bit and your target is 64 bit? I'm not sure if that's supported at all. Maybe try adding `-m64` to `HOST_CC`.

**Comment by MikePall** [comment]
The [cross-compile documentation](https://luajit.org/install.html#cross) states the requirement for a matching 32/64 bit host/target.
