### ISSUE TITLE
Cannot build LuaJIT on Windows via msvcbuild.bat

### ISSUE THREAD

**Issue by TracerDS** [LuaJIT/LuaJIT#1037]
The title says everything. I can only build dynamic library via mingw32-make but thats all. 
As you can see on the screenshot I have VS CMD prompt open but it just wont build.

Error in text form: `You must open a "Visual Studio Command Prompt" to run this script`

1. Reinstalling VisualStudio didnt help
2. Installing some shady, helper tools for VisualStudio didnt either
3. Modifying `Makefile` to manually build static lib causes more harm than good
4. Yes, `cl.exe` and other tools are visible and I can execute them freely
5. No, `cd` and executing `msvcbuild.bat` directly in the `src` folder didnt help

![image](https://github.com/LuaJIT/LuaJIT/assets/43095317/ecc38d6c-2159-467f-8c45-649ea9da3480)
![image](https://github.com/LuaJIT/LuaJIT/assets/43095317/262111e5-5030-4d24-8ab1-05541553f9a6)

**Comment by labrax** [comment]
I don't know lots of this package but it seems that your developer command prompt does not have all the needed environment variables. In msvcbuild.bat:
```
@if not defined INCLUDE goto :FAIL
...
:FAIL
@echo You must open a "Visual Studio Command Prompt" to run this script
```

**Comment by TracerDS** [comment]
> I don't know lots of this package but it seems that your developer command prompt does not have all the needed environment variables. In msvcbuild.bat:
> ```
> @if not defined INCLUDE goto :FAIL
> ...
> :FAIL
> @echo You must open a "Visual Studio Command Prompt" to run this script
> ```

Thats all i know too.

**Comment by TracerDS** [comment]
I was making an attempt to compile jit directly from visual studio (create new project, add jit files to it, compile) but that was a big mistake. Jit is missing a lot of definitions (string.len, string.rep, whole jit profiler) thus resulting in errors during compilation.
Im currently stuck. I could just use dynamic lib from `make` but in my case i need to use a static lib. `make` sadly doesnt compile to a static lib

**Comment by tsafin** [comment]
@TracerDS as uou can see from the `msvcbuild.bat` script this error is reported iff there is no `%INCLUDE%` environment variable defined inside of `vsvars*.bat` (`VsDevCmd.bat`) shell. To make sure that everything is properly configured after running of VS Developer Command Prompt you may check it via `echo %INCLUDE%`:

```
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.5.4
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

C:\Program Files\Microsoft Visual Studio\2022\Community>echo %INCLUDE%
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\ATLMFC\include;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include;C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt
```

**Comment by TracerDS** [comment]
> @TracerDS as uou can see from the `msvcbuild.bat` script this error is reported iff there is no `%INCLUDE%` environment variable defined inside of `vsvars*.bat` (`VsDevCmd.bat`) shell. To make sure that everything is properly configured after running of VS Developer Command Prompt you may check it via `echo %INCLUDE%`:
> 
> ```
> **********************************************************************
> ** Visual Studio 2022 Developer Command Prompt v17.5.4
> ** Copyright (c) 2022 Microsoft Corporation
> **********************************************************************
> [vcvarsall.bat] Environment initialized for: 'x64'
> 
> C:\Program Files\Microsoft Visual Studio\2022\Community>echo %INCLUDE%
> C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include;
> C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\ATLMFC\include;...
> ;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt
> ```

Im currently investigating this issue. Looks like newest VS installation doesnt provide this env variable anywhere in the bat files

**Comment by MikePall** [comment]
Is this an isolated issue with a particular installation or has there been a general change by MS?

The question is: what alternate means do we have to detect that the correct paths and environment variables are set? I.e. that it's invoked from the correct command prompt. And if not, then give a helpful message.

Otherwise the script invocation yields an undecipherable stream of error messages. This will likely cause a flurry of did-not-read-the-manual bug reports.

**Comment by kennethrapp** [comment]
Here is how I do it - you need to run either the x64 or x86 command tools prompt for Visual Studio - there is no need to open anything in VS itself. Loading one of these prompts should load all necessary environment variables. You should be able to find the shortcuts for these under the Visual Studio folder in the startup menu:

![Clipboard01](https://github.com/LuaJIT/LuaJIT/assets/665097/e9e00c94-ce98-4575-a5f5-b73826e91a0d)

Then cd into the necessary folder and build from the prompt. 

I prefer to copy the shortcut files and paste them into a folder where i have the luajit source code, then add the build command through the target field of the properties dialog, so that I only need to click on the shortcut to run the build.

![Clipboard02](https://github.com/LuaJIT/LuaJIT/assets/665097/499a6ee9-5b22-4ed0-b6bd-13bc2fefd673)

Hope this helps.

**Comment by TracerDS** [comment]
> Here is how I do it - you need to run either the x64 or x86 command tools prompt for Visual Studio - there is no need to open anything in VS itself. Loading one of these prompts should load all necessary environment variables. You should be able to find the shortcuts for these under the Visual Studio folder in the startup menu:
> 
> ![Clipboard01](https://user-images.githubusercontent.com/665097/260687266-e9e00c94-ce98-4575-a5f5-b73826e91a0d.png)
> 
> Then cd into the necessary folder and build from the prompt.
> 
> I prefer to copy the shortcut files and paste them into a folder where i have the luajit source code, then add the build command through the target field of the properties dialog, so that I only need to click on the shortcut to run the build.
> 
> ![Clipboard02](https://user-images.githubusercontent.com/665097/260687776-499a6ee9-5b22-4ed0-b6bd-13bc2fefd673.png)
> 
> Hope this helps.

that's the issue: cmd tools don't load up required variables (including `INCLUDE` variable) due to some VS update I'd guess.

**Comment by TracerDS** [comment]
> Is this an isolated issue with a particular installation or has there been a general change by MS?
> 
> The question is: what alternate means do we have to detect that the correct paths and environment variables are set? I.e. that it's invoked from the correct command prompt. And if not, then give a helpful message.
> 
> Otherwise the script invocation yields an undecipherable stream of error messages. This will likely cause a flurry of did-not-read-the-manual bug reports.

reinstall didn't help so I'd guess a general change

**Comment by MikuAuahDark** [comment]
Maybe it was a bug in v17.6.4. I'm using Developer Command Prompt v17.6.5 and `%INCLUDE%` environment variable is available.

**Comment by MikePall** [comment]
Closing, since we have two conflicting reports here. And I do not see an easy solution for the failing case.
Will reopen if there are more reports.

**Comment by TracerDS** [comment]
Adding more info to it: VS's vcpkg caused this issue.
Removing vcpkg package from VisualStudio and installing it directly fixed the issue.
Just Windows things i guess
