### ISSUE TITLE
Where can I see the latest NYI list?

### ISSUE THREAD

**Issue by AlwaysYng** [LuaJIT/LuaJIT#1039]
I noticed that the NYI page on Luajit's official website has been removed (http://wiki.luajit.org/NYI). Does that mean all features have been implemented? If not, where can I find the latest NYI list? Thanks a lot!

**Comment by AlwaysYng** [comment]
Unfortunately, the performance guide page (http://wiki.luajit.org/Numerical-Computing-Performance-Guide) has also been removed.

**Comment by MikePall** [comment]
Dup of #902
