### ISSUE TITLE
vm_mips.dasc assumes 32-bit FPU register model

### ISSUE THREAD

**Issue by corsix** [LuaJIT/LuaJIT#1040]
The implementations of `lj_vm_floor` and `lj_vm_ceil` in `vm_mips.dasc` contain `mtc1` / `mfc1` against `f5` and `f13`, in attempts to refer to the high 32-bits of the double-precision values in `f4` and `f12`:
https://github.com/LuaJIT/LuaJIT/blob/8635cbabf3094c4d8bd00578c7d812bea87bb2d3/src/vm_mips.dasc#L2531-L2571

Per https://s3-eu-west-1.amazonaws.com/downloads-mips/documents/MD00082-2B-MIPS32INT-AFP-06.01.pdf page 85, the FPU can be configured in one of two ways:
- `FR=0`: FPU registers are 32 bits wide, even/odd pairs used for representing double-precision values, so only 16 double-precision values can be stored in the 32 FPRs
- `FR=1`: FPU registers are 64 bits wide, so 32 double-precision values can be stored in the 32 FPRs

The referenced code is assuming `FR=0`, and badly misbehaves when `FR=1` (as then the accesses are _not_ to the high 32-bits of the double-precision values in `f4` and `f12`).

Per https://web.archive.org/web/20180828210612/https://dmz-portal.mips.com/wiki/MIPS_O32_ABI_-_FR0_and_FR1_Interlinking, this assumption can be codified by the `.module fp=32` assembly directive:
```diff
--- a/src/host/buildvm_asm.c
+++ b/src/host/buildvm_asm.c
@@ -270,6 +270,9 @@ void emit_asm(BuildCtx *ctx)
 #endif
 #endif
 #if LJ_TARGET_MIPS
+#if !LJ_ABI_SOFTFP
+  fprintf(ctx->fp, ".module fp=32\n");
+#endif
   fprintf(ctx->fp, ".set nomips16\n.abicalls\n.set noreorder\n.set nomacro\n");
 #endif
```

If MIPS32R2 could be assumed, then `mthc1` / `mfhc1` (against even FPRs) could be used instead of `mtc1` / `mfc1` (against odd FPRs), and then the value of `FR` should be irrelevant. MIPS32R6 disallows `FR=0`, so perhaps `mthc1` / `mfhc1` is the way to go if we can detect R2 or above at compile-time.

Notably, with a recent qemu, installing a recent Debian in `qemu-system-mipsel -M malta` and building LuaJIT gives rise to an binary which executes in `FR=1` mode, and thus misbehaves. The above diff seems to fix this.

**Comment by MikePall** [comment]
I've made it conditional for MIPS32. Otherwise it breaks MIPS64. Thanks!

On real hardware this would only be an issue for certain MIPS64 CPUs when run in MIPS32 mode. That's uncommon and they are going extinct, anyway.

There's still a surprising number of MIPS32 4kc CPUs on the market (inside $10 access points). But they don't have an FPU.
