### ISSUE TITLE
Odd CHECK_int behaviours

### ISSUE THREAD

**Issue by corsix** [LuaJIT/LuaJIT#1042]
In v2.1, the `table.move` and `table.remove` functions are implemented in (extended) bytecode, making use of `CHECK_int`.

On DUALNUM builds, this gets turned into `BC_ISTYPE int`. On !DUALNUM builds, `buildvm_lib.c` rewrites this to `BC_ISNUM num`. This means that if end-users call `string.dump` on either of these functions, the resultant bytecode is not portable between DUALNUM/!DUALNUM systems. In one direction, this can can assertion failures:
```
$ luajit_dualnum -e 'io.open("bc_dualnum.dat","wb"):write(string.dump(table.remove))'
$ luajit_singlenum -e 'tr=loadfile("bc_dualnum.dat") tr({},true)'
LuaJIT ASSERT lj_meta.c:434: lj_meta_istype: bad type for ISTYPE
Abort trap: 6
```
In the other, it can cause misbehaviour:
```
$ luajit_singlenum -e 'io.open("bc_singlenum.dat","wb"):write(string.dump(table.remove))'
$ luajit_dualnum -e 'tr=loadfile("bc_singlenum.dat") t={"a","b","c"} print(tr(t,2.0000000000000004)) for k,v in pairs(t) do print(k,v) end'
a
1	a
2	b
```

This last example is interesting, in that even without bytecode dumping / restoration, it gives different behaviour on DUALNUM versus !DUALNUM (both of which are different to the previously shown transplanted-bytecode behaviour, and the DUALNUM behaviour here matches Lua 5.1):
```
$ luajit_dualnum -e 't={"a","b","c"} print(table.remove(t,2.0000000000000004)) for k,v in pairs(t) do print(k,v) end'
b
1	a
2	c
```
```
$ luajit_singlenum -e 't={"a","b","c"} print(table.remove(t,2.0000000000000004)) for k,v in pairs(t) do print(k,v) end'
b
1	a
2	b
```

It strikes me that both issues could be resolved by always generating the `BC_ISTYPE int` bytecode, and having the implementation of this on !DUALNUM canonicalise numeric values to 32-bit integers (as is done on DUALNUM).

Alternatively, you could deploy the "if it hurts, don't do it" argument vis-a-vis transplanting bytecode of builtins and/or passing not-quite-integers to `table.move` and `table.remove`.

(In case it matters, this is 8635cbabf309, with luajit_dualnum being an ARM64 build, and luajit_singlenum being an x64 build via Rosetta 2)

**Comment by MikePall** [comment]
I *do* subscribe to the "if it hurts, don't do it" argument here. :-)
