### ISSUE TITLE
Wrong J->maxslot for single-result BC_VARG

### ISSUE THREAD

**Issue by corsix** [LuaJIT/LuaJIT#1046]
`BC_VARG` can deliver some number of varargs to the top of the stack, or it can deliver a single result to anywhere in the stack. The handling of `J->maxslot` in `rec_varg` assumes we're always in the former case, leading to potential misbehaviour if we're in the latter case.

This causes failures of the following two examples:
```lua
-- varargs defined on-trace
local function f1(i, j, k, ...)
    i = ...
    if j >= k then assert(j >= k) end
end
for j = 1, 60 do
    f1(nil, j, 59)
end

-- varargs passed to trace
local function f2(...)
    local i
    local k = 59
    for j = 1, 60 do
        i = ...
        if j >= k then assert(j >= k) end
    end
end
f2()
```

Possible fix sitting at https://github.com/corsix/LuaJIT/commits/varg-maxslot

**Comment by MikePall** [comment]
Fixed. Thanks!
