### ISSUE TITLE
pcall as metamethod can overflow stack

### ISSUE THREAD

**Issue by corsix** [LuaJIT/LuaJIT#1048]
`pcall` has two separate ways by which it can grow the stack by one slot:
1. Resolving the `__call` metamethod of its first argument
2. In LJ_FR2 mode, it always grows the stack by one slot

The first of these points leads to a stack smash if `pcall` is used as `__call`: `setmetatable({},{__call=pcall})()` will cause an infinite loop which fills up the stack with pcall frames and then keeps going beyond the end of the stack until it segfaults.

Either of these points can cause an issue if `pcall` is used as `__newindex`: `LJ_STACK_EXTRA` gets fully utilised by a vanilla `__newindex` metamethod call, and growing the stack by one takes you to `LJ_STACK_EXTRA+1`. This is _usually_ fine, given that there actually are `LJ_STACK_EXTRA+1` spare slots allocated (though that `+1` might be reserved for something else, such as throwing an error), but hitting both points takes you to `LJ_STACK_EXTRA+2`, which is definitely not fine, as it can write one slot beyond the end of the allocated stack. Accordingly, the following can segfault in LJ_FR2 mode:
```lua
local t = setmetatable({}, {__newindex = pcall, __call = pairs})
local function prober(...)
    local v0, v1, v2, v3, v4, v5, v6, v7, v8, v9
    local v10, v11, v12, v13, v14, v15, v16, v17, v18, v19
    t[t] = t
end
local function looper(n, ...)
    --print(n)
    prober(...)
    prober(nil, ...)
    return looper(n+1, n, ...)
end
pcall(coroutine.wrap(looper), 0)
```

The above example also hits a third problem on arm64 (and I think mips64): the stack check in `BC_IFUNCV` is off by one. They grow the stack if `BASE+framesize*8+nargs*8 >= L->maxstack`, a notable difference to x64's growth if `BASE+(nargs+1)*8+8+framesize*8 > L->maxstack`.

**Comment by corsix** [comment]
It strikes me that in LJ_FR2 mode, metamethods aren't required; the following can overflow the stack:
```lua
local function prober(...)
    local v0, v1, v2, v3, v4, v5, v6, v7, v8, v9
    local v10, v11, v12, v13, v14, v15, v16, v17, v18, v19
    pcall(pcall, pcall, pcall, pcall, pcall, pcall, pcall, pcall, pairs, {})
end
local function looper(n, ...)
    print(n)
    prober(...)
    prober(nil, ...)
    return looper(n+1, n, ...)
end
pcall(coroutine.wrap(looper), 0)
```

**Comment by corsix** [comment]
The off-by-one issue in `BC_IFUNCV` is seemingly replicated in `lj_dispatch.c:call_init`: `if ((pt->flags & PROTO_VARARG)) need += 1+gotparams;` should presumably be `if ((pt->flags & PROTO_VARARG)) need += 1+LR_FR2+gotparams;`. For a while I thought that `call_init` was fine, as the real `BC_IFUNCV` handler would repeat the stack check with the proper value before doing its stack manipulation, but there's a wrinkle: if `BC_IFUNCV` fails a stack check, it'll repeat the opcode, which'll play merry hell with recording if we happen to be recording at that moment (the TLDR being that `call_init` needs to perform a stack check that is at least as aggressive as the real handler).

As yet another issue, affecting all FR2 interpreters (x64, arm64, mips64), this bit from the previous paragraph isn't quite true:
> `BC_IFUNCV` handler would repeat the stack check with the proper value before doing its stack manipulation

The handlers seem to write a frame link (2 slots) to the stack, _then_ do a stack check (and then do the rest of their stack manipulation). The problem is that there might not be 2 free slots: if the handler for `__newindex` is a vararg function, then during `BC_IFUNCV`, all of `LJ_STACK_EXTRA` might already be spent, and so writing the frame link takes us to `LJ_STACK_EXTRA+2`. The FR2 versions of `BC_IFUNCV` either need to do their stack checks slightly earlier, or we need to allocate yet another extra slot.

**Comment by corsix** [comment]
So I think the conclusions are:
- arm64/mips64 `BC_IFUNCV` and `LR_FR2` `lj_dispatch.c:call_init` `PROTO_VARARG`: off-by-one in stack check. Justification should be clear.
- `LR_FR2` implementations of `BC_IFUNCV`: need to perform stack check _before_ writing high half of frame link (or bump LJ_STACK_EXTRA by 1 to give them space to write the entire frame link). Justification: vararg function as `__newindex`.
- `LR_FR2` implementations of pcall/xpcall: need to perform a stack check. Justification: pcall which directly calls pcall a few times can otherwise blow the stack. Alternative justification: `__newindex` set to pcall and `__call` set to a vararg function. Third justification: `__call` set to pcall (which is a somewhat silly thing to do, but ideally it wouldn't segfault).
- `!LR_FR2` implementations of pcall/xpcall: need to perform a stack check if they end up doing `lj_meta_call`. Same `__newindex` and/or `__call` justifications as previous.

**Comment by MikePall** [comment]
A stack check in pcall/xpcall would penalize the fast path. I'd rather do it in or around the metamethod handlers. The question is: which of them are affected?

**Comment by corsix** [comment]
If LJ_STACK_EXTRA is bumped sufficiently, and we ignore `pcall(pcall, pcall, ...` on LJ_FR2, then `__call` is the only metamethod handler that needs to be looked at. I think `1+LJ_FR2` is a sufficient bump, as the worst case is `__newindex` (consuming all of the current LJ_STACK_EXTRA), which ends up calling `xpcall`/`pcall`, which in turn hits a `__call`.

There's a commit at https://github.com/corsix/LuaJIT/commits/meta_call_pcall which slips the logic into `lj_meta_call`, though there's a decent amount of flexibility in exactly what/how to slip in.

**Comment by MikePall** [comment]
I've taken the smaller side-issue fixes. Thanks!

That meta_call_pcall patch looks adventurous, for sure. I'll have to think about a better solution.

**Comment by MikePall** [comment]
After the simple fix, I have difficulties coming up with a crashing testcase for the remaining issues you've mentioned.

**Comment by corsix** [comment]
This guy remains problematic:
```lua
setmetatable({},{__call=pcall})()
```
As does this for FR2:
```lua
for i = 1, 245 do
  local code = "return pcall(X pairs,{})"
  local f = load(code:gsub("X", ("pcall,"):rep(i)), "=code")
  coroutine.wrap(f)()
end
```
(Git head, i.e. 07b3cd3cf9b, macOS arm64, `-DLUA_USE_ASSERT`)

**Comment by MikePall** [comment]
I've added a stack check to `pcall` and `xpcall`. The overhead for the interpreter is minimal. Or zero on out-of-order CPUs.
Thanks!
