### ISSUE TITLE
Typo in Makefile removing symlink

### ISSUE THREAD

**Issue by sjcooke** [LuaJIT/LuaJIT#1051]
Commit https://github.com/LuaJIT/LuaJIT/commit/093759d528a9c3f1b69c1ff5fd46b5f52fc4d9aa appears to contain a typo in the variable name: "INSTALL_TYSM" should be "INSTALL_TSYM" on line 150 of Makefile.

**Comment by MikePall** [comment]
Fixed. Thanks!
