### ISSUE TITLE
luajit trigger the ASSERT in aarch64

### ISSUE THREAD

**Issue by caohongqing** [LuaJIT/LuaJIT#1055]
OS: centos 7.6
ARCH: aarch64(ARM)

My process occasionally was aborted by luajit. It printed "LuaJIT ASSERT lj_opt_narrow.c:600: lj_opt_narrow_forl: expected number type"  before it codredumped.
@corsix @MikePall can you give me a clue, please?

**Comment by Buristan** [comment]
Hi!
My best idea for now - that this is caused somehow by `LJ_DUALNUM` mode (enabled by default on aarch64). Looks like the reason is the omitted `lj_meta_for()` check in the `rec_for_loop()`: https://github.com/LuaJIT/LuaJIT/blob/03c31124cc3b521ef54fe398e10fa55660a5057d/src/lj_record.c#L459-L466
OTOH, it's totally unclear to me how we can end up there without be checked in `FORI` here (on in the VM):
https://github.com/LuaJIT/LuaJIT/blob/03c31124cc3b521ef54fe398e10fa55660a5057d/src/lj_record.c#L522-L526

May you please provide backtraces from the coredump and/or dump of the traces (dumped file may be large enough) if the problem is reproducible?

P.S. you may dump traces:
* From the command line with the option: `-jdump=abimsrtTX,dump_filename.txt`
* Or from the code:
```lua
require("jit.dump").start("abimsrtTX", "dump_filename.txt")
```

**Comment by caohongqing** [comment]
@Buristan It's kind of you. This problem is very difficult to reproduce, it only occurs once a month. 
I'm trying to get a coredump

**Comment by corsix** [comment]
From a cursory inspection of the FORI/FORL recording code, I don't see anything particularly suspicious.

Deliberately malicious `debug` library usage can violate the assert (even on !DUALNUM), but anyone doing this deserves what they get:
```lua
local function f()
    for i=1,60 do
        if i==56 then
            debug.setlocal(1, 1, false)
        end
    end
end
f()
```
Unfortunately, a similar effect can arise from various malign sources (e.g. memory corruption hitting the Lua stack or hitting Lua function bytecode, or JIT compiler somehow forgetting to update a particular stack slot when leaving a trace), and I fear we might be in such a case, which would make it potentially tricky to track down.

**Comment by Buristan** [comment]
I suppose that within malicious debug library usage, `lj_assert_bad_for_arg_type()` (inside the VM) is observed with much higher probability, so _probably_ it's not the case. I agree here that corrupting the Lua VM by the compiler is a more possible option.

P.S. Lua 5.1 just goes into the infinite loop, resetting its counter on the 56th iteration. LuaJIT without enabled assertions just stops loop execution. So this situation may be claimed as undefined behaviour or implementation-defined behaviour.

**Comment by MikePall** [comment]
Please let's not sidetrack this discussion. Clearly they do not do this. I know you're experts on the darker corners of the VM by now, but this is not helpful here.

I suspect a Lua stack overwrite. Either from the ARM64 `asm_stack_restore()` or (less likely) the equivalent data-driven code in `lj_snap_restore()`. Hard to say without a testcase.

Another thing to verify is they are not using OpenResty's fork. They keep ignoring my pleas to rip out most of their patches relative to this repo. In particular, they ignored my [hint](https://github.com/openresty/luajit2/pull/201#issuecomment-1633193504) for their last merge. Sigh.

**Comment by corsix** [comment]
On the hypothesis that we're hitting some other rare bug in the ARM64 backend that is just happening to first reveal itself at `lj_opt_narrow.c:600`, I've spent a lot of time recently considering the ARM64 backend code, identifying #1056 and #1057 and #1062 and #1065 and #1068. Some of these could _possibly_ reveal themselves at `lj_opt_narrow.c:600`, though in every case segfaults or other misbehaviour are more likely.

**Comment by MikePall** [comment]
Closing, since we still have no reproducer, no further feedback and lots of ARM64-related fixes in the meantime.

**Comment by corsix** [comment]
I have the beginnings of an idea of a different possible cause of this: `rec_for_loop` can create `IR_SLOAD` instructions with the combination of mode bits `IRSLOAD_INHERIT | IRSLOAD_READONLY | IRSLOAD_CONVERT`. When such an instruction is encountered by `snapshot_slots`, it'll gain `SNAP_NORESTORE` in single-num mode, but it _won't_ gain `SNAP_NORESTORE` in dual-num mode. So far so good, everything is operating as expected. Should this snapshot entry later be seen by `lj_snap_replay`, then it'll create a new `IR_SLOAD` instruction in the child, which will have the combination of mode bits `IRSLOAD_INHERIT | IRSLOAD_PARENT | IRSLOAD_READONLY`. When _this_ instruction is encountered by `snapshot_slots`, it'll always gain `SNAP_NORESTORE`, which is wrong in dual-num mode.

One fix might be:
```diff
diff --git a/src/lj_snap.c b/src/lj_snap.c
index 68de208f44..99d2b7fa44 100644
--- a/src/lj_snap.c
+++ b/src/lj_snap.c
@@ -537,7 +533,7 @@ void lj_snap_replay(jit_State *J, GCtrace *T)
       IRType t = irt_type(ir->t);
       uint32_t mode = IRSLOAD_INHERIT|IRSLOAD_PARENT;
       if (LJ_SOFTFP32 && (sn & SNAP_SOFTFPNUM)) t = IRT_NUM;
-      if (ir->o == IR_SLOAD) mode |= (ir->op2 & IRSLOAD_READONLY);
+      if (ir->o == IR_SLOAD) mode |= (ir->op2 & (IRSLOAD_READONLY|IRSLOAD_CONVERT));
       if ((sn & SNAP_KEYINDEX)) mode |= IRSLOAD_KEYINDEX;
       tr = emitir_raw(IRT(IR_SLOAD, t), s, mode);
     }
```
