### ISSUE TITLE
DynASM/ARM64: out of range error

### ISSUE THREAD

**Issue by pwoolvett** [LuaJIT/LuaJIT#1061]
downstream: https://github.com/pyston/pyston/issues/304

Hi! I am currently trying to debug "`dynasm_encode() returned error 15000163`", I assume from [here](https://github.com/search?q=repo%3ALuaJIT%2FLuaJIT+RANGE_REL+path%3A**%2Fdynasm%2Fdasm_arm64.h&type=code), so I think in the `CK` macro.

There is no problem when running on `x86-64`, but crashes on aarch64 (graviton and mac m1).

Any guidelines or help on how to debug this `DASM_S_RANGE_REL` (If I'm in the right code)? 

thanks!

---
Sample repro via docker, with pyston-lite:

```dockerfile
FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive
ENV LANG=C.UTF-8
RUN : \
  && apt-get update \
  && apt-get install -y \
    git \
    python3.8 \
    python3-venv \
    python3-dev \
    make \
    gcc \
  && :
# setup virtualenv to build wheel
RUN : \
  && /usr/bin/python3.8 -m venv /opt/python \
  && /opt/python/bin/python -m pip install --upgrade \
    pip==23.2.1 \
  && :
ENV PYTHON=/opt/python/bin/python
ENV PATH="/opt/python/bin:$PATH"
# clone pyston_lite source
RUN : \
  && git clone \
    -b pyston_2.3.5 \
    https://github.com/pyston/pyston \
    /opt/pyston \
  && cd /opt/pyston \
  && git submodule update --init pyston/LuaJIT \
  &&:
# customize flags: enable JIT_DEBUG macro
RUN : \
  && sed -i \
    's|//#define JIT_DEBUG 1|#define JIT_DEBUG 1|' /opt/pyston/Python/aot_ceval_jit.c \
  && :
WORKDIR /opt/pyston/pyston/pyston_lite
# install LuaJIT
RUN :\
  && make -C ../LuaJIT clean \
  && make -C ../LuaJIT -j`nproc` \
  && make -C ../LuaJIT -j`nproc` install \
  && ln -sf luajit-2.1.0-beta3 /usr/local/bin/luajit \
  && :
# build wheel
ARG NOLTO=1
ARG NOBOLT=1
ARG NOPGO=1
RUN : \
  && ln -sf $PYTHON /usr/local/bin/ \
  && $PYTHON -m pip wheel . \
      --no-deps \
  && :
# install
RUN : \
  && pip install /opt/pyston/pyston/pyston_lite/pyston_lite-2.3.5-cp38-cp38-linux_*.whl \
  && :
WORKDIR /opt/check
SHELL [ "/bin/bash", "-c" ]
RUN : \
  && printf 'import os \n\
os.environ["JIT_SHOW_STATS"] = "1" \n\
os.environ["JIT_MIN_RUNS"] = "10" \n\
import pyston_lite \n\
pyston_lite.enable() \n\
' > common \
  && echo "from itertools import combinations  # this won't make it crash" \
    | cat common - > ok.py \
  && echo "from email.feedparser import FeedParser  # this makes it crash" \
    | cat common - > crashes.py \
  && :
ENTRYPOINT [ "bash", "-c", "python ok.py && echo 'success!' && python crashes.py"]
```

**Comment by MikePall** [comment]
A `DASM_S_RANGE_REL` error means that a branch has a target that is too far away. 

The lower bits in that error code are the failing position in the DynASM actionlist. Look at the DynASM-generated file for a `dasm_put` with the nearest position below or equal to that.

In your case that's 0x163 = 355, so look for the closest `dasm_put(Dst, NNN, ...)` with NNN <= 355. The assembler source code immediately above it contains the culprit.

ARM64 has different limits for the branch range, depending on the instruction type. They are _much_ lower than the +-2GB range on x86, so one cannot expect to branch just anywhere. One really needs to check the range before emitting a code segment and e.g. use an inverted conditional branch around a (longer-range) unconditional branch. Or use indirect branches or rearrange the code so this cannot happen.
