### ISSUE TITLE
ARM64: Inconsistent sign extension of 32-bit constants

### ISSUE THREAD

**Issue by corsix** [LuaJIT/LuaJIT#1065]
When a 32-bit value exists in a GPR, there are various options for the contents of the high 32 bits: they could all be zero ("zero-extend"), or they could all be copies of bit 31 ("sign-extend"), or they could be some arbitrary other value ("undefined"). For reasons that will become clear, we need to answer the following questions:

- A: When a `IR_KINT` instruction has a value in a GPR, what is in the high 32 bits?
- B: When any other type of instruction has a value in a GPR, what is in the high 32 bits?

B=zero-extend is the obvious answer to the latter question, as ARM64 instructions operating on 32-bit values don't care about the high 32 bits of input GPRs, and write zeros to the high 32 bits of output GPRs. I could see the argument for B=undefined though; a lot of mixed-width instructions could (or do already) employ SXTW/UXTW to ignore the undefined bits, with the tradeoff being that u32 to u64 conversion is no longer a no-op.

We seem to fairly consistently go with B=zero-extend at the moment; see the various occurrences of `emit_dm(as, A64I_MOVw, dest, dest)`. That said, surprisingly few places rely on it, with the notable place being u32 to u64 conversion (either explicitly in `asm_conv`, or implicitly as in `asm_snew`).

So far so good, but things are about to get unpleasant. At the moment, we sometimes emit code as if A=zero-extend, and sometimes as if A=sign-extend. Simultaneously, we have some consumers that assume A=zero-extend, and other consumers that assume A=sign-extend. When the assumption of the consumer mismatches the behaviour of the emitter, bad things happen.

The emitter is `lj_emit_arm64.h`'s `emit_loadk`. The `is64` parameter therein is interesting; the current semantics appear to be "is64=0 means that the caller does not care about the top 32 bits of the resulting GPR", as it can go either way: the `emit_isk13` route does A=zero-extend when is64=0, whereas the `emit_kdelta` route does A=sign-extend when is64=0, while the MOVK/MOVN/MOV route is even more interesting: if any MOVK instructions are required then A=zero-extend, but if a single MOVN suffices then A=sign-extend. On the consumer side, i32 to u32 conversions assume A=zero-extend (one of the no-op cases in `asm_conv`), whereas `get_k64val` and `ra_allock` assume A=sign-extend (one particularly concerning use of `get_k64val` is within `emit_kdelta`).

----

One example of this going wrong is:
```lua
local ffi = require "ffi"
local t = {}
for i = 1, 60 do
    t[i] = tonumber(ffi.cast("uint64_t", ffi.cast("uint32_t", ffi.cast("int32_t", -1))))
end
assert(t[1] == 4294967295, t[1])
assert(t[60] == 4294967295, t[60]) -- fails
```

The following works at the moment, but is an example of care being required; at the moment, the same GPR can hold the 32-bit `-1` and the 64-bit `nil`, but this is no longer true if A=zero-extend:
```lua
local t = {}
for i = 60, 1, -1 do
    t[i] = nil
end
for i = 60, 1, -1 do
    assert(not t[i])
end
```

-----

Relevant commits at https://github.com/corsix/LuaJIT/commits/arm64-int32; 9da8a12ea adopts A=zero-extend, or apply 525ec7bc51 on top for A=sign-extend and attempts at plugging the resultant holes. These overhaul `emit_loadk` such that it always generates the exact 64-bit constant passed in, with callers responsible for appropriate extension of 32-bit constants. As part of the overhaul, it can now emit `A64I_MOVNw` instructions, allowing certain constants (notably, things like `ra_allock(as, irt_toitype(ir->t)`) to be generated via a single `A64I_MOVNw` rather than MOVKw+MOV(N)x pair.

Three other commits are optimisations in the same general area rather than fixes:
- b280181de0 gets rid of `emit_loada`, replacing the one use with `A64I_ADDx` against `RID_GL`.
- 9b99a6de adopts a shorter algorithm for `emit_isk13`.
- c787fdf7 changes the order of preferences in `emit_lsptr`, to result in more deterministic codegen (as almost all usages of `emit_lsptr` are `glofs` cases), and gives more chances for LDP fusion (notably, the two `emit_getgl` calls in `asm_gc_check` will now always fuse, rather than only fusing when the mcode region was far away from GL).

**Comment by corsix** [comment]
As examples of constant generation going wrong:

The following sometimes fails, depending on whether the IR_KNUM holding 0x1.f9dff8p-1051 is near PC/GL or not:
```lua
local t = {}
for i = 1, 60 do
    if -0x30004 <= i then end
    t[i] = 0x1.f9dff8p-1051
end
assert(t[1] == t[60], ("%+a"):format(t[60])) -- Fails: +0x1.00fceffcp-1042
```
The following fails:
```lua
local s = ("x"):rep(0x10ffc)
for i = 1, 60 do
    if -0x30004 <= i then end
    s = s:sub(1, 0x10ffc) -- Fails: string length overflow
end
```
In both cases, -0x30004 (bit pattern 0xfffcfffc) becomes an IR_KINT, which gets emitted as a zero-extended 32-bit bitwise constant. However `emit_kdelta` thinks it got emitted as the sign-extended 64-bit value 0xffffffff'fffcfffc, and then tries to form 0x1.f9dff8p-1051 (bit pattern 0xfceffc) and 0x10ffc by adding a 12-bit shifted immediate to this sign-extended value, meaning that it ends up with 0x00000001'00fceffc or 0x00000001'00010ffc.

**Comment by MikePall** [comment]
I've opted for zero-extension for ARM64. Thanks!

The other 64 bit backends ought to be revised, too, at some point.

**Comment by corsix** [comment]
This had the unintended side-effect of breaking the optimisation whereby negative 32-bit constants can be fused into 32-bit arithmetic operations. Fix at https://github.com/corsix/LuaJIT/commits/arm64-asm_fuseopm.

**Comment by MikePall** [comment]
Follow-up fix committed. Thanks!
