### ISSUE TITLE
Allow manually specifying paths in genversion.lua

### ISSUE THREAD

**Issue by arch1t3cht** [LuaJIT/LuaJIT#1067]
Hello,

I'm maintaining an application that needs to build luajit using a meson wrap, and I'm currently working on migrating that to rolling releases. I ran into complications with running `genversion.lua` to generate `luajit.h` since meson uses out-of-tree builds and can't easily run commands from custom working directories.

Would it be possible to allow `genversion.lua` to read the input/output file paths from command line arguments (but default to the normal ones if no arguments are given), so that it can be run from other working directories? E.g. with a change like this:
```diff
diff --git a/src/host/genversion.lua b/src/host/genversion.lua
index 42b5e6fe..042121f0 100644
--- a/src/host/genversion.lua
+++ b/src/host/genversion.lua
@@ -5,9 +5,10 @@
 -- Released under the MIT license. See Copyright Notice in luajit.h
 ----------------------------------------------------------------------------
 
-local FILE_ROLLING_H = "luajit_rolling.h"
-local FILE_RELVER_TXT = "luajit_relver.txt"
-local FILE_LUAJIT_H = "luajit.h"
+local args = {...}
+local FILE_ROLLING_H = args[1] or "luajit_rolling.h"
+local FILE_RELVER_TXT = args[2] or "luajit_relver.txt"
+local FILE_LUAJIT_H = args[3] or "luajit.h"
 
 local function file_read(file)
   local fp = assert(io.open(file, "rb"), "run from the wrong directory")
```

(Let me know if I should make a PR)

**Comment by MikePall** [comment]
Applied. Thanks!

**Comment by arch1t3cht** [comment]
Thanks for applying this, but while the change in 4d05806ae046838826f9bab3b3b804eae26cd017 works when running `genversion.lua` with a normal lua runtime, it doesn't work in `minilua` (which is what this script would be run with during builds). There, the `arg` table just ends up empty even when extra arguments are given to `minilua`. I'm not sure if this is an issue with minilua or by design, but either way this makes the script unable to read the arguments. That's why I manually used `{...}` in the patch I sent.

**Comment by MikePall** [comment]
Ah, I forgot. `minilua` doesn't set `arg`.
Fixed. Thanks!

**Comment by arch1t3cht** [comment]
Works now, thanks!
