### ISSUE TITLE
ARM64: Improve backend codegen in several places

### ISSUE THREAD

**Issue by corsix** [LuaJIT/LuaJIT#1070]
Assorted commits sitting at https://github.com/corsix/LuaJIT/commits/arm64-asm. Unlike most of my recent issues, there are no correctness bugs here, though `asm_href` is only _accidentally_ correct at the moment.

The minor events are the following:
- `asm_intmul` - shorter instruction sequence.
- `asm_obar` - shorter instruction sequence (TST + B.EQ -> TBZ).
- `asm_uref` - shorter instruction sequence (CMP + B.NE -> CBZ), fewer scratch registers (can use `dest` instead).
- `asm_hrefk`, `asm_xstore`, `asm_ahuvload`, `asm_sload` - fewer scratch registers (can use RID_TMP).

The main event is `asm_href`, which currently contains two disturbing pieces of code:
- In the case of `isk && !irt_isnum(kt) && !irt_ispri(kt)` (i.e. `isk && irt_isaddr(kt)`), there's a branch `if (!(k = emit_isk12(irkey->i))) { key = ra_alloc1(as, refkey, allow); rset_clear(allow, key); }`, which is a complicated way of doing nothing: `irkey->i` will always be zero for constant addresses in GC64 mode, which is a valid k12 encoding, so `k` will be set, `key` will not get allocated, and then subsequent logic for `isk && irt_isaddr(kt)` makes no use of either `k` nor `key`.
- `emit_nm(as, A64I_FCMPd, key, ftmp)`, as `emit_nm` expects `n` and `m` in the range 0 through 31, but both `key` and `ftmp` are FPRs here, and thus in the range 32 through 63. This means that we don't emit `A64I_FCMPd`, but instead emit whatever instruction `A64I_FCMPd | (1 << 21) | (1 << 10)` happens to be. The `1 << 21` is harmless, as bit 21 is already set in `A64I_FCMPd`. The `1 << 10` changes the instruction from FCMP to FCCMP.HS, which just happens to be fine because we're immediately preceded by a B.LO instruction, so we'll only reach the FCCMP in cases where the condition is initially true.

In addition to cleaning up the disturbances, there are several improvements possible to `asm_href`:
- Fuse `CMP` + `B.NE` -> `CBNZ`.
- When `!destused`, fuse loading of `Node::key` and `Node::next` into a load-pair.
- When `irt_isnum(kt) && !isk`, use a single CMPx+branch rather than CMPx(tag bits)+branch+FCMPd+branch; this requires canonicalising the runtime key, which is FCMPZd+CSEL, and assumes that any runtime NaNs in FPRs are canonical NaNs (an assumption already made elsewhere), and assumes that canonical NaNs are never keys in tables (an assumption that I thought was true until writing this, but see #1069).
- Unify the constants `type = ra_allock(as, (int32_t)irt_toitype(kt), allow)` (used for constructing a tagged key) and `ra_allock(as, irt_toitype(kt) << 15, allow)` (used for hashing a key).
- When hashing, fuse some shifts/rotates on to subsequent EOR instructions.
- Eliminate MOVw and MOVx instructions.
- As a result of all the above, no longer need `checkmclim`.

**Comment by Pokemetti** [comment]
A small clarification could be that CMP + B.NE should only be fused when comparing against zero. Apart from that I don't know enough about LuaJIT to judge any of this lol.

**Comment by MikePall** [comment]
Applied. Thanks!
