### ISSUE TITLE
Is JIT compiling on iOS possible with iOS entitlement "com.apple.security.cs.allow-jit"?

### ISSUE THREAD

**Issue by svermeulen** [LuaJIT/LuaJIT#1072]
In the LuaJIT docs, it states the following:

    Note: the JIT compiler is disabled for iOS, because regular iOS Apps are not allowed to generate code at runtime. You'll only get the performance of the LuaJIT interpreter on iOS. This is still faster than plain Lua, but much slower than the JIT compiler. Please complain to Apple, not me. Or use Android. :-p

I'm wondering if apple has since change policy and is now allowing this via a flag as described here:

https://developer.apple.com/documentation/apple-silicon/porting-just-in-time-compilers-to-apple-silicon

If so is it possible to re-enable LuaJIT JIT for iOS for certain builds of LuaJIT?

**Comment by mraleph** [comment]
You can't use this entitlement on iOS. So the short answer is no. There is currently no way on iOS to have a JIT in your app and release it through an AppStore.

**Comment by svermeulen** [comment]
Ah right I misread that, thanks.  What about jail broken devices?  Just thinking that LuaJIT JIT could at least be useful during development, before the app is released to app store.

**Comment by mraleph** [comment]
In development if you respect W^X rule (code is never both writable and executable) you can use JIT as long as debugger was at some point attached to your application: `ptrace` currently disables code signing requirements. No special entitlements needed.

We use this fact in Flutter for example: development mode Dart VM is just using our ARM64 JIT on iOS (deployed apps use AOT compiled Dart code).

**Comment by corsix** [comment]
LuaJIT _does_ currently respect W^X, unless you explicitly go out of your way and define `LUAJIT_SECURITY_MCODE=0`.

It does this via `mprotect` calls; it would be an interesting little enhancement to instead do it via `MAP_JIT` / `pthread_jit_write_protect_np` (when `LJ_TARGET_OSX && LJ_TARGET_ARM64`).

**Comment by svermeulen** [comment]
In that case - I wonder how possible it would be to follow a similar approach to flutter with luajit on iOS?   (JIT during development using ptrace etc then AOT for deployment)

I see that the luajit docs do mention AOT support:

    Ahead-Of-Time (AOT) compilation (at runtime) is supported, too:
    - A number of API functions and command line options allows full user control over the compilation process.

However, it specifically says at runtime so I'm guessing that's a dealbreaker?

**Comment by corsix** [comment]
I'm not sure what documentation you're looking at, but I suspect it is some ancient documentation for LuaJIT 1.x (I won't link to it, but you can find 3rd party mirrors of this ancient documentation on the web, and the clue about it being ancient is that the copyright date in the footer is 2010 rather than 2020+). In short, LuaJIT is not intended for the kind of AOT you're thinking of. I'd also say that Lua is not intended for AOT either; Flutter/Dart benefits from being able to design AOT-friendliness into the language.
