### ISSUE TITLE
ARM64: Backend assumes TBZ/TBNZ target is always in range

### ISSUE THREAD

**Issue by corsix** [LuaJIT/LuaJIT#1074]
Example of a long non-looping trace with a TBZ/TBNZ-amenable guard at the start, which currently fails the assertion `LuaJIT ASSERT ./lj_emit_arm64.h:336: emit_tnb: branch target out of range`:
```lua
local code = [[
  local bit = require("bit")
  return function(t, k)
    if bit.band(k, 128) == 0 then
      FILLER
    end
  end
]]
code = code:gsub("FILLER", (('t=t[t]'):rep(341)))
code = assert(loadstring(code, "=code"))()
local t = {}
t[t] = t
for i=1,50 do code(t, 0) end
for i=1,50 do code(t, 0) end
for i=1,50 do code(t, 0) end
```

Potential fix at https://github.com/corsix/LuaJIT/commits/arm64-guardtnb

Looping traces also have the possibility of the loop condition being TBZ/TBNZ-amenable, which exercises a slightly different code path. My potential fix includes `if (as->orignins > 1023) return 0;` to guard against any problems, as without such a check, the following can cause issues (though it requires a slightly non-default `-Osizemcode=80`):

```lua
local code = [[
  local bit = require("bit")
  return function(t)
    local k = 255
    while bit.band(k, 128) ~= 0 do
      FILLER
      k = k - 1
    end
  end
]]
code = code:gsub("FILLER", (('t=t[t]'):rep(345)))
code = assert(loadstring(code, "=code"))()
local t = {}
t[t] = t
code(t)
```

While in the area, I also noticed that the `LJ_TRERR_MCODEOV` check in `lj_mcode_limiterr` is wrong for non-x86/x64 backends:
```diff
diff --git a/src/lj_mcode.c b/src/lj_mcode.c
index 947679377f..7d88d06158 100644
--- a/src/lj_mcode.c
+++ b/src/lj_mcode.c
@@ -363,7 +363,7 @@ void lj_mcode_limiterr(jit_State *J, size_t need)
   sizemcode = (size_t)J->param[JIT_P_sizemcode] << 10;
   sizemcode = (sizemcode + LJ_PAGESIZE-1) & ~(size_t)(LJ_PAGESIZE - 1);
   maxmcode = (size_t)J->param[JIT_P_maxmcode] << 10;
-  if ((size_t)need > sizemcode)
+  if ((need * sizeof(MCode)) > sizemcode)
     lj_trace_err(J, LJ_TRERR_MCODEOV);  /* Too long for any area. */
   if (J->szallmcarea + sizemcode > maxmcode)
     lj_trace_err(J, LJ_TRERR_MCODEAL);
```

**Comment by MikePall** [comment]
Fixed. Thanks!

Fixed the mcode check in v2.0 + v2.1.
