### ISSUE TITLE
ARM64: Should not fuse sign-extension into logical operands, can fuse rotations though

### ISSUE THREAD

**Issue by corsix** [LuaJIT/LuaJIT#1076]
The following currently fails, as it tries to fuse a sign extension into a logical operand:
```lua
local t = {}
local zero = 0LL
local bit = require("bit")
for i = 1, 60 do
  t[i] = bit.bor(-i, zero)
end
for i = 1, 60 do
  assert(tonumber(t[i]) == -i)
end
```

There's also a missed optimisation of fusing rotates into a logical operand.

Both at https://github.com/corsix/LuaJIT/commits/arm64-fuseopm

**Comment by MikePall** [comment]
Fixed. Thanks!
