### ISSUE TITLE
Fails to build on MSYS (CYGWIN)

### ISSUE THREAD

**Issue by facboy** [LuaJIT/LuaJIT#1077]
I thinks commit [cb413bf8f](https://github.com/LuaJIT/LuaJIT/commit/cb413bf8f4814fe3e47c8c619602c7a161469faf) breaks support for building on CYGWIN. Specifically, I think it's the changes in `src/host/buildvm_peobj.c`, the build errors out with:

```
...
HOSTLINK  host/buildvm.exe
BUILDVM   lj_vm.o
Error: no PE object support for this target
make[1]: *** [Makefile:673: lj_vm.o] Error 1
make[1]: Leaving directory '/d/git/LuaJIT/src'
make: *** [Makefile:138: src/luajit] Error 2
```

**Comment by MikePall** [comment]
Fixed. Thanks!
