### ISSUE TITLE
Fix recording of implicit number-to-string conversion in select(x, ...)

### ISSUE THREAD

**Issue by corsix** [LuaJIT/LuaJIT#1083]
Things like `select('2', ...)` are valid; the interpreter will implicitly convert `'2'` to a number and then carry on. The trace recorder currently overlooks this possibility, causing _very interesting_ IR where the input operand of `IR_CONV(IRCONV_INT_NUM)` has a string type rather than a number type.

Fix at https://github.com/corsix/LuaJIT/commits/strto-select.

**Comment by MikePall** [comment]
Fixed. Thanks!
