### ISSUE TITLE
Promote 32-bit constants in 64-bit operations

### ISSUE THREAD

**Issue by corsix** [LuaJIT/LuaJIT#1084]
There are two commits at https://github.com/corsix/LuaJIT/commits/lj_ir_kintpgc, the first of which fixes two cases of `IRT(IR_ADD, IRT_PGC)` with a potentially-negative constant operand. For LJ_GC64 backends that zero-extend 32-bit registers and choose not to fuse the constant operand into the IR_ADD (e.g. because the value happens to already be sitting in a register, or because `JIT_F_OPT_FUSE` was turned off), this can cause misbehaviour. The UREFO case would just cause spurious trace exits most of the time; you'd have to be incredibly unlucky for the `IR_EQ` to succeed when it shouldn't. The `select(x, ...)` case would cause spurious trace exits most of the time for non-number types (because the type check in the VLOAD is likely to fail), but can much more easily cause the wrong value to be loaded for number types (because most random 64-bit values will pass the type check for numbers). At the moment, this causes the following to fail on ARM64 (though https://github.com/LuaJIT/LuaJIT/issues/1065#issuecomment-1722486862 will sidestep the issue):
```lua
local function f(...)
  local t = {}
  for i = 1, 60 do
    t[i] = select(2, ...)
  end
  assert(t[1] == t[60], tostring(t[60]))
end
f(0.5, 1.5)
```

The second commit tidies up a bunch of more benign cases where 64-bit operations have a constant in the range 0 through INT32_MAX expressed as a KINT. It is less clear what the correct thing to do here is; on the one hand, there are places that implicitly assume that various operations have the same type (or at least same register class and bit width) as their operands, but on the other hand there are `LJ_TARGET_X64`-specific fold rules that intentionally produce IR for which this isn't true.

**Comment by MikePall** [comment]
Fixed. Thanks!
Note this needed an additional fix for the x64 backend, which assumed `K=KINT` in `VLOAD(AREF(ADD(...,K),...),...)`.
