### ISSUE TITLE
IR_UREFO unsoundness

### ISSUE THREAD

**Issue by corsix** [LuaJIT/LuaJIT#1085]
Conceptually, there are three different categories of upvalue references during recording:
1. Upvalues that (at recording time) alias an SSA slot.
2. Upvalues that (at recording time) are open, but do not alias an SSA slot.
3. Upvalues that (at recording time) are closed.

Category (1) becomes an IR_UREFO followed by an IR_EQ to confirm the aliasing at runtime. Confirming the aliasing implicitly confirms the open-ness. Category (3) becomes an IR_UREFC, which confirms the closed-ness at runtime (which in turn implicitly confirms non-aliasing). Category (2) is more problematic; it becomes an IR_UREFO followed by IR_UGT to confirm non-aliasing, but the open-ness is never confirmed. It might transpire to be closed at runtime, as in the following:
```lua
local set, get
local function f()
  for i = 1, 100 do
    set({get()})
    collectgarbage("step", 1)
  end
end
do
  local uv
  set = function(v) uv = v end
  get = function() return uv end
  f() -- uv is open during trace recording
end
f();f() -- but now uv is closed
```
The above can non-deterministically fail, for example with:
```
LuaJIT ASSERT lj_gc.c:207: gc_traverse_tab: TValue and GC type mismatch
Abort trap: 6
```
Or:
```
LuaJIT ASSERT lj_gc.c:62: gc_mark: mark of dead object
Abort trap: 6
```

---

Another issue with category (2) is that a particular upvalue might transition from category (2) to category (3) _during recording_, which will confuse `aa_uref`. This can happen if an upvalue is pointing into some other coroutine's stack, and that stack is garbage collected during recording. I think a fix for this is:
```diff
diff --git a/src/lj_state.c b/src/lj_state.c
index b45a20438b..9ec09d0b86 100644
--- a/src/lj_state.c
+++ b/src/lj_state.c
@@ -327,8 +327,11 @@ void LJ_FASTCALL lj_state_free(global_State *g, lua_State *L)
   lj_assertG(L != mainthread(g), "free of main thread");
   if (obj2gco(L) == gcref(g->cur_L))
     setgcrefnull(g->cur_L);
-  lj_func_closeuv(L, tvref(L->stack));
-  lj_assertG(gcref(L->openupval) == NULL, "stale open upvalues");
+  if (gcref(L->openupval) != NULL) {
+    lj_func_closeuv(L, tvref(L->stack));
+    lj_trace_abort(g);  /* For aa_uref soundness. */
+    lj_assertG(gcref(L->openupval) == NULL, "stale open upvalues");
+  }
   lj_mem_freevec(g, tvref(L->stack), L->stacksize, TValue);
   lj_mem_freet(g, L);
 }
```

---

Possibly a fix for the first issue is to represent category (1) as an IR_UREFO _without_ IRT_GUARD (because the subsequent IR_EQ is sufficient), and category (2) as an IR_UREFO _with_ IRT_GUARD. Backends would need to be taught to emit a check for open-ness for guarded IR_UREFO instructions (at the moment, all IR_UREFO instructions have IRT_GUARD, but backends do not emit a check). Fold rules could then possibly also tell apart categories (1) and (2), noting that gcstep_barrier is only needed for category (2). ~~Going further, there might be value in guarded and unguarded variants of IR_UREFC; if only loading from an upvalue, then _possibly_ there's no need to confirm closed-ness at runtime (stores of gcvalues need closed-ness for the barrier, and stores of non-gcvalues could fall afoul of `aa_uref`)~~. The same argument could drop the guard from category (2) loads, though then gcstep_barrier would have to stay.

**Comment by achaulk** [comment]
Checking closedness for the barrier is not really necessary, it's just required for closed and is redundant for open, which is really the problem here, there's no barrier once this transitions to closed and requires it. A guard works, could also just emit the barrier for case 2 instead and it'll continue to work whenever it closes. I agree reading is probably fine without a guard

**Comment by corsix** [comment]
The _current_ OBAR logic isn't going to work for case 2, as the OBAR needs to inspect the mark bits of the `GCupval*` (or, hypothetically, it needs to inspect the `closed` field of the `GCupval*`), but it only has the `TValue*` of the upvalue's value. For closed upvalues it is easy to go from the `TValue*` back to the `GCupval*` (just subtract `offsetof(GCupval, tv)`), but there is no such shortcut for open upvalues. Accordingly an OBAR for (possibly) open upvalues would need to either unconditionally make the stored object gray, or resynthesize the `GCupval*` so that it could inspect its metadata.

I also belatedly realised that unguarded UREFC isn't much use; if the closed-ness isn't verified, then we instead need to verify non-aliasing of SSA slots, which is a more expensive check (or at least as expensive).

**Comment by corsix** [comment]
There's a commit at https://github.com/corsix/LuaJIT/commits/urefo which explores having three variants of UREFO: SSA aliasing (unguarded, type PGC), probably open but we don't mind if it is closed (guarded, type IGC), definitely open (guarded, type PGC). Case 2 starts out as "probably open", but gets promoted to "definitely open" if required (i.e. because we store a gcvalue to it and want to elide a barrier, or because it would improve upvalue alias analysis), at which point there'll be a runtime guard confirming open-ness.

**Comment by achaulk** [comment]
Oh yeah you're right. I must have been looking at my branch where I changed that barrier to just unconditionally mark

**Comment by MikePall** [comment]
Fixed. Thanks!
