### ISSUE TITLE
DCE can sometimes leave instructions off their chain

### ISSUE THREAD

**Issue by corsix** [LuaJIT/LuaJIT#1094]
If DCE keeps instruction `A` because it wasn't marked but did have a non-weak guard, and then eliminates the next (in iteration order, i.e. previous in IR order) instruction of the same kind, then `A` gets left off the relevant chain (whereas if the next instruction is kept, then `A` makes it to the chain). As a very silly example, the following in DUALNUM mode can leave one of the CONV instructions intact but off the chain:
```lua
local outer = 0.5
for i = 1, 60 do
  local _ = i + 0.5 -- There's an unguarded and unused CONV here, which gets eliminated
  math.floor(outer) -- There's a guarded but otherwise unused CONV after the call, which ends up missing from the chain
end
```

To hit this, you need an instruction kind with strong guards, that is sometimes emitted with a guard and sometimes emitted without a guard. That alone basically limits you to HREFK (because the guard can be eliminated if the source is TDUP) or CONV or SLOAD, and I can't think of anything particularly bad that can happen because of one of these being left off their chain after DCE - _at worst_ it's a missed CSE opportunity during LOOP (and even that might not be hittable in practice). Nevertheless, it seems worth maintaining the invariant that chains always contain all instructions of a given kind (except the always-empty NOP chain), as it removes a potential future footgun.

It also helps that the fix is trivial:
```diff
diff --git a/src/lj_opt_dce.c b/src/lj_opt_dce.c
index c6c3e1bc34..e6fcc552c4 100644
--- a/src/lj_opt_dce.c
+++ b/src/lj_opt_dce.c
@@ -44,12 +44,12 @@ static void dce_propagate(jit_State *J)
     IRIns *ir = IR(ins);
     if (irt_ismarked(ir->t)) {
       irt_clearmark(ir->t);
-      pchain[ir->o] = &ir->prev;
     } else if (!ir_sideeff(ir)) {
       *pchain[ir->o] = ir->prev;  /* Reroute original instruction chain. */
       lj_ir_nop(ir);
       continue;
     }
+    pchain[ir->o] = &ir->prev;
     if (ir->op1 >= REF_FIRST) irt_setmark(IR(ir->op1)->t);
     if (ir->op2 >= REF_FIRST) irt_setmark(IR(ir->op2)->t);
   }
```

**Comment by MikePall** [comment]
Fixed. Thanks!
