### ISSUE TITLE
Support for the ARM64EC ABI on Windows ARM64

### ISSUE THREAD

**Issue by kobykahane** [LuaJIT/LuaJIT#1096]
LuaJIT recently introduced support for Windows ARM64 targets, based on the original Windows ARM64 ABI.

In Windows 11, an additional ABI was introduced, ARM64EC. This ABI allows mixing native ARM64 code and emulated x64 code in the same process. This is useful for projects that want to support, e.g., legacy x64-compiled plugin DLLs on ARM64 devices. It would be useful if LuaJIT could be built for ARM64EC, so it could be consumed by hosting programs with such requirements.

Presently only MSVC supports this ABI, although there's been some initial work in clang as well. To target this ABI, the `/arm64EC` option is passed in the cl.exe command line, or `/machine:arm64ec` to lib.exe or link.exe. Details of the ABI are described in [Overview of ARM64EC ABI conventions
](https://learn.microsoft.com/en-us/cpp/build/arm64ec-windows-abi-conventions?view=msvc-170) and [Understanding Arm64EC ABI and assembly code](https://learn.microsoft.com/en-us/windows/arm/arm64ec-abi). Some key issues that appear to impact a potential port of LuaJIT:
- A one-to-one mapping between the ARM64 processor context and the emulated x64 processor context is defined. To facilitate this, the ABI bans certain ARM64 registers from being used, including x13, x14, x23, x24, x28 and v16-v31. The interpreter and the JIT would need to avoid using the banned registers.
- When the JIT allocates executable memory, it needs to do so with `VirtualAlloc2` and specify `MEM_EXTENDED_PARAMETER_EC_CODE`, so the system knows the dynamically generated code is ARM64 code and not x64 code.
- When a call is made to an externally provided function pointer (i.e., a lua_CFunction or via FFI), in the general case the provided function might be native ARM64 code or it might be x64 code that needs to be run by the emulator, so the indirect call needs to be made via a call checker provided by the OS, e.g., `__os_arm64x_check_icall`. The call checkers are automatically used by compiler-generated code, but need to be invoked explicitly by assembly code.

**Comment by fsfod** [comment]
[VirtualAlloc2](https://learn.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-virtualalloc2) could be useful on x64 as well using [MemExtendedParameterAddressRequirements](https://learn.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-mem_address_requirements) to allow the JIT to constrain executable memory allocation to an address range completely replacing mcode_alloc and its random allocation probing on windows 10 at least.

**Comment by corsix** [comment]
It looks to be an interesting ABI, in an academic and/or Frankenstein sense. I wouldn't expect the banned registers to cause _too_ much pain (vm_arm64.dasc could gain the option to neither save nor use x23/x24/x28 by using a volatile register for RC, moving TISNIL to an FPR, moving LREG to where TISNIL was, and using `TISNUMhi, lsl #32` in place of TISNUM), though there'll be a minor performance hit from the banning. I can't say the same about call checkers and exit stubs (lua_CFunction / interpreted FFI calls / compiled FFI calls) and entry stubs (FFI callbacks) though; they look annoying.

For testing purposes, I _think_ any Windows 11 ARM64 install suffices; unlike [Apple's ARM64e ABI](https://github.com/LuaJIT/LuaJIT/issues/559), this isn't reliant on hardware/qemu having ptrauth features (Microsoft's x64 emulator hopefully runs anywhere, unlike Apple's Rosetta 2 that relies on another piece of custom hardware).

My gut feeling is that the development+maintenance burden will be high, and that user demand will be low (at least in the near future), but I could be wrong on both counts. That said, it's tempting to try throwing something together, if only to get a better feel for how much work it'll be.

**Comment by MikePall** [comment]
My gut feeling is the same. Windows/ARM64 itself is not exactly widespread. Judging by diverse forums it's mostly users who didn't closely read the label before buying that laptop on hot sale.

And we're talking about the hypothetical case where someone develops a new application 1. with LuaJIT, 2. which must run on Windows/ARM64 and 3. includes some x64 DLLs they don't have the source code for. That's a bit too hypothetical for me.

So, unless someone steps forward with that exact use case _and_ is willing to pay for the initial development and the ongoing maintenance cost, I'll close this as wontfix.

**Comment by corsix** [comment]
@fsfod wrote:
> [VirtualAlloc2](https://learn.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-virtualalloc2) could be useful on x64 as well using [MemExtendedParameterAddressRequirements](https://learn.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-mem_address_requirements) to allow the JIT to constrain executable memory allocation to an address range completely replacing mcode_alloc and its random allocation probing on windows 10 at least.

Following a bunch of experimentation, strong no from me. The ARM64 Windows 11 VM that I'm playing with seems to respond with STATUS_INVALID_PARAMETER if MemExtendedParameterAddressRequirements is used with the LowestStartingAddress/HighestEndingAddress fields set to anything non-zero (the Alignment field can successfully be set, but it isn't much use in this context). The documentation on HighestEndingAddress also says that it "must not exceed lpMaximumApplicationAddress returned by GetSystemInfo", which seems like a needless footgun compared to just having the call internally clamp the end address. Finally, the WINE implementation I'm looking at doesn't support LowestStartingAddress at all.

**Comment by fsfod** [comment]
The issue i found when i was using it was that LowestStartingAddress\HighestEndingAddress\Alignment must be page aligned or it failed with STATUS_INVALID_PARAMETER.

**Comment by corsix** [comment]
I eventually found the issue; HighestEndingAddress needs to be page aligned then _minus 1 byte_, rather than page aligned. It also looks like Wine [started supporting LowestStartingAddress a few months ago](https://github.com/wine-mirror/wine/commit/11cd51139d4b9adaf877f4082d16adccc22cab7c). For example the tests therein show a usage with `HighestEndingAddress = (void *)0x2fffffff`. Once that Wine version is broadly rolled out, the only remaining footgun is lpMaximumApplicationAddress, as if lua51.dll is loaded at a very high address, adding our jump range to that might push us beyond lpMaximumApplicationAddress, causing the allocation request to fail.

-----

Returning to the original topic, I've thrown together a sequence of commits at https://github.com/corsix/LuaJIT/commits/arm64ec. JIT-compiled code takes a trace abort/exit if it tries to call an X64 function, but interpreted FFI code can call X64 functions, as can the C API, and FFI callbacks can come _from_ X64 code. My feeling about its utility remains low, but it can be pulled out of bit-rot purgatory if it becomes useful in the future. I've pulled some generally-useful commits to the start of the sequence, which are probably worth picking up even if the rest is left.

**Comment by kobykahane** [comment]
Thanks @corsix! This is a great news. I am glad this Frankenstein ABI was an itch you just had to scratch...
I really appreciate you looking into this. In terms of utility, our use case (a high-rate event streaming system with the hot path in Lua, with dependencies on binary only x64 components in non-hot paths), having ARM64EC support is the difference between a port being feasible or not, so we'll definitely be checking out this patch set internally. Trace aborts on x64 invocations are perfectly fine in our scenarios.
From a cursory glance, the changes don't appear too extensive. Given what Mike said on ongoing maintenance cost, do you think it would be prohibitive for merging this?

**Comment by corsix** [comment]
For completeness, I've added one additional commit that allows JIT calls to X64 functions. The thunking isn't always pretty, but it is better than doing an interpreted FFI call.

**Comment by corsix** [comment]
Looks like Mike has adopted most of the generally-useful commits, so I've rebased https://github.com/corsix/LuaJIT/commits/arm64ec on top of them.

**Comment by kobykahane** [comment]
> Looks like Mike has adopted most of the generally-useful commits, so I've rebased https://github.com/corsix/LuaJIT/commits/arm64ec on top of them.

Thanks @corsix! All your hard work on this is greatly appreciated and we'll be using your branch for our workload.

**Comment by baconpaul** [comment]
> And we're talking about the hypothetical case where someone develops a new application 1. with LuaJIT, 2. which must run on Windows/ARM64 and 3. includes some x64 DLLs they don't have the source code for. That's a bit too hypothetical for me.

Hi!

So it turns out that this exact case is the case for audio software. Namely:

1. Many plugins are x64 dlls which are not yet recompiled and where users dont have source but load into the parent program
2. Therefore the parent program compiles as arm64ec
3. And since arm64ec can't load arm binaries, thats having audio plugins be arm64ec (or the more recent arm64x which is sort of a kinda-fat-binary of arm64ec and arm64)

This weekend I did the port of surge to arm64ec and it runs fine in reaper on this snapdragon windows laptop I've been using. But to do so, I turned off the lua support in the synth.

So I think the non-hypothetical case really is the plugins case which is dominant in audio (seems reaper and cubase both are arm64ec targeted)

It's a bit unclear from this issue what the state of arm64ec is though and at head the code seems to only have arm64 and x86, not arm64ec. Do we need to use a branch to get arm64ec? Also does cross compilation work on the branch?

Any guidance would be greatly appreciated. 

Thanks!

**Comment by kobykahane** [comment]
@baconpaul ARM64EC support was never upstreamed to LuaJIT, for the reasons Mike pointed out. However, for what it's worth, we've been using @corsix's ARM64EC branch for a while with good results. Regarding cross-compilation, there's a little bug in the build batch script there that causes builds to fail on a non-ARM64 device, but it's relatively easy to work around. Also, since it's been a while since that branch was made, it's probably worth the trouble to attempt to rebase it on top of newer bug fixes in LuaJIT upstream.

**Comment by theAeon** [comment]
For whatever its worth, there's also a use case here with porting game software to WoA. Until valve deigns to port their client dll to arm, any dev (or enterprising user) wanting to run games natively _will_ need to use the EC abi.

(an aside-balatro runs _great_ with @corsix's branch rebased to HEAD, much appreciated)

**Comment by baconpaul** [comment]
I was really hoping to not fork luajit for my project. Does the @corsix branch rebased to HEAD also work on the other platforms or do I need a separate luajit repo for arm64ec?

It's becoming increasingly clear that for *everything* which is software-in-software (games in engine, synths in daws, plugins in photo editors) that arm64ec (or arm64x) is going to be the solution on windows. so i guess I should figure out how to industrialize two sources of lua for my project sometime early next year.

thanks for all your efforts!

**Comment by corsix** [comment]
I should do a rebase on to HEAD so that there’s something canonical, but I’d also welcome being pointed at other people’s rebases (if they’re public) as a cross-check.

To answer the question above, the intent is that the patch series is entirely additive: all platforms and configurations supported by HEAD should also work with the patch series - it adds Arm64EC support, and this does not come at the cost of anything else.

**Comment by theAeon** [comment]
> I should do a rebase on to HEAD so that there’s something canonical, but I’d also welcome being pointed at other people’s rebases (if they’re public) as a cross-check.

Series applied cleanly on my local so I didn't think it made sense to fork. Shouldn't be any issues.

**Comment by baconpaul** [comment]
Yeah we use a submodule so “fork apply use” would be our pattern but glad to know if we do that we can use one submodule for all platforms 

just it makes sweeping upgrades painful. But we can live with that! We just won’t upgrade often.

but from looking at how windows arm is playing out, I don’t think arm64ec will be a transition period thing (or I guess will be a transition period only inasmuch as every period is a transition period on the right timescale). For the audio world I bet we have half a decade before windows arm64ec demand drops so I want to make a sustainable choice here

**Comment by theAeon** [comment]
I am curious what would be required to merge the patchset at this point. Genuinely-JIT isn't my forte and I'm sure there's pitfalls I'm unaware of.

**Comment by kobykahane** [comment]
@MikePall Given the additional use cases presented here, would you be inclined to reconsider upstreaming @corsix's ARM64EC patch set?

**Comment by corsix** [comment]
FWIW, I've rebased https://github.com/corsix/LuaJIT/commits/arm64ec onto the latest commit from `v2.1`.

**Comment by baconpaul** [comment]
Hi. I'm just wondering if there is any further consideration of adding 64ec support to the luajit main branch? Our arm users are increasing, and 64ec is a popular choice for some windows arm digital audio workstations which have begun porting.

Thanks

**Comment by baconpaul** [comment]
yeah we decided to go wait-and-see and not have an arm version with lua (so not include the arm version in our numbered releases) for now.

I thought about a fork/port/grab the things but this is a complicated bit of code and one I don't particularly want to master the internals of. And on the platforms where it is supported it's a really important dep for us to be working so I'm reticent to move away from core distro.

But if folks wanted to rally around a community effort for a 64ec branch we could include and try it.

**Comment by Psychlist1972** [comment]
Any movement on this? We're starting to see apps in the video production space also needing this. Pretty much any application which can load plugins on Windows (think all your Adobe plugins, BlackMagic Design, all the DAWs, etc.) relies on Arm64EC to enable them to load x64 plugins (many of which are expensive items customers have already purchased).

Are there blockers here?

I'd love to see @baconpaul 's Surge XT fully support Arm64, and this is the blocker for that. It's also the blocker for some other partners as mentioned.

Pete
Microsoft
