### ISSUE TITLE
ARM64: Use ADR or ADRP to form constants

### ISSUE THREAD

**Issue by corsix** [LuaJIT/LuaJIT#1100]
One commit at https://github.com/corsix/LuaJIT/commits/arm64-adrp.

The ADRP without ADD case can hit more often than you might think, due to this in `emit_lsptr`:
```c
  } else {  /* Split up into base reg + offset. */
    int64_t i64 = i64ptr(p);
    base = ra_allock(as, (i64 & ~0x7fffull), rset_exclude(RSET_GPR, r));
    ofs = i64 & 0x7fffull;
  }
```

ADR is fairly rare, but crops up occasionally, and fits into the emission code very easily.

ADRP+ADD will fuse on _some_ CPUs.

**Comment by corsix** [comment]
2<sup>nd</sup> commit added, which fixes up some disassembly, based on looking at an aforementioned `emit_lsptr` scenario.

**Comment by MikePall** [comment]
Applied. Thanks!
