### ISSUE TITLE
Binary name for v2.1.ROLLING seems incorrect?

### ISSUE THREAD

**Issue by geoffpaulsen** [LuaJIT/LuaJIT#1101]
Hello.

  I'm new to LuaJit, and am building from scratch.  I am using `v2.1.ROLLING` tag (currently: `2090842410e0b`).
  
  I'm building on MAC OSX v13.5.2 (and set `MACOSX_DEPLOYMENT_TARGET=13.05`).  I also set an alternate PREFIX to somewhere in my homedir.
  After `make install` succeeded, I notice that the binary name in `${PREFIX}/bin` is `luajit-2.1.`.  
  
  The trailing dot (`.`) seems very strange.  Is this expected?
  
  Digging in a bit more, this seems to be happening since `INSTALL_T` is set to this value, and that's apparently because `src/luajit_relver.txt` is a 0 length file for some reason.
  
  I do see these lines in my `make all` output:
  ```
**** WARNING Cannot determine rolling release version from git log.
**** WARNING The 'git' command must be available during the build.
  ```
  
I just worked around this issue by forcing RELVER=`20908424`.

**Comment by MikePall** [comment]
This is not the version you want there. You either need a git checkout (with the 'git' command available) or a tarball with `.relver` properly set at the root.

**Comment by MikePall** [comment]
That file is created by the `GIT_RELVER` commands from within `src/Makefile` when creating `src/luajit.h` from `src/luajit_rolling.h`.

It looks like the 'git' command is not working correctly in your installation. Try `git show -s --format=%ct` from within the source tree. This should output the time of the last commit as a numeric timestamp.
