### ISSUE TITLE
Lua51.dll not compiling to 64-bit on Windows

### ISSUE THREAD

**Issue by Kuumba123** [LuaJIT/LuaJIT#1104]
I really wish there more details for compiling (still not sure why there aren't pre-compiled libraries for atleast the 3 main operating systems) but basicly Im using Visual Studio command prompt and when ever I run the msvcbuild.bat it always builds a 32-bit dll even if I type nogc64.

**Comment by MikePall** [comment]
The [documentation](https://luajit.org/install.html#windows) says you need to open the x86, x64 or ARM64 Visual Studio command prompt, depending on the target architecture.
