### ISSUE TITLE
Windows: _BitScanForward64/_BitScanReverse64 not available as an intrinsic function

### ISSUE THREAD

**Issue by memcorrupt** [LuaJIT/LuaJIT#1109]
It seems that cb413bf8f4814fe3e47c8c619602c7a161469faf that added Windows/ARM64 support added intrinsics that should be behind a ARM ifdef.

See lj_def.h _BitScanForward64/_BitScanReverse

```
src\lj_def.h(266): warning C4163: '_BitScanForward64': not available as an intrinsic function
src\lj_def.h(267): warning C4163: '_BitScanReverse64': not available as an intrinsic function
```

compiled with MSVC command line for Visual Studio 2019

**Comment by MikuAuahDark** [comment]
Actually it needs to have 64-bit check. Those are not available on 32-bit.

**Comment by MikePall** [comment]
Fixed. Thanks!
