### ISSUE TITLE
how do i build luajit for wasm?

### ISSUE THREAD

**Issue by JonnycatMeow** [LuaJIT/LuaJIT#1112]
can it be possible to do so?

**Comment by JonnycatMeow** [comment]
and for my os that i am using is windows

**Comment by MikePall** [comment]
Here's [the list of target architectures](https://luajit.org/status.html#architectures).
WASM is not a viable target at this time. It lacks the support required for JIT compilers (runtime code generation + execution).

**Comment by Kingrd97** [comment]
> Here's [the list of target architectures](https://luajit.org/status.html#architectures). WASM is not a viable target at this time. It lacks the support required for JIT compilers (runtime code generation + execution).

Can we build it without JIT and FFI? Just to be compatible with the same bytecode on both the app and web, and only enable jit on Android

**Comment by Kingrd97** [comment]
> Here's [the list of target architectures](https://luajit.org/status.html#architectures). WASM is not a viable target at this time. It lacks the support required for JIT compilers (runtime code generation + execution).

Can we build it without JIT and FFI? Just for compatible with the same bytecode on both the App and Web, and only enable jit on Android. I tried to modify the source code to build it but finally found that some core functions were implemented in lj_vm.S and could not be linked to by wasm-ld.

**Comment by MikePall** [comment]
The interpreter is written in architecture-specific machine code. It needs a WASM equivalent, too. But even then, performance would not be great and would give people the wrong impression.

LuaJIT without the JIT, without the FFI and without a fast interpreter is not that attractive.

**Comment by thenumbernine** [comment]
https://webvm.io is running luajit in browser with jit and ffi.

**Comment by alexjgriffith** [comment]
webvm.io uses CheerpX an x86 virtualisation layer for wasm https://labs.leaningtech.com/cheerpx

It just runs normal luajit compiled for x86 systems. 

That said a pure c reference implementation of luajit would be useful to extend cross platform compatibility. Lua PUC 5.1 is a poor drop in replacement.
