### ISSUE TITLE
ARM64: Fix disassembly of ldp/stp offsets

### ISSUE THREAD

**Issue by corsix** [LuaJIT/LuaJIT#1113]
The following fixes computation of the shift amount in `dis_arm64.lua`'s handling of ldp/stp offsets:
```diff
diff --git a/src/jit/dis_arm64.lua b/src/jit/dis_arm64.lua
index a7a2949441..8467766628 100644
--- a/src/jit/dis_arm64.lua
+++ b/src/jit/dis_arm64.lua
@@ -985,8 +985,7 @@ local function disass_ins(ctx)
        x = x.."]"
       end
     elseif p == "P" then
-      local opcv, sh = rshift(op, 26), 2
-      if opcv >= 0x2a then sh = 4 elseif opcv >= 0x1b then sh = 3 end
+      local sh = 2 + rshift(op, 31 - band(rshift(op, 26), 1))
       local imm7 = lshift(arshift(lshift(op, 10), 25), sh)
       local rn = map_regs.x[band(rshift(op, 5), 31)]
       local ind = band(rshift(op, 23), 3)
```
The cases where the old logic differs from the new logic are:

| Instruction Bit Pattern | dis_asm64.lua Pattern | Old sh | New sh |
|--------|--------|--------|--------|
|01_111_0_001_1_??????????????????????|ldpswDAxP|3|2|
|01_111_0_010_1_??????????????????????|ldpswDAxP|3|2|
|01_111_0_011_1_??????????????????????|ldpswDAxP|3|2|
|10_101_0_001_0_??????????????????????|stpDzAzxP|4|3|
|10_101_0_001_1_??????????????????????|ldpDzAzxP|4|3|
|10_101_0_010_0_??????????????????????|stpDzAzxP|4|3|
|10_101_0_010_1_??????????????????????|ldpDzAzxP|4|3|
|10_101_0_011_0_??????????????????????|stpDzAzxP|4|3|
|10_101_0_011_1_??????????????????????|ldpDzAzxP|4|3|
|10_111_0_001_0_??????????????????????|stpDzAzxP|4|3|
|10_111_0_001_1_??????????????????????|ldpDzAzxP|4|3|
|10_111_0_010_0_??????????????????????|stpDzAzxP|4|3|
|10_111_0_010_1_??????????????????????|ldpDzAzxP|4|3|
|10_111_0_011_0_??????????????????????|stpDzAzxP|4|3|
|10_111_0_011_1_??????????????????????|ldpDzAzxP|4|3|

In the above table, it should be clear why old sh is wrong and new sh is correct:
- ldpsw should have sh == 2, as a signed word is 4 bytes.
- ldp/stp with `x` operands (i.e. bit 31 set, bit 26 clear) should have sh == 3, as `x` registers are 8 bytes.

The new logic matches the [recently amended](https://github.com/LuaJIT/LuaJIT/commit/656ecbcf8f669feb94e0d0ec4b4f59190bcd2e48) assembler side.

**Comment by MikePall** [comment]
Fixed. Thanks!
