### ISSUE TITLE
SIGINT (CTRL+C) interruption unreliable with jit compilation enabled

### ISSUE THREAD

**Issue by rhaberkorn** [LuaJIT/LuaJIT#1120]
Tested with the current v2.1 HEAD.

Code like this is not interruptible from the official interpreter:
```
> while true do end
```

That is, not the regular way. Pressing CTRL+C twice will kill the process since the original SIGINT action is restored. However we would expect the code to raise an error instead and return us to the prompt. Apparently the hook, set via `lua_sethook()`, is not invoked from jit compiled code. The same is probably true for everything set via `debug.sethook()` from Lua. Which does make sense as it would be a major slow down to poll for the necessary conditions from machine code all the time. Consequently, everything works as expected when disabling jit compilation first:
```
> jit.off()
> while true do end
```

But being able to interrupt from SIGINT is IMHO very useful for interactive prompts. So perhaps, it shouldn't rely on hooks. I am not sure how this could be solved within LuaJIT's architecture.

**Comment by MikePall** [comment]
https://luajit.org/faq.html#ctrlc
Sometimes I wonder whether writing documentation is a complete waste of effort ...

**Comment by rhaberkorn** [comment]
> https://luajit.org/faq.html#ctrlc Sometimes I wonder whether writing documentation is a complete waste of effort ...

I overlooked that, sorry. However the FAQ just confirms that the bug exists. And it begs the question on how to work around it. Basically you are saying, LuaJIT (with JIT compilation enabled) does not support CTRL+C interruptions at all and never will? From the human standpoint it's unpredictable when LuaJIT produces code that checks the hook and when not, so you must assume that it is never checked as long as JIT compilation is enabled. Any kind of endless or long-running loop is thus potentially non-interruptible. It's one thing to say that C function calls are naturally not interruptible and another thing to say, that well, nothing that you might want to interrupt is actually interruptible.

Is there a workaround, how can we reliably - and with the least overhead - poll for SIGINT in code where this matters? As long as hooks are not used for anything else, it might be sufficient to add an `assert(not debug.gethook())` to the loop, perhaps with caching debug.gethook. I suggest to add this information to the FAQ entry.

**Comment by rhaberkorn** [comment]
As a workaround in my own application, where I luckily control the interpreter, I ended up setting a flag as well whenever SIGINT occurs. This is exposed to Lua-land via a C function. Something like `extern volatile int interrupted_flag;` won't do as LuaJIT ignores the `volatile` and will apparently optimize away reads to the variable. The C function is wrapped into a Lua function for throwing an error. This should still be way more efficient than using the Lua C API for defining a function.

Now I can add calls to this function manually in tight loops in order to make them reliably interruptible.
