### ISSUE TITLE
Cross-compile for ARM given Ubuntu bug #1300211

### ISSUE THREAD

**Issue by igorpupkinable** [LuaJIT/LuaJIT#1126]
How do you cross-compile for ARM given that `gcc-multilib` and `gcc-arm-linux-gnueabihf` cannot co-exist on the same Ubuntu system?

Ubuntu bug [#1300211](https://bugs.launchpad.net/ubuntu/+source/gcc-defaults/+bug/1300211)

`sudo apt install libc6-dev-i386` (i.e. gcc-multilib, gcc-9-multilib or gcc-10-multilib packages) forces removal of gcc-arm-linux-gnueabihf (i.e. gcc-arm-linux-gnueabihf, gcc-9-arm-linux-gnueabihf or gcc-10-arm-linux-gnueabihf).

On another hand

`sudo apt install gcc-arm-linux-gnueabihf` (i.e. gcc-arm-linux-gnueabihf, gcc-9-arm-linux-gnueabihf or gcc-10-arm-linux-gnueabihf packages) forces removal of gcc-multilib, gcc-9-multilib or gcc-10-multilib.

In the first case you get `gcc not found` error.
In the second case you get another error:
```bash
$ make HOST_CC="gcc -m32" CROSS=arm-linux-gnueabihf-
==== Building LuaJIT 2.1 ====
make -C src
make[1]: Entering directory '/home/ubuntu/LuaJIT/src'
HOSTCC    host/minilua.o
In file included from /usr/include/bits/errno.h:26,
                 from /usr/include/errno.h:28,
                 from host/minilua.c:40:
/usr/include/linux/errno.h:1:10: fatal error: asm/errno.h: No such file or directory
    1 | #include <asm/errno.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:715: host/minilua.o] Error 1
make[1]: Leaving directory '/home/ubuntu/LuaJIT/src'
make: *** [Makefile:125: default] Error 2
```

Which `-I` and `-L` do I need to provide to fix this if any?

**Comment by igorpupkinable** [comment]
I have found two instances of _asm/errno.h_ in these two locations:
- /usr/arm-linux-gnueabihf/include/asm/errno.h
- /usr/include/x86_64-linux-gnu/asm/errno.h

`make HOST_CC="gcc -m32 -I/usr/include/x86_64-linux-gnu" CROSS=arm-linux-gnueabihf-` worked with trial and error approach, but please let me know if this is a correct way to fix this issue.

**Comment by MikePall** [comment]
I think the best workaround is to install the target cross-compiler (`gcc-arm-linux-gnueabihf` in your case) _plus_ the 32 bit x86 cross-compiler package `gcc-i686-linux-gnu`. Then use the latter as `HOST_CC`. This line works for me:

```
make HOST_CC=i686-linux-gnu-gcc CROSS=arm-linux-gnueabihf-
```

**Comment by igorpupkinable** [comment]
```bash
$ sudo apt install gcc-10-i686-linux-gnu
$ make HOST_CC=i686-linux-gnu-gcc-10 CROSS=arm-linux-gnueabihf-
```

@MikePall this worked perfectly. Thank you.
