### ISSUE TITLE
"do not serialize" special table key for string.buffer?

### ISSUE THREAD

**Issue by bjne** [LuaJIT/LuaJIT#1135]
Does it exist a special lightuserdata, that can be used to signal to buf:encode() that it should
not include certain table keys and their content in the serialized output?

If not, is there any trick that can be used?

thinking:

```lua
{
  do_encode = {1,2,3},
  [require("string.buffer").do_not_encode] = {4,5,6}
}

**Comment by MikePall** [comment]
This would only cover one specific use case. It gets tricky with nested tables. Or when the same key is used in different parts of the tree. Or one may want to check for (non-serializable) values, too.

OTOH I might consider a filter function. Similar to what some JavaScript serializers offer. But to be 1. general enough and 2. fast, i.e. JIT-compilable requires a lot of changes to the VM, which are not in scope right now. So, no ETA for this and closing as WONTFIX.
