### ISSUE TITLE
Strange integer truncation/conversion on x86 Windows MSVC22 build

### ISSUE THREAD

**Issue by aaptel** [LuaJIT/LuaJIT#1136]
I have an closed-source 32bit x86 app shipping with LuaJIT 2.0.4 DLL.
I was hitting issues which were fixed in later versions.
Since LuaJIT ABI is stable I swapped the DLL with a more recent one I built.
But now I'm hitting a different issue:

- Calls to a C primitive are made with integer constants as one of the argument.
- The C primitive always gets the constant `0x80000000` instead.

    -- lua call (color, func_name)
    RegisterSpawnFunction( 0xffd0d0b4, "spawn_treasure" )
    -- func receives 0x80000000, "spawn_treasure") instead!

I've logged with a debugger what the values are with the 2.0.4 LJ DLL and made a diff with current 2.1 LJ DLL.

```
    -color=0xff4c9333 func='spawn_shopitem'
    -color=0xffb4d0d0 func='spawn_treasure'
    -color=0xff4d7041 func='spawn_specialshop'
    -color=0xffddeeff func='init'
    -color=0xff155a23 func='spawn_music_machine'
    
    +color=0x80000000 func='spawn_shopitem'
    +color=0x80000000 func='spawn_treasure'
    +color=0x80000000 func='spawn_specialshop'
    +color=0x80000000 func='init'
    +color=0x80000000 func='spawn_music_machine'
 ```

As you can see these constants always end up mangled to 0x80000000.

The 2.0 branch doesn't have this problem, and I was able to do a git bisect to commit  b359ce804bb525 .
The bad integer constant starts to appear after applying this.

**Comment by MikePall** [comment]
`0xffd0d0b4` is out of range for a 32 bit signed integer. Most likely the C function is mis-declared to take an `int32_t`, but it should be an `uint32_t`.

This triggers undefined behavior, so the result could be anything. And, yes, the actual behavior changed a long time ago in v2.1.

You could try to patch the declarations in the closed-source app. ;-)
