### ISSUE TITLE
Cross compile on Windows for Linux

### ISSUE THREAD

**Issue by Mellnik** [LuaJIT/LuaJIT#1137]
The [installation page](https://luajit.org/install.html) explains how to cross compile LuaJIT.

My goal is to compile LuaJIT for Linux x64 on Windows x64. I've an installation of llvm with clang and make on Windows 10.

I've tried a lot of different variations and overcome a lot of errors - the following command seems to work best so far but it does not fully complete.

```
make CROSS=x86_64-unknown-linux-gnu- HOST_CC="clang -D_CRT_SECURE_NO_WARNINGS --sysroot=C:\UnrealToolchains\v22_clang-16.0.6-centos7\x86_64-unknown-linux-gnu" CC="gcc --target=x86_64-pc-linux-gnu --sysroot=C:\UnrealToolchains\v22_clang-16.0.6-centos7\x86_64-unknown-linux-gnu" TARGET_SYS=Linux
```

Outputs

```
cc1.exe: warning: command line option '-ftarget=x86_64-pc-linux-gnu' is valid for Java but not for C [enabled by default]
The system cannot find the path specified.
The system cannot find the path specified.
"HOSTLINK  host/minilua.exe"
"VERSION   luajit.h"
"DYNASM    host/buildvm_arch.h"
"HOSTCC    host/buildvm.o"
"HOSTCC    host/buildvm_asm.o"
"HOSTCC    host/buildvm_peobj.o"
"HOSTCC    host/buildvm_lib.o"
"HOSTCC    host/buildvm_fold.o"
"HOSTLINK  host/buildvm.exe"
"BUILDVM   lj_vm.S"
"ASM       lj_vm.o"
cc1.exe: warning: command line option '-ftarget=x86_64-pc-linux-gnu' is valid for Java but not for C [enabled by default]
x86_64-unknown-linux-gnu-gcc: error: CreateProcess: No such file or directory
make: *** [lj_vm.o] Error 1
```

What is the correct way of achieving this goal or is it not supported at all?

Thank you!

**Comment by MikuAuahDark** [comment]
Generally cross-compiling to Linux from Windows is not supported in general, not just LuaJIT.

**Comment by Mellnik** [comment]
Not being a specialist in cross compiling but are you sure about that? I can cross compile Unreal Engine projects with the same LLVM toolchain to Linux on Windows without issues.

**Comment by MikePall** [comment]
While theoretically possible, there's no explicit support for this. Given the proper toolchains (compiler *and* C library headers), it could be made to work with enough patience.

In your case, judging from the error message, it looks like you do not have a complete C cross-compiler installation. Or the right incantation to invoke it. First, try to get a simple hello-world C file to cross-compile.
