### ISSUE TITLE
Large penalty for frequent side-trace exit

### ISSUE THREAD

**Issue by lukego** [LuaJIT/LuaJIT#114]
The overhead of a frequently taken branch to a side-trace can be dramatic. See lukego/blog#8 for a discussion. This is presumably the root of the [optimization advice](http://wiki.luajit.org/Numerical-Computing-Performance-Guide) to "avoid unbiased branches" and "prefer branch-free algorithms".

I decided to file this issue with a bounty (see below) after a [tweet](https://twitter.com/mraleph/status/669920751085076482) from @mraleph raised the very exciting possibility that there may be a simple (partial) solution.

This is a problem for common applications. For example inner loops in networking code will naturally include some unbiased branches such as:

- Is this a TCP or UDP packet?
- Is this an IPv4 or IPv6 packet?
- Does this packet belong to a known session?

and to hoist such branches outside of inner loops (hot traces) can require elaborate programming practices, for example to sort packets into separate categories (taking the branch penalties) before processing them (doing the "heavy lifting" separate branch-free traces). This is unfortunate because it substantially "raises the bar" on how much expertise is required to write reasonably efficient code.

It would be wonderful if the JIT could somehow be enhanced such that a modest number of unbiased branches, such as the examples listed above, could be taken without a major performance penalty. This would bring efficient programming within the reach of more people and especially people without a strong mental model of trace-based just-in-time compilation (a large and interesting group!)

Here are some "in the wild" examples where a lot of programmer-time is being spent dealing with this issue:

- lukego/blog#8: Synthetic example.
- SnabbCo/snabbswitch#612: Side trace caused by FFI type guards.
- SnabbCo/snabbswitch#623: traceprof profiler written to make this issue more transparent.
- SnabbCo/snabbswitch#638: Code rewritten to avoid side-trace problems: inner loops either [ported to C to hide from the JIT](https://github.com/alexandergall/snabbswitch/blob/4b4b8ad33daa2d97d536727bfd3018657c310d9e/src/apps/bridge/mac_table.c) or [manually hoisted](https://github.com/SnabbCo/snabbswitch/pull/638/files#diff-11ea90d417d95e910b8ae1261df91879R197) outside of the trace that contains branches (classification of unicast/multicast/discard packets).
- Igalia/snabbswitch#97: PodHashMap hashtable written in Lua with much hand-wringing about potential non-local impact of side traces.

and previous discussion in the LuaJIT community:

- luajit/luajit#37: Hyperblock scheduling (potential solution that may be prohibitively difficult to implement).

**Comment by lukego** [comment]
There is a [BountySource bounty](https://www.bountysource.com/issues/28691855-large-penalty-for-frequent-side-trace-exit) available to anybody who improves LuaJIT such that a modest number of unbiased branches (e.g. the three listed in the example above) could be included in a hot trace with only modest overhead. The example code on lukego/blog#8 could be used as an initial/partial test case.

**Comment by drbo** [comment]
I have thought about how to implement this.  This plan seems like it might work.  It is based on LuaJIT using a 2-pass optimization scheme: one set of forward optimizations and one set of backwards optimizations.

- Create IR that is the same as the IR used by the main trace, but with the trace-exiting guard reversed.
- Run all forward optimization passes.  Assert that the IR prior to the LOOP instruction is the same as the IR for the original trace.
- We can't run all backward passes straightforwardly, because they may not be valid with the different control flow.  Therefore, they must be run with the branching guard as a barrier, to insure that the pre-guard IR matches.

This has some problems, such as a potentially exponential trace blow-up, but should still be an improvement over the current situation.

**Comment by MikePall** [comment]
There's no easy fix and no general solution with the current compiler backend.

Closing, since there's already #37 for the actual solution.
