### ISSUE TITLE
user environment variable E cause make fail

### ISSUE THREAD

**Issue by tkkcc** [LuaJIT/LuaJIT#1141]
When I build [yazi](https://github.com/sxyazi/yazi), I got this error
```txt
  --- stderr
  /bin/sh: line 1: /home/bilabila/.cache: Is a directory
  make: *** [Makefile:718: host/minilua.o] Error 126
  thread 'main' panicked at '
  Error building LuaJIT:
      Command: cd "/tmp/cargo-install03ecMP/release/build/mlua-sys-6518a0c16d2d5fdd/out/luajit-build/build/src" && BUILDMODE="static" STATIC_CC="/usr/bin/cc -O2 -ffunction-sections -fdata-sections -fPIC -m64" TARGET_AR="/usr/bin/ar rcus" TARGET_LD="/usr/bin/cc -O2 -ffunction-sections -fdata-sections -fPIC -m64" TARGET_STRIP="/usr/bin/strip" TARGET_SYS="Linux" XCFLAGS="-fPIC -DLUAJIT_ENABLE_LUA52COMPAT" "make" "-e"
      Exit status: exit status: 2
      ', /home/bilabila/.cargo/registry/src/index.crates.io-6f17d22bba15001f/luajit-src-210.5.3+29b0b28/src/lib.rs:261:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `yazi-fm v0.1.5`, intermediate artifacts can be found at `/tmp/cargo-install03ecMP`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

dependency: [yazi](https://github.com/sxyazi/yazi) -> [mlua-sys](https://github.com/khvzak/mlua) -> [luajit-src-rs](https://github.com/khvzak/luajit-src-rs) -> [LuaJIT](https://github.com/LuaJIT/LuaJIT)

The cause is, in the `LuaJIT/src/Makefile`, `E` is `@echo`, but the above command `make -e` will override variables in makefile, and I usually set `E` to `~/.cache` for less typing(also other A-Z). So `@echo` is replaced with `~/.cache`. Boom.

https://github.com/LuaJIT/LuaJIT/blob/29b0b282f59ac533313199f4f7be79490b7eee51/src/Makefile#L611-L612
https://github.com/LuaJIT/LuaJIT/blob/29b0b282f59ac533313199f4f7be79490b7eee51/src/Makefile#L717-L719

Is this a habit to use `E` for `@echo`? As variables in makefile can be override, using meaningfull words instead of single charactor is better i think.

**Comment by MikePall** [comment]
Maybe you've never compiled a Linux kernel, then. Q/E is quite common.
