### ISSUE TITLE
increasing upvalue count

### ISSUE THREAD

**Issue by Frityet** [LuaJIT/LuaJIT#1150]
I am trying to use a function in an external library that has more than 60 upvalues, causing LuaJIT to error. Is it possible to increase the upvalue count, through a compile flag or macro?

**Comment by MikePall** [comment]
You can change `LJ_MAX_UPVAL` in `src/lj_def.h`. The possible maximum is 127 right now.

Note that a high number of upvalues indicates inefficient Lua code and/or (bad) automatically generated Lua code.

**Comment by Frityet** [comment]
Thank you!
