### ISSUE TITLE
Luajit memory not really release

### ISSUE THREAD

**Issue by libing0526** [LuaJIT/LuaJIT#1157]
### Environment
Luajit version: v2.1
system information : Windows 11 or Centos7

### Problem description
Using the following code for testing, I found that the memory allocated by Luajit was not actually released：
```-- jit.off()
local function get_process_meminfo()
    -- just get process working set
    local ret, mem = myfunc.get_process_memory()
    if ret == 0 then
        --unit is K
        if os_type == "windows" then
            ret = math.ceil(mem)
        else
            ret = math.ceil(mem * 1024)
        end
    else
        ret = 0
    end
    return ret
end

local function get_luavm_meminfo()
    local current_mem = 0
    local max_mem = 0
    local real_mem = 0;
    local LUA_GCCOUNT = 3
    local LUA_GCMAXIMUM = 8
    local LUA_REALMEM = 14
    current_mem = collectgarbage("count")
    if type(current_mem) ~= "number" then
        current_mem = 0
    end
    max_mem = 0--collectgarbage("maxcount")
    if type(max_mem) ~= "number" then
        max_mem = 0
    end
    real_mem = 0 --collectgarbage("real_mem")
    if type(real_mem) ~= "number" then
        real_mem = 0
    end
    return current_mem, max_mem, real_mem
end

local function gen_data()
    local result = {}
    print("begin gen_data")
    for i = 1, 100000 do
        local ip_info = {{
            ["type"] = "ipv4",
            ["ip"] = "192.168.137.1",
            ["mac_addr"] = "3c-7c-3f-d3-0b-68",
            ["name"] = "local",
            ["netmask"] = "255.255.255.0",
            ["gateway"] = "192.168.137.1"
        }, {
            ["type"] = "ipv4",
            ["ip"] = "192.168.137.1",
            ["mac_addr"] = "00-50-56-c0-00-01",
            ["name"] = "VMware Network Adapter VMnet1",
            ["netmask"] = "255.255.255.0",
            ["gateway"] = "0.0.0.0"
        }, {
            ["type"] = "ipv4",
            ["ip"] = "192.168.137.1",
            ["mac_addr"] = "00-50-56-c0-00-08",
            ["name"] = "VMware Network Adapter VMnet8",
            ["netmask"] = "255.255.255.0",
            ["gateway"] = "0.0.0.0"
        }}
        local ipv61 = {"fe80::fe80:fe80:fe80:fe80/64"}
        local ipv6_info = {{
            ["type"] = "ipv6",
            ["name"] = "local",
            ["mac_addr"] = "3c-7c-3f-d3-0b-68",
            ["ip"] = ipv61
        }, {
            ["type"] = "ipv6",
            ["name"] = "VMware Network Adapter VMnet1",
            ["mac_addr"] = "00-50-56-c0-00-01",
            ["ip"] = ipv61
        }, {
            ["type"] = "ipv6",
            ["name"] = "VMware Network Adapter VMnet8",
            ["mac_addr"] = "00-50-56-c0-00-08",
            ["ip"] = ipv61
        }, {
            ["type"] = "ipv6",
            ["name"] = "Loopback Pseudo-Interface 1",
            ["mac_addr"] = "",
            ["ip"] = ipv61
        }}
        local obj = {
            ["os_type"] = "windows",
            ["hardid"] = "04aa0db9-xxxx-xxxx-xxxx-xxxx95347af51",
            ["os_info"] = {
                ["ver"] = "10.0.19045",
                ["sp_ver"] = "0.0",
                ["product_type"] = "workstation",
                ["is_64bit"] = true,
                ["language"] = "chs",
                ["name"] = "DESKTOP-6N54CGU",
                ["description"] = "Microsoft Windows 10(build 19045)",
                ["kernel_ver"] = "10.0.19041.3930"
            },
            ["cpu_info"] = {
                ["cpu_type"] = "amd64",
                ["cpu_number"] = 12,
                ["cpu_producer"] = "GenuineIntel",
                ["cpu_bandstr"] = "Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz",
                ["cpu_speed"] = " 2.90GHz",
                ["physical_id"] = "0x5"
            },
            ["ip_info"] = ip_info,
            ["ipv6_info"] = ipv6_info,
            ["connect_ip"] = "",
            ["log_level"] = 3,
            ["last_boot_time"] = "2024-02-01 10:39:00",
            ["is_ipv6"] = false
        }
        table.insert(result, obj)
        obj = nil
    end
    print("end gen_data")
    return result
end

local function main()
    collectgarbage("collect")

    local agent_mem = get_process_meminfo() / 1024
    local lua_mem, lua_max_mem, real_mem = get_luavm_meminfo()
    print("[test_gc] start: agent=" .. tostring(agent_mem) .. " lua:" .. tostring(lua_mem) .. " " ..
                       tostring(lua_max_mem) .. " " .. tostring(real_mem))

    local data = gen_data()
    agent_mem = get_process_meminfo() / 1024
    lua_mem, lua_max_mem, real_mem = get_luavm_meminfo()
    print("[test_gc] mid: agent=" .. tostring(agent_mem) .. " lua:" .. tostring(lua_mem) .. " " ..
                       tostring(lua_max_mem) .. " " .. tostring(real_mem))

    for i = 1, 10 do
        myfunc.sleep(500)
        data = nil
        collectgarbage("collect")
        agent_mem = get_process_meminfo() / 1024
        lua_mem, lua_max_mem, real_mem = get_luavm_meminfo()
        print("[test_gc] end: agent=" .. tostring(agent_mem) .. " lua:" .. tostring(lua_mem) .. " " ..
                           tostring(lua_max_mem) .. " " .. tostring(real_mem))
    end

end

main()
```
Output As(Unit is KB):
```
[test_gc] start: agent=57952 lua:97 103 128
[test_gc] mid: agent=379228 lua:287066 287066 316992
[test_gc] end: agent=162676 lua:101 287066 100288
[test_gc] end: agent=162676 lua:101 287066 100288
[test_gc] end: agent=162792 lua:101 287066 100288
[test_gc] end: agent=162792 lua:101 287066 100288
[test_gc] end: agent=162792 lua:101 287066 100288
[test_gc] end: agent=162792 lua:101 287066 100288
[test_gc] end: agent=162792 lua:101 287066 100288
[test_gc] end: agent=162792 lua:101 287066 100288
[test_gc] end: agent=162792 lua:101 287066 100288
[test_gc] end: agent=162792 lua:101 287066 100288
```
Even if GC calls multiple times, it can be seen that the memory requested internally by Luajit has not been fully released (the last digit of each output line)

### Verification 1
close jit，it becomes normal：
```
[test_gc] start: agent=57920 lua:97 103 128
[test_gc] mid: agent=378936 lua:287063 287063 316928
[test_gc] end: agent=62488 lua:97 287063 384
[test_gc] end: agent=62488 lua:97 287063 384
[test_gc] end: agent=62488 lua:97 287063 384
[test_gc] end: agent=62488 lua:97 287063 384
[test_gc] end: agent=62488 lua:97 287063 384
[test_gc] end: agent=62488 lua:97 287063 384
[test_gc] end: agent=62488 lua:97 287063 384
[test_gc] end: agent=62488 lua:97 287063 384
[test_gc] end: agent=62508 lua:97 287063 384
[test_gc] end: agent=62508 lua:97 287063 384
```
From this, it can also be seen that enabling jit does not bring significant additional memory overhead to the process（379228  ~= 378936 ）

### Verification 2
Using the system's malloc，I have adjusted some interfaces of LUAJIT here, instead of enabling LUAJIT_ Use_ SYSMALLOC macro to implement. output is also normal (At this point, there is no need to focus on the last column of each row):
```
[test_gc] start: agent=57852 lua:97 103 0
[test_gc] mid: agent=555568 lua:287063 287063 0
[test_gc] end: agent=64696 lua:97 287063 0
[test_gc] end: agent=64696 lua:97 287063 0
[test_gc] end: agent=64696 lua:97 287063 0
[test_gc] end: agent=64696 lua:97 287063 0
[test_gc] end: agent=64696 lua:97 287063 0
[test_gc] end: agent=64696 lua:97 287063 0
[test_gc] end: agent=64696 lua:97 287063 0
[test_gc] end: agent=64696 lua:97 287063 0
[test_gc] end: agent=64696 lua:97 287063 0
[test_gc] end: agent=64696 lua:97 287063 0
```
### Question
I tried debugging the process of memory allocation in alloc. c, but the reason was not found. I speculate that it may be because the unused and used segments or chunks formed a linked list, resulting in the unused segments that should have been actually released not being released, but only being kept for future reuse. Unless adjacent segments or chunks also need to be released, the chunks are released together when merged.

**Comment by howiezhao** [comment]
I'm just curious what your system's malloc is?

**Comment by libing0526** [comment]
> I'm just curious what your system's malloc is? glibc's malloc? As far as I know, LuaJIT uses a customized version of dlmalloc, which does have the feature of deferred coalescing.

glibc's malloc and msvcrt's malloc is the same result.
yes, luajit uses dlmalloc，But I couldn't find detailed information about dlmalloc and its delayed coalescing feature. Do you know a way to solve the problem of delayed coalescing?

**Comment by libing0526** [comment]
> I'm just curious what your system's malloc is? glibc's malloc? As far as I know, LuaJIT uses a customized version of dlmalloc, which does have the feature of deferred coalescing.

glibc's malloc and msvcrt's malloc is the same result.
yes, luajit uses dlmalloc，But I couldn't find detailed information about dlmalloc and its delayed coalescing feature. Do you know a way to solve the problem of delayed coalescing?

**Comment by MikePall** [comment]
Your script does not work, due to a) missing 'myfunc' dependencies and b) unknown flags to collectgarbage. Even when a) is commented out, b) means you're apparently using a modified codebase. In that case, do not open issues here.

Also, you forgot `jit.flush()` before `collectgarbage()`, if you really insist on cleaning up all temporary memory (it's a bad idea to do this frequently).

Delayed coalescing is a common performance measure used by all dynamic memory allocators (for any language). General discussion about computer science topics is out of scope here.

**Comment by libing0526** [comment]
@MikePall 
(1) yes, I add a flag to collectgarbage to account the real memory cost of luajit(mmap)
(2)I have also tried using jit. flush before, and I don't think it's a good method. But I'm curious why this question is related to jit?
(3)Delayed coalescing is really a common performance measure used by all dynamic memory allocators, but In glibc's malloc or msvc's malloc, this problem does not exist. I debugged dlmalloc in luajit, and some unused large chunks were still saved. Therefore, I considered adding an interface in luajit to force the collection of unused large chunks in dlmalloc (for example, in my example, the size of this large chunk reached nearly 80M)

**Comment by zengjinji** [comment]
@MikePall  Hello,

I had a similar problem。Even if GC calls, memory not been fully released

I found that the condition for segment release in the `release_unused_segments` function depends on whether the last address of the free chunk above the segment is greater than the segment's end `TOP_FOOT_SIZE` (64 bytes on my machine). Normally, the hidden chunk recording segment information above the segment is within these 64 bytes.
However, in the `add_segment` function, the hidden chunk might be located an additional `MIN_CHUNK_SIZE` size away from the segment's end, which is 80 bytes away from the segment's end. In this case, even if all chunks on the segment are free, the entire segment will not be released.
Perhaps in `release_unused_segments`, the condition for determining whether to release needs to be modified so that the last address of the free chunk needs to be greater than the address of the hidden chunk.
like:
```
@@ -1051,13 +1051,14 @@ static size_t release_unused_segments(mstate m)
   while (sp != 0) {
     char *base = sp->base;
     size_t size = sp->size;
+    mchunkptr hidep = mem2chunk(sp);
     msegmentptr next = sp->next;
     nsegs++;
     {
       mchunkptr p = align_as_chunk(base);
       size_t psize = chunksize(p);
       /* Can unmap if first chunk holds entire segment and not pinned */
-      if (!cinuse(p) && (char *)p + psize >= base + size - TOP_FOOT_SIZE) {
+      if (!cinuse(p) && (char *)p + psize >= (char *)hidep) {
```


On my machine, I printed out the segment information for segments where the hidden chunk exceeds 64 bytes from the segment's end and found that even if the entire segment is free, it will not be released.

```
seg_count:1, seg_size:100139008, (hide_chunk - seg_end):72, free_chunk_size:99793360, use_chunk_size:72, free_chunk_size:345504, hide_chunk_size:32, use_chunk_size:8, use_chunk_size:8, use_chunk_size:8, use_chunk_size:8
seg_count:2, seg_size:97779712, (hide_chunk - seg_end):72, free_chunk_size:97779640, hide_chunk_size:32, use_chunk_size:8, use_chunk_size:8, use_chunk_size:8, use_chunk_size:8
seg_count:3, seg_size:86507520, (hide_chunk - seg_end):88, free_chunk_size:86507432, hide_chunk_size:32, use_chunk_size:8, use_chunk_size:8, use_chunk_size:8, use_chunk_size:8, use_chunk_size:8, use_chunk_size:8
seg_count:4, seg_size:584581120, (hide_chunk - seg_end):80, free_chunk_size:584581040, hide_chunk_size:32, use_chunk_size:8, use_chunk_size:8, use_chunk_size:8, use_chunk_size:8, use_chunk_size:8
seg_count:5, seg_size:393216, (hide_chunk - seg_end):64, use_chunk_size:16392, use_chunk_size:12296, free_chunk_size:2232, use_chunk_size:1544, use_chunk_size:392.......
```
As shown above, this happens for segments numbered 2,3, and 4, which together occupy memory to reach 584581040+86507432+97779640=733MB
