### ISSUE TITLE
Failure to parse certain operators

### ISSUE THREAD

**Issue by bendrissou** [LuaJIT/LuaJIT#1158]
Hi,

There are some operators that are not recognised by LuaJIT, such as the floor devision `//` and bitwise exclusive OR `~`.

Is this intended?

Example program:
```
if 123 // 66 then 
x = 2
end
```
Output error:
```
./luajit: .../tests/input_1.in:1: unexpected symbol near '/'
```

**Comment by vanc** [comment]
It's well documented that [LuaJIT is only compatible with Lua 5.1](https://luajit.org/extensions.html).

```
LuaJIT is fully upwards-compatible with Lua 5.1. It supports all standard Lua library functions and the full set of Lua/C API functions.
```

**Comment by MikePall** [comment]
New operators will be part of v3.0. #1092
