### ISSUE TITLE
How much of these performance claims are true?

### ISSUE THREAD

**Issue by iahung3** [LuaJIT/LuaJIT#1159]
Each of them claimed to have superior performance to LuaJIT.

https://github.com/wren-lang/wren

https://github.com/marcobambini/gravity

https://github.com/vtereshkov/umka-lang

https://github.com/ThakeeNathees/pocketlang

**Comment by RevengerWizard** [comment]
These are all classic interpreter implementations...
None mention being faster than LuaJIT, quite the contrary.

**Comment by iahung3** [comment]
> None mention being faster than LuaJIT, quite the contrary.

https://wren.io/performance.html

**Comment by RevengerWizard** [comment]
> LuaJIT with the JIT enabled is much faster than all of the other languages benchmarked, including Wren, because Mike Pall is a robot from the future.

**Comment by iahung3** [comment]
They are benchmarking LuaJIT without JIT. I didn't notice it.
