### ISSUE TITLE
Loading mysql library with FFI

### ISSUE THREAD

**Issue by fenix272** [LuaJIT/LuaJIT#1162]
I'm trying to load the mysql library using this code:
`local ffi = require "ffi"
ffi.cdef [[

  void * malloc(size_t);                   
  void free(void*);
  typedef void MYSQL;
  MYSQL * mysql_real_connect(MYSQL *mysql, const char *host,
                                  const char *user, const char *passwd,
                                  const char *db, unsigned int port,
                                  const char *unix_socket,
                                  unsigned long clientflag);
]]
local res, err = pcall( function() ffi.load( "mysql/lib/libmysql.dll" , true) end ) 
if not res then
 -- error("Could not load mysql library")
end`
The error i get is 'Cannot load the module 'libmysql.dll'. The specified module could not be found'.  But the library is present at the specified path.  I tried using the absolute path but i get the same error. What could the problem be? Maybe  the library  depends on another one?

**Comment by corsix** [comment]
"The specified module could not be found" is the error message as reported by the Windows API. Try using https://www.dependencywalker.com/ to identify which dependency the Windows API is complaining about.

**Comment by fenix272** [comment]
corsix, from the bottom of my heart THANK YOU!!! I used the 'dependency walker' utility and it told me that 'libssl-3-x64,dll' and 'libcrypto-3-x64.dll' implicit dependencies were missing. So i added this code  before loading the main libray 'ffi.load( "mysql/lib/libcrypto-3-x64.dll" , true); ffi.load( "mysql/lib/libssl-3-x64.dll" , true) end ' and volia'!! It works. Thank you again and thank you to Mike Pall for the awesome LuaJit that allows even amateur programmers like me to use  C libraries in an almost straightforward way. Never liked and used the official c api from the Lua main distribution.
