### ISSUE TITLE
./?/init.lua is missing from LUA_PATH_DEFAULT

### ISSUE THREAD

**Issue by lolbinarycat** [LuaJIT/LuaJIT#1163]
is this an intentional choice? it doesn't really look like one, considering:
* `luaconf.h` goes to quite a bit of effort to check for init.lua in all other paths
*  as far as i can tell this lowers compatibility with lua5 for no real advantage
* i don't see this difference documented anywhere

**Comment by MikePall** [comment]
LuaJIT needs to stay compatible with Lua 5.1, which doesn't have this relative path (it was added in Lua 5.3). It would break compatibility to change the path or the element order, so this is not an option.

That said, relative paths pose certain security issues. I'd rather add a flag to remove them, than add one more.
