### ISSUE TITLE
LuaJIT has unexpected behaviour

### ISSUE THREAD

**Issue by Enem-20** [LuaJIT/LuaJIT#1174]
I'm trying to integrate LuaJIT with sol2 binding inside my c++ program instead of standard Lua 5.4. Now I can't load standard io module with require. All of built-in functions and jit modules(jit, ffi, stringbuffer) is allowed.
OS: Windows
Tools: Qt 6.6.1, cmake, Mingw, git bash, LuaJIT 2.1.ROLLING.
LuaJIT was built by shell script which called by git bash:

CMakeLists fragment:
```
find_program(BASH_EXECUTABLE bash
        NAMES bash
        #HINTS
        #    "C:/Users/szamaro/AppData/Local/Programs/Git/bin"
        REQUIRED
    )

message("bash path: ${BASH_EXECUTABLE}")

execute_process (
        COMMAND ${BASH_EXECUTABLE} "makeLuaJIT.sh"
        WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
        COMMAND_ERROR_IS_FATAL ANY
        OUTPUT_VARIABLE RESULTSV_OUT
        ERROR_VARIABLE RESULTSV_ERR
        ECHO_OUTPUT_VARIABLE
        ECHO_ERROR_VARIABLE
        RESULT_VARIABLE RESULTSV_VARY
    )
    ...
    
    target_link_libraries(UniversalAutoTests PRIVATE ${VISA_LIBS_PATH}/visa32.lib ${CMAKE_SOURCE_DIR}/external/libs/LuaJIT/usr/local/lib/libluajit-5.1.a)
```

    
makeLuaJIT.sh:
    
```
#!/bin/bash
script_dir=$(dirname $(readlink -f $0))
luaJITDir=$script_dir/external/libs/LuaJIT
cd $luaJITDir
mingw32-make BUILDMODE=static
mingw32-make install BUILDMODE=static DESTDIR=$luaJITDir
```

Lua script:
```
require "os"
require ("Tools.TestInfo")
require("jit")
require "io"
--require("mobdebug").start()

io.stdout:setvbuf("no")

print("jit version: " .. jit.version)
print("os: " .. jit.os)
resourceManager = Engine.ResourceManager.getInstance()
resourceManager:getMainWindow():addResult("test", "just test", 0.5, 0.9, 1.0, 112, "main.lua")
toggle()
resourceManager:getMainWindow():addResult("test", "just test", 0.5, 0.9, 1.0, 112, "main.lua")
toggle()
resourceManager:getMainWindow():addResult("test", "just test", 0.5, 0.9, 1.0, 112, "main.lua")
toggle()
```

An error occured:
[sol2] An error occurred and has been passed to an error handler: sol: runtime error: ...p_Qt_6_6_1_MinGW_64_bit-Debug/resources/scripts/main.lua:4: module 'io' not found:
	no field package.preload['io']
	no file 'D:\SZamaro\build-UniversalAutoTests-Desktop_Qt_6_6_1_MinGW_64_bit-Debug/resources/scripts/io.lua'
	no file '.\io.dll'
	no file 'D:\SZamaro\build-UniversalAutoTests-Desktop_Qt_6_6_1_MinGW_64_bit-Debug\io.dll'
	no file 'D:\SZamaro\build-UniversalAutoTests-Desktop_Qt_6_6_1_MinGW_64_bit-Debug\loadall.dll'
stack traceback:
	[C]: in function 'require'
	...p_Qt_6_6_1_MinGW_64_bit-Debug/resources/scripts/main.lua:4: in main chunk
[2024-03-10 16:27:24.612] [info] QObject::killTimer: Timers cannot be stopped from another thread	default
[2024-03-10 16:27:24.612] [info] QObject::~QObject: Timers cannot be stopped from another thread	default
terminate called after throwing an instance of 'sol::error'
  what():  sol: runtime error: ...p_Qt_6_6_1_MinGW_64_bit-Debug/resources/scripts/main.lua:4: module 'io' not found:
	no field package.preload['io']
	no file 'D:\SZamaro\build-UniversalAutoTests-Desktop_Qt_6_6_1_MinGW_64_bit-Debug/resources/scripts/io.lua'
	no file '.\io.dll'
	no file 'D:\SZamaro\build-UniversalAutoTests-Desktop_Qt_6_6_1_MinGW_64_bit-Debug\io.dll'
	no file 'D:\SZamaro\build-UniversalAutoTests-Desktop_Qt_6_6_1_MinGW_64_bit-Debug\loadall.dll'
stack traceback:
	[C]: in function 'require'
	...p_Qt_6_6_1_MinGW_64_bit-Debug/resources/scripts/main.lua:4: in main chunk

**Comment by MikePall** [comment]
`luajit -e "require'io'"` works just fine, so the error must be in some other component.

**Comment by Enem-20** [comment]
> `luajit -e "require'io'"` works just fine, so the error must be in some other component.

Sorry, could you help me with an understanding regarding this issue? It seems to me that the problem is due to luajit not being built correctly for my project. Specifically for my case, I did not find a detailed explanation of compiling luajit as an embedded static library. I already read the instructions on the site and searched on the Internet as much as I had the patience to do.
