### ISSUE TITLE
free segment not release memory 

### ISSUE THREAD

**Issue by zengjinji** [LuaJIT/LuaJIT#1179]
Hello,

I had a similar problem like this issue  https://github.com/LuaJIT/LuaJIT/issues/1157 。Even if GC calls, memory not been fully released.

I debugged the src/lj_alloc.c file.
I found that the condition for segment release in the `release_unused_segments` function depends on whether the last address of the free chunk above the segment is greater than the segment's end `TOP_FOOT_SIZE` (64 bytes on my machine). Normally, the hidden chunk recording segment information above the segment is within these 64 bytes.
However, in the `add_segment` function, the hidden chunk might be located an additional `MIN_CHUNK_SIZE` size away from the segment's end, which is 80 bytes away from the segment's end. In this case, even if all chunks on the segment are free, the entire segment will not be released.
Perhaps in `release_unused_segments`, the condition for determining whether to release needs to be modified so that the last address of the free chunk needs to be greater than the address of the hidden chunk.
like:
```
@@ -1051,13 +1051,14 @@ static size_t release_unused_segments(mstate m)
   while (sp != 0) {
     char *base = sp->base;
     size_t size = sp->size;
+    mchunkptr hidep = mem2chunk(sp);
     msegmentptr next = sp->next;
     nsegs++;
     {
       mchunkptr p = align_as_chunk(base);
       size_t psize = chunksize(p);
       /* Can unmap if first chunk holds entire segment and not pinned */
-      if (!cinuse(p) && (char *)p + psize >= base + size - TOP_FOOT_SIZE) {
+      if (!cinuse(p) && (char *)p + psize >= (char *)hidep) {
```

On my machine, I printed out the segment information for segments where the hidden chunk exceeds 64 bytes from the segment's end and found that even if the entire segment is free, it will not be released.

```
seg_count:1, seg_size:100139008, (hide_chunk - seg_end):72, free_chunk_size:99793360, use_chunk_size:72, free_chunk_size:345504, hide_chunk_size:32, use_chunk_size:8, use_chunk_size:8, use_chunk_size:8, use_chunk_size:8
seg_count:2, seg_size:97779712, (hide_chunk - seg_end):72, free_chunk_size:97779640, hide_chunk_size:32, use_chunk_size:8, use_chunk_size:8, use_chunk_size:8, use_chunk_size:8
seg_count:3, seg_size:86507520, (hide_chunk - seg_end):88, free_chunk_size:86507432, hide_chunk_size:32, use_chunk_size:8, use_chunk_size:8, use_chunk_size:8, use_chunk_size:8, use_chunk_size:8, use_chunk_size:8
seg_count:4, seg_size:584581120, (hide_chunk - seg_end):80, free_chunk_size:584581040, hide_chunk_size:32, use_chunk_size:8, use_chunk_size:8, use_chunk_size:8, use_chunk_size:8, use_chunk_size:8
seg_count:5, seg_size:393216, (hide_chunk - seg_end):64, use_chunk_size:16392, use_chunk_size:12296, free_chunk_size:2232, use_chunk_size:1544, use_chunk_size:392.......
```
As shown above, this happens for segments numbered 2,3, and 4, which together occupy memory to reach 584581040+86507432+97779640=733MB

**Comment by MikePall** [comment]
Congratulations! You've found a 20 year old bug in dlmalloc, from which the current LuaJIT allocator code is derived.

Fixed. Thanks!
