### ISSUE TITLE
Performance issue for reg expression with "$"

### ISSUE THREAD

**Issue by hyee** [LuaJIT/LuaJIT#118]
Hello,

With following code, the output is costing 8 seconds on my laptop, I've expected that the `$` symbol helps easily identifing the end of the string and then do some matchings, which should not take so much time. Can LuaJIT improve this scenario?  Thanks a lot.

```
 do
    local a=string.rep("x",40000)..";xxxx"
    local t=os.clock()
    a=a:gsub("[^;]+$","")
    print('cost: '..(os.clock()-t))
end
```

**Comment by MikePall** [comment]
Same for plain Lua. This can only be fixed by substantial changes to the pattern matching algorithm. The JIT compiler isn't involved at all.

A simple workaround for the particular problem would be to use a loop and search backwards for the last semicolon.
