### ISSUE TITLE
On Linux or macOS use ./luajit -bg xxx.lua xxx.out generate bytecode file two times the two output files are different!

### ISSUE THREAD

**Issue by liqt** [LuaJIT/LuaJIT#1180]
I use v2.1 branch code build macs os luajit or linux luajit file， and then:
1. ./luajit -b a.lua 001.lua
2. ./luajit -b a.lua 002.lua

use tools to compare 001.lua and 002.lua,  there are different！
sunc as follow lua code
--------------------------------
local EnvTable = {
OK = 0,
ERR = 1,
DIR_CREATE_FAIL = 2,
LUA_CRASH = 3,
WIN_ERROR=4
}
function sendMsg(msg)
end

sendMsg(EnvTable.OK )
-------------------------------------------

**Comment by Buristan** [comment]
I suppose you should use [the `-d` option](https://luajit.org/extensions.html#string_dump) too:
> Due to VM hardening, bytecode is not deterministic. Add d to the mode string to dump it in a deterministic manner: identical source code always gives a byte-for-byte identical bytecode dump. This feature is mainly useful for reproducible builds.
