### ISSUE TITLE
LLVM tools cannot parse FAT object (Universal Binary) generated by LuaJIT

### ISSUE THREAD

**Issue by ligurio** [LuaJIT/LuaJIT#1181]
### Steps to reproduce 

Create an empty Lua file and generate Mach-O universal binary [^1] using LuaJIT, and then execute `llvm-otool` and `llvm-objdump` for the generated binary. Both tools will give an error (all steps are on Linux x86_64):

```sh
$ echo > empty.lua
$ LUA_PATH="./src/?.lua;./src/jit/?.lua;"  ./build/src/luajit -b -o osx -a arm empty.lua empty.o
$ file empty.o
empty.o: Mach-O universal binary with 2 architectures: [i386:Mach-O i386 object] [armv7:Mach-O armv7 object]
$ llvm-otool-15 -f empty.o
lvm-otool-15: error: 'empty.o': truncated or malformed fat file (cputype (7) cpusubtype (3) at offset 48 with a size of 402, overlaps cputype (12) cpusubtype (9) at offset 224 with a size of 226)
$ llvm-objdump --all-headers empty.o
llvm-objdump: error: 'empty.o': truncated or malformed fat file (cputype (7) cpusubtype (3) at offset 48 with a size of 402, overlaps cputype (12) cpusubtype (9) at offset 224 with a size of 226)
```

### Observations

The FAT object generated with the steps above on Linux is correctly parsed by `otool` on macOS:

```
$ otool --version
llvm-otool(1): Apple Inc. version cctools-1009.3
otool(1): Apple Inc. version cctools-1009.3
disassmbler: LLVM version 15.0.0

$ otool -f empty.o
Fat headers
fat_magic 0xcafebabe
nfat_arch 2
architecture 0
    cputype 7
    cpusubtype 3
    capabilities 0x0
    offset 48
    size 402
    align 2^0 (1)
architecture 1
    cputype 12
    cpusubtype 9
    capabilities 0x0
    offset 224
    size 226
    align 2^0 (1)
```

Pay attention to an incorrect value in `align` field: `2^0`. Align must be a power of two, see "OS X ABI Mach-O File Format Reference" [^5] (page 24):

> An integer specifying the section’s byte alignment. Specify this as a power of two; for example, a section
> with 8-byte alignment would have an align value of 3 (2 to the 3rd power equals 8).

Align is a power of two in a binary produced by `lipo`, see below.

Let's extract Mach-O binaries and build the FAT object again using `lipo`:
```sh
$ lipo -archs empty.o
i386 armv7
$ lipo empty.o -thin armv7 -output mach_arm.o
$ lipo empty.o -thin i386 -output mach_i386.o

$ lipo -create -output empty_lipo.o mach_i386.o mach_arm.o
$ lipo -archs empty_lipo.o
i386 armv7
```

Below is the output `otool` for a binary with the same Mach-O objects generated by `lipo`:

```
$ otool -f empty_lipo.o
Fat headers
fat_magic 0xcafebabe
nfat_arch 2
architecture 0
    cputype 7
    cpusubtype 3
    capabilities 0x0
    offset 4096
    size 402
    align 2^12 (4096)
architecture 1
    cputype 12
    cpusubtype 9
    capabilities 0x0
    offset 8192
    size 226
    align 2^12 (4096)
```

The difference of both FAT objects:

```diff
@@ -5,13 +5,13 @@
     cputype 7
     cpusubtype 3
     capabilities 0x0
-    offset 48
+    offset 4096
     size 402
-    align 2^0 (1)
+    align 2^12 (4096)
 architecture 1
     cputype 12
     cpusubtype 9
     capabilities 0x0
-    offset 224
+    offset 8192
     size 226
-    align 2^0 (1)
+    align 2^12 (4096)
```

----

It seems section by bytecode is shared by both Mach-O executables [^2]. The idea behind it is clear: reduce a size of a resultant FAT object. But this break LLVM tools.

There is a document "OS X ABI Mach-O File Format Reference" [^5] published by Apple (currently removed from site) and it says nothing about overlapped sections. Implementations of LLVM and `cctools` (includes `otool`) have checks to avoid overlapping, see [^3] and [^4]). Is it a bug in LuaJIT?

### References

[^1]: https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary
[^2]: https://github.com/LuaJIT/LuaJIT/blob/d06beb0480c5d1eb53b3343e78063950275aa281/src/jit/bcsave.lua#L565
[^3]: `check_overlaping_element`, https://github.com/opensource-apple/cctools/blob/fdb4825f303fd5c0751be524babd32958181b3ed/libstuff/ofile.c#L6183
[^4]: https://github.com/llvm/llvm-project/blob/9e00405419c7a8bb6b8f00454b8fd47a2a400674/llvm/lib/Object/MachOUniversal.cpp#L213-L225
[^5]: https://github.com/aidansteele/osx-abi-macho-file-format-reference

**Comment by MikePall** [comment]
I've removed the obsolete 32 bit archs and the FAT object support from the MACH-O object file writer.
