### ISSUE TITLE
it isn't compiling

### ISSUE THREAD

**Issue by Antonygamergod** [LuaJIT/LuaJIT#1187]
every time i use the command make(im using cygwin) it gives this error

==== Building LuaJIT 2.1 ====
make -C src
make[1]: Entering directory 'C:/Users/user/Downloads/luajit/src'
CC        lj_err.o
lj_err.c: In function 'lj_err_unwind_win':
lj_err.c:271: error: 'STATUS_LONGJUMP' undeclared (first use in this function)
lj_err.c:271: error: (Each undeclared identifier is reported only once
lj_err.c:271: error: for each function it appears in.)
make[1]: *** [Makefile:706: lj_err.o] Error 1
make[1]: Leaving directory 'C:/Users/user/Downloads/luajit/src'
make: *** [Makefile:125: default] Error 2

how do i solve this

**Comment by mfisher31** [comment]
The MSVC batch script works pretty good instead of Cygwin.  Unless you need it for some reason.
https://github.com/LuaJIT/LuaJIT/blob/v2.1/src/msvcbuild.bat

**Comment by corsix** [comment]
If cygwin's `Windows.h` lacks a definition of `STATUS_LONGJUMP`, then perhaps we need to add it, along the lines of:
```c
#ifndef STATUS_LONGJUMP
#define STATUS_LONGJUMP 0x80000026
#endif
```

**Comment by MikePall** [comment]
Sorry, but Cygwin is not a supported target, anymore. Use either MinGW or MSVC to compile a plain Windows DLL.

**Comment by Antonygamergod** [comment]
Ok i Will try
