### ISSUE TITLE
LuaJIT segmentation fault (possibly internal state corruption) 

### ISSUE THREAD

**Issue by MarioSieg** [LuaJIT/LuaJIT#1222]
Hello,
when I call a Lua function from LuaBridge LuaJIT crashes at somewhat abritary points.
I've already looked at [this issue](https://github.com/LuaJIT/LuaJIT/issues/624) and it seems somewhat similar. With plain PUC Lua my program worked without any issues. I compiled LuaJIT with -g and valgrind support to get follow callstack.
The functions where it randomy crashes at are:
lj_tab_newkey, lj_obj_equal, lj_tab_setstr
It really seems random which one it is.
![image](https://github.com/LuaJIT/LuaJIT/assets/49988901/6c39a352-ed2e-4616-9b8e-29a25e7b95e8)
The error seems to come from a require() function to a file that does exist, and failes after parsing with a GCValue / TValue mismatch. Weirdly the error is somewhat different every time, like if some memory get's overriden internally and the state is corrupted:
LuaJIT ASSERT lj_str.c:332: lj_str_new: (o)->gch.gct == ~LJ_TSTR
![image](https://github.com/LuaJIT/LuaJIT/assets/49988901/3135d619-c524-4478-8c50-9621d8177a7f)
Sometimes it crashes here, it really seems random:
![image](https://github.com/LuaJIT/LuaJIT/assets/49988901/8ccaeed7-7f44-4fc9-9124-fc5918aa5db2)
Sadly I can't provide a simple reproduceable repo as I switched my engine from PUC Lua to LuaJIT and the code and the new FFI Integration is quite alot.

I've seen here that the filename is != NULL but an empty string - IDK if this is valid as only NULL Is checked:
![image](https://github.com/LuaJIT/LuaJIT/assets/49988901/9c235045-7fe9-4794-8d90-4edd2e205f6d)
and the chunkname looks like a weird corrupted string too?

![image](https://github.com/LuaJIT/LuaJIT/assets/49988901/a72f30fb-2ae9-4d95-adcc-fb38f9998c76)
![image](https://github.com/LuaJIT/LuaJIT/assets/49988901/b827f892-987b-4597-b103-0f838bfdcbd3)
Sometimes it also hits:
LuaJIT ASSERT lj_parse.c:1439: fs_fixup_line: bad line delta
it really seems to be releated to parsing, as the error changes even more if I change the require() order of some files.

Let me know if I can provide any more info to help to resolve this!

**Comment by corsix** [comment]
> I've seen here that the filename is != NULL but an empty string - IDK if this is valid as only NULL Is checked:

Other things aside, an empty filename doesn't seem right. It implies that `fopen` of an empty string succeeded at lj_cf_package_loader_lua > findfile > searchpath > readable, and again `fopen` of an empty string succeeded at luaL_loadfilex. The chunkname reported by your debugger also seems odd. The combination of the two raises the question of whether your debugger is feeding you misinformation.
