### ISSUE TITLE
C Callback crashing wxLua app

### ISSUE THREAD

**Issue by fenix272** [LuaJIT/LuaJIT#1228]
I'm using luajit with wxlua(binding for c++ wxwidgets). I've made a really simple http server library in C which receives data from a javascript web extension and stores it in a buffer. I use Luajit's ffi to start the C server which runs in another thread. To get the data posted to the server i've used a "pull approach". I start a wxTimer in wxLua and every some seconds i check if there is data in the C buffer. All works pretty well. Recently i tried to use the callback approach, a' la javascript, which to me seems more natural. The C server invokes the callback i registered when starting it whenever it receives some data.  In the callback itself i just store the data in a Lua table and a wxTimer periodically checks if there is any.  I thought it would work like a charm, instead i get random crashes.  Why the crashes?  Is it because 2 different threads are accessing the same Lua table? But isnt the same for the "pull approach" also? 2 different threads accessing the same C array, one to store the data and one to read it. But there there is no crash(at least until now). Are callbacks not worth it then?(Mike said that they are slow and one should use them only when really necessary). Or am i doing something wrong with them?

**Comment by MikePall** [comment]
Not clear what you're exactly doing, so can't comment on it.

The safest approach for inter-thread communication is to use messages, e.g. via POSIX `socketpair` or Windows Message Queues. GUI toolkits typically have API functions for adding other event sources to their main event loop. This allows you to process messages synchronously in a handler. No need for polling, either.

For details please refer to the GUI toolkit documentation and support forums.

**Comment by fenix272** [comment]
Thank you for your answer Mike.  Yes, i found exactly the solution you suggested. Thank you again
