### ISSUE TITLE
Building for PSP

### ISSUE THREAD

**Issue by tpimh** [LuaJIT/LuaJIT#1233]
I am trying to build LuaJIT for PSP (32-bit LE MIPS). I thought, since platforms like PS3 and PS Vita are already supported, that wouldn't be a problem.

I've got the following error: `Only o32 ABI supported for MIPS32`

What does it take to port LuaJIT to PSP?

**Comment by corsix** [comment]
Miscellaneous internet sources suggest that PSP toolchains default to the EABI rather than the O32 ABI. EABI is different to O32, but it doesn't look _massively_ different.

**Comment by tpimh** [comment]
If you are interested in investigating, it's pretty easy to get PSP toolchain up and running locally using Docker: `docker run -ti -v .:/source pspdev/pspdev` ([more info](https://pspdev.github.io/quickstart.html))
