### ISSUE TITLE
luajit allocator leak 1 handle on mpv

### ISSUE THREAD

**Issue by wbtcpip2** [LuaJIT/LuaJIT#1237]
on windows, creating and terminating an mpv instance with libmpv leaks 1 handle if luajit is enabled.

https://github.com/mpv-player/mpv/issues/14472

https://github.com/mpv-player/mpv/issues/14451

https://github.com/mpv-player/mpv/pull/14457

i've been told that the handle comes from luajit allocator, i would better off reporting to you. It is not related to mpv.

could you please invetsigate the problem?

**Comment by MikePall** [comment]
The recent updates to the referenced discussion make it clear the leak is in MPV, not LuaJIT.
