### ISSUE TITLE
syntax error when creating a label after the break statement

### ISSUE THREAD

**Issue by cerealpxl** [LuaJIT/LuaJIT#1238]
I am running this using [LÖVE](https://github.com/love2d/love)

![image](https://github.com/LuaJIT/LuaJIT/assets/83312057/df557cfc-b1ba-44b6-bb17-dfb5adc628be)

It's strange because when I put the break inside a block(do break end), it runs normally

**Comment by MikePall** [comment]
This is one of the differences between Lua 5.1 (where this fails) and Lua 5.2 (where this is allowed).

If you build LuaJIT with `LUAJIT_ENABLE_LUA52COMPAT` defined, then you get the Lua 5.2 behavior for `break` (amongst [other changes](https://luajit.org/extensions.html#lua52)).
