### ISSUE TITLE
`LUA_LJDIR` doesn't respect `INSTALL_LJLIBD`

### ISSUE THREAD

**Issue by GitSparTV** [LuaJIT/LuaJIT#1239]
Makefile allows to change `INSTALL_LJLIBD`, in our installation we changed the folder name in it.
`LUA_LJDIR` is used in default `package.path` and since it is fixed, `jit.*` libraries are not found, because they were installed in different folder

**Comment by fesily** [comment]
Use the env var `LUA_PATH` `LUA_CPATH`

**Comment by MikePall** [comment]
Thank you for the suggestion! I've added the changes so overriding `INSTALL_LJLIBD` is reflected in `package.path`.
