### ISSUE TITLE
Error while building: "Use only the provided Makefiles" when using provided Makefiles

### ISSUE THREAD

**Issue by anoraktrend** [LuaJIT/LuaJIT#1241]
```
./lj_err.c:498:2: error: "Broken build system -- only use the provided Makefiles!"
  498 | #error "Broken build system -- only use the provided Makefiles!"
      |  ^
```
I'm on iglunix (linux without many gnu components), if that helps at all

**Comment by corsix** [comment]
I assume you're using the latest git commit of LuaJIT, but it would be good to confirm what revision you're using.

I suspect similar to #1154; with either `gcc` or `grep` behaving strangely. If you're avoiding GNU components, then `gcc` presumably gives `clang`, but `grep` could be one of several non-GNU implementations. Could you try the exploratory steps in https://github.com/LuaJIT/LuaJIT/issues/1154#issuecomment-1919415709?

This area has already caused issues in the past with busybox's `grep` and OSX's `grep`. At some point it might become less hassle to replace the `grep` invocation with a `minilua` invocation.

**Comment by anoraktrend** [comment]
>I assume you're using the latest git commit of LuaJIT, but it would be good to confirm what revision you're using.

haven't check the master branch yet, but the 2.1 branch, and even the 2.0 branch were having issues. 

>If you're avoiding GNU components, then gcc presumably gives clang,

we are using CC=cc (or clang) for instead of making gcc a link to clang, (I could do that though).
 
>grep could be one of several non-GNU implementations.

Grep is busybox's grep... I'm scratching my head because Luv builds fine. I will check out that comment and report back if trying the master version or trying something there works.

**Comment by anoraktrend** [comment]
> Grep is busybox's grep... I'm scratching my head because Luv builds fine. I will check out that comment and report back if trying the master version or trying something there works.

Slight correction: it's freebsd's grep

>Could you try the exploratory steps in #1154 (comment)?
the readelf we have doesn't have a -w option, but similarly, both greps output 1.

**Comment by anoraktrend** [comment]
it's a good thing gnu's grep isn't in coreutils, it's the only one that isn't broken when this is considered.

**Comment by MikePall** [comment]
I'm absolutely not fond of that line in the Makefile. But it works for the 'common' target toolchain combinations, so closing as WONTFIX.

I don't want to add an extra dependency on `tr` (too many different implementations) or complicate that line any futher.

`minilua` might be an alternative, with some intermediate dependencies. But `minilua` will eventually be removed when DynASM is no longer needed (SSAcode interpreter).
