### ISSUE TITLE
luaL_loadfilex in low memory situations

### ISSUE THREAD

**Issue by Assumeru** [LuaJIT/LuaJIT#1249]
`luaL_loadfilex` uses `lua_pushfstring` a few times under the assumption that it won't "throw". However, `lua_pushfstring` sometimes needs to grow its buffer and ends up calling `lj_mem_realloc`. `lj_mem_realloc` calls `lj_err_mem` if allocation failed, which in this context ends up terminating the program.

In the case where `fopen` succeeded and `lua_pushfstring(L, "@%s", filename)` failed, this means `fclose` is never called. Probably fine since the program terminates anyway, but still.

Secondarily, it means that `luaL_loadfilex` can crash a program instead of returning `LUA_ERRMEM` like might be expected.

**Comment by MikePall** [comment]
The `luaL_loadfile*` functions are documented to potentially throw an OOM.

But I've fixed the file descriptor leak. Thanks!

**Comment by corsix** [comment]
Is there still potential for a leak if the `lua_pushfstring` within `if (ferror(ctx.fp))` OOMs?

**Comment by MikePall** [comment]
Fixed. Thanks!
