### ISSUE TITLE
msvcbuild.bat does not work

### ISSUE THREAD

**Issue by Mellnik** [LuaJIT/LuaJIT#1256]
Running ```msvcbuild.bat``` does nothing when run in x64 Native Tools Command Line Prompt.

Specs:
- Windows 11 Pro x64
- Visual Studio Community 2022 17.11.1

Output:
```
C:\Lib\LuaJIT\src>msvcbuild.bat

C:\Lib\LuaJIT\src>cl /nologo /c /O2 /W3 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_STDIO_INLINE=__declspec(dllexport)__inline host\minilua.c
minilua.c

C:\Lib\LuaJIT\src>link /nologo /out:minilua.exe minilua.obj
   Creating library minilua.lib and object minilua.exp

C:\Lib\LuaJIT\src>if exist minilua.exe.manifest mt /nologo -manifest minilua.exe.manifest -outputresource:minilua.exe

C:\Lib\LuaJIT\src>minilua ..\dynasm\dynasm.lua -LN -D WIN -D JIT -D FFI -D ENDIAN_LE -D FPU -D P64 -o host\buildvm_arch.h vm_x64.dasc

C:\Lib\LuaJIT\src>if exist ..\.git (git show -s --format=%ct   1>luajit_relver.txt )  else (type ..\.relver   1>luajit_relver.txt )
```

Trying an old commit https://github.com/LuaJIT/LuaJIT/commit/51fb2f2c3af778f03258fccee9092401ee4a0215 works just fine.

**Comment by corsix** [comment]
Perchance, is thing called `git` on your path actually a batch file rather than a native executable?

**Comment by Mellnik** [comment]
Uff you are right. ```where git``` shows git.bat from the Google depot tools that I've installed.
I've replaced the ```git``` with ```git.exe``` in the msvcbuild.bat and now it works just fine.
Thank you very much!
