### ISSUE TITLE
Luajit + Ipopt

### ISSUE THREAD

**Issue by Lorenzo-maker** [LuaJIT/LuaJIT#1259]
Hi, I'm trying to solve an optimal control problem inside lua using Ipopt library that implement an efficient interior point method to solve nonlinear programming problem. I'm able to import the ipopt.dll file inside lua and to call through the ffi module the functions that I need. These functions and the code itself runs correctly until line 102. At this line, lua calls ipoptsolver and it solves the problem correctly, in fact i can see correct ipopt output in the terminal. However, after this line the code seems to stop. The last line of the code are not executed. It seems that when ipopt finishes to solve the problem, something stops the lua execution. However, no errors appears and I have no idea how to debug it. Could you help me debugging ?
Here you can find the code.

`
local ffi = require("ffi")

-- Load the IPOPT shared library
ffi.cdef[[
typedef int Bool;
typedef int Index;
typedef double Number;
typedef void* IpoptProblem;

IpoptProblem CreateIpoptProblem(Index n, Number* x_L, Number* x_U,
                                Index m, Number* g_L, Number* g_U,
                                Index nele_jac, Index nele_hess, void* user_data,
                                Bool (*eval_f)(Index n, Number* x, Bool new_x, Number* obj_value, void* user_data),
                                Bool (*eval_g)(Index n, Number* x, Bool new_x, Index m, Number* g, void* user_data),
                                Bool (*eval_grad_f)(Index n, Number* x, Bool new_x, Number* grad_f, void* user_data),
                                Bool (*eval_jac_g)(Index n, Number* x, Bool new_x, Index m, Index nele_jac,
                                                   Index* iRow, Index* jCol, Number* values, void* user_data),
                                Bool (*eval_h)(Index n, Number* x, Bool new_x, Number obj_factor, Index m, Number* lambda,
                                               Bool new_lambda, Index nele_hess, Index* iRow, Index* jCol, Number* values,
                                               void* user_data));

void FreeIpoptProblem(IpoptProblem problem);
enum IpoptStatus IpoptSolve(IpoptProblem problem, Number* x, Number* g, Number* obj_value, Number* mult_g, Number* mult_x_L, Number* mult_x_U, void* user_data);
int AddIpoptNumOption(IpoptProblem problem, const char* keyword, double val);
int AddIpoptStrOption(IpoptProblem problem, const char* keyword, const char* val);
]]

local libipopt = ffi.load("ipopt-3.dll")

-- Define the objective function: f(x) = x1^2 + x2^2
local function eval_f(n, x, new_x, obj_value, user_data)
    obj_value[0] = x[0] * x[0] + x[1] * x[1]
    return 1
end

-- Define the gradient of the objective function
local function eval_grad_f(n, x, new_x, grad_f, user_data)
    grad_f[0] = 2.0 * x[0]
    grad_f[1] = 2.0 * x[1]
    return 1
end

-- Define the constraint: g(x) = x1 + x2 - 1 = 0
local function eval_g(n, x, new_x, m, g, user_data)
    g[0] = x[0] + x[1] - 1.0
    return 1
end

-- Define the Jacobian of the constraints
local function eval_jac_g(n, x, new_x, m, nele_jac, iRow, jCol, values, user_data)
    if values == nil then
        iRow[0] = 0; jCol[0] = 0
        iRow[1] = 0; jCol[1] = 1
    else
        values[0] = 1.0
        values[1] = 1.0
    end
    return 1
end

-- Hessian is not required for this simple problem, so we provide a dummy function
local function eval_h(n, x, new_x, obj_factor, m, lambda, new_lambda, nele_hess, iRow, jCol, values, user_data)
    return 1
end

-- Problem dimensions
local n = 2
local m = 1
local nele_jac = 2
local nele_hess = 0  -- Hessian is not used

-- Variable bounds
local x_L = ffi.new("double[2]", {-1e19, -1e19})
local x_U = ffi.new("double[2]", {1e19, 1e19})

-- Constraint bounds
local g_L = ffi.new("double[1]", {0.0})
local g_U = ffi.new("double[1]", {0.0})

-- Initial guess
local x = ffi.new("double[2]", {0.5, 0.5})

-- Create IPOPT problem
local problem = libipopt.CreateIpoptProblem(n, x_L, x_U, m, g_L, g_U, nele_jac, nele_hess, nil,
    eval_f, eval_g, eval_grad_f, eval_jac_g, eval_h)

-- Solve the problem
--local status = ffi.new("int[1]")
local obj_value = ffi.new("double[1]")
local g = ffi.new("double[1]")
local mult_g = ffi.new("double[1]")
local mult_x_L = ffi.new("double[2]")
local mult_x_U = ffi.new("double[2]")

libipopt.AddIpoptNumOption(problem, "tol", 1e-7);

libipopt.AddIpoptStrOption(problem, "mu_strategy", "adaptive");
libipopt.AddIpoptStrOption(problem, "output_file", "ipopt.out");

local status = libipopt.IpoptSolve(problem, x, g, obj_value, mult_g, mult_x_L, mult_x_U, nil)
print(status)
-- Output the solution
print("Solution status:", status[0])
print("Solution: x1 =", x[0], "x2 =", x[1])
print("Objective value:", obj_value[0])

-- Clean up
--libipopt.FreeIpoptProblem(problem)

`

**Comment by Lorenzo-maker** [comment]
Here the terminal output, As you can see after all the Ipopt output (which are correct from my experience), the last lua code lines (referring to print command) are not executed.

`PS C:\Users\blore\Documents\lua-code> luajit hello.lua

******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit https://github.com/coin-or/Ipopt
******************************************************************************

This is Ipopt version 3.14.16, running with linear solver MUMPS 5.6.2.

Number of nonzeros in equality constraint Jacobian...:        2
Number of nonzeros in inequality constraint Jacobian.:        0
Number of nonzeros in Lagrangian Hessian.............:        0

Total number of variables............................:        2
                     variables with only lower bounds:        0
                variables with lower and upper bounds:        0
                     variables with only upper bounds:        0
Total number of equality constraints.................:        1
Total number of inequality constraints...............:        0
        inequality constraints with only lower bounds:        0
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:        0

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  5.0000000e-01 0.00e+00 0.00e+00   0.0 0.00e+00    -  0.00e+00 0.00e+00   0

Number of Iterations....: 0

                                   (scaled)                 (unscaled)
Objective...............:   5.0000000000000000e-01    5.0000000000000000e-01
Dual infeasibility......:   0.0000000000000000e+00    0.0000000000000000e+00
Constraint violation....:   0.0000000000000000e+00    0.0000000000000000e+00
Variable bound violation:   0.0000000000000000e+00    0.0000000000000000e+00
Complementarity.........:   0.0000000000000000e+00    0.0000000000000000e+00
Overall NLP error.......:   0.0000000000000000e+00    0.0000000000000000e+00


Number of objective function evaluations             = 1
Number of objective gradient evaluations             = 1
Number of equality constraint evaluations            = 1
Number of inequality constraint evaluations          = 0
Number of equality constraint Jacobian evaluations   = 1
Number of inequality constraint Jacobian evaluations = 0
Number of Lagrangian Hessian evaluations             = 0
Total seconds in IPOPT                               = 0.002

EXIT: Optimal Solution Found.`

**Comment by sonoro1234** [comment]
IpoptStatus is not defined. Who knows?

**Comment by Lorenzo-maker** [comment]
I fixed it by changing the type of IpoptStatus inside cdef from enum to int. In fact, this output will be an integer that define the status of the solved problem, as solved succed (return 1) or maximum iteration reached (return -1) etc.

**Comment by sonoro1234** [comment]
> print("Solution status:", status[0])

indexing an int?

**Comment by Lorenzo-maker** [comment]
Yes the indexing status[0] was a typo, in fact I removed it now. Ipopt is c++ but can be used with c/api. I downloaded the latest compiled version for windows x64 from here https://github.com/coin-or/Ipopt/releases
