### ISSUE TITLE
`cannot convert function to void (*)()` when assigning to function pointer with by-value argument

### ISSUE THREAD

**Issue by Clemapfel** [LuaJIT/LuaJIT#1260]
Steps to reproduce:

```lua
ffi = require "ffi"
ffi.cdef[[
typedef struct SubStruct {} SubStruct;
typedef struct Struct
{
    void (*fn_pointer_sub_ptr)(SubStruct* x);
    void (*fn_pointer_sub_value)(SubStruct x);
} Struct;
]]
local test = ffi.typeof("Struct")()
test.fn_pointer_sub_ptr = function(x) end    -- l16, no error
test.fn_pointer_sub_value = function(x) end   -- l17, error
```
```
main.lua:17: cannot convert 'function' to 'void (*)()'
```

When assigning to a function pointer whose signature has at least one argument that is another struct passed by value, this error appears. The signature of `fn_pointer_sub_value` is `void(*)(SubStruct)`, not `void(*)()`. 

This error appears no matter where the by-value argument is in the signature, for example assigning any function to

```C
void (*fn_pointer_sub_three)(float x, int y, SubStruct z, void* w);
```

throws the same exact error. From my testing, the exact definition of `SubStruct` has no impact on the error.

**Comment by MikePall** [comment]
That's expected. Quoting https://luajit.org/ext_ffi_semantics.html#callback:
> Neither C vararg functions nor functions with pass-by-value aggregate argument or result types are supported.
