### ISSUE TITLE
Segfault when print's upvalue is not a string

### ISSUE THREAD

**Issue by GitSparTV** [LuaJIT/LuaJIT#1264]
On [2.1.1724512491](https://github.com/LuaJIT/LuaJIT/commit/f725e44cda8f359869bf8f92ce71787ddca45618) this code produces a segfault.

```lua
= debug.setupvalue(print, 1, nil)
```

Segfaults on regular build, and assert with `-DLUA_USE_ASSERT`

```
LuaJIT ASSERT lib_base.c:516: lj_cf_print: tvisstr((&((GCobj *)((((L->base-2)->gcr).gcptr64) & (((uint64_t)1 << 47) - 1)))->fn.c.upvalue[(1)-1]))
```

**Comment by MikePall** [comment]
The `debug` library is defined as unsafe. There are tons of ways to produce a crash with it.
