### ISSUE TITLE
ffi.cast different results in 32 bits and 64 bits LuaJIT

### ISSUE THREAD

**Issue by sonoro1234** [LuaJIT/LuaJIT#1270]
This code
```Lua
local ffi = require"ffi"
local a = ffi.cast("void*",5)
print(a)
print(ffi.cast("uintptr_t",a))
print(ffi.cast("uintptr_t",5))
print(ffi.cast("uintptr_t",5))
print(ffi.cast("unsigned int",5))
```
on 32bit LuaJIT returns

````
cdata<void *>: 0x00000005
cdata<unsigned int>: 0x001e7930
cdata<unsigned int>: 0x001e8550
cdata<unsigned int>: 0x001e38f8
cdata<unsigned int>: 0x001e1c30
````

on 64bit LuaJIT returns

````
cdata<void *>: 0x00000005
5ULL
5ULL
5ULL
cdata<unsigned int>: 0x001de290
````

I dont understand the meaning of this results

**Comment by corsix** [comment]
`uintptr_t` is, by its nature, a different type on 32 bits versus 64 bits: it is equivalent to `uint32_t` on 32 bits, and it is equivalent to `uint64_t` on 64 bits. You're then seeing the different behaviour of `__tostring` on cdata objects:
- For pointers, the reported pointer is the contents of the cdata object.
- For integers smaller than 8 bytes, the reported pointer is the address of the cdata object.
- For 8 byte integers, you get the contents of the cdata object, followed by `LL` or `ULL` (noting that LuaJIT's parser recognises such things as cdata literals).

**Comment by sonoro1234** [comment]
Thanks for the insights!!

I didnt know: `For integers smaller than 8 bytes, the reported pointer is the address of the cdata object.`

In fact this code
```Lua
local b = ffi.cast("uintptr_t",5)
print(b, ffi.cast("void*",b))
```
returns in 64bit

````
5ULL    cdata<void *>: 0x00000005
````

and in 32 bit

````
cdata<unsigned int>: 0x0011a548 cdata<void *>: 0x00000005
````
