### ISSUE TITLE
An incorrect error message in jit.on and jit.off

### ISSUE THREAD

**Issue by ligurio** [LuaJIT/LuaJIT#1274]
The functions `jit.off()` and `jit.on()` [^1] expects a Lua function as argument.
However, passing a Lua function that actually is a `FFUNC` leads to a wrong error message (`function expected, got function`) that confuses:

```sh
> jit.off(rawget)    
stdin:1: bad argument #1 to 'off' (function expected, got function)
stack traceback:
        [C]: in function 'off'
        stdin:1: in main chunk
        [C]: at 0x5dd2a5880310
> 
> jit.on(rawget)
stdin:1: bad argument #1 to 'on' (function expected, got function)
stack traceback:
        [C]: in function 'on'
        stdin:1: in main chunk
        [C]: at 0x5dd2a5880310
> 
```

`jit.on()` and `jit.off()` are a good way to distinguish a fast function and a regular Lua function, but I propose to fix the aforementioned error message with a patch below:

```diff
--- a/src/lib_jit.c
+++ b/src/lib_jit.c
@@ -56,6 +56,8 @@ static int setjitmode(lua_State *L, int mode)
     else
       mode |= LUAJIT_MODE_FUNC;
   }
+  if (isffunc(funcV(L->base)))
+    lj_err_callermsg(L, "function expected, got fast function");
   if (luaJIT_setmode(L, idx, mode) != 1) {
     if ((mode & LUAJIT_MODE_MASK) == LUAJIT_MODE_ENGINE)
       lj_err_caller(L, LJ_ERR_NOJIT);
```

[^1]: https://luajit.org/ext_jit.html

**Comment by MikePall** [comment]
Granted, the error message may confuse people who are not familiar with the VM internals. But I doubt a cosmetic improvement of the error message matters to them.  The conclusion in both cases will be: "this doesn't work, don't do this".

Also, v3.0 doesn't have fast functions anymore, so this would be obsolete by then.
