### ISSUE TITLE
Can't get it to properly install in Windows.

### ISSUE THREAD

**Issue by SuppliedOrange** [LuaJIT/LuaJIT#1277]
Attempting to build with "make" in cygwin
```console
> make clean
del luajit.exe libluajit.a lua51.dll host\minilua.exe host\buildvm.exe lj_vm.S lj_bcdef.h lj_ffdef.h lj_libdef.h lj_recdef.h lj_folddef.h host\buildvm_arch.h luajit.h luajit_relver.txt jit\vmdef.lua *.o host\*.o *.obj *.lib *.exp *.dll *.exe *.manifest *.pdb *.ilk
Could Not Find C:\Users\Dhruv\Desktop\G-Shortcuts\Chained Together\ChainedTogether\Binaries\Win64\Mods\CTChatMod\luajit\src\lj_vm.S
Could Not Find C:\Users\Dhruv\Desktop\G-Shortcuts\Chained Together\ChainedTogether\Binaries\Win64\Mods\CTChatMod\luajit\src\host\buildvm_arch.h
"HOSTCC    host/minilua.o"
"HOSTLINK  host/minilua.exe"
"VERSION   luajit.h"
"DYNASM    host/buildvm_arch.h"
"HOSTCC    host/buildvm.o"
"HOSTCC    host/buildvm_asm.o"
"HOSTCC    host/buildvm_peobj.o"
"HOSTCC    host/buildvm_lib.o"
"HOSTCC    host/buildvm_fold.o"
"HOSTLINK  host/buildvm.exe"
"BUILDVM   lj_vm.o"
"CC        lj_assert.o"
"CC        lj_gc.o"
"BUILDVM   lj_ffdef.h"
"CC        lj_err.o"
lj_err.c: In function 'lj_err_unwind_win':
lj_err.c:271:31: error: 'STATUS_LONGJUMP' undeclared (first use in this function)
     if (rec->ExceptionCode == STATUS_LONGJUMP &&
                               ^~~~~~~~~~~~~~~
lj_err.c:271:31: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile:709: lj_err.o] Error 1
```

Attempting to build via the `msvcbuilt.bat` works, but I get this error:
```console
> ./luajit/src/luajit -b scripts/pollnet.lua pollnet_compiled.lua
luajit.exe: unknown luaJIT command or jit.* modules not installed
```

### System information
I'm on an `x64 Windows 10`.
This is my `gcc` version:
```console
gcc (MinGW.org GCC-6.3.0-1) 6.3.0
```

### Reason:
The point of me trying to get this working is to get another library `pollnet` working which relies on `ffi`. I'll be using UE4SS (Unreal Mod Loader) which does not allow you to use dependencies from luarocks, meaning I need to build all of them myself and include it within the mod.

**Comment by corsix** [comment]
See https://github.com/LuaJIT/LuaJIT/issues/1187#issuecomment-2065516623.

**Comment by SuppliedOrange** [comment]
I have tried all Cygwin, MinGW and VS methods. Cygwin and MinGW hit the same error above.

**Comment by MikePall** [comment]
This looks like an ancient version of MinGW. According to https://www.mingw-w64.org/downloads/ the MSYS2 Windows installer is at GCC 14.

Also, the VS build worked just fine. You need to follow the [Windows install instructions](https://luajit.org/install.html#windows) to be able to invoke the internal `jit.*` modules (which is what `-b` does).
