### ISSUE TITLE
Union initializer ignored? when jitted

### ISSUE THREAD

**Issue by fogfx** [LuaJIT/LuaJIT#128]
Highly artificial/simplified example:

```
local ffi = require("ffi")
local u = ffi.typeof("union { double d; int64_t i; }")

-- working loop
for i = 1, 100 do
    local v = u()
    v.d = i

    assert(v.d == i)
end

-- failing loop
for i = 1, 100 do
    local v = u(i)

    assert(v.d == i)
end
```

Seems to work fine if the union has only one member, though.

(I realize throwaway union objects aren't the best idea, but still...)

2.1 HEAD, x64.

**Comment by CapsAdmin** [comment]
there's a thread on this here with some patches (though the patches might not be correct):

http://www.freelists.org/post/luajit/Flat-initializer-list-for-union-of-unnamed-struct-fields

the conclusion is sadly "it's not trivial nor high priority"



For your simplified example I would cast.

If you want to literally convert numbers (serializing?) you can do this:
```
ffi.cast("uint64_t *", ffi.new("double[1]", 5))[0]
>> 4617315517961601024ULL

ffi.cast("double *", ffi.new("uint64_t[1]", 4617315517961601024ULL))[0]
>> 5
```
But I'm just guessing.

What do you really want to do with unions?

**Comment by fogfx** [comment]
I did see that thread, but the unions I'm using only contain scalar types.

> What do you really want to do with unions?

Type punning. Actually I've ported LuaJIT's RNG to Lua so that I could have multiple RNGs, and this is where I noticed this as there's a stage where you have to start messing with the bits in a double.

> If you want to literally convert numbers (serializing?) you can do this:
> 
> ffi.cast("uint64_t *", ffi.new("double[1]", 5))[0]
> >> 4617315517961601024ULL
> 
> ffi.cast("double *", ffi.new("uint64_t[1]", 4617315517961601024ULL))[0]
> >> 5

Does this not violate strict aliasing rules, though? I thought LuaJIT allowing type punning through unions to be a concession to this.

**Comment by CapsAdmin** [comment]
This is a late response but I don't know the details so I was waiting for someone else to respond. But I just found out this issue already exists here. See #20
