### ISSUE TITLE
Strange perfromance on Apple Silicon MacOS when LuaJIT is used in MacOS app.

### ISSUE THREAD

**Issue by sfence** [LuaJIT/LuaJIT#1280]
I have a lua_benchmarks script and if I run it from `luajit` standalone binary it takes around 0.15 seconds to finish (Tested `luajit` from brew and self-build). If I run the same script from LuaJIT integrated into the MacOS app running on Apple Silicon and build for arm64, it takes around 16 - 20 seconds.

Here is a test app I created to find out what is going on:
https://github.com/sfence/luajit_app

Benchmark script: https://github.com/sfence/luajit_app/blob/master/luajit_app/lua_benchmark.lua

It does not happen for the same app build for x86_64 running on Apple Silicon.

It looks like `mmap` function on the MacOS commonly "ignore" hint if LuaJIT is integrated into the app.

Screenshots are at the end of this post.

I did some experiments. Like add `MAP_JIT `flag and `allow-jit` entitlement etc., but the effect of it is unpredictable and in my case always temporary (in my case typically a few first runs performance was good (0.15 seconds), and later it fell again to 16-20 seconds.).

I also tried removing the line `lj_trace_err(J, LJ_TRERR_MCODEAL);  /* Give up. OS probably ignores hints? */` in `mcode_alloc`, and it takes effect in the test `luajit_app` (benchmark time falls to less than 0.2 seconds ) but causes a freeze when I tried that version of LuaJIT with Minetest.

From `printf` I saw that `mmap` in cases where bad performance always allocates the same block of memory, no matter what hint value was. It looks like documented behaviors of `mmap` on MacOS:
```
     The addr argument is used by the system to determine the starting address
     of the mapping, and its interpretation is dependent on the setting of the
     MAP_FIXED flag.  If MAP_FIXED is specified in flags, the system will try
     to place the mapping at the specified address, possibly removing a
     mapping that already exists at that location.  If MAP_FIXED is not
     specified, then the system will attempt to use the range of addresses
     starting at addr if they do not overlap any existing mappings, including
     memory allocated by malloc(3) and other such allocators.  Otherwise, the
     system will choose an alternate address for the mapping (using an
     implementation dependent algorithm) that does not overlap any existing
     mappings.  In other words, without MAP_FIXED the system will attempt to
     find an empty location in the address space if the specified address
     range has already been mapped by something else.  If addr is zero and
     MAP_FIXED is not specified, then an address will be selected by the
     system so as not to overlap any existing mappings in the address space.
     In all cases, the actual starting address of the region is returned.  If
     MAP_FIXED is specified, a successful mmap deletes any previous mapping in
     the allocated address range.  Previous mappings are never deleted if
     MAP_FIXED is not specified.
```

So maybe there is a collision with other memory allocator functions?

Screenshots:

![luajit_time](https://github.com/user-attachments/assets/dff3f4b1-3d09-44bb-91d0-6ecf69a655da)
`CaptureLuaOutput` takes 98.3% of total CPU time.
![luajit_profiler](https://github.com/user-attachments/assets/76b35265-6894-4142-a1a6-e380fc04ed2b)
By my diagnostic, it comes from here:
![luajit_breakpoint](https://github.com/user-attachments/assets/69ad4253-478b-47ed-878d-550f72d7456f)

**Comment by sfence** [comment]
Some examples of captured `mcode_alloc_at` results from `mcode_alloc`:
```
Failed for try 1 hint 0xff890000 siz 65536 range 65011712 target 0x100740000 with p 0x10ff74000
Failed for try 1 hint 0xfe9c0000 siz 65536 range 65011712 target 0x100740000 with p 0x10ff74000
Failed for try 1 hint 0x102620000 siz 65536 range 65011712 target 0x100740000 with p 0x10ff34000
Failed for try 1 hint 0x100c40000 siz 65536 range 65011712 target 0x100740000 with p 0x10ff34000
Failed for try 1 hint 0xfe7c0000 siz 65536 range 65011712 target 0x100740000 with p 0x10ff34000
Failed for try 1 hint 0x100030000 siz 65536 range 65011712 target 0x100740000 with p 0x10ff34000
Failed for try 1 hint 0xfec90000 siz 65536 range 65011712 target 0x100740000 with p 0x10ff34000
```

**Comment by svermeulen** [comment]
I spent a bunch of time testing my high performance luajit based osx app on apple silicon and also found very strange performance characteristics.  Just want to report my experience here in case it's useful.  I would find that the performance would vary wildly, sometimes being incredibly slow, sometimes being quite fast.  I know that LuaJIT performance is expected to vary wildly, but this was on a much larger scale than I am used to (like a doubling or halving in speed)

Between this and the other [apple silicon issue](https://github.com/LuaJIT/LuaJIT/issues/285), for now I am hoping to keep using intel builds and rely on the rosetta 2 emulation.  It is slower most of the time but seems more consistent so far

**Comment by MikePall** [comment]
Looks like a duplicate of #285.
