### ISSUE TITLE
Is enabling of FFI on Nintendo Switch Possible

### ISSUE THREAD

**Issue by Clemapfel** [LuaJIT/LuaJIT#1281]
I currently don't have access to a switch to test, does someone know if modifying the build script to remove the `-LUAJIT_DISABLE_FFI` from https://github.com/LuaJIT/LuaJIT/blob/v2.1/src/nxbuild.bat#L72 would allow me to `require "ffi"` and call into C shared libraries on Switch? I'm unsure of whether if it is disabled for specific technical or legal reasons. Thank you

**Comment by MikePall** [comment]
Console SDKs lack functions to do dynamic symbol binding (`dlopen()`, `dlsym()` etc.). And JIT compilation is not allowed on consoles, so the FFI would be pretty slow, anyway.
