### ISSUE TITLE
There is an issue with the result of a 64 bit integer

### ISSUE THREAD

**Issue by merrykate** [LuaJIT/LuaJIT#1286]
local hex_value = 0x003A870003860F23
local decimal_string = string.format("%u", hex_value)
print(decimal_string)  

In x64 systems, it will output: 16473982778085156, but when I use a calculator to calculate, the correct output is: 16473982778085155. At the same time, in Lua 5.3 and above versions, the correct output will also be: 16473982778085155

**Comment by wuxindao** [comment]
如果我是接收一个参数，这个参数long类型的，我怎么附加 LL or ULL??

**Comment by stephenmax-zhang** [comment]
> 如果我是接收一个参数，这个参数long类型的，我怎么附加 LL or ULL??

english

**Comment by wuxindao** [comment]
> > 如果我是接收一个参数，这个参数long类型的，我怎么附加 LL or ULL??
> 
> english

long 类型变量 local l1=99999999999999LL
我并不知道l2参数的来源
function test1(l2){
l2 = l2 .. LL  --这样写???? 
print(l2)
}

**Comment by wuxindao** [comment]
> > 如果我是接收一个参数，这个参数long类型的，我怎么附加 LL or ULL??
> 
> english

Long type variable local l1=999999999999999LL
I don't know the source of the l2 parameter
function test1(l2){
L2=l2.. LL -- Write it like this????
print(l2)
}

**Comment by CapsAdmin** [comment]
> > > 如果我是接收一个参数，这个参数long类型的，我怎么附加 LL or ULL??
> > 
> > 
> > english
> 
> Long type variable local l1=999999999999999LL I don't know the source of the l2 parameter function test1(l2){ L2=l2.. LL -- Write it like this???? print(l2) }

```lua
-- with ffi
local ffi = require("ffi")
local num_to_u64 = ffi.typeof("uint64_t")
local num_to_i64 = ffi.typeof("int64_t")

-- without ffi
local num_to_u64 = function(num) return num + 0ULL end 
local num_to_i64 = function(num) return num + 0LL end

-- without ffi + runtime compatibility with vanilla lua
local _0ULL = _G.jit and loadstring("return 0ULL")() or 0
local _0LL = _G.jit and loadstring("return 0LL")() or 0

local num_to_u64 = function(num) return num + 0ULL end 
local num_to_i64 = function(num) return num + 0LL end

-- without ffi + runtime compatibility with vanilla lua while using some third party "BigInt"-type library
local tonumber_u64 = function(str) return _G.jit and loadstring("return ".str.."ULL")() or BigInt(str) end
```
Also note that assert(type(0LL) == "cdata"), and not "number"

Obviously, casting a double to u/i64 is mostly pointless as you'd be limited by double's min max range.

**Comment by wuxindao** [comment]
> > > > 如果我是接收一个参数，这个参数long类型的，我怎么附加 LL or ULL？？
> > > 
> > > 
> > > 英语
> > 
> > 
> > 长类型变量 local l1=999999999999999LL 我不知道 l2 参数函数 test1（l2）{ L2=l2..LL -- 像这样写????打印 （L2） }
> 
> ```lua
> -- with ffi
> local ffi = require("ffi")
> local num_to_u64 = ffi.typeof("uint64_t")
> local num_to_i64 = ffi.typeof("int64_t")
> 
> -- without ffi
> local num_to_u64 = function(num) return num + 0ULL end 
> local num_to_i64 = function(num) return num + 0LL end
> 
> -- without ffi + runtime compatibility with vanilla lua
> local _0ULL = _G.jit and loadstring("return 0ULL")() or 0
> local _0LL = _G.jit and loadstring("return 0LL")() or 0
> 
> local num_to_u64 = function(num) return num + 0ULL end 
> local num_to_i64 = function(num) return num + 0LL end
> 
> -- without ffi + runtime compatibility with vanilla lua while using some third party "BigInt"-type library
> local tonumber_u64 = function(str) return _G.jit and loadstring("return ".str.."ULL")() or BigInt(str) end
> ```
> 
> 还要注意 assert（type（0LL） == “cdata”），而不是 “number”
> 
> 显然，对 u/i64 施放双倍基本上毫无意义，因为你会受到双倍的最小最大范围的限制。

thank you
