### ISSUE TITLE
msvcbuild.bat: Amalgamated and Static builds not supported together

### ISSUE THREAD

**Issue by namandixit** [LuaJIT/LuaJIT#1289]
I tried to build a amalgamed static build and realized that passing `amalg` to the script ignores the `static` keyword due to there being no `@shift` [between these two lines](https://github.com/LuaJIT/LuaJIT/blob/97813fb924edf822455f91a5fbbdfdb349e5984f/src/msvcbuild.bat#L105-L106). Is this intentional? If yes, please document it [here](https://luajit.org/install.html#distro).

**Comment by MikePall** [comment]
Fixed. Thanks!
