### ISSUE TITLE
[ffi.metatype]ctype with metatable cause incorrect value of  member variable 

### ISSUE THREAD

**Issue by M1NGS** [LuaJIT/LuaJIT#1297]
I realized the game character control by attaching metatable to SDL_Rect. it working well util I added the direction variable as the basis for flipping the picture, a strange situation occurred. When I rewrote the direction to 0, it was 1 when I read it the next moment, or the value was assigned to 0 and read to 1.

I have tested it under several LuaJIT 64/32bit versions and it can be reproduced stably.
 when i turn off JIT, everything working well.
please see the attached minimal reproducible code.

![a73cb8466dff07ab16751a23eaa17b5b](https://github.com/user-attachments/assets/8560d16a-e67f-45fd-8d96-00d529ad4dba)

[metatype.zip](https://github.com/user-attachments/files/17572238/metatype.zip)

**Comment by MikePall** [comment]
The `direction` field is part of the `__index` of a metatable of a cdata type. Modifying it is not allowed. And it most certainly should be an instance field, not a class field, in any case.

Quoting https://luajit.org/ext_ffi_api.html#ffi_metatype
> Creates a ctype object [...] and associates it with a metatable. [...] Neither the contents of the `metatable` nor the contents of an `__index` table (if any) may be modified afterwards.
