### ISSUE TITLE
Can `ffi.load()` return nil instead of throwing error and exit?

### ISSUE THREAD

**Issue by gyatpear** [LuaJIT/LuaJIT#1299]
It would be more convenient if `ffi.load()` returns nil instead of throwing errors and halt the program.

In my project, I want to test if lib*something*.so exist and call its APIs, or run other Lua codes. However, it is halted when loading failed.

**Comment by MikePall** [comment]
```Lua
local ok, lib = pcall(ffi.load, "something")
if not ok then
  ok, lib = pcall(ffi.load, "somethingelse")
  if not ok then
    error("missing something")
  end
end
```
