### ISSUE TITLE
use FFI call variadic c function with uint32/int32 parameter failed

### ISSUE THREAD

**Issue by M1NGS** [LuaJIT/LuaJIT#1306]
Such as printf family functions

```lua
local ffi = require("ffi")

ffi.cdef [[
    int printf(const char *format, ...);
]]

local printf = ffi.C.printf

local u = ffi.new("uint32_t[1]", 100)

local ull = ffi.new("uint64_t[1]", 100)


printf("32bit unsigned %u\n", u[0])

printf("64bit unsgined %llu\n", ull[0])

printf("32bit unsigned %u, 64bit unsgined %llu\n", u[0], ull[0])

printf("64bit unsigned %u, 32bit unsgined %llu\n", ull[0], u[0])
``` 

WSL2 Ubuntu 64bit
LuaJIT 2.1.1727870382

> 32bit unsigned 0
> 64bit unsgined 100
> 32bit unsigned 100, 64bit unsgined 0
> 64bit unsigned 100, 32bit unsgined 0

Win11 MinGW32
LuaJIT 2.1.1731601260

> 32bit unsigned 0
> 64bit unsgined 100
> 32bit unsigned 0, 64bit unsgined 430576304128
> 64bit unsigned 100, 32bit unsgined 0

**Comment by MikePall** [comment]
The [documentation for FFI vararg calls](https://luajit.org/ext_ffi_semantics.html#convert_vararg) shows how to use a boxed scalar to pass 32 bit integers.

An array of scalars is not the same as a boxed scalar. The `u[0]` dereference converts the value back to a Lua number, which is then passed as a double to the vararg function.

This example works:
```Lua
local ffi = require("ffi")
ffi.cdef[[
int printf(const char *, ...);
]]
local u = ffi.new("uint32_t", 100)
ffi.C.printf("%u\n", u)
```
