### ISSUE TITLE
Add bytecode assembler

### ISSUE THREAD

**Issue by miko1112** [LuaJIT/LuaJIT#1307]
I've been looking for a resource for assembling the output of the `-bl` command line option, but it seems most community-made projects and documentation relating to LuaJIT only support/document the bytecode of up to version 2.0. I believe that officially supporting the ability to directly experiment with LuaJIT's bytecode would be quite interesting.

**Comment by MikePall** [comment]
The project itself doesn't have a need for this, so you'd have to do this outside of this repo.

Writing bytecode by hand is not recommended, anyway. There are just too many subtle details the interpreter and the JIT compiler rely on.

Even for v3.0 the plan is to write plain Lua code for all builtin operators and functions. The bootstrap flowcode generation step applies context-specific maps to strength-reduce it to elementary ops. E.g. the expression `a + b` would generate some kind of `ADD* a b`  flowcode op.
