### ISSUE TITLE
luajava question

### ISSUE THREAD

**Issue by dayo05** [LuaJIT/LuaJIT#1317]
I am working on [Java ported LuaJit](https://github.com/gudzpoz/luajava) and I got crash on my project.

My simplified logic flow is following:
1. Create object on JVM that wraps Lua side function.

This is my code written on Kotlin:
```kt
class LuaFunc(private val lua: Lua, loc: Int = -1) {
    init {
        if (!lua.isFunction(loc))
            throw Exception("Lua function expected but got ${lua.type(loc)}")
        lua.pushValue(loc)
    }

    val ref = lua.ref()

    fun call(vararg values: Any) {
        lua.refGet(ref)

        var a = 0
        for (x in values) a += LuaMain.pushNoInline(lua, x)

        lua.pCall(a, 0)
    }

    fun finalize() {
        // commented because this may execute on other thread
        // lua.unref(ref)
    }
}
```
The instance will created like `LuaFunc(lua, 1)` on Lua-C function.

2. Invoke received function on dedicated lifecycle(but on same thread. I asserted them)
3. Finalize first instance
4. Repeat one more

When I proceed 4, JVM crashes on JNI part.

[This is my crash dump](https://github.com/user-attachments/files/18096557/hs_err_pid14699.log)

At there, I figure out `gc_traverse_thread` function crashes.

I want to know general cases that leads `gc_traverse_thread` crash.

Thanks

**Comment by MikePall** [comment]
Sorry, but you may have better luck reporting this to the luajava project.

**Comment by dayo05** [comment]
This may not related to luajava because that library only does some automated(forced) `lua_checkstack` call and FFI, which not affects to main logic. But Ill report it to them too.

**Comment by dayo05** [comment]
About a month of debugging, I found the issue caused by misunderstood of coroutine system.
