### ISSUE TITLE
proto_chunkname returns binary contents if used on stripped bytecode

### ISSUE THREAD

**Issue by Lyrth** [LuaJIT/LuaJIT#1319]
The Lua-side functions `debug.getinfo` and `jit.util.funcinfo` rely on C `proto_chunkname` to obtain the `source` value, which would return garbage if used on stripped bytecode, e.g., from `string.dump(..., true)`.

```lua
debug.getinfo(load(string.dump(function() end, true))).source
```
The above line on LuaJIT latest will produce a string of bytes `\x1BLJ\x02\x0A`[...], which does not seem intended.

For reference, Lua 5.3 using the same line of code will just give the string `=?`.

**Comment by MikePall** [comment]
The `load()` and `loadstring()` functions take a second parameter, which is the name of the chunk. If omitted, the loaded content is used as the chunk name. In the stripped case `debug.getinfo()` has no source file name and falls back to the chunk name.

I.e. you're getting back the binary bytecode itself. So, this is not some random stuff from memory.

To avoid user confusion, I've forced the chunk name to `=?` for this particular case. Thanks!
