### ISSUE TITLE
Optimize a % b in a loop?

### ISSUE THREAD

**Issue by SoniEx2** [LuaJIT/LuaJIT#137]
Is there any way to optimize a loop of this kind?

```lua
for i=2,1000 do
  if n % i == 0 then
    return i
  end
end
```

This construct isn't used very often but, if possible, would be a nice optimization to have.

**Comment by bjoe2k4** [comment]
assuming n is an integer and in this particular example, how about:
```
return 1
```

**Comment by SoniEx2** [comment]
Uh, oops, I thought I skipped 1 .-.

**Comment by MikePall** [comment]
Apart from the useless example and the rare occurrence, a division with a non-constant divisor is already optimal.

In other words: Don't write code like that (in whatever language).

**Comment by SoniEx2** [comment]
Uh, I was trying to get you to help me factor large numbers...

**Comment by corsix** [comment]
Efficient factoring of large numbers isn't the kind of thing a compiler should spot and try to optimise.
