### ISSUE TITLE
String buffer API

### ISSUE THREAD

**Issue by MikePall** [LuaJIT/LuaJIT#14]
A string buffer API  allows efficient incremental construction of a string. The crucial detail is that this allows postponing the decision when to intern the string, if at all. E.g. some `io.*` builtins could be extended to output the string buffer data without an intermediate string interning.

The 2.1 JIT compiler already has some optimizations for typical incremental string construction. But these cannot eliminate all intermediate string allocations, especially for the typical head + loop + tail construction.

The first implementation should probably use a special userdata type (see `UDTYPE_*` in `lj_obj.h`) and only allow a very limited number of operations. One could use the same approach as `require("table.new")` for gentle introduction of a new `string.buffer()` constructor in the core string.\* library namespace.

At a later stage, the string buffer could be made an alias for the core string type. This would implicitly intern the string for any function that expects a plain string, but would open optimization opportunities for many other builtins like `string.sub()`. Since this requires changes to the core of the type system, this should be discussed separately and in context, e.g. for the new GC.

[Please do not infest this issue with a discussion of ropes (string views with links to parent strings). The latter are only useful for very specific scenarios (like an editor), but harmful when used for a generic string type. E.g. the JVM has recently overhauled their rope-based string representation and replaced it with a much simpler co-located string type (same as used in Lua/LuaJIT). That decision was backed by extensive benchmarking, since it wasn't a simple change, for sure.]

**Comment by kostja** [comment]
This is what we use for buffers:

https://github.com/tarantool/tarantool/blob/1.6/src/lua/buffer.lua

The underlying implementation: 

https://github.com/tarantool/tarantool/blob/1.6/src/lib/small/ibuf.h

**Comment by drbo** [comment]
@kostja seems to have a good approach.  It has the following advantages:
 - The FFI calls are already compiled.
 - Provides easy access to constituent pointers.  This can be useful for (say) FFI code.
The only issue that I can identify is that its type is wrong: `cdata`, not `userdata` or `string`.  One solution I have thought of is to give string buffers a special metatable, whose address is known to the VM.  The VM then treats `cdata` objects with this metatable specially. `__metatable` in this metatable is set to `nil`, so it is not possible to retrieve this metatable (except with the C API or debug library).

I could be wrong, but this was one solution that came to my mind.

**Comment by katlogic** [comment]
The disadvantage with @fsfod 's approach in #88 is the need for special-cased buffer access in place of strings _everywhere_. Without having a chimera to strings, is there even a point to bother LuaJIT with it at all? While it is possible to mutilate string access macros/functions most of the time (API and trace recorder) to prevent most of code duplication, resizable buffers break the "pointer stays" API contract - we can never expose buffers which mimic strings to 3rd party C API code which does lua_tostring().

Instead, we could make it very clear to the user that buffers can move in memory - by offseting the responsibility for (re)allocation on the user code.

It is alternative, and utterly hackish, approach - https://github.com/katlogic/ljx/commit/9b1a52c133afe01720345aa3653eff70da107d2d

Simply allow user to convert arbitrary C pointer to GCstr, and put a barrier in IR after the cast to TValue to avoid the optimizer's assumption that strings don't change (if there is one).

Obviously, this cannot give us completely transparently resizable buffers, but:
* The implementation is very simple
* User has to be aware that strings constructed this way have unique pointer identity (ie not interned), just like arbitrary C buffer
* However almost all string APIs work with such a buffer (unless they perform rawequal expecting to see the string interned).
* All string.* read APIs you get are for free
* Writing can be done through the aliased pointer using FFI
* If there are aliasing issues regarding writes, we'd need to make trace recorder to distinguish such buffer-strings (just a flag somewhere in GCstr) and never cache values from there.

The API is intentionally this low level, though we could expose simple functions to either set GCstr fields and tell user how much space is needed to be reserved for the header, or just hardcode predefined cstruct in ctypes, so user code stays portable in the event the GCstr object changes.

Buffers are simply interned by call to buffer:sub(1). As for resizability - it's possible to allocate large buffer, then resize it to smaller, and use the rest of the memory after it for something else. Essentially user has to check if realloc moved the memory or not. If backing memory moved, user is responsible for constructing new object, updating references and never accessing the old chimera-TValue again.

**Comment by fsfod** [comment]
I should of listed this under future ideas but there could GCstr sized space negative of the buffers based pointer that could be filled in by APIs like lj_lib_checkstr to make string buffers transparently look like strings to most of the api as long as they don't leak GCstr ptr to stack/table/return value

**Comment by MikePall** [comment]
The basics are done. Further enhancements will follow. Closing here.
