### ISSUE TITLE
FFI: Package standard system headers

### ISSUE THREAD

**Issue by Positive07** [LuaJIT/LuaJIT#144]
types.h defines a lot of useful types that are mostly OS and architecture dependant, most of the time we have to define this types by hand and there are LOTS of them, and we have to take the system into account in order to match what the system expects.

Could LuaJIT FFI handle this internally? If so I would request this to be added.
I would like to know what the penalties are or if there is a reason why this isn't done.

**Comment by MikePall** [comment]
The key issue behind this is the desire to package and install standard system header files for convenient use by the FFI.

The main difficulties are:
* There's no easy way to automatically generate a 'sane' excerpt from the C headers typically provided by modern toolchains.
* The headers available at build time or install time may not match the libraries available at runtime. Especially if the build host is not the deployment host.
* The deployment host may not have any headers installed and/or shared libraries with versioned names only.
* Cross-arch or multilib builds make this task even trickier.
* You really don't want to package all definitions with an application. Only the subset of definitions that are actually used.
* CPP macros, conditional parts of headers etc. ... it's a mess.

In short: TANSTAAFL

**Comment by Positive07** [comment]
Well that seems like a good reason. This is pretty complex stuff. I would see this failing and wondering why it doesn't work as expected and taking the blame on LuaJIT when actually the system is so hard.

So I understand that it may be better to keep it simple so that users don't run into unexpected/undesired behaviour.

I'm closing this but if there is actual interest it may be opened up again

Thanks for taking your time to answer Mike! LuaJIT is the BEST!

**Comment by drbo** [comment]
@Positive07 This would be an excellent task for an external library.

**Comment by bigbes** [comment]
@drbo there's ljsyscalls, already.
