### ISSUE TITLE
Mixed charsets in the path to program which uses lua breaks "require" and file manipulation functions on Windows

### ISSUE THREAD

**Issue by Wohlstand** [LuaJIT/LuaJIT#150]
*Continue discussion at PR https://github.com/LuaJIT/LuaJIT/pull/148*

So, I'll explain what trouble I have and why I made workaround to force fopen() function in luajit understand paths encoded in UTF-8:

I have a cross-platform project (game engine) which uses lua-JIT (and plain lua 5.2 as backup for cases when JIT is not works or causes crashes) for scripting. Everything internally uses UTF-8: source codes are encoded into UTF-8, most of libraries are understands UTF8-encoded paths (SDL). On Linux and OS X I have no troubles with LuaJIT, but on Windows all libraries are fine except LuaJIT which doesn't accepts UTF-8 paths from C++ code, but when I encoding absolute paths into ANSI charset, it works fine until full path will contain mixed charsets or just contain characters from another locales, require() and other file manipulation functions are always fails.

For example, if program located in path (while Russian layout is default locale):
```
"C:\Users\Вася\Desktop\testing thing"
```
Program and lua are will work fine.

BUT, if path has a mixed Russian and Chinese charsets, or just Chinese while Russian locale is toggled:
```
"C:\Users\Вася\Desktop\我的朋友\testing thing"
```
"require" and possible os.* functions (not tested/fixed yet) are will always fail, and no matter which charset in the lua file.

UTF-8-encoded paths support in C side allows lua to work on those paths on Windows.
On Linux and OS X everything works fine without any workarounds. 

Anyway I agree that I must to implement next things to don't break functionality:
* passed string from "require" must be converted from ANSI into UTF-8 before it will be sent into _lua_fopen. Without this, "require" supports ASCII-only file names.
* passed strings from "os.*" file manipulation functions are must be converted from ANSI into UTF-8 before there are will be sent into _lua_fopen.

However, because lua 5.2 is not supports UTF-8 encoded scripts with strings, to take able to run program and lua scripts correctly from the paths with mixed charsets, scripts are must contain ASCII-only filenames/paths in the require/os.* functions. There are will work on computers with same locale, but on computers with different locale this script is unworkable until file-names are will be fixed.

I have same patch for a plain lua, but I kept that at my project repository.

**Comment by NukeRusich** [comment]
Are only filepaths affected by this issue?

**Comment by Wohlstand** [comment]
Yes.

fopen() function (used in PUC-Rio Lua and LuaJIT to open files) on Windows accepts ANSI encoded file paths. Therefore to correctly take access to path with mixed charsets, need to use _wfopen which accepts UTF-16 encoded strings and returns same file descriptor. 

On Linux, OS X and other unix-like operating systems fopen works fine with UTF-8 encoded strings (while most of modern operating systems are using UTF-8 for filenames on their drives), therefore is no troubles with file paths on those operating systems.

**Comment by NukeRusich** [comment]
You might want to take this to Lua (PUC-Rio) and tell us to add it whenever we're ready to update to a newer version of Lua. This issue is too obscure to be worth the effort.
