### ISSUE TITLE
Support for 64bit values in "for" loop

### ISSUE THREAD

**Issue by MageSlayer** [LuaJIT/LuaJIT#154]
Please implement support  64bit values in "for" loop.

for i=0LL,9LL do
  print(i)
end

This minimum example fails with:
luajit: 1.lua:1: 'for' initial value must be a number

Tested using LuaJIT 2.1 beta2 (0dcd2d129241964925e27831fa61194a8dbe6191)

The same loop using while statement like:
local i=0LL
while i<=9LL do
  print(i)
end
... works fine.

**Comment by kirbyfan64** [comment]
Pretty sure this has been brought up numerous times in the mailing list...

**Comment by MageSlayer** [comment]
It just means people still need it...

**Comment by TheNuke** [comment]
You mean "want" it. Pretty sure it's a "won't fix".

**Comment by MageSlayer** [comment]
Are you trying to say that nobody uses calculated ranges in "for" loop except me?
I mean:
```
for i=a+b,c+d do
   ...
end
```
If any of those variables have 64bit-ness, "for" loop suddenly stops working.

**Comment by MikePall** [comment]
Duplicate of #17.
