### ISSUE TITLE
Geting warnings when cross-compiling LuaJIT for MIPSEL arch

### ISSUE THREAD

**Issue by fdagostino** [LuaJIT/LuaJIT#155]
Hi there,
When cross-compiling LuaJIT v2.0.4 or v2.1.0-beta2 for MIPSEL arch, I'm getting the following warnings.

Build enviroment
============
- Windows XP / Mingw-w64 
- The toolchain is provided by vendor: "mipsel-linux-uclibc-" (cygwin) and can *not* be upgraded
- mipsel-linux-uclibc-gcc --version: 3.4.6 (I've modified lg_arch.h in order to avoid "need at least gcc 4.3 or newer" message).
- Compiling with following cmd:
  make HOST_CC="i686-w64-mingw32-gcc.exe -m32" CROSS=mipsel-linux-uclibc- TARGET_SYS=Linux CFLAGS="-DLUAJIT_ENABLE_LUA52COMPAT"

lj_mcode.c: In function `lj_mcode_sync':
lj_mcode.c:48: warning: implicit declaration of function `__clear_cache'
lj_mcode.c: In function `lj_mcode_sync':
lj_mcode.c:48: warning: implicit declaration of function `__clear_cache'
CC        lj_snap.o
lj_snap.c: In function `snap_restoredata':
lj_snap.c:657: warning: dereferencing type-punned pointer will break strict-aliasing rules
lj_snap.c:668: warning: dereferencing type-punned pointer will break strict-aliasing rules
lj_snap.c: In function `snap_restoredata':
lj_snap.c:657: warning: dereferencing type-punned pointer will break strict-aliasing rules
lj_snap.c:668: warning: dereferencing type-punned pointer will break strict-aliasing rules

Thanks,
Fran

**Comment by MikePall** [comment]
The check for a recent GCC is there precisely to avoid bogus reports about ancient compilers. GCC 3.4.6 is ten years old.

If you intentionally remove those checks, then you're on your own.
