### ISSUE TITLE
FFI: Possible memory leak?

### ISSUE THREAD

**Issue by bungle** [LuaJIT/LuaJIT#163]
I have been trying to figure out what's going on here:
https://github.com/bungle/lua-resty-libcjson/issues/6

It seems that something is leaking memory there. First I suspected that it was my code, but I have tried all the tricks I can, but have not found anything (maybe I just don't spot it). Then I thought it might be a problem with cJSON C library, so I opened an issue here:
https://github.com/kbranigan/cJSON/issues/33

Now I think it might be a problem with LuaJIT leaking memory.

How to reproduce:

1. download this: https://github.com/bungle/lua-resty-libcjson/blob/master/lib/resty/libcjson.lua
2. run this example:

```lua
local enc = require "libcjson".encode
local tbl  = { hello = "world" }

for _ = 1, 100000 do
    collectgarbage()
    collectgarbage()
    enc(tbl)
    collectgarbage()
    collectgarbage()
    print(collectgarbage("count")*1024)
end
```

On my machine it constantly outputs:
`46976`

But if I look LuaJIT process on some system monitor, I can see that memory usage of luajit is growing, and growing. Is it a problem on LuaJIT, I don't know? Is it a problem with my FFI binding, I don't know. Is it a problem with cJSON library, I don't know. But the garbage `count` prints the same number, so that's why I'm thinking that maybe there is a leak in LuaJIT? I did run this with:

```
LuaJIT 2.1.0-beta1 -- Copyright (C) 2005-2015 Mike Pall. http://luajit.org/
JIT: ON SSE2 SSE3 SSE4.1 fold cse dce fwd dse narrow loop abc sink fuse
```

But I suspect it may be a problem with other releases as well.

**Comment by corsix** [comment]
Your encode function appears to call cJSON_Print but not free the resulting
pointer (ffi.string will create a GC-managed string from the passed char*,
but it doesn't take ownership of the char*, so you still have to free it
yourself). See also
http://stackoverflow.com/questions/27394364/should-the-return-value-of-cjson-print-be-freed-by-the-caller

**Comment by bungle** [comment]
@corsix Indeed, thanks a lot!
