### ISSUE TITLE
Random failures in compiled code

### ISSUE THREAD

**Issue by iehrlich** [LuaJIT/LuaJIT#164]
Cross-posting here from the mailing list.

Dear all,

during the investigation of random core dumps in LuaJIT 2.0.4, I found an issue that's present in both master and 2.1 branches, which may lead to random failures with arbitrary symptoms on x86 and x86_64. The issue affects x86 and x86_64 targets, GNU/Linux confirmed, other OSes are most probably affected too. Such failures are extremely hard to reproduce, so I'll just dump the results of the investigation below.

First of all, during the compilation of a trace emitter produces the following mcode:
```
0xfa98b57: jne 0x1efbca7b
   # 0f 85 1e 3f 52 0f
0xfa98b5d: cmp DWORD PTR [rdx+0x274],0xfffffffb
   # 83 ba 74 02 00 00 fb
```
FTR, these are the last instruction of HREFK and the first instruction of HLOAD with "str" output type. Everything works fine until the compiler generates a side trace for this trace and starts patching the parent. The function lj_asm_patchexit scans parent trace byte-by-byte and eventually comes to the address 0xfa98b5c in attempt to find a six-byte side exit jcc pattern. As you may see, this is not an address of any particular valid instruction. The six-byte pattern here overlaps the last byte of jne and five bytes of cmp, looking like "0f 83 ba 74 02 00". Patcher tries to interpret this as a jcc instruction, and it __succeeds__, as "0f 83" works for it as an opcode and 0x274ba is the __exact relative offset__ from 0xfa98b5c to the stub of the side exit being patched (plus-minus 6, hope you get the idea).

As a result of this misinterpretation, bytes 0xfa98b5c through 0xfa98b5f are patched with the offset to the newly created side trace, resulting in...
```
0xfa98b57:  jne 0x1efbca7b
   # 0f 85 1e 3f 52 0f
0xfa98b5d:  and DWORD PTR [rsi],0x1b
   # 83 26 1b
0xfa98b60:  rex.WX (bad)
   # 00
0xfa98b63:  sti
   # fb
```
...and the application segfaults on 0xfa98b5d. Actually, that's the point where the investigation was started.

As it was said earlier, technically, you can get virtually any error here. This might be a SIGSEGV, or SIGILL. If you are lucky enough to encounter such an unlikely issue, you might even get no error with an unpredictable outcome.

Best regards,
Igor A. Ehrlich

**Comment by corsix** [comment]
This has already been fixed in both `master` and `v2.1` (although there was no annoucement as such). See e.g. https://github.com/LuaJIT/LuaJIT/commit/73680a5fc760cb39760e4bbfce1166ce75de237f

**Comment by iehrlich** [comment]
Wow. That was quick! Thanks! Should I close this issue?

**Comment by corsix** [comment]
Please.

**Comment by iehrlich** [comment]
Fixed, closing.

**Comment by iehrlich** [comment]
Dear all,

sadly this issue must be reopened. I ran some tests on the code and found at least one quite simple instruction that is decoded incorrectly.
The following sequence of x64 mcode bytes:
`test   BYTE PTR [r15+0x8],0x4`
`41 f6 47 08 04`
Is decoded incorrectly. I'm not sure if compiler currently emits such instructions, but this seems a pretty simple case to me. As long as instruction length decoder is now employed in trace patching, maybe we want to fix that and add some tests? I'm afraid that current approach will result in the situation when any new (not yet emitted) instruction will be able to screw trace patching.

I did not yet look through the implementation of this patch, it's possible that I'll be able to provide a hotfix for this particular issue shortly.

**Comment by corsix** [comment]
What was I thinking; handling of group 3 can't just skip modrm decoding. Patch follows:

```diff
diff --git a/src/lj_asm_x86.h b/src/lj_asm_x86.h
index 86a5b0a..02918e2 100644
--- a/src/lj_asm_x86.h
+++ b/src/lj_asm_x86.h
@@ -2836,9 +2836,9 @@ static uint32_t asm_x86_inslen(const uint8_t* p)
     case 4: result -= (prefixes & 2);  /* fallthrough */
     case 5: return result + (x & 15);
     case 6:  /* Group 3. */
-      if (p[1] & 0x38) return result + 2;
-      if ((prefixes & 2) && (x == 0x66)) return result + 4;
-      return result + (x & 15);
+      if (p[1] & 0x38) x = 2;
+      else if ((prefixes & 2) && (x == 0x66)) x = 4;
+      goto mrm;
     case 7: /* VEX c4/c5. */
       if (LJ_32 && p[1] < 0xc0) {
        x = 2;
```

**Comment by MikePall** [comment]
Applied.
