### ISSUE TITLE
FFI: `pure`, `readonly`, and `reentrant` attributes on function declarations

### ISSUE THREAD

**Issue by DemiMarie** [LuaJIT/LuaJIT#165]
A pure foreign function is one that has no side effects (not even dereferencing pointers passed as arguments); therefore, it can be optimized out when its result is not needed, and can be subject to CSE and other optimizations.  Examples are most of `math.h`.

A readonly foreign function is one that has no write side effects; therefore, it can be optimized out when its result is not used.  It is still okay if it dereferences pointers passed to it, provided that it does not write to the corresponding memory locations.

A reentrant foreign function is one that may call back into the same Lua state as the one that called it, directly or indirectly (note that calling into a _different_ Lua state has always been allowed).  This tells the LuaJIT VM to save VM state to allow for restoring it later.  Currently, this may simply disable JIT-compilation of the calling function, but later LuaJIT might be able to stitch the call or perhaps even compile it, without paying the overhead on every call.

**Comment by MikePall** [comment]
The benefit of defining and handling these kind of attributes is very, very limited in practice. Most FFI C functions are called explicitly and consciously only when needed. Very few people bother defining such attributes, even for pure C code.
