### ISSUE TITLE
Compile with -fvisibility=hidden

### ISSUE THREAD

**Issue by drbo** [LuaJIT/LuaJIT#166]
This allows the C compiler to generate better code and keeps LuaJIT's internals private.

**Comment by corsix** [comment]
This is already done where possible - see `#define LJ_NOAPI	extern __attribute__((visibility("hidden")))` in `lj_def.h`. Is there something in particular which you think should have this attribute but doesn't?

**Comment by corsix** [comment]
In the interest of tidiness, I'm going to interpret silence as "no".
