### ISSUE TITLE
Better error messages on API check failures

### ISSUE THREAD

**Issue by drbo** [LuaJIT/LuaJIT#167]
When LuaJIT is compiled with `-DLUA_USE_APICHECK`, C API misuse is detected by assertions.  However, these assertions give bad error messages.  A string that indicates the nature of the caller's mistake (stack index out of bounds, etc) should be provided.

**Comment by corsix** [comment]
One could blindly go through and twiddle the assertions, but do you have particular examples of errors you currently get versus what you'd like to get instead (or, better yet, a PR to that effect)?

**Comment by MikePall** [comment]
Closing as wontfix, due to lack of activity on behalf of the OP.
