### ISSUE TITLE
LUAJIT_USE_GDBJIT is not thread safe

### ISSUE THREAD

**Issue by iehrlich** [LuaJIT/LuaJIT#170]
There is no reproducer for this issue, but it is quite obvious, so I hope that this description will be enough.

Environment: generic multi-core x86/x64, Ubuntu Linux 12.04/14.04, possibly other platforms.

Enabling `LUAJIT_USE_GDBJIT `in multi-threaded application might cause random crashes. Since `__jit_debug_descriptor `list is not surrounded with any sort of synchronization primitives, simultaneous access/mutation might cause condition race and undefined behaviour.

It's been reported quite a number of times that creating two global states in two different host threads and near-simultaneous closing of such states might lead to segmentation faults around the mutation of this list. This was temporary fixed by adding mutexes in `lj_gdbjit_addtrace`/`lj_gdbjit_deltrace`.

In general, I see two options here:

1. Implement thread safety.
2. Introduce a note/comment/doc mentioning the issue and, maybe, proposing some sort of workaround.

Thanks.

**Comment by MikePall** [comment]
OK, so adding a spinlock avoids the crashes. But that would be pretty useless in practice.

The info provided by `LUAJIT_USE_GDBJIT` is bogus with multiple VMs. Each VM will define the exact same symbols (TRACE_1, TRACE_2, ...). They'll simply override each other. I doubt GDB has the internal data structures to attach different symbol contexts to different threads (but I haven't checked).

In other words: don't build with `LUAJIT_USE_GDBJIT`, if you're using multiple VMs in the same process.

Or, maybe someone misunderstood that feature: don't build with this flag at all, unless you're debugging the JIT compiler itself.

Given the limited nature of the LuaJIT GDB support, I'm not sure _anyone_ has actually made good use of it. The last time I tried to use it to debug some problem in the JIT compiler was a couple years ago ... and AFAIR it didn't improve matters over GDB + `-jdump`.

**Comment by corsix** [comment]
> Or, maybe someone misunderstood that feature: don't build with this flag at all, unless you're debugging the JIT compiler itself.

If you're debugging a C program which uses LuaJIT, and want to make it easy for GDB to generate backtraces when there is JITted code on the call stack, it is a useful flag to turn on. In this context, it doesn't particularly matter that there are several things all called `TRACE_1`; you're just happy to see `TRACE_1` in the backtrace, and also see the frames which come after it.

**Comment by MikePall** [comment]
OK, I can buy that argument. Applied.

**Comment by iehrlich** [comment]
I'll add a little bit more context here JIC.

> They'll simply override each other. I doubt GDB has the internal data structures to attach different symbol contexts to different threads (but I haven't checked).

Does not seem to be that way, but due to our most valuable use case, that does not matter. What matters is that symbol object array will contain `TRACE_1` entry for all threads where such trace will be present.

> Given the limited nature of the LuaJIT GDB support, I'm not sure anyone has actually made good use of it. The last time I tried to use it to debug some problem in the JIT compiler was a couple years ago ... and AFAIR it didn't improve matters over GDB + -jdump.

OK, here's the use case. A multi-threaded application invokes multiple VMs and runs them concurrently for, say, three days. After that, core is dumped with the host stack corrupted due to the inner frame is VM+trace. At this point, if `LUAJIT_USE_GDBJIT` is enabled, we are able to invoke GDB with the core file, traverse symbol array, find the exact entry for this trace (based on actual RIP), dump it, re-load GDB with this symbol file and get proper stack trace. Despite the complex description, this might be done automatically, which helps a lot. With broken support of multi-threading, this toolchain will not work properly.

Anyway, thanks for the fix. Is it possible that this will be (officially) backported to 2.0.5?

**Comment by MikePall** [comment]
Strictly speaking, this is an enhancement and thus only applies to 2.1. I don't want to break the 2.0 build under any circumstances.
