### ISSUE TITLE
Proposal: Three String Tables

### ISSUE THREAD

**Issue by funny-falcon** [LuaJIT/LuaJIT#171]
Proposal for fixing problem with hash collisions on interned strings:

- strings upto 11 bytes are stored in a separate small table, which is 1:1 as current code.
  with fixed loop: 
```diff
-      if (sx->len == len && str_fastcmp(str, strdata(sx), len) == 0) {
+      if (sx->hash == h && sx->len == len && str_fastcmp(str, strdata(sx), len) == 0) {
  ...
-      if (sx->len == len && memcmp(str, strdata(sx), len) == 0) {
+      if (sx->hash == h && sx->len == len && memcmp(str, strdata(sx), len) == 0) {
```
- larger strings are stored within two other tables
 - first string's hash is computed using "fast" approach
 - if "fast" table has no string or thumbstone with equal hash, then insert and finish
 - if there is thumbstone or string with equal hash, but different content, then "stronger" hash is computed.
 - Second table is looked up for. If there is no equal string:
 - and element in "fast" table were thumbstone, then thumbstone replaced with new string
 - and element in "fast" table were real string, new string is inserted into "strong" table
- in the end of GC marking phase, strings from "strong" table are traversed
 - "fast" hash is calculated for each string,
 - elements in "fast" table with same hashes are marked (strings and thumbstones)
- Corner case:
 - strings in "fast" table converted to "thumbstones" during sweep
 - to do it, during "strong" table traversion string in "fast" table, that were not marked before, marked with flag "convert to thumbstone" (using `unused` field in `GCstr`),
 - during lookup in "fast" table, string with "convert to thumbstone" mark could be found equal to new string. Perhaps, it is safe just clear "convert to thumbstone" mark and return this string.

This will lead to duplicated code in lj_str_new, using `GCstr.unused` for distinguishing thumbstones, more incremental GC steps.

- depending of performance/safety tradeoff one of "stronger" hash functions proposed:
 - fastest, but weakest (protection only from unintentional collisions): from https://github.com/LuaJIT/LuaJIT/pull/169
 - slower (fast as Murmur) but resistant to Seed Independent Collisions (I believe, it is): https://github.com/funny-falcon/funny_hash
 - cryptographically safe: SipHash13 for 64bit platform;
   and 32 bit variant for 32bit platform, for example https://github.com/funny-falcon/funny_hash/blob/master/others/csaphash.h
- probably, other (cause this list of functions look like my promotion)

**Comment by mraleph** [comment]
Here is a more radical thought: maybe some strings should never be interned. Ultimately interning is only relevant if you are doing `==` comparisons and/or you produce a lot of equivalent strings and want to save space. I think that interning large strings (~ computing hash for them) is just a waste of time in majority of use cases.

**Comment by fogfx** [comment]
@mraleph 5.2/5.3 already do this so it'd be interesting to see how this could work out for LuaJIT.

**Comment by CapsAdmin** [comment]
I have no idea about jit and compilers and stuff but is it also possible to hash strings when it's important? (or just in time)

**Comment by funny-falcon** [comment]
uncontended case is also fast using this proposal, cause currently hashsum calculated using only 16bytes.
LuaJIT relies on hash+pointer string equality for generated native code and in the interpreter.
So, some one ought to change it to "hash+memcmp" for not interned strings.
I fill not brave enough to fix interpreter and jit. Do you?

**Comment by funny-falcon** [comment]
Obsoleted by https://github.com/LuaJIT/LuaJIT/pull/174
