### ISSUE TITLE
maxsd/minsd DynASM support

### ISSUE THREAD

**Issue by MageSlayer** [LuaJIT/LuaJIT#175]
Looks like mentioned commands are not supported by DynASM at the moment.

See a small patch to add support [here](https://gist.github.com/MageSlayer/299f5eb1a02f08604d86edd4ceaf1d9f)

**Comment by corsix** [comment]
These commands are, in fact, already supported, and your patch doesn't actually have any effect.

You're overlooking that `map_op` isn't _just_ a static list of instruction templates; it is also programatically extended, in this case by:
```lua
-- SSE / AVX FP arithmetic ops.
for name,n in pairs{ sqrt = 1, add = 8, mul = 9,
		     sub = 12, min = 13, div = 14, max = 15 } do
  map_op[name.."ps_2"] = format("rmo:0F5%XrM", n)
  map_op[name.."ss_2"] = format("rro:F30F5%XrM|rx/od:", n)
  map_op[name.."pd_2"] = format("rmo:660F5%XrM", n)
  map_op[name.."sd_2"] = format("rro:F20F5%XrM|rx/oq:", n)
  if n ~= 1 then
    map_op["v"..name.."ps_3"] = format("rrmoy:0FV5%XrM", n)
    map_op["v"..name.."ss_3"] = format("rrro:F30FV5%XrM|rrx/ood:", n)
    map_op["v"..name.."pd_3"] = format("rrmoy:660FV5%XrM", n)
    map_op["v"..name.."sd_3"] = format("rrro:F20FV5%XrM|rrx/ooq:", n)
  end
end
```
There are several ways to see the contents of `map_op` after all such mutations. One such way which I'm inclined to point out is [my reference](https://corsix.github.io/dynasm-doc/instructions.html#M).

**Comment by MageSlayer** [comment]
You are right. Thanks for info.
