### ISSUE TITLE
Help wanted: LuaJIT pros to contribute to Snabb

### ISSUE THREAD

**Issue by lukego** [LuaJIT/LuaJIT#177]
Howdy!

I would love to get some professional LuaJIT hackers involved in optimizing the [Snabb](https://www.github.com/snabbco/snabb) open source networking project. I will describe the project a little below and if this sounds interesting then please get in touch with me (`luke@snabb.co`).

Note: I will close this Issue in a few days to avoid clutter but this is an ongoing thing over years so don't hesitate to get in touch in the future.

We have created a happy community of application developers who are building high-end router-like network equipment in LuaJIT. We are patiently going through the process of learning to write LuaJIT code that is fast and predictable. We have a mix of skills in our community - networking, compilers, low-level programming - but not people who know LuaJIT internals well. I see this as a missing piece that would help us to develop an efficient coding style and improve the tools we use for measuring and optimizing performance.

There are several small and large companies doing business around Snabb these days and it would be great for us to know who we can call when we want help with LuaJIT optimization! I for one also have a backlog of such work that I would love to engage help on right away...

#### Quick start

If you want to get a really quick feel for the software then here is the quickest way to run a benchmark that is worth optimizing:

```
$ git clone https://github.com/snabbco/snabb
$ cd snabb
$ make -j
...
BINARY    2.3M snabb

# Run simple benchmark to process 100M synthetic packets
$ sudo src/snabb snabbmark basic1 100e6
Processed 100.2 million packets in 3.46 seconds (rate: 28.9 Mpps).

# ... and with JIT dump enabled
$ sudo src/snabb snsh -jdump=+rs -p snabbmark basic1 100e6
```

We have plenty more reproducible benchmarks that are always valuable to optimize. They all have the same basic theme: do something useful with network packets and stick to a ~ 200 cycle per packet total processing budget.

More sophisticated benchmarks usually run in the "Snabb Lab" which is a dozen servers with a few terabits worth of 10G/40G/100G network cards that everybody can ssh into for development.

#### Background

Here is a raw braindump with lots of links to illustrate our journey over these past few years. Loosely from newest to oldest. These all represent areas that would be interesting to continue digging into.

##### Snabb based projects

There are several projects based on the Snabb code base: Hypervisor switch, IPv4/IPv6 translator, VPN variants, DDoS protector, etc.

Here is a recent talk about one, Igalia's Snabb lwAFTR:

- Blurb: https://fosdem.org/2016/schedule/event/snabbswitch/
- Video: https://vimeo.com/157411603
- Slides: https://wingolog.org/pub/fosdem-2016-lwaftr-slides.pdf

##### Programming style

How do you write LuaJIT code such that it is easy to optimize? The latest (mostly untested) theory I have is that you want to write a series of short loops with no internal branches. In practice this can mean making several passes over an input (e.g. array of 100 network packets): for example first process only TCP packets, then process only UDP packets, then process the remaining packets. This can require a slightly contorted programming style, reminiscent of models like SIMT perhaps, and the expected benefit is for each loop to compile into a single trace of tight machine code that runs for (say) 1,000 CPU cycles at a time.

Open questions: Is this indeed the most important concern for writing predictably efficent programs? Should we rewrite all our code in this style? How can we factor such code in a convenient way?

- Related Github comment: https://github.com/snabbco/snabb/pull/879#issuecomment-212250596
- Related blog: lukego/blog#8 (and nearby linked entries).

##### Trace profiling

We have often found trace-level profiling important for optimizing code. Particularly finding and eliminating side-traces in performance sensitive code. This is still a laborious process, sometimes done entirely by hand and sometimes with basic tooling.

- By hand: https://github.com/snabbco/snabb/pull/612
- traceprof: https://github.com/snabbco/snabb/pull/623

##### Timeline

Timeline is a low-overhead logging facility (~20ns per message) intended to support both in-the-field diagnostics and in-the-lab optimization. This is a new experimental feature.

- doc: https://github.com/snabbco/snabb/blob/timeline/src/core/timeline.md
- code: https://github.com/snabbco/snabb/blob/timeline/src/core/timeline.dasl
- screenshots of frontend prototype: https://github.com/snabbco/snabb/pull/873#issuecomment-212258564

##### Assembler routines

Certain routines are key to performance and worth writing in assembler to maximize performance. Squeezing more performance out of these routines is always important -- as is writing a few new ones.

- Large table lookup: https://github.com/Igalia/snabb/blob/streaming-ctable/src/lib/binary_search.dasl
- IP checksum: https://github.com/snabbco/snabb/pull/899
- Packet dispatching (can't get it working well enough yet): https://github.com/snabbco/snabb/pull/813
- Packet copies (NYI): https://github.com/snabbco/snabb/issues/648

##### CI

Here are a few links to give an idea of the Continuous Integration infrastructure that we are building and using for tracking performance charactistics (etc) over time:

- We have a dozen servers and around 3,000 Gbps of 10G/40G/100G networking hardware all dedicated to use by open source developers.
- We have a Hydra CI: http://hydra.snabb.co/
- We are adopting statistical tools: https://github.com/snabbco/snabb/pull/778#issuecomment-189158350

## Summary

I hope that gives you an idea of what we are up to!

We are looking forward to many years of productive LuaJIT hacking and I would love to involve some people who know LuaJIT internals well. If this sounds interesting to you then please drop me a line on `luke@snabb.co` and I will find you a suitable problem to work on and pay you for your time.

Thanks for reading!

**Comment by MikePall** [comment]
Issues are not job advertising boards.
