### ISSUE TITLE
Illegal instruction on Mips

### ISSUE THREAD

**Issue by israellot** [LuaJIT/LuaJIT#178]
I get occasional **Illegal instruction** exit messages on mips32.
I'm using AR9331 and compiling with -march=mips32r2.

**Comment by MikePall** [comment]
Check your toolchain. You'll need to build with the proper soft-float ABI flags.

**Comment by sindrom91** [comment]
Could you provide a backtrace or at least a disassembly of surrounding instructions?
Also, if you are using FFI, make sure that your libraries are built for proper ABI (-msoft-float?).

**Comment by israellot** [comment]
I'm compiling it on OpenWrt

```
TARGET_CFLAGS+= -fPIC -march=mips32r2 -msoft-float
define Build/Compile
	$(MAKE) -C $(PKG_BUILD_DIR) HOST_CC="gcc -m32 -fPIC" CROSS=$(TARGET_CROSS) TARGET_CFLAGS="$(TARGET_CFLAGS)"  DESTDIR="$(PKG_INSTALL_DIR)" PREFIX=/usr 
	$(MAKE) -C $(PKG_BUILD_DIR) HOST_CC="gcc -m32 -fPIC" CROSS=$(TARGET_CROSS) TARGET_CFLAGS="$(TARGET_CFLAGS)"  DESTDIR="$(PKG_INSTALL_DIR)" PREFIX=/usr install
endef
```

Am I missing something obvious?

**Comment by israellot** [comment]
```
local s = ""

repeat

s=s.."a"
print("b: "..s)


until (s:len()==50)

print(s)
```

this snippet will generate a Illegal Instruction exit.

**Comment by sindrom91** [comment]
Are you getting any warnings when you build it like that? I am.
You can use TARGET_FLAGS instead of TARGET_CFLAGS or add -msoft-float to TARGET_LDFLAGS and TARGET_SHLDFLAGS.

**Comment by israellot** [comment]
The final CFLAGS are 
`TARGET_CFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -fPIC -march=mips32r2 -msoft-float" ` 
The other ones are added by the openwrt build system. Adding -msoft-float to TARGET_SHLDFLAGS and TARGET_LDFLAGS didn't solve it.

**Comment by israellot** [comment]
The float operations are fine, the problem seems to be on concatenating strings.

**Comment by israellot** [comment]
The problem seems to be on concatenating strings
This snippet 
```
local s = ""
local i =0
while i < 150 do
        s=s.."a"
        i=i+1   
end 
```
will exit with illegal instruction, while doing multiple float operations run just fine.

**Comment by sindrom91** [comment]
Could you try to ommit -mips16 and -minterlink-mips16 flags and let me know if that did any good?

**Comment by israellot** [comment]
That did the trick! Thank you @sindrom91

**Comment by milani** [comment]
I got the same issue. Why removing `-mips16` and `-minterlink-mips16` fixes the problem? Shouldn't be any improvement in the code to solve this?

**Comment by sindrom91** [comment]
LuaJIT does not support MIPS16 extension and it's very likely that minor changes can solve it.

I don't have time to look into this now, but I think that LuaJIT uses compressed call to jump to MIPS16 code. I can see that `emit_call` function in `lj_emit_mips.h:155` tries to use compressed call, if possible. You can force it to always use `else` and see if you still get an illegal instruction error.

**Comment by milani** [comment]
Yes I confirm that forcing it to always use `else` solves illegal instruction error. Should I send a pull request like below?

```
static void emit_call(ASMState *as, void *target, int needcfa)
{
  MCode *p = as->mcp;
  *--p = MIPSI_JALR | MIPSF_S(RID_CFUNCADDR);
  as->mcp = p;
  ra_allockreg(as, i32ptr(target), RID_CFUNCADDR);
}
```

**Comment by sindrom91** [comment]
Well, it's definitely suboptimal when compiled without `-mips16`, so I'd say that you need to detect if the flag is enabled (at compile time) and then check it in `emit_call` (add one more check to `if` statement). Also, you should probably run some more complex tests to make sure that's the only part that yields illegal instruction.

**Comment by MikePall** [comment]
I've added MIPS16 interlinking support.

But please note that building applications with `-minterlink-mips16` comes with a significant performance penalty for cross-module calls.

This can only be avoided with an amalgamated build. So better use `make amalg CROSS=...` to build LuaJIT.

**Comment by milani** [comment]
@MikePall How is amalgamated build different from a usual build regarding memory usage? I'm running on a board with only 128M of memory along with other processes running.

**Comment by MikePall** [comment]
Runtime memory usage doesn't change. An amalgamated LuaJIT binary is usually smaller and faster.

**Comment by milani** [comment]
Built and tested without `-minterlink-mips16` and `-mips16` flags with `amalg` enabled.  Works as expected.
