### ISSUE TITLE
Parse binary numbers 0bxxx

### ISSUE THREAD

**Issue by MikePall** [LuaJIT/LuaJIT#18]
Very useful for bit operations. The enhancement to the number parsing code should not be that hard.

But this should be synced up to a release, since it breaks source code compatibility. It either should make it into the code base for 2.1.0-final or not into 2.1 at all. Remove the label, if this is the case.

**Comment by creationix** [comment]
Implemented in https://github.com/LuaJIT/LuaJIT/pull/44.  I don't fully understand the purpose of all the local variables in the various parsers, but this appears to work in my tests.

Also, would you also like new unit tests for this?

**Comment by MikePall** [comment]
I guess you could attach some unit tests to this issue, for now. They'll be merged when we get the test suite rolling.
