### ISSUE TITLE
LuaJIT 2.1.0-beta2 hotloop optimization breaking correctness

### ISSUE THREAD

**Issue by joshuafcole** [LuaJIT/LuaJIT#180]
While using the latest LuaJIT available on brew (installed with `brew install --devel --with-52compat luajit` on OS X 10.11.5), hotloop optimization is breaking correctness on a trivial example. Unfortunately, this appears to be environment or hardware-specific, as my coworker cannot reproduce the bug with the same code and same LuaJIT version installed on a 4 year old macbook, but can reproduce it on his new iMac 5k. I've collected as much information as I can on the issue to try and help diagnose it, and I'm happy to provide any additional diagnostic information on request.

A minimal reproduction case for the issue follows:
```
math.randomseed(os.clock())
for i = 1, 120 do
   local val = math.random(10)
   if val < 0 or val > 10 then
      local kind = "none"
      if val < 0 then kind = "less" end
      if val > 10 then kind = "more" end
      print(val, kind)
   end
end
```
Example output:
```
10	none
2	none
7	none
8	none
9	none
10	none
9	none
5	none
7	none
10	none
5	none
10	none
2	none
3	none
```

The expected result is that nothing should be printed. However, stochastically one or more prints trigger, with kind = "none" and values in the range of 1..10 inclusive. The upper bound on the for loop (120) is not necessary to reproduce the bug, it just increases the probability of the bug occurring one or more times on a given run. Any number greater than the hotloop flag (default 56) is sufficient. Similarly, decreasing the value of the hotloop flag allows the bug to be reproduced with a lower upper bound.

Interestingly, different (but equally strange) issues occur when eliding one of the conditions of the outer if statement. E.g,
```
math.randomseed(os.clock())
for i = 1, 120 do
   local val = math.random(10)
   if val < 0 then
      local kind = "none"
      if val < 0 then kind = "less" end
      if val > 10 then kind = "more" end
      print(val, kind)
   end
end
```
Example output:
```
-2.7205499287627e+85	less
-3.9534533542751e+162	less
-7.4977761191095e+72	less
-1.2051856504094e+228	less
-9.0117823094763e+223	less
-2.7525934920099e+215	less
-8.2670892940875e+183	less
-4.7607760617757e+269	less
-2.4624396009012e+196	less
-72559489.510503	less
-3.7305609299049e+145	less
-5.6260335247273e+76	less
-5.280696595853e+179	less
-1.373248568573e+230	less
-7.5219770155876e+134	less
-8.7588279549506e+135	less
-5.6328787689073e+131	less
```
Similarly, including only the `val > 10` condition prints all values massive orders of magnitude greater than 0 and "more" as the kind.

The -jdump is included below for an even smaller reproduction. The problem shows up after the JIT recompiles the detected hotloop, as evidenced by the prints of `val` occurring after the recompilation trace.
```
math.randomseed(os.clock())
for i = 1, 120 do
   local val = math.random(10)
   if val < 0 or val > 10 then
      print(val)
   end
end
```
Output of `-jdump`
```
---- TRACE 1 start foo.lua:2
0011  GGET     4   0      ; "math"
0012  TGETS    4   4   4  ; "random"
0013  KSHORT   5  10
0014  CALL     4   2   2
0000  . FUNCC               ; math.random
0015  KSHORT   5   0
0016  ISLT     4   5
0017  JMP      5 => 0021
0018  KSHORT   5  10
0019  ISGE     5   4
0020  JMP      5 => 0024
0024  FORL     0 => 0011
---- TRACE 1 IR
0001    int SLOAD  #1    CI
0002    fun SLOAD  #0    R
0003    tab FLOAD  0002  func.env
0004    int FLOAD  0003  tab.hmask
0005 >  int EQ     0004  +63
0006    p32 FLOAD  0003  tab.node
0007 >  p32 HREFK  0006  "math" @54
0008 >  tab HLOAD  0007
0009    int FLOAD  0008  tab.hmask
0010 >  int EQ     0009  +31
0011    p32 FLOAD  0008  tab.node
0012 >  p32 HREFK  0011  "random" @8
0013 >  fun HLOAD  0012
0014 >  fun EQ     0013  math.random
0015    num CALLS  lj_math_random_step  ([0x03e9bf48])
0016    num SUB    0015  +1
0017    num MUL    0016  +10
0018    num FPMATH 0017  floor
0019    num ADD    0018  +1
0020 >  num UGE    0019  +0
0021 >  num ULE    0019  +10
0022  + int ADD    0001  +1
0023 >  int LE     0022  +120
0024 ------ LOOP ------------
0025    num CALLS  lj_math_random_step  ([0x03e9bf48])
0026    num SUB    0025  +1
0027    num MUL    0026  +10
0028    num FPMATH 0027  floor
0029    num ADD    0028  +1
0030 >  num UGE    0029  +0
0031 >  num ULE    0029  +10
0032  + int ADD    0022  +1
0033 >  int LE     0032  +120
0034    int PHI    0022  0032
---- TRACE 1 mcode 312
f4eafec3  mov dword [0x03e96410], 0x1
f4eafece  movsd xmm3, [0x03eb5c58]
f4eafed7  movsd xmm2, [0x03eb5c50]
f4eafee0  xorps xmm1, xmm1
f4eafee3  cvttsd2si ebp, [rdx]
f4eafee7  mov r15d, [rdx-0x8]
f4eafeeb  mov r14d, [r15+0x8]
f4eafeef  cmp dword [r14+0x1c], +0x3f
f4eafef4  jnz 0xf4ea0010	->0
f4eafefa  mov r13d, [r14+0x14]
f4eafefe  mov rdi, 0xfffffffb03e9bf10
f4eaff08  cmp rdi, [r13+0x518]
f4eaff0f  jnz 0xf4ea0010	->0
f4eaff15  cmp dword [r13+0x514], -0x0c
f4eaff1d  jnz 0xf4ea0010	->0
f4eaff23  mov r12d, [r13+0x510]
f4eaff2a  cmp dword [r12+0x1c], +0x1f
f4eaff30  jnz 0xf4ea0010	->0
f4eaff36  mov ebx, [r12+0x14]
f4eaff3b  mov rdi, 0xfffffffb03e9cb18
f4eaff45  cmp rdi, [rbx+0xc8]
f4eaff4c  jnz 0xf4ea0010	->0
f4eaff52  cmp dword [rbx+0xc4], -0x09
f4eaff59  jnz 0xf4ea0010	->0
f4eaff5f  cmp dword [rbx+0xc0], 0x03e9cae8
f4eaff69  jnz 0xf4ea0010	->0
f4eaff6f  mov edi, 0x03e9bf48
f4eaff74  call 0x103c6cdd0	->lj_math_random_step
f4eaff79  movq xmm0, rax
f4eaff7e  subsd xmm0, xmm2
f4eaff82  mulsd xmm0, xmm3
f4eaff86  roundsd xmm4, xmm0, 0x09
f4eaff8c  addsd xmm4, xmm2
f4eaff90  ucomisd xmm1, xmm4
f4eaff94  ja 0xf4ea0014	->1
f4eaff9a  ucomisd xmm4, xmm3
f4eaff9e  ja 0xf4ea0018	->2
f4eaffa4  add ebp, +0x01
f4eaffa7  cmp ebp, +0x78
f4eaffaa  jg 0xf4ea001c	->3
->LOOP:
f4eaffb0  mov edi, 0x03e9bf48
f4eaffb5  call 0x103c6cdd0	->lj_math_random_step
f4eaffba  movq xmm0, rax
f4eaffbf  subsd xmm0, xmm2
f4eaffc3  mulsd xmm0, xmm3
f4eaffc7  roundsd xmm7, xmm0, 0x09
f4eaffcd  movsd xmm0, [0x03eb5c58]
f4eaffd6  addsd xmm7, xmm2
f4eaffda  ucomisd xmm1, xmm7
f4eaffde  ja 0xf4ea0024	->5
f4eaffe4  ucomisd xmm7, xmm0
f4eaffe8  ja 0xf4ea0028	->6
f4eaffee  add ebp, +0x01
f4eafff1  cmp ebp, +0x78
f4eafff4  jle 0xf4eaffb0	->LOOP
f4eafff6  jmp 0xf4ea002c	->7
---- TRACE 1 stop -> loop

5
3
9
10
10
8
5
6
8
10
9
```
As best I have been able to discern, the generated assembly for the ->LOOP label looks healthy. Unless something is circumventing ff90 - ff9e and jumping directly to the print routines, or clobbering xmm1 prior to hitting the ->LOOP, or a faulty value is in 0x03eb5c58, I don't see how this could possibly be happening given that code. Any advice is much appreciated.

**Comment by corsix** [comment]
> While using the latest LuaJIT available on brew (installed with `brew install --devel --with-52compat luajit` on OS X 10.11.5)

It would be nice to take `brew` out of the picture. Can you still reproduce the problem with the following steps?
```
$ git clone http://luajit.org/git/luajit-2.0.git
$ cd luajit-2.0/src
$ git checkout v2.1
$ make
$ ./luajit foo.lua
```

One way of getting more information would be to dump the contents of all registers immediately after an exit is taken:
```
$ make clean
$ make CCDEBUG=-g
$ lldb ./luajit foo.lua
(lldb) b lj_vm_exit_handler
Breakpoint 1: where = luajit`lj_vm_exit_handler, address = 0x00000001000059f2
(lldb) run
Process 77670 launched: './luajit' (x86_64)
Process 77670 stopped
* thread #1: tid = 0x503394, 0x00000001000059f2 luajit`lj_vm_exit_handler, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
    frame #0: 0x00000001000059f2 luajit`lj_vm_exit_handler
luajit`lj_vm_exit_handler:
->  0x1000059f2 <+0>: push   r13
    0x1000059f4 <+2>: push   r12
    0x1000059f6 <+4>: push   r11
    0x1000059f8 <+6>: push   r10
(lldb) register read -a
General Purpose Registers:
...
Floating Point Registers:
...
Exception State Registers:
...
```

My first hypothesis would be that `lj_math_random_step` is clobbering various `xmm` registers (the x64 ABI allows it to, but the LuaJIT JIT assumes that it doesn't clobber any). Seeing how `lj_math_random_step` was assembled would be useful:
```
$ lldb ./luajit
(lldb) disassemble -F intel -n lj_math_random_step
luajit`lj_math_random_step:
luajit[0x100065790] <+0>:   mov    rax, qword ptr [rdi]
...
luajit[0x10006583b] <+171>: ret    
```

You could also try replacing `#define CCI_RANDFPR	CCI_NOFPRCLOBBER` with `#define CCI_RANDFPR	0` in `lj_ircall.h`, and then re-running:
```
$ make
$ ./luajit foo.lua
```

**Comment by joshuafcole** [comment]
I can confirm the issue doesn't occur on the v2.1 branch. Similarly, checking out and compiling `2.1.0-beta2`doesn't produce the problem. I also built using the brew formula's make parameters `make amalg XCFLAGS=-DLUAJIT_ENABLE_LUA52COMPAT` on the `2.1.0-beta2` branch and was unable to reproduce the bug. It seems plausible that the brew formula is to blame here, though I'm unsure exactly how. It may be fetching the wrong code or doing something funny under the covers.

**Comment by corsix** [comment]
Interesting. Could you share the faulty LuaJIT binary which brew created? (attach it to this issue, or email it to me, etc.)

**Comment by joshuafcole** [comment]
Sure thing, I found the formula (https://github.com/Homebrew/homebrew-core/blob/fb81645562f7e495a49561065912788af2d1f14f/Formula/luajit.rb) and it has a `--with-debug` flag to add `CCDEBUG=-g` to the build. The build with debugging symbols still shows the error. I've attached the executable (zipped to please github). I've also included the result of disassembling lj_math_random_step, which does seem to use `xmm1`, one of the registers in question.
```
(lldb) target create "/usr/local/bin/luajit"
Current executable set to '/usr/local/bin/luajit' (x86_64).
(lldb) disassemble -F intel -n lj_math_random_step
luajit`lj_math_random_step:
luajit[0x100018dd0] <+0>:   vmovdqu ymm0, ymmword ptr [rdi]
luajit[0x100018dd4] <+4>:   vpsllvq ymm1, ymm0, ymmword ptr [rip + 0x6cae3] ; luajit.__TEXT.__const + 576
luajit[0x100018ddd] <+13>:  vpxor  ymm1, ymm1, ymm0
luajit[0x100018de1] <+17>:  vpsrlvq ymm1, ymm1, ymmword ptr [rip + 0x6caf6] ; luajit.__TEXT.__const + 608
luajit[0x100018dea] <+26>:  vpsllvq ymm0, ymm0, ymmword ptr [rip + 0x6cb0d] ; luajit.__TEXT.__const + 640
luajit[0x100018df3] <+35>:  vpand  ymm0, ymm0, ymmword ptr [rip + 0x6cb25] ; luajit.__TEXT.__const + 670
luajit[0x100018dfb] <+43>:  vpor   ymm0, ymm1, ymm0
luajit[0x100018dff] <+47>:  vmovq  rax, xmm0
luajit[0x100018e04] <+52>:  vpextrq rcx, xmm0, 0x1
luajit[0x100018e0a] <+58>:  xor    rcx, rax
luajit[0x100018e0d] <+61>:  vextracti128 xmm1, ymm0, 0x1
luajit[0x100018e13] <+67>:  vmovq  rax, xmm1
luajit[0x100018e18] <+72>:  xor    rax, rcx
luajit[0x100018e1b] <+75>:  vpextrq rcx, xmm1, 0x1
luajit[0x100018e21] <+81>:  xor    rcx, rax
luajit[0x100018e24] <+84>:  vmovdqu ymmword ptr [rdi], ymm0
luajit[0x100018e28] <+88>:  mov    al, 0x34
luajit[0x100018e2a] <+90>:  bzhi   rcx, rcx, rax
luajit[0x100018e2f] <+95>:  movabs rax, 0x3ff0000000000000
luajit[0x100018e39] <+105>: or     rax, rcx
luajit[0x100018e3c] <+108>: vzeroupper
luajit[0x100018e3f] <+111>: ret
```

Thanks again for the speedy support, debugging this has been a very exciting experience.

[luajit.zip](https://github.com/LuaJIT/LuaJIT/files/271566/luajit.zip)

**Comment by joshuafcole** [comment]
I also notice that brew is somewhat rudely replacing CC in the makefile. I expect means it'll be using clang rather than gcc.
https://github.com/Homebrew/homebrew-core/blob/fb81645562f7e495a49561065912788af2d1f14f/Formula/luajit.rb#L30

**Comment by joshuafcole** [comment]
Since this isn't reproducible using the makefile directly, I'm totally content if you'd like to close this issue. I'll link against it and file a bug on brew. I'm not sure why they decided to swap CC in the makefile, but that seems like the likeliest culprit here.

**Comment by corsix** [comment]
FWIW, I can reproduce the problem by compiling with `make CCDEBUG=-g CCOPT_x64=-march=native`, at which point I also get a version of `lj_math_random_step` which has been vectorised and uses AVX and BMI2.

**Comment by slime73** [comment]
> I expect means it'll be using clang rather than gcc.

`gcc` is an alias for `clang` in modern versions of OS X anyway.

**Comment by joshuafcole** [comment]
Thanks for pointing that out, I'm not as familiar with the OS X toolchain as I am with Linux.

**Comment by corsix** [comment]
I wouldn't put any blame on `brew`; it is within its rights to specify `-march=native` or similar. Similarly, clang is within its rights to vectorise anything, and to use `xmm`/`ymm` registers as it sees fit. The fault lies in a LuaJIT optimisation which assumes that `lj_math_random_step` doesn't touch `xmm`/`ymm` registers (this optimisation was disabled for x86 - but not x64 - in 7dc9e5ad).

**Comment by MikePall** [comment]
I've unconditionally removed the optimization for `lj_math_random_step()`. Its effect was probably very minor, anyway.
