### ISSUE TITLE
64-bit Integer Hack

### ISSUE THREAD

**Issue by SoniEx2** [LuaJIT/LuaJIT#182]
Right now 64-bit integers in LuaJIT are done very inefficiently but LuaJIT could generate multiple IRs depending on how integers are passed around, think something like static analysis but dynamically.

TL;DR: tag types in bytecode, untag in IR, use "static" analysis to untag properly.

**Comment by mraleph** [comment]
Please don't file meaningless issues. If you think you have a great idea I suggest implementing it and submit a pull request. 

Additionally writing TL;DR after two lines of vague hand waving does not help, nothing here is "too long".

Thanks.

**Comment by SoniEx2** [comment]
The idea is that you'd have a fully-dynamically-typed Lua 5.3-like VM, then JIT that into statically-typed-ish IR/IL (this wouldn't be toggleable with -joff, -joff would only disable the IR/IL->machine code JIT, and this IR/IL JIT would be avaiable on all systems), which would run on an optimized VM which uses NaN tagging for things that can be done with NaN tagging or specific opcodes (i.e. static typing) for 64-bit integers.

Because you can't fit a 64-bit integer in a 64-bit NaN, creating statically-typed code out of dynamically-typed code seems to be the best option here.

**Comment by corsix** [comment]
I'm going to go out on a limb here and just say no. Firstly, LuaJIT is explicitly Lua 5.1+extensions, with no plans to be 5.2 or 5.3 any time soon. Your last paragraph already applies: LuaJIT's answer to 64-bit integers are FFI types, which are dynamic in the interpreter and static once JIT compiled. Your earlier paragraph is still hand-wavey IMO, and proposes a new totally different kind of interpreter, which isn't going to happen (unless you can put forward an extremely compelling argument, which thus far you haven't).

**Comment by SoniEx2** [comment]
Well the current design is garbage for 64-bit integers (including allocations each time they're used), and the totally new interpreter design would be 64-bit GC friendly. At least that's what I understood from what @MikePall once said on the mailing list or something. (I couldn't find the posts .-.)

**Comment by MikePall** [comment]
I strongly recommend reading https://en.wikipedia.org/wiki/Dunning%E2%80%93Kruger_effect

**Comment by SoniEx2** [comment]
@MikePall What did you mean when you talked about the NaN tagging stuff?

**Comment by cztk** [comment]
I wanted to implement https://github.com/blep/luajit_perf_poc/commit/499f88d91d39aac58ec8127c0fc9ad21374a4bf3 to see if it allows me to make alot of stuff from existing code available like that.
However it may not be ideal or future proof to use 32-Bit integers on new implementations. It also mentions https://gist.github.com/nddrylliog/8722197
Fine, there is another ugly hack https://github.com/lostsnow/lua-int64-x ( Readme says it's ugly )

So having no int64 for a while will lead to ugly hacks, maybe that's what @SoniEx2 really wanted to say
