### ISSUE TITLE
Atomic operations

### ISSUE THREAD

**Issue by DemiMarie** [LuaJIT/LuaJIT#185]
While Lua states are single-threaded, it is possible to have many Lua states in the same process.  These states can run in parallel on multicore systems.

While passing Lua objects between Lua states is not allowed, one can arrange for two Lua states to have FFI pointers to the same object in the C heap, and use this for shared-memory communication.  One can call functions in pthreads or Windows threads to achieve locking.  However, atomic operation support would be nice.

This is thus a feature request for atomic operations in LuaJIT.'s FFI.

**Comment by fsfod** [comment]
You can already use create atomic operations using the intrinsics system I implemented in #116. Check the unit tests for many examples of FFI definitions of atomic ops.

**Comment by MikePall** [comment]
Part of #39.
