### ISSUE TITLE
Document behavior when using the FFI to interact with other `lua_State`s

### ISSUE THREAD

**Issue by drbo** [LuaJIT/LuaJIT#186]
The LuaJIT FFI allows interacting with the Lua/C API of LuaJIT on different `lua_State`s, as follows:

```lua
local ffi = require 'ffi'
local C = ffi.C
ffi.cdef [[
typedef struct lua_State lua_State;
lua_State *luaL_newstate();
int lua_error(lua_State *L);
void lua_pushnumber(lua_State *L, double num);
]]
local state = assert(C.luaL_newstate())
local a, b = pcall(C.lua_pushnumber, state, 100)
print(a, b)
```
So far, so good.  But suppose the next two lines of code are invoked:
```lua
local x, y = pcall(C.lua_error, state)
print(x, type(y), y)
```
This reveals that `y` is a cdata, specifically of type `ctype<struct lua_State*>`.  Note that a Lua error was thrown through the FFI boundery, and caught on a different state than the one that threw it.

Is this well-defined behavior?  Is it portable? What if the call site gets JIT-compiled?

This needs to be documented.

**Comment by daurnimator** [comment]
Isn't this just the standard exception interoperability working? http://luajit.org/extensions.html#exceptions

**Comment by corsix** [comment]
@daurnimator: No; note the following from http://luajit.org/ext_ffi_semantics.html:
> C++ exception interoperability does not extend to C functions called via the FFI, if the call is compiled.

**Comment by daurnimator** [comment]
> if the call is compiled.

Perhaps in this case it wasn't?

**Comment by MikePall** [comment]
From the perspective of the FFI, the C-level API functions used to control another VM state are just that: C functions. Thus the existing FFI documentation applies.
