### ISSUE TITLE
Problems with nested functions

### ISSUE THREAD

**Issue by Sheph** [LuaJIT/LuaJIT#187]
This code:
```lua
function C(func, ...)
    local args = { ... };
    func(unpack(args));
end

local function B(arg1, fn1, fn2, ...)
    C(function(self)
        if fn1 ~= nil then
            fn1(unpack(self.args));
        end
        C(function(self)
            fn2(unpack(self.args));
        end, { args = self.args });
    end, { args = {...} });
end

C(B, 1, nil, function()
    C(B, 1, function()
        print("a");
    end,
    function()
        print("b");
    end);
end);
```
yields:
```
a
b
```
when run with lua 5.1, but with LuaJIT I get:
```
./luajit: attempt to call upvalue 'fn2' (a nil value)
stack traceback:
	./a.lua:12: in function 'func'
	./a.lua:3: in function 'C'
	./a.lua:11: in function 'func'
	./a.lua:3: in function 'C'
	./a.lua:7: in function 'func'
	./a.lua:3: in function 'C'
	./a.lua:17: in main chunk
	[C]: at 0x00404ac0
```
This happens both with stable 2.0.4 and git master. Due to this issue I can't switch to LuaJIT in my game...

**Comment by szakharchenko** [comment]
Indeed. Making C a local function doesn't help either.

**Comment by Sheph** [comment]
szakharchenko, yep, but guess what, if I remove the 'arg1' argument it works fine. Also, it works fine if I replace:
```lua
C(B, 1, nil, function()
```
with
```lua
C(B, 1, function() end, function()
```
IMO there're some problems with vararg/unpack/nested functions in LuaJIT, I would dig through the code myself, but I really don't have time for this :(

**Comment by corsix** [comment]
This has nothing to do with nested functions, and everything to do with tables. In particular, note that:
  * `unpack(t)` is equivalent to `t[1], t[2], ..., t[#t]` ([reference](http://www.lua.org/manual/5.1/manual.html#pdf-unpack)).
  * `#t` is defined to be any integer index `n` such that `t[n]` is not `nil` and `t[n+1]` is `nil` ([reference](http://www.lua.org/manual/5.1/manual.html#2.5.5)).

For tables with multiple possible values for `#t`, different Lua implementations can give different values, which is exactly what you're seeing.

**Comment by Sheph** [comment]
corsix, in my case i have:
arg[1] = nil
arg[2] = fn2
>#t is defined to be any integer index n such that t[n] is not nil and t[n+1] is nil

so t can't be 1, since arg[1] is in fact nill
that means t is 2, since arg[2] is not nill and arg[3] is nill
so there's a problem after all.

P.S: local args = {...}; pass it somewhere; func(unpack(args)) is the very common pattern for passing variable arguments around, it should work

**Comment by szakharchenko** [comment]
Sheph, the pattern is very common but isn't guaranteed to work; that's why table.pack/table.unpack have come in 5.2. Sorry I didn't notice that nil at first. Try rebuilding LuaJIT with 5.2 compat and using table.pack(...) instead of {...}.

**Comment by corsix** [comment]
> corsix, in my case i have:
arg[1] = nil
arg[2] = fn2

Your first invocation of `C` does `local args = {1, nil, function()...end};`. The length of this table can be either 1 or 3, and things go downhill from there.

**Comment by Sheph** [comment]
szakharchenko, corsix, I see now, thanks. This is indeed an "ugly" feature of lua then, also considering that http://www.lua.org/pil/5.1.html states:
>An important use for unpack is in a generic call mechanism. A generic call mechanism allows you to call any function, with any arguments, dynamically.

I've been using 'unpack' like this for as long as I can remember without any issues (since I've been using only one implementation of lua), I guess I'll have to go through all my scripts and replace this in order to make the game work with LuaJIT then...

**Comment by szakharchenko** [comment]
Sheph, it gets weirder. Stock Lua 5.1:

```
> a={1,2,3}
> =#a
3
> a[2]=nil
> =#a
3
> a[4]=nil -- should do totally nothing
> =#a
1
```

To have correct lengths for nil-containing tables, you basically have to store them explicitly, and that's what table.pack does.

**Comment by Sheph** [comment]
szakharchenko, yeah, I know about the # operator behavior, I'm always extra careful with it, but it never occurred to me that {...}/unpack have the same issues... Thanks, I guess the only right way is to use table.pack here as you say...

**Comment by SinisterRectus** [comment]
Adding to this for posterity

```lua
local tests = {
    table.pack(nil, nil, 3),
    {n = 3, nil, nil, 3},
    function(...) return table.pack(...) end,
    {n = 3, [3] = 3},
    function(...) return {n = select('#', ...), ...} end,
    {nil, nil, 3},
    function(...) return {...} end,
}

for i, v in ipairs(tests) do
    if type(v) == 'function' then
        v = v(nil, nil, 3)
    end
    print(i, #v, v.n)
end

--    LuaJIT 2.1:         Lua 5.3:
-- 1: # = 3, n = 3    # = 3, n = 3
-- 2: # = 3, n = 3    # = 3, n = 3
-- 3: # = 3, n = 3    # = 3, n = 3
-- 4: # = 0, n = 3    # = 0, n = 3
-- 5: # = 0, n = 3    # = 3, n = 3
-- 6: # = 3, n = nil  # = 3, n = nil
-- 7: # = 0, n = nil  # = 3, n = nil
```
