### ISSUE TITLE
Parse unicode escapes \uxxxx \Uxxxxxxxx

### ISSUE THREAD

**Issue by MikePall** [LuaJIT/LuaJIT#19]
The escape sequence for a 16 bit or 32 bit code point should be converted to UTF-8 in the lexer. Lowercase \u accepts exactly 4 hex digits (in either case), uppercase \U accepts exactly 8 hex digits.

This should be synced up to a release, since it breaks source code compatibility. It either should make it into the code base for 2.1.0-final or not into 2.1 at all. Remove the label, if this is the case.

**Comment by SoniEx2** [comment]
What about 5.3-compatible `\u{XXX}` where `XXX` is a sequence of 1 or more hexadecimal digits representing the character code point?

**Comment by MikePall** [comment]
Maybe in addition. And, yes, I think this is just another pointless and stupid Lua 5.3 weirdness. Why should one be bothered to enter raw UTF-8 as hex values with \u{abcd}?!? This can already be entered as \xab\xcd -- that proprietary \u{} syntax doesn't help at all.

The point is to be able to enter or cut'n'paste a hex code point literally, not having to convert it to UTF-8 by hand. What an ill-conceived 'feature'.

Following the lead of Python, Java, Javascript etc. and implementing \u and \U just makes so much more sense.

**Comment by fperrad** [comment]
I've already implemented this lexer extension in [TvmJIT](https://github.com/fperrad/tvmjit)

see https://github.com/fperrad/tvmjit/blob/master/src/tj_lex.c#L171

**Comment by SoniEx2** [comment]
> This can already be entered as \xab\xcd -- that proprietary \u{} syntax doesn't help at all.

"\u{ABCD}" == "\xEA\xAF\x8D", NOT "\xAB\xCD".  
Also "\u{0}" == "\0" and "\u{10301}" == "\xF0\x90\x8C\x81". It's variable-length so you don't need to have to handle \u and \U separately, you can just handle both.

> The point is to be able to enter or cut'n'paste a hex code point literally, not having to convert it to UTF-8 by hand.

Exactly. Lua 5.3 also removes the need to add padding :wink:

**Comment by drbo** [comment]
Rust also uses the "\u{ABCD}"-style escapes.  These have the advantages mentioned above.

I am going to try this.

**Comment by MikePall** [comment]
Thanks! Applied to my git master (with modifications).
