### ISSUE TITLE
Intermittent testsuite failures in LJ_GC64 mode on x64 (-joff fixes them)

### ISSUE THREAD

**Issue by DemiMarie** [LuaJIT/LuaJIT#196]
The [LuaJIT test suite][1] has some tests that can be run with a test runner.

When running with the JIT compiler enabled: I have observed intermittent failures in the following tests:

- 402
- 404

I cannot reproduce them with `-joff`.

[1]: /LuaJIT/LuaJIT-test-cleanup

**Comment by MikePall** [comment]
Please use names and not numbers to reference tests. Indicate the LuaJIT version, architecture, OS and toolchain you're testing with, too.

But try again with v2.1 HEAD, since something related might have just been fixed.

**Comment by DemiMarie** [comment]
The specific failure for 402 is:
```
[402/498] trace/phi/ref.lua --- don't eliminate PHI if referenced from another non-redundant PHI
../LuaJIT-test-cleanup/test/trace/phi/ref.lua:130: assertion failed!
stack traceback:
	[C]: in function 'assert'
	../LuaJIT-test-cleanup/test/trace/phi/ref.lua:130: in function <../LuaJIT-test-cleanup/test/trace/phi/ref.lua:117>
	[C]: in function 'xpcall'
	../LuaJIT-test-cleanup/test/test.lua:378: in function 'execute_plan'
	../LuaJIT-test-cleanup/test/test.lua:413: in main chunk
	[C]: at 0x004052d0
```

Now trying to reproduce with v2.1 git HEAD.

**Comment by DemiMarie** [comment]
Either the bug is fixed in HEAD or I can't reproduce it.  Closing.
