### ISSUE TITLE
Performence is slowly when using jit.on()  on android

### ISSUE THREAD

**Issue by TerranTian** [LuaJIT/LuaJIT#197]
http://www.freelists.org/post/luajit/Android-performance-drop-moving-from-LuaJIT201-LuaJIT202,8

Some problem with it mention in this mail , but does not solved the problem with the advise in the mail.

Any help?

**Comment by DemiMarie** [comment]
Did you try the `mmap()` trick?

The best answer is to do this at process startup:

- `mmap()` a huge region of virtual memory with `PROT_NONE`.
- load LuaJIT
- `munmap()` the region
- `mmap()` a smaller region for use by LuaJIT for executable code
- tell LuaJIT to use it

**Comment by MikePall** [comment]
No response after 17 days. Closing as invalid.
