### ISSUE TITLE
Any plans to support Lua 5.3?

### ISSUE THREAD

**Issue by campbx** [LuaJIT/LuaJIT#198]
Trying to familiarize myself with the development plan forward for LuaJIT.  Is there a plan / list of upcoming features?  Thanks!

**Comment by daurnimator** [comment]
Complete 5.3 support is not currently a target (though I wish it was).
However there are some 5.3 features that are scheduled to be added.
(perhaps we should make a github milestone?)

**Comment by DemiMarie** [comment]
Unicode escape support was added (by me, changed username from drbo to DemiMarie)

**Comment by DemiMarie** [comment]
Also, the LuaJIT FFI provides 64-bit integers.

**Comment by campbx** [comment]
@DemiMarie  Aha - my main goal was to find 64-bit integer support, which is the industry standard for all financial coding.  Let me look into FFI - thank you for the lead.

@daurnimator  Milestone would be great.  Gives more faith and peace of mind to new users to Lua like me.

**Comment by campbx** [comment]
@DemiMarie Hey Demi, a follow up thought: it will be really hard for me to get approvals from managers about using integers with FFI dependency because finance industry is totally against using floats.  It makes it much harder to get Lua algorithms approved by management and deployed in production.

Since LuaJIT is becoming much more popular with deep learning and Torch, I can imagine several other specialized fields may also crave for integer support.  Please include it if you can for future versions!

**Comment by DemiMarie** [comment]
@campbx FFI integers are first class objects in LuaJIT, and the FFI is built-in to the LuaJIT VM.  No need for a 3rd party library.

**Comment by alnsn** [comment]
@campbx I'm in finance for 10+ years and I always use doubles. It's much harder to get an approval from manangement to deploy performance critical app in a scripting language compared to using doubles.

**Comment by dobegor** [comment]
@FuriouslyCurious why did you close this issue? I think most LuaJIT users will be happy to see 5.3 support, let this issue be open for a roadmap.

**Comment by spacekookie** [comment]
Yea I hope this doesn't just get swept under the rug. There are a ton of features in lua-5.3 (not so mention libraries that require it). Kinda shitty this was just randomly closed?

**Comment by dobegor** [comment]
@FuriouslyCurious any update on this?

**Comment by FuriouslyCurious** [comment]
Hey everyone, I switched to PyTorch so not using LuaJIT / 5.3 anymore.  Someone needs to take over this issue and move it ahead.  Thanks!

**Comment by XVilka** [comment]
Would be nice to have.

**Comment by timofonic** [comment]
@dobegor @spacekookie @daurnimator @XVilka I agree.

LuaJit is great, but segmentation is killing Lua. There should be new ideas and standardize the language in a dynamic and evolutive way.

@FuriouslyCurious Too sad. I hope someone evolves LuaJit to 5.3+

**Comment by szbnwer** [comment]
hi there :)

@timofonic +1

@FuriouslyCurious you could reopen it (or i dont know enough github if anyone else could do it, probalby @MikePall can)

i can understand that lj is great as it is and can solve anything even now, and there can be more important targets for development currently, just as well as 'wontfix' blocks for whatever reasons... however but following lua would be really great. if not officially, then a fork is always possible.

my best idea is to make some special versioning that includes the related lua and lj version, but ive got no any perfect idea for what form would be the best, maybe like 5.3.0.0.1 as the last number of lua versions are not needed as those are bugfixes and whatever for a different codebase, but those have nothing to do with ecosystem, but lj could get a fresh versioning for a cleaner vision, or can be 5.3.2.1 and 5.3.2.0.4 . this would make some temporary mess as everyone have to follow up such a change, but its good as it wont break the lj community, as it have already some strong forks, even if they are ruining nothing as far as i can see them. this way we could see where such a change leads without the need of leave back the current path for the new one. all it takes are brave people who would make it, and Mike's opinion about such a versioning for the official lj, but even if he disagree then a fork can use this disambiguation, if keeping the name luajit is not a problem for such a fork.

btw an another question: is there any wip improvement that must be ready before this?

finally but not lastly i like so much luajit no matter whats next and very very deeply respect the whole community, you have a huge knowledge and are making a better world! ;)
