### ISSUE TITLE
Binary version of -jdump?

### ISSUE THREAD

**Issue by lukego** [LuaJIT/LuaJIT#199]
I find myself longing for a binary version of `-jdump`. Has anybody ever developed such a thing?

Specifically I would like a mechanism to capture generated code that is efficient enough to enable in production and that produces files that can be post-processed conveniently. I am imagining that a binary format based on LuaJIT's internal data structures would fit the bill. (The problems with `-jdump` are that it is expensive to run the string formatting inside the system being observed and that the output is not especially convenient for tools to parse.)

The use cases is offline performance analysis of running production systems. For example I should be able to produce reports like `-jdump` and cross-reference them with profiler information and source code even for processes that already started and/or terminated before I decided that I was interested in analyzing them.

I also want to be able to do things like highlight the relationships between bytecode, IR, and machine code to understand e.g. which part of the program a given machine instruction belongs to. This would require access to other information that may be present inside the LuaJIT heap but is absent from the `-jdump` output.

(The main alternative I see would be to create a coredump of the running process and inspect that in the spirit of gdb. Would that actually be a better idea?)

**Comment by fsfod** [comment]
I have IR annotation of assembly extension to jdump/modified jit emit loop in a custom branch here https://github.com/fsfod/LuaJIT/tree/iroffsets that might be some use

**Comment by lukego** [comment]
@fsfod Super cool! I like these interleaved IR/mcode traces. Snippet from running your branch:
```
---- TRACE 1 mcode 40
0000 rdx      p32 BASE   #0    #0  
0bcbffd5  mov dword [0x4044f410], 0x1
0001 rbp      int SLOAD  #1    CI
0bcbffe0  cvttsd2si ebp, [rdx]
0002 rbp    + int ADD    0001  +1  
0bcbffe4  add ebp, +0x01
0003       >  int LE     0002  +100
0bcbffe7  cmp ebp, +0x64
0bcbffea  jg 0x0bcb0014 ->1
```

I am really keen to have functionality like this. I think it would be useful to include the bytecode too, right? I have recently been wondering whether a pretty-printer for recorded bytecodes could also produce output readable enough to serve as a proxy for source code, e.g. `0005 for x = i, j do`.

Do you have any thoughts on how practical it would be to capture the dumps very efficiently in the running LuaJIT and then analyze/format them separately with another process? (So that tracing could always be enabled and available for post-mortem analysis of production processes.) I almost wonder if the JIT could even allocate its internal data structures in file-backed shared memory? But I don't have a clear enough mental model of the data structures and how easy/hard they are to inspect from the outside.

**Comment by fsfod** [comment]
Its not as simple to map IR back to bytecode because IR is directly fed into the FOLD engine as its emitted for each bytecode so what you record(current IR inst top) is lossy based on if things like field access get de-duplicated and some stuff like the loop body are emitted twice but with CSE for loop invariant values for the second time.

You need to capture things like protos, functions and strings as well as the traces themselves for a dump. Which you could do with my [GC heap dumper ](https://github.com/fsfod/LuaJIT/blob/gcstats/src/lj_gcutil.c#L287). I think I showed you it before its completely standalone with no changes to LuaJIT. It will still take about the same time to dump as both the GC sweep phases roughly because it just walks all the GC object linked lists. 

> I almost wonder if the JIT could even allocate its internal data structures in file-backed shared memory?

Maybe [one day](https://github.com/fsfod/LuaJIT/blob/4d3646f78f53ff644ad3a4cbf5f9769165824bd0/src/lj_gcarena.c#L145) :wink:

**Comment by lukego** [comment]
GC heap dumper is news to me. Could be exactly what I am looking for. Is there a demo?

**Comment by lukego** [comment]
(Oh I see that this is dumping the whole heap. I am only interested in the code e.g. bytecode, traces, mcode, and objects that they reference e.g. constants or information about identify of FFI types and calls.)

Relatedly I see that `perf` has grown new JIT support recently. Have not looked into it yet. https://lwn.net/Articles/633846/

**Comment by corsix** [comment]
> The main alternative I see would be to create a coredump of the running process and inspect that in the spirit of gdb. Would that actually be a better idea?

I expect you could get quite far by `fork()`ing the process, and then performing your inspections/dumping in one of the prongs.

**Comment by lukego** [comment]
@corsix Could be that the `fork()` route is a good one. I have been considering that in https://github.com/snabbco/snabb/pull/754. However at the moment it does feel a little more invasive than a cheap incremental dump driven by `jit.attach()` i.e. same mechanism as `-jdump` except quickly writing binary data for offline analysis.

Could perhaps have a compromise e.g. a fork()-based dumper that is triggered by JIT events so that it is not running all the time. Then the dumping could conceivably even be done with Lua code.

**Comment by lukego** [comment]
@fsfod How are you using these heap dumps? Do you have any example tools/screenshots? Is there enough information to reproduce `-jdump` output or does that depend on information not dumped e.g. ephemera during tracing?

Could potentially be reasonable to perform full heap dumps on production systems if done in a fork(). Then the heap dumps from @fsfod's branch could make a convenient defacto standard format for analysis tools.

**Comment by fsfod** [comment]
I didn't really use heap dumps I had something more complex with my trace analyser that would build a proto/function pointer to Id Lua hash table incrementally as code is traced and when a dump was requested or traces flushed I saved everything from the table and all live traces into a stable binary format. For strings I just saved them all along with there address. I also packed all the vmdef.lua data like IR and fast func names into the dump

**Comment by lukego** [comment]
(Thanks for the discussion. Closing to avoid clutter.)
