### ISSUE TITLE
binary code compilation is broken

### ISSUE THREAD

**Issue by milani** [LuaJIT/LuaJIT#201]
I could successfully compile https://github.com/luvit/luvi/blob/master/src/lua/luvibundle.lua using `luajit -b -a mipsel` command using commit 287a5347cfe452d44748327fb7c27f6ce57f5dc2. But I can't build it any more using latest version (22e8e0796940e0583c59642dad069873c1077f75). It crashes without any error. Probably something is broken.

**Comment by MikePall** [comment]
Fixed.
