### ISSUE TITLE
Performance problem in the table allocation

### ISSUE THREAD

**Issue by mah0x211** [LuaJIT/LuaJIT#202]
Latest LuaJIT version has a performance problem when allocated the table with the returned value of the string.byte() function.

``` lua
-- display time
function time(title, block)
  local st = os.clock()
  block()
  local ed = os.clock()

  print(title .. ": " .. ed-st.. " sec")
end

-- this is fast
local function _string2bytearray_fast(data)
  local i = 1
  local t = {}
  for i=1, string.len(data) do
     t[i] = data:byte(i)
  end
  return t
end

-- this is slow
local function _string2bytearray_slow(data)
  return { data:byte(1, -1) }
end

-- target string
msg = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'

-- check the logic
assert(_string2bytearray_fast(msg) ~= _string2bytearray_slow(msg), "_string2bytearray_fast != _string2bytearray_slow")



----------------------------------------------------------------------
-- bench 1
time("_string2bytearray_fast", function()
  for i=0, 1000000 do
     local tmp = _string2bytearray_fast(msg)
  end
end)

-- bench 2
time("_string2bytearray_slow", function()
  for i=0, 1000000 do
     local tmp = _string2bytearray_slow(msg)
  end
end)
```

on LuaJIT v2.1x;

```
$ src/luajit bench.lua
_string2bytearray_fast: 2.357741 sec
_string2bytearray_slow: 55.882848 sec
```

on LuaJIT v2.0.4;

```
$ luajit bench.lua
_string2bytearray_fast: 2.362028 sec
_string2bytearray_slow: 0.855845 sec
```

I found this problem at the following Japanese web community; 
http://qiita.com/toritori0318/items/dd0990c5521998155a00

**Comment by katlogic** [comment]
Corner case, not sure if really a bug. Seen this in other places with large multret.

Add:
``
jit.off(_string2bytearray_slow)
``
Before calling it, and you'll get:

```
_string2bytearray_fast: 1.18 sec
_string2bytearray_slow: 0.48 sec
```

Why this happens.
The "slow" variant unrolls the loop (via recff_string_range which directly emits the IR stores for each return value), and I-cache gets spammed to hell. Each value gets its unique store + lj_tab_newkey call. The "fast" variant does basically the same, but does not spam icache - it will loop in machine code.

Why interpreter is faster in both cases compared to jit? The produced JIT code does not look very good - spread over 7 traces, and there's so many guards interpreter can do a better job of it.
