### ISSUE TITLE
Compiling @ macOS doesn't work with latest NDK

### ISSUE THREAD

**Issue by astennu** [LuaJIT/LuaJIT#204]
# Android/ARM, armeabi-v7a (ARMv7 VFP), Android 4.0+ (ICS)
HOST_OS=`uname -s | tr "[:upper:]" "[:lower:]"`
NDK=/Users/foobar/android-sdk-macosx/ndk-bundle
NDKABI=19
NDKVER=$NDK/toolchains/arm-linux-androideabi-4.9
NDKP=$NDKVER/prebuilt/${HOST_OS}-x86_64/bin/arm-linux-androideabi-
NDKF="--sysroot $NDK/platforms/android-$NDKABI/arch-arm"
NDKARCH="-march=armv7-a -mfloat-abi=softfp -Wl,--fix-cortex-a8"
make HOST_CC="gcc -m32" CROSS=$NDKP TARGET_FLAGS="$NDKF $NDKARCH" TARGET_SYS=Linux clean default

This gives me following errors:
make[1]: /Users/foobar/android-sdk-macosx/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-clang: Command not found
make[1]: /Users/foobar/android-sdk-macosx/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-clang: Command not found
make[1]: /Users/foobar/android-sdk-macosx/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-clang: Command not found
make[1]: /Users/foobar/android-sdk-macosx/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-clang: Command not found
make[1]: /Users/foobar/android-sdk-macosx/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-clang: Command not found
make[1]: /Users/foobar/android-sdk-macosx/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-clang: Command not found
Makefile:262: *** Unsupported target architecture.  Stop.

I did quick check for Makefile and found most likely the cause for this error:
ifeq (Windows,$(findstring Windows,$(OS))$(MSYSTEM)$(TERM))
  HOST_SYS= Windows
  HOST_RM= del
else
  HOST_SYS:= $(shell uname -s)
  ifneq (,$(findstring MINGW,$(HOST_SYS)))
    HOST_SYS= Windows
    HOST_MSYS= mingw
  endif
  ifneq (,$(findstring CYGWIN,$(HOST_SYS)))
    HOST_SYS= Windows
    HOST_MSYS= cygwin
  endif
  # Use Clang for OSX host.
  ifeq (Darwin,$(HOST_SYS))
    DEFAULT_CC= clang <-- This is causing issues, we are compiling NDK build with macOS host. Should we use gcc instead?
  endif
endif

**Comment by MikePall** [comment]
Fixed. Partially reverting #102 and #4. Amending #1.
