### ISSUE TITLE
Segmentation fault when using FFI

### ISSUE THREAD

**Issue by cyberz-eu** [LuaJIT/LuaJIT#206]
I have started using LuaJIT's FFI for binding with openssl for encryption but encountered **Segmentation fault** after 100 consecutive iterations in this simple example:
```
function aes (str, _key, _iv)
	local out = {}
	local outlen = ffi.new("int[1]", 0)
	local outbuf = ffi.new("unsigned char[?]", str:len() + 32)
	
	-- full or empty 'outbuf' does not change anything
	ffi.copy(outbuf, str)
	outlen[0] = str:len()
	
	local inbuf = ffi.new("unsigned char[?]", str:len())
	ffi.copy(inbuf, str)
	
	local key = ffi.new("unsigned char[?]", 16)
	ffi.copy(key, _key)
	
	local iv = ffi.new("unsigned char[?]", 16)
	ffi.copy(iv, _iv)
	
	table.insert(out, ffi.string(outbuf, outlen[0]))
	
	table.insert(out, ffi.string(outbuf, outlen[0]))

	return table.concat(out), ffi.string(key, 16), ffi.string(iv, 16)
end

ffi = require "ffi"
ffi.cdef [[
	void *malloc( size_t numbytes );
	int free( void *region );
]]
for i=1,500 do
	print(i .. " ==> " .. string.format('%.2f', collectgarbage("count")) .. "KB")
	print(aes("12345678901234567890", "1234567890qazwsx", "1234567890qazwsx"))
end
```

I tried adding finalizer like this 
```
local key = ffi.gc(ffi.new("unsigned char[?]", 16), ffi.C.free)
ffi.copy(key, _key)
	
local iv = ffi.gc(ffi.new("unsigned char[?]", 16), ffi.C.free)
ffi.copy(iv, _iv)
```
 but then luajit started failing with
*** Error in `./luajit': free(): invalid size: 0x00000000410510d0 ***

I know that luajit has enough memory because usage is around 60KB-70KB and memory is regularly freed but may be I do something wrong. Any idea?

**Comment by corsix** [comment]
Your `ffi.copy` calls are might suspicious, and are probably corrupting memory. In particular, note that `ffi.copy(dst, src)` copies `#src+1` bytes (your buffers seem to have `#src` bytes, so try passing `#src` as a third argument to `ffi.copy`).

**Comment by cyberz-eu** [comment]
You are absolutely right! I have forgotten about the C's zero-terminated strings. 

I had to either specify manually the number of bytes to copy:
```
local key = ffi.new("unsigned char[?]", 16)
ffi.copy(key, _key, #_key)
```
 OR create 1 byte bigger buffers to hold the zero-terminator:
```
local key = ffi.new("unsigned char[?]", 16 + 1)
ffi.copy(key, _key)
```
Thanks very much!
