### ISSUE TITLE
How to control the scope of traces?

### ISSUE THREAD

**Issue by lukego** [LuaJIT/LuaJIT#208]
Greetings wonderful LuaJIT hackers!

I have a juicy question for you all :-).

I am interested in influencing the way LuaJIT chooses to structure the traces for my code. Sometimes I have intuitions for when side-traces or root-traces are more appropriate for a given code path. Question is: How should I convey this information to the JIT?

Let me present a toy example.

### Toy example

This example is made up of three modules: `util` that defines a looping utility function and then `a` and `b` that both call this function with different parameters.

```lua
-- file: util.lua
return function (mode, n)
   local acc = 0
   for i = 1, n do
      acc = acc + (mode == 'add' and 1 or -1) -- Guard on 'mode'
   end
   return acc
end

-- file: a.lua
require("util")('add', 1e9)

-- file: b.lua
require("util")('sub', 1e9)
```

This code behaves consistently if I run either of `a` or `b`:

```
$ $(which time) -f "time: %es" luajit -jv -l a - < /dev/null
[TRACE   1 util.lua:4 loop]
time: 0.85s

$ $(which time) -f "time: %es" luajit -jv -l b - < /dev/null
[TRACE   1 util.lua:4 loop]
time: 0.85s
```

but if I run both in sequence then the second one will create a side-trace and perform much worse:

```
$ $(which time) -f "time: %es" luajit -jv -l a -l b - < /dev/null
[TRACE   1 util.lua:4 loop]
[TRACE   2 (1/1) util.lua:5 -> 1]
time: 5.37s
```

The problem I want to solve is: How should I tell LuaJIT to create a separate root trace for each call so that each loop behaves the same way?

### More bytecodes

One solution that I concocted is to load the `util` module separately each time. This presumably means that each copy has separate bytecodes and LuaJIT will not understand that the traces could be combined.

```lua
-- file: util.lua
return function (mode, n)
   local acc = 0
   for i = 1, n do
      acc = acc + (mode == 'add' and 1 or -1) -- Guard on 'mode'
   end
   return acc
end

-- file: aa.lua
dofile("util.lua")('add', 1e9)

-- file: bb.lua
dofile("util.lua")('sub', 1e9)
```

This works:

```
$ $(which time) -f "time: %es" luajit -jv -l aa -l bb - < /dev/null
[TRACE   1 util.lua:4 loop]
[TRACE   2 util.lua:4 loop]
time: 1.71s
```
### More closures

One alternative solution would be to reuse the code but create separate closures for each call. This occured when seeing the keyword *prototype* in the LuaJIT sources. Seems like each closure will have a separate root trace?

```lua
-- file: util2.lua
return function (mode, n)
   return function ()
      local acc = 0
      for i = 1, n do
         acc = acc + (mode == 'add' and 1 or -1)
      end
      return acc
   end
end

-- file: a2.lua
require("util2")('add', 1e9)()

-- file: b2.lua
require("util2")('sub', 1e9)()
```

This works too:

```
$ $(which time) -f "time: %es" luajit -jv -l a2 -l b2 - < /dev/null
[TRACE   1 util2.lua:5 loop]
[TRACE   2 (1/0) util2.lua:6 loop]
time: 1.71s
```

### So...

Question now is, what is the appropriate solution? How do other people deal with this?

This is important to me because in Snabb we have cases where the application's workload changes over time and performance drops because slower traces are executing. Users have been resorting to detecting low performance and calling `jit.flush()` to put it back on track. I see this as a kludge and would prefer to prevent the problem from occuring rather than diagnosing and curing it with drastic measures.

Tips welcome!

**Comment by corsix** [comment]
> One alternative solution would be to reuse the code but create separate closures for each call. This occured when seeing the keyword *prototype* in the LuaJIT sources.

A prototype counts how many times a closure has been created from it. If this counter is 1 or 2, then calls to the any its closures specialise to the closure (and thus specialise to values of immutable upvalues). If this counter is 3 or more, calls to its closures instead specialise to the prototype (and thus cannot specialise to values of upvalues). The frame in which tracing begins is similarly specialised to either the prototype or the closure according to the same rules (in this case, specialisation to the prototype is implicit, and specialisation to the closure is done lazily on first upvalue access if the counter is less than 3). Note that this counter is a lifetime counter - it never decrements, and in particular can be larger than the number of closures currently in existence for the prototype.

> Seems like each closure will have a separate root trace?

Your example already shows this not to be true:

> ```
[TRACE   1 util2.lua:5 loop]
[TRACE   2 (1/0) util2.lua:6 loop]
```

Trace 2 is a side trace of trace 1, rather than a root trace. However, as it takes exit 0, trace 2 forms its own loop rather than rejoining trace 1 at the end of each iteration (*), which is why you still see good performance.

If your example is extended with two more files, then things play out rather differently:

```lua
-- file: c2.lua
require("util2")('mul', 1e9)()

-- file: d2.lua
require("util2")('add', 1e9)()
```

```
$ time ./luajit -jv -l a2 -l b2 -l c2 -l d2 - < /dev/null
[TRACE   1 util2.lua:4 loop]
[TRACE   2 (1/0) util2.lua:5 loop]
[TRACE   3 (2/0) util2.lua:5 loop]
[TRACE   4 (3/1) util2.lua:5 -> 1]

real	0m10.041s
```

Trace 1 specialised to the closure. This specialisation wasn't valid for `b2`, so trace 2 was formed at trace 1 exit 0. Trace 2 again specialised to a closure. When `c2` came along, neither specialisation was valid, i.e. trace 1 exit 0 was taken, and then trace 2 exit 0 was taken, and trace 3 was formed at trace 2 exit 0. Trace 3 specialised to the prototype rather than the closure. So far, everything is performant, but things get bad when `d2` comes along. Again, trace 1 exit 0 and trace 2 exit 0 are taken on account of the closure specialisation being invalid, and execution starts along trace 3. Within trace 3, exit 1 is taken, forming trace 4. As trace 4 wasn't formed at exit 0 of its parent, its tail rejoins its parent rather than forming its own loop (**), and performance tanks.

In other words, your closure-based example only gives good performance because the number of closures is small and because the specialisation to the closure occurs before snapshot 1 (which needn't be the case, because as mentioned, specialisation for the initial frame is done lazily on first upvalue access - change the loop body to `acc = acc + (acc == 0 and 0 or 0); acc = acc + (mode == 'add' and 1 or -1)` to see the specialisation done at/after snapshot 1).

(*) Exit 0 is a good proxy, but not quite the full story. The actually important factor is that trace 2 starts at the start of the loop, and thus ends where it starts, and so can be made into a loop.

(**) Again, exit 0 is merely a good proxy for the full story. The important point is that trace 4 starts in the middle of the loop and ends at the end of the loop. As such, it cannot be looped round to itself (because it starts and ends at different points) and so has to rejoin its parent.

**Comment by lukego** [comment]
@corsix Thanks for the info! I see that there is a lot going on behind the scenes. I suppose that I need to understand this in more detail before I will be able to effectively "hint" the JIT.

I have poked around with this example a little bit. First I tried forcing the trace to always specialize on the closure.

```diff
diff --git a/src/lj_record.c b/src/lj_record.c
index 480c80c..ba54fff 100644
--- a/src/lj_record.c
+++ b/src/lj_record.c
@@ -1531,8 +1531,10 @@ static TRef rec_upvalue(jit_State *J, uint32_t uv, TRef val)
     TRef tr, kfunc;
     lua_assert(val == 0);
     if (!tref_isk(fn)) {  /* Late specialization of current function. */
+#if 0
       if (J->pt->flags >= PROTO_CLC_POLY)
        goto noconstify;
+#endif
       kfunc = lj_ir_kfunc(J, J->fn);
       emitir(IRTG(IR_EQ, IRT_FUNC), fn, kfunc);
       J->base[-1] = TREF_FRAME | kfunc;
```

This makes your example run fast:

```
$(which time) -f "time: %es" luajit -jv -l a2 -l b2 -l c2 -l d2 - < /dev/null
[TRACE   1 util2.lua:5 loop]
[TRACE   2 (1/0) util2.lua:6 loop]
[TRACE   3 (2/0) util2.lua:6 loop]
[TRACE   4 (3/0) util2.lua:6 loop]
time: 3.43s
```

Then I tried the opposite: never specializing on the closure.

```diff
diff --git a/src/lj_record.c b/src/lj_record.c
index 480c80c..3b2dc4e 100644
--- a/src/lj_record.c
+++ b/src/lj_record.c
@@ -1527,6 +1527,7 @@ static TRef rec_upvalue(jit_State *J, uint32_t uv, TRef val)
   TRef fn = getcurrf(J);
   IRRef uref;
   int needbarrier = 0;
+  goto noconstify;
   if (rec_upvalue_constify(J, uvp)) {  /* Try to constify immutable upvalue. */
     TRef tr, kfunc;
     lua_assert(val == 0);
```

The immediate effect of this change is that it runs slowly:

```
$ $(which time) -f "time: %es" luajit -jv -l a2 -l b2 -l c2 -l d2 - < /dev/null
[TRACE   1 util2.lua:5 loop]
[TRACE   2 (1/1) util2.lua:6 -> 1]
time: 10.86s
```

And this seems to be because the first trace has a guard on `add` but (crucially?) this comes immediately after the first snapshot:

```
[luke@lugano-1:~/luatest]$ $(which time) -f "time: %es" luajit -jdump=is -l a2 -l b2 -l c2 - < /dev/null
---- TRACE 1 start util2.lua:5
---- TRACE 1 IR
....        SNAP   #0   [ ---- ]
0001 >  int SLOAD  #3    CRI
0002 >  int LE     0001  +2147483646
0003    int SLOAD  #2    CI
0004    fun SLOAD  #0    R
0005 >  p32 UREFC  0004  #1  
0006 >  str ULOAD  0005
....        SNAP   #1   [ ---- ---- 0003 0001 ---- ---- ]
0007 >  str EQ     0006  "add"
....        SNAP   #2   [ ---- ---- 0003 0001 ---- 0003 ]
0008 >  num SLOAD  #1    T
0009  + num ADD    0008  +1  
0010  + int ADD    0003  +1  
....        SNAP   #3   [ ---- 0009 ]
0011 >  int LE     0010  0001
....        SNAP   #4   [ ---- 0009 0010 0001 ---- 0010 ]
0012 ------ LOOP ------------
0013  + num ADD    0009  +1  
0014  + int ADD    0010  +1  
....        SNAP   #5   [ ---- 0013 ]
0015 >  int LE     0014  0001
0016    int PHI    0010  0014
0017    num PHI    0009  0013
---- TRACE 1 stop -> loop

---- TRACE 2 start 1/1 util2.lua:6
---- TRACE 2 IR
0001    int SLOAD  #2    PI
0002    int SLOAD  #3    PRI
....        SNAP   #0   [ ---- ---- 0001 0002 ---- ---- ]
0003 >  num SLOAD  #1    T
0004    num ADD    0003  -1  
0005    int ADD    0001  +1  
....        SNAP   #1   [ ---- 0004 ]
0006 >  int LE     0005  0002
0007    num CONV   0005  num.int
....        SNAP   #2   [ ---- 0004 0007 0002 ---- 0007 ]
---- TRACE 2 stop -> 1

time: 10.01s
```

### Recap

This is very interesting.

On the one hand LuaJIT can have multiple traces for the same piece of code that all have their own specialized (fast) loops. The traces will be executed in series: each one tests whether it is the right one and otherwise branches to the next one. The machine code for the check-and-maybe-branch looks something like this:

```
---- TRACE 1 mcode 130
0bcaff7e  mov dword [0x403fe410], 0x1
0bcaff89  movsd xmm0, [0x4040dae0]
0bcaff92  movsd xmm7, [rdx+0x10]
0bcaff97  cvttsd2si eax, xmm7
0bcaff9b  xorps xmm6, xmm6
0bcaff9e  cvtsi2sd xmm6, eax
0bcaffa2  ucomisd xmm7, xmm6
0bcaffa6  jnz 0x0bca0010        ->0
0bcaffac  jpe 0x0bca0010        ->0
```

On the other hand this chaining only happens if the trace can detect *very* early whether it is the right one or not. Is there a way to understand how to ensure this as an application developer? I feel like I could reasonable arrange for the first loop iteration to test all the relevant guards, but I don't know how to make that happen before the first snapshot. I don't have a feeling for where the snapshots are when I am looking at the application sources.

### Crazy idea

Just as a working idea...

Suppose there were a `specialize` language construct to explicitly say how you want a trace to be specialized. You would write:

```
specialize foo
   ...
end
```

and then any trace creates in `...` would immediately (exit 0) guard on the identity of `foo` (an expression that resolves to any object). This way I could write for example:

```
specialize mode
   ...
end
```

and then I am sure that each mode will have a separate loop for its trace. I am also in control of whether the number of traces explodes by how many values I supply for `mode` in practice. (Could be that there are four different cases that I want to specialize, for example, corresponding to different application configurations that influence the biases of branches in the source code.)

Fun to ponder! (Yes, I realize that 99% of the time new language constructs are bad ideas, just suggesting as a vehicle for discussion.)

**Comment by lukego** [comment]
### specialize.lua

So here is a less wild idea :-)

Suppose that instead of `require(modulename)` I would call `specialize(modulename, argument)` which loads a separate copy of the module for each distinct argument value. The argument value is also passed to the module at load-time so that it can be included in a closure. This way each distinct argument value should have its own root trace (separate prototypes) and should also be aggressively specialized on argument value (singleton closure).

```lua
-- file: specialize.lua
local cache = {}  -- module-name -> specialization-arg -> code
return function (mod, arg)
   cache[mod] = cache[mod] or {}
   local code = cache[mod][arg]
   if code == nil then
      code = package.loaders[2](mod)(arg)
      cache[mod][arg] = code
   end
   return code
end

-- file: util.lua
-- "mode" is supplied as a module argument and saved in a closure
local mode = ...
return function (n)
   local acc = 0
   for i = 1, n do
      acc = acc + (mode == 'add' and 1 or -1) -- Guard on 'mode'
   end
   return acc
end

-- file: abcd.lua
local specialize = require("specialize")
specialize('util','add')(1e9) -- a
specialize('util','sub')(1e9) -- b
specialize('util','mul')(1e9) -- c
specialize('util','add')(1e9) -- d
```

Sane? Crazy? Seems to work, anyway:

```
$ time luajit abcd.lua
real    0m3.433s
```

This time each specialization (`add`, `sub`, `mul`) does have a dedicated root trace:

```
$ luajit -jv abcd.lua                                                                                                                                               
[TRACE   1 util.lua:6 loop]
[TRACE   2 util.lua:6 loop]
[TRACE   3 util.lua:6 loop]
```

And the generated code is satisfyingly specialized. In fact there is no test for `mode` at all because the JIT is smart enough to see that its value is constant for a given trace and does not need to be tested at all:

```
$ time luajit -jdump=i abcd.lua 
---- TRACE 1 start util.lua:6
---- TRACE 1 IR
0001 >  int SLOAD  #4    CRI
0002 >  int LE     0001  +2147483646
0003    int SLOAD  #3    CI
0004    fun SLOAD  #0    R
0005 >  fun EQ     0004  util.lua:4
0006 >  num SLOAD  #2    T
0007  + num ADD    0006  +1  
0008  + int ADD    0003  +1  
0009 >  int LE     0008  0001
0010 ------ LOOP ------------
0011  + num ADD    0007  +1  
0012  + int ADD    0008  +1  
0013 >  int LE     0012  0001
0014    int PHI    0008  0012
0015    num PHI    0007  0011
---- TRACE 1 stop -> loop

... other traces are identical except for +1 vs -1 based on mode ...
```

This has the look of something that I could put into practical use.

### Taking a step back

These tricks are fun but I reflect that I am still basically working around the root problem which is the performance cost of side-traces that loop back to their parents (#114). I still wonder whether we have a [worse is better](https://www.jwz.org/doc/worse-is-better.html) situation here. The Right Thing is Hyperblock scheduling (#37) but we don't have that because it is prohibitively difficult to implement. If there would be a solution that is less optimal but feasible to implement, as @mraleph has mused as a possibility, then doing that could make more sense than punting the problem up to application developers with mechanisms like `specialize()`.

I dunno about other people but for me the one big challenge as a LuaJIT user is worrying about the JIT heuristics giving me the wrong traces e.g. when the biases of my branches change over time.

(I suppose that a more dynamic mechanism here would be a possibility too like a CPU branch predictor that is sensitive to context and learns from mistakes.)

**Comment by lukego** [comment]
Closing to avoid clutter. Thanks again @corsix for the feedback. I will post any relevant experiences that I have later.

**Comment by lukego** [comment]
I have had some excellent results with this approach now over on snabbco/snabb#1001. Thanks again @corsix for the tips!

**Comment by lukego** [comment]
@corsix Just a follow-on idea to make specializing JIT traces easier to work with...

How about if we had a primitive `jit.cloneprototype(func)` that takes a closure for input and returns a new closure with the same environment but a new prototype that is an identical clone? So then I could write something like:

```lua
function new (x)
   return jit.cloneprototype(
      function () 
	 for i = 1,n do f(x) end
      end)
end
```

and then I would know that (a) traces starting on the `for` loop here would be compiled separately for each closure (since traces are not shared between prototypes) and (b) each trace would be specialized on the _value_ of the variable `x` (since there is only one closure for each of these prototypes).

This would be basically a neater mechanism for what I am doing now i.e. reloading the bytecodes for a module in order to clone one or more prototypes.

what do you think?

**Comment by corsix** [comment]
Could you implement `cloneprototype` as `string.dump` followed by `load` followed by `getfenv`/`setfenv` and some `debug.upvaluejoin` calls?

**Comment by lukego** [comment]
@corsix Cool idea. Google turns up a blog on exactly this technique: [Cloning a Function in Lua](http://leafo.net/guides/function-cloning-in-lua.html). I'll give it a try.

**Comment by lukego** [comment]
@corsix Groovy. This works and seems like a step forward. I have to think about how to explain how to use this "design pattern" but that is the next problem. I may also need to handle fenv somewhere?

Here is my current example program that is admittedly fairly contrived.

```lua
ffi = require("ffi")

-- Clone a function with a new prototype (taken from blog)
local function clone_function(fn)
  local dumped = string.dump(fn)
  local cloned = loadstring(dumped)
  local i = 1
  while true do
    local name = debug.getupvalue(fn, i)
    if not name then
      break
    end
    debug.upvaluejoin(cloned, i, fn, i)
    i = i + 1
  end
  return cloned
end

-- Return a function for zeroing elements of <size>-entry ring buffers.
function zeroer (size)
   return function (ring, start, n)
      for i = start, start+n do
         ring[i % size] = 0
      end
   end
end

-- Create some zeroing functions. This will bump the instance count on
-- the prototype so that LuaJIT will not aggressively specialize the
-- traces.
zeroer(1024) zeroer(2048) zeroer(4096)

local s = 4096                     -- pick a ring size for testing
local r = ffi.new('int32_t[?]', s) -- allocate a ring
local z = zeroer(s)                -- make a size-specific zeroer

z(r, 0, 1e6)                       -- zero with generic trace
z = clone_function(z)              -- create specializable clone
z(r, 0, 1e6)                       -- zero with specialized trace
```

This does create the expected traces i.e. first a generic one that uses a division instruction for the `%` and then a specialized one that uses `band` with a fixed mask.

Generic trace inner loop:

```
->LOOP:
0bcbffc0  xorps xmm7, xmm7
0bcbffc3  cvtsi2sd xmm7, ebp
0bcbffc7  divsd xmm7, xmm0
0bcbffcb  roundsd xmm7, xmm7, 0x09
0bcbffd1  mulsd xmm7, xmm0
0bcbffd5  movsxd rbx, ebp
0bcbffd8  cvttsd2si r15, xmm7
0bcbffdd  sub rbx, r15
0bcbffe0  mov dword [rcx+rbx*4+0x8], 0x0
0bcbffe8  add ebp, +0x01
0bcbffeb  cmp ebp, eax
0bcbffed  jle 0x0bcbffc0	->LOOP
```

Specialized trace inner loop:

```
->LOOP:
0bcbfed0  mov ebx, ebp
0bcbfed2  and ebx, 0xfff
0bcbfed8  movsxd rbx, ebx
0bcbfedb  mov dword [rcx+rbx*4+0x8], 0x0
0bcbfee3  add ebp, +0x01
0bcbfee6  cmp ebp, eax
0bcbfee8  jle 0x0bcbfed0	->LOOP
```

So this at least looks like a way that I can comfortably use `%` for manipulating ring buffers instead of manually calculating masks and applying them with bitops.

**Comment by corsix** [comment]
> I may also need to handle fenv somewhere?

Yes, I'd throw `setfenv(cloned, getfenv(fn))` in there somewhere.

**Comment by lukego** [comment]
@corsix I am keen to better understand exactly when a side-trace can form a loop and when it cannot. Just now I am seeing unfortunately non-looping side traces over at rtsisyk/luafun#32 but in this more minimal example I do see separate loops:

```lua
-- Create an array to iterate over
local a = {}
for i = 1, 100 do a[i] = i end

-- Define a 'foreach' higher-order function
function foreach (f, l)
  for i = 1, #l do f(l[i]) end
end

local acc = 0
-- Call with two different prototypes for the function argument.
foreach(function (x) acc = acc+x end, a)
foreach(function (x) acc = acc+x end, a)
print(acc)
```

Printing:

```
[TRACE   1 test.lua:3 loop]
[TRACE   2 test.lua:6 loop]
[TRACE   3 (2/0) test.lua:6 loop]
10100
```

where we see that the side-trace (3) took exit 0 from the parent and formed a loop.

Questions on my mind are: How does the JIT decide whether the side-trace can have its own loop? Can this be phrased in practical terms for application developers wanting to write fast code? Could we broaden the applicability of loops in side traces e.g. with a new optimization that attempts to "hoist" pure guards (e.g. check prototype of a function argument) to run early enough to permit clean exits from the root trace?

Just browsing the code the most likely line I have found is https://github.com/LuaJIT/LuaJIT/blob/v2.1/src/lj_record.c#L267 which looks like a very simple requirement that the function call stack be at the same position. Is that the whole story? (Or am I barking up the wrong tree completely?)
