### ISSUE TITLE
Will LUAI_MAXSHORTLEN in Lua-5.3 be supported in LuaJIT?

### ISSUE THREAD

**Issue by strrchr** [LuaJIT/LuaJIT#210]
#define LUAI_MAXSHORTLEN	40
In Lua-5.3, long strings are not interned.
It seems that it solves many performance issues related to string interning.
In practice, long strings are read, processed, written, and never be keys in table.
I think the modification is related to string creation, comparison operators, table key hashing.

**Comment by MikePall** [comment]
Duplicate of #168
