### ISSUE TITLE
Consider support keyboard shortcuts for LuaJIT under shell

### ISSUE THREAD

**Issue by halfcrazy** [LuaJIT/LuaJIT#213]
I found that Lua has supported shortcuts like CTRL-A CTRL-E CTRL-P CTRL-n which luajit current not support. 
![haha2](https://cloud.githubusercontent.com/assets/4113173/18238351/a4318b3e-736e-11e6-8a3e-1d9a445db451.gif)
After take a look at lua's code, i found it use an extra library readline to do this. So i port this feature to luajit via readline too.

Because it use readline as an extra library, it will make this project not so purify, and in most case people dont need this feature. 

**So i don't know whether so send this [PR](https://github.com/halfcrazy/LuaJIT/tree/readline_support) or not.**

**Comment by daurnimator** [comment]
Usually you just run luajit via [rlwrap](http://utopia.knoware.nl/~hlub/rlwrap/#rlwrap)
You may want to add this to your .bashrc or such:
```
alias luajit='rlwrap luajit'
```

**Comment by MikePall** [comment]
Linking to readline is a potential licensing hazard (*). Also, it slows down startup, even if you don't use it. And it messes with the locale settings.

Use a wrapper as suggested. Or, what I do most of the time: use `luajit -e '...'` and the history functions of your shell for short explorations. Two advantages: 1) locals still work and 2) it can be easily cut'n'pasted into your favorite editor, once it gets unwieldy.

(*) Yes, there are non-GPL alternatives with the same API. But someone, somewhere will distribute a binary linked against a GPL library and then might have to deal with the consequences.
