### ISSUE TITLE
LuaJIT defunct?  Kill -9 lead to process state becoming DN or ZNL?

### ISSUE THREAD

**Issue by AlecWong** [LuaJIT/LuaJIT#220]
Hi there,  I recently encounter with a problem..
When I use  torch (scripts written in Lua) to train models, there will be a process `LUAJIT` (the Lua interpreter). And sometimes when I use `kill -9` to send the SIGKILL signal to the `LUAJIT` process, it just switch its state to `ZNL` or `DN` state. And remaining no response to any signals: `sudo kill -9  or kill -9.`  Even worse, if I tap `nvidia-dmi` in the terminal, it just no response.? 

( It seems this problem may occur when the GPU is TITAN, while it's fine for TITAN X.  )

**Comment by MikePall** [comment]
This is unlikely to be a problem of LuaJIT itself, since it doesn't do anything, that could possibly cause a lockup of a thread in kernel. Looks more a like a driver problem in the GPGPU integration of Torch.

You should ask on Torch issue tracker or mailing list. Closing here.
