### ISSUE TITLE
Traces still available after flushing

### ISSUE THREAD

**Issue by lukego** [LuaJIT/LuaJIT#229]
Traces can still be accessed via the introspection API (`jit.util`) after they have been flushed. Is a bug or a feature?

Demo code:

```lua
local util = require("jit.util")
for i = 1, 100 do end
local tr = 1
print(("trace #%d has %d instructions"):format(tr, util.traceinfo(tr).nins))
print("flushing...")
jit.flush(tr)
print(("trace #%d has %d instructions"):format(tr, util.traceinfo(tr).nins))
```

Output:

```
$ ./luajit -jv x.lua
[TRACE   1 x.lua:2 loop]
trace #1 has 7 instructions
flushing...
trace #1 has 7 instructions
```

**Comment by corsix** [comment]
Try throwing in a `collectgarbage()` call. That is, traces are garbage collected like other Lua objects, and `jit.flush` merely removes the reference to the trace from the bytecode at which it begins. Accordingly, the trace can still be obtained via its number until it is collected, at which point its number (and its memory) is released and available for re-use.

**Comment by lukego** [comment]
Thanks for the explanation. I might follow up with a patch to flag flushed traces as such, e.g. a special value on their link field, but only if this is actually practical for some reason.
