### ISSUE TITLE
Clear blacklisting state on jit.flush()?

### ISSUE THREAD

**Issue by lukego** [LuaJIT/LuaJIT#232]
Looks to me like when a bytecode is "blacklisted" this mark is not cleared by `jit.flush()`. Is this interpretation correct? If so then is this a bug?

In the context of #218 it would seem valuable for `jit.flush()` to clear blacklistings. This way the JIT could compile a loop whose bias has changed away from an NYI path.

Example that has potential to form a trace after a branch bias changes, but does not due to blacklisting that survived across a `jit.flush()`:

``` lua
for _, nyi in pairs({true, false}) do
   jit.flush()
   -- First iteration calls an NYI function (pcall).
   -- Second iteration is not JITed due to earlier blacklisting.
   for i = 1, 1e6 do
      if nyi then
         pcall(function () end)
      end
   end
end
```

Output showing that no trace is formed:

```
[TRACE flush]
[TRACE --- test.lua:3 -- NYI: bytecode 51 at test.lua:5]
[TRACE --- test.lua:3 -- NYI: bytecode 51 at test.lua:5]
[TRACE --- test.lua:5 -- NYI: return to lower frame]
[TRACE --- test.lua:3 -- NYI: bytecode 51 at test.lua:5]
[TRACE --- test.lua:5 -- NYI: return to lower frame]
[TRACE --- test.lua:3 -- NYI: bytecode 51 at test.lua:5]
[TRACE --- test.lua:5 -- NYI: return to lower frame]
[TRACE --- test.lua:3 -- NYI: bytecode 51 at test.lua:5]
[TRACE --- test.lua:5 -- NYI: return to lower frame]
[TRACE --- test.lua:3 -- NYI: bytecode 51 at test.lua:5]
[TRACE --- test.lua:5 -- NYI: return to lower frame]
[TRACE --- test.lua:3 -- NYI: bytecode 51 at test.lua:5]
[TRACE --- test.lua:5 -- NYI: return to lower frame]
[TRACE --- test.lua:3 -- NYI: bytecode 51 at test.lua:5]
[TRACE --- test.lua:5 -- NYI: return to lower frame]
[TRACE --- test.lua:3 -- NYI: bytecode 51 at test.lua:5]
[TRACE --- test.lua:5 -- NYI: return to lower frame]
[TRACE --- test.lua:3 -- NYI: bytecode 51 at test.lua:5]
[TRACE --- test.lua:5 -- NYI: return to lower frame]
[TRACE --- test.lua:3 -- NYI: bytecode 51 at test.lua:5]
[TRACE --- test.lua:5 -- NYI: return to lower frame]
[TRACE --- test.lua:5 -- NYI: return to lower frame]
[TRACE flush]
```

Seems like the issue is that blacklisting is accomplished by patching a bytecode like `LOOP` (i.e. a loop that could be JITed) with a replacement like `ILOOP` (i.e. a loop that must be interpreted) but that this is never undone. The code to undo the mark exists but it would need to be called on all of the right prototypes somehow e.g. by maintaining a list of blacklisted prototypes or walking the heap to search for them. I am not sure which approach would be best...?

**Comment by lukego** [comment]
(Relatedly: `jit.v()` is not reporting the blacklisting although I can separately confirm that the C function `blacklist_pc()` is being called. Could be a bug in JIT event reporting? I am testing v2.1 @ 716f2daef8019ce53d75d2c376c74b8f478fd5c5.)

**Comment by Laaas** [comment]
What about a function-specific jit.flush?
e.g.
```lua
local function NYI(nyi)
  for i = 1, 1e6 do
    if nyi then pcall(function() end) end
  end
end

for _, nyi in pairs({true, false}) do
   jit.flush(NYI)
   -- First iteration calls an NYI function (pcall).
   -- Second iteration is not JITed due to earlier blacklisting.
   NYI(nyi)
end```
