### ISSUE TITLE
 Where can I find opcode ISTYPE ISNUM TGETR TSETR description？

### ISSUE THREAD

**Issue by lpcdma** [LuaJIT/LuaJIT#237]
E.g this description
![qq 20161108183057](https://cloud.githubusercontent.com/assets/2943003/20095703/8ab51e96-a5e1-11e6-995f-9ce0ae3a44ad.png)
I can't restore it by assembly
Please help me, thank you.

**Comment by MikePall** [comment]
The description is specific to LuaJIT 2.0 bytecode.

`ISTYPE` etc. are opcodes used by LuaJIT 2.1 builtin functions. They shouldn't be seen or used anywhere else. There's no description, since the 2.1 bytecode format is not final, yet.
