### ISSUE TITLE
Evaluation order in the LuaJIT implementation?

### ISSUE THREAD

**Issue by lukego** [LuaJIT/LuaJIT#238]
Does the LuaJIT _implementation_ have a strict evaluation order (e.g. left-to-right or right-to-left) for any of these cases?

1. Function argument evaluation: `foo(X(), Y())`.
1. Multiple assignment: `x,y = X(),Y()`.
1. Table constructors: `{x=X(),y=Y()}`.
1. ... other important situations that I have not thought of?

(I am hoping that I can rely on at least strict left-to-right evaluation of function arguments when working with LuaJIT 2.1.)

**Comment by MageSlayer** [comment]
> (I am hoping that I can rely on at least strict left-to-right evaluation of function arguments when working with LuaJIT 2.1.)

Personally, I doubt it's a good idea. 
See http://lua-users.org/lists/lua-l/2006-06/msg00378.html

**Comment by MikePall** [comment]
The evaluation order is undefined.

**Comment by lukego** [comment]
Thanks for clarifying!
