### ISSUE TITLE
Drop tuning for ancient x86 Intel Atom CPUs

### ISSUE THREAD

**Issue by MikePall** [LuaJIT/LuaJIT#24]
This is mainly about the `JIT_F_LEA_AGU` flag. This involves some tuning for deficiencies of these CPUs wrt. AGU <-> ALU forwards.

Actually, this only applies to really old Intel Atom CPUs, that were soldered into netbooks around 2008 (remember those?). AFAIK the newer CPUs under the Atom brand have very different code tuning requirements, which are more in line with the desktop CPUs (i.e. don't worry, just emit plain and simple machine code).

One should evaluate whether the AGU/ALU issue is truly gone (delve into Agner docs) and then ruthlessly rip out all of the special cases.

**Comment by nico-abram** [comment]
Can this be ripped out?

In the agner document (I assume https://www.agner.org/optimize/microarchitecture.pdf , last updated 2019-12-30 as of this writing according to the first page) it still mentions these two things: https://i.imgur.com/anMkrOx.png and https://i.imgur.com/mS5Au2e.png . Is this sufficient to *not* rip out the special cases (And are we to assume that this document is up to date)?

**Comment by MikePall** [comment]
Well, yes, that applies to the original and obsolete Atom architecture. Today "Intel Atom" is just a trade name for reduced-performance implementations of the current Intel architecture.

Nowadays, the considerations for the use of LEA are complex and very CPU-specific, mostly dependent on the number of operands. It's unclear whether limiting fusion would be beneficial though. I doubt it, since the extra register pressure and/or extra instructions are not free, either. Unless there's compelling evidence to the contrary, I would rather keep the LEA fusion.

**Comment by MikePall** [comment]
Done.
