### ISSUE TITLE
LuaJIT 2.1.0-beta2 segmentation fault when set CONFIG_ARM64_VA_BITS = 48 on ARM64

### ISSUE THREAD

**Issue by zhangkehong2brad** [LuaJIT/LuaJIT#240]
Does LuaJIT 2.1.0-beta2 support user mode 48bit addr ?

I install LuaJIT 2.1.0-beta2 on arm64 server. When set CONFIG_ARM64_VA_BITS = 48, run luajit will result segmentation fault. While I change CONFIG_ARM64_VA_BITS to 39, luajit  run ok.

**Comment by zhangkehong2brad** [comment]
I have strace the luajit. From the log below, We can see that luajit mmap a memory which address is 0xffff9530a000. but then it run an error which error address is 0x7fff9530a381. The error address is diff from the mmap address. The highest bit is mask to 0. Do the code of LuaJIT have any address transfers? And if address transfer have 47bit mask?
---------------------------------------------------------------------------------------------------
-bash-4.3# strace ./luajit -v
execve("./luajit", ["./luajit", "-v"], [/* 21 vars */]) = 0
brk(0)                                  = 0xd724000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xffff955e1000
faccessat(AT_FDCWD, "/etc/ld.so.preload", R_OK) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=28544, ...}) = 0
mmap(NULL, 28544, PROT_READ, MAP_PRIVATE, 3, 0) = 0xffff955da000
close(3)                                = 0
openat(AT_FDCWD, "/lib64/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0\267\0\1\0\0\0\20S\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=915568, ...}) = 0
mmap(NULL, 787096, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0xffff954f4000
mprotect(0xffff9559b000, 98304, PROT_NONE) = 0
mmap(0xffff955b3000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xaf000) = 0xffff955b3000
close(3)                                = 0
openat(AT_FDCWD, "/lib64/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0\267\0\1\0\0\0\200\16\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=74256, ...}) = 0
mmap(NULL, 131296, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0xffff954d3000
mprotect(0xffff954d6000, 114688, PROT_NONE) = 0
mmap(0xffff954f2000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xf000) = 0xffff954f2000
close(3)                                = 0
openat(AT_FDCWD, "/lib64/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0\267\0\1\0\0\0\360(\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=77976, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xffff955d9000
mmap(NULL, 141888, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0xffff954b0000
mprotect(0xffff954c3000, 61440, PROT_NONE) = 0
mmap(0xffff954d2000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x12000) = 0xffff954d2000
close(3)                                = 0
openat(AT_FDCWD, "/lib64/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0\267\0\1\0\0\0\244\363\1\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1873736, ...}) = 0
mmap(NULL, 1594368, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0xffff9532a000
mprotect(0xffff9548c000, 106496, PROT_NONE) = 0
mmap(0xffff954a6000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x16c000) = 0xffff954a6000
mmap(0xffff954ac000, 13312, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0xffff954ac000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xffff955d8000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xffff955d7000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xffff955d6000
mprotect(0xffff954a6000, 16384, PROT_READ) = 0
mprotect(0xffff954f2000, 4096, PROT_READ) = 0
mprotect(0xffff955b3000, 4096, PROT_READ) = 0
mprotect(0xffff955e4000, 4096, PROT_READ) = 0
munmap(0xffff955da000, 28544)           = 0
mmap(NULL, 131072, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xffff9530a000
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x7fff9530a381} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)

**Comment by MikePall** [comment]
There have been some fixes for 48 bit VA support in the meantime.

But ... the strace output looks like you've compiled LuaJIT with non-standard options. E.g. LUAJIT_USE_SYSMALLOC most probably doesn't work on a 48 bit VA system.

**Comment by zhangkehong2brad** [comment]
I simple run make to compile the LuaJIT.  Is there any options that I need to change to compile the LuaJIT?

For 48 bit VA support, which version is fixed that I can try again?

**Comment by zhaozg** [comment]
please pull head of v2.1 branch

**Comment by zhangkehong2brad** [comment]
I tried the v2.1 branch just now. It runs well. Thanks
