### ISSUE TITLE
Immutability of FFI metatypes

### ISSUE THREAD

**Issue by lukego** [LuaJIT/LuaJIT#246]
I am curious about the motivation for the immutability of FFI metatypes:

> The association with a metatable is permanent and cannot be changed afterwards. Neither the contents of the metatable nor the contents of an __index table (if any) may be modified afterwards.

Is the purpose of this restriction to make more information fixed at recording time in order to generate tight code? If so then, in principle, could this restriction be replaced with a mechanism that detects when an FFI metatype is changed and automatically flushes all traces that reference the relevant FFI type?

(Generally I am wondering whether more aggressive optimizations would be possible without restricting language semantics, by detecting barrier operations and flushing traces that may need to be re-recorded.)

**Comment by MikePall** [comment]
Given the FFI is a new API, it makes sense to add well-considered restrictions that don't pose any problems in practice and that are beneficial for performance.

**Comment by LennyPenny** [comment]
I would love to read such 'epic rant' :thinking: 
Got any pointers?
