### ISSUE TITLE
Alternative to the lua_cpcall(L, f, &x) pattern

### ISSUE THREAD

**Issue by DemiMarie** [LuaJIT/LuaJIT#255]
When working with plain Lua 5.1, the standard pattern for calling into Lua from a function that cannot throw a Lua error is:

```c
struct data {
  lua_State *L;
  int alpha;
  char *beta;
  ...
};
void actual_callback (lua_State *L) {
   struct data *data = (struct data*)lua_touserdata(L, -1);
   /* do something */
}
void library_callback(void *callbackinfo) {
   int retval = lua_cpcall(((struct data*)callbackinfo)->L, actual_callback, callbackinfo);
   /* do something with retval */
}
```

Unfortunately, there is no good way to allocate `callbackinfo` on platforms with >47 bit virtual address space.  In many cases, one cannot use a static object because of thread safety requirements, and stack, heap, and thread-local storage may all be too high in memory.

What is the recommended workaround?  One option is pass `NULL` as the third argument of `lua_cpcall` and pass the actual data in thread-local storage.  This is both slower and ugly.

Note that pushing a full userdata won't work, since `lua_pushuserdata` can throw an error in the event of an allocation failure.  I know that LuaJIT is not in general robust against allocation failure (which is a bug unto itself), but in some cases throwing from a callback immediately invokes Undefined Behavior.

**Comment by daurnimator** [comment]
FWIW I mentioned this issue here: https://github.com/LuaJIT/LuaJIT/pull/230#issuecomment-262864138

**Comment by DemiMarie** [comment]
Can `lua_cpcall` ever trigger a garbage collection?  If not, would it be okay for a bad value to be on the stack temporarily, as long as it was overwritten before a GC could occur?

**Comment by DemiMarie** [comment]
@MikePall If `lj_vm_cpcall` were exported, could it be used for the purpose?

**Comment by MikePall** [comment]
See #230
