### ISSUE TITLE
How to add CMPXCHG to DynASM?

### ISSUE THREAD

**Issue by lukego** [LuaJIT/LuaJIT#257]
I would like to use the x86 instruction `CMPXCHG` in DynASM but it seems to be not supported at present.

Would anybody care to demonstrate how to add support for this instruction? This could be a nice gentle supplement to DynASM source code which is quite dense.

**Comment by corsix** [comment]
Start at the Intel manual, which documents `cmpxchg` as:
```
        0F B0 /r   CMPXCHG r/m8, r8     Compare AL with r/m8. If equal, ZF is set and r8 is loaded into r/m8. Else, clear ZF and load r/m8 into AL.
  REX + 0F B0 /r   CMPXCHG r/m8**,r8    Compare AL with r/m8. If equal, ZF is set and r8 is loaded into r/m8. Else, clear ZF and load r/m8 into AL.
        0F B1 /r   CMPXCHG r/m16, r16   Compare AX with r/m16. If equal, ZF is set and r16 is loaded into r/m16. Else, clear ZF and load r/m16 into AX.
        0F B1 /r   CMPXCHG r/m32, r32   Compare EAX with r/m32. If equal, ZF is set and r32 is loaded into r/m32. Else, clear ZF and load r/m32 into EAX.
REX.W + 0F B1 /r   CMPXCHG r/m64, r64   Compare RAX with r/m64. If equal, ZF is set and r64 is loaded into r/m64. Else, clear ZF and load r/m64 into RAX.
```
Find something with a not too dissimilar encoding, say these variants of `test`:
```
        84 /r   TEST r/m8, r8     AND r8 with r/m8; set SF, ZF, PF according to result.
  REX + 84 /r   TEST r/m8*, r8*   AND r8 with r/m8; set SF, ZF, PF according to result.
        85 /r   TEST r/m16, r16   AND r16 with r/m16; set SF, ZF, PF according to result.
        85 /r   TEST r/m32, r32   AND r32 with r/m32; set SF, ZF, PF according to result.
REX.W + 85 /r   TEST r/m64, r64   AND r64 with r/m64; set SF, ZF, PF according to result.
```
Find where `test` is listed in `dasm_x86.lua`:
```lua
  test_2 =	"mr:85Rm|rm:85rM|Ri:A9ri|mi:F70mi",
```
Extrapolate to the following: [1]
```lua
  cmpxchg_2 =	"mr:0FB1Rm",
```
(Not tested, just blindly extrapolated, use at own risk)

-----
[1] OK, the extrapolation isn't completely watertight: `|` as a separator is guessable, `Ri:A9ri` and `mi:F70mi` are easily discarded as the variants of `test` which take an immediate value, `rm:85rM` can be tentatively discarded by noting that `test` is symmetric in its arguments and DynASM is being friendly by listing a variant not in the Intel manual. This leaves `mr:85Rm`. The following verifications are left to the reader: that `m` corresponds to `r/m`, that `r` corresponds to `r`, that hex chars accumulate to form the opcode, that `R` corresponds to `/r` from the 2nd operand (maybe verify this last), that `m` corresponds to ModRM from the 1st operand, that standard opcode mods (`-1 for "b", o16 prefix for "w", rex.w for "q"`) apply by default, and that 32/16/8 or 64/32/16/8 (`"dwb" or "qdwb"`) variants are created by default.

**Comment by lukego** [comment]
Thanks for the tutorial! I'll test it.

**Comment by lukego** [comment]
via Russ Cox on Twitter:

> Intel published an open-source machine-readable (non-PDF) description of the x86 instruction set. https://github.com/intelxed/xed/tree/master/datafiles

Could this be interesting for DynASM in the future?

**Comment by astocko** [comment]
@lukego In the next few days, I will be releasing a Rust based XED datafiles parser/converter primarily for generating the op map for https://github.com/CensoredUsername/dynasm-rs and for use in a couple of other projects. I could add support for generating DynASM template strings as well.

**Comment by lukego** [comment]
@astocko I missed your message earlier, but that would be really awesome to be able to automatically generate the DynASM instruction encodings from XED! I wonder if we could even gain AVX512 support this way?

Curious: How has your experience been operating on the XED data without using their C code?

**Comment by lukego** [comment]
(Closed to avoid clutter.)
