### ISSUE TITLE
How to support LuaJIT in 64-bit Windows kernel-mode addressing ( Address range 0xFFFF0000`00000000 - 0xFFFFFFFF`FFFFFFFF )

### ISSUE THREAD

**Issue by hendrikp** [LuaJIT/LuaJIT#258]
I have the problem that I would like to use LuaJIT inside of a program run by a realtime-extension (RTX64) running in the Windows kernel-mode, however the address range is not compatible with LuaJIT, as LuaJIT requires all upper bits to be zero'ed not set)

- Some details about the x64 windows kernel mode addressing: http://www.codemachine.com/article_x64kvas.html

1. Do you think this problem is solveable without substantial performance loss?
2. Where would be the places be to "fix" the addresses (Set all the upper bits after their extraction from the nan-tagged doubles).
3. Would it be possible that you add a precompiler define LJ_64_KERNELMODE or similar that handles this case?

Thank you

**Comment by corsix** [comment]
You're out of luck; LuaJIT's address space layout requirements are pervasive and not easily changed.

**Comment by hendrikp** [comment]
So there is not a central place where with even a performance hit the upper bits could be set again?
