### ISSUE TITLE
Add ARM64 JIT compiler backend

### ISSUE THREAD

**Issue by MikePall** [LuaJIT/LuaJIT#26]
It should not be difficult to find sponsors for this feature, since ARM Holdings plc and their hardware partners want to invade the server world with this architecture. Also, Android is heading for ARM64, too (not in user mode, yet).

IMHO ARM64 is the cleanest 64 bit architecture so far and writing the backend should be a joy. Lots of low-hanging fruit for on-the-fly optimizations in the backend.

However, there's the ugly issue #25, on which this depends on.

**Comment by joeyu** [comment]
Is there anybody that is willing to work on this if there is a sponsorship in place?

**Comment by drbo** [comment]
@joeyu I almost certainly am, but I would need to learn ARM64 assembler first, which I am willing to do.

**Comment by MikePall** [comment]
What matters more than willingness is experience.

Ask @corsix.

Or ask RT-RK.com, they did the MIPS soft-float port and are working on the MIPS64 port (sponsored by Cisco).  (I'm not affiliated)

**Comment by joeyu** [comment]
Thanks, @MikePall, @drbo.

**Comment by drbo** [comment]
@MikePall Is this true for all work on LuaJIT?

In particular, is it true for #114 (Large penalty for frequent side-trace exit)?

**Comment by joeyu** [comment]
@MikePall @corsix If RT-RK.com is working on MIPS64 port, does it imply that the LJ_64GC common part (i.e. the architecture neutral part consisting of compiler data structures and frontent) will be covered? If so, will it overlap with the work of the other architecture ports like ARM64? Thanks.

**Comment by petar-jovanovic** [comment]
@joeyu Not everything has been scheduled yet, so hopefully no work will get duplicated.

**Comment by stevewin64** [comment]
Any update on this?  It looks like progress has been made in  #149 

Side note - I assume (hope) supported target OS for build will include Linux arm64? (not just IOS) (I'm specifically interested in Ubuntu 16.04)

**Comment by petar-jovanovic** [comment]
@stevewin64 The work in ongoing, and yes, it will applicable for Linux distributions.

**Comment by stevewin64** [comment]
Thanks @petar-jovanovic .  Is there any gross estimate or target for initial availability?

**Comment by MikePall** [comment]
Merged.
