### ISSUE TITLE
Unable to create anonymous opaque struct, required for solving circular dependencies

### ISSUE THREAD

**Issue by L-as** [LuaJIT/LuaJIT#260]
S = ffi.typeof("struct") doesn't work.

This is required for solving circular dependencies without actually naming the structs in the C namespace.

Example:
```
A = ffi.typeof("struct"); -- This *does* look pretty weird.

B = ffi.typeof("struct {
  $*  a;
}", A);

-- Unclear how it should be
ffi.cdef("struct $ {
  $* b;
}", A, B);
```

C equivalent:
```
struct A;

struct B {
  struct A* a;
};

struct A {
  struct B* b;
};
```

**Comment by MikePall** [comment]
Sorry, but I do not see a way to handle that edge case without major contortions. It works when you give the struct a name.
