### ISSUE TITLE
How to get fd from Lua's file handle

### ISSUE THREAD

**Issue by spacewander** [LuaJIT/LuaJIT#262]
It seems there was an idea:
http://lua-users.org/lists/lua-l/2011-05/msg00310.html

But none of `io.fdopen()` and `fp:fileno()` could be used in the latest version of LuaJIT.
Is there any plan to implement them? Or there is already another way to get the fd?

Any reply is welcome, thanks!

**Comment by corsix** [comment]
You can use the FFI to declare `fileno`:
```
$ ./luajit 
LuaJIT 2.1.0-beta2 -- Copyright (C) 2005-2016 Mike Pall. http://luajit.org/
JIT: ON SSE2 SSE3 SSE4.1 BMI2 fold cse dce fwd dse narrow loop abc sink fuse
> ffi=require"ffi"
> ffi.cdef"int fileno(struct FILE* stream);"
> =ffi.C.fileno(io.stdin)
0
> =ffi.C.fileno(io.stdout)
1
> =ffi.C.fileno(io.stderr)
2
> f=io.open"luajit.c"
> =f
file (0x7fff95d9d0b0)
> =ffi.C.fileno(f)
3
```

**Comment by daurnimator** [comment]
You can happily get cast a `FILE*` userdata to a `FILE*` (not officially documented, but [Mike mentioned he won't break this](http://lua-users.org/lists/lua-l/2011-05/msg00312.html)), from there you can use `fileno`.

If you're using the normal lua C API, see e.g. https://github.com/daurnimator/lua-psl/blob/d4e950a314cb37587294850dd82faa7fc1759e21/psl/psl.c#L26

If you're using the ffi, see @corsix's answer above.

**Comment by spacewander** [comment]
@corsix @daurnimator 
Great! This works like a charm!
You guys help me a lot.
