### ISSUE TITLE
string.sub sometimes returns incorrect slice

### ISSUE THREAD

**Issue by jamessan** [LuaJIT/LuaJIT#264]
Neovim's test suite was periodically failing and after looking into it, it turns out that LuaJIT sometimes incorrectly handles `str:sub(i, j)`.

I instrumented the [test] to log the `i`, `j`, and `size` of the returned string.  A snippet of the relevant code is below:

```lua
local shift = 0
while shift < #fcontents do
  local size = 3
  local s = fcontents:sub(shift + 1, shift + size)
  if shift + size < #fcontents then
    io.stdout:write('shift+1: '..(shift)..', shift+size: '..(shift+size)..', s: '..#s..'\n')
    eq(size, #s)
  end
  local wr = file_write(fp, s)
  eq(wr, #s)
  shift = shift + size
end
```

`fcontents` is a string of 4096 bytes, which we take 3 bytes at a time and write to a file.  Sometimes, this fails because `fcontents:sub` returns the rest of the string instead of just the slice requested.  As an
example:

    …
    shift+1: 2931, shift+size: 2934, s: 3
    shift+1: 2934, shift+size: 2937, s: 3
    shift+1: 2937, shift+size: 2940, s: 3
    shift+1: 2940, shift+size: 2943, s: 1156
    not ok 192 - file_write can write the whole file by small chunks

The final call (`fcontents:sub(2940, 2943)`) returned a slice from 2940 →
4096 (1156 bytes).

So far I've only seen this on mipsel systems.  In particular, I've seen this on Debian's [eller] porterbox and [mips-aql-01] buildd.

[test]: https://github.com/neovim/neovim/blob/207ba359b0127fa5893b980abcb9186ffec1879c/test/unit/os/fileio_spec.lua#L319-L334
[eller]: https://db.debian.org/machines.cgi?host=eller
[mips-aql-01]: https://db.debian.org/machines.cgi?host=mips-aql-01

**Comment by MikePall** [comment]
* Please always provide a complete, self-standing test case that can be directly run by the standalone LuaJIT executable.
* Please indicate the version of LuaJIT tested and the exact build environment and build options you've used.
* Please confirm that you've tested against git HEAD of 2.0 and 2.1, too -- and it's outcome.

I cannot reproduce this under QEMU mipsel, but maybe I haven't conjured up the right test from your snippet.

**Comment by sindrom91** [comment]
Observed similar issues with `string.sub` before [ffgccheck's delay slot](https://github.com/LuaJIT/LuaJIT/commit/62af10152433c45e5d83e442538fabf1f57f189b)  was fixed.

**Comment by jamessan** [comment]
This was encountered with Debian's build of 2.0.4.  I can provide more details and work on a smaller reproduction, if it's still needed after @sindrom91's comment.

**Comment by jamessan** [comment]
I've confirmed that it happens with Debian's 2.0.4 and 2.1.0 beta2.  I'll try building the head of both branches and reproducing.

**Comment by jamessan** [comment]
HEAD of master and v2.1 both work fine and 62af10152433c45e5d83e442538fabf1f57f189b is indeed the commit the fixed the issue (according to a bisect and letting the test suite run for awhile to see whether the intermittent failure happens).
