### ISSUE TITLE
Can't pass 64bit int to C function

### ISSUE THREAD

**Issue by vadz1999** [LuaJIT/LuaJIT#271]
```
int lua_invoke(lua_State *L)
{
	std::cout << std::hex << lua_tointeger(L, 1) << std::endl;
        return 0;
}
```
When i call it like invoke(0xFFFFFFFFFFFFFFFF) output is `8000000000000000`
For invoke(0x21F191D9AFF98B5E) `21f191d9aff98c00`

**Comment by daurnimator** [comment]
This is expected. In lua 5.1 lua_tointeger returns a lua_Integer, which is 32bits.

**Comment by MikePall** [comment]
Use the FFI to create and pass actual 64 bit integers to C functions.

Note: `0xffffffffffffffff` is a plain Lua number, i.e. a double and rounded to some different value. Use `0xffffffffffffffffULL` to create an FFI 64 bit unsigned integer.

**Comment by vadz1999** [comment]
Oh, thanks! That is what i really was looking for
