### ISSUE TITLE
math.random(a, b) may return a value bigger than b.

### ISSUE THREAD

**Issue by henriquegemignani** [LuaJIT/LuaJIT#274]
If you pass two double numbers to `math.random`, there's a chance the generated number is bigger than the second number.

See the following test case:
```lua
local a, b = -72.3, 42.6
for _ = 1, 10000000 do
    if math.random(a, b) > b then
        error("Invalid random return!")
    end
end
```

Something special: if `a+b` fits in an integer, the random does not fail.

**Comment by Laaas** [comment]
How much bigger is the randol value?

Den 20/01/2017 19.26 skrev "Henrique Gemignani Passos Lima" <
notifications@github.com>:

**Comment by henriquegemignani** [comment]
With some variations and some tests, the biggest value I found was `math.random(10.8, 20.9)` returning `21.8`.

Test Code:
```lua
local a, b = ...

local high = -math.huge
for _ = 1, 10000000 do
    high = math.max(math.random(a, b), high)
end
print(high)
```

Invoking:
```shell
for a in $(seq 0 9); do for b in $(seq 0 9); do echo -n "$a $b: "; ./src/luajit fun.lua 10.$a 20.$b; done; done
```

**Comment by MikePall** [comment]
Quoting the Lua manual:

> When called **with two integer numbers** m and n, math.random returns a uniform pseudo-random integer in the range [m, n].

I.e. you're passing arguments that invoke undefined behavior and then all bets are off. There's no hand-holding, in case you pass non-integer arguments (the check would be too expensive).

**Comment by iryont** [comment]
Lua 5.3 does report an error:

```bad argument #1 to 'random' (number has no integer representation)```
