### ISSUE TITLE
__gc receiving wrong argument if collection occurs during coroutine execution

### ISSUE THREAD

**Issue by Openarl** [LuaJIT/LuaJIT#276]
I've found under some conditions, a garbage collection during the execution of a coroutine will result in userdata's __gc metamethods being called with the thread as the argument, instead of the userdata.

It occurs reliably in the program I'm developing, but I haven't been able to find an isolated test case for it; I suspect it only occurs when the metamethod is a C function.

I've tested against the heads for both 2.0 and 2.1; the only difference in behaviour is that the resulting error raised by the metamethod is propagated outside of the coroutine in 2.0, and caught by coroutine.resume in 2.1. Interestingly, in 2.1 instead of .resume returning the error string, it returns the userdata that was being finalised.

Built with VS2010 x86 on Win7.

**Comment by MikePall** [comment]
I don't think this can be tracked down without an isolated testcase.

I suggest you turn on assertions and carefully inspect all changes to the Lua main thread and coroutine stacks, too. It's probably unbalanced somewhere.

Or maybe you haven't anchored your coroutines: the object returned by `lua_newthread()` on the Lua stack must be anchored somewhere on the Lua side ... it's not sufficient to keep just the returned `lua_State` pointer on the C side.

**Comment by Openarl** [comment]
False alarm!

I took a fresh look at the code and almost immediately saw the problem: the routine that verified that the argument was a userdata of the expected type was operating on the main thread's stack, instead of the coroutine's stack. If I hadn't bothered to add that check for the __gc method the code would have worked fine... a little ironic.

That still leaves the question of why the thread object was sitting on the main stack during that call. Undocument feature, I presume? Actually the contents of the main stack during coroutine execution doesn't seem to be documented at all (not surprising as it's of little relevance normally). I wish I'd known about it though; it would have made the cause of the problem blindingly obvious.
