### ISSUE TITLE
Does it a bug about luajit?

### ISSUE THREAD

**Issue by hongliang5316** [LuaJIT/LuaJIT#278]
see code.
```lua
local ffi = require "ffi"


 print(ffi.new("uint64_t", 9999999999999998))

 --result: 9999999999999998ULL

 print(ffi.new("uint64_t", 9999999999999999))

 --result: 10000000000000000ULL   why does this result happend?

 print(ffi.new("uint64_t", 9999999999999999ULL))

 --result: 9999999999999999ULL

```

**Comment by javierguerragiraldez** [comment]
>  print(ffi.new("uint64_t", 9999999999999999))

the `9999999999999999` here is a Lua number, passed in a Double.  Since it's bigger than 2^52, it doesn't have full integer resolution.

**Comment by hongliang5316** [comment]
@javierguerragiraldez thanks for your answer, but the `9999999999999998` is also bigger then 2^52, it looks work well.

**Comment by javierguerragiraldez** [comment]
just luck.  it was rounded too, but to itself.  you're missing bits at the end, so first odd numbers are rounded to even ones, then to multiples of 4, and so on.   (http://floating-point-gui.de/)
