### ISSUE TITLE
Feature request: lj_cpcall

### ISSUE THREAD

**Issue by DemiMarie** [LuaJIT/LuaJIT#279]
This is a feature request for a new API: `lj_cpcall`.  This has the following form:

```c
typedef void(*lj_cpcall_callback)(lua_State *state, void *user);
int lj_cpcall(lua_State *state, lj_cpcall_callback callback, void *user, int ret);
```

`lj_cpcall` calls `callback` in a protected environment.  On entry, it does not alter the stack in any way whatsoever.  On exit, the stack is adjusted to `ret` values, unless `ret` is set to `LUA_MULTRET`, in which case it is not adjusted.

The `void *user` argument is passed unchanged to the callback.  It is not pushed as a lightuserdata.  Therefore, it does not need to be within the valid range for a lightuserdata.

**Comment by MikePall** [comment]
See #230
