### ISSUE TITLE
For anyone interested in: Lua pure version of LuaJIT's sort algorithm

### ISSUE THREAD

**Issue by DarkRoku12** [LuaJIT/LuaJIT#281]
Hello LuaJIT community.

I was working on a project that is LuaJIT based, and watching the [NYI](http://wiki.luajit.org/NYI#libraries_table-library) i saw that table.sort is not compiled.

So i was looking for a workaround (because i need table.sort to being compiled), and i arrived to #59 and tested severals algorithms quoted there and in others places too and realize that Mike marked it as `wontfix`  (don't know why).

I tested several Lua pure sort algorithms (most of them were Quicksort and one Smoothsort), but no one was faster than the (NYI) built-in table.sort, despite of those were fully compiled by the JIT.

So, i decided to look at lib_table.c and realize that was a Quicksort implementation with severals optimizations, so i decided to **port it to Lua.**

**I'm here only for sharing if anyone needs one.**
[Link to the github here](https://github.com/DarkRoku12/lua_sort)

**Details can be found in the readme.**

**Comment by Laaas** [comment]
The issue was probably closed because the licenses were incompatible.
I don't know why it's `wontfix` though.

Also, I'm really suprised that the performance of the sort implemented in Lua is so good with JIT off.

**Comment by MikePall** [comment]
For (plain Lua code) sort algorithms to be truly efficient, the compiler backend would either need #37 Hyperblock Scheduling (not planned) or intrinsics for branchless operations. Will open an issue and link this one here, once this is addressed.
