### ISSUE TITLE
mcode_alloc() doing busywork on exhausted allocation pool

### ISSUE THREAD

**Issue by akopytov** [LuaJIT/LuaJIT#283]
This is related to #282 and mmap() scalability issues. When the pool of available mmap() regions is exhausted in mcode_alloc() (which is possible on applications with many threads and architectures with a small `LJ_TARGET_JUMPRANGE` values), mcode_alloc() is doing a lot of busywork repeating attempts 32 times just to discover that no allocations are available and signal `LJ_TRERR_MCODEAL`. Which amplifies kernel-level scalability issues with mmap() performed concurrently within a single process on Linux.

It is hard to pick a good value that would work best in all cases. In my tests, replacing 32 with `LJ_TARGET_JUMPRANGE` (31 for x86, 27 for ARM64 -- these are 2 architectures that I care about) results in significant improvements. The warmup time for benchmarks required to stabilize throughput is reduced from tens of seconds to just a few seconds.

A more complicated approach would probably be blacklisting JIT states based on the number of failed mcode_alloc() calls, but a simple heuristic by replacing the hard-coded number of iterations in mcode_alloc() works well enough for me.

**Comment by MikePall** [comment]
Applied. Thanks!
