### ISSUE TITLE
LJ_PRNG_BITS() is too weak for multi-threaded applications

### ISSUE THREAD

**Issue by akopytov** [LuaJIT/LuaJIT#284]
This is related to #282, #283 and mmap() scalability issues.

mcode_alloc() uses LJ_PRNG_BITS() for randomized allocations. Which is probably good enough for applications with low concurrency and architectures when the available allocation pool is big (read "x86").

With high concurrency and small allocation pools (I tested on an ARM64 server with more than a hundred of cores), it results in many threads trying to allocate same blocks simultaneously, which amplifies contention on mmap() described earlier and leads to longer "warmup" times required to stabilize performance of JIT states.

In my microbenchmarks I got better warmup times by replacing LCG with [splitmix64](http://xoroshiro.di.unimi.it/splitmix64.c) and seeding it with rand() for each thread (and thus, each JIT state).

**Comment by MikePall** [comment]
Can't take this, as we don't want a dependency on `rand()` (and it's unclear and unportable guarantees). Also, this adds just another band-aid for the underlying issue.

See [my comment](https://github.com/LuaJIT/LuaJIT/issues/285#issuecomment-285194907) in #285.

**Comment by daurnimator** [comment]
Could you mix in `gettid()` just so it's different per-thread?

**Comment by akopytov** [comment]
The dependency on `rand()` can be easily avoided, I just picked it as the lowest hanging fruit. But I'm looking forward to a cleaner solution to the underlying issue you mentioned in #285. Thanks.

**Comment by MikePall** [comment]
Fixed.
