### ISSUE TITLE
Does luajit support MIPS which does not have FPU?

### ISSUE THREAD

**Issue by dedok** [LuaJIT/LuaJIT#298]
Subj.

**Comment by bigbes** [comment]
Try to use search, before asking questions https://github.com/LuaJIT/LuaJIT/issues/34#issuecomment-182567612

**Comment by MikePall** [comment]
For anyone stumbling upon this issue: yes, the v2.1 branch supports MIPS soft-float.

**Comment by dedok** [comment]
@MikePall thank you for the branch reference. I have not found correct branch and source code references across repo / issues.
