### ISSUE TITLE
GC64: BC_CALLM snapshot handling

### ISSUE THREAD

**Issue by nnikolaev-virtualopensystems** [LuaJIT/LuaJIT#299]
The following Lua snippet, demonstrates an issue with LuaJIT 2.1 on ARM64:

```lua
local ffi = require("ffi")
local vla_t = ffi.typeof("uint8_t[?]")

local t = {}
for i = 0, 255 do
   table.insert(t, vla_t(1))
end
print("done")
```

When this code is run on an ARM64 machine with the following arguments, it produces and error:
```shell
$ ./luajit -O3,-fold ../crash.lua 
./luajit: ../crash.lua:6: wrong number of arguments to 'insert'
$ uname -m
aarch64
```
The issue do not manifest itself if `-fold` is not present, or if the code is run on x86 or arm (32bit):
```shell
$ ./luajit -O3,-fold ../crash.lua 
done
$ uname -m
armv7l
```

**Comment by MikePall** [comment]
Confirmed bug.

The test suite shows a lot more failures with `-O-fold` on ARM64. Summoning @sindrom91 to have a look at it.

**Comment by sindrom91** [comment]
I can reproduce this bug on MIPS64 and x64 as well.

This fixes one (and only, for me) issue in the test suite on ARM64 (but not this particular issue):
```
diff --git a/src/lj_asm_arm64.h b/src/lj_asm_arm64.h
index 328e4d7..b58ab3a 100644
--- a/src/lj_asm_arm64.h
+++ b/src/lj_asm_arm64.h
@@ -286,7 +286,7 @@ static void asm_fusexref(ASMState *as, A64Ins ai, Reg rd, IRRef ref,
        }
        rm = ra_alloc1(as, lref, allow);
        rn = ra_alloc1(as, rref, rset_exclude(allow, rm));
-       emit_dnm(as, (ai^A64I_LS_R), rd, rn, rm);
+       emit_dnm(as, (ai^A64I_LS_R), (rd & 31), rn, rm);
        return;
       }
     } else if (ir->o == IR_STRREF) {
```

**Comment by MikePall** [comment]
Applied the patch. Thanks.

**Comment by MikePall** [comment]
This was a general issue with GC64 mode. Fixed.
