### ISSUE TITLE
FFI: Compile bit field access

### ISSUE THREAD

**Issue by MikePall** [LuaJIT/LuaJIT#30]
Handling bit fields in C structs is notoriously complicated. The memory layout is target-specific and compiler-specific. Most of that has been taken care of, but it hasn't been throughly tested for compatibility with the system C compiler.

Bit field access is currently NYI in the compiler frontend. There are some complications with unaligned accesses or split accesses. But one could implement the easier parts of that first.

Also, currently only fields of max. 32 bits are handled. Larger fields are not mandated by the standard, but this is a common C compiler extension.

**Comment by Wiladams** [comment]
+1  I've run across int64_t based bitfields, so I'm all for at least expanding the range.  But mostly not super high priority as I've only seen it once thus far.  Mostly code seems to stick to int32.

Getting those compiled would certainly be beneficial perf wise.

**Comment by DemiMarie** [comment]
I think I can do this.  Incidentally, my name is Demi Obenour, not Demetrios Obenour.

**Comment by DemiMarie** [comment]
I have a branch that tries (without any success so far) to compile them: <https://github.com/DemiMarie/LuaJIT/tree/ffi_bitfield_jit>.  I am currently hitting assertions in `rec_check_slots` and/or unexpected NYI trace bailouts.

**Comment by DemiMarie** [comment]
Pinging @corsix.

**Comment by DemiMarie** [comment]
Disabling assertions causes a segfault in the assembler, which is to be expected given that the IR is bogus (I get assertions in `rec_check_ir` if I move it manually to be before `rec_check_slots`).

**Comment by mraleph** [comment]
@DemiMarie instead of pinging people, you should read your code attentively and try to figure out if it make sense, e.g.

```c
tr = emitir(IRT(IR_BSHR, t), bitoff, tr);
```

does this line make sense?

or 

```
tr = emitir(IRT(IR_BAND, t), tr, lj_ir_kintp(J, (1ULL << bitoff) - 1U));
```

does this line make sense?

Both lines actually have bugs.

[I did not think about validity of the whole approach, just skimmed your code for obvious issues]

**Comment by DemiMarie** [comment]
@mraleph In fact neither made any sense.  Now fixed (and passes a simple test case) and submitted as #301.

**Comment by MikePall** [comment]
Bit field accesses are now compiled for v2.1.

Add a new enhancement issue for 64 bit bitfields, if needed.
