### ISSUE TITLE
Memory leak with closure based OOP approach

### ISSUE THREAD

**Issue by rm-code** [LuaJIT/LuaJIT#303]
Hello,

I ran into an issue with LuaJIT and using a closure based approach for OOP with Lua. For some reason the garbage collector doesn't seem to kick in for any of the memory when I use LuaJIT.

Here is a small example I wrote for testing:

```lua
local TestClass = {}

function TestClass.new()
    local self = {}

    local tiles

    local function sub( x, y )
        tiles[x] = tiles[x] or {}
        tiles[x][y] = { 'foo' }
    end

    local function iter()
        for x = 1, 2000 do
            for y = 1, 2000 do
                sub( x, y )
            end
        end
    end

    function self:init()
        tiles = {}
        iter()
    end

    return self
end

return TestClass
```

```lua
local TestClass = require( 'TestClass' )

local function memtest()
    collectgarbage()
    print( 'preCreation', collectgarbage( 'count' ))

    local class = TestClass.new()
    class:init()

    print( 'preCollection', collectgarbage( 'count' ))

    class = nil

    collectgarbage()
    print( 'postCollection', collectgarbage( 'count' ))
end

memtest()
```

Running the above with both `Lua` and `LuaJIT` gives the following result:
```
> lua test.lua
preCreation	24.9140625	936
preCollection	345416.2890625	296
postCollection	24.4453125	456

> luajit test.lua
preCreation	28.1396484375
preCollection	220133.54199219
postCollection	219625.75683594
```

As you can see LuaJIT doesn't seem to free the memory after the call. I even tried calling `collectgarbage` multiple times, but to no avail.

Any help would be highly appreciated since this a major issue for one of my current projects.

**Comment by rm-code** [comment]
It looks like passing the `tiles` variable to the functions instead of making them use it as an upvalue gets rid of the issue and memory is now freed correctly.

```lua
local TestClass = {}

function TestClass.new()
    local self = {}

    local tiles

    local function sub( tiles, x, y )
        tiles[x] = tiles[x] or {}
        tiles[x][y] = { 'foo' }
    end

    local function iter( tiles )
        for x = 1, 2000 do
            for y = 1, 2000 do
                sub( tiles, x, y )
            end
        end
    end

    function self:init()
        tiles = {}
        iter( tiles )
    end

    return self
end

return TestClass
```

**Comment by Alloyed** [comment]
other stuff: This behavior doesn't exist in `-joff` mode.

**Comment by tapir** [comment]
If you take out everything from the .new() function and just return the table, the problem still exist. So it's not about closures necessarily.

**Comment by rm-code** [comment]
> If you take out everything from the .new() function and just return the table, the problem still exist. So it's not about closures necessarily.

Please post the code you tested with, because I can't confirm this on my end. When I return a table from `TestClass.new` I get the following results:
```
preCreation	27.52734375
preCollection	27.55859375
postCollection	27.52734375
```

**Comment by tapir** [comment]
```lua
local TestClass = {}

local newClass = {}

local tiles

local function sub( x, y )
	tiles[x] = tiles[x] or {}
	tiles[x][y] = { 'foo' }
end

local function iter()
	for x = 1, 2000 do
		for y = 1, 2000 do
			sub( x, y )
		end
	end
end

function newClass:init()
	tiles = {}
	iter()
end

function TestClass.new()
	return newClass
end

return TestClass
```
This gives
```
preCreation     28.1494140625
preCollection   220060.25097656
postCollection  219625.67285156
```

**Comment by rm-code** [comment]
In your case that's expected behavior though since the reference to `tiles` is never removed. The variable is in the module's scope. 

Just add 
```lua
function TestClass.clear()
    tiles = nil
end
```
and call it before collecting garbage to see that everything is working fine:

```
preCreation	28.484375
preCollection	220127.5703125
postCollection	31.84375
```

**Comment by tapir** [comment]
Ah yes I see 👍

**Comment by MikePall** [comment]
Apart from what @rm-code said, please note that JIT-compiled code is cached and may reference some upvalues, too. You may need to augment your tests with `jit.flush()`.

**Comment by rm-code** [comment]
@MikePall Thanks for the quick help. I wasn't aware of `jit.flush()`, but it fixes my problems 👍
