### ISSUE TITLE
Most stable commit for arm64 callbacks?

### ISSUE THREAD

**Issue by rweichler** [LuaJIT/LuaJIT#304]
To be clear:

* This isn't a bug report, I'm sorry if I put this in the wrong place.
* I don't care about the JIT. Just the FFI.

Currently I'm using 892d370edd36ef748f3b6095a80f77798fac9bee with the JIT off, which seems to work pretty well. No crashes or anything (crashes a lot with the JIT on), but I'm running into some minor hiccups. Not sure if this is due to my code or the fact that arm64 callbacks are unstable. **It could just be that my code is the issue.**

I was wondering if a commit exists where the arm64 callbacks are rock solid?

**Comment by MikePall** [comment]
The ARM64 FFI callback code hasn't changed since it was created in January 2015.

It's possible this hasn't been exercised thoroughly, yet. FFI callbacks don't work on iOS, which happens to be the main user-base for LuaJIT/ARM64 so far. This is changing as we speak, since ARM64 is finally making inroads into the server space.

If your FFI code works fine on x86/x64, but fails on ARM64, then please start to file bug reports. I presume you're an experienced FFI user and you already know about cdata anchoring pitfalls etc.

Likewise, the ARM64 JIT is pretty fresh. If you find any issues with it, please file bug reports.

**Comment by rweichler** [comment]
I'm jailbroken, so I am able to use the C callback feature in the ffi. It's just that it tends to corrupt memory (or something). 

I don't know how I could file an effective bug report. I could post the code I'm using, but I don't think anyone who knows how to fix this uses LuaJIT on non-jailed iOS.

Is there any other way I could file a bug report?

_____

Anyway, here's my bad/hard-to-reproduce attempt at a bug report:

This is my code:

https://github.com/rweichler/cylinder/tree/4628821beca4c8cacabd752cab6803e1c5331f9c

Essentially, I'm `dlopen`ing that code and running init.lua in the SpringBoard process (which is where all the apps are launched from). If you change the `USE_C` variable at the top of init.lua to true, then the code works with absolutely no issues. But if you change it to false, then you'll start to notice some weirdness. The code "works", in the sense that the Lua function is cast to a C function and it behaves as expected, but if you try to launch any apps then they immediately crash. Further, if you scroll to the spotlight page you are unable to scroll back (however, if you `dlopen` after previously swiping to that page, this doesn't happen).

^ This probably will be of no use to anybody but me. I don't really know how else I could report this. I cannot test this on x86/x64 because MobileSubstrate isn't available for it.

**Comment by sindrom91** [comment]
You shouldn't load FFI module to a global variable. Try loading it to a local variable in every file that uses FFI. And make sure you read the FFI tutorial carefully.

**Comment by rweichler** [comment]
I have been using the ffi for about 2 years now, I know what I'm doing. :p For my use case putting the ffi in a local variable is counter productive because I use the ffi throughout my code. `require`ing at the top of each file would be very redundant. This isn't production code, anyway. Plus I don't see how that has anything to do with the issue at hand

**Comment by rweichler** [comment]
Just to confirm, with `USE_C` set to false on armv7, it works with no issues.

**Comment by DemiMarie** [comment]
@rweichler It is best to load it in a local variable for performance reasons.

What happens if the JIT is turned on?  Note that FFI operations without the JIT are very slow.

**Comment by DemiMarie** [comment]
I think I found the source of the crash: on [line 31] you use `ffi.cast()` to convert a Lua function to a C callback, but then pass the callback directly to C without storing it in a variable.  So the callback gets garbage collected.  Try storing the callback in a local variable and then calling `cb:free()` when done.

[line 31]: https://github.com/rweichler/cylinder/blob/4628821beca4c8cacabd752cab6803e1c5331f9c/init.lua#L31

**Comment by MikePall** [comment]
Please confirm/close if it's a simple FFI usage error.

**Comment by rweichler** [comment]
@DemiMarie Thank you for catching that, [however putting the callback in a global variable did not fix it](https://gist.github.com/rweichler/7b134d8b8c9e44e13017acb751d82f52#file-init-lua-L31-L32). AFAIK, a local variable would be garbage collected as well.

I'd like to state again that the process becomes unstable. No crash occurs. I'm guessing it's something like memory corruption or call stack corruption. [Note how after going to the spotlight page on the left after `dlopen`ing the Lua script, all new launched apps immediately crash.](https://www.youtube.com/watch?v=UMpvJ1R--7E)

_________

As for the other suggestions: thanks, but as for right now, code readability and maintainability is of utmost importance. I will about performance later on in my development cycle. I also avoid writing C code as much as possible. The point of this project is to allow newbie developers to contribute. Forcing them to install a toolchain and compile code is too much of a con in comparison to the relatively small performance loss.

That is also why I choose to use lua_call over lua_pcall whenever possible. I always put my error handling code on the Lua side. Therefore using lua_pcall is redundant.

Not that it matters, anyway. Once this issue is fixed, then I won't be using any C code at all, and I will be able to delete `hook.m`. It is simply a workaround until this instability issue is resolved.

**Comment by rweichler** [comment]
Sorry if this isn't the right place to put this (this would probably better go in the mailing list, but this already has so much context).

I really want this fixed and am willing to learn / do some research myself if it is necessary. However I don't really know where to start. I have a rudimentary understanding of assembly and how functions are called in C, something about pushing stuff to the stack in a certain way and jumping and whatnot.

Problem is I have no idea where to look for the documentation of how this stuff works on iOS ARM64. I'm looking in lj_callback.c and it seems like I could start messing around with the value for [CALLBACK_MCODE_HEAD](https://github.com/LuaJIT/LuaJIT/blob/8271c643c21d1b2f344e339f559f2de6f3663191/src/lj_ccallback.c#L60) and [these](https://github.com/LuaJIT/LuaJIT/blob/8271c643c21d1b2f344e339f559f2de6f3663191/src/lj_ccallback.c#L171-L189) other [chunks](https://github.com/LuaJIT/LuaJIT/blob/8271c643c21d1b2f344e339f559f2de6f3663191/src/lj_ccallback.c#L399-L418) of [code](https://github.com/LuaJIT/LuaJIT/blob/8271c643c21d1b2f344e339f559f2de6f3663191/src/lj_ccallback.c#L644-L648) in [there](https://github.com/LuaJIT/LuaJIT/blob/8271c643c21d1b2f344e339f559f2de6f3663191/src/lj_ccallback.c#L627-L629), but idk where the documentation for this kind of stuff would be. What would I look in? The ARM64 instruction set? Somewhere on the Apple docs? It seems like it could be related to#205 where you said that iOS has a [nonstandard ARM64 ABI](https://developer.apple.com/library/content/documentation/Xcode/Conceptual/iPhoneOSABIReference/Articles/ARM64FunctionCallingConventions.html). But in my example my function pointer only uses 3 arguments.

Where would I start?

**Comment by corsix** [comment]
> I don't think anyone who knows how to fix this uses LuaJIT on non-jailed iOS.

Let's say that **I** have OS X on a MacBook, and though I don't normally do any iPhone development or jailbreak my iPhones, I have an old iPhone 6 that I'm prepared to sacrifice in the name of ~~science~~ LuaJIT. What steps do I need to perform on the OS X side and on the phone side in order to reproduce the issue?

**Comment by rweichler** [comment]
@corsix 

1. If you're on 10.0-10.2, use Xcode or [Cydia Impactor](http://www.cydiaimpactor.com/) to sideload [this IPA](https://yalu.qwertyoruiop.com/yalu102_beta7.ipa) (Cydia Impactor is probably easier, and works on Linux/Mac/Windows). If you're on a lower version, [refer to this](https://canijailbreak.com/). If you're on 10.2.1 or higher, then you can't jailbreak. If this is the case, I can message you when a new one comes out
2. Open the app you sideloaded and click "go" to jailbreak.
3. Through Cydia, go to "Sources", then hit "Add", and type my repo URL: http://cydia.r333d.com
4. Go to search, and through that install "Lucy", "LuaJIT", "bash", "OpenSSH", "Tape Archive", "wget", and "Cydia Substrate".
5. SSH into your iPhone, using the username `root` and password `alpine`. 
6. Make sure `pwd` outputs either `/var/root` or `/private/var/root`. Then run this:

```
wget http://r333d.com/corsix.tar.gz
tar xvf corsix.tar.gz
cd test
lucy default < init.lua
```

Now try swiping the pages on your home screen. The icons should spin when you do a page swipe. At this point the memory/callstack/whatever corruption should have taken place.

In order to reset the phone back to a stable state, SSH in and run the command `killall backboardd`.

**Comment by rweichler** [comment]
@corsix just realized i gave you bad instructions.... i updated them, should work now. let me know how it goes

**Comment by rweichler** [comment]
@corsix What's the status on this? There is a jailbreak coming out soon for iOS 10.3.1 and lower.

If jailbreaking your phone is too much I can try recreating this for jailed iOS, I managed to get mcode working there.

**Comment by rweichler** [comment]
Could the issue perhaps be related to this?

> If you're building a 64 bit application on OSX which links directly or indirectly against LuaJIT, you need to link your main executable with these flags:
> 
> `-pagezero_size 10000 -image_base 100000000`

But what's weird is, when I don't use this flag on OS X, my application immediately segfaults. But I don't use this flag at all for iOS, it does not segfault.
