### ISSUE TITLE
Bytecode cross-compilation

### ISSUE THREAD

**Issue by goodguy97** [LuaJIT/LuaJIT#308]
Is there any way to generate windows luajit bytecode from linux application written in c++?

**Comment by Laaas** [comment]
I think the bytecode is the same for both linux and windows..?

**Comment by corsix** [comment]
Indeed; LuaJIT has different bytecode between v2.0 / v2.1, and between GC64-mode / not-GC64-mode, but not between Windows / Linux. As such, a Linux application should generate bytecode which works just fine on Windows application (unless the two applications differ in their LuaJIT version or GC64 mode setting).

**Comment by goodguy97** [comment]
many thanks for the fast reply, but can you help me once more?
Can you provide more info on what 4th byte mean?

There are the beginning of two files I got with lua_dump

vs2017: 1b4c 4a02 0018 4072 6573 6f75 7263 6573
g++: 1b4c 4a01 0018 4072 6573 6f75 7263 6573

**Comment by corsix** [comment]
That would be the bytecode version; `01` implies LuaJIT v2.0, whereas `02` implies LuaJIT v2.1.

**Comment by goodguy97** [comment]
Many thanks, i ll try to find out where is the problem
