### ISSUE TITLE
missing 64-bit expansion of resultofs (RA/RAa) before jumping to lj_vm_return

### ISSUE THREAD

**Issue by javierguerragiraldez** [LuaJIT/LuaJIT#319]
I got a spurious segfault inside `lj_vm_return`, specifically at: https://github.com/LuaJIT/LuaJIT/blob/v2.1/src/vm_x86.dasc#L532 :

    mov RBa, [BASE+RA]

or:

    mov rbp,QWORD PTR [rdx+rcx*1]

were `rcx` was `0xfffffff8`, evidently as a result of 32-bit arithmetic.  Since `lj_vm_returm` is usually reached direct jumping, there's no stack to point me to the previous instruction (and the Lua code has several different codepaths, including some API calls to C).  Searching in the interpreter code, I found at least two places where the result offset is set via `RA` (`ecx`, 32 bit) instead of `RAa` (`rcx`, 64 bits):

https://github.com/LuaJIT/LuaJIT/blob/v2.1/src/vm_x86.dasc#L738
and 
https://github.com/LuaJIT/LuaJIT/blob/v2.1/src/vm_x86.dasc#L5439-L5441

**Comment by MikePall** [comment]
The two places where the 32 bit register is used are OK. It cannot go negative for the first one, unless the frame structure on the stack is corrupted. The second one depends on the proper use of the return value of a Lua/C API function (which is in a 32 bit register, in any case).

I suspect one of your C API calls returns -2. But only -1 (yield) or 0..n is allowed. You can find out by setting a breakpoint on vm_returnc + 2 lines (after the jz). If ecx is negative there, then you can track down the buggy C function, that has just returned. The GCfuncC is still on the stack.

**Comment by MikePall** [comment]
No further info provided by reporter. Assuming programmer error. Closing.
