### ISSUE TITLE
Benchmark source code

### ISSUE THREAD

**Issue by domingues** [LuaJIT/LuaJIT#320]
Could the source code of the benchmarks done in [Performance Comparison](http://luajit.org/performance.html) be published? It would be very useful to replicate the results and benchmark changes on the VM.

**Comment by bigbes** [comment]
https://github.com/LuaJIT/LuaJIT-test-cleanup/tree/master/bench

With best regards, Eugene.

2017-04-06 14:11 GMT+03:00 domingues <notifications@github.com>:
