### ISSUE TITLE
FILE minilua VS ij_parse!

### ISSUE THREAD

**Issue by questionpython** [LuaJIT/LuaJIT#322]
hello,
FILE `minilua.c` VS `ij_parse.c`!

example:
typedef enum BinOpr in `lj_parse.c`
typedef enum BinOpr in `minilua.c`

why in 2 file?
why have 2 file for parser?

**Comment by kirbyfan64** [comment]
AFAIK `minilua.c` is a tiny version of Lua designed for bootstrapping (since DynAsm is written in Lua), and `lj_parse.c` is LuaJIT's actual parser.

**Comment by sindrom91** [comment]
You might find [this talk](https://www.youtube.com/watch?v=8Q0KLTma_FA) informative.
