### ISSUE TITLE
lua 5.1 API compliance broken

### ISSUE THREAD

**Issue by andresy** [LuaJIT/LuaJIT#325]
Since the commit https://github.com/LuaJIT/LuaJIT/commit/de97b9d52bbc42effeaf1180764053a912526873

luajit 2.1 defines luaL_setfuncs (and other lua 5.2 specific functions) in lauxlib.h; luaL_setfuncs (and others) are supposed to be only defined for lua 5.2 and up. A lot of open-source packages are relying on tests like "LUA_VERSION_NUM < 502" to define or not luaL_setfuncs on their own. Not sticking to lua 5.1 API breaks those packages.

**Comment by MikePall** [comment]
The `lua*` namespace is reserved for the VM itself. Lua/C Modules are not supposed to define any such symbol, not even for compatibility shims. These may cause conflicts, if multiple modules use them, too.

[Lua/C Modules are only allowed to define `luaopen_*` symbols.]

Instead, it would be better to notify the module authors.

**Comment by nicholas-leonard** [comment]
@MikePall I understand that you are technically correct to not care your new luajit breaks our nice little fixes. But we still can't take the risk of updating luajit as it could break a lot of Torch packages. And other packages which we don't control: https://github.com/mpx/lua-cjson/blob/master/lua_cjson.c#L1307 . Currently Torch's policy is to not update luajit to your new version. Is there any way that you could fix this on your end?

**Comment by neomantra** [comment]
@nicholas-leonard Like Torch, OpenResty is solution/distribution dedicated to LuaJIT (versus plain Lua).  OpenResty takes the approach that it maintains repos for its dependencies when it makes sense to.  Then it is not at the mercy of module authors.  Another option would be for Torch to use the OpenResty modules, knowing that the two projects interests are aligned.

This OpenResty lua-cjson commit is relevant (and is not adopted upstream, along with other changes):
https://github.com/openresty/lua-cjson/commit/55d22ef3bc5f512a9dadd84fd85895824dad73d9

**Comment by ahupowerdns** [comment]
Hi PowerDNS here, we're wondering what the most karmic way of doing this is. We just moved our luaL_setfuncs to pdns_luaL_setfuncs, but I'd still like to benefit from the native luaL_setfuncs if luajit offers it. The lua-cjson patch uses an unrelated #define to detect LuaJIT 2.1, but this seems fragile. Suggestions?

**Comment by vcunat** [comment]
@ahupowerdns: for knot-resolver I went for a pkg-config check on luajit version, but I'd prefer if there was some better way.

**Comment by evgeni** [comment]
Another issue is https://github.com/LuaJIT/LuaJIT/commit/dc320ca70f2c5bb3977b82853bcee6dad2523d01, which removes some defines, that are still present in Lua 5.1: https://www.lua.org/source/5.1/lauxlib.h.html (`luaL_getn`, `luaL_setn`, `luaL_reg` etc).

This means that code that compiles fine with Lua 5.1, fails with LuaJIT 2.1.

**Comment by MikePall** [comment]
@evgeni These are long deprecated symbols from  **Lua 5.0**. LuaJIT never claimed to be compatible to Lua 5.0.

You shouldn't have used them, if you're writing against Lua 5.1. And while you're at it, please clarify and close the related Debian bug report, too.

**Comment by evgeni** [comment]
@MikePall I completely agree that those are deprecated symbols (and I am about to remove the use of them in https://github.com/draios/sysdig/pull/921), but: these symbols are available in the latest Lua 5.1.z release, and my understanding is that LuaJIT tries to be Lua 5.1 compatible (that's how I read http://luajit.org/faq.html and http://luajit.org/extensions.html). And as such I would expect it to be able to compile software that compiles against Lua 5.1, regardless whether it is using deprecated (but available in 5.1.z) symbols or not. Or it should state that LuaJIT 2.1.x is to be considered Lua 5.2 and not 5.1 and then my expectation would vanish.

For Debian the 5.1 compat-expectation is even higher, as the binary packages actually have **5.1** in their name.

**Comment by vcunat** [comment]
I personally understand compatibility wrt. officially *documented* stuff, as in http://www.lua.org/manual/5.1/manual.html , not copying whatever properties the Lua 5.1.x *implementation* has.

**Comment by evgeni** [comment]
@vcunat but doesn't https://www.lua.org/manual/5.1/manual.html#7.3 actually define `luaL_getn` and `luaL_setn` as being deprecated, but still available and only removed in the next version of Lua?

**Comment by vcunat** [comment]
Oh, right, I should have checked that properly.

**Comment by fperrad** [comment]
@evgeni The C/API 5.1 is documented in chapter 3 & 4 of https://www.lua.org/manual/5.1/manual.html. The chapter 7 is the migration guide between 5.0 & 5.1. You could find `luaL_getn` & `luaL_setn` only in chapter 7.
