### ISSUE TITLE
Add ARM Thumb2 port

### ISSUE THREAD

**Issue by MikePall** [LuaJIT/LuaJIT#33]
This is relevant for the low-end Cortex-M CPUs that only support Thumb2 code. They simply can't run ARM32 machine code.

Even though mobile ARM CPUs are going the ARM64 route (which explicitly includes ARM32), the Cortex-M SoCs are not going away. Most of them have enough internal memory to run LuaJIT and they're quite popular due to their low cost.

This needs a DynASM Thumb2 port, a port of the interpreter and a new JIT compiler backend.

Beginnings of this can be found at: https://github.com/tcr/luajit
But this work has apparently been abandoned and never submitted upstream. It's interwoven with unrelated support code for their JS to Lua transpiler. It looks incomplete, too. It needs significant cleanup and/or rewriting.

**Comment by tcr** [comment]
All changes that are specific to adding Thumb support to LuaJIT are in the `tcr-thumb` branch. You can compare changes in this PR: https://github.com/tcr/luajit/pull/1

**Comment by jturnsek** [comment]
tcr-thumb branch Thumb support is full of bugs and still needs a lot of work. Thumb2 instruction set is quite complex, especially those IT instructions preceding conditional instructions and mixing of 16-bit instructions with 32 bit instructions.
It would be nice to have a decent Thumb2 port for those new Cortex M7 processors with a lot of RAM and double precision FPU.

**Comment by jturnsek** [comment]
FYI. Working Thumb support will be available after successful campaign of EdgePro1 on CrowdSupply. Currently we are in Prelaunch phase and LuaJIT is running on Nuttx RTOS.

**Comment by jturnsek** [comment]
https://www.hackster.io/jturnsek/hello-world-edgepro1-ef83f6

**Comment by MikePall** [comment]
Eight years later things have changed: recent CPUs with a useful amount of memory for running LuaJIT are now ARMv8.
There's only limited need for this port, anymore. Adventurous minds can explore the above patches. Closing here.
