### ISSUE TITLE
Add PowerPC 32-bit soft-float port

### ISSUE THREAD

**Issue by petar-jovanovic** [LuaJIT/LuaJIT#330]
The plan is that this should be done by RT-RK. I have created the issue as a placeholder only, to prevent someone else possibly start this and duplicate the work.

**Comment by vcunat** [comment]
@petar-jovanovic: does that mean there's some WIP on this?

**Comment by petar-jovanovic** [comment]
@vcunat Yes.

**Comment by petar-jovanovic** [comment]
Soft-float support has been added to interpreter. Committed in v2.1.

**Comment by gut** [comment]
Isn't it fixed by fd37da0d586c331b0008fbfd653a9659344fe76f ? Shouldn't this issue be closed now?

**Comment by petar-jovanovic** [comment]
> Isn't it fixed by fd37da0 ? Shouldn't this issue be closed now?

As said in the commit message and me earlier on, support for the interpreter was added.
JIT part still needs to be added and it will be available soon.

**Comment by MikePall** [comment]
Done.
