### ISSUE TITLE
LuaJIT 2.0.5 slow on android (Nexus 7)

### ISSUE THREAD

**Issue by codeservice** [LuaJIT/LuaJIT#331]
I compiled and tried library for ARMV5 and ARMV7 for android and have the same result - it slower then official lua 5.2 for me. 
Searched for solution and found few links:
http://luajit.freelists.narkive.com/MK64BXL6/android-performance-drop-moving-from-luajit-2-0-1-luajit-2-0-2
https://www.reddit.com/r/programming/comments/54e4xk/my_lovehate_relationship_with_luajit/

Looks like it wasn't an issue in version 2.0.1
Is it something what can be fixed in next versions?

**Comment by MikePall** [comment]
See #285
