### ISSUE TITLE
Could not "inline caching" be used in any table (not saying about metatables)?

### ISSUE THREAD

**Issue by hydroper** [LuaJIT/LuaJIT#334]
It is like my suggestion for https://github.com/luaj/luaj/issues/2 , where the "inline caching" optimization could be adapted to the fields of Lua tables. I find this important... because it is boring to do this multiple times in the code:

```lua
local longNameForAField = instance.longNameForAField;

--[=[
 * Use longNameForAField more than once
  ]=]
```

... just to avoid field lookuping. Also, this local solution cannot always be used. At least one field lookup needed for the local.

**Comment by daurnimator** [comment]
@hydroper what makes you think this optimization does not already exist?

**Comment by hydroper** [comment]
@daurnimator Does it? I didn't find much information on it.

**Comment by MikePall** [comment]
It does. Run some code with `-jdump` and study the generated code.
