### ISSUE TITLE
Add distinct feature defines for LJ_52

### ISSUE THREAD

**Issue by alkino** [LuaJIT/LuaJIT#337]
Hello,
We can only enable or disable all features with LJ_52. We need to pick only a specific one (*pairs*/*ipairs* meta-methods).
Do you think it's possible to add specific defines which will all be enabled with `LUAJIT_ENABLE_LUA52COMPAT`.

Maybe something like.
``` c
#ifdef LUAJIT_ENABLE_LUA52PAIRS
#  define LJ_52PAIRS
#endif

#ifdef LUAJIT_ENABLE_LUA52GOTO
#  define LJ_52GOTO
#endif

#ifdef LUAJIT_ENABLE_LUA52_COMPAT
#  define LJ_52PAIRS
#  define LJ_52GOTO
#  define LJ_52
#endif
```

What do you think about this idea?

Regards.

**Comment by MikePall** [comment]
Too much effort (to test all variants) for little gain.
