### ISSUE TITLE
debug.* memory reading/writing/running

### ISSUE THREAD

**Issue by meepdarknessmeep** [LuaJIT/LuaJIT#338]
setting the upvalue to ipairs_aux to the double representation of a uintptr_t will generate a GCfunc at that address allowing people to run whatever the code points at, read and write the fenv and more.

setting the upvalue of string_gmatch_aux to a double representation of a uintptr_t will allow you to call the auxiliary function and read memory also

**Comment by corsix** [comment]
The `debug` library should be considered just as dangerous as e.g. the `ffi` library - it is no surprise that it can be abused to execute arbitrary native code.

For what it's worth, provided that the JIT compiler part of LuaJIT is enabled, you can achieve arbitrary native code execution without having to use any libraries at all - see http://www.corsix.org/content/malicious-luajit-bytecode.
