### ISSUE TITLE
ffi.string incorrectly accepts non-integer as size

### ISSUE THREAD

**Issue by aaiyer** [LuaJIT/LuaJIT#339]
ffi.string(ffi.cast("char*", "A"), ffi.typeof("int"))

works in LuaJIT2.1-beta3

str = ffi.string(ffi.cast("char*", "A"), ffi.typeof("int"))
print(#str) -- has a size of 9

This is incorrect as only numbers should be accepted as a size for ffi.string

**Comment by bbxiong1999** [comment]
Use ffi.sizeof("int")

**Comment by aaiyer** [comment]
@bbxiong1999 Yea, I know that, but it should accept results from ffi.typeof() is what I mean.

**Comment by spacewander** [comment]
@aaiyer 
`ffi.typeof()` returns an integer as type id.

**Comment by Laaas** [comment]
Well shouldn't that be the issue then? It should probably have a distinct userdata type.
