### ISSUE TITLE
loadstring crash in OSX

### ISSUE THREAD

**Issue by hyee** [LuaJIT/LuaJIT#343]
Hello,

I recently downloaded the newest version 2.1 and compile in my OSX 10.12, and then I got below error message, my expectation is even there is Lua grammar issue, the application should not crash. The Makefile is unchanged, and gcc version is 4.9.4, may I know how can I fix this issue? I'm not familiar with gcc and C. Thanks a lot.

```
LuaJIT 2.1.0-beta3 -- Copyright (C) 2005-2017 Mike Pall. http://luajit.org/
JIT: ON SSE2 SSE3 SSE4.1 BMI2 fold cse dce fwd dse narrow loop abc sink fuse
> loadstring 'return /2'
PANIC: unprotected error in call to Lua API ([string "return /2"]:1: unexpected symbol near '/')
```

**Comment by kusinza** [comment]
Send me the complete file so I can check the function

**Comment by hyee** [comment]
Sorry for late response, I managed to fix my issue by changing `DEFAULT_CC` as `clang`. with gcc 4.9.4 the issue is still there. I would close this ticket, and also attached the problematic luajit binary for your reference. Thanks.
[luajit.zip](https://github.com/LuaJIT/LuaJIT/files/1203053/luajit.zip)
