### ISSUE TITLE
Another Lua 5.3 support issue..

### ISSUE THREAD

**Issue by haikarainen** [LuaJIT/LuaJIT#345]
I will try to keep this short, and not argue about the politics on why you should/shouldn't support 5.3 etc.

I value 5.3 support a lot, and I'm curious as to the possibilities on getting it working with LuaJIT.  Are you set in stone on never *ever* supporting it, or do you simply dislike it and therefore not prioritize it?

I understand that this is an open-source project, and that you don't owe us anything. I also appreciate your very hard work.  If you _are_ set in stone on never *ever* supporting it, I'm curious about the sum of money that would be required to change your opinion (not that I'm filthy rich or anything, just really want to make it happen).

Cheers! 💯

**Comment by mirageglobe** [comment]
Seems like money is not an issue. Time is.

Ref: - https://news.ycombinator.com/item?id=12573981

Quote from mikemike (assuming this is himself):
"This is a wrong perception. There is/was no shortage of sponsorships. I had to turn down most of these offers, due to time constraints."

**Comment by gantleman** [comment]
Maintaining multiple version branches is really too difficult for independent developers
