### ISSUE TITLE
some issues in .dasc file

### ISSUE THREAD

**Issue by MichoChan** [LuaJIT/LuaJIT#346]
`  |->vm_call_dispatch:

  |  mov LFUNC:RB, [RA-16]

  |  checkfunc LFUNC:RB, ->vmeta_call	// Ensure KBASE defined and != BASE.`

here, [RA-16] may be TFUNC?

if so, it's better to replace LFUNC:RB with TFUNC (and add |.type TFUNC,  GCfunc) ?

**Comment by MikePall** [comment]
That's a minor detail. I wouldn't bother with this.
