### ISSUE TITLE
Dereferencing double* cdata results in userdata

### ISSUE THREAD

**Issue by aaiyer** [LuaJIT/LuaJIT#348]
Having the following c code compiled into a shared library
```
#include <stdlib.h>
#include <math.h>
#include <stdint.h>
double* mk() {
        double* r = malloc(sizeof(double));
        *((uint64_t*)r) = 18446468139240592383U;
        return r;
}
```
Then being used via ffi in the following manner
```
ffi = require("ffi")
ffi.cdef[[
double* mk();
]]
lib = ffi.load("./a.so")
print(lib.mk()[0])
```
results in the double* being **dereferenced** into a userdata, as seen in the following output of the lua program
```
userdata: 0x0509ffff13ff
```

When luajit is compiled with -DLUA_USE_ASSERT results in the follow assertion failure
```
lj_cconv.c:392: lj_cconv_tv_ct: Assertion `(((o)->it) < 0xfffeffffu)' failed.
```

**Comment by corsix** [comment]
Don't combine non-canonical NaNs and FFI `double`s. See https://www.freelists.org/post/luajit/fficast-weird-behaviour,1 and https://www.freelists.org/post/luajit/fficast-weird-behaviour,6.
