### ISSUE TITLE
SoniEx2 nonsense (was __tostring/tostring/print doesn't work)

### ISSUE THREAD

**Issue by SoniEx2** [LuaJIT/LuaJIT#351]
http://www.lua.org/manual/5.1/manual.html#pdf-print

> Receives any number of arguments, and prints their values to stdout, **using the tostring function to convert them to strings**. print is not intended for formatted output, but only as a quick way to show a value, typically for debugging. For formatted output, use string.format. 

http://www.lua.org/manual/5.1/manual.html#pdf-tostring

> Receives an argument of any type and converts it to a string in a reasonable format. For complete control of how numbers are converted, use string.format.
> 
> **If the metatable of e has a "__tostring" field, then tostring calls the corresponding value with e as argument, and uses the result of the call as its result.**

```
$ luajit
LuaJIT 2.0.5 -- Copyright (C) 2005-2017 Mike Pall. http://luajit.org/
JIT: ON CMOV SSE2 SSE3 SSE4.1 fold cse dce fwd dse narrow loop abc sink fuse
> getmetatable("").__tostring=function(v)return'+'..v end
> print("")

> 
$ lua5.1
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
> getmetatable("").__tostring=function(v)return'+'..v end
> print("")
+
> 
```

**Comment by SoniEx2** [comment]
Please fix every API incompatibility with Lua 5.1.

**Comment by corsix** [comment]
The API compatibility ship sailed a long time ago. `__tostring` on strings is too esoteric to be worth matching 5.1 on.

**Comment by SoniEx2** [comment]
some ppl use __tostring on strings as an alias to string.format("%q", str).

**Comment by corsix** [comment]
Well, good luck with that. You can monkey-patch `tostring` to support such silliness if you really need it.

**Comment by daurnimator** [comment]
As silly as this is (and I truly wonder how @SoniEx2 found it...), it *would* be nice if LuaJIT didn't diverge from PUC-Rio lua for things like this: I feel like it would be minimal work and impact to support this.

For what it's worth, I checked, and Lua 5.2 and 5.3 have the same behaviour here.
It's even [documented behaviour of `luaL_tolstring`](http://www.lua.org/manual/5.3/manual.html#luaL_tolstring):
> If the value has a metatable with a __tostring field, then luaL_tolstring calls the corresponding metamethod with the value as argument, and uses the result of the call as its result.

**Comment by corsix** [comment]
It would not be minimal work.

**Comment by SoniEx2** [comment]
It would be as minimal as Ctrl+X followed by Ctrl+V, i.e. reordering some code.

Also, I found it through someone else, who couldn't get their code to work in LuaJIT because of this.

**Comment by daurnimator** [comment]
> It would be as minimal as Ctrl+X followed by Ctrl+V, i.e. reordering some code.

What makes you think that?

I didn't look too hard, but the main things I noticed were https://github.com/LuaJIT/LuaJIT/blob/b93a1dd0c831cab22f98163d0dde792a493c0eef/src/lib_string.c#L807 and https://github.com/LuaJIT/LuaJIT/blob/b93a1dd0c831cab22f98163d0dde792a493c0eef/src/lj_ffrecord.c#L337

**Comment by corsix** [comment]
You also need to look at the asm code for every arch, as the fast path of `tostring` is done there (and, obviously, the fast path is where inputs of type string are handled). Unlike for numbers, it can't just bail out if there is a string metatable set, as there is almost always a string metatable set.

**Comment by SoniEx2** [comment]
Oh good more issues.

```
$ luajit
LuaJIT 2.0.5 -- Copyright (C) 2005-2017 Mike Pall. http://luajit.org/
JIT: ON CMOV SSE2 SSE3 SSE4.1 fold cse dce fwd dse narrow loop abc sink fuse
> debug.setmetatable(0, {__tostring=function(v) return "v"..v end})
> print(0)
0
> print(tostring(0))
v0
> 
$ lua5.1
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
> debug.setmetatable(0, {__tostring=function(v) return "v"..v end})
> print(0)
v0
> print(tostring(0))
v0
> 
```
```

**Comment by corsix** [comment]
That one I'd consider legitimate - `print` needs an extra constraint on whether it can take its shortcut:
```diff
diff --git a/src/lib_base.c b/src/lib_base.c
index 6107bde..0c63975 100644
--- a/src/lib_base.c
+++ b/src/lib_base.c
@@ -492,7 +492,8 @@ LJLIB_CF(print)
     lua_gettable(L, LUA_GLOBALSINDEX);
     tv = L->top-1;
   }
-  shortcut = (tvisfunc(tv) && funcV(tv)->c.ffid == FF_tostring);
+  shortcut = (tvisfunc(tv) && funcV(tv)->c.ffid == FF_tostring)
+              && !gcrefu(basemt_it(G(L), LJ_TNUMX));
   for (i = 0; i < nargs; i++) {
     cTValue *o = &L->base[i];
     const char *str;
```
