### ISSUE TITLE
JIT crash on arm64

### ISSUE THREAD

**Issue by jteplitz** [LuaJIT/LuaJIT#357]
The JIT segfaults on arm64 starting from 1131fa22a23c6284ba5945bffb3dcd6deef2076e (the original arm64 JIT compiler backend commit) on the following test case.

```lua
local Queue = {}
-- Turning off the jit here fixes the segfault
--jit.off(true, false)

function Queue:new()
  local o = {first = 0, last = -1}
  setmetatable(o, self)
  self.__index = self
  return o
end

function Queue:enqueueFront(elem)
  self.first = self.first - 1
  self[self.first] = elem
end

function Queue:dequeueFront()
  if self.first > self.last then
    error("Attempt to dequeue from an empty queue")
  end
  local val = self[self.first]
  self[self.first] = nil
  self.first = self.first + 1
  return val
end

local NUM_TIMES = 10^6

function main()
  local queue = Queue:new()

  for i = NUM_TIMES, 1, -1 do
    queue:enqueueFront(i)
  end

  for i = 1, NUM_TIMES do
    assert(queue:dequeueFront() == i)
  end

end
main()
```

This code appears to work fine before 1131fa22a23c6284ba5945bffb3dcd6deef2076e and always works on x86_64 for me.

**Comment by sindrom91** [comment]
It's a register allocation issue in asm_hrefk (dest and key had the same register). This makes it go away for me:

`diff --git a/src/lj_asm_arm64.h b/src/lj_asm_arm64.h
index 8fd92e7..540d0f5 100644
--- a/src/lj_asm_arm64.h
+++ b/src/lj_asm_arm64.h
@@ -871,7 +871,7 @@ static void asm_hrefk(ASMState *as, IRIns *ir)
   int bigofs = !emit_checkofs(A64I_LDRx, ofs);
   RegSet allow = RSET_GPR;
   Reg dest = (ra_used(ir) || bigofs) ? ra_dest(as, ir, RSET_GPR) : RID_NONE;
-  Reg node = ra_alloc1(as, ir->op1, allow);
+  Reg node = ra_alloc1(as, ir->op1, rset_clear(allow, dest));
   Reg key = ra_scratch(as, rset_clear(allow, node));
   Reg idx = node;
   uint64_t k;
@@ -879,7 +879,6 @@ static void asm_hrefk(ASMState *as, IRIns *ir)
   rset_clear(allow, key);
   if (bigofs) {
     idx = dest;
-    rset_clear(allow, dest);
     kofs = (int32_t)offsetof(Node, key);
   } else if (ra_hasreg(dest)) {
     emit_opk(as, A64I_ADDx, dest, node, ofs, allow);`

**Comment by jteplitz** [comment]
That diff fixes the problem for me. Thanks @sindrom91! I submitted a PR for your change.

**Comment by MikePall** [comment]
I've committed a different fix.
