### ISSUE TITLE
Can't build for Android under Linux on Windows (WSL)

### ISSUE THREAD

**Issue by bahusoid** [LuaJIT/LuaJIT#360]
Trying to build with the following command (based on this [instruction](http://luajit.org/install.html#cross)):
`make HOST_CC="gcc -m32" CROSS=/mnt/c/Git/toolchain/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi- TARGET_FLAGS="--sysroot /mnt/c/Git/toolchain/android-ndk-r15c/platforms/android-14/arch-arm -march=armv7-a -mfloat-abi=softfp -Wl,--fix-cortex-a8"`

And it gives the following error:
```
==== Building LuaJIT 2.1.0-beta3 ====
make -C src
make[1]: Entering directory '/mnt/c/Git/luajit/LuaJIT-2.1.0-beta3/src'
DYNASM    host/buildvm_arch.h
host/minilua: 1: host/minilua: Syntax error: word unexpected (expecting ")")
Makefile:635: recipe for target 'host/buildvm_arch.h' failed
make[1]: *** [host/buildvm_arch.h] Error 2
make[1]: Leaving directory '/mnt/c/Git/luajit/LuaJIT-2.1.0-beta3/src'
Makefile:112: recipe for target 'default' failed
make: *** [default] Error 2
```
Linux version: Linux 4.4.0-43-Microsoft x86_64

Any ideas what might be wrong?

**Comment by henriquegemignani** [comment]
I stumbled into this problem earlier and this was my conclusion, correct me if I'm wrong:

When building for a 32-bit target, such as Android armv7, you must build a 32-bit binary to run in the host machine as part of the build process. However, WSL can only run 64-bit linux binaries so the process fails.

**Comment by bahusoid** [comment]
Indeed. Thanks for clarification. I see the same error discussed here:
https://github.com/Microsoft/BashOnWindows/issues/228

And user voice to support 32-bit binary in WSL is here:
https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13377507-please-add-32-bit-elf-support-to-the-kernel

**Comment by MikePall** [comment]
Host and target must be either both 32 bit or both 64 bit for cross-builds. This requirement is not something that can be changed easily.
