### ISSUE TITLE
loadstring(a lua file with error syntax) will terminate my app.

### ISSUE THREAD

**Issue by guijun** [LuaJIT/LuaJIT#368]
I'm newbie using luajit.
OS: macosx
xcode: 9
compiler: clang and gcc
luajit 2.1.0-beta3

My app will crash if I call loadstring("error(ssdsf")
My app won't crash if I call loadstring("io.write(\"Hello world\")");
try{
loadstring(...)
}
catch(...)
{

};
doesn't work .

Could you please let me know how to catch and print the error? and, My app shouldn't crash ~

thanks for help.

**Comment by guijun** [comment]
I removed exit call at lj_err.c:537.
Now, loadstring will not crash my app.
syntax error is printed.
error_handler is called.

I'm wondering if it's the right way.

**Comment by MikePall** [comment]
Use `lua_pcall` to call into Lua from C. And/or use `lua_atpanic`.
