### ISSUE TITLE
Arrow key binding when running interactive

### ISSUE THREAD

**Issue by pp611** [LuaJIT/LuaJIT#369]
When running luajit interactively, hit up arrow key results a string "^[[A" while lua's interactively shell results the previous line. 

Is there any setting to make it behave the same like lua?

**Comment by daurnimator** [comment]
On 29 November 2017 at 12:33, Yi Zhao <notifications@github.com> wrote:
> When running luajit interactively, hit up arrow key results a string "^[[A" while lua's interactively shell results the previous line.
>
> Is there any setting to make it behave the same like lua?

It's common to run luajit under `rlwrap` to get readline keyboard bindings.

**Comment by pp611** [comment]
Many thanks, works great

**Comment by alains-trend** [comment]
I just tried the following in the documentation and it worked like a charm

> If you're running Linux, try "make linux-readline" to build the interactive Lua interpreter with handy line-editing and history capabilities.

http://www.lua.org/manual/5.4/readme.html

**Comment by daurnimator** [comment]
@alains-trend this repository is for LuaJIT; your comment is regarding PUC-Rio Lua.
