### ISSUE TITLE
Add Hyperblock Scheduling

### ISSUE THREAD

**Issue by MikePall** [LuaJIT/LuaJIT#37]
Producing good code for unbiased branches is a key problem for trace compilers. This is the main cause for "trace explosion" and bad performance with certain types of branchy code.

Hyperblock scheduling promises to solve this nicely at the price of a major redesign of the compiler: selected traces are woven together to a single hyper-trace. This would also pave the way for emitting predicated instructions, which benefits some CPUs (e.g. ARM) and is a prerequisite for efficient vectorization.

Be warned: this is heavy stuff! Something for a thesis, not for an afternoon.

Probably needs a major reorganization of the compiler. Requires an (adjunct) predicated IR. Selecting a profitable region for this optimization is the first hurdle. The merge phase for the predicated IR is tough.

Ask me, if you need a motivating example of how a predicated IR would look like and what this would enable. But don't hold your breath, this requires a long explanation.

**Comment by fsfod** [comment]
Do you think comparing IR chains backward based on snapshot slots between traces and using snapshot pc location/IR ref would be a reasonable way find and extract divergent IR. You would still have islands IR in-between which would either be dead code or have side effects to deal with though.
I assume a IR chain differing only by a constant would be a easy case for predicted IR.

**Comment by MikePall** [comment]
I looked into diff algorithms for inspiration. But the key problem is not finding a minimal diff. Handling all the edge cases is tricky.

First, I guess we can agree that an N-way trace merge can be done with N x 2-way merges.

Here's a 4 phase algorithm for merging two traces A and B:
1. Find a common suffix: Use common snapshots as starting points. Backpropagate each slot from both traces. Find the last common instruction and mark it (those will be the PSIs). Stores add some complications (duplicating them may be a better approach).
2. Emit a common prefix: Start a new hypertrace with an empty IR. Emit IR from parent trace until the 1st split (no CSE needed).
3. Emit non-common code: Emit code for each trace until the marked PSIs. CSE gets in the way here, maybe rollback to common point when CSE of B points into A. That would be more like an alternation between phase 2 and 3.
4. Emit common suffix: Emit all PSIs. Emit not-yet emitted code from either trace with PSI substitutions (beware of control-flow dependencies). One should mix already complete PSIs between phase 3 to phase 2 transitions. Also, emit already complete code following PSIs.

The register allocator could do register coalescing for split paths, in case they cannot be joined with a branch-free idiom.

**Comment by MikePall** [comment]
Bibliography:

Francois de Ferriere: Improvements to the Psi-SSA representation, 2007

Dirk Tetzlaff: Erweitertes Hyperblock-Scheduling für VLIW-Prozessoren, Diplomarbeit, Technische Universität Berlin, Fachgebiet Programmierung eingebetteter Systeme, Oktober 2007

Youfeng Wu und James R. Larus: Static Branch Frequency and Program Profile Analysis, In: MICRO 27, ACM Press, S. 1–11, 1994

S. A. Mahlke, D. C. Lin, W. Y. Chen, R. E. Hank und R. A. Bringmann: Effective Compiler Support for Predicated Execution Using the Hyperblock, In: MICRO 25, IEEE Computer Society Press, S. 45–54, 1992

**Comment by mraleph** [comment]
Any suggestions of how one could obtain "Erweitertes Hyperblock-Scheduling für VLIW-Prozessoren"? Unlike other papers in the list this one does not seem to be available online in any form.

**Comment by Mischanix** [comment]
There are physical copies of the conference papers available in German libraries:
- <https://portal.dnb.de/opac.htm?method=simpleSearch&query=987900129>

Searching for the ISBN yields some other possibilities for obtaining a physical copy.  No signs of a digital version, however.

**Comment by hishamhm** [comment]
I'd venture that the easiest way for an interested reader to access the document (or any related publications) would be to contact [Dirk Tetzlaff](http://www.tu-berlin.de/?id=tetzlaff) himself.

**Comment by Mischanix** [comment]
I am in the process of obtaining a digital copy of the paper.  It should be available tomorrow.

**Comment by MikePall** [comment]
https://mega.nz/#!p9t13QQY!k1GshGIsZzutn6OoAVGc_Az3O2OGghCJZwFBf67Tatg

Apologies for the Mega Link. Remember to click on "download with browser". I guess it should find a better home.

BTW: It's in German, but half of the words are in English, anyway. Still worth a try, even if you can't understand German.

**Comment by Mischanix** [comment]
Thank you!  That PDF is longer than I would expect pages 111-114 to contain, so perhaps the conference proceedings wouldn't have been fruitful anyway.

Here is a github-hosted link for those who don't wish to spend cycles doing javascript crypto:

<https://gist.github.com/Mischanix/8a262a891b550d55d509/raw/e25064b706c4c94582f420d973d4e4509f378db8/da07oct-tetzlaff-hyperblock.pdf>

**Comment by lukego** [comment]
I am becoming interested in a related problem: How about if a branch is heavily biased but the bias changes over time?

This seems to be a problematic case for Snabb applications recently. Specifically, the workload changes and performance degrades and a `jit.flush()` is required to recover performance. It would be wonderful if the JIT could detect this situation much more quickly and adapt the traces before application behavior is impacted.

Is this perhaps a simpler problem that could be solved within the current framework? (For example, might one detect when a branch becomes biased towards a side-trace rather than the root trace and then re-record? In my own naive mental model this seems similar to how CPU branch prediction works.)

**Comment by DemiMarie** [comment]
I just had a thought: Would some Ph. D. student somewhere be interested in doing this as their thesis?  Perhaps in Germany?

**Comment by DemiMarie** [comment]
@lukego I think that the answer is yes, albeit at a performance overhead during normal operation (need to add instrumentation to each branch).

I have been wondering "Just why is this so hard?"  Diff algorithms are ubiquitous – I wrote a stripped-down `diff` as a class project in undergraduate CS.  They might not do an _optimal_ job for this case, but they should do better than nothing, and @MikePall has already stated that he knows roughly how a predicated IR would look like.  It seems that the biggest hurdle is the assumptions in the existing codebase.

**Comment by DemiMarie** [comment]
I'll bite: @MikePall, what would a predicated IR look like?

**Comment by nico-abram** [comment]
Has any work related to this been done since 2016?

**Comment by MikePall** [comment]
This is unlikely to happen within the context of LuaJIT. But maybe some other language. Maybe.

**Comment by DemiMarie** [comment]
> This is unlikely to happen within the context of LuaJIT. But maybe some other language. Maybe.

Is this because of time constraints, or because Lua makes it hard?
