### ISSUE TITLE
missing `str_fastcmp` suppresion record in lj.supp

### ISSUE THREAD

**Issue by pspacek** [LuaJIT/LuaJIT#370]
I believe that `lj.supp` is missing following record:

```
{
   Optimized string compare
   Memcheck:Addr4
   fun:lj_getu32
   fun:str_fastcmp
}
```

Existing records contain only `fun:str_fastcmp` but the comment `/* Note: innocuous access up to end of string + 3. */` is right above call to `lj_getu32` function.

**Comment by neoxic** [comment]
I see the same issue with the default `lj.supp` loaded:
```
==1096== Invalid read of size 4
==1096==    at 0x49364AA: lj_getu32 (lj_def.h:235)
==1096==    by 0x49364AA: str_fastcmp (lj_str.c:53)
==1096==    by 0x49364AA: lj_str_new (lj_str.c:127)
==1096==    by 0x4942A7B: lua_pushlstring (lj_api.c:587)
...
```
