### ISSUE TITLE
Warning: corrupt .drectve at end of def file

### ISSUE THREAD

**Issue by zhaozg** [LuaJIT/LuaJIT#372]
luajit build with msys-mingw32

Env
---
```shell
$ deps/luv/luajit.exe -v
LuaJIT 2.0.5 -- Copyright (C) 2005-2017 Mike Pall. http://luajit.org/
$ gcc -v                                                                                                                                
Using built-in specs.                                                                                                                   
COLLECT_GCC=E:\msys64\mingw32\bin\gcc.exe                                                                                               
COLLECT_LTO_WRAPPER=E:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.2.0/lto-wrapper.exe                                             
Target: i686-w64-mingw32                                                                                                                
Configured with: ../gcc-7.2.0/configure --prefix=/mingw32 --with-local-prefix=/mingw32/local --build=i686-w64-mingw32 --host=i686-w64-mi
ngw32 --target=i686-w64-mingw32 --with-native-system-header-dir=/mingw32/i686-w64-mingw32/include --libexecdir=/mingw32/lib --enable-boo
tstrap --with-arch=i686 --with-tune=generic --enable-languages=c,lto,c++,objc,obj-c++,fortran,ada --enable-shared --enable-static --enab
le-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-time=yes --disable-libstdcxx-pch 
--disable-libstdcxx-debug --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disab
le-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw3
2 --with-mpfr=/mingw32 --with-mpc=/mingw32 --with-isl=/mingw32 --with-pkgversion='Rev1, Built by MSYS2 project' --with-bugurl=https://so
urceforge.net/projects/msys2 --with-gnu-as --with-gnu-ld --disable-sjlj-exceptions --with-dwarf2                                        
Thread model: posix                                                                                                                     
gcc version 7.2.0 (Rev1, Built by MSYS2 project)          
```

Step
---
$ cat a.lua
```lua
print "A"
```                                                                              
$ deps/luv/luajit.exe -b a.lua a.obj
$ gcc a.obj -shared
Warning: corrupt .drectve at end of def file

Result
---
mingw32-gcc or ming64-gcc fail to embed dumped code to binary.
but msvc or gcc on linux work fine.

**Comment by MikePall** [comment]
Well, it's a warning only. I don't know why mingw-gcc complains. The embedded `.drectve` (`/EXPORT:symbol,DATA`) looks fine and is actually required for proper MSVC linking.

**Comment by zhaozg** [comment]
I do some dig, and found msvc and mingw-gcc with diff format for export function.
https://github.com/LuaJIT/LuaJIT/blob/046129dbdda5261c1b17469a2895a113d14c070a/src/jit/bcsave.lua#L345
only works for msvc.
when change this line to `local symexport = "   -export:"..symname:sub(2,-1) only works for mingw gcc

**Comment by zhaozg** [comment]
Accroding to https://msdn.microsoft.com/library/windows/desktop/ms680547(v=vs.85).aspx
`
A section is a directive section if it has the IMAGE_SCN_LNK_INFO flag set in the section header and has the .drectve section name. The linker removes a .drectve section after processing the information, so the section does not appear in the image file that is being linked.

A .drectve section consists of a string of text that can be encoded as ANSI or UTF-8. If the UTF-8 byte order marker (BOM, a three-byte prefix that consists of 0xEF, 0xBB, and 0xBF) is not present, the directive string is interpreted as ANSI. The directive string is a series of linker options that are separated by spaces. Each option contains a hyphen, the option name, and any appropriate attribute. If an option contains spaces, the option must be enclosed in quotes. The .drectve section must not have relocations or line numbers.
`
So directive section is related with you compile chains, We need not over concern about It.
And Finally I prefer to  save bytecode to .C source file, exported bytecode data for more portable reasons..
