### ISSUE TITLE
"__eq" support

### ISSUE THREAD

**Issue by codeservice** [LuaJIT/LuaJIT#379]
I am trying make custom __eq metamethod for my userdata objects

tried this: 
                lua_pushcfunction(l, my_lua_equal);
    		lua_setfield(l, -2, "__eq");
and second option:
                lua_pushstring(l, "__eq");
                lua_pushcclosure(l, my_lua_equal, 0);
                lua_rawset(l, -3);

Non of above works. Lua 5.2 no problems.

For the same userdata objects I already have "__index" and "__newindex", works on both JIT and lua 5.2 versions

**Comment by MikePall** [comment]
There are subtle semantic differences in metamethod handling between 5.1 and 5.2 modes. LuaJIT just follows these. Check the Lua documentation and/or source code.
