### ISSUE TITLE
Length of int64

### ISSUE THREAD

**Issue by MageSlayer** [LuaJIT/LuaJIT#386]
Hi
Doing obviously stupid thing (but happens during refactoring) results in a crash.
... when compiled with asserts.
```
$ luajit -e "print(#1LL)"
luajit: lj_carith.c:211: carith_int64: Assertion `0' failed.
Aborted
```
Tested under latest git revision, Linux GC64 build.

**Comment by MikePall** [comment]
Fixed. Thanks!
