### ISSUE TITLE
lua callbacks in C structs

### ISSUE THREAD

**Issue by vcunat** [LuaJIT/LuaJIT#389]
Possibly a bug, or point me to some explanation/resources, please.

I tried to assign a lua function (also explicitly cast) into a FFI-bound C struct member, but it won't work.  Luajit printed the value of the field after assignment as a cdata function pointer, but in C it was still be seen as NULL (!).  No error gets reported at all; I also tried with `jit.off()`.  Did I miss some warning in the _Callbacks_ section of http://luajit.org/ext_ffi_semantics.html ?

I worked around this by creating a trivial C function to do this assignment, and that seems to work fine, but I wonder if I'm seriously misunderstanding something.  I used luajit-2.0.5 on x86_64 linux, though other (recent) versions+platforms also interest me if they differ.

**Comment by Hydroque** [comment]
Is this issue present in the beta master?

**Comment by MikePall** [comment]
Storing a function pointers in a struct is how many callback-oriented C APIs work. It would be very surprising if that didn't work. Please provide a complete, isolated test case.

**Comment by vcunat** [comment]
2.1.0-beta3 gives me the same.

**Comment by vcunat** [comment]
I'm sorry, I was being an idiot.  In all the complexity I missed a mistake in the lua bindings for the structures, so luajit was reading (and writing) at a different location than c.

**Comment by vcunat** [comment]
Thanks for LuaJIT, BTW.
