### ISSUE TITLE
[dynasm] Potential mov64 issue  in dasm_x86.lua 

### ISSUE THREAD

**Issue by dibyendumajumdar** [LuaJIT/LuaJIT#390]
Hi,

While building luaffifb (https://github.com/facebookarchive/luaffifb) on Windows 10 using MSVC, and using latest dynasm from 2.1 branch, I came across some compiler errors when C pointer variable is an operand of mov64. It seems that the luaffifb project has applied a workaround as follows in dasm_x86.lua in the commit below:

https://github.com/jmckaskill/luaffi/commit/9f6cdfac79226da864b965f035b94d71ccd65b8d#diff-7a28d94a3a900709756a9bfeac69eccd

The relevant lines are:

```
-waction("IMM_D", format("(unsigned int)(%s)", op64))
-waction("IMM_D", format("(unsigned int)((%s)>>32)", op64))
+waction("IMM_D", format("(unsigned int)((uintptr_t)(%s))", op64))
+waction("IMM_D", format("(unsigned int)(((uintptr_t)(%s))>>32)", op64))
```

These impact lines such as:

```
    // hardcode the lua_State* value into the assembly
    | mov64 L_ARG, L
```

I don't know whether this is incorrect usage of mov64, or a code generation issue in dynasm. In any case the error does occur when compiling lines like above in MSVC which doesn't seem to be happy about applying a shift operator (>>) to a pointer variable.

**Comment by MikePall** [comment]
DynASM expects integers as immediate operands. If you want to use other types, then add the cast yourself.
