### ISSUE TITLE
Minimal memory requirements

### ISSUE THREAD

**Issue by lyssdod** [LuaJIT/LuaJIT#391]
Hi,

Can somebody give an advice on minimal memory requirements of LuaJIT? Can I use it in embedded environments (<8MBs of RAM), for example? Thanks!

**Comment by MikePall** [comment]
The code itself  is a couple hundred kilobytes, depending on the ISA code density. You can strip out some parts you don't need.

Technically, LuaJIT could do with 50-something kilobytes data at runtime. But a) Lua is a garbage-collected language, b) the JIT compiler needs some working space and c) you probably want to do something useful in your code. So I guess 300 kilobytes of data would be a realistic minimum.
