### ISSUE TITLE
Required steps for a new port?

### ISSUE THREAD

**Issue by lyssdod** [LuaJIT/LuaJIT#392]
Hi all,

What are required steps to add a new architecture? As far as I can see, they are:

1. Implement `lj_asm_<arch>.h`;
2. Implement `lj_emit_<arch>.h`;
3. Implement `lj_target_<arch>.h`;
4. Implement `vm_<arch>.dasc`;
5. Setup `#ifdefs` for the above;
6. Implement `jit/dis_<arch>.lua`;
7. Implement `dynasm/dasm_<arch>.lua`;
8. Implement `dynasm/dasm_<arch>.h`;

Am I missing something? Is there any doc besides bytecode and IR format? Thank you!

**Comment by swalk-cavium** [comment]
@lyssdod - Don't forget to check the branches to make sure the port hasn't already been
done.  ARMv8 is on v2.1 for example.

**Comment by sindrom91** [comment]
There are a lot more places that need some changes. On the top of my head: `lj_arch.h`, `lj_frame.h`, `lj_ccall.c`, `lj_ccallback.c`.

**Comment by preetikhorjuvenkar** [comment]
@swalk-cavium Can I raise a PR to port to the v2.1 branch instead of the master ?

**Comment by sindrom91** [comment]
You can and you probably should.

**Comment by petar-jovanovic** [comment]
@lyssdod What port do you plan to write?
Rename this issue accordingly, so other people are aware of it.

**Comment by petar-jovanovic** [comment]
@lyssdod how is it going? You probably should open a separate ticket to log your progress on m68k work.

**Comment by MikePall** [comment]
Please note that m68k is only of historic interest. Such an architecture won't be merged. You can develop it outside of this repo, of course. Closing here.

**Comment by lyssdod** [comment]
@MikePall but why?

**Comment by javierguerragiraldez** [comment]
If you start writing it, I'll star it.  hopefully contribute too, but it has been a long time since i had a M68k
