### ISSUE TITLE
Pattern matching can exhibit exponential run-time behaviour

### ISSUE THREAD

**Issue by cloudspeech** [LuaJIT/LuaJIT#396]
Run this line in LuaJIT:

`local x = ('a'):rep(1000); print(x:match(('a.*'):rep(10)..'b')`

EXPECTED: it terminates quickly.
OBSERVED: it takes forever at 100% CPU.

Since LuaJIT is overall extremely fast, the regexp engine should be rewritten to avoid exponential blowup like in the above example. 

See https://swtch.com/~rsc/regexp/regexp1.html for advice on how to implement it.

**Comment by MikePall** [comment]
[Lua's pattern engine is known](http://lua-users.org/lists/lua-l/2011-02/msg01595.html) to not prevent pathological cases. This is the same engine that LuaJIT uses. OTOH a gazillion of other functions can make your process hang.

In other words: if it hurts, don't do it. If you have untrusted input, then don't use it as a pattern. If you have untrusted code, then you need process sandboxing, anyway (for many other reasons).

Rewriting the pattern engine to not exhibit pathological cases is a) hard to implement, b) even harder to make performant and memory-efficient and c) not a priority. Please open a new issue, when you're done, including convincing benchmarks on real-world cases (and not just pathological cases).
