### ISSUE TITLE
Crash with 'frame is nullptr', LuaJit 2.1.0-beta2

### ISSUE THREAD

**Issue by Nathan1852** [LuaJIT/LuaJIT#398]
Luajit crashed on Windows 10 x64 when calling a C function from sciter through the ffi with a callback
I'm using luajit 2.1.0-beta2.
I also tried it on Windows 7, and the same problem emerged.

When debugging it crashed [here](https://github.com/LuaJIT/LuaJIT/blob/master/src/lj_ccall.c#L879) with 'frame is nullptr'

The same call worked fine on Ubuntu 16.04.

I could reproduce it with this code every time: [luajit_crash.zip](https://github.com/LuaJIT/LuaJIT/files/1747248/luajit_crash.zip) Just call 'luajit init.lua'
It crashes in the last line in init.lua ( sciter.SciterSetupDebugOutput )

**Comment by MikePall** [comment]
The link to the source is to master and not to 2.1. And you haven't explained where that error message comes from (your debugger?).

Anyway, nobody is going to run or even take a look at 18 Megabytes of untrusted binary code on Windows. That's also not helpful to find the problem.

Try to reduce the Lua code to a minimal reproducible example, then reduce the C code. A dozen lines should suffice, to demonstrate the problem.

(That is, if it's really in LuaJIT and not in your FFI declarations.)

**Comment by Nathan1852** [comment]
The error message comes from Visual Studio, attached to luajit.
The binary is the unmodified sciter dll from sciter.com, which I try to wrap with the ffi.

I'll try to create a smaller reproducible variant of the lua code, but I can't change anything in the C code.
