### ISSUE TITLE
OSX default compiler

### ISSUE THREAD

**Issue by MikePall** [LuaJIT/LuaJIT#4]
The Makefile relies on GCC and a few GCC-specific features (like -fpmath=sse).

We can probably safely switch to Clang on OSX by default. However, this needs some restructuring to avoid burying the compiler override in the OS selection jungle further down src/Makefile.

**Comment by corsix** [comment]
At least on my OSX install, Clang is the only C/C++ compiler present, and `gcc`/`g++` are synonyms for `clang`. I presume that this is the default state of affairs, as I've not done anything special beyond installing XCode / developer tools. In such an environment, LuaJIT seems to build fine.

**Comment by mraleph** [comment]
Recent clang actually supports `-fpmath=sse`[1]. Though it's meaning is completely different from GCC one - they just check that SSE level permitted by `-msseX` matches `-fpmath`. Old versions of clang used to complain "Argument unused during compilation: '-mfpmath=sse'" - but it was just a warning.

As @corsix notes: XCode also comes with `/use/bin/gcc` which is essentially `clang`. I assume for portability and backward compatibility reasons - though I can't find anything in XCode Release Notes about this. 

```
$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
 $ clang -v
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

I think as long as we are only targeting modern enough clang we can just leave `Makefile` as is.

One potential improvement can be something like this though, to avoid hardcoding `10.4` as a deployment target and instead use the minimal available one instead:

```diff
diff --git a/src/Makefile b/src/Makefile
index 532da6e..05c018e 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -297,7 +297,7 @@ ifeq (,$(shell $(TARGET_CC) -o /dev/null -c -x c /dev/null -fno-stack-protector
 endif
 ifeq (Darwin,$(TARGET_SYS))
   ifeq (,$(MACOSX_DEPLOYMENT_TARGET))
-    export MACOSX_DEPLOYMENT_TARGET=10.4
+    export MACOSX_DEPLOYMENT_TARGET=$(xcodebuild -showsdks | grep -o "macosx[0-9]*.[0-9]*" | head -1 | cut -c 7-)
   endif
   TARGET_STRIP+= -x
   TARGET_AR+= 2>/dev/null
```

[1] https://github.com/llvm-mirror/clang/commit/5389b84a780ac17b63c10ad97cd5e3aaa41595b7

**Comment by mraleph** [comment]
Though now that I started looking at #1 I can see a reason to switch to `clang` a default compiler on Mac OS X - iOS SDKs don't really come with `gcc` anymore so instructions simply do not work unless `CC` is set to `clang`.

**Comment by slime73** [comment]
> As @corsix notes: XCode also comes with /use/bin/gcc which is essentially clang.

gcc is an alias for clang on modern versions of OS X.

> One potential improvement can be something like this though, to avoid hardcoding 10.4 as a deployment target and instead use the minimal available one instead:

That change would make it use the SDK version as the deployment target, which isn't what most people would want. The deployment target is the earliest version of OS X that will be supported at runtime, whereas the SDK version is the OS X version of the current SDK. For example, Xcode 7 includes an SDK for OS X 10.11, and supports deploying down to OS X 10.4 at runtime.

https://developer.apple.com/library/mac/documentation/DeveloperTools/Conceptual/cross_development/Configuring/configuring.html

**Comment by mraleph** [comment]
> gcc is an alias for clang on modern versions of OS X.

It's not an alias and not a symlink (as opposed to `/usr/bin/cc`), it's a separate binary - but yes, it is a clang. 

@slime73 yeah, right, scratch that suggestion - I knew that it *should* support deploying to earlier versions, but somehow my dev mac machine has a borked XCode 6 setup which refuses to compile anything with 10.4 - so I jumped to the conclusion that they removed 10.4 support. Which doesn't seem to be the case from the docs. My fault.

**Comment by MikePall** [comment]
Fixed.
