### ISSUE TITLE
obtaining the main *lua_State given a non-main coroutine *lua_State (lua_mainthread?)

### ISSUE THREAD

**Issue by glycerine** [LuaJIT/LuaJIT#400]
I'm getting C callbacks on coroutines, but I cannot find a way via API to get the main state.

I resorted to adding this. If there's not an official way, perhaps this could be added to the API.

github.com/LuaJIT/LuaJIT/src/lj_api.c
~~~
LUA_API lua_State* lua_mainthread(lua_State *L)
{
  return mainthread(G(L));
}
~~~
lua.h addition:
~~~
LUA_API lua_State *(lua_mainthread) (lua_State *L);
~~~

**Comment by glycerine** [comment]
I note this patch specifically seems to crash luajit on Windows10/amd64. So while the API would be very useful, the implementation may need some vetting before merge.

**Comment by neoxic** [comment]
There's no need to change the API for that. Just store the main state's pointer in the registry and retrieve it in each callback.

**Comment by daurnimator** [comment]
If anything was actually changed, adding support for `LUA_RIDX_MAINTHREAD` would be helpful.
