### ISSUE TITLE
GC64: out of memory when reading output from popen

### ISSUE THREAD

**Issue by lblasc** [LuaJIT/LuaJIT#407]
Hello,

I think this should work for files bigger than 1G when luajit is built with `LUAJIT_ENABLE_GC64`.

test.lua:
```
local full_command = 'cat test-data'
local in_ = io.popen(full_command, 'r')

local read = in_:read('*all')
in_:close()
```
Testcase (latest 2.1 branch with `-DLUAJIT_ENABLE_GC64` on linux):
```
$ truncate -s 2G test-data
$ luajit test.lua
luajit: not enough memory
```

Thanks!

**Comment by MikePall** [comment]
This is not going to work. Apart from the core restriction on maximum string length, neither the built-in `read('*a')` functionality nor the garbage collector would handle this gracefully, anyway.

Use the FFI for dealing with big files. And better `mmap` them, if you're only reading them.
