### ISSUE TITLE
Metatable/__index specialization

### ISSUE THREAD

**Issue by MikePall** [LuaJIT/LuaJIT#41]
Accesses to metatables and __index tables with constant keys are already specialized by the JIT compiler to use optimized hash lookups (HREFK). This is based on the assumption that individual objects don't change their metatable (once assigned) and that neither the metatable nor the __index table are modified. This turns out to be true in practice, but those assumptions still need to be checked at runtime, which can become costly for OO-heavy programming.

Further specialization can be obtained by strictly relying on these assumptions and omitting the related checks in the generated code. In case any of the assumptions are broken (e.g. a metatable is written to), the previously generated code must be invalidated or flushed.

Different mechanisms for detecting broken assumptions and for invalidating the generated code should be evaluated.

This optimization works at the lowest implementation level for metatables in the VM. It should equally benefit any code that uses metatables, not just the typical frameworks that implement a class-based system on top of it.

**Comment by Neopallium** [comment]
As a first step towards implementing this would the following be a good idea?

1. By default enable specialization assuming metatables and __index are not modified.
2. When the assumptions broken (metatable or __index are changed), then invalid all (or some) of the generated code.
3. If the assumptions are broken X times, disable the optimization.

I think this would at least allow trying the optimization out.  Then improvements could be made to detecting when the assumptions are broken and invaliding only the affected code.

**Comment by fogfx** [comment]
Just throwing an idea out there for assumption-breaking detection: how about sacrificing one of the nomm bits to mark a table as a metatable? Just set this bit whenever a table is passed as the metatable argument to the Lua and C `setmetatable` family; if this bit is set, the metatable will be eligible for this optimization. This seems to work for a few reasons:
- LuaJIT only uses 6 of the 8 available nomm bits (for `__index`, `__newindex`, `__mode`, `__gc`, `__eq`, and `__len`). This is sufficient for 5.1 and 5.2, and assuming 5.3 support is remotely an option, probably that as well.
- The nomm bits are already cleared when a table is written to; this would conveniently clear the metatable bit too.
- Only if the metatable bit is set in the above case will LuaJIT need to flush traces; traces generated while the bit is cleared will use the current, safe metatable lookup. This is suboptimal if the metatable bit is later set again, but it's valid.
- It does add a branch to table writes, but sanely written Lua code should rarely if ever take it. 

Granted, it doesn't efficiently handle the case of a metatable constantly flip-flopping between optimized and unoptimized states (and the associated trace flushing overhead)... but then again you wouldn't be benefitting from the nomm either. It is, however, relatively forgiving to infrequent metatable patching.

`self.__index = self` people will just have to get over it :) (or use the inevitable -O flag)

**Comment by MikePall** [comment]
That's not a feasible approach, since it adds a load and a branch to **every** table write.

One needs to kick any write to such a metatable off of the fast path by re-purposing the *existing* checks.
Reducing the problem to string keys, either the hash lookup must fail and end up in the slow path (for writes only), or the table barrier must trigger and do an extra check for a metatable write in the slow path (currently, this path is also very fast).

It's instructive to follow `case BC_TSETS` in `src/vm_x86.dasc` (or whichever architecture you prefer). Of course, the JIT compiler does lots of additional magic to reduce this to a few instructions -- but it basically has to do the same checks for table writes. Adding more checks in the fast path is too expensive.

Adding some bit to `GCtab.marked` that's checked together with `LJ_GC_BLACK` is probably the way to go.

But the more difficult problem is the actual trace invalidation. Flushing all traces (every time) seems excessive.
