### ISSUE TITLE
Negative non-base10 tonumber

### ISSUE THREAD

**Issue by 44100hertz** [LuaJIT/LuaJIT#413]
```
LuaJIT 2.1.0-beta3 -- Copyright (C) 2005-2017 Mike Pall. http://luajit.org/
JIT: ON SSE2 SSE3 SSE4.1 BMI2 fold cse dce fwd dse narrow loop abc sink fuse
> print(tonumber("-1", 16))
1.844674407371e+19
> print(tonumber("-0.9", 16))  
nil
```
This bug is present on all non-10 bases.
Parsing hex literals (-0x1, etc.) does behave correctly. Vanilla lua does not have this bug.

**Comment by hnes** [comment]
Which version of the vanilla lua you are using?
 
Because I got this:

```bash
$lua
Lua 5.1.4  Copyright (C) 1994-2008 Lua.org, PUC-Rio
> print(tonumber("-1", 16))
1.844674407371e+19
> print(tonumber("-0.9", 16))
nil
> ^C
$lua5.2.4
Lua 5.2.4  Copyright (C) 1994-2015 Lua.org, PUC-Rio
> print(tonumber("-1", 16))
-1
> print(tonumber("-0.9", 16))
nil
> ^C
$lua5.3.4
Lua 5.3.4  Copyright (C) 1994-2017 Lua.org, PUC-Rio
> print(tonumber("-1", 16))
-1
> print(tonumber("-0.9", 16))
nil ```

**Comment by fogfx** [comment]
Straight out of the 5.1 manual for `tonumber`:

> In base 10 (the default), the number can have a decimal part, as well as an optional exponent part (see §2.1). In other bases, only unsigned integers are accepted.

**Comment by 44100hertz** [comment]
Oh I should have been more thorough. I was using lua5.3, and I did make the mistake of saying that hex parses with a decimal place. It doesn't.

I guess that turns this more into a feature request.

**Comment by MikePall** [comment]
Feature added (to v2.1).
