### ISSUE TITLE
Build with JEMALLOC on x86_64

### ISSUE THREAD

**Issue by PSChrisHinshaw** [LuaJIT/LuaJIT#414]
In attempting to pass in the following `make XCFLAGS=-DLUAJIT_USE_SYSMALLOC LDFLAGS=-L$(ROOTDIR)/jemalloc/lib -ljemalloc`, I ran into a compile error generated in src/lib_aux.c `"Must use builtin allocator for 64 bit target"`.  I made the following change to that file:
`$ git diff
diff --git a/src/lib_aux.c b/src/lib_aux.c
index 7af1cd4..a26abd9 100644
--- a/src/lib_aux.c
+++ b/src/lib_aux.c
@@ -303,7 +303,7 @@ static int panic(lua_State *L)
 #ifdef LUAJIT_USE_SYSMALLOC
 
 #if LJ_64 && !defined(LUAJIT_USE_VALGRIND)
-#error "Must use builtin allocator for 64 bit target"
+//#error "Must use builtin allocator for 64 bit target"
 #endif
 
 static void *mem_alloc(void *ud, void *ptr, size_t osize, size_t nsize)
@@ -320,7 +320,12 @@ static void *mem_alloc(void *ud, void *ptr, size_t osize, size_t nsize)
 
 LUALIB_API lua_State *luaL_newstate(void)
 {
-  lua_State *L = lua_newstate(mem_alloc, NULL);
+  lua_State *L = NULL;
+#if LJ_64
+  L = lj_state_newstate(mem_alloc, NULL);
+#else
+  L = lua_newstate(mem_alloc, NULL);
+#endif
   if (L) G(L)->panic = panic;
   return L;
 }
@@ -331,7 +336,7 @@ LUALIB_API lua_State *luaL_newstate(void)
 
 LUALIB_API lua_State *luaL_newstate(void)
 {
-  lua_State *L;
+  lua_State *L = NULL;
   void *ud = lj_alloc_create();
   if (ud == NULL) return NULL;
 #if LJ_64`

There was apparently a reason not to allow the `system` malloc on a 64 bit system.  This change will allow me to do so.  Please let me know if a pull request for this change is appropriate.

**Comment by daurnimator** [comment]
LuaJIT requires that allocated memory is in the first 47 bits of address space. system `malloc` has no such guarntee of this, and hence can't (in general) be used.
If your `malloc` happens to return only things in the right address space then your patch will work; but the change is not suitable for upstreaming.

**Comment by PSChrisHinshaw** [comment]
Thanks for the prompt reply.  I will verify that jemalloc limits to 47 bits for our purposes.

**Comment by MikePall** [comment]
Jemalloc most certainly doesn't support address-range restrictions.

If you really want to link with jemalloc, use the GC64 mode in the v2.1 branch, which doesn't have this limitation. And do some performance testing, because it's unlikely it'll be better/faster/smaller than the built-in allocator.
