### ISSUE TITLE
Insufficient bytecode documentation

### ISSUE THREAD

**Issue by thomasb892** [LuaJIT/LuaJIT#417]
I have a custom language written which basically is like lua with braces instead of do..end, 0 based indexes, local by default and list comprehensions and with a more terse syntax. The parser is almost complete but we soon understood that it would not be productive to write a translator which would translate to Lua just for executing on the Luajit VM, we may as well translate it to C++ or C which could be compiled but it is non trivial. We really need good byte code documentation so that more languages could be ported to Luajit vm. It would be very helpful if a tutorial/documentation would be written to explain the file format and the opcodes used(the portable version of byte code which is listed when we use "luajit -bl filename.lua"). We need enough information to be able to understand and write the compiler for our language.

I bet this will help people in future

**Comment by MikePall** [comment]
http://wiki.luajit.org/Bytecode-2.0
