### ISSUE TITLE
Need help debugging GC issue on exit

### ISSUE THREAD

**Issue by cronhan** [LuaJIT/LuaJIT#424]
Hi,

We are trying to replace Lua 5.1 with LuaJIT (2.0.5) in our application. Everything seems to be working fine until the final "exit". In the function `static GCRef *gc_sweep(global_State *g, GCRef *p, uint32_t lim)` the code exits with a segfault on the line `if (o->gch.gct == ~LJ_TTHREAD)`. This is due to the fact that `p` seems to have an invalid value:

> 403: 0x40109930 0x40109930 lim: 2147472905 1074829616
> 403: 0x40109d08 0x40109d08 lim: 2147472904 1074830600
> 403: 0x40109690 0x40109690 lim: 2147472903 1074828944
> 403: 0x401022a8 0x401022a8 lim: 2147472902 1074799272
> 403: 0x66696c70 0x66696c70 lim: 2147472901 1718185072 <-- here is the problematic address
> Program received signal SIGSEGV, Segmentation fault.
> 
> (gdb) print o
> $2 = (GCobj *) 0x66696c70
> (gdb) print p
> $3 = (GCRef *) 0x401022a8
> (gdb) print *p
> $4 = {gcptr32 = 1718185072}

At this point I'm not sure if it is an initialisation problem or due to "how we use it". What I have noticed is that the interpreter state exhibits this behaviour when a state is constructed at the same location in memory as a previous state:

> luaL_newstate: 0x40000010
> ctor this=0x5f18220 m_state=0x40000378
> luaL_newstate: 0x40120010
> ctor this=0x246e150 m_state=0x40120378
> dtor this=0x5f18220 m_state=0x40000378 gc=0x400003d8 gc.root=0x400003e8
> close: g=0x400003b8
> luaL_newstate: 0x40100010
>
> ----> Here m_state is created at 0x40100378:
> ctor this=0x7fffffffb800 m_state=0x40100378 
> ----> Here this m_state is destructed/cleaned:
> dtor this=0x7fffffffb800 m_state=0x40100378 gc=0x401003d8 gc.root=0x401003e8
> close: g=0x401003b8
> [New Thread 0x7fffa3511700 (LWP 87586)]
> luaL_newstate: 0x40100010
> 
> ----> Here m_state is created at 0x40100378 again:
> ctor this=0x24c9920 m_state=0x40100378
> dtor this=0x246e150 m_state=0x40120378 gc=0x401203d8 gc.root=0x401203e8
> close: g=0x401203b8
> [Thread 0x7fffa3511700 (LWP 87586) exited]
> [New Thread 0x7fffa3511700 (LWP 87588)]
> [Thread 0x7fffa3511700 (LWP 87588) exited]
> luaL_newstate: 0x40180010
> ctor this=0x7418990 m_state=0x40180378
> 
> ----> Here this m_state is destructed/cleaned again:
> dtor this=0x24c9920 m_state=0x40100378 gc=0x401003d8 gc.root=0x401003e8
> close: g=0x401003b8
> 
> Program received signal SIGSEGV, Segmentation fault

Any help trying to figure out what is going on will be appreciated. My current thinking is the memory at the state is not properly cleaned, and when it is then "reused" something is not assigned/initialised correctly. Unfortunately I do not know where to go look for this.

**Comment by cronhan** [comment]
I forgot to add that this happens on Windows (using Visual Studio 2015) as well, same issue. However, when I added printf statements for debugging on Windows, the problem went away...

**Comment by cronhan** [comment]
I should also probably mention that this is (at least so far) happening when I run code that was wrapped with SWIG.

**Comment by sindrom91** [comment]
You will probably need to provide a small example someone can run. But here are some questions:

Does it happen consistently? If so, maybe you can put a few watchpoints in GDB and see what generated corrupted data.

Does it happen when you turn JIT off? Considering it's so sensitive that printf makes it disappear, I guess disabling JIT will have the same effect.

**Comment by MikePall** [comment]
First, look into your Lua project and relink it with a Lua library built with assertions enabled. Fix all ensuing assertions, before porting over to LuaJIT.

LuaJIT is not very tolerant, when it comes to mishandling of the Lua stack from the C side, memory overwrites beyond the end of userdata or unanchored threads (main cause of crashes in the  Lua/C API). Rebuild LuaJIT with assertions enabled.

Also, SWIG imposes a giant binding overhead on the C side. LuaJIT cannot help you with the binding overhead, unless you're willing to do a new binding -- FFI or even the plain Lua/C API will be tons faster. First, profile your application and check whether any bottleneck you're seeing is really in the pure Lua part or in the binding.

**Comment by cronhan** [comment]
Thanks for all the suggestions. After what can only be described as 'debugging fatigue' a colleague realized it is due to INOUT char* variables not being handled correctly, leading to memory smashes.
