### ISSUE TITLE
Mainline LuaJIT 

### ISSUE THREAD

**Issue by swalk-cavium** [LuaJIT/LuaJIT#427]
Aarch64 has been supported for quite a while on the v2.1 branch, but since it's
labeled 'beta' it won't be included in any linux distros.

Is there a timeline for merging the branch onto master?

**Comment by swalk-cavium** [comment]
@MikePall - Any comments?

**Comment by myfreeweb** [comment]
> won't be included in any linux distros

It is included actually… https://repology.org/metapackage/luajit/versions

Debian Testing, Ubuntu 18.x, Fedora are shipping 2.1.0beta3

**Comment by swalk-cavium** [comment]
Thanks.  Apparently I had old information.  No need for issue now.
