### ISSUE TITLE
Is 'require "jit.opt".start("maxirconst=xxx")' deprecated?

### ISSUE THREAD

**Issue by spacewander** [LuaJIT/LuaJIT#430]
`JIT_P_maxirconst` could not be found in the source code. Is this option deprecated or is there another way to fetch this `JIT_PARAMENUM`?
Please correct me if I am wrong.

**Comment by MikePall** [comment]
Search for `maxirconst`. Some macros do the expansion to the internal `JIT_P_` constants.

The call in the title works just fine.

**Comment by spacewander** [comment]
@MikePall 
I searched `maxirconst` and only found two cases:
```sh
 $ rg maxirconst     
doc/running.html
271:<td class="param_name">maxirconst</td><td class="param_default">500</td><td class="param_desc">Max. number of IR constants of a trace</td></tr>

src/lj_jit.h
100:  _(\012, maxirconst,	500)	/* Max. # of IR constants of a trace. */ \
```

One is its definition, another one is in the documentation.

**Comment by spacewander** [comment]
@daurnimator 
I mean, there are only definition and documentation for `maxirconst`, but there is not usage in the repo.

**Comment by corsix** [comment]
I'm inclined to agree with @spacewander's observations here: yes, `JIT_P_maxirconst` gets defined, and yes there is a slot in `J->param` corresponding to it, and yes doing `require "jit.opt".start("maxirconst=xxx")` will change the value in this slot, but nothing seems to read from this slot, and so changing the value in the slot has little effect. Something like the following would cause it to have an effect, but as things currently stand there does not seem to be any code like the following in the repo:

```diff
diff --git a/src/lj_record.c b/src/lj_record.c
index 1a2b1c5d5b..582849e177 100644
--- a/src/lj_record.c
+++ b/src/lj_record.c
@@ -2473,6 +2473,9 @@ void lj_record_ins(jit_State *J)
   /* Limit the number of recorded IR instructions. */
   if (J->cur.nins > REF_FIRST+(IRRef)J->param[JIT_P_maxrecord])
     lj_trace_err(J, LJ_TRERR_TRACEOV);
+  /* Limit the number of recorded IR constants. */
+  if (J->cur.nk+(IRRef)J->param[JIT_P_maxirconst] > REF_BIAS)
+    lj_trace_err(J, LJ_TRERR_TRACEOV);
 }
```

**Comment by MikePall** [comment]
Added (and fixed, the comparison is in the wrong direction).
