### ISSUE TITLE
 conflicting types for '_BitScanForward'  '_BitScanReverse'

### ISSUE THREAD

**Issue by mumin16** [LuaJIT/LuaJIT#431]
i gets errors following while i compile luajit with clang 6 in windows 10 

host/lj_def.h:258:15: error: conflicting types for '_BitScanForward'
unsigned char _BitScanForward(uint32_t *, unsigned long);
              ^
host/lj_def.h:258:15: note: '_BitScanForward' is a builtin with type 'unsigned char (unsigned long *, unsigned long)'
host/lj_def.h:259:15: error: conflicting types for '_BitScanReverse'

**Comment by mumin16** [comment]
I deleted 258-261 lines lj_def.h. Does this cause a problem?

**Comment by MikePall** [comment]
Fixed.
