### ISSUE TITLE
Complex numbers

### ISSUE THREAD

**Issue by LXSMNSYC** [LuaJIT/LuaJIT#434]
hello, so I just learned that C has complex types, I learend about it when I was using ffi for declaring a "complex" struct and it threw me an error, which then I realized that "complex" was reserved.

anyways, to the issue. so I tried accessing the complex feature. Here is my code:

```lua
local ffi = require "ffi"
local C, new = ffi.C, ffi.new

ffi.cdef[[
   double cabs(double complex z);
]]

print(C.cabs(new("double complex", 5, 2)))
```

it threw an error:
```lua
stdin:1: cannot resolve symbol 'cabs': The specified procedure could not be found.

stack traceback:
        [C]: in function '__index'
        stdin:1: in main chunk
        [C]: at 0x00402020
```

In which I am confused. LuaJIT knows that there is a "complex" keyword that is reserved and yet I can't seem to access this library. I also tried this: http://lua-users.org/lists/lua-l/2011-08/msg01026.html
and it also threw the same error.

I tried the functions provided by the tutorial http://luajit.org/ext_ffi_tutorial.html and it seems to work fine. So what is the problem? any possible workaround? 

Thanks!

**Comment by daurnimator** [comment]
> So what is the problem? any possible workaround?

On your platform, `cabs` is likely in the math library ("libm"). Instead of using `ffi.C.cabs` use `ffi.load("m").cabs`

**Comment by LXSMNSYC** [comment]
> On your platform, cabs is likely in the math library ("libm"). Instead of using ffi.C.cabs use ffi.load("m").cabs

Hello, thanks for the reply!

Unfortunately, it threw this error:

```lua
stdin:1: cannot load module 'm': The specified module could not be found.

stack traceback:
        [C]: in function 'load'
        stdin:1: in main chunk
        [C]: at 0x00402020
```

Do I have to install something? I checked my gcc, and I saw that the functions are declared on the complex.h header

**Comment by MikePall** [comment]
I guess you need to ask in some MinGW forum, which library contains the complex functions. Maybe it's in `libgcc`, i.e. `ffi.load('gcc')`.
