### ISSUE TITLE
os.clock() behave differently on Linux and Windows when calling sleep() with FFI

### ISSUE THREAD

**Issue by SuperUserNameMan** [LuaJIT/LuaJIT#442]
Hi,

Tested on LuaJit 2.1.0beta3, LuaJit 2.0.5 and LuaJit 2.0.4 on Windows 8.1 x64, Linux Mint 18 x86, and DietPi on a Raspberry Pi W.

If you define a ``sleep()`` with FFI (like the example provided on LuaJit FFI tutorial page), and if you run this tiny code :
````lua
t0 = os.clock()
for i=1,10 do
	print( os.clock() - t0 );
	sleep(1);
end
````

On Windows, you'll get the expected result :
````
0
1.013
2.014
3.018
4.03
5.041
6.057
7.069
8.081
9.091
````

On Linux (x86 and ARM), you'll get wrong result :
````
2.1999999999999e-05
0.000754
0.001067
0.001392
0.001775
0.002094
0.002382
0.00267
0.002916
0.003112
````

Here is the ``sleep()`` defined using FFI like provided into the LuaJit FFI tutorial page :

````lua
local ffi = require("ffi")

ffi.cdef[[
	void Sleep(int ms);
	int poll(struct pollfd *fds, unsigned long nfds, int timeout);
]]

if ffi.os == "Windows" then
	function sleep(s)
		ffi.C.Sleep(s*1000) -- TODO implement something with a better granularity
	end
else
	function sleep(s)
		ffi.C.poll(nil, 0, s*1000)
	end
end
````

If you replace this FFI definition with this code :

````lua
function sleep(s)
	local t0 = os.clock()
	repeat until (os.clock() - t0) >= s
end
````
Then, both Windows and Linux get the same expected results.

**Comment by spacewander** [comment]
@SuperUserNameMan 
It is because `os.clock()` calls the `clock()` in the C land. And the behavior of `clock()` is OS dependent.

**Comment by SuperUserNameMan** [comment]
As I'm far from being an expert on this toppic, i don't know if it could/should be implemented directly into LuaJit, neither if it's the most appropriate alternative, but here is a hack that gives me the expected bahavior in Linux :


````C
// compile libclockalternative.so : 
// gcc -c -fPIC clockalternative.c && gcc -shared clockalternative.o -o libclockalternative.so

#include <time.h>

PUBLIC_API
double clock_alternative() {
	struct timespec ts;
	clock_gettime( CLOCK_MONOTONIC_RAW, &ts );
	return ((double)ts.tv_sec ) + ((double)ts.tv_nsec) / 1000000000;
}
````

````lua
-- universal_clock.lua

if ffi.os == "Linux" then
	ffi.cdef [[
		double clock_alternative();
	]]
	local bind = ffi.load("./libclockalternative.so");
	function clock_override()
		local t0 = bind.clock_alternative();
		return function() return bind.clock_alternative() - t0; end
	end
	os.clock = clock_override();
end
````

**Comment by corsix** [comment]
If you're trying to measure real time, then call `os.time()` (potentially also with `os.difftime`) rather than `os.clock()`?

**Comment by daurnimator** [comment]
`clock()`'s behaviour is well known on windows (and by many people, expected). For parity with PUC-Rio Lua, I do not think LuaJIT should change behaviour.

See the windows docs on their `clock()` function: https://docs.microsoft.com/en-au/cpp/c-runtime-library/reference/clock?view=vs-2017

**Comment by spacewander** [comment]
@SuperUserNameMan 
> Maybe an OS dependant behavior was not expected by the author of the vanilla Lua and should be homogenised in LuaJIT ?

Actually PUC-Rio Lua implements `os.clock()` with `clock()`. I guess LuaJIT inherits the implementation from it.

**Comment by SuperUserNameMan** [comment]
@corsix : i was writing a generic tool module related to timing, and I found that if I implemented a ``sleep()`` with FFI, then it was interfering in an unexpected and unwanted manner with the behaviour of ``os.clock()`` under Linux.
All I need is to keep the same default behavior on each platforms. And as ``os.time()`` returns time in seconds when I require at least milliseconds, I focused my efforts on a way to make ``os.clock()`` more cross-platform friendly.

@daurnimator :
Apparently, on Linux, the time consummed by the ``sleep()`` is ignored by ``os.clock()`` ? 
I thought it was some sort of "bug" into LuaJit, because into the PUC-Rio (vanila?) Lua, the behavior was not supposed to be platform dependent since it has no FFI and no way to call a C ``sleep()``, does it ?

@spacewander :
Well, from my Lua/LuaJIT newby point of view, this sudden and unexpected platform dependant behavior was a bad surprise that would have required a fix ... but I guess i should have better concidered the fact that this function was stored into the ``os`` module ...

**Comment by MikePall** [comment]
`os.clock()` simply calls C89 `clock()`, which has unportable behavior. The Lua-side API cannot be changed, because someone may rely on the existing (crappy) behavior. Simply avoid this function.

In fact, there are no portable OS APIs for either getting the elapsed wall clock time since boot or the elapsed CPU time. But it's trivial to call them via the FFI directly (and there's really no need for a C wrapper). Some suggestions have been given above.

**Comment by SuperUserNameMan** [comment]
@MikePall : thank you for your answer.
As for the reason I used a C wrapper, it's because I could not find the official integer value of ``CLOCK_MONOTONIC_RAW`` which might be OS dependant (if i understood correctly the doc i read).
