### ISSUE TITLE
Debug symbols on Release configuration (MSVC)

### ISSUE THREAD

**Issue by Xottab-DUTY** [LuaJIT/LuaJIT#444]
It would be awesome if we would be able to get the `.pdb` for LuaJIT using the standard `msvcbuild.bat`

**Comment by MikePall** [comment]
I was under the impression that `mscvbuild debug` does that? If not, then I don't know which MSVC switches would activate that.

**Comment by Xottab-DUTY** [comment]
It does but I mean getting `.pdb` without a `debug` key.
