### ISSUE TITLE
X86_64: constant pointers get sign-extended if > 0x80000000

### ISSUE THREAD

**Issue by javierguerragiraldez** [LuaJIT/LuaJIT#445]
In `asm_fuseloadk64()`, there's this check before using a constant pointer:
```
  if (!LJ_GC64 || checki32((intptr_t)k)) {
```
but `!LJ_GC64` doesn't guarantee that `k` fits in the positive part of the `int32_t`.

I have a trace where `T->ir = 0x7ffcdb20` and `T->nk = 32544`, so the IR code `MUL 0187  +1000000` gets assembled into `mulsd  xmm6,QWORD PTR ds:0xffffffff8000d808`, since that `+1000000` is at `T->ir[REF_BIAS-99]`, which is 0x8000d808, and gets sign extended by the `mulsd` opcode format.

It seems that just removing the first part of the check would avoid this instruction format:
```
  if (checki32((intptr_t)k)) {
```
I haven't been able to build a testcase, since it depends on allocating a long trace at just the right place.

**Comment by MikePall** [comment]
First, your proposed fix is wrong -- this would just leave some fields undefined for `!LJ_GC64`.

Second, this cannot happen on `!LJ_GC64`. `k` is the address of a 64 bit constant inside the IR. And the IR memory is allocated by the internal allocator, so it must surely be below the 2GB limit. If this is not the case, then you'll run into way bigger problems than this. Have you modified the allocator?

**Comment by javierguerragiraldez** [comment]
`lj_trace_alloc()` calls `lj_mem_newt()`, which only checks that the start of the new block is below 2GB. but when a trace is long enough, part of if could be above that limit, as on the example I mention (`T->ir = 0x7ffcdb20` and `T->nk = 32544`)

**Comment by MikePall** [comment]
Turns out to be an actual bug in the fallback probing allocator. Fixed.
