### ISSUE TITLE
Faster float conversions on ARM

### ISSUE THREAD

**Issue by daurnimator** [LuaJIT/LuaJIT#446]
Today I saw https://twitter.com/gparker/status/1047246359261106176

> ARMv8.3 adds a new float-to-int instruction with errors and out-of-range values handled the way that JavaScript wants.

Is this something LuaJIT can take advantage of?

**Comment by MikePall** [comment]
You mean `FJCVTS`. No, not really.

First, LuaJIT uses dual-number mode on ARM and ARM64. And very successfully, so. Almost all numbers that are used in an integer context are also kept as integers. Thus, no FP to int conversions are needed.

Second, the semantics of the instruction are not a perfect fit for LuaJIT, e.g. wrt. the handling of `-0`.

To back up the first claim, I've tracked the actual use of `asm_tointg()` and `asm_tobit()` in `lj_asm_arm64.h`. Those are the only two places where such an instruction might be helpful.

I've found that these instruction sequences are emitted very, very rarely and mostly in non-critical paths. The dynamic execution counts are immeasurably low.
