### ISSUE TITLE
Number precision is lost when converting to string

### ISSUE THREAD

**Issue by spacewander** [LuaJIT/LuaJIT#447]
Here is the test case:
```lua
local n = 123456789.123456
print(tostring(n)) -- 123456789.12346
print(string.format("%.14g", n)) -- 123456789.12346
print(string.format("%.17g", n)) -- 123456789.123456
```

In LuaJIT, `STRFMT_G14` is used to format a number, which causes precision lost when the number has more than 14 significant digits.
I guess this behavior is inherited from Lua 5.1.

Is it possible to use `%.17g` or something better instead  of `STRFMT_G14`, when converting a number to a string? 

PS. `%.17g` is chosen as the max signaificant digits precision of IEEE 754 double is 17.
Quote from the wikipedia: https://en.wikipedia.org/wiki/Double-precision_floating-point_format

> If an IEEE 754 double-precision number is converted to a decimal string with at least 17 significant digits, and then converted back to double-precision representation, the final result must match the original number.

**Comment by daurnimator** [comment]
This is on purpose to match lua; which has the same behavior in all of 5.1 up to 5.3.
See http://lua-users.org/lists/lua-l/2014-07/msg00071.html for some rationale.

**Comment by spacewander** [comment]
Is it worth breaking the Lua compatibility to bring in a more correct implementation?

**Comment by daurnimator** [comment]
> Is it worth breaking the Lua compatibility to bring in a more correct implementation?

What do you mean by 'correct' here?
I agree with luiz in the linked thread that it would be confusing to e.g. have `0.1` repeated back to you as `0.10000000000000001`. And the rounding to 14 places is consistent with both python and javascript.

**Comment by spacewander** [comment]
I agree  with you that  using `%.17g` is not a good solution as it could not handle `0.x` well.
But there should be a better solution.

> And the rounding to 14 places is consistent with both python and javascript.

It is incorrect with the recent version of Python and Javascript.

```bash
 ￥ python
Python 3.6.3 (default, Oct  3 2017, 21:45:48) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> n = 1234567890.12345678
>>> print(n)
1234567890.1234567
```

```bash
// I choose Node to represent Javascript because it is popular and is installed in my machine.
￥ node --version                             
v8.9.1
 /tmp  0
 ￥ node          
> String(1234567890.12345678)
'1234567890.1234567'
```

**Comment by MikePall** [comment]
`tostring` must have the same behavior as Lua. If you need a specific precision, use `string.format`. If you need a fully precise textual equivalent, then use `%a`.
