### ISSUE TITLE
Seemingly incorrect code generation with JIT enabled

### ISSUE THREAD

**Issue by gonzalezjo** [LuaJIT/LuaJIT#448]
I'm unsure if LuaJIT intentionally avoids IEEE float compliance a la ffast-math as an optimization. If it does, that might explain the behavior being observed, and this would be a non-issue. If it does not, I believe this is a bug. The code given has different behavior with the JIT on, versus off.

```lua
local terms, distinct, i = 
  {}, {}, 0

for a = 25, 81 do 
  for b = 25, 81 do 
    i = i + 1
    terms[i] = a ^ b
  end
end

i = 0 
for j = 1, #terms do 
  local term = terms[j]

  if not distinct[term] then 
    i = i + 1
    distinct[term] = true
  end
end

print(i)
```

with jit.off() before the first for loop, the script will print out `3228`. Without jit.off(), it will print out `3239`, which is a nonsensical answer. Is this intentional behavior?

**Comment by MikePall** [comment]
Dup of #9.
