### ISSUE TITLE
OSX 10.14 Mojave build errors

### ISSUE THREAD

**Issue by stuta** [LuaJIT/LuaJIT#449]
Latest 2.1 version of git.

```bash
make clean
make
...
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C src
...
Undefined symbols for architecture x86_64:
  "__Unwind_DeleteException", referenced from:
      _lj_err_unwind_dwarf in libluajit.a(lj_err.o)
  "__Unwind_GetCFA", referenced from:
      _lj_err_unwind_dwarf in libluajit.a(lj_err.o)
  "__Unwind_RaiseException", referenced from:
      _lj_err_throw in libluajit.a(lj_err.o)
  "__Unwind_SetGR", referenced from:
      _lj_err_unwind_dwarf in libluajit.a(lj_err.o)
  "__Unwind_SetIP", referenced from:
      _lj_err_unwind_dwarf in libluajit.a(lj_err.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by stuta** [comment]
After about one hour osx software update wanted to update command line tools. After those updates make did work.

**Comment by cosmtrek** [comment]
@stuta Hi, I've met this problem again, I tried the solutions provided but not fixed it... Can you build it successfully now?

**Comment by stuta** [comment]
Yes, I can build successfully in 10.14.2 using latest command line tools. I don't have xcode installed.

**Comment by cosmtrek** [comment]
Thanks. Finally I reset my `$PATH` to `/usr/bin:/bin:/usr/sbin:/sbin` and build it successfully.

**Comment by ariesdevil** [comment]
reset `$PATH` not works for me.

**Comment by stuta** [comment]
* Install 10.12.sdk from here: https://github.com/phracker/MacOSX-SDKs/releases
  - also it is impossible to build i386 with current SDK
* use MACOSX_DEPLOYMENT_TARGET="10.12" in build:
```bash
MACOSX_DEPLOYMENT_TARGET="10.12" CFLAGS="-DLUAJIT_ENABLE_GC64 -DLUAJIT_ENABLE_LUA52COMPAT" make amalg
```

**Comment by Spillage** [comment]
@ariesdevil  you can use ```make MACOSX_DEPLOYMENT_TARGET=10.14``` , it can solve my problem

**Comment by qinyao7777** [comment]
use make MACOSX_DEPLOYMENT_TARGET=10.14 , it also solve my problem.

**Comment by ariesdevil** [comment]
@Spillage Thx~

**Comment by unrealTOM** [comment]
> @ariesdevil you can use `make MACOSX_DEPLOYMENT_TARGET=10.14` , it can solve my problem

thanks.

**Comment by cosisis** [comment]
> 问题

it's works , thank you!

**Comment by eyeseaevan** [comment]
> * Install 10.12.sdk from here: [phracker/MacOSX-SDKs/releases](https://github.com/phracker/MacOSX-SDKs/releases)
>   
>   * also it is impossible to build i386 with current SDK
> * use MACOSX_DEPLOYMENT_TARGET="10.12" in build:
> 
> ```shell
> MACOSX_DEPLOYMENT_TARGET="10.12" CFLAGS="-DLUAJIT_ENABLE_GC64 -DLUAJIT_ENABLE_LUA52COMPAT" make amalg
> ```

Thank you, this worked!! I fact I had the same error on Intel MacOS 12.6, and I was able to compile for my version using my existing compiler flags for optimization like so...

```MACOSX_DEPLOYMENT_TARGET="12.6" CFLAGS="-DLUAJIT_ENABLE_GC64 -DLUAJIT_ENABLE_LUA52COMPAT $CFLAGS" CPPFLAGS="-DLUAJIT_ENABLE_GC64 -DLUAJIT_ENABLE_LUA52COMPAT $CPPFLAGS" CXXFLAGS="-DLUAJIT_ENABLE_GC64 -DLUAJIT_ENABLE_LUA52COMPAT $CXXFLAGS" luaver install-luajit 2.1.0-beta3```

So it doesn't need to be ```10.14```, but I'm assuming a higher version of *MACOSX_DEPLOYMENT_TARGET* than libundwind.
