### ISSUE TITLE
x86_64 Bad light userdata pointer question

### ISSUE THREAD

**Issue by sonoro1234** [LuaJIT/LuaJIT#450]
Compiling x86_64 windows7 LuaJIT2.1 and using LuaLanes says:Bad light userdata pointer
Is this the already known lightuserdata limitation to 47 bits?
I thought it was only present in Solaris/x64, and on ARM64
https://github.com/LuaJIT/LuaJIT/blob/v2.1/doc/status.html#L102

my compiler is mingw-w64 with gcc 8.1.0 perhaps is the 57bits VA issue?

How can we apply this recomendation 

>Avoid using <tt>lightuserdata</tt> to hold pointers that may point outside
of that range, e.g. variables on the stack. In general, avoid this data
type for new code and replace it with (much more performant) FFI bindings.
FFI cdata pointers can address the full 64 bit range.

if we cant create cdata pointers from the LuaJIT C API?

**Comment by sonoro1234** [comment]
How can we apply this recomendation if we cant create cdata pointers from the LuaJIT C API?

**Comment by daurnimator** [comment]
> How can we apply this recomendation if we cant create cdata pointers from the LuaJIT C API?

See https://github.com/LuaJIT/LuaJIT/pull/435

Note that the new function proposed there *can* throw: it's not a substitute for `pushlightuserdata` in places where you are trying to be safe.
----
However I assume the code you have tries to push a stack pointer (as opposed to a heap pointer) in a lightuserdata. Sadly LuaJIT doesn't support this.

**Comment by sonoro1234** [comment]
Finally founded that LuaLanes was using some generated keys with 64bits and pushing as lightuserdata. 
But in the future we will have to face the VA57 bits issue

**Comment by MikePall** [comment]
Resolved in v2.1
