### ISSUE TITLE
[RFE] pipelined scheduling of instructions: optimization for performance (and privacy/security)

### ISSUE THREAD

**Issue by verdy-p** [LuaJIT/LuaJIT#454]
Is there a plan to support pipeline scheduling, i.e. emitting codes in available slots of parallel pipelines (e.g. hyperthreading). This does not just apply to Intel x86/x64, but to various kinds of processors that have multiple processing units, each one with its own pipeline, and possibly by chaining pipepline of different kinds.

CPUs/GPUs/APUs today now use extensive parallel pipelines (this is used because there are multi-cycle delays for processing a single instruction, where some stages may even have unpredictable number of wait cycles: while they are waiting, the processing unit is doing nothing, but other parallel slots may be doing something else.

The idea is to track the instruction dependencies (data paths, including for general purpose registers, FP registers, flags, and atomicity of instructions that can be partially interrupted in the middle of their completion, and resumed after handling the interrupt).

Basically the idea is to handle multiple instruction flows in parallel, schedule the instructions in the correct instruction flow, counting the minimum number of cycles they need to complete in their pipeline before being able to process another instruction.

So the instructions are arranged in a "grid", with one column per parallel flow, and one row per cycle used (a single instruction will be occupying multiple cells vertically in one column, and each instruction has a graph of dependencies, i.e. it needs the data resulting from the completion of another prior instruction being terminated.

In compilers, this can be used to schedule the instruction and then merge the instruction flow into a single one where instructions may be delayed or freely reordered (within some maximum distance, i.e. the height of the grid, which is basically on the same order as the number of stages in a CPU/GPU/APU pipeline).

This in turn can be used by compilers to avoid CPUs using many false guesses in branch prediction, out-of-order execution. This can also help reduce the exposition to time issues like Spectre and Meltdown, caused by false guesses branch prediction: the instructions, even if their execution is anticipated, has lower chance to be cancelled and restarted with a higher latency which then becomes measurable and detectable if we compare to the time taken to complete instructions executed without successful guesses (which complete with a higher speed and the lowest latency).

As well such scheduling, because it would reduce the number of cycles spent in CPUs (anticipating some dependencies, which turn later to be false guess, meaning that execution must be restarted from the first stage in the pippeline), could help reduce energy used. With CPUs with hyperthreading, NUMA topology, many parallel cores, this can dramataically improve the throughput of the intruction set used. Modern CPUs take lot of resources trying to do branch prediction, and now spend too many cycles anticipating the result of a dependency before this dependency can be really checked, so many cycles are wasted performing computation thaty will finally be completely abandonned. The problem being that when anticipating the execution, they have monopolized important processing units (such as an ALU, a FPU, a VPU) which would have better been used by other competing instructions waiting for a time slot.

Instruction scheduling can avoid most of these wasted cycles, and help improve the security of computing systems (against time attacks), because the throughput is more linear, latency is stabilized. And globally performance is largely improved.

Instruction scheduling is especially useful in JIT compilers for highly dynamic languages like Lua, where branche prediction is much more difficult: interleaving the instructions that are mutually dependant by inserting enough other non-dependant instructions allow more instruction to complete (while other interleaved instructions are also running in their own separate pipeline of the processor). False guesses in branch prediction of processors will be much less likely, there will be less waiting cycles in all pipelines.

It is possible to instanciate a JIT compiler so that it will allow a maximum of N pipelines and schedule all instructions in these N pipelines. If finally the hardware processor has LESS pipelines, the optimization is still not lost (all what other emulated pipelines are doing are to eliminate data dependency and wait cycles, and eliminate many false guesses of processors in out-or-order execution.

This optimization is even more effective when a CPU has a large file of registers (8086 had very few registers and lot of dependencies across instructions at short distance, but modern x64 or ARM64 processors (and even more importantly the VPUs and dramatically more the GPUs) have allowed to create instruction flows with many more datas paths. But we still don't maximize this by scheduling also instructions into multiple instruction flow: an higher number of available data paths should also mean a higher number of instruction flows so we can maximize the number of data paths successfully parallelized.

All processors today (ecept the old CPUs of the 1980s) can benefit of this (including RISC processors that are built with NO or very basic branch prediction, just to offer more data paths and a higher number of instructions that can run in parallel without mutual dependency, such as "vector" instructions: MMX, SSE, GPU...)

So I wonder if you have a way to improve the JIT compiler so that its "code emitter" will allocate and schedule instructions into more virtual pipelines (note: it's not necessary that the virtual pipelines match the final pipelines of hardware processors: for CPU instruction sets, generally emulating about 16 or 32 pipelines in the code emitter will good results. For VPUs (and MMX/SSE instructions) and GPUs instruction sets, you may need more (typically about 256 virtual pipelines).

Reducing the number of virtual pipelines (e.g. to only 8 virtual pipelines, in the emitted instruction set is only needed for some privileged code that needs to have the smallest latency and accelerated responses, but this is rare and should only concern a few internal critial exception handlers in a OS or in hardware drivers that need near "real time" response, and that will run with higher priority (in ring 0), and will ensure that their high priority (causing higher delays in concurrent non-privileged code) will not open time attacks (the critical part of this privilege code will erase the predictability of delays experienced by concurrent non-critical unprivileged threads), by forcing them to wait more randomly.

A good scheduler in the code emitter can avoid many experiences of resource starvation (where a resource is an execution time slot to a processing unit, a memory access, access to L1/L2/L3 caches (or even now network caches, in the case of distributed computing, which is the next target of time attacks that will try to steal private data worldwide, using time-based covert channels now possible over fast Internet accesses at 1 Gbps or more).

**Comment by verdy-p** [comment]
This suggestion changes a bit what the code emitters (for each arch) do:
instead of emitting opcodes and operands directly to a single instruction stream, the code is emitted in a set of N streams, along with data depency marks (one mark for each dependant source: a register, a flag, a memory address), and a number of cycles to wait.
Each stream has a "busy" counter of cycles to wait because it is busy: each instruction emitted in a stream increments the stream's counter by the number of relevant cycles (this makes the stream busy for that amount of cycles, meaning that the final serialized stream cannot emit the instruction before the busy counter is zero: the final serialized stream will have to select an instruction from the least busy stream to emit it and decrease the busy cycles of each stream by the amount indicated in each instruction, provided that dependency bits are met. When the serialized stream outputs the instruction from one of the substreams it also unsets the dependency bits from the global dependency bits that were set, but then sets the dependency bits from the emitted instruction.
That's the generic idea: instructions will be reordered  (scheduled) in the serialized output stream, emulating the effect of multiple pipelines or pipeline stages in processors.
How many dependency bits to allocate per instruction? This depends only on the size of the register file (the number of registeres, the number of independant flags, plus a memory read and a memory write (these must be kept ordered).
This also has consequences when emitting relative jump instructions as the offset of the relocation is not known before the jump instructions is selected from one intermediate stream to the final serilaized stream. But this has advantages: if the relative jump goes to a recently emitted instruction, the offset is immediately available exactly (allowing immediate resolution of relative jumps without needing any relation record).
Two parameters are conditioning the size (in memory) of intermediate streams to keep: the number of substreams (i.e. emulated pipelines) and the maximum number of cycles (the height of each pipeline).
Typical modern processors will require a height of at least 64 cycles (the most costly instructions being those that perform memory access, as the number of cycles depends on L1/L2/L3 cache hits); more cycles may be needed for complex instructions.
modern CPUS generally can work with pipelines with at least 5 stages, as these pipeline work in parallel, this means that you need at least 5 streams (the width of your intermediate stream buffer); processors with hyperthreading can double this (2 threads per core) and if so you need to double also the number of substreams.
For a basic X64 processor (with 2-thread hyperthreading, 5 state pipelines, and 64 cycles used per pipeline), the intermediate streams buffer must then hold at least 10 instruction streams with a height equal to the maximum of 64 cycles which can be scheduled (so the scheduler can buffer up to 640 instructions if all of them are in busy, because they are in dependant data paths, or because the estimated number of cycles they need to complete fills the buffer completely: in that case the scheduler has to make a arbitrary choice to choose the stream to emit (it may do that by selecting depending on "age" of instructions in each substream, i.e. using a simple FIFO policy).
You can increase the number of substreams if you want more agressive optimization.
But the complex part of the code is to define instructions set and their opmodes so that they properly define their dependency bits (for datapaths)
For processors that have vector instructions (or instructions capable of operating on ranges of multiple registers) this can be used to optimize the instructions: two or more similar but independant instructions performing the same operation but on difference registers, and that have all their dependant datapaths in ready state (not marked budy in the emulated pipelines) can generate in the final output stream a single vectorized instruction instead of multiple instructions.
This allows automatic vectorization of the final code from a initially precompiled code not built to support vector instructions. As well if this optimization is supported, it may have constraints (such as which ranges of registers can be used to be vectorized: this has consequences on how you allocate the registers; one way to resolve this is to use "virtual" register numbers in the input instruction set, the real registers can be allocated by the optimizer built in the "pipelined" scheduler, which will use the best registers that can mit the vectorization constraints.

**Comment by MikePall** [comment]
The backend already does indirect instruction scheduling through various means. Explicit instruction scheduling is unlikely to improve upon that beyond the noise floor. Also it's too expensive for the constraints the JIT compiler operates under.

You could have phrased your question in one sentence. Conciseness is a virtue.
