### ISSUE TITLE
LuaJIT 2.1 ffi.cast("uint64_t", -1) returns wrong value

### ISSUE THREAD

**Issue by elliottslaughter** [LuaJIT/LuaJIT#459]
LuaJIT 2.1 differs from 2.0 in the behavior of `ffi.cast("uint64_t", -1)`.

LuaJIT 2.1 (commit 0a9ff94c4a1fcec2c310dcb092da694f23186e23):

```
> ffi=require('ffi')
> =ffi.cast('uint64_t', -1)
9223372036854775808ULL
```

LuaJIT 2.0.5:

```
> ffi=require('ffi')
> =ffi.cast('uint64_t', -1)
18446744073709551615ULL
```

Tested on Ubuntu 16.04, x86_64.

```
$ gcc --version
gcc (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010
```

**Comment by elliottslaughter** [comment]
Would it be worth making the behavior defined?

The reason why `-1` is useful is because if it's treated as signed two's complement and is sign-extended on conversion, then I can use it with any unsigned integer type `uint8_t`, `uint16_t`, `uint32_t`, `uint64_t`, `uint128_t`, etc. and get the right value. It's also a lot more obvious looking at the code that it's correct; I don't have to count the number of `F`s in `0xFF...FF` to make sure I'm not missing any. (Note this is not just true when writing the code, but also when auditing.)

**Comment by finnw** [comment]
Using an intermediate `int` representation will give the correct result (like in C)

    local int = ffi.typeof "int"
    local uint16_t = ffi.typeof "uint16_t"
    local uint64_t = ffi.typeof "uint64_t"

    local function m1_as_int()
        return int(-1)
    end

    print(tonumber(ffi.cast(uint16_t, m1_as_int())))
    print(ffi.cast(uint64_t, m1_as_int())) -- etc

Also resist the temptation to cache the boxed integral values. They will not get constified but they do have a chance to get allocation-sunk.

**Comment by MikePall** [comment]
Just use `-1ULL` for assignment, if you intend to get an all-ones bit pattern for any unsigned FFI type. No explicit cast required.
