### ISSUE TITLE
LuaJIT 2.1 VM out of memory for os.date

### ISSUE THREAD

**Issue by cleaton** [LuaJIT/LuaJIT#463]
The new implementation of `os.date` can cause a vm to get out of memory on an invalid formatting string when bound to musl instead of glibc. 

musl libc `strftime` will return 0 for malformed formatting strings while glibc seems to always return a positive length indicating partially copied buffer. The LuaJIT 2.1 implementation assumes 0 is only returned when the buffer is too small, causing an infinite loop increasing the buffer when using musl libc.

https://github.com/LuaJIT/LuaJIT/blob/0a9ff94c4a1fcec2c310dcb092da694f23186e23/src/lib_os.c#L213-L222

**Comment by cleaton** [comment]
After more testing I've found that this problem also affects glibc, for example using the following Lua code.

```
os.setlocale("sv_SE.utf8")
os.date("%p")
```

**Comment by MikePall** [comment]
Fixed. Thanks!
