### ISSUE TITLE
XCODE10 build error

### ISSUE THREAD

**Issue by yiyucyp** [LuaJIT/LuaJIT#468]
cd "$( dirname "${BASH_SOURCE[0]}" )"
LIPO="xcrun -sdk iphoneos lipo"
STRIP="xcrun -sdk iphoneos strip"

IXCODE=`xcode-select -print-path`
ISDK=$IXCODE/Platforms/iPhoneOS.platform/Developer
ISDKVER=iPhoneOS.sdk
ISDKP=$IXCODE/usr/bin/

if [ ! -e $ISDKP/ar ]; then 
  sudo cp /usr/bin/ar $ISDKP
fi

if [ ! -e $ISDKP/ranlib ]; then
  sudo cp /usr/bin/ranlib $ISDKP
fi

if [ ! -e $ISDKP/strip ]; then
  sudo cp /usr/bin/strip $ISDKP
fi

cd luajit-2.1.0b3
make clean
ISDKF="-arch armv7 -isysroot $ISDK/SDKs/$ISDKVER -miphoneos-version-min=7.0"
make HOST_CC="gcc -m32 -std=c99" TARGET_FLAGS="$ISDKF" TARGET=armv7 TARGET_SYS=iOS LUAJIT_A=libxluav7.a

make clean
ISDKF="-arch armv7s -isysroot $ISDK/SDKs/$ISDKVER -miphoneos-version-min=7.0"
make HOST_CC="gcc -m32 -std=c99" TARGET_FLAGS="$ISDKF" TARGET=armv7s TARGET_SYS=iOS LUAJIT_A=libxluav7s.a

make clean
ISDKF="-arch arm64 -isysroot $ISDK/SDKs/$ISDKVER -miphoneos-version-min=7.0"
make HOST_CC="gcc -std=c99" TARGET_FLAGS="$ISDKF" TARGET=arm64 TARGET_SYS=iOS LUAJIT_A=libxlua64.a

cd src
lipo libxluav7.a -create libxluav7s.a libxlua64.a -output libluajit.a

the output:
Building armv7 lib
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C src clean
rm -f luajit libluajit.a libluajit.so host/minilua host/buildvm lj_vm.S lj_bcdef.h lj_ffdef.h lj_libdef.h lj_recdef.h lj_folddef.h host/buildvm_arch.h jit/vmdef.lua .o host/.o *.obj *.lib *.exp *.dll *.exe *.manifest *.pdb *.ilk
==== Building LuaJIT 2.1.0-beta3 ====
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C src
HOSTCC host/minilua.o
HOSTLINK host/minilua
ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libm.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libm.tbd
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
Undefined symbols for architecture i386:
"__DefaultRuneLocale", referenced from:
_luaB_tonumber in minilua.o
_llex in minilua.o
_luaX_lexerror in minilua.o
_read_numeral in minilua.o
_statement in minilua.o
_check_match in minilua.o
_constructor in minilua.o
...
"___bzero", referenced from:
_luaS_resize in minilua.o
_luaD_call in minilua.o
_f_parser in minilua.o
"___error", referenced from:
_io_fclose in minilua.o
_io_pclose in minilua.o
_f_flush in minilua.o
_io_readline in minilua.o
_g_read in minilua.o
_g_write in minilua.o
_io_flush in minilua.o
...
"___maskrune", referenced from:
_luaB_tonumber in minilua.o
_llex in minilua.o
_luaX_lexerror in minilua.o
_read_numeral in minilua.o
_check_match in minilua.o
_error_expected in minilua.o
_match_class in minilua.o
...
"___sprintf_chk", referenced from:
_main in minilua.o
_luaL_loadfile in minilua.o
_panic in minilua.o
_luaO_pushvfstring in minilua.o
_luaV_concat in minilua.o
_luaB_assert in minilua.o
_luaB_loadfile in minilua.o
...
"___stack_chk_fail", referenced from:
_main in minilua.o
_luaL_loadfile in minilua.o
_panic in minilua.o
_luaG_runerror in minilua.o
_luaO_pushvfstring in minilua.o
_luaV_concat in minilua.o
_newkey in minilua.o
...
"___stack_chk_guard", referenced from:
_main in minilua.o
_luaL_loadfile in minilua.o
_panic in minilua.o
_luaG_runerror in minilua.o
_luaO_pushvfstring in minilua.o
_luaV_concat in minilua.o
_newkey in minilua.o
...
"___stderrp", referenced from:
_main in minilua.o
_panic in minilua.o
_luaopen_io in minilua.o
"___stdinp", referenced from:
_luaL_loadfile in minilua.o
_luaopen_io in minilua.o
"___stdoutp", referenced from:
_luaopen_io in minilua.o
"___strcat_chk", referenced from:
_luaO_chunkid in minilua.o
"___strncat_chk", referenced from:
_luaO_chunkid in minilua.o
"___strncpy_chk", referenced from:
_str_format in minilua.o
"___tolower", referenced from:
_str_lower in minilua.o
_match_class in minilua.o
"___toupper", referenced from:
_str_upper in minilua.o
"_clearerr", referenced from:
_g_read in minilua.o
"_exit", referenced from:
_f_luaopen in minilua.o
_luaH_new in minilua.o
_luaS_resize in minilua.o
_luaS_newlstr in minilua.o
_luaD_throw in minilua.o
_resetstack in minilua.o
_luaG_errormsg in minilua.o
...
"_fclose", referenced from:
_luaL_loadfile in minilua.o
_io_fclose in minilua.o
"_feof", referenced from:
_getF in minilua.o
"_ferror", referenced from:
_luaL_loadfile in minilua.o
_io_readline in minilua.o
_g_read in minilua.o
"_fflush", referenced from:
_f_flush in minilua.o
_io_flush in minilua.o
"_fgets", referenced from:
_read_line in minilua.o
"_fopen$UNIX2003", referenced from:
_luaL_loadfile in minilua.o
_io_lines in minilua.o
_io_open in minilua.o
_g_iofile in minilua.o
"_fprintf", referenced from:
_main in minilua.o
_panic in minilua.o
_g_write in minilua.o
"_fread", referenced from:
_read_chars in minilua.o
_getF in minilua.o
"_free", referenced from:
_l_alloc in minilua.o
"_freopen$UNIX2003", referenced from:
_luaL_loadfile in minilua.o
"_fscanf", referenced from:
_g_read in minilua.o
"_fwrite$UNIX2003", referenced from:
_g_write in minilua.o
"_getc", referenced from:
_luaL_loadfile in minilua.o
_g_read in minilua.o
"_isspace", referenced from:
_luaO_str2d in minilua.o
"_longjmp", referenced from:
_f_luaopen in minilua.o
_luaH_new in minilua.o
_luaS_resize in minilua.o
_luaS_newlstr in minilua.o
_luaD_throw in minilua.o
_resetstack in minilua.o
_luaG_errormsg in minilua.o
...
"_memchr", referenced from:
_llex in minilua.o
_read_numeral in minilua.o
_str_format in minilua.o
_str_find_aux in minilua.o
"_memcmp", referenced from:
_luaS_newlstr in minilua.o
_str_find_aux in minilua.o
_match in minilua.o
"_memcpy", referenced from:
_luaS_newlstr in minilua.o
_luaV_concat in minilua.o
_luaL_addvalue in minilua.o
"_pow", referenced from:
_luaD_call in minilua.o
_Arith in minilua.o
_codearith in minilua.o
"_realloc", referenced from:
_main in minilua.o
_l_alloc in minilua.o
"_remove", referenced from:
_os_remove in minilua.o
"_setjmp", referenced from:
_luaD_rawrunprotected in minilua.o
"_strchr", referenced from:
_luaO_pushvfstring in minilua.o
_propagatemark in minilua.o
_lua_getinfo in minilua.o
_str_format in minilua.o
_luaL_findtable in minilua.o
"_strcmp", referenced from:
_ipairsaux in minilua.o
_luaB_assert in minilua.o
_luaB_loadstring in minilua.o
_luaB_rawget in minilua.o
_luaB_setfenv in minilua.o
_luaB_setmetatable in minilua.o
_luaB_tonumber in minilua.o
...
"_strcoll", referenced from:
_luaD_call in minilua.o
_luaV_lessthan in minilua.o
"_strcspn", referenced from:
_luaO_chunkid in minilua.o
"_strerror$UNIX2003", referenced from:
_io_fclose in minilua.o
_io_pclose in minilua.o
_f_flush in minilua.o
_io_readline in minilua.o
_g_read in minilua.o
_g_write in minilua.o
_io_flush in minilua.o
...
"_strlen", referenced from:
_main in minilua.o
_luaL_register in minilua.o
_luaL_loadfile in minilua.o
_panic in minilua.o
_f_luaopen in minilua.o
_luaO_pushvfstring in minilua.o
_luaO_chunkid in minilua.o
...
"_strncpy", referenced from:
_luaO_chunkid in minilua.o
"_strpbrk", referenced from:
_str_find_aux in minilua.o
"_strtod$UNIX2003", referenced from:
_luaO_str2d in minilua.o
"_strtoul", referenced from:
_luaO_str2d in minilua.o
_luaB_tonumber in minilua.o
"_ungetc", referenced from:
_luaL_loadfile in minilua.o
_g_read in minilua.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [host/minilua] Error 1
make: *** [default] Error 2

**Comment by woshihuo12** [comment]
why close this issue？ has some solutions？？

**Comment by MikePall** [comment]
Have you actually **read** the error message?
Apple has removed 32 bit support for OSX and iOS.

**Comment by woshihuo12** [comment]
> Have you actually **read** the error message?
> Apple has removed 32 bit support for OSX and iOS.

I think can tip:if you want support iPhone4 or iPhone5. you need xcode9.4.1 to support this.but suggest dont support that.

**Comment by daurnimator** [comment]
> I think can tip:if you want support iPhone4 or iPhone5. you need xcode9.4.1 to support this.but suggest dont support that.

Apple dropped support for the iphone 4 in 2016 and iphone 5 in 2017/2018.
