### ISSUE TITLE
__gc on tables

### ISSUE THREAD

**Issue by daurnimator** [LuaJIT/LuaJIT#47]
Lua 5.2 and 5.3 allow a `__gc` metamethod on tables.
Currently for compatibility with Lua 5.1 or LuaJIT you need to do hacks via `newproxy`.
e.g. https://github.com/wahern/cqueues/blob/3f2fc57a07bb9e658f4d53ccc60ba8177e3f1236/src/dns.resolvers.lua#L51

**Comment by MikePall** [comment]
Part of #38.

**Comment by daurnimator** [comment]
> Part of #38.

Thanks for noting that. (It would have been possible to add the new garbage collector; or (with difficulty) to add `__gc` on tables without it)

**Comment by katlogic** [comment]
Note that I've ported Lua 5.3 GC to luajit with some success (the abysmal performance of currently naive gc is even more abysmal though with newer gc, as it traverses two more lists). Porting it from my repo is fairly trivial for anyone seriously interested.

Question is, should the effort be focused on incremental hacks on luajit, or better consolidate effort into something more radical? Sadly I dont have that much time these days to try to clean up and try to bring all the cowboyish NYI fixes and 5.2-compat LJ hacks into here, just hoping somebody else would pick up the mantle.

**Comment by katlogic** [comment]
Here is very preliminary implementation:

https://github.com/katlogic/LuaJIT/commit/a9636d35753c1c66c013086a6f204238420f5b5c

How it works:
* Enabled ONLY when LUAJIT_ENABLE_LUA52COMPAT is in place
* Tables are put onto userdata list
* GC udata w/ __gc separation code pick it from there if finalizers are due (when they lose white) and puts onto mmudata queues
* Some GC flag juggling had to be done, as LJ_GC_FINALIZED has now 3 purposes, depending on object type:
    * userdata it means the object had finalizer called, and shall not be invoked again
    * for tables, it marks the table actually has a finalizer (and was moved onto userdata list). it is cleared after finalizer is called, the inverse of userdata.
    * for ctypes, it works the same as with userdata
* Cosmetic change to interpreter, when __gc exists, use fallback. Porting to other archs is trivial, but would be done only if this code gets accepted.

In addition, resurrection is possible by calling setmetatable again. Dangerous, but in some rare cases extremely useful feature.

Comments starting with ``UNSURE:`` are possible bugs in maintaining GC invariants - I have only somewhat vague high level understanding of Lua GC, I don't know what I'm really doing as all possible state transitions during object tracking are numerous. Comments from somebody with better grasp of Lua 5.1 GC would be much appreciated.

**Comment by katlogic** [comment]
JIT recorder https://github.com/katlogic/ljx/commit/d293101384e55fbdcff053696f1e2d53d755c4ae
