### ISSUE TITLE
Update benchmarks

### ISSUE THREAD

**Issue by nico-abram** [LuaJIT/LuaJIT#470]
I don't see 2.1 in the benchmarks (Ex. http://luajit.org/performance_x86.html).

Unimportant: Does anyone know a place where one can find up to date (2.1) luajit benchmarks against other languages (Like benchmarks game used to do)

**Comment by siddhesh** [comment]
Those tests are in a separate repo and are reasonably up to date:

https://github.com/LuaJIT/LuaJIT-test-cleanup
