### ISSUE TITLE
Dead link in faq?

### ISSUE THREAD

**Issue by nico-abram** [LuaJIT/LuaJIT#471]
http://article.gmane.org/gmane.comp.lang.lua.general/58908 gives me a completely empty page (It's linked in http://luajit.org/faq.html 's "Where can I learn more about the compiler technology used by LuaJIT?" . Specifically "innovative features in LuaJIT").

**Comment by kirbyfan64** [comment]
Alternative link I found: http://lua-users.org/lists/lua-l/2009-11/msg00089.html

**Comment by siddhesh** [comment]
The original link seems to work just fine, maybe it was a transient error.
