### ISSUE TITLE
string.format for long string

### ISSUE THREAD

**Issue by hyee** [LuaJIT/LuaJIT#472]
The maximum supported width of a string in `string.format` is 99 (`%99s`), is it possible to support larger width, for example 1024? 
Acknowledged that 99 is the Lua standard, but it's inconvenient in some cases.

**Comment by MikePall** [comment]
The relevant code has been rewritten for LuaJIT, so the limit could technically be raised to 255. But since that wouldn't be much of an improvement and for compatibility with Lua, I think it's better to keep the documented limit.
