### ISSUE TITLE
LuaJIT crash coredump

### ISSUE THREAD

**Issue by dengchenjin** [LuaJIT/LuaJIT#474]
#2  <signal handler called>
No symbol table info available.
#3  hashmask (L=0x409c1378, t=0x71, key=0x7fffdfd55200) at lj_tab.c:23
        n = <error reading variable n (Cannot access memory at address 0x85)>
#4  lj_tab_getstr (L=0x409c1378, t=0x71, key=0x7fffdfd55200) at lj_tab.c:376
        n = <value optimized out>
#5  lj_tab_get (L=0x409c1378, t=0x71, key=0x7fffdfd55200) at lj_tab.c:387
        tv = 0x41c45a50
#6  0x00007f5f4d5598b6 in fwd_ahload (J=0x409c1550, xref=32916) at lj_opt_mem.c:192
        keyv = {u64 = 18446744053338102352, n = -nan(0xffffb41c45a50), {{gcr = {gcptr32 = 1103387216}, i = 1103387216}, it = 4294967291}, fr = {func = {gcptr32 = 1103387216}, tp = {
              ftsz = -5, pcr = {ptr32 = 4294967291}}}, u32 = {lo = 1103387216, hi = 4294967291}}
        tv = <value optimized out>
        key = <value optimized out>
        ir = 0x43787668
        tab = 32871
        xr = 0x437877d0
        lim = 32916
        ref = 0
#7  0x00007f5f4d559920 in lj_opt_fwd_hload (J=0x409c1550) at lj_opt_mem.c:253
        ref = 1103387216
#8  0x00007f5f4d55afff in lj_opt_fold (J=0x409c1550) at lj_opt_fold.c:2218
        k = <value optimized out>
        h = <value optimized out>
        fh = <value optimized out>
        key = 8578048
        any = 1047552
        ref = <value optimized out>
#9  0x00007f5f4d55e494 in loop_unroll (L=<value optimized out>, dummy=<value optimized out>, ud=0x409c1550) at lj_opt_loop.c:322
        ref = <value optimized out>
        ir = <value optimized out>
        op1 = <value optimized out>
---Type <return> to continue, or q <return> to quit---
        op2 = <value optimized out>
        loopsnap = <value optimized out>
        loopmap = 0x45bd1b84
        psentinel = 0x45bd1b94
        phi = {32910, 32871, 0, 0, 29542, 17272, 0, 0, 29646, 17272, 0, 0, 30326, 17272, 0, 0, 5896, 16540, 0, 0, 30230, 17272, 0, 0, 5900, 16540, 0, 0, 5902, 16540, 0, 0, 30630, 
          17272, 0, 0, 29550, 17272, 0, 0, 30238, 17272, 0, 0, 29510, 17272, 0, 0, 5912, 16540, 0, 0, 29502, 17272, 0, 0, 5916, 16540, 0, 0, 5918, 16540, 0, 0}
        nphi = <value optimized out>
        ins = <value optimized out>
        invar = 32911
        subst = 0x4765aba8
        onsnap = 7
        osnap = 0x4635be98
#10 cploop_opt (L=<value optimized out>, dummy=<value optimized out>, ud=0x409c1550) at lj_opt_loop.c:400
No locals.
#11 0x00007f5f4d5410dc in lj_vm_cpcall () from /ball/pf/libluajit-5.1.so.2
No symbol table info available.
#12 0x00007f5f4d55e10d in lj_opt_loop (J=<value optimized out>) at lj_opt_loop.c:410
        nins = 32911
        nsnap = 7
        nsnapmap = 64
        errcode = <value optimized out>
#13 0x00007f5f4d578aa3 in trace_state (L=0x409c1378, dummy=<value optimized out>, ud=0x409c1550) at lj_trace.c:599
        J = 0x409c1550
#14 0x00007f5f4d5410dc in lj_vm_cpcall () from /ball/pf/libluajit-5.1.so.2
No symbol table info available.
#15 0x00007f5f4d5779cf in lj_trace_ins (J=0x409c1550, pc=<value optimized out>) at lj_trace.c:647
No locals.
#16 0x00007f5f4d54a71d in lj_dispatch_ins (L=0x409c1378, pc=0x4190d848) at lj_dispatch.c:399
        J = <value optimized out>
        olderr = 11
        fn = <value optimized out>
        pt = <value optimized out>
        cf = 0x7fffdfd55200
        oldpc = <value optimized out>
        g = 0x409c13b8
        slots = <value optimized out>
#17 0x00007f5f4d542763 in lj_vm_inshook () from /ball/pf/libluajit-5.1.so.2
No symbol table info available.
#18 0x00007f5f4d54cb00 in lua_pcall (L=<value optimized out>, nargs=<value optimized out>, nresults=<value optimized out>, errfunc=<value optimized out>) at lj_api.c:1052
        g = 0x409c13b8
---Type <return> to continue, or q <return> to quit---
        oldh = 0 '\000'
        ef = <value optimized out>
        status = <value optimized out>
#19 0x00007f5f4e67e1e7 in LuaEngine::ExecuteLua (this=0x7ffefffffffb) at lua_engine.cpp:1478
        packet = {m_pObject = 0x7f5effb4e754}
        errmsg = {px = 0x7fff00000003 <Address 0x7fff00000003 out of bounds>, pn = {pi_ = 0x2392d70}}
        cookie = 552800254
        message = 0x1d1c0e8 "MSG_DBA_RESULT"
        ret = -539666768
        para_count = 3
        fd = <value optimized out>
        __ShinyZone_EXECUTE_LUA_FUNC = {next = 0x0, _state = 0, name = 0x7f5f4e68e98e "EXECUTE_LUA_FUNC", data = {entryCount = {cur = 0, avg = 0}, selfTicks = {cur = 0, avg = 0}, 
            childTicks = {cur = 0, avg = 0}}}
        status = <value optimized out>
        err_index = -5
        elem = {px = 0x23955b0, pn = {pi_ = 0x1ca0880}}
        i = <value optimized out>
        __ShinyZoneFunc = {next = 0x0, _state = 0, name = 0x7f5f4e68ecaa "ExecuteLua", data = {entryCount = {cur = 0, avg = 0}, selfTicks = {cur = 0, avg = 0}, childTicks = {
              cur = 0, avg = 0}}}
        __FUNCTION__ = "ExecuteLua"
        tempList = std::vector of length 1, capacity 1 = {{px = 0x23955b0, pn = {pi_ = 0x1ca0880}}}
        costTime = <value optimized out>
        beginTime = 552800254
        size = 1
        __ShinyZone_ExecuteLuaClear = {next = 0x0, _state = 0, name = 0x7f5f4e68e9b0 "ExecuteLuaClear", data = {entryCount = {cur = 0, avg = 0}, selfTicks = {cur = 0, avg = 0}, 
            childTicks = {cur = 0, avg = 0}}}
#20 0x00007f5f4e8d3144 in game_run (argc=<value optimized out>, argv=<value optimized out>) at game.cpp:264
        ret = <value optimized out>
        sleep_time = 0
        running = true
        count = <value optimized out>
#21 game (argc=<value optimized out>, argv=<value optimized out>) at game.cpp:309

**Comment by dengchenjin** [comment]
#0  WriteCoreDumpLimited (file_name=0x2394068 "coredump_gs4_2019-01-31_09:53:19.txt", max_length=1073741824) at src/coredumper.c:183
#1  0x00007f5f4e8d1af5 in sig_handler (sig=11, si=<value optimized out>, unused=<value optimized out>) at console_linux.cpp:228
#2  <signal handler called>
#3  hashmask (L=0x409c1378, t=0x71, key=0x7fffdfd55200) at lj_tab.c:23
#4  lj_tab_getstr (L=0x409c1378, t=0x71, key=0x7fffdfd55200) at lj_tab.c:376
#5  lj_tab_get (L=0x409c1378, t=0x71, key=0x7fffdfd55200) at lj_tab.c:387
#6  0x00007f5f4d5598b6 in fwd_ahload (J=0x409c1550, xref=32916) at lj_opt_mem.c:192
#7  0x00007f5f4d559920 in lj_opt_fwd_hload (J=0x409c1550) at lj_opt_mem.c:253
#8  0x00007f5f4d55afff in lj_opt_fold (J=0x409c1550) at lj_opt_fold.c:2218
#9  0x00007f5f4d55e494 in loop_unroll (L=<value optimized out>, dummy=<value optimized out>, ud=0x409c1550) at lj_opt_loop.c:322
#10 cploop_opt (L=<value optimized out>, dummy=<value optimized out>, ud=0x409c1550) at lj_opt_loop.c:400
#11 0x00007f5f4d5410dc in lj_vm_cpcall () from /ball/pf/libluajit-5.1.so.2
#12 0x00007f5f4d55e10d in lj_opt_loop (J=<value optimized out>) at lj_opt_loop.c:410
#13 0x00007f5f4d578aa3 in trace_state (L=0x409c1378, dummy=<value optimized out>, ud=0x409c1550) at lj_trace.c:599
#14 0x00007f5f4d5410dc in lj_vm_cpcall () from /ball/pf/libluajit-5.1.so.2
#15 0x00007f5f4d5779cf in lj_trace_ins (J=0x409c1550, pc=<value optimized out>) at lj_trace.c:647
#16 0x00007f5f4d54a71d in lj_dispatch_ins (L=0x409c1378, pc=0x4190d848) at lj_dispatch.c:399
#17 0x00007f5f4d542763 in lj_vm_inshook () from /ball/pf/libluajit-5.1.so.2
#18 0x00007f5f4d54cb00 in lua_pcall (L=<value optimized out>, nargs=<value optimized out>, nresults=<value optimized out>, errfunc=<value optimized out>) at lj_api.c:1052
#19 0x00007f5f4e67e1e7 in LuaEngine::ExecuteLua (this=0x7ffefffffffb) at lua_engine.cpp:1478
#20 0x00007f5f4e8d3144 in game_run (argc=<value optimized out>, argv=<value optimized out>) at game.cpp:264
#21 game (argc=<value optimized out>, argv=<value optimized out>) at game.cpp:309
#22 0x00007f5f4dee4d1d in __libc_start_main () from /lib64/libc.so.6
#23 0x000000000040a039 in _start ()

**Comment by siddhesh** [comment]
Would you be able to share a program that reproduces this crash?  That will help diagnose the problem.

**Comment by smartlot** [comment]
Same issue, OBS-Studio
