### ISSUE TITLE
DynASM: Why can‘t ldrsb/ldrsh load to odd register in ARM?

### ISSUE THREAD

**Issue by qtiuto** [LuaJIT/LuaJIT#475]
I see no description from the arm instruction set guide or in the source code, and gcc allow the operation.
Any problem in some arm cpu?
[Source code](https://github.com/LuaJIT/LuaJIT/edit/master/dynasm/dasm_arm.lua) is at line 722:
```lua
if (ldrd or oplo == 240) then
    d = band(shr(op, 12), 15)
    if band(d, 1) ~= 0 then werror("odd destination register") end
  end
```
I test odd register on my Android phone, and find no problem. And in your new jit compiler in jit folder, no warning about odd register. I think it may be a test code that you forgot to delete. I hope dynasm is still being maintained.

**Comment by MikePall** [comment]
ARMv-7A Architecture Reference Manual. See the page for LDRD, in particular the ARM encoding (not Thumb2):
```
if Rt<0> == '1' then UNPREDICTABLE;
```
Also QEMU throws an illegal instruction.
