### ISSUE TITLE
ppc32 luajit bss plt incompatible with muslc

### ISSUE THREAD

**Issue by dcrawford1** [LuaJIT/LuaJIT#481]
I am trying to get luajit running on a powerpc 32 target dynamically linked with muslc.   luajit segfaults early in __register_frame_info near got.plt.  I noticed at build time the linker outputs:
```
DYNLINK libluajit.so
../powerpc-buildroot-linux-musl/bin/ld: bss-plt forced due to lj_vm.o
```
It looks like luajit-2.0.5/src/lj_vm.s is forcing the linker to use the older bss-plt. But, musl only supports secure-plt.  Here is the response when I asked this question on the musl mailing list:

> That's correct. The difference in ABI is that the secure-plt form
> requires a particular GOT register to be loaded as part of the
> contract for calling a PLT entry. The function calls in the asm (and
> in jit-generated code, if it calls to C functions) need to be modified
> to either follow the secureplt ABI, or better yet, not to use the PLT
> at all, and instead just load the function address from the GOT and
> perform an indirect call/jmp to it (this is considerably more
> efficient than using a PLT anyway).
>
> Rich

**Comment by MikePall** [comment]
PPC32 support will be removed soon, anyway.
