### ISSUE TITLE
How to disable tail call optimizations?

### ISSUE THREAD

**Issue by svermeulen** [LuaJIT/LuaJIT#487]
In some cases I would love to be able to temporarily turn off tail call optimizations, so that error stack traces are more complete.  How would I go about this?   I've been poking around in the code but can't make heads or tails of it (no pun intended)

**Comment by fsfod** [comment]
I just resorted to turning them off in the parser like this https://github.com/fsfod/LuaJIT/commit/79c70043073e97bb60c11e1a53b4fd0d2e940150. You could just edit your code to wrap the return value in parentheses to disable just a specific tail call, this only works if the code is returning a single value.

**Comment by svermeulen** [comment]
Can confirm that code change works like a charm!  Thanks very much

**Comment by AGulev** [comment]
@fsfod do you know a way to do the same for C-calls? I need to turn it off for debug purposes as well.
