### ISSUE TITLE
JIT non-closures (IIFEs)

### ISSUE THREAD

**Issue by SoniEx2** [LuaJIT/LuaJIT#491]
I have the following (auto-generated) code:

```lua
(function(t, k, k2, ...) return t[k][k2](t, ...) end)(t, k, "k2", ...)
```

which comes from (not lua):

```text
t:[k].k2(...)
```

and I need this to be JITted because I use it a lot.

**Comment by SoniEx2** [comment]
this is publicly released now: https://marc.info/?l=lua-l&m=156458156026332&w=2

it seems there's still no JIT support for these, which sucks. :(

**Comment by MikePall** [comment]
DUP of #106

**Comment by SoniEx2** [comment]
wait, this isn't #106. that one is about creating closure objects.

**Comment by sharpobject** [comment]
Can we reopen this, since it's distinct from #106 and #106 was closed by the reporter?
