### ISSUE TITLE
prime is sometimes not prime bug

### ISSUE THREAD

**Issue by achan001** [LuaJIT/LuaJIT#493]
I recently did the code for [isprime(n) ](https://github.com/achan001/PrimePi/blob/master/nextprime.lua)

Got this weird result for Luajit (but run ok for old Luajit 1.18, and plain Lua)

> LuaJIT 2.0.4 -- Copyright (C) 2005-2015 Mike Pall. http://luajit.org/
> JIT: ON CMOV SSE2 SSE3 SSE4.1 fold cse dce fwd dse narrow loop abc sink fuse
> p = require 'nextprime'
> n = 165276799 -- a prime
> for i=1,8 do print(p.isprime(n)) end
true
true
true
true
false
false
false
false

After some diggiing, isolate the weird result in sqrmod, but that is also very weird:
I replaced the constants such as 2^26 as 67108864, but no changes to result.

> LuaJIT 2.0.4 -- Copyright (C) 2005-2015 Mike Pall. http://luajit.org/
> JIT: ON CMOV SSE2 SSE3 SSE4.1 fold cse dce fwd dse narrow loop abc sin
```
function sqrmod(a, n) -- a^2 (mod n)
   local b = a * a
   if b < 9007199254740992 then return b%n end
   if a > 6369051764850687 then a=n-a end
   b = a % 67108864
   a = a - b
   a = (a * a) % n - n + (2 * a * b) % n
   if a <= 4503599761588223 then return (a + b * b) % n end
   return (a - n + b * b) % n
end

>
> a, m, i = 158626126, 165276799, 0
> x = sqrmod(a, m)
> print(x)
74404549
>
> repeat y = sqrmod(a, m); i=i+1 until x ~= y; print(y, i)
74404548        57
> repeat y = sqrmod(a, m); i=i+1 until x ~= y; print(y, i)
74404548        114
> repeat y = sqrmod(a, m); i=i+1 until x ~= y; print(y, i)
74404548        116
> repeat y = sqrmod(a, m); i=i+1 until x ~= y; print(y, i)
74404548        117
> repeat y = sqrmod(a, m); i=i+1 until x ~= y; print(y, i)
74404548        118
>
> x = y -- when it flip back ???
> repeat y = sqrmod(a, m); i=i+1 until x ~= y; print(y, i)
74404549        174

**Comment by achan001** [comment]
Tried the latest **LuaJIT 2.1.0-beta3**
sqrmod(158626126, 165276799) still wrong, returning 74404548
The good news is the bad result do not flip, and stay bad all the time.

Doing the math step by step, found the issue:
> a = 2^54
> n = 165276799
> = a % n, math.fmod(a, n)
87517308        87517309

**Comment by achan001** [comment]
I just remembered I patched **Luajit 1.18** to do % correctly, months ago :-)

luaconf.h:

```
/* #define luai_nummod(a,b)  ((a) - floor((a)/(b))*(b)) */
#define luai_nummod(a,b) ({double _m=fmod((a),(b)); if (signbit((_m)*(b)) && _m) _m+=(b); _m;})
```
Is there a way to patch the newer Luajit 2.x versions ?

**Comment by vanc** [comment]
It's a generic issue in Lua 5.1.

**Comment by SuperUserNameMan** [comment]
@achan001 : why have you closed this issue ? 
does your patch work with Luajit 2.x ?
https://github.com/LuaJIT/LuaJIT/blob/f0e865dd4861520258299d0f2a56491bd9d602e1/src/host/minilua.c#L151

**Comment by achan001** [comment]
@SuperUserNameMan : No, my patch does not work for Luajit 2.x

However, I felt this might be labelled by Mike as WONT-FIX. (to be compatible with Lua 5.1)

With so many other issues on this list, I closed this for now ...
