### ISSUE TITLE
Create project commit (decentralization)

### ISSUE THREAD

**Issue by SoniEx2** [LuaJIT/LuaJIT#496]
LuaJIT is, effectively, dead. As such I believe it would be beneficial to create a "project commit", as described here: https://cybre.tech/SoniEx2/ganarchy#usage

This project commit is key to allowing LuaJIT development to continue in a decentralized fashion. Since LuaJIT development has stopped completely in the current centralized way it's set up, I believe this would be extremely beneficial to LuaJIT. This requires very little effort from the LuaJIT maintainers and only involves running `git commit --allow-empty` and setting it up with the following details:

```text
[Project] LuaJIT

LuaJIT is a Just-In-Time Compiler (JIT) for the Lua programming language. Lua is a powerful, dynamic and light-weight programming language. It may be embedded or used as a general-purpose, stand-alone language.
```

(Feel free to adjust as desired.)

**Comment by vcunat** [comment]
> This project commit is key to allowing LuaJIT development to continue in a decentralized fashion.

I really fail to see how it could help moving LuaJIT forward, even after reading the description.

**Comment by SoniEx2** [comment]
oh, I believe that by not having a central authority, it would be easier to contribute to the project, as such more ppl would be willing to do it and it'd never stop being developed.

**Comment by SoniEx2** [comment]
unlike the current state where nobody does anything because they feel discouraged by the fact that development has mostly stopped/patches aren't getting accepted and stuff.

**Comment by rzr** [comment]
May the project would be interested into co maintenance in this "Best effort" organization:
https://abandonware.github.io/

**Comment by rzr** [comment]
Alternative repo:
https://github.com/openresty/luajit2
