### ISSUE TITLE
Better pointer hash

### ISSUE THREAD

**Issue by MikePall** [LuaJIT/LuaJIT#5]
The pointer hash leaves something to be desired. However the constraints on acceptable hash functions are very strict. Not just for performance, but also for instruction space, since this is inlined in lots of places, including JIT-compiled code.

Changing the pointer hash affects: performance (hah!), inlined hash constants in C switch statements, all JIT backends.

There have been previous discussions on the mailing list with (so-so) benchmarks. TODO: gather all links.

**Comment by drbo** [comment]
Two questions:

- Does the hash need to be deterministic?
- Is clustering a problem?
- Can a random 64-bit number be generated at startup?

If the answer to the first two questions is "no", and the answer to the third is "yes", it is possible to use a very simple "universal hash" that (provably!) solves the problem.

**Comment by MikePall** [comment]
While on a tangential investigation:

CRC32 is available on many x86/x64 and ARM/ARM64 CPUs nowadays. The latency isn't too bad (3 cycles). But at least for pointers the hash quality is lower than the current ARX pointer hash. I tried quite a few variations. This is a surprising result and I have no good explanation.

**Comment by MikePall** [comment]
Real-world code doesn't need use it that much. The hash is 'good enough' for the remaining cases.
