### ISSUE TITLE
LuaJIT 2.1.0-beta3 - X64 - Crash when "not enough memory"

### ISSUE THREAD

**Issue by NgaiShunChan** [LuaJIT/LuaJIT#501]
The following code can reproduce crash on win7/10 x64 when running out of memory . It seems that lj_err_unwind_win can't catch exception raise by err_raise_ext.
```
local function crash()
    local a = {}
    while(true) do
        table.insert(a, 'teststr')
    end
end

crash()
```

**Comment by siddhesh** [comment]
I'm happy to accept patches in my fork: https://github.com/siddhesh/LuaJIT.git

**Comment by MikePall** [comment]
Fixed.
