### ISSUE TITLE
how to compile Android lib on Windows?

### ISSUE THREAD

**Issue by RPG3D** [LuaJIT/LuaJIT#502]
got error on Cygwin

`export NDK=D:/AndroidSDK/ndk-bundle
export NDKABI=21
export NDKVER=$NDK/toolchains/arm-linux-androideabi-4.9
export NDKP=$NDKVER/prebuilt/windows-x86_64/bin/arm-linux-androideabi-
export NDKF="--sysroot $NDK/platforms/android-$NDKABI/arch-arm"
export NDKARCH="-march=armv7-a -mfloat-abi=softfp -Wl,--fix-cortex-a8"
export NDK_MAKE=$NDK/prebuilt/windows-x86_64/bin/make.exe
make HOST_CC="gcc -m32" CROSS=$NDKP TARGET_FLAGS="$NDKF $NDKARCH" TARGET_SYS="Linux" clean default`

**Comment by RPG3D** [comment]
$ sh buildAndroid.sh
D:/AndroidSDK/ndk-bundle/prebuilt/windows-x86_64/bin/make -C src clean
make[1]: Entering directory `D:/VSProject/LuaJIT-2.1.0-beta3/src'
make[1]: Leaving directory `D:/VSProject/LuaJIT-2.1.0-beta3/src'
process_begin: CreateProcess(NULL, D:android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-clang -O2 -fomit-frame-pointer -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -U_FORTIFY_SOURCE --sysroot D:android-ndk-r14b/platforms/android-16/arch-arm -march=armv7-a -mfloat-abi=softfp -Wl,--fix-cortex-a8 -E lj_arch.h -dM, ...) failed.
process_begin: CreateProcess(NULL, D:android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-clang -O2 -fomit-frame-pointer -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -U_FORTIFY_SOURCE --sysroot D:android-ndk-r14b/platforms/android-16/arch-arm -march=armv7-a -mfloat-abi=softfp -Wl,--fix-cortex-a8 -E lj_arch.h -dM, ...) failed.
process_begin: CreateProcess(NULL, D:android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-clang -O2 -fomit-frame-pointer -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -U_FORTIFY_SOURCE --sysroot D:android-ndk-r14b/platforms/android-16/arch-arm -march=armv7-a -mfloat-abi=softfp -Wl,--fix-cortex-a8 -E lj_arch.h -dM, ...) failed.
process_begin: CreateProcess(NULL, D:android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-clang -O2 -fomit-frame-pointer -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -U_FORTIFY_SOURCE --sysroot D:android-ndk-r14b/platforms/android-16/arch-arm -march=armv7-a -mfloat-abi=softfp -Wl,--fix-cortex-a8 -E lj_arch.h -dM, ...) failed.
process_begin: CreateProcess(NULL, D:android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-clang -O2 -fomit-frame-pointer -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -U_FORTIFY_SOURCE --sysroot D:android-ndk-r14b/platforms/android-16/arch-arm -march=armv7-a -mfloat-abi=softfp -Wl,--fix-cortex-a8 -E lj_arch.h -dM, ...) failed.
process_begin: CreateProcess(NULL, D:android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-clang -O2 -fomit-frame-pointer -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -U_FORTIFY_SOURCE --sysroot D:android-ndk-r14b/platforms/android-16/arch-arm -march=armv7-a -mfloat-abi=softfp -Wl,--fix-cortex-a8 -E lj_arch.h -dM, ...) failed.
Makefile:268: *** Unsupported target architecture.  Stop.

**Comment by MikuAuahDark** [comment]
Those spamming `CreateProcess(NULL, ...) failed` looks like your environment is not setup correctly.
