### ISSUE TITLE
Fold machinery misses data dependency

### ISSUE THREAD

**Issue by sergos** [LuaJIT/LuaJIT#505]
The folder makes incorrect transformation as a result of **kfold_strref_snew** 
For a simple test of 
```
jit.opt.start("hotloop=1")`
for _ = 1, 20 do
  local value = "abc"
  local pos_c = string.find(value, "c", 1, true)
  local value2 = string.sub(value, 1, pos_c - 1)
  local pos_b = string.find(value2, "b", 2, true)
  assert(pos_b == 2, "FAIL: position of 'b' is " .. pos_b)
end

print("OK")
```
The transformation leads to a mess with pointer arithmetics later on (IR after folding)
```
0028    str SNEW   [0x41a85030]  0020
0029 >  int UGE    0020  +1
0030    p32 STRREF 0028  +1
0031    int ADD    0020  -1
0035    p32 CALLN  lj_str_find  (0030 [0x41a85260] 0031 +1  )
0036 >  p32 NE     0035  NULL
0037    int SUB    0035  [0x41a85030]
0038    int ADD    0037  +1
0039 >  p32 HREFK  0006  "assert" @3
```

The 0037 subtracts original string pointer [0x41a85030] from the result of SNEW operation obtained through 0035 -> 0030 -> 0028

**Comment by sergos** [comment]
Tracked down to emit of IR for the string find at lj_ffrecord.c:942-952:

    TRef trsptr = emitir(IRT(IR_STRREF, IRT_PGC), trstr, trstart);
    TRef trpptr = emitir(IRT(IR_STRREF, IRT_PGC), trpat, tr0);
    TRef trslen = emitir(IRTI(IR_SUB), trlen, trstart);
    TRef trplen = emitir(IRTI(IR_FLOAD), trpat, IRFL_STR_LEN);
    TRef tr = lj_ir_call(J, IRCALL_lj_str_find, trsptr, trpptr, trslen, trplen);
    TRef trp0 = lj_ir_kkptr(J, NULL);
    if (lj_str_find(strdata(str)+(MSize)start, strdata(pat),
                    str->len-(MSize)start, pat->len)) {
      TRef pos;
      emitir(IRTG(IR_NE, IRT_PGC), tr, trp0);
      pos = emitir(IRTI(IR_SUB), tr, emitir(IRT(IR_STRREF, IRT_PGC), trstr, tr0));

The problem is the last statement. The intention was to generate the subtraction of tr position (taken off the **trstr** through the trsptr) and the 0 position of the **trstr**. 

In the Lua test above the **trstr** is a string obtained from the SNEW operation and fold machinery considers it possible to substitute the STRREF (trstr, 0) - pointer to the head of the SNEW result - with pointer to the head of the original string. IMHO this is incorrect per se, since we make folding ahead of emission of the future STRREF and can't guarantee consistency. 

So, the fold **kfold_strref_snew** should be removed.

**Comment by mraleph** [comment]
I think it's `recff_string_find` mistake to not accommodate for the folding rules. 

I would propose to fix this like so

```
diff --git a/src/lj_ffrecord.c b/src/lj_ffrecord.c
index 849d7a2..c0a171b 100644
--- a/src/lj_ffrecord.c
+++ b/src/lj_ffrecord.c
@@ -939,17 +939,24 @@ static void LJ_FASTCALL recff_string_find(jit_State *J, RecordFFData *rd)
   if ((J->base[2] && tref_istruecond(J->base[3])) ||
       (emitir(IRTG(IR_EQ, IRT_STR), trpat, lj_ir_kstr(J, pat)),
        !lj_str_haspattern(pat))) {  /* Search for fixed string. */
-    TRef trsptr = emitir(IRT(IR_STRREF, IRT_PGC), trstr, trstart);
+    /*
+    ** Caveat: STRREF is not guaranteed to return a pointer into its operand
+    ** due to folding - however for pointer arithmetic below we want to make
+    ** sure that we substract pointers that point into the same string. Hence
+    ** the double STRREF.
+    */
+    TRef trstartptr = emitir(IRT(IR_STRREF, IRT_PGC), trstr, tr0);
+    TRef trsearchptr = emitir(IRT(IR_STRREF, IRT_PGC), trstartptr, trstart);
     TRef trpptr = emitir(IRT(IR_STRREF, IRT_PGC), trpat, tr0);
     TRef trslen = emitir(IRTI(IR_SUB), trlen, trstart);
     TRef trplen = emitir(IRTI(IR_FLOAD), trpat, IRFL_STR_LEN);
-    TRef tr = lj_ir_call(J, IRCALL_lj_str_find, trsptr, trpptr, trslen, trplen);
+    TRef tr = lj_ir_call(J, IRCALL_lj_str_find, trsearchptr, trpptr, trslen, trplen);
     TRef trp0 = lj_ir_kkptr(J, NULL);
     if (lj_str_find(strdata(str)+(MSize)start, strdata(pat),
                    str->len-(MSize)start, pat->len)) {
       TRef pos;
       emitir(IRTG(IR_NE, IRT_PGC), tr, trp0);
-      pos = emitir(IRTI(IR_SUB), tr, emitir(IRT(IR_STRREF, IRT_PGC), trstr, tr0));
+      pos = emitir(IRTI(IR_SUB), tr, trstartptr);
       J->base[0] = emitir(IRTI(IR_ADD), pos, lj_ir_kint(J, 1));
       J->base[1] = emitir(IRTI(IR_ADD), pos, trplen);
       rd->nres = 2;
```

or even more bullet-proof

```
diff --git a/src/lj_ffrecord.c b/src/lj_ffrecord.c
index 849d7a2..e879c2a 100644
--- a/src/lj_ffrecord.c
+++ b/src/lj_ffrecord.c
@@ -949,8 +949,9 @@ static void LJ_FASTCALL recff_string_find(jit_State *J, RecordFFData *rd)
                    str->len-(MSize)start, pat->len)) {
       TRef pos;
       emitir(IRTG(IR_NE, IRT_PGC), tr, trp0);
-      pos = emitir(IRTI(IR_SUB), tr, emitir(IRT(IR_STRREF, IRT_PGC), trstr, tr0));
-      J->base[0] = emitir(IRTI(IR_ADD), pos, lj_ir_kint(J, 1));
+      /* Caveat: can't use STRREF trstr 0 here because that might be pointing into a wrong string due to folding. */
+      pos = emitir(IRTI(IR_SUB), tr, trsptr);
+      J->base[0] = emitir(IRTI(IR_ADD), pos, emitir(IRTI(IR_ADD), trstart, lj_ir_kint(J, 1)));
       J->base[1] = emitir(IRTI(IR_ADD), pos, trplen);
       rd->nres = 2;
     } else {
```

In the second fix we are guaranteed to do pointer arithmetic on the right pointers.

**Comment by sergos** [comment]
I have a question - how many more places are not accommodate to this folding rule, as you mentioned?
Also, how can we be sure that the code appeared as a result of `recff_string_find` will not appear as a result of other foldings? 

The fix you propose will resolve this particular symptohm, but will not cure the disease itself - the folder will cause the same pointer substitution for constant offset `STRREF` and will not do the same for `STRREF` with variable offset hence, results will point into different strings.

**Comment by mraleph** [comment]
It's a valid question - I asked it myself: fortunately it `STRREF` occurs only 24 times in the whole code base, so it is easy to review all those places and see if any of them are incorrect. Fortunately it does not seem like any other places need to be fixed. Search also reveals that there was at least one more bug when @MikePall  himself failed to accommodate for STRREF-SNEW folding (see 3eeb7d3aa02259e93db6e4816909e80acb57f8f8). 

So ultimately I think this boils down to a very simple choice - would one like to make generated code worse or would one like to have a potential footgun in the IR. I think footgun would be smaller if IR had clear documentation which stated that STRREF does not necessarily return a pointer into the same string given to it as operand. (in reality I think this is a very minor footgun though - pointer identity should matter very rarely).

So I am in favor of lading the fix I proposed (the second variant) because I believe it actually fixes the problem, rather than the symptom.

**Comment by sergos** [comment]
Correct me if I'm wrong: all `STRREF`s and **_all their uses_** appear as part of one bytecode instruction generation, so that the pointer never live out into code that was not inspected.

Also, out of these 24 places - is there any opportunity left for the folder to succeed?

**Comment by mraleph** [comment]
There are only 6 places where STRREF is generated during recording. Out of those 6 - 5 flow into `XLOAD` or a call to a C-function (fwrite, lj_str_find). One flows into `SNEW` - from where it could "leak" outside if `(STRREF (SNEW (STRREF ...)) 0)` gets folded to inner `STRREF`, but that is benign by induction (because we inspected all other uses of `STRREF`. If you don't trust my judgement I suggest greping through `lj_ffrecord.c` to inspect all of them for yourself.

Out of those 6 places folding can succeed in any of them.

**Comment by sergos** [comment]
Please, don't get me wrong: I'm not trying to undermine anyone's expertise. I hope I will ask a question that will lead you - or @MikePall - to a correct solution. 

My point was that currently folder may change semantics by substitution of one string with another. If this happens with arbitrary pointer arithmetics code available later on, then we will face similar problem eventually. If no pointers leave into arbitrary code - we're safe. This is what I derive from your explanation.

Another problem I expect: if a new folder rule/IR generation will be introduced it can break the solution. You explained that clear documentation of `STRREF` use should prevent this from appearing in the future.

Given that I completely satisfied with your patch #2 - if my humble opinion has any weight in this universe.

Thanks for looking into this!

**Comment by sergos** [comment]
@mraleph we found a problem with the patch you provided after some testing.
Obviously, as we change the meaning of pos, we have to do the same for the 2nd returning argument.
Please, consider:

```diff
diff --git a/src/lj_ffrecord.c b/src/lj_ffrecord.c
index 632b8f2..22b36d2 100644
--- a/src/lj_ffrecord.c
+++ b/src/lj_ffrecord.c
@@ -952,7 +952,7 @@ static void LJ_FASTCALL recff_string_find(jit_State *J, RecordFFData *rd)
       /* Caveat: can't use STRREF trstr 0 here because that might be pointing into a wrong string due to folding. */
       pos = emitir(IRTI(IR_SUB), tr, trsptr);
       J->base[0] = emitir(IRTI(IR_ADD), pos, emitir(IRTI(IR_ADD), trstart, lj_ir_kint(J, 1)));
-      J->base[1] = emitir(IRTI(IR_ADD), pos, trplen);
+      J->base[1] = emitir(IRTI(IR_ADD), pos, emitir(IRTI(IR_ADD), trplen, trstart));
       rd->nres = 2;
     } else {
       emitir(IRTG(IR_EQ, IRT_PGC), tr, trp0);

**Comment by mraleph** [comment]
@sergos yeah, I completely missed that `pos` is used twice in the code. I would maybe write it a bit differently and easier to read

```
       pos = emitir(IRTI(IR_SUB), tr, trsptr);
       pos = emitir(IRTI(IR_ADD), pos, trstart);
       J->base[0] = emitir(IRTI(IR_ADD), pos, lj_ir_kint(J, 1));
       J->base[1] = emitir(IRTI(IR_ADD), pos, trplen);
```

**Comment by siddhesh** [comment]
Hi, I've incorporated your patches and test into my repo.  Thanks!

**Comment by MikePall** [comment]
Fixed. Thanks!
