### ISSUE TITLE
Android 64bit device crash when jit.on

### ISSUE THREAD

**Issue by shiminDu** [LuaJIT/LuaJIT#506]
our app use LuaJIT-2.1.0-beta3 for Android arm64-v8a,the app will crash

engine->executeString("release_print(jit.status())");

[LUA-print] true fold cse dce fwd dse narrow loop abc sink fuse

07-26 11:52:06.947 20307 20307 F DEBUG : Build fingerprint: 'Xiaomi/hydrogen/hydrogen:7.0/NRD90M/V10.2.2.0.NBCCNXM:user/release-keys'
07-26 11:52:06.948 20307 20307 F DEBUG : Revision: '0'
07-26 11:52:06.948 20307 20307 F DEBUG : ABI: 'arm64'
07-26 11:52:06.949 20307 20307 F DEBUG : pid: 20215, tid: 20235, name: GLThread 1513 >>> org.cocos2dx.xxxxx <<<
07-26 11:52:06.949 20307 20307 F DEBUG : signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x7f86216b9c
07-26 11:52:06.949 20307 20307 F DEBUG : x0 0000000000000020 x1 0000007f7e610408 x2 00000000fff90000 x3 0000000000000000
07-26 11:52:06.949 20307 20307 F DEBUG : x4 0000000000000000 x5 0000007f7e6100a8 x6 0000000000000021 x7 000000007ffffffe
07-26 11:52:06.949 20307 20307 F DEBUG : x8 0000000000000020 x9 0000000000000021 x10 0000000000000000 x11 0000000000000020
07-26 11:52:06.949 20307 20307 F DEBUG : x12 000000007ffffffe x13 fff9000000000000 x14 fff9000000000000 x15 0000007f88590720
07-26 11:52:06.949 20307 20307 F DEBUG : x16 0000007f88030668 x17 0000007fa707afc0 x18 0000000000000022 x19 0000007f7ebb5e70
07-26 11:52:06.949 20307 20307 F DEBUG : x20 fffd807f86298518 x21 fffd807f86296830 x22 0000007f862933d8 x23 0000007f7e610408
07-26 11:52:06.949 20307 20307 F DEBUG : x24 0000000040000000 x25 0000000000000000 x26 0000000000000020 x27 41e0000000000000
07-26 11:52:06.949 20307 20307 F DEBUG : x28 fffffffffffffff4 x29 0000007f88590800 x30 fff9000000000000
07-26 11:52:06.949 20307 20307 F DEBUG : sp 0000007f885907f0 pc 0000007f86216b9c pstate 0000000020000000

but when I call engine->executeString("jit.off()");

the app can work well without crash

Does LJ_GC64 can only use interpreter on Android 64Bit device?

The same apk can work well on Android 32Bit device with jit.on

 I have tried to use the luajit 2.1 latest  codes, the problem still exists

**Comment by siddhesh** [comment]
I have some fixes in aarch64 on my fork:

https://github.com/siddhesh/LuaJIT/

Please test with that and see if it works.  If not, please share a reproducer program to help diagnose the problem.
