### ISSUE TITLE
LuaJIT segfault in debug.getinfo()

### ISSUE THREAD

**Issue by sergos** [LuaJIT/LuaJIT#509]
Issuing the following 
``` 
debug.getinfo(1, '>S') 
```
causes segmentation fault both in the interactive interpreter and through command line chunk.

The reason is: '>' in the expects to have an extra argument on stack, so the code unconditionally fails on an assertion (in debug mode) or pop from stack and crashes later on.

**Comment by ImagicTheCat** [comment]
PUC Lua 5.1.5 has the same issue; I don't think the debug library is something you can guarantee to be safe.

**Comment by MikePall** [comment]
Fixed. Thanks!
