### ISSUE TITLE
Profiler hook not called with Lua cdata finalizers

### ISSUE THREAD

**Issue by jdesgats** [LuaJIT/LuaJIT#512]
When enabling the profiler on a rather big code base, I've seen LuaJIT crashing randomly. While looking at core dumps, I noticed that every time it was calling the profile hook on top of the garbage collector when it was calling a Lua cdata finalizer. Here is a call stack sample:

```Core Dump: Program terminated with signal SIGSEGV, Segmentation fault.
#0  lj_debug_funcname (L=L@entry=0x7fe15ef10378, frame=<optimized out>, frame@entry=0x7fe02ac67740, name=name@entry=0x7ffceb8943e8) at lj_debug.c:303
  ?, in ??
  ?, in ??
  ?, in lj_vm_exit_handler
  File "lj_trace.c", line 875, in lj_trace_exit
  File "lj_gc.c", line 689, in lj_gc_step
  File "lj_gc.c", line 659, in gc_onestep
  File "lj_gc.c", line 509, in gc_finalize
  File "lj_gc.c", line 475, in gc_call_finalizer
  ?, in lj_vm_profhook
  File "lj_dispatch.c", line 549, in lj_dispatch_profile
  File "lj_profile.c", line 139, in lj_profile_interpreter
  File "MY OWN C-BASED PROFILER", line 638, in xxxxx
  File "lj_profile.c", line 363, in luaJIT_profile_dumpstack
  File "lj_debug.c", line 596, in lj_debug_dumpstack
  File "lj_debug.c", line 303, in lj_debug_funcname
```

I wrote that small minimal script:

```lua
local ffi = require "ffi"
local profile = require "jit.profile"
local luagc = arg[1] ~= nil

if luagc then print("enable Lua finalizer") end

local created, destroyed= 0, 0

profile.start("li100", function(thread, samples, vmstate)
  local stack = profile.dumpstack(thread, "lZ;", 10)
  print("HOOK", created, destroyed, samples, vmstate, stack)
end)

local ctype = ffi.metatype("struct { int i; }", {
   __gc = luagc and function() destroyed = destroyed + 1 end or nil
})

while true do
   ctype(created)
   local a = {}
   created = created + 1
   if created % 1e7 == 0 then
      print("LOOP", created, destroyed)
   end
end
```

When called with an argument, it will setup a Lua finalizer for the cdata objects, otherwise, it the cdata objects are just freed normally.

Running it doesn't crash not my laptop (commit f0e865dd4861, Linux x86-64). However the profiling callback stops getting called very quickly **only when the Lua finalizer is enabled**:

```
$ ./luajit luagc-simple.lua on
enable Lua finalizer
HOOK	471211	470449	1	N	luagc-simple.lua:20;@0x55aebf1e01c0
HOOK	934494	933549	1	N	luagc-simple.lua:20;@0x55aebf1e01c0
HOOK	1399852	1398898	1	N	luagc-simple.lua:20;@0x55aebf1e01c0
HOOK	1864415	1863412	1	N	luagc-simple.lua:20;@0x55aebf1e01c0
HOOK	2324106	2323411	1	C	luagc-simple.lua:15;luagc-simple.lua:20;@0x55aebf1e01c0
LOOP	10000000	9999366
LOOP	20000000	19999059
LOOP	30000000	29999842
^CHOOK	31672772	31672031	111	C	luagc-simple.lua:19;@0x55aebf1e01c0
./luajit: luagc-simple.lua:19: interrupted!
stack traceback:
	luagc-simple.lua:19: in main chunk
	[C]: at 0x55aebf1e01c0
```

Switching GC64 on and off doesn't seem to have any effect. It looks like the `G(L)->hookmask` attribute gets corrupted at some point, causing the callback to not be called. I tried to attach a debugger after the callback stopped being called, the value of the `hookmask` was alterning between `HOOK_PROFILE` (128) and `HOOK_ACTIVE|HOOK_GC|HOOK_PROFILE` (209).

Another detail: we can see that after I pressed `Ctrl+C`, the hook got called one last time with a high sample count.

I don't know either if the crashes I've seen on our bigger code base are related, I keep digging into that. Happy to provide more details to help narrowing this down.

**Comment by jdesgats** [comment]
I did a few more tests:

* The hook keeps being called when using a C function as `__gc` callback (either FFI of standard C API)
* Setting a Lua function as `__gc` of a regular userdata also triggers this bug (tested with `newproxy`)
* This bug also exists on ARM64 (I can't easily test other architectures)

**Comment by jdesgats** [comment]
While digging further, I seen that the profiler hook stopped being called after being called while a Lua finalizer was running.

From my understanding the `hookmask` and the dispatch table can end up being out-of-sync in this case. I managed to fix the issue by not calling the profiling hook anymore in this case and not altering the flags or dispatch table if the signal happens to be handled at that time too.

I'm not sure if it completely fixes the issue, or if it is the smartest way to fix it. Comments welcome :)

**Comment by MikePall** [comment]
Fixed. Thanks!
