### ISSUE TITLE
OpenBSD: ldconfig: unknown option -- n

### ISSUE THREAD

**Issue by blueyed** [LuaJIT/LuaJIT#515]
`ldconfig` on OpenBSD does not appear to have support for the "-n" option.

From GNU's ldconfig:

> -n     Process only the directories specified on the command line.  Don't process the trusted directories, nor those specified in /etc/ld.so.conf.  Implies -N.

For osx this appears to be handled already: https://github.com/LuaJIT/LuaJIT/blob/f0e865dd4861520258299d0f2a56491bd9d602e1/Makefile#L100-L105

Ref: https://github.com/neovim/neovim/pull/10978#issuecomment-529537454

**Comment by siddhesh** [comment]
Here's an untested patch.  Can you please verify that it works?  I don't have an OpenBSD system to test this:

https://github.com/siddhesh/LuaJIT/commit/889b5a39941aa408e3c8636a505cc56ba30d7568

**Comment by blueyed** [comment]
Thanks.
I do not have a OpenBSD system myself, but could only test it on Neovim's CI.

I've wondered where that branch is based on though.. it does not appear to be master/v2.0/v2.1.

**Comment by siddhesh** [comment]
> Thanks.
> I do not have a OpenBSD system myself, but could only test it on Neovim's CI.

Cool, as long as you can confirm that it works somehow :)

> I've wondered where that branch is based on though.. it does not appear to be master/v2.0/v2.1.

It's based off v2.1 but there's been quite a bit of progress over the last ~9 months so it won't look the same, although I've tried to keep the tree compatible merge-wise for now.  This original tree has been dormant for a while now, so there needed to be some place to continue development...

**Comment by blueyed** [comment]
It's not trivial to test unfortunately - and I just assume that it works (similar to osx).
For reference, the build where it failed: https://builds.sr.ht/~jmk/job/88327#task-build-1114
I've looked into it again since I'd expected it to fail the build by itself already in the first place, but the code there is fine - only when it works it will create the symlinks.  So it's better to continue, outputting the error though, instead of failing.

**Comment by siddhesh** [comment]
Done.

**Comment by blueyed** [comment]
Thanks!

> It's based off v2.1 but there's been quite a bit of progress over the last ~9 months so it won't look the same, although I've tried to keep the tree compatible merge-wise for now. This original tree has been dormant for a while now, so there needed to be some place to continue development...

Are there plans to get this into v2.1 then, or 2.2 even?!

I wonder if it's ok/good for e.g. Neovim to go with 2.1 already? (https://github.com/neovim/neovim/pull/10321)

**Comment by siddhesh** [comment]
> Are there plans to get this into v2.1 then, or 2.2 even?!
> 

I just pushed this patch into my v2.1 fix update branch.  Note that I do not have rights to make changes in this repo.

> I wonder if it's ok/good for e.g. Neovim to go with 2.1 already? ([neovim/neovim#10321](https://github.com/neovim/neovim/pull/10321))

It should be ok.  We have been using 2.1.0-beta3 (with all of my patches) in Fedora for a while now without any issues.
