### ISSUE TITLE
Build fails on osx Catalina(10.15)

### ISSUE THREAD

**Issue by dm1try** [LuaJIT/LuaJIT#518]
osx 10.15, Xcode 11.1

with  `MACOSX_DEPLOYMENT_TARGET=10.15`
```
BUILDVM   lj_folddef.h
make[1]: *** [lj_folddef.h] Segmentation fault: 11
make[1]: *** Deleting file `lj_folddef.h'
make: *** [default] Error 2
```
with  `make MACOSX_DEPLOYMENT_TARGET=10.14` it works:
```
BUILDVM   jit/vmdef.lua
DYNLINK   libluajit.so
LINK      luajit
OK        Successfully built LuaJIT
==== Successfully built LuaJIT 2.1.0-beta3 ====
```

original issue => https://github.com/neovim/neovim/issues/11192

**Comment by dm1try** [comment]
I'll close, it looks like there is nothing we can do here. see https://github.com/neovim/neovim/issues/11192#issuecomment-540715700

**Comment by MikePall** [comment]
DUP of #484
