### ISSUE TITLE
Tracing state machine does not account for OOM in trace_save

### ISSUE THREAD

**Issue by mraleph** [LuaJIT/LuaJIT#52]
`trace_stop` first patches code (bytecode or machine code) and then commits executable code (`lj_mcode_commit`) and *allocates a new trace object* (`trace_save`). 

Errors inside `lj_mcode_commit` just cause panic. 

However `trace_save` calls `lj_mem_newt` (aka `lj_mem_realloc`) which *can* throw `lj_err_mem`.

Tracer catches this OOM and aborts tracing, but `trace_abort` will simply drop trace [to the floor](https://github.com/LuaJIT/LuaJIT/blob/master/src/lj_trace.c#L533-L537) without trying to undo `trace_stop` [side effects](https://github.com/LuaJIT/LuaJIT/blob/master/src/lj_trace.c#L422-L459). 

This can lead to a variety of problems, most notably "dangling" references to this trace from patched bytecode (or patched machine code) which now point to a dropped trace. 

I don't have a really good standalone repro for this bug, but it is easy to reproduce: just add an unconditional throw inside `trace_save` to emulate OOM.

```diff
diff --git a/src/lj_trace.c b/src/lj_trace.c
index 79c50b0..473b7c2 100644
--- a/src/lj_trace.c
+++ b/src/lj_trace.c
@@ -125,6 +125,7 @@ static void trace_save(jit_State *J)
   size_t sz = sztr + szins +
              J->cur.nsnap*sizeof(SnapShot) +
              J->cur.nsnapmap*sizeof(SnapEntry);
+  lj_err_mem(J->L);  /* Always OOM. */
   GCtrace *T = lj_mem_newt(J->L, (MSize)sz, GCtrace);
   char *p = (char *)T + sztr;
   memcpy(T, &J->cur, sizeof(GCtrace));
```

```
$ gdb --args src/luajit
(gdb) r
Starting program: /usr/local/google/home/vegorov/src/third_party/LuaJIT-2.1/src/luajit 
LuaJIT 2.1.0-alpha -- Copyright (C) 2005-2015 Mike Pall. http://luajit.org/
JIT: ON SSE2 SSE3 SSE4.1 fold cse dce fwd dse narrow loop abc sink fuse
> for i = 0, 10000 do end

Program received signal SIGSEGV, Segmentation fault.
0x000000000041d54e in ?? ()
(gdb) bt
#0  0x000000000041d54e in ?? ()
#1  0x000000000040d2bd in lua_pcall ()
#2  0x000000000040485c in _start ()
(gdb) x/i $pc
=> 0x41d54e:  mov    rax,QWORD PTR [rax+0x40]  ;; this is mov RDa, TRACE:RD->mcode
```

**Comment by MikePall** [comment]
Thanks! Fixed in master.
