### ISSUE TITLE
LuaJIT fails to run on macOS Catalina: "cannot create state: not enough memory"

### ISSUE THREAD

**Issue by fxcoudert** [LuaJIT/LuaJIT#521]
I'm trying to compile LuaJIT-2.0.5 from source, for Homebrew, on Catalina. When one fixes https://github.com/LuaJIT/LuaJIT/issues/518 by passing `-fno-stack-check` to the compiler, the build succeeds. However, the resulting binary does not work:

```
$ /usr/local/Cellar/luajit/2.0.5/bin/luajit          
/usr/local/Cellar/luajit/2.0.5/bin/luajit: cannot create state: not enough memory
```

The system has, of course, plenty of memory, and not limits set on it. We're seeing this on all our machines, including CI VMs and my own laptop.

---

OS: macOS 10.15 Catalina (with supplemental update)
Compiler: Xcode 11
LuaJIT is built with: `make amalg && make install`

**Comment by fxcoudert** [comment]
Other projects are having issues with memory, that might be related:
- ghc, the Haskell compiler: https://gitlab.haskell.org/ghc/ghc/issues/17353
- sbcl needed two commits to its mmap code: https://github.com/sbcl/sbcl/commit/07d135b0dd4e7c34bc0dce6aac07570d66e297ee and https://github.com/sbcl/sbcl/commit/5cefb8506b7d8d9a0277236eb3f7e76c4428ac10

**Comment by vanc** [comment]
For LuaJIT 2.1, you can enable GC64 to avoid the memory issue.

**Comment by vanc** [comment]
Actually, even without GC64, LuaJIT still works fine for me on Catalina, as long as the following option is still in the Makefile.
```
    TARGET_XLDFLAGS+= -pagezero_size 10000 -image_base 100000000
    TARGET_XSHLDFLAGS+= -image_base 7fff04c4a000
```

If the linker option is removed, you must enable GC64.

```
 # Enable GC64 mode for x64.
-#XCFLAGS+= -DLUAJIT_ENABLE_GC64
+XCFLAGS+= -DLUAJIT_ENABLE_GC64
 #
```

**Comment by fxcoudert** [comment]
This is LuaJIT-2.0.5, which is (as far as I can see) the latest stable released version.

**Comment by chernando** [comment]
@fxcoudert FYI The only way I've managed to install LuaJIT with Hombrew on a fresh install of Catalina:

```diff
     # Build with 64-bit support
     args << "XCFLAGS=-DLUAJIT_ENABLE_GC64" if build.head?
+    args << "CFLAGS=-fno-stack-check" if build.head?
```

and `brew install --HEAD luajit`.

```
$ luajit-2.1.0-beta3
LuaJIT 2.1.0-beta3 -- Copyright (C) 2005-2017 Mike Pall. http://luajit.org/
JIT: ON SSE2 SSE3 SSE4.1 BMI2 fold cse dce fwd dse narrow loop abc sink fuse
>
```

I was trying to install neovim Formula, that requires luajit, and using `--HEAD` makes `luarocks` to fail trying to find an usable lua interpreter. So it also needs `ln -s opt/luajit/bin/luajit-2.1.0-beta3 opt/luajit/bin/luajit`. And `ln -s bin/luajit-2.1.0-beta3 bin/luaji` just in case.

Hope this helps 🤞

**Comment by MichaelEischer** [comment]
LuaJIT 2.0.5 compiles when disabling the stack check. However, it will still crash when starting it. As noted by vanc, LuaJIT 2.1.0-beta3 works. I've tracked this down to the memory allocation code in `lj_alloc.c` where apparently the mmap call issued by LuaJIT 2.0.5 fails to allocate the requested memory.

What has worked for me is to copy the LuaJIT 2.1.0-beta3 version of `lj_alloc.c` (https://github.com/LuaJIT/LuaJIT/blob/v2.1/src/lj_alloc.c) into the LuaJIT 2.0.5 source code. After building with the `-fno-stack-check` flag LuaJIT 2.0.5 seems to work fine.

**Comment by fxcoudert** [comment]
@MichaelEischer there are only 8 commits to the 2.1.0 branch between 3 April 2016 (which is 2.0.5 state) and now. Could you try to see which one would be needed for Catalina? I'm guessing it's https://github.com/LuaJIT/LuaJIT/commit/0c6fdc1039a3a4450d366fba7af4b29de73f0dc6#diff-456deef6abee232e0d60986d4b192be5

**Comment by MichaelEischer** [comment]
@fxcoudert Your guess is correct. Judging from the changes made in the other commits, none of them should be necessary on macOS with a LuaJIT that only uses the lower 2GB of the memory space.

**Comment by fxcoudert** [comment]
Sadly, the commit at https://github.com/LuaJIT/LuaJIT/commit/0c6fdc1039a3a4450d366fba7af4b29de73f0dc6 does not apply to LuaJIT-2.0.5

**Comment by MichaelEischer** [comment]
The difference between the lj_alloc.c on the 2.0 branch and the https://github.com/LuaJIT/LuaJIT/blob/101115ddd86f6e66f225eee4702793623e683007 , which is the commit before the mmap rewrite, is rather small:
```diff
--- lj_alloc-2.0.c	2019-11-18 19:37:24.000000000 +0100
+++ lj_alloc-101115ddd.c	2019-11-18 19:36:07.000000000 +0100
@@ -77,7 +77,7 @@
 #define WIN32_LEAN_AND_MEAN
 #include <windows.h>
 
-#if LJ_64
+#if LJ_64 && !LJ_GC64
 
 /* Undocumented, but hey, that's what we all love so much about Windows. */
 typedef long (*PNTAVM)(HANDLE handle, void **addr, ULONG zbits,
@@ -174,8 +174,10 @@
 #endif
 #define MMAP_FLAGS		(MAP_PRIVATE|MAP_ANONYMOUS)
 
-#if LJ_64
-/* 64 bit mode needs special support for allocating memory in the lower 2GB. */
+#if LJ_64 && !LJ_GC64
+/* 64 bit mode with 32 bit pointers needs special support for allocating
+** memory in the lower 2GB.
+*/
 
 #if defined(MAP_32BIT)
 
@@ -258,7 +260,7 @@
 
 #else
 
-/* 32 bit mode is easy. */
+/* 32 bit mode and GC64 mode is easy. */
 static LJ_AINLINE void *CALL_MMAP(size_t size)
 {
   int olderr = errno;
@@ -294,7 +296,7 @@
 #define CALL_MREMAP(addr, osz, nsz, mv) CALL_MREMAP_((addr), (osz), (nsz), (mv))
 #define CALL_MREMAP_NOMOVE	0
 #define CALL_MREMAP_MAYMOVE	1
-#if LJ_64
+#if LJ_64 && !LJ_GC64
 #define CALL_MREMAP_MV		CALL_MREMAP_NOMOVE
 #else
 #define CALL_MREMAP_MV		CALL_MREMAP_MAYMOVE
```
As `LJ_GC64` is not defined in LuaJIT-2.0.5 it evaluates to 0 and therefore the diff between both versions of the file is a no-op. That is the cleanest solution would be to just remove those ` && !LJ_GC64` checks again, however, it is not strictly necessary.

**Comment by MikePall** [comment]
Since macOS nowadays is only 64 bit and only compatible with LJ_GC64, please use the 2.1 branch.

**Comment by fxcoudert** [comment]
@MikePall the 2.1 does not have a stable released version. Does this mean that LuaJIT does not support macOS anymore?
