### ISSUE TITLE
Length operator inconsistent with Lua 5.1 (and 5.3) when packing varargs containing nil

### ISSUE THREAD

**Issue by Myaamori** [LuaJIT/LuaJIT#527]
Demonstration of the issue; LuaJIT prints a different value from vanilla Lua:

```
$ lua5.3
Lua 5.3.5  Copyright (C) 1994-2018 Lua.org, PUC-Rio
> function a(...)
>> local x = {...}
>> print(#x)
>> end
> a(1, 2, nil, 4, 5)
5
> 
$ lua5.1
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
> function a(...)
>> local x = {...}
>> print(#x)
>> end
> a(1, 2, nil, 4, 5)
5
> 
$ luajit
LuaJIT 2.0.5 -- Copyright (C) 2005-2017 Mike Pall. http://luajit.org/
JIT: ON CMOV SSE2 SSE3 SSE4.1 fold cse dce fwd dse narrow loop abc sink fuse
> function a(...)
>> local x = {...}
>> print(#x)
>> end
> a(1, 2, nil, 4, 5)
2
> 
$ luajit-2.1.0-beta3 
LuaJIT 2.1.0-beta3 -- Copyright (C) 2005-2017 Mike Pall. http://luajit.org/
JIT: ON SSE2 SSE3 SSE4.1 BMI2 fold cse dce fwd dse narrow loop abc sink fuse
> function a(...)
>> local x = {...}
>> print(#x)
>> end
> a(1, 2, nil, 4, 5)
2
> 
```

This also means `unpack({...})` doesn't return the original arguments. Workaround:

```
local args = {...}
local n = select("#", ...)
unpack(args, 1, n)
```

**Comment by corsix** [comment]
Lua's length operator has undefined behaviour for tables which contain `nil`s. To pick one random answer from the thousands of times this has come up, see https://stackoverflow.com/questions/23590885/why-does-luas-length-operator-return-unexpected-values.

**Comment by Myaamori** [comment]
Well FWIW the behaviour can also be considered internally inconsistent, since on the other hand

```lua
$ luajit
LuaJIT 2.0.5 -- Copyright (C) 2005-2017 Mike Pall. http://luajit.org/
JIT: ON CMOV SSE2 SSE3 SSE4.1 fold cse dce fwd dse narrow loop abc sink fuse
> x = {1, 2, nil, 4, 5}
> print(#x)
5
```

But I guess it doesn't matter if the behaviour is undefined to begin with and you're not aiming for compatibility with vanilla Lua.

**Comment by slime73** [comment]
The exact wording from Lua 5.3's reference manual is this:

> a border is any (natural) index in a table where a non-nil value is followed by a nil value (or zero, when index 1 is nil). 

> When t is a sequence, #t returns its only border, which corresponds to the intuitive notion of the length of the sequence. When t is not a sequence, #t can return any of its borders. (The exact one depends on details of the internal representation of the table, which in turn can depend on how the table was populated and the memory addresses of its non-numeric keys.) 

So it's defined to be "internally inconsistent", as you put it, and LuaJIT matches Lua's spec in that regard.

**Comment by szbnwer** [comment]
hi there! :)

u can use these for what u want:

```
table.pack=table.pack or function(...) return {n=select('#', ...), ...} end

table.unpack=table.unpack or unpack
```

bests, have fun! :)

**Comment by clason** [comment]
For those coming across this in 2021: The length operator is even more inconsistent (as of https://github.com/LuaJIT/LuaJIT/commit/b4b2dce9fc3ffaaaede39b36d06415311e2aa516), since (only) a `nil` in a penultimate _and even_  position terminates a table: Consider
```lua
print(#{1,2,nil,4,5}) -- 5
print(#{1,2,nil,4})   -- 4
print(#{1,nil,3,4})   -- 4
print(#{1,nil,3})   -- 1
```
PUC Lua 5.1 prints `3` for the last one.

(I know table length with `nil` is undefined behavior, and you shouldn't rely on `#` for this, but I thought I'd mention this inconsistency even if it's not a bug as a heads-up.)
