### ISSUE TITLE
when compare a number with a userdata,it don't call userdata metatable method

### ISSUE THREAD

**Issue by ElPsyCongree** [LuaJIT/LuaJIT#529]
attempt to compare number with userdata

**Comment by GitSparTV** [comment]
Maybe some code?

**Comment by ElPsyCongree** [comment]
local meta = {
	__lt = function(a, b) return a.value > b end
}
local x = {value = 1}
setmetatable(x, meta)
local y = 2
print (y > x)

**Comment by ElPsyCongree** [comment]
int lua5.3 it print "false" but int luajit it show error:attempt to compare number with table

**Comment by ElPsyCongree** [comment]
in lj_meta.c 378:line

**Comment by GitSparTV** [comment]
__lt was changed in 5.2, in LuaJIT this is disabled.
To enable see `DLUAJIT_ENABLE_LUA52COMPAT` here: http://luajit.org/extensions.html
