### ISSUE TITLE
Apply to GitHub sponsorship

### ISSUE THREAD

**Issue by XVilka** [LuaJIT/LuaJIT#530]
Since the development of the LuaJIT is largely stalled, the project might benefit from the sponsoring. I am sure there are many other projects and organizations who use LuaJIT and would be happy to chip in.

See [GitHub Matching Sponsorship](https://github.com/sponsors) program, when they match the contributions made through the [Sponsor](https://help.github.com/en/github/building-a-strong-community/displaying-a-sponsor-button-in-your-repository) button:

![image](https://user-images.githubusercontent.com/203261/69779761-0c039b00-11e4-11ea-8aec-5399fab8d720.png)

**Comment by ExtReMLapin** [comment]
Michael Pall is hibernating

**Comment by XVilka** [comment]
Well, do the same for any main fork of LuaJIT, doesn't really matter.

**Comment by MikePall** [comment]
Sponsoring was never an issue.
