### ISSUE TITLE
if exit meta __gc method,lightdata should call it when lua not ref this object

### ISSUE THREAD

**Issue by ElPsyCongree** [LuaJIT/LuaJIT#532]
**C don't know when to free the lightuserdata.**

if C directly free it,lua may cause same error when visit the data.otherwise may cause the memory leak.so is there and method to notify C that lua don't use this lightdata?

**Comment by spacewander** [comment]
lightuserdata are not managed by the Lua's garbage collection, since Lua doesn't allocate memory for them.
If the C code doesn't manage the data, better to use userdata or cdata (recommended) instead.
