### ISSUE TITLE
__eq not support different type,I just wan't use userdata as a int64 and __eq compare with number

### ISSUE THREAD

**Issue by ElPsyCongree** [LuaJIT/LuaJIT#534]
`
local mt = {
__eq = function(a,b) print(a) return true end
}

local x = {}
setmetatable(x, mt)

print(x == 1)
`
 
I just want this trick the metamethod __eq

**Comment by edubart** [comment]
This is correct and defined behavior for luajit, lua 5.1, 5.2, 5.3 and even lua 5.4. `__eq`  is only evaluated when both types are same (as the manual states).

In this scenario you can either convert both types to the same before comparing or create a function that can compare different types.

**Comment by ElPsyCongree** [comment]
in lua 5.3 lua5.4 it has interger type,so there are not need to design a int64 userdata,bug luajit still in lua5.1,we must has a int64 userdata to compare with a number

**Comment by MikePall** [comment]
Maybe you missed that LuaJIT already has int64_t, uint64_t and others as part of the FFI. Mixed-type comparisons work as expected:

```Lua
print(1 == 1LL) --> true
```
