### ISSUE TITLE
JIT Compiler ON + C Call with lua_getlocal inside *sometimes* return the function instead of the function call result

### ISSUE THREAD

**Issue by ExtReMLapin** [LuaJIT/LuaJIT#536]
Hello,

At the office we got a function that basically do the following : 

```Lua
local handler = function(msg)
	local occupation = (msg.state == 'F') and 0 or 1
	local tk = getTk()
	memUpdateRecord("STD_TRANSTOCKEURS", "STD_TRANSTOCKEUR=tk", "STD_OCCUPATION_DEPOSE=occupation")
end
```

`getTk` is a global function always returning a string, to `tk` can only be a string

 `memUpdateRecord` is a C function.

Here is the locals "dump" when the bug happen : 

```
msg = { destination = "", ... }

occupation = 0

tk = <function>

(*temporary) = <nil>

(*temporary) = 6.9513464862328e-310

(*temporary) = 8.1476278837674e-312
```

3 extra temp variables and tk is the value of getTk, not getTk()

Bascically, `"STD_TRANSTOCKEUR=tk"` will search `tk` in the local variables with lua_getlocal then in the upvalues if not found.

**Technically, tk can be detected as "unused", even if we technically use it by searching all the variables having the name `tk` in the C function.**

What we did here works perfectly with Lua PUC 5.1, According to my boss it works with LuaJIT when the JIT compiler is OFF, but when the JIT compiler is ON, `tk` is not even a string, it's the value of the function that is supposed to be called : `getTk`, instead of returning `getTk()`.

Ourselves aren't able to reproduce this issue every-time, so it's impossible for us to provide exact code to reproduce this issue.

However, I found [this gist](https://gist.github.com/mejedi/d61752c5fd582d2507360d375513c6b8) talking about something similar.

I also disabled tail-calls [using this](https://github.com/fsfod/LuaJIT/commit/79c70043073e97bb60c11e1a53b4fd0d2e940150), I doubt it breaks anything.

If anyone got an Idea of what's going on and what we could do to debug this...

For a moment i tought it was because the jit compiler was aborting traces if it found a debug.* lib call, and it couldn't know my C function was using lua_getlocal, but I have doubts about this theory.

Thanks.

**Comment by MikePall** [comment]
The purpose of the `debug.*` functions is for debugging Lua code. Period. In general, you'd want to turn the JIT compiler off for that, because it does a lot of things that will interfere with that task.

But honestly ... that piece of code is not just unacceptable -- it's outrageously bad. Peeking at local variables of an outer frame instead of simply passing them as arguments, is an unspeakable sin (in any computer language). If this wasn't written by a greenhorn at programming, they should definitely reconsider their career choice.

**Comment by ExtReMLapin** [comment]
Thank for the answer Mike,

The function wasn't designed/coded by me and I had kinda the same reaction when I saw it for the first time.
