### ISSUE TITLE
dynasm: How to load a C value into an ARM register

### ISSUE THREAD

**Issue by pollen5** [LuaJIT/LuaJIT#537]
Okay this might be stupid and wrong place to ask but I'm struggling with this issue for long and google didn't help.

Basically consider this dynasm example for x86
```
| mov eax, num
| ret
```
How would you do that in ARM? I tried
```
| mov r0, num
| bx lr
```
but it says invalid register 'num' i know arm immediates are a bit weird because instructions size but then how would you do this, google could only lead me to "load it into a register first"
So i tried
```
| ldr r0, =num
```
and that's an invalid reference now, so how do you even load a C variable into an arm register, I'm totally stuck here.

This might be more of a "general assembly question" I'm sorry but i couldn't find any resource about this so an answer would be really appreciated.

**Comment by MikePall** [comment]
Immediates need to be prefixed with a #: `ldr r0, #num`

But you're right, this is an issue tracker and not an assembly tutorial. Read `vm_arm.dasc` for lots of (rather complex) ARM assembly code.

**Comment by pollen5** [comment]
@MikePall thanks but the ldr example you provided did not work, with `mov` the # did the job but I'm still limited by ARM's immediates (511 gives illegal instruction) so i tried the ldr one but dynasm still complains about "expected address operand" for the `#num`

**Comment by pollen5** [comment]
I think this is more of a dynasm question now, `ldr r0, =511` works in regular assembly, but not with a C variable.
