### ISSUE TITLE
OSX *** [lj_folddef.h] Segmentation fault: 11

### ISSUE THREAD

**Issue by easonzhou214** [LuaJIT/LuaJIT#538]
macOS x64
Help!!!

**Comment by ExtReMLapin** [comment]
Give us more informations, like the version you're using, if you downloaded a release or cloned the repo.

**Comment by easonzhou214** [comment]
I tried to download a zip and cloned the rep. When I run the make command and all they failed.
version: 2.1 beta3 and 2.0.5
os: macOS 10.15.2

**Comment by ExtReMLapin** [comment]
#484 related ?

**Comment by easonzhou214** [comment]
I tried this command:
make MACOSX_DEPLOYMENT_TARGET=10.6 DEFAULT_CC=clang -j8

and I got an error:
CC        lj_err.o
lj_err.c:290:8: error: thread-local storage is not supported for the current
      target

**Comment by stuta** [comment]
Download and install MacOSX10.12.sdk: https://github.com/phracker/MacOSX-SDKs/releases <https://github.com/phracker/MacOSX-SDKs/releases>

MACOSX_DEPLOYMENT_TARGET="10.12" CFLAGS="-DLUAJIT_ENABLE_LUA52COMPAT" LDFLAGS="-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.12.sdk" make amalg

-stuta

**Comment by easonzhou214** [comment]
it works!!! thanks mate!!!!

**Comment by SummerRui** [comment]
> it works!!! thanks mate!!!!
hello，frined. I met the same problem as you.
Environment：
MACOSX: 10.15.2
XCODE: 11.2.1
Luajit Version: LuaJIT-2.1.0-beta3

I tried this command:
make MACOSX_DEPLOYMENT_TARGET=10.15 DEFAULT_CC=clang -j8
and I got an error:
[lj_folddef.h] Segmentation fault: 11

Help, Thanks!!!

**Comment by easonzhou214** [comment]
> > it works!!! thanks mate!!!!
> > hello，friend. I met the same problem as you.
> > Environment：
> > MACOSX: 10.15.2
> > XCODE: 11.2.1
> > Luajit Version: LuaJIT-2.1.0-beta3
> 
> I tried this command:
> make MACOSX_DEPLOYMENT_TARGET=10.15 DEFAULT_CC=clang -j8
> and I got an error:
> [lj_folddef.h] Segmentation fault: 11
> 
> Help, Thanks!!!

hey summer,
You should download and install MacOSX10.12.sdk: https://github.com/phracker/MacOSX-SDKs/releases <https://github.com/phracker/MacOSX-SDKs/releases>

and make MACOSX_DEPLOYMENT_TARGET=10.12

**Comment by SummerRui** [comment]
> > > it works!!! thanks mate!!!!
> > > hello，friend. I met the same problem as you.
> > > Environment：
> > > MACOSX: 10.15.2
> > > XCODE: 11.2.1
> > > Luajit Version: LuaJIT-2.1.0-beta3
> > 
> > 
> > I tried this command:
> > make MACOSX_DEPLOYMENT_TARGET=10.15 DEFAULT_CC=clang -j8
> > and I got an error:
> > [lj_folddef.h] Segmentation fault: 11
> > Help, Thanks!!!
> 
> hey summer,
> You should download and install MacOSX10.12.sdk: https://github.com/phracker/MacOSX-SDKs/releases https://github.com/phracker/MacOSX-SDKs/releases
> 
> and make MACOSX_DEPLOYMENT_TARGET=10.12
It's ok! Thanks your very much!!

**Comment by jancywen** [comment]
macOS Catalina  10.15.6  
only make MACOSX_DEPLOYMENT_TARGET=10.15 
It works!
