### ISSUE TITLE
collectgarbage won't recycle some memory on 2.1.0 beta3

### ISSUE THREAD

**Issue by blocklifeAKA** [LuaJIT/LuaJIT#539]
version: Luajit 2.1.0 beta3 x64
machine:Win10 x64 16GB
notice:work's fine at beta2 x64
code:
local count = 10000000
while count ~= 0 do
	count = count - 1	
	table.insert(dataTable,{})
end
--about 800MB

dataTable = nil
collectgarbage("collect")
--170MB showed on process manager.
print(collectgarbage("count")) --return 23KB

--one more strange case.
local count = 10000000
while count ~= 0 do
	count = count - 1	
	table.insert(dataTable,{})
end
--about 800MB
someTable = {} --someTable must be a global value.
local count2 = 10000000
while count2 ~= 0 do
 count2 = count2 - 1
 someTable = {}
end
--about 1.2GB. I don't know is a right performance or not.
dataTable = nil
someTable = nil
collectgarbage("collect")
--224MB showed on process manager
print(collectgarbage("count")) --return 30KB

**Comment by blocklifeAKA** [comment]
`print("start up")

dataTable = {}
local count = 10000000
while count ~= 0 do
	count = count - 1	
	table.insert(dataTable,{})
end

print("press to release")
os.execute("pause")

dataTable = nil 

print("start collect")
collectgarbage("collect")
print("collect finish")

print(string.format("Lua Memory:%fMB",collectgarbage("count")/1024))
print("press to exit")
os.execute("pause")
`

**Comment by blocklifeAKA** [comment]
dataTable = {}
local count = 10000000
while count ~= 0 do
	count = count - 1	
	table.insert(dataTable,{})
end

for i=1,10000000,1 do --add this line will trigger memory leak at beta2
end
dataTable = nil
collectgarbage("collect")

**Comment by MikePall** [comment]
This is expected behavior and the same in plain Lua.
The GC uses a memory allocator which may free memory lazily (to speed up subsequent allocations and/or to reduce fragmentation). When and how it recycles or releaes memory depends on many factors, e.g. allocation order and memory layout. This may change between versions, but the general behavior is not version-specific.
