### ISSUE TITLE
FFI: Call C function from main executable

### ISSUE THREAD

**Issue by cxxcunow** [LuaJIT/LuaJIT#543]
Gents,
I have one issue about how to use lua call C function without ffi.load.
My code like following.
here I can call libc 's printf. but I can't call my function __aadd, __ssub.  and error info is  ./tt: undefined symbol: __aadd
My environment is linux. And I dont want to compile one dynamic so.

thanks.

extern "C" 
{
#include "include/lua.h"
#include "include/lauxlib.h"
#include "include/lualib.h"
};
#include <iostream>
#include <stdio.h>
using namespace std;
//extern "C" [[gnu::visibility("default")]] int Add(int a, int b);

extern "C"  __attribute__((visibility("default")))  int __aadd(int a, int b)
//extern "C" int Add(int a, int b)
{
  return a + b;
}

extern "C" __attribute__((visibility("default"))) int __ssub(int a, int b)
{
  return a-b;
}
//}
//

int main()
{
   const char *lua_code =
"local ffi = require('ffi')                   \n"
//"ffi.load('c', true)\n"
//"ffi.load(default, true)\n"
"print(\"www\")                               \n"
"ffi.cdef[[                                   \n"
"int __aadd(int,int);                            \n"
"int __ssub(int, int);                            \n"
"int printf(const char *fmt, ...);\n"
"]]                                           \n"
"sum = ffi.C.__aadd(10,20)      \n"
"ffi.C.printf(\"wwwwww\")      \n"
"print('sum:'..sum)      \n"
;

lua_State *lua = luaL_newstate();
luaL_openlibs(lua);
const int status = luaL_dostring(lua, lua_code);
if(status)
    printf("Couldn't execute LUA code: %s\n", lua_tostring(lua, -1));
lua_close(lua);
return 0;
}

**Comment by MikePall** [comment]
On Linux, symbols from the main executable are not exported unless you use the `-Wl,-E` option when linking.

**Comment by cxxcunow** [comment]
g++ --std=c++11 -o tt  tt.i tt.cpp t2.cpp  -L. -lluajit -ldl ,--version-script=export.map 
so how can I modify the complie cmd?
