### ISSUE TITLE
how to compile to a libx.a and then link to main?

### ISSUE THREAD

**Issue by cxxcunow** [LuaJIT/LuaJIT#545]
the following is my code:
I need to build it into one libX.a. and then, I will link it to a binary.  so what build flags should I have?

thanks.
`
extern "C"  __attribute__((visibility("default")))  int Add(int a, int b)
{
  return a + b;
}

//extern "C" __attribute__((visibility("default"))) int __ssub(int a, int b)

//}
//

int test()   // lua与c++通过lua堆栈交互的
{
   const char *lua_code =
"local ffi = require('ffi')                   \n"
//"ffi.load('c', true)\n"
//"ffi.load(default, true)\n"
"print(\"www\")                               \n"
"ffi.cdef[[                                   \n"
"int Add(int, int);                            \n"
"int printf(const char *fmt, ...);\n"
"]]                                           \n"
"sum = ffi.C.Add(10,20)      \n"
"ffi.C.printf(\"wwwwww\")      \n"
"print('sum:'..sum)      \n"
;

        lua_State *lua = luaL_newstate();
        luaL_openlibs(lua);

        const int status = luaL_dostring(lua, lua_code);
        if(status)
                printf("Couldn't execute LUA code: %s\n", lua_tostring(lua, -1));

lua_close(lua);
return 0;
}`

**Comment by MikePall** [comment]
**Stop opening duplicate issues!** If you continue, you will be blocked. This is the last warning.
Your question has already been answered in #543.
This is an issue tracker, not an introductory course to C.
