### ISSUE TITLE
luaL_newstate return NULL with multi-thread

### ISSUE THREAD

**Issue by cxxcunow** [LuaJIT/LuaJIT#548]
if  call luaL_newstate in c++ multi-thread, it will return NULL,
if  call luaL_newstae in main function without multi-thread, it success.

what's the problem?

**Comment by MikePall** [comment]
Uh, what's 'without multi-thread'?
Please file only issues with clear questions and clear, concise and complete information about your build environment and flags. Also (again) **do not file multiple issues** for the same problem.
