### ISSUE TITLE
musl: ldconfig unavailable, library symlinks not created

### ISSUE THREAD

**Issue by wylfen** [LuaJIT/LuaJIT#552]
Similar to #515, though ldconfig is not available _at all_ on musl-based systems (see [here](https://wiki.musl-libc.org/faq.html#Q:-Where-is-%3Ccode%3Eldconfig%3C/code%3E?)).

A clean solution is to check for availability of `ldconfig` and then do `LDCONFIG= :` if it is missing. Looking through the mailing list archive I found [this](https://www.freelists.org/post/luajit/Do-not-silently-and-prematurely-end-install-when-ldconfig-is-missing,1), which also seems like a potential fix.

**Comment by MikePall** [comment]
I've committed a change that solves both issues.
