### ISSUE TITLE
Lua-lang scanner/parser bug

### ISSUE THREAD

**Issue by 09f4775e-b2ff-43f3-ad76-f5484ba8318a** [LuaJIT/LuaJIT#553]
--tmp.lua
function f_aaa(a);
print("hw")
end
f_aaa()

...
~$ lua tmp.lua  >>> hw
~$ luajit tmp.lua  >>> err. unexpected symbol near ';'

Lua 5.3.5
LuaJIT 2.1.0-beta3
Linux devuan 32bit

**Comment by stuta** [comment]
This is not a bug. Please, read the error message and learn the syntax before posting. Remove ';' from the end of function -line.

**Comment by MikePall** [comment]
The parsing rules for statements have changed between Lua 5.1 and 5.2.
LuaJIT builds as Lua 5.1-compatible by default. Turn on the Lua 5.2-compatible build in `src/Makefile` and your code works.
