### ISSUE TITLE
Pathological string performance

### ISSUE THREAD

**Issue by Lssikkes** [LuaJIT/LuaJIT#555]
Hey Mike,

I've been stumped a bit with some massive performance degradation in my lua based ninja generator when I was messing around with some strings. I narrowed it down to the following:

local outputs = {}
for i=1,1000000 do
    local file = "__stress_stress_test_out" .. (tostring(i) .. ".out")
    table.insert(outputs, file)
end

Try running that with lua53 and then with luajit (I tested 2.0 and latest 2.1 beta, turned jit off/on, etc)
Lua53 seems to run a lot faster.. I modified the build files to generate some .pdbs on windows and attached the visual studio performance profiler to luajit.exe test.lua:

![image](https://user-images.githubusercontent.com/5462782/73562167-dafd4c00-445a-11ea-9086-3b2452c180cf.png)

![image](https://user-images.githubusercontent.com/5462782/73562187-e6507780-445a-11ea-9a8d-476c3466a8e5.png)

Looks like lj_str_new is consuming a ton of cycles. My guess it's because it's not constructing a full hash of the string object, and instead uses some random offsets in the string to generate an approximate hash. Unfortunately in this case that generates a hash that is constant, and everything ends up in the same hash bucket, making string creation extremely slow (turning this O(N) loop into O(N^2)).

I'm not sure how to exactly fix this efficiently.. One thing would be to do a fast hash on the full string, but that would degrade perf in case the easy hash already generates a good enough version. Skipping hashing for large strings could work (and only keep full hashes (cityhash?) for tiny strings (<= 64 bytes)).

In any case I need to fix this so that at least the performance is somewhat constant instead of having this super pathological case. I'm going to do some experiments with other hashing schemes or just skipping string deduplication altogether. Ideas are welcome :)

**Comment by hippi777** [comment]
hi there! :)

as u provided only an example instead of the real code, i dunno if either of these could be suitable to ur needs, but one possible solution i could think about is to store a different (more essential) data and then generate the long form in place where u need it (print/write to fs/whatever); or u could use ffi with an array of strings, possibly hidden with some metatable magic. so these ways u dont need to hack the engine, and probably they wont bring much headache, but it depends...

ps: sorry, im not Mike, but i hope it could be any much better than the obvious answer that u already considered and decided to not use :D otherwise i pass the word on to Mike or anyone wiser than me.

have fun, bests! :)

**Comment by Lssikkes** [comment]
Hey Hippi, I found some old "wontfix" bug that seems to have a nice solution to this problem, I merged it into my fork (https://github.com/funny-falcon/LuaJIT/tree/smart_str4).. It speeds up this benchmark so that now it's 4x faster than Lua53.. Good enough for me 👍  Just wish this would be integrated in mainline as well.. Having such a bad worst case performance for new strings is not something I'd have expected

**Comment by Lssikkes** [comment]
(it also works in my app :))
[dbg] 0.004     Scripts: Building FS cache..
[dbg] 0.009     Scripts: Detecting scripts in FS cache..
[dbg] 0.011     Scripts: Done..
[dbg] 0.011     Loading module  qs.test_stress_ninja    e:\cfc\qs_dev\test\ninja\qs.test_stress_ninja.module.qss
[dbg] 0.070     Loading module  compiler.ninja  e:\cfc\qs_dev\.quicksilver\system_modules\compiler.ninja.module.qss
[dbg] 0.071     Loading action  e:\cfc\qs_dev\.quicksilver\system_actions\ninja.lua
[dbg] 0.073     Ninja: Processing       qs.test_stress_ninja    from    compiler.ninja
[dbg] 0.304     Ninja: Done processing..
[dbg] 0.305     Ninja: Writing ninja.build
/e/CFC/qs_dev/test/.build /e/CFC/qs_dev/test
[7370/100000] cmd.exe /C echo hello world > stress_stress_test4378.out

**Comment by hippi777** [comment]
seems good to me, and as it can be en-/disabled at will, i think no harm can come from it, but im not a pro in the hashing topic, and i only read it with more or less understanding... also, i dunno why its a wontfix, and its not my role to decide about its fate, but from my side, thx for showing it! :)

**Comment by MikePall** [comment]
Dup of #168
