### ISSUE TITLE
Weird behaviour with `realpath` FFI function in macOS Catalina

### ISSUE THREAD

**Issue by tomas** [LuaJIT/LuaJIT#557]
This code randomly returns nil when ran in a Macbook running macOS Catalina:

```
local ffi = require('ffi')

ffi.cdef [[
  char *realpath(const char *path, char *resolved_path);
]]

result = ffi.C.realpath("some/dir") 
```

Apparently this is caused by the new security features introduced in Catalina, which (randomly?) blocks access to applications unless given Full Disk Access in the Preferences > Privacy section.

Any ideas how to get around this?

Apparently the Julia folks [managed to fix this](https://github.com/JuliaLang/julia/issues/33545) by replacing the realpath implementation, but I'm not sure how would I translate that to LuaJIT/FFI land. [Here's another](https://github.com/crystal-lang/crystal/issues/8431) similar bug report in the Crystal lang repository.

**Comment by MikePall** [comment]
You need to supply a pre-allocated buffer as the second argument. Apparently Catalina has issues with a NULL argument.
Fix your code similarly to this: https://github.com/deepmind/lab/issues/173#issuecomment-560446111

**Comment by tomas** [comment]
Great, thanks Mike.

So something like `ffi.C.realpath('some/dir', ffi.new('char *'))` ?
