### ISSUE TITLE
Any thought to release luajit 2.1.0 as stable?

### ISSUE THREAD

**Issue by jnozsc** [LuaJIT/LuaJIT#563]
It has been almost 3 year since last release.

From ubuntu 18.04, 2.1.0 beta is the default version of luajit https://packages.ubuntu.com/search?keywords=luajit , which means this beta has already been used widely

and here  https://groups.google.com/d/msg/openresty-en/M2cpxWiP8Xk/2anWsVxBcYgJ  it seems luajit 2.1 is alway **production ready**

 In addition, Mike recommends to use 2.1 branch on macOS 64-bit  as https://github.com/LuaJIT/LuaJIT/issues/521#issuecomment-562999247

I install 2.1 branch on my local, and it works fine.

However, some software managers , such as Homebrew, do not accept `unstable` version to be added.

As a result, end users have to use
```
brew install luajit --HEAD
```
to install the 2.1 branch.

This works fine as individual. However, when we have any package `depends_on luajit`. This statement will not ensure the 2.1 branch is being chosen, and it may cause some issue on macOS Catalina.

Is there any breaking backwards compatibility issue to prevent a 2.1.0 release as stable? 

Thanks

**Comment by MoNTE48** [comment]
I would be glad to see at least beta4, after so many years!
To download the zip archive and be sure of the version, rather than clone the master with the hope that it still works the way I expect!

**Comment by jsgv** [comment]
Just to chime in. Installing Neovim nightly on macOS requires reinstalling luajit.
```
brew uninstall --ignore-dependencies luajit
brew install --HEAD luajit
```

**Comment by JCash** [comment]
Hi!
First, I want to say I appreciate all th ehard work going into this product!

Secondly, I agree with the idea of getting at least a `beta 4` release for us to start testing/using.
And thought, news or updates on this, @MikePall ?

Is there a roadmap over the issues needed for v2.1 to release?

**Comment by bmulholland** [comment]
FWIW, Homebrew is waiting for this as well and is tracking luajit as one of the major blockers to Apple Silicon support. https://github.com/Homebrew/brew/issues/10152

**Comment by clason** [comment]
That's not quite the situation (anymore): homebrew has started transitioning to openresty/LuaJIT2, which tracks LuaJIT but actually makes (unversioned) releases that can be targeted: https://github.com/Homebrew/homebrew-core/issues/68013

**Comment by inaryart** [comment]
openresty/LuaJIT2 seems to have a stable team to maintain it

**Comment by FrankXie05** [comment]
@MikePall 
As maintainers of vcpkg, we want to be able to get a stable release even though the `v2.1.0-beta3 beta` has been stable for three years.

Expectation: When will the stable version be released?

Note: Based on upstream behavior, are there plans to switch the master branch to the `v2.1` branch?

Looking forward to your reply. :)

**Comment by lblasc** [comment]
Hello @FrankXie05 , I'm one of the maintainers of [luajit in nixpkgs](https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/interpreters/luajit). I can share some of my experiences in packaging luajit.

Many times Mike said he won't do releases any more, so effectively luajit switched to "rolling" releases. 

How we do in nixpkgs is from time to time take latest HEAD for 2.0 and 2.1 do some tests, mainly by rebuilding all dependent packages and running them, then we make our own "release snapshot". If you [query nixpkgs](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=luajit) you will see that our package versions include date of released commit `2.1.0-YYYY-MM-DD`, `2.0.5-YYYY-MM-DD`.
For now this worked very well for us.

Old releases such as `v2.1.0-beta3` should not be used, HEAD is only release you need.
There are also plans to [bake commit hash](https://github.com/LuaJIT/LuaJIT/issues/711) in build time together with luajit version, which should give more clarity which commit/version is actually used.

**Comment by FrankXie05** [comment]
@lblasc Thank you very much for your reply, we fully accept the form of rolling release.
For the push of `LuaJIT`  update on `vcpkg` , can you tell me which version(`version-data: 2.1.0-YYYY-MM-DD`) can be used stably now?  Is it the search version(`version-date: 2.1.0-2022-04-05`) https://search.nixos.org/packages?channel=unstable&show=luajit&from=0&size=50&sort=relevance&type=packages&query=luajit  you provided and git commit https://github.com/LuaJIT/LuaJIT/commit/5e3c45c43bb0e0f1f2917d432e9d2dba12c42a6e or something else? :)

**Comment by lblasc** [comment]
@FrankXie05 just take a latest HEAD and use it as stable version, in time of writing commit is [e61a1f9](https://github.com/LuaJIT/LuaJIT/commit/e61a1f961ac3f063a5d80ca9b7b7e263810abf74) - 2022-08-07
Another option is to match version with one in nixpkgs, maybe you will feel more comfortable by using version which we tested, currently it is a bit behind upstream.

**Comment by FrankXie05** [comment]
@lblasc Thank you very much for your confirmation, we will keep the version whitch match to `nixpkgs` and keep updating. Thanks. 😀

**Comment by kloczek** [comment]
Gentle ping .. any update? 😋

**Comment by kloczek** [comment]
Is it possible release at least final 2.1.0? 🤔

**Comment by MikePall** [comment]
Obsolete with switch to rolling releases.
