### ISSUE TITLE
String methods ignore envinroments

### ISSUE THREAD

**Issue by 2048khz-gachi-rmx** [LuaJIT/LuaJIT#564]
```lua
local empty_env = {}
local func = setfenv(function() return ("Ding"):rep(100) end, empty_env)
print(func())
```
(screwed up code formatting a bunch of times, nice)

![image](https://user-images.githubusercontent.com/44749188/76674129-72b79380-65de-11ea-8f71-2ce8ffbdf41d.png)

they probably **should** only work when "string" is in the envinroment, otherwise there's no way to take the string library out

**Comment by hippi777** [comment]
hi there! :) 

this is the standard lua5.1 behavior, and there is nothing special in it other than a sandboxing gotcha...

```lua
> print(setfenv(function() return string, ('a'):rep(3) end, {})())
nil     aaa
```

`string.rep()` is exposed via the standard string metatable, but the global `string` table isnt, just how it is intended to work...

have fun, all the bests to u! :)
