### ISSUE TITLE
memory leaks in luajit when using opencl through FFI

### ISSUE THREAD

**Issue by pgmatg** [LuaJIT/LuaJIT#566]
A while ago I wrote fractal program in Lua. It works fine on my old Windows 7, and Windows 8 PCs.
I got a new laptop with Windows 10, and I run it with luajit 2.1.0 , that was working best for me in the past. Unfortunately some of the runs with various parameters failed with no errors or cause. And then I noticed that even successful execution is using too much memory. I tried my best to track down the problem using various builds of luajit from 2.0 to 2.1 , but only thing I can see is that memory leak is somehow connected to FFI calls to OpenCl api.
If someone is willing to take a look, I will provide complete code of program and required api dlls.
Attaching old demo lua code , that is also leaking on win10 , based on and using : https://github.com/malkia/luajit-opencl

[cl-demo.lua](https://github.com/LuaJIT/LuaJIT/files/4366334/cl-demo.txt)

**Comment by MikePall** [comment]
This is not the place to ask for debugging your code. Especially given the regrettably low quality of your code and the dependency on other (huge) frameworks.

Only short, self-contained and zero-dependency reproductions are accepted as bug reports.

**Comment by pgmatg** [comment]
> This is not the place to ask for debugging your code. Especially given the regrettably low quality of your code and the dependency on other (huge) frameworks.
> 
> Only short, self-contained and zero-dependency reproductions are accepted as bug reports.

I'm sure my coding skills are no where near even mediocre level, which is why I like Lua, because it makes it so much easier to write something that works. I myself have memory issues in my brain, which made it impossible to continue to work as a programmer. I do try to code a little bit still despite that it takes me 4-10 times to write anything resembling working program, and still make a lot of mistakes.
I'm sure that my post was not worded correctly, english is not my first language, and maybe not in the right place. I didn't mean someone of your level to waste your time debugging my cobbled together old code, but to maybe point me in the right direction, or suggest some easily available memory errors inspection tool, like purify. I used to use it to find memory bugs, unfortunately its no longer available for single user.
Also I now have a strong suspicion that something is overwriting memory after calls to opencl. as a result calls to os.time, math.random & etc. result in code execution stop.
