### ISSUE TITLE
IOS build issues

### ISSUE THREAD

**Issue by wanxing** [LuaJIT/LuaJIT#569]
MacOS: 10.15.4
Xcode:11.4
Luajit:2.1.0-beta3
sdk:iPhoneOS13.4.sdk

I got a Contradictory question, it building from source fails, so I use make MACOSX_DEPLOYMENT_TARGET=10.14, it built success, but the new version xcode get an error,  "Building for iOS, but the linked library 'libluajit.a' was built for macOS".  So what should I do?

**Comment by MikePall** [comment]
Looks like you're using inconsistent build flags. Please check the v2.1 (!) install instructions for iOS cross-compilation.
