### ISSUE TITLE
C++ Exception Interoperability on OSX x64

### ISSUE THREAD

**Issue by otristan** [LuaJIT/LuaJIT#571]
Hi,

It looks like C++ Exception Interoperability do not currently work on OSX when building x64 version with LLVM clang (which is now the default on OSX (even when you call GCC as there is an alias)).

Can you confirm this ?

I am wondering if installing GCC using brew could fix the issue as the doc says 
POSIX/x64, DWARF2 unwinding	GCC 4.3+ is listed as full Interoperability.

Thanks !

**Comment by corsix** [comment]
Seems to work for me in minimal test cases. You'll have to provide more details (OS version, compiler version, LuaJIT branch/version, which direction of interoperability, ...) and/or a minimal test case.

**Comment by otristan** [comment]
Interesting to know.
I'm using LuaJIT through Sol2
https://github.com/ThePhD/sol2

If I have an error in my lua script (just a typo for example), using regular Lua backend, I get an exception so I can catch the error and print the error. Hence from Lua to C++.

When using switching to LuaJIT it just fail.

OS is 10.15 with Xcode 11.3 built like that
make MACOSX_DEPLOYMENT_TARGET=10.14 XCFLAGS="-DLUAJIT_ENABLE_GC64 -DLUAJIT_ENABLE_LUA52COMPAT" BUILDMODE=static

Is there something to enable to have exception support ?

This might be a just an issue in Sol though :)

Thanks !
