### ISSUE TITLE
C++ issue when linking with '-static-libgcc -static-libstdc++' and throwing errors

### ISSUE THREAD

**Issue by n-ham** [LuaJIT/LuaJIT#573]
On ubuntu 18.04 specifically when linking with `-static-libgcc -static-libstdc++` I'm getting "Aborted (core dumped)" when after retrieving and removing a string parameter from the stack I try to push a string and throw an error.

I am wondering whether LuaJIT is expected to work when linking with '-static-libgcc -static-libstdc++' or will there likely be lots of other issues as well?

**Comment by MikePall** [comment]
This looks like an executable with broken unwinding. Probably missing unwind tables in some linked library.

I don't think this is an issue in LuaJIT. A stand-alone statically linked LuaJIT works fine. But this doesn't involve any C++ of course.

Search for "C++ static linking" and you see many complaints. I'm not sure this is fully supported everywhere.

**Comment by n-ham** [comment]
I just tried adding in all possible combinations of `-unwind-tables -funwind-tables -fexceptions` when linking and no love, still get `Aborted (core dumped)` when without `-static-libgcc -static-libstdc++` it throws the errors nicely. Thanks for the suggestion though.
