### ISSUE TITLE
Thread-local storage is not supported on macOS Mojave

### ISSUE THREAD

**Issue by elliottslaughter** [LuaJIT/LuaJIT#575]
I am unable to build on macOS Mojave as of the commit 44382e833a9334c19e47e64e8078a322026e094d. The error does not appear on the previous commit.

```
$ git reset --hard 44382e833a9334c19e47e64e8078a322026e094d
$ make MACOSX_DEPLOYMENT_TARGET=10.6
==== Building LuaJIT 2.0.5 ====
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C src
HOSTCC    host/minilua.o
HOSTLINK  host/minilua
DYNASM    host/buildvm_arch.h
HOSTCC    host/buildvm.o
HOSTCC    host/buildvm_asm.o
HOSTCC    host/buildvm_peobj.o
HOSTCC    host/buildvm_lib.o
HOSTCC    host/buildvm_fold.o
HOSTLINK  host/buildvm
BUILDVM   lj_vm.s
ASM       lj_vm.o
CC        lj_gc.o
BUILDVM   lj_ffdef.h
CC        lj_err.o
lj_err.c:293:8: error: thread-local storage is not supported for the current target
static __thread _Unwind_Exception static_uex;
       ^
1 error generated.
make[1]: *** [lj_err.o] Error 1
make: *** [default] Error 2
$ git clean -fxd
...
$ git reset --hard HEAD~1
HEAD is now at 8961a92 OSX: Don't set a default MACOSX_DEPLOYMENT_TARGET.
$ make MACOSX_DEPLOYMENT_TARGET=10.6
==== Building LuaJIT 2.0.5 ====
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C src
HOSTCC    host/minilua.o
HOSTLINK  host/minilua
DYNASM    host/buildvm_arch.h
HOSTCC    host/buildvm.o
HOSTCC    host/buildvm_asm.o
HOSTCC    host/buildvm_peobj.o
HOSTCC    host/buildvm_lib.o
HOSTCC    host/buildvm_fold.o
HOSTLINK  host/buildvm
BUILDVM   lj_vm.s
ASM       lj_vm.o
CC        lj_gc.o
BUILDVM   lj_ffdef.h
CC        lj_err.o
...
OK        Successfully built LuaJIT
==== Successfully built LuaJIT 2.0.5 ====
```

I'm on macOS 10.14.6 with XCode 11.3.1 (both XCode.app and command line tools are installed and up to date). The output of `cc --version` is included below. I don't have any reason to believe this is specific to the version of the OS or tools, but I'm including them for completeness.

```
$ cc --version
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by daurnimator** [comment]
> `$ make MACOSX_DEPLOYMENT_TARGET=10.6`

...

> I'm on macOS 10.14.6

update your deployment target to something newer than 10.6!

**Comment by elliottslaughter** [comment]
Yeah, you're right. Sorry about the noise.

In case anyone comes to look for this issue in the future, the oldest value of `MACOSX_DEPLOYMENT_TARGET` that builds on Mojave is 10.7.

**Comment by daurnimator** [comment]
Out of curiosity, why did you pick 10.6? (some old blog? if so, should shoot the author an email)

**Comment by elliottslaughter** [comment]
It was #484. Prior to the patch I noted above, 10.6 was the earliest deployment target that still built on Mojave.

Not that I care precisely what the value of the deployment target is, but I do in general want to avoid raising it too high since I may be building binaries not just for my own machine but also for others to use as well. (I assume this is the same sentiment that motivated having it set to 10.4 in the first place.)

**Comment by daurnimator** [comment]
> Not that I care precisely what the value of the deployment target is, but I do in general want to avoid raising it too high since I may be building binaries not just for my own machine but also for others to use as well. (I assume this is the same sentiment that motivated having it set to 10.4 in the first plac

FWIW, apple only support the last 3 releases of OSX, for e.g. [zig](https://ziglang.org/) we recently bumped the minimum version to 10.13.
