### ISSUE TITLE
About the luajit's depevopment status and its supporting for lua 5.3+?

### ISSUE THREAD

**Issue by hongyi-zhao** [LuaJIT/LuaJIT#576]
Hi,

The last release time of luajit was in on May 2, 2017.  So is luajit still in actively depevopment status? 
And does the current luajit support the lua 5.3+ or not?

Regards

**Comment by MikePall** [comment]
Well, have a look at the commits of the v2.1 branch.

There's no good reason to be fully compatible with Lua 5.3. Most Lua libraries you'd ever care about are compatible with 5.1. And LuaJIT already has the (few) relevant/useful features from 5.3. The poorly designed changes to the core numeric type will silently break lots of existing code. That's not something I intend to emulate.
