### ISSUE TITLE
ARM64 - corrupted local variable on trace exit / snapshot replay

### ISSUE THREAD

**Issue by javierguerragiraldez** [LuaJIT/LuaJIT#579]
At Kong we've hit a problem when running on ARM64 servers, which we think is caused by a LuaJIT bug.

the code in question is like this:

    local n_bulk = bulk.n * 4

    ....

    for i = 1, n_bulk, 4 do
        local b_key = bulk[i]
        local b_opts = bulk[i + 1]
        local b_cb = bulk[i + 2]

        if type(b_key) ~= "string" then
            error("key at index " .. i .. " must be a string for operation " ..
                ceil(i / 4) .. " (got " .. type(b_key) .. ")", 2)
        end

        ....
    end

where `bulk` is an array of "records", four elements each (key, opts, cb, arg) stored sequentially in an array, and a 'n' entry with the number of records.  As far as we can tell, it isn't corrupted; specifically, the "key" entries are always strings and the 'n' entry does have the right number (usually 2 or 3 in our case).

the error message we get is "key at index 2.1217691418087e-314 must be a string for operation 1 (got nil)"

where the surprise is the floating value in the index, which is always exactly the same value.  The hex representation is 0x00000000fff90009, which points to a misplaced NaN tag, given that a value of 0xfff9000000000009 would be appropriate.

Analyzing trace dumps, there are several examples like:

    ---- TRACE 649 start 640/0 mlcache.lua:979
    0062  TGETV   12   1  11       (mlcache.lua:979)
    ---- TRACE 649 abort mlcache.lua:979 -- NYI: mixed sparse/dense table

if I understand correctly, this means that on exit 640/0, the index was already a non-integer number, so it's not compiled and falls back to the interpreter.

Trace 640 starts just within this loop, and starts like this:

    ---- TRACE 640 start 620/0 mlcache.lua:979
    0062  TGETV   12   1  11       (mlcache.lua:979)
    0063  ADDVN   13  11   1  ; 1       (mlcache.lua:980)
    0064  TGETV   13   1  13       (mlcache.lua:980)
    ....

    ---- TRACE 640 IR
    ....              SNAP   #0   [ ---- ---- ]
    0001 x0       int SLOAD  #11   RI
    0002       >  int LE     0001  +2147483643
    0003 x27   >  int SLOAD  #10   TI
    0004 x4    >  tab SLOAD  #3    T
    0005 x15      int FLOAD  0004  tab.asize
    0006       >  p32 ABC    0005  0001
    0007 x14      p64 FLOAD  0004  tab.array

on the failing exits, register x27 already contains the value 0x00000000fff90009, apparently this triggered the type guard at instruction 0003

On the rest of the trace, all operations on the SSA value at 0003 use register w27, given that the index fits comfortably in 32 bits.  My hypothesis is that at some point after some loop iterations an index value of 9 is written or read from the stack or the snapshot as a 32bit value instead of the full 64 bits, resulting in the wrong bit pattern.

I haven't been able to find any such discrepancy between w27 and x27 in the generated mcode; maybe this happens at the snapshot replay when falling back to the interpreter?.

Looking in the VM implementation (vm_arm64.dasc), x27 and w27 are used for RA and RAw "temporary" variables, but mentioned that they should be saved.  Could this save/restore be using the wrong wordsize?

I've also compared with the traces generated when the bug isn't triggered.  In those cases, there's no trace starting on this loop, either because it's fully unrolled, or because the traces are aborted with "inner loop in root trace".  and of course, none of these "NYI: mixed sparse/dense table" aborts.  This seems to hint that the problem occurs because of the specific register use or snapshot layout.

**Comment by MikePall** [comment]
First, please try to come up with a small and isolated test case.

I'd check the mcode for any traces that join to trace 640. Though the stack restore code in `asm_stack_restore` and `asm_tvstore64` looks benign.

Another possibility would be that the `TISNUM` and`TISNUMhi` constants in the interpreter (x24 and x25) are somehow corrupted or mixed up. But I can't find anything suspicious in `vm_arm64.dasc`.

Before proceeding, please confirm that you're using an unmodified copy of the original LuaJIT repo for your tests.

**Comment by thibaultcha** [comment]
I've isolated the issue into a minimalistic OpenResty application (much smaller than Kong) - alas, not a LuaJIT-only test case - yet.

The good news here is that this has been fixed in OpenResty's LuaJIT fork in this commit: https://github.com/openresty/luajit2/commit/0fe9339bd731d6d824edd90fb5c7550ae594f436. The latest version of Kong uses an OpenResty version that does not bundle the aforementioned commit. @siddhesh also proposed another ARM64 fix here: https://github.com/openresty/luajit2/commit/73421198ea814ff5e73b38c55848361c8c51558d.

@MikePall What are your thoughts on these fixes, and would you consider them for inclusion in this repository?

**Comment by thibaultcha** [comment]
Nevermind about porting the fix to this repository. The issue seems to have been introduced by the numerous patches applied by the OpenResty team on LuaJIT's ARM64 support. The fork received quite a lot of those ARM64 patches, I wonder which ones should be ported upstream, if any.

We can probably close this issue?

**Comment by MikePall** [comment]
The first one is already covered by https://github.com/LuaJIT/LuaJIT/commit/b33e3f2d441590f4de0d189bd9a65661824a48f6 .

The second 'fix' looks suspicious and I cannot locate a corresponding test case. Please open a new issue (not a PR) with a test case.
