### ISSUE TITLE
warning when making on Windows

### ISSUE THREAD

**Issue by n-ham** [LuaJIT/LuaJIT#580]
I get the following warning when building the official beta release on Windows (I have quite a few warnings turned on for my project).

```
"CC        lj_alloc.o"
lj_alloc.c:154:14: warning: 'DIRECT_MMAP' defined but not used [-Wunused-function]
 static void *DIRECT_MMAP(size_t size)
```

**Comment by MikePall** [comment]
Oops, there's a real bug behind that. Fixed. Thank you very much!
