### ISSUE TITLE
asm: RENAME IR invariant violation

### ISSUE THREAD

**Issue by igormunkin** [LuaJIT/LuaJIT#584]
## Intro

In scope of the [issue](https://github.com/tarantool/tarantool/issues/4252) we faced a platform misbehave. After the deep investigation I reduced the test case to [this Lua chunk](https://gist.github.com/igormunkin/18cb6afe5a495bce31f772d453f3117e#file-4252-lua).

If one runs the chunk with disabled sink optimization the following output is produced:

```bash
$ ./luajit 4252.lua .
-------- -sink ------------------------------------------------------------
a       b       c       q       w       e
a       b       c       q       w       e
a       b       c       q       w       e
```

Whether sink is enabled the failure occurs:
```bash
$ ./luajit 4252.lua
-------- +sink ------------------------------------------------------------
a       b       c       q       w       e
a       b       c       q       w       e
4252.lua:29: attempt to call local 'gen_x' (a nil value)
stack traceback:
        4252.lua:63: in function 'gen_x'
        4252.lua:29: in function 'gen_x'
        4252.lua:56: in function <4252.lua:50>
        [C]: in function 'xpcall'
        4252.lua:50: in main chunk
        [C]: at 0x56193a8b8f0a
```

It's worth to mention that the failure doesn't explicitly relate to sink optimization, *but* I failed to reproduce it in other ways. That's why I created a [gist](https://gist.github.com/igormunkin/18cb6afe5a495bce31f772d453f3117e) with trace dumps for both succeed and failed runs.

## Why the failure happens?

* While [trace #3](https://gist.github.com/igormunkin/18cb6afe5a495bce31f772d453f3117e#file-4252-w-sink-dump-L723) execution there is a sunk table ([`0063`](https://gist.github.com/igormunkin/18cb6afe5a495bce31f772d453f3117e#file-4252-w-sink-dump-L827)) that need to be created while restoring Lua stack on [trace exit #4](https://gist.github.com/igormunkin/18cb6afe5a495bce31f772d453f3117e#file-4252-w-sink-dump-L1163).
* All stores to that table are also sunk ([`0066`](https://gist.github.com/igormunkin/18cb6afe5a495bce31f772d453f3117e#file-4252-w-sink-dump-L830) and [`0071`](https://gist.github.com/igormunkin/18cb6afe5a495bce31f772d453f3117e#file-4252-w-sink-dump-L836)) and need to be restored on that trace exit.
* The value to be stored in scope of the `0066` IR reference (i.e. [`0051`](https://gist.github.com/igormunkin/18cb6afe5a495bce31f772d453f3117e#file-4252-w-sink-dump-L815)) is an operand of the [`0124`](https://gist.github.com/igormunkin/18cb6afe5a495bce31f772d453f3117e#file-4252-w-sink-dump-L893) PHI node, since it is changed within both invariant and variant trace parts.
* While assembling `0124` IR reference (trace is assembled in linear backwards order) register allocator picks `xmm6` register for [`0104`](https://gist.github.com/igormunkin/18cb6afe5a495bce31f772d453f3117e#file-4252-w-sink-dump-L871) destination and also set it as a hint for `0051` destination.
* In scope of assembling the **guarded** [`0110`](https://gist.github.com/igormunkin/18cb6afe5a495bce31f772d453f3117e#file-4252-w-sink-dump-L877) IR reference, [snap #4](https://gist.github.com/igormunkin/18cb6afe5a495bce31f772d453f3117e#file-4252-w-sink-dump-L839) allocation is triggered. As I mentioned above the sunk table and all corresponding stores have to be restored. While assinging a register to `0051` IR reference, register allocator misses the hint (since `xmm6` is still used as a destination for `0104`) and picks the next free FPR (i.e. `xmm5`).
* `0104` IR reference assembling is a bit tricky: `<add>` is a destructive op on 2-operand x86 platform, ergo, `0104` destination has to coincide with its left operand (i.e. `0051`) destination. Considering everything above this condition is not met in our case.
* Since `0104` IR reference is a PHI operand, register allocator appends an auxiliary [`RENAME`](http://wiki.luajit.org/SSA-IR-2.0#miscellaneous-ops) IR and emits the corresponding `<mov>` instruction:
  ```
  5619649cf8a4  movaps xmm5, xmm6
  ```
* However, there are other **guarded** IR references to be assembled further also referencing exitno#4. E.g. [`0102`](https://gist.github.com/igormunkin/18cb6afe5a495bce31f772d453f3117e#file-4252-w-sink-dump-L869) one, where the example leaves the trace:
  ```
  5619649cf88b  cmp dword [rbx+r15*8+0x4], -0x01
  5619649cf891  jnz 0x5619649c0020      ->4
  ```
* This is the place where `RENAME` invariant is violated: the side exit is emitted prior to the instruction setting the value to be used for guest stack restoration.
* As a result while restoring guest stack non-synced register is used for the corresponding store to the table, invalid value is restored, <gen_x> is misfetched (i.e. is nil) and the corresponding error occurs:
  > attempt to call local 'gen_x' (a nil value)

## What's next?

As you can see sink optimization is used only to reduce register pressure while trace assembling and this leads to emitting an invalid `RENAME` IR.

@MikePall, I discussed the issue with @sergos and @igelhaus and can propose the following:
* Since all snapshots are placed before assembling process is started, we can't emit another one without IR rearranging and mcode reassembling. Emitted `RENAME` can trigger it if there are **guarded** IR references left to be assembled (similar to the way the second emitted `RENAME` IR triggers). Considering your [comment](https://github.com/LuaJIT/LuaJIT/blob/v2.1/src/lj_asm.c#L2314) regarding traces percentage with `RENAME`s it *might* be a solution.
* All such `RENAME`s can be postponed and emitted in scope of `loopref` assembling (like the others emitted within `asm_phi_shuffle`).

Nevertheless, it's a considerable design change in assembly machinery, so I decided to file an issue first.

**Comment by MikePall** [comment]
Confirmed bug.

I need some time to think about a good solution.

**Comment by MikePall** [comment]
Fixed. The check for inconsistent renames didn't consider sunk values. Bloom filters to the rescue.

Thank you for your patience!

**Comment by igormunkin** [comment]
@MikePall, thanks a huge for the fix (it's committed on 10 month anniversary, heh), but there _might_ be a [typo](https://github.com/LuaJIT/LuaJIT/commit/33e3f4badfde8cd9c202cedd1f4ed9275bc92e7d#diff-8536b1d569297d168f98f1ba252fbb23041961241f1e13c09f1e634e32f91bcaR829) in condition. Otherwise the branch for `RID_SUNK` "allocation" [few lines below](https://github.com/LuaJIT/LuaJIT/commit/33e3f4badfde8cd9c202cedd1f4ed9275bc92e7d#diff-8536b1d569297d168f98f1ba252fbb23041961241f1e13c09f1e634e32f91bcaR833) is a dead one, isn't it?

For the history: the issue is closed via 33e3f4b.

**Comment by MikePall** [comment]
Nope. Go to split view to understand what I did there. `!= RID_SUNK` vs. `== RID_SINK`.

**Comment by igormunkin** [comment]
> Nope. Go to split view to understand what I did there. `!= RID_SUNK` vs. `== RID_SINK`.

Yep, my bad: I've missed the parentheses. Everything is fine with the change in condition.
