### ISSUE TITLE
Cross-compiling 2.1.0-beta3 for iOS simulator

### ISSUE THREAD

**Issue by Riyaaaaa** [LuaJIT/LuaJIT#585]
I want to build static library for iOS and iOS simulator. I tried to build along document... in the following. The library built by this works well on real device.

```
ISDKP=$(xcrun --sdk iphoneos --show-sdk-path)
ICC=$(xcrun --sdk iphoneos --find clang)
ISDKF="-arch arm64 -isysroot $ISDKP"
make DEFAULT_CC=clang CROSS="$(dirname $ICC)/" TARGET_FLAGS="$ISDKF" TARGET_SYS=iOS
```

But iOS simulator's architecture is not ARM64 but x86_64. So the library occur linker errors when build my app for iOS simulator. 

So I tried to build another library for exclusive simulator. 

```
ISDKP=$(xcrun --sdk iphonesimulator --show-sdk-path)
ICC=$(xcrun -sdk iphonesimulator -find clang)
ISDKF="-arch x86_64 -isysroot $ISDKP"
make DEFAULT_CC=clang CROSS="$(dirname $ICC)/" TARGET_FLAGS="$ISDKF" TARGET_SYS=iOS
```

But make command does not success above options.  It occurred error following.

```
CC        lib_os.o
lib_os.c:52:14: error: 'system' is unavailable: not available on iOS
  int stat = system(cmd);
             ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/usr/include/stdlib.h:190:6: note: 
      'system' has been explicitly marked unavailable here
int      system(const char *) __DARWIN_ALIAS_C(system);
         ^
1 error generated.
make: *** [lib_os.o] Error 1

```

How do you make workable library on iOS simulator? Or... If you know how to make workable both real device and simulator, please tell me. 

Thank you.

**Comment by MikePall** [comment]
Please try to add the following to `src/Makefile` after the last line setting `XCFLAGS`:

`XCFLAGS+= -DLJ_NO_SYSTEM=1`
