### ISSUE TITLE
non-ASCII file paths Windows 

### ISSUE THREAD

**Issue by lilitZak** [LuaJIT/LuaJIT#588]
I work on Windows and have file paths with non-ASCII symbols. For non-ASCII symbols windows using wstring. I am doing the conversion and pass them to luaL_dofile but it fails with can not find a file. 

Here is my example of code:

std::wstring wstr_path = "non-ASCII path"

using convert_type = std::codecvt_utf8_utf16<wchar_t>;
std::wstring_convert<convert_type, wchar_t> converter;
std::string str_path = converter.to_bytes(wstr_path);
luaL_dofile(mRoot, str_path.c_str());

**Comment by MikePall** [comment]
This is a general problem of Windows and conversion to 8 bit strings. It won't work in plain Lua either.

There are various add-on libraries for working with Windows data types. I don't have any recommendations, maybe ask on the Lua mailing list.

**Comment by corsix** [comment]
On very recent versions of Windows 10, your application can set the ANSI codepage to UTF8, at which point your code might work. Alternatively, you need to convert from UTF16 to whatever your process' ANSI codepage is, which is likely not UTF8 (unless you've gone out of your way to make it so).

**Comment by lilitZak** [comment]
Hi, thank you for your responses. 
One more question is there any plan to add  _wfopen support?
I think it will be an ideal solution for such cases.

**Comment by MikePall** [comment]
That alone won't work. One would need to pull in the whole UTF-16 and codepage conversion stuff and lots more. This is simply outside of the scope of the LuaJIT core. There are add-on libraries that deal with this, see above.

**Comment by MikuAuahDark** [comment]
I recently have this function that monkeypatch io.open to accept UTF-8 in Windows using FFI. https://gist.github.com/MikuAuahDark/d62ff287d56a8ac402893fd710347ac0

I can't say that's ideal, but it seems working based on my testing.
