### ISSUE TITLE
Replace table.sort() with pure Lua code

### ISSUE THREAD

**Issue by stepelu** [LuaJIT/LuaJIT#59]
Currently table.sort() cannot operate on FFI data structures.
A pure Lua version would solve this issue and most likely gain in efficiency as well.

On the topic, @MikePall previously suggested [1] the use of the Smoothsort algorithm.
[1] http://www.freelists.org/post/luajit/Fast-sorting-of-FFIzed-data,7

**Comment by ladc** [comment]
I've looked into this, and my implementation of the smoothsort algorithm in
Lua did not appear to surpass Francesco Abbate's implementation of
quicksort (with heapsort fallback). I'll post the code here, if anyone
feels like optimizing it further. In any case it's essentially quite
branchy, and even though the number of comparisons is lower in
nearly-sorted cases it doesn't seem to compensate for the constant overhead
for the array sizes that I've tried out.

**Comment by ladc** [comment]
Here it is: https://gist.github.com/ladc/26e3c35d6839365e91cd
And apparently there's another implementation here: https://gist.github.com/scythe/74eb568a314f5ec5692f

Mike mentioned branch-free versions of Shell sort or Comb sort as other possible candidates.

**Comment by CapsAdmin** [comment]
Just FYI that other implementation doesn't seem to sort properly since:

for i,v in ipairs(tbl) do
	if (tbl[i + 1] or math.huge) < v then
		error("badly sorted")
	end
end

triggers.

**Comment by drbo** [comment]
Both shellsort and combsort are asymptotically slower, though -- O(n<sup>2</sup>) in the worst case, and shellsort is O(n*log<sup>2</sup>n) even in the best case.

Branchless sorting seems to be an open research problem -- I don't believe any asymptotically efficient algorithms are known.  Once trace stitching gets implemented, a C sort might be best, assuming that the JIT can trace the comparison metamethods even when called by C.  I don't think there will be a perfect solution until LuaJIT gets hyperblock scheduling.  `qsort` and an FFI callback might be faster but dooms the _caller_ of `table.sort` to never be JIT-compiled.

**Comment by stepelu** [comment]
For reference, Francesco Abbate's implementation should be the following:
http://www.freelists.org/post/luajit/Lua-quicksort-implementation

**Comment by franko** [comment]
Hi,

I landed here by accident. The implementation I made for the quicksort algorithm, adapted from the gcc libstdc++, is available from the gsl shell repository in the algorithm file:

https://github.com/franko/gsl-shell/blob/master/algorithm.lua

as Lesley mentioned the algorithm will actually switch to heapsort if thing get bad to avoid worst-case O(N^2) behavior.

**Comment by henriquegemignani** [comment]
@franko This code's license (GPL) is incompatible with LuaJIT's MIT license.
