### ISSUE TITLE
"Missing fp64 helper definitions for this compiler" when using Clang as host compiler in Windows

### ISSUE THREAD

**Issue by MikuAuahDark** [LuaJIT/LuaJIT#595]
This happends when I try to compile LuaJIT under ARMv7 using Android NDK toolchain. Compiling for ARMv8/ARM64 and any x86(-64) is fine.

The Clang 10.0.0 compiler I'm using has GNU-style command-line options but targets MSVC ABI by default which can be found [here](https://releases.llvm.org/download.html). My guess, `__GNUC__` is not defined for my case, so I have to patch `lj_ircall.h` like this.
```patch
diff --git a/src/lj_ircall.h b/src/lj_ircall.h
index 9b3883b..d19edcb 100644
--- a/src/lj_ircall.h
+++ b/src/lj_ircall.h
@@ -330,7 +330,7 @@ extern double lj_vm_sfmax(double a, double b);
 #endif
 
 #if LJ_HASFFI && LJ_NEED_FP64 && !(LJ_TARGET_ARM && LJ_SOFTFP)
-#ifdef __GNUC__
+#if defined(__GNUC__) || defined(__clang__)
 #define fp64_l2d __floatdidf
 #define fp64_ul2d __floatundidf
 #define fp64_l2f __floatdisf
```
Is that fine? Is even using Clang in Windows as host compiler a supported scenario afterall?

**Comment by MikePall** [comment]
I've added checks for `__clang__` at various places.

I never tried, but Clang ought to work as host compiler on Windows, too.
