### ISSUE TITLE
Is there an actual list of options anywhere for using jit.opt.start()?

### ISSUE THREAD

**Issue by VaasKahnGrim** [LuaJIT/LuaJIT#596]
So I'm currently looking for something to expirement with rn and I stumbled across this function and the only options I seem to find are legit the same exact options which are 2, "-dce", "hotloop=10" or "hotexit=2". but nowhere can I seem to find an exact list of options that can be put into it

**Comment by ExtReMLapin** [comment]
JIT_PARAMDEF in source code

**Comment by ExtReMLapin** [comment]
Also

```c
/* Optimizations names for -O. Must match the order above. */
#define JIT_F_OPT_FIRST		JIT_F_OPT_FOLD
#define JIT_F_OPTSTRING	\
  "\4fold\3cse\3dce\3fwd\3dse\6narrow\4loop\3abc\4sink\4fuse"
```

**Comment by GitSparTV** [comment]
Also this list exists here: http://luajit.org/running.html

**Comment by MikePall** [comment]
Yes, the option list is in the "Running LuaJIT" page.

But please note it's not a good idea to apply some random VM options. Unless you're tracking down a bug in the VM, or just want to experiment with the VM, or have solid evidence in the form of application-specific benchmarks, better stay with the defaults.
