### ISSUE TITLE
table.sort doesn't support yielding

### ISSUE THREAD

**Issue by GitSparTV** [LuaJIT/LuaJIT#597]
LuaJIT has true coroutines by Coco.
Coco page mentions:
> Yield across callbacks (table.foreach(), dofile(), ...).

`table.foreach` is here (it wasn't implemented in pure lua that time), but `table.sort` doesn't work that way.
I searched in this issue tracker and on freelist, didn't find any mentions about this issue.
So can we yield in it's callback or not?

**Comment by MikePall** [comment]
Coco is used by LuaJIT 1.x. LuaJIT 2.x uses a different coroutine model.

`table.sort` does not support yielding. It doesn't work in plain Lua, too. It wouldn't be particularly useful to yield from a sort comparator, anyway.

**Comment by GitSparTV** [comment]
Oh, didn't test in plain Lua. Thanks for clarifying
I had some ideas to yield in it, for example if the sorting function is complex or the table is large. And it's NYI.

Is there a list of all scopes/placed where you can (or can't) yield?
