### ISSUE TITLE
nyi when allocating structs that contain arrays

### ISSUE THREAD

**Issue by samiam308** [LuaJIT/LuaJIT#598]
hello

here is the simplest example of what i am trying to do  
```
local ffi = require "ffi"
ffi.cdef [[
    struct mystruct {
        int myarray[4];
    };
]]
local mystruct_t = ffi.typeof("struct mystruct")

while true do
    local mystruct = mystruct_t()
end
```

when run with `-jv` i get  
```
[TRACE --- h.lua:9 -- NYI: unsupported C type conversion at h.lua:10]
[TRACE --- h.lua:9 -- NYI: unsupported C type conversion at h.lua:10]
[TRACE --- h.lua:9 -- NYI: unsupported C type conversion at h.lua:10]
[TRACE --- h.lua:9 -- NYI: unsupported C type conversion at h.lua:10]
[TRACE --- h.lua:9 -- NYI: unsupported C type conversion at h.lua:10]
[TRACE --- h.lua:9 -- NYI: unsupported C type conversion at h.lua:10]
[TRACE --- h.lua:9 -- NYI: unsupported C type conversion at h.lua:10]
[TRACE --- h.lua:9 -- NYI: unsupported C type conversion at h.lua:10]
[TRACE --- h.lua:9 -- NYI: unsupported C type conversion at h.lua:10]
[TRACE --- h.lua:9 -- NYI: unsupported C type conversion at h.lua:10]
[TRACE --- h.lua:9 -- NYI: unsupported C type conversion at h.lua:10]
```
ive tested this all the way down to
```
struct mystruct {
    int8_t myarray[1];
};
```
allocating arrays by themselves, as in `ffi.typeof("int[4]")` compiles just fine. same with having 4 int fields in the struct.

ive looked through all the docs and i havent seen anything about this case. is it a bug or am i missing something?

im running 2.1. ive tried the luajit from ubuntu apt and a fresh build from this repository.

thanks! :)

**Comment by MikePall** [comment]
NYI cases are mentioned at the end of the FFI semantics page.

**Comment by samiam308** [comment]
i dont see this case on either the [nyi page in the wiki](http://wiki.luajit.org/NYI) or the [ffi semantics](https://luajit.org/ext_ffi_semantics.html).

> 2.1: Not for non-default init of VLA/VLS or > 128 bytes or > 16 array elements.

-wiki

> * Allocations of variable-length arrays or structs.
> * Allocations of C types with a size > 128 bytes or an alignment > 8 bytes.

-ffi semantics


`ffi.sizeof(mystruct_t)` returns 16. `myarray` has only 4 elements. the struct is not variable length.

this nyi case can be described as "allocations of structs containing arrays". i cant find a case like this in the docs.

**Comment by sonoro1234** [comment]
You should check the docs from this repo.

**Comment by samiam308** [comment]
for this repo:

> * Non-default initialization of VLA/VLS or large C types (> 128 bytes or > 16 array elements.

-ffi semantics

there is still nothing written about this case that i can see

**Comment by MikePall** [comment]
The array is nested in a struct. I.e. the 3rd clause applies.

But arguing about the docs is not furthering the cause. Do you intend to contribute a patch to resolve this NYI? The relevant code is in `src/lj_crecord.c crec_alloc()`

**Comment by samiam308** [comment]
thanks mike!  
i wasnt trying to argue, sorry if my question came off as one.

if arrays count as nested structs, i can try fixing it. ill look through the code and see what i can do.
