### ISSUE TITLE
Add compressed bytecode support

### ISSUE THREAD

**Issue by drbo** [LuaJIT/LuaJIT#60]
Being able to save and load compressed bytecode would be useful for [snabb](https://github.com/SnabbCo).

I have an implementation almost ready.

**Comment by lukego** [comment]
See also SnabbCo/luajit#7.

**Comment by slime73** [comment]
This doesn't seem like something that should be included with LuaJIT, as it's not a "catch-all program with a language attached". Including a decompression library inside the LuaJIT library is not something I'd expect or want.

There are various compression libraries / algorithms, each with their own compression speed, compressed size, and decompression speed tradeoffs. Different situations call for different combinations of those tradeoffs, and so different libraries – there is no one-size-fits-all compression library.

Plain text often compresses better than generated bytecode does, as well. I'm guessing that just using LZ4[hc] or zip or LZMA or what have you on the source lua files will result in smaller file sizes than compressing the bytecode.


Feature creep and bloat is a really easy and dangerous trap to encounter when there isn't a single unified leadership for a project.

**Comment by lukego** [comment]
> This doesn't seem like something that should be included with LuaJIT, as it's not a "catch-all program with a language attached".

Reasonable point of view. I hope that the new Github-based workflow for LuaJIT would make it easy for me to merge the compression support into my tree while you don't merge it into your tree (but we would both see the PR and have the opportunity to decide).

I don't know who will decide what lands on the master branch of this repository. That is less important to me though: all I need is a way to cooperate with other people who share my interests/requirements. This would at least feed upstream in that changes under consideration would have already been battle-tested in applications that can be tracked on github.

**Comment by MikePall** [comment]
Wrong approach. Such a feature does not belong into the core. And it depends on 3rd party libraries, too.

The correct approach is to add pluggable stream loaders (just like searchers are already pluggable). Then you can develop any such extension separately.

But, please for the sake of my time ... discuss and implement this *after* I'm gone.

**Comment by lukego** [comment]
> But, please for the sake of my time ... discuss and implement this after I'm gone.

Mike, have you considered pressing `Fork` and doing your work on a private Github repository without distractions? Then you could hand over this repository right away to the new leadership and they can start organizing the new contributors who have answered your call.

**Comment by drbo** [comment]
As the one who implemented compressed bytecode support, I think I can provide a library-based solution.  It won't be completely transparent, but it could get the job done.

In retrospect, I believe that Mike was correct in excluding this &ndash; a library can do this equally well, and it can even be fully transparent to Lua code.
