### ISSUE TITLE
getentropy not exist on iOS9

### ISSUE THREAD

**Issue by zhaozg** [LuaJIT/LuaJIT#602]
Luajit-2.1 head crash on iOS9, and I checked crash log, found that because `https://github.com/LuaJIT/LuaJIT/blob/v2.1/src/lj_prng.c#L190` access getentropy not found.

If can, please make getentropy as a configable when build luajit.

**Comment by MikePall** [comment]
Fixed.

**Comment by zhaozg** [comment]
Thank you very much
