### ISSUE TITLE
ffi.new("char[4]", "1234") is not JIT-compiled

### ISSUE THREAD

**Issue by ExtReMLapin** [LuaJIT/LuaJIT#604]
Hello,

It seems like this part of code "works"

```Lua
ffi.new("char[4]", "1234") -- "1234"
```

Unless I misunderstood something, this is not what you're supposed to do, you're supposed to do : 

`ffi.new("char*", "1234") -- "1234"`

Since when using `char[4]`, `ffi.new` should hold an initialization value as the second parameter, like this : 

`ffi.new("char[4]", 0x41) -- "AAAA"` 

But it seems like it still works (with some kind of special type check ?)

However, even if it works perfectly, the jit compiler refuses to compile to code and states : 

`[TRACE --- md5_main.lua:5 -- bad argument type at md5_main.lua:6]`

```Lua
local ffi = require("ffi")
local i = 0
while (i < 5000) do
	local cInt = ffi.new("const char[4]", "lol1")
	i = i + 1
end
```

If it refuses to jit-compile it, why not throw an lua error instead of allowing it in interpreted mode ?

**Comment by MikePall** [comment]
Initializing an FFI array of chars with a Lua string copies the characters. This is a perfectly valid operation.

If you want it JIT-compiled then please submit a patch. Closing here.
