### ISSUE TITLE
LuaJIT intermittent bug on 32-bit mipsel

### ISSUE THREAD

**Issue by jpc** [LuaJIT/LuaJIT#610]
Hi,

I have a fairly complex app that fails intermittently when running with LuaJIT on Linux on a 32-bit mipsel chip. I managed to printf-debug it down to this function:

```
function CT._default:_handle_rx(data, flags, final)
  local b = self.buffer
  local r
  if b == false then
    r = data
  else
    b[#b+1] = data
    if final then
      data = table.concat(b)
      for i=1,#b do b[i] = nil end
      r = data
    end
  end
  if r then self:_inbox_put(self:_decode(r)) end
end
```

In the problematic case `data` is a non-empty string (`"n\007\000"` or `"n\007\001"`), `final` is always true and `self.buffer` is always an empty table so `r` should never be `nil` or `false` yet the sometimes `self:_decode` and `self:_inbox_put` do not get called. The code is old and could be optimized but it worked correctly for the past 10 years on PUC Lua (I also tested on x86_64 LuaJIT but not a lot).

I managed to capture several JIT traces (using `require'jit.dump'.on("","/tmp/luajit-trace")`) for both successful and unsuccessful runs of the program (see the attached files). The error seems to be triggered by a trace that starts at the entry to `_handle_rx` at `sepack.lua:285`. If the trace gets incorporated into a larger one that starts at the caller of `_handle_rx` (`parse_packet`) at `sepack.lua:161` (or is not JITed at all) then everything works fine.

I've attached 4 dumps of failed runs. I managed to confirm that in the case of luajit-trace-2 flushing the trace 41 (`require'jit'.flush(41)`) fixed the issue. The same can be said for trace 40 in luajit-trace-3 and trace 45 in luajit-trace-4 (but flushing trace 56 here did not help). I could not run interactive code during luajit-trace-1.

[luajit-trace-1.txt](https://github.com/LuaJIT/LuaJIT/files/5059913/luajit-trace-1.txt)
[luajit-trace-2.txt](https://github.com/LuaJIT/LuaJIT/files/5059914/luajit-trace-2.txt)
[luajit-trace-3.txt](https://github.com/LuaJIT/LuaJIT/files/5059915/luajit-trace-3.txt)
[luajit-trace-4.txt](https://github.com/LuaJIT/LuaJIT/files/5059916/luajit-trace-4.txt)

I also attach two traces of correct runs for comparison:

[luajit-trace-ok.txt](https://github.com/LuaJIT/LuaJIT/files/5059918/luajit-trace-ok.txt)
[luajit-trace-ok-2.txt](https://github.com/LuaJIT/LuaJIT/files/5059917/luajit-trace-ok-2.txt)

I do not have a reduced test case because the app is a pretty big real-time embedded system and the bug is pretty difficult to reproduce (occurs only once in about 30 runs). I hope the traces will be helpful in diagnosing the problem.

**Comment by MikePall** [comment]
First, you haven't indicated which version of LuaJIT you're using. Always try to reproduce with v2.1 git HEAD, before reporting an issue.

Also, your traces are undecipherable, because there's a mismatch between the installed `jit.*` modules used for dumping and the LuaJIT core. This breaks the IR dump. 

If you have difficulties reproducing, then _temporarily_ (!) turn off ASLR (`echo 0 | sudo tee /proc/sys/kernel/randomize_va_space`) and set all of the `LUAJIT_SECURITY_*` defines at the end of `lj_arch.h` to 0.

**Comment by jpc** [comment]
Thank you for getting back to me so quickly. I am sorry, I did upgrade the LuaJIT library to 2.1 HEAD but forgot to repackage my app with the new `jit` library.

I updated the jit lib and ran a test with the adjustments you recommended but when I compare the IR dump of my traces I found only one difference that looks significant:
`0033    int ALEN   0006  0010`
changed to
`0033    int CALLL  lj_tab_len  (0006)`
with the new jit lib. Is there some way for me to double check I am running the correct jit lib version?

**Comment by jpc** [comment]
I managed to get one bad trace (with new 'jit', security bits set to 0 but `randomize_va_space` set to 2) in which flushing trace 46 fixed the issue while flushing 53 did not.

[luajit-trace-bad-3.txt](https://github.com/LuaJIT/LuaJIT/files/5062130/luajit-trace-bad-3.txt)

**Comment by MikePall** [comment]
Well, I don't see anything obviously wrong in the IR or machine code. But it's too big to inspect all of it.

To debug this further, we really need a reduced test case without external depdendencies. It's OK if it only fails intermittently.

That said, `-jdump=+rsx` would be helpful. Also, if you can repro this on non-MIPS architectures or not.

If the IR shows `ALEN` then you're running recent code and the (currently) matching `jit.*` files.

Was this already failing before you upgraded LuaJIT? If not, then one thing to try would be to roll back to b2307c8a, before the introduction of the table length optimizations (yes, you need to roll back the `jit.*` files, too). But that's just a wild guess.

**Comment by jpc** [comment]
I can add a little bit of background: My test consist of starting the app and changing the state of a physical input on an embedded board. This causes a microprocessor to send some bytes through a serial port, these get read through the Linux kernel driver and are fed into a C procedure via the LuaJIT FFI. The result of the procedure then goes though some bitop manipulations and finally the _handle_rx method is called. This whole cycle utilizes several coroutines communicating via mailboxes and a scheduler (implemented in Lua).

I ran that test 150 times with `/proc/sys/kernel/randomize_va_space` set to 0 and failed to reproduce the error. With `/proc/sys/kernel/randomize_va_space` set to 2 (the default on my OpenWRT) I get a failure after running 3, 27, 17, 5 times.

I've attached two more failed traces:
[luajit-trace-bad-5.txt](https://github.com/LuaJIT/LuaJIT/files/5062388/luajit-trace-bad-5.txt)
[luajit-trace-bad-6.txt](https://github.com/LuaJIT/LuaJIT/files/5062389/luajit-trace-bad-6.txt)

OK trace with `/proc/sys/kernel/randomize_va_space == 0`:
[luajit-trace-ok-2.txt](https://github.com/LuaJIT/LuaJIT/files/5062392/luajit-trace-ok-2.txt)

OK trace with `/proc/sys/kernel/randomize_va_space == 2`:
[luajit-trace-ok-3.txt](https://github.com/LuaJIT/LuaJIT/files/5062395/luajit-trace-ok-3.txt)

**Comment by jpc** [comment]
Thanks for the reply. I found the problem on 322db0208160169cbfcd6cc2f93d5e0dfcb2081e (so before the b2307c8)  and today I test on 94d4abcca966df2cc423e821bcacd04898f73117.

**Comment by jpc** [comment]
I wanted to make sure I am not misrepresenting the flow through the _handle_rx method so I added `print(string.format("%q", data), flags, final, self.buffer and #self.buffer)` at the entry to the function and got `"n\7\0"	0	true	0` for a failed run. So _handle_rx really should call `_decode`. I'll try adding more print statements. If it does not confuse the JIT compiler maybe it will help pinpoint the reason.

**Comment by jpc** [comment]
Ok, `print` is an amazing debugging tool, as always. The problem is not that `_handle_rx` does not call `_decode` but that it calls `_decode` from the wrong metatable.

I have a `_default` class which has a dummy `_decode` method (which just returns it's only argument). I have several subclasses (`spi`, `notify`, `gpio`, `watchdog` and others which are not instantiated in this particular program). All of them use the default `_decode` method apart from `notify` which has it's own implementation.

I added a printout (`print("_default:_decode", self.id, self.name, getmetatable(self), string.format("%q", data))`) to the base class's `_decode` method. It runs for all the objects and prints the correct `id` and `name` of the instance as well as the correct metatable for each object's subclass.

For some reason in "bad" runs `_handle_rx` always calls the `_decode` method from the base class (`_default`) despite the fact that the notify subclass has it's own `_decode` method which should be called instead of the default one.

I also printed the value of `self._decode` in `_handle_rx` and in "bad" runs it always prints the address of the function defined on the base class. In good runs it prints correct addresses and subsequently calls the correct methods.

Would this help in figuring out where the error may be coming from?

**Comment by jpc** [comment]
Hi @MikePall,

I managed to simplify my test case considerably and make it completely independent of the hardware. I failed to reproduce the error on macOS x86_64 but it still reproduces pretty reliably on Linux mipsel. I also hacked away all the dependencies on my C modules and FFI. It is unfortunately still quite a lot of code.

[luajit-mips-testcase.zip](https://github.com/LuaJIT/LuaJIT/files/5081263/luajit-mips-testcase.zip)

I run it like this:
```cd luajit-mips-testcase && while true; do luajit testcase.lua serial:/dev/null; grep "sepack.lua:291" /tmp/luajit-trace; sleep 1; done```
If the code works correctly then the program will exit. When there is an error it hangs at the `io.stdin:read('*l')`.

Correct runs end like this (and exit the process) (notice that the correct notify function was called):
```
_handle_rx channel:	1	spi0	mt:	table: 0x77d49658	_decode:	function: 0x77d20840	mt._decode:	function: 0x77d20840
_default:_decode channel:	1	spi0	mt:	table: 0x77d49658
_handle_rx channel:	2	notify	mt:	table: 0x77d49440	_decode:	function: 0x77d49488	mt._decode:	function: 0x77d49488
notify decode	"n\0\1"
```

Failed runs do not exit and print this (for both packets the _default:_decode method is called):
```
_handle_rx channel:	1	spi0	mt:	table: 0x77cf2478	_decode:	function: 0x77cd89f8	mt._decode:	function: 0x77cd89f8
_default:_decode channel:	1	spi0	mt:	table: 0x77cf2478
_handle_rx channel:	2	notify	mt:	table: 0x77cf22f0	_decode:	function: 0x77cd89f8	mt._decode:	function: 0x77cd89f8
_default:_decode channel:	2	notify	mt:	table: 0x77cf22f0
```

I spent several hours trying to throw away more code (e.g. inject these packets directly into _handle_rx) but these attempts apparently threw the JIT compiler onto a different path and I could not reproduce the error.

A significant clue seems to be that without `randomize_va_space == 2` all the method addresses stay same between runs and the bug does not manifest.

Please let me know what more I could do to help debug this issue further.

**Comment by MikePall** [comment]
Sorry, but I cannot reproduce this under QEMU MIPS (EL). No matter how long I run this.

The one thing I haven't menioned yet, is that the particular traces where you indicated flushing helped contained the same machine code as the equivalent trace from the OK logfile (modulo address changes). So this is probably not the root cause.

Since you're seeing variations due to ASLR, the only relevant things this affects is trace region selection and table iteration order (with collectable non-string objects as keys). The latter is also affected by the recent security improvements for strings as keys. Are you 100% sure none of your code relies on a particular iteration order (which is not guaranteed by pairs)?

**Comment by jpc** [comment]
I prepared a QEMU OpenWRT image with the same rootfs I have on my hardware target. I can reproduce the error quite quickly. OpenWRT uses the musl libc. Maybe that has something to do with it?

[openwrt-malta-le-rootfs-ext4.img.gz](https://github.com/LuaJIT/LuaJIT/files/5096215/openwrt-malta-le-rootfs-ext4.img.gz)
[openwrt-malta-le-vmlinux.elf.gz](https://github.com/LuaJIT/LuaJIT/files/5096270/openwrt-malta-le-vmlinux.elf.gz)

```
gunzip -k openwrt-malta-le-rootfs-ext4.img.gz openwrt-malta-le-vmlinux.elf.gz
qemu-system-mipsel -machine malta -kernel "openwrt-malta-le-vmlinux.elf" -drive file="openwrt-malta-le-rootfs-ext4.img",format=raw -append 'root=/dev/sda' -nographic -m 256 -nic user -nic user,net=192.168.43.0/24,hostfwd=tcp::22325-192.168.43.1:22
```

You should be able to SSH into the machine without a password using `ssh root@localhost -p 22325`

If the traces are ok then maybe there is a problem with the table lookup? In the `print` statements I see method lookup failing to return the correct function:
```
_handle_rx channel:	1	spi0	mt:	table: 0x77d0f418	_decode:	function: 0x77cf5a28	mt._decode:	function: 0x77cf5a28
_default:_decode channel:	1	spi0	mt:	table: 0x77d0f418
_handle_rx channel:	2	notify	mt:	table: 0x77cf59b8	_decode:	function: 0x77cf5a28	mt._decode:	function: 0x77cf5a28
_default:_decode channel:	2	notify	mt:	table: 0x77cf59b8
```

In these two invocations of the `_handle_rx` method the two objects have different metatables but both return the same function address for `_decode`. The second metatable (`0x77cf59b8 ` which has a different `_decode` method) inherits from the first one (`0x77d0f418`) using this code:
```
  local o = {}
  o.__index = o
  if base then setmetatable(o, base) end
  return o
```

**Comment by jpc** [comment]
I tested a Debian mipsel image in QEMU and the problem does not reproduce. If I copy the libc and luajit from the OpenWRT image and run them in a chroot in the Debian QEMU then it fails quite often. So it has to be related either to the LuaJIT compilation flags or to some magic inside the libc.

I think I'll try recompiling `luajit` in the same way using crosstool-ng toolchains for glibc and musl.

**Comment by jpc** [comment]
Ok, I don't know why this took me so long to notice but all my musl builds are softfp and Debian on mipsel (which I guess you are testing with) is hardfp. I tested multiple toolchain configurations (using crosstool) and compiling the newest LuaJIT `v2.1` branch against glibc with softfp also has the same problem so it's not actually the fault of the musl libc.

I've used the following crosstool-ng defconfig file:
http://al.loee.pl/2021/glibc_softfp-root.defconfig
and here is the resulting glibc chroot I tested with (with my testcase included):
http://al.loee.pl/2021/glibc_softfp-root.tar.xz

The test command (the shell loop and the lua code cooperate to rerun the testcase until there is a failure; for me it usually takes 3 to 5 loop iterations to trigger the problem):
```
while true; do chroot . ./luajit testcase.lua serial:/dev/null; sleep 1; done
```

Adding `-joff` helps. `-O0` does not. There seems to be a bug in table lookup that's triggered when the JIT is enabled. Maybe some out-of-bounds write corrupts some unrelated memory? Please let me know if you have any ideas on how I could attack this problem.

I am running this test in qemu-system-mipsel on Debian bullseye (installed recently using the official mipsel images):
```
Linux debian 5.10.0-8-4kc-malta #1 SMP Debian 5.10.46-3 (2021-07-28) mips GNU/Linux
```

P.S. Here is my script that builds the toolchain, LuaJIT and then prepares the chroot:
http://al.loee.pl/2021/build-glibc
```
./build-glibc softfp ""
```

**Comment by MikePall** [comment]
Found it after 10 hours of debugging. A bug in the MIPS code generation for `IR_HREF`. A somewhat related bug affected ARM64, too.

Fixed. Thanks!
