### ISSUE TITLE
VMRSS increases with the number of Requests being issued to the Turbo Lua Server, causing memory leak.

### ISSUE THREAD

**Issue by GINUGEORGE** [LuaJIT/LuaJIT#613]
@MikePall @corsix @dknecht @ido @mraleph 

**Could anyone please explain whether the behaviour mentioned below is expected:**

**I am having a simple application , the source code of which is as mentioned below -**

```
local turbo = require("turbo")
local HelloNameHandler = class("HelloNameHandler", turbo.web.RequestHandler)

function HelloNameHandler:get()
     -- Get the 'name' argument, or use 'Santa Claus' if it does not exist
     local name = self:get_argument("name", "Santa Claus")
     self:write("Hello " .. name .. "!")
     self:finish()
end

function HelloNameHandler:post()
    -- Get the 'name' argument, or use 'Easter Bunny' if it does not exist
    local name = self:get_argument("name", "Easter Bunny")
    self:write("Hello " .. name .. "!")
end

local app = turbo.web.Application:new({
    {"/hello", HelloNameHandler}
})
function HelloNameHandler:on_finish()
    collectgarbage("collect")
end

app:listen(9080)
turbo.ioloop.instance():start()
```
**I am running the application**

```
# luajit server.lua &
[1] 11322
```

**Post starting the application, I am checking the VMRSS as below**

```
# cat /proc/11322/status | grep -i vm*
VmPeak:    26228 kB
VmSize:    26228 kB
VmLck:         0 kB
VmPin:         0 kB
VmHWM:      4140 kB
VmRSS:      4140 kB
VmData:     1180 kB
VmStk:       132 kB
VmExe:       440 kB
VmLib:      5784 kB
VmPTE:       100 kB
VmPMD:        16 kB
VmSwap:        0 kB
Speculation_Store_Bypass:       thread vulnerable
voluntary_ctxt_switches:        48
nonvoluntary_ctxt_switches:     1
```

**Now I am trying to trigger 2000 requests to the server with concurrency level as 1.**

`# ab -k -n 2000 -c 1 http://<<Machine-IP>>:9080/hello`

**After the requests are finished triggering, I am checking the VMRSS again as below**

```
# cat /proc/11322/status | grep -i vm*
VmPeak:    26292 kB
VmSize:    26292 kB
VmLck:         0 kB
VmPin:         0 kB
VmHWM:      4612 kB
VmRSS:      4612 kB
VmData:     1244 kB
VmStk:       132 kB
VmExe:       440 kB
VmLib:      5784 kB
VmPTE:       100 kB
VmPMD:        16 kB
VmSwap:        0 kB
Speculation_Store_Bypass:       thread vulnerable
voluntary_ctxt_switches:        1984
nonvoluntary_ctxt_switches:     8
```

### Where does the memory leak by the way ? Why does VMRSS keep on increasing ?

**Comment by GINUGEORGE** [comment]
@MikePall @corsix @dknecht @ido @mraleph

I ran a different experiment this time for observing the increase in VmRSS between issuing requests with concurrency as 1 and greater than 1. 

**_So below mentioned are the observations:_**

### Experiment 1 : Issuing Parallel Requests

**Initial Stage of Process Start:**

```
~ # ps -ef|grep server.lua
sysadmin  7055     1  0 00:58 ttyS4    00:00:00 luajit server.lua
sysadmin  7078  4160  0 00:58 ttyS4    00:00:00 grep server.lua
```

```
~ # cat /proc/7055/status | grep -i vm*
VmPeak:    14632 kB
VmSize:    14632 kB
VmLck:         0 kB
VmPin:         0 kB
VmHWM:      9000 kB
VmRSS:      9000 kB
VmData:     8688 kB
VmStk:       132 kB
VmExe:       364 kB
VmLib:      4288 kB
VmPTE:        22 kB
VmSwap:        0 kB
voluntary_ctxt_switches:        11
nonvoluntary_ctxt_switches:     8
```

**Now I am trying to trigger 2000 requests to the server with concurrency level as 50.**

`# ab -k -n 2000 -c 50 https://<<Machine-IP>>:<<Port>>/<<API URI>>`

**I am checking the VMRSS again as below**

```
~ # cat /proc/7055/status | grep -i vm*
VmPeak:    16932 kB
VmSize:    16852 kB
VmLck:         0 kB
VmPin:         0 kB
VmHWM:     11636 kB
VmRSS:     11528 kB
VmData:    10908 kB
VmStk:       132 kB
VmExe:       364 kB
VmLib:      4288 kB
VmPTE:        22 kB
VmSwap:        0 kB
voluntary_ctxt_switches:        2410
nonvoluntary_ctxt_switches:     86119
```

###  Result : VmRSS has increased by around 2528 KB

### Experiment 2 : Issuing One-By-One Requests for the same URI

**Initial Stage of Process Start:**

```
~ # ps -ef|grep server.lua
sysadmin  8660     1  0 01:15 ttyS4    00:00:00 luajit server.lua
sysadmin  8686  4160  0 01:15 ttyS4    00:00:00 grep server.lua
```

```
~ # cat /proc/8660/status | grep -i vm*
VmPeak:    14632 kB
VmSize:    14632 kB
VmLck:         0 kB
VmPin:         0 kB
VmHWM:      9000 kB
VmRSS:      9000 kB
VmData:     8688 kB
VmStk:       132 kB
VmExe:       364 kB
VmLib:      4288 kB
VmPTE:        20 kB
VmSwap:        0 kB
voluntary_ctxt_switches:        5
nonvoluntary_ctxt_switches:     8
```

**Now I am trying to trigger 2000 requests to the server with concurrency level as 1.**

`# ab -k -n 2000 -c 1 https://<<Machine-IP>>:<<Port>>/<<API URI>>`

**I am checking the VMRSS again as below**

```
~ # cat /proc/8660/status | grep -i vm*
VmPeak:    14636 kB
VmSize:    14520 kB
VmLck:         0 kB
VmPin:         0 kB
VmHWM:      9176 kB
VmRSS:      9124 kB
VmData:     8576 kB
VmStk:       132 kB
VmExe:       364 kB
VmLib:      4288 kB
VmPTE:        20 kB
VmSwap:        0 kB
voluntary_ctxt_switches:        5709
nonvoluntary_ctxt_switches:     85796
```

###  Result : VmRSS has increased by around 124 KB only

### Does anyone have an idea as to why the VmRSS increases by around 2528 KB when issuing Parallel Requests and increases only by around 124 KB when issuing Requests one at a time ? 

### Does it have anything to do with the Lua Garbage Collector ? Is it not able to do proper garbage collection when parallel requests are issued.

### Any suggestions/ideas on how to fix this would be welcome.

**Comment by ExtReMLapin** [comment]
Are we sure it's related to LuaJIT and not turbo?

**Comment by GINUGEORGE** [comment]
> Are we sure it's caused by LuaJIT and not turbo?

@ExtReMLapin We are not sure as to whether Luajit or Turbo is causing this behaviour and we have already raised similar issue as mentioned below :

https://github.com/kernelsauce/turbo/issues/350

**Comment by MikePall** [comment]
You have already been told on the LuaJIT mailing list in no unclear words, that **THIS IS NOT THE CORRECT PLACE TO ASK!**

Stop spamming unrelated forums, mailing lists and trackers. Stop spamming mentions of random people. You have been blocked.
