### ISSUE TITLE
error {CROSS} path on NDK 

### ISSUE THREAD

**Issue by meilaopo** [LuaJIT/LuaJIT#616]
in src/MakeFile defined: 
TARGET_LD= $(CROSS)$(CC)
TARGET_AR= $(CROSS)ar rcus 2>/dev/null

I use clang compiler android lib, cc=clang.

in ndk dir {MyDir}/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/bin
CC is aarch64-linux-android21-clang
AR is aarch64-linux-android-ar

**Comment by MikePall** [comment]
Read the Android install instructions: https://luajit.org/install.html#android
