### ISSUE TITLE
dynasm: failing to encode mov [=>label], Rq(n)

### ISSUE THREAD

**Issue by sgraham** [LuaJIT/LuaJIT#617]
I'm trying to encode references to global-type variables that are defined earlier via `.space`.

Given:
```
  int label_name = 10;
  | =>label_name:
  | .space 8
```
and then later
```
  | mov rax, 1
  | mov [=>label_name], rax
```
everything seems fine. But if I use:
```
  | mov rax, 1
  | mov [=>label_name], Rq(0)
```
the mov to label is garbled (obviously not using a literal 0 in practice.)

Attached a repro [mov_label.zip](https://github.com/LuaJIT/LuaJIT/files/5211129/mov_label.zip) with Win32 compile instructions. (Requires cl.exe and ndisasm.exe to see dump. Sorry for the .zip, github won't allow .c attachments.)

**Comment by sgraham** [comment]
A silly hack like this:

```
  if (reg == 0) {
    | mov [=>label_name], rax
  } else if (reg == 1) {
    | mov [=>label_name], rcx
  } else if (reg == 2) {
    | mov [=>label_name], rdx
  }
  ...
```

works ok. I couldn't figure out how to fix dasm_x86.lua after a bit of poking unfortunately. :(

**Comment by MikePall** [comment]
Fixed. Thanks!
