### ISSUE TITLE
Add support for freeing memory manually

### ISSUE THREAD

**Issue by FlamingArr** [LuaJIT/LuaJIT#620]
I am here to propose a function : `table.free(ref)` which will instantly free the table referenced by `ref` without making it wait for the GC, This can be very useful and can help a lot in not producing a lot of garbage.

**Comment by GitSparTV** [comment]
```lua
ref = nil
collectgarbage()
```

**Comment by DarkWiiPlayer** [comment]
that function sounds extremely dangerous and absolutely shouldn't be in the `table` namespace.

At the very least it should be replaced with a new "empty" table, which would basically turn it into a table-clear function.

**Comment by FlamingArr** [comment]
@GitSparTV That makes the garbage collector do an entire collection, defeating the purpose of this function
@DarkWiiPlayer How is this going to be dangerous exactly? Every reference to the table would just be niled out
And even if it is dangerous how will not putting it inside the table namespace make a difference?

**Comment by GitSparTV** [comment]
But if you passed the table in this function that means you still have the reference.

**Comment by GitSparTV** [comment]
Lua won't trust you the reference counting

**Comment by DarkWiiPlayer** [comment]
> Every reference to the table would just be niled out
And even if it is dangerous how will not putting it inside the table namespace make a difference?

And how exactly would it do that? That is, how would it do so *effectively*?

**Comment by MikePall** [comment]
First, there's a general misunderstanding in this discussion how values vs. variables work. Dynamic languages pass values around, variables just give names to them. And all non-primitive values are really references, which means e.g. that tables are shared and not copied. When the last reference is gone, the GC may eventually free the memory occupied by the table.

Thus the advice to set the variable to nil is correct.

LuaJIT v2.1 also has the `table.clear` function, which clears all keys and values from a table, but preserves the allocated array/hash sizes. You need to `require("table.clear")` to make it available. This may or may not do what you want, read the v2.1 docs.

**Comment by DarkWiiPlayer** [comment]
Is there even such a thing as a memory representation of a `nil` value though? iirc at least in PUC Lua there's not really such a thing. Unless that's a thing, wouldn't the VM still have to find all the variables with a reference to a table?

A side thought:

Assuming that LuaJIT works similar to PUC Lua and saves Lua values as a struct with the type and a pointer to the actual data, wouldn't it technically be very easy to just free the data and replace the pointer with some freshly initialized memory? That way you could "clear" a table without looping through it, no?

**Comment by MikePall** [comment]
@DarkWiiPlayer You are discussing a hypothetical (and infeasible) way to implement something which has neither be requested nor suggested. The issue creator just wants to free some memory immediately without waiting for the GC. This is not about variables or the references they hold. This is about the memory the table object takes up. Without knowing more about the intentions of the issue creator, I don't think it's helpful to discuss irrelevant tangents.

**Comment by DarkWiiPlayer** [comment]
That's probably right. My line of thinking was that deleting the tables contents while keeping the value valid would probably solve the problem, but that's still not something that fits Lua as a language either way.
