### ISSUE TITLE
"in ipairs" loop constuction raises an exception

### ISSUE THREAD

**Issue by DLdota** [LuaJIT/LuaJIT#621]
I transfer my project from **x32** to **LuaJit x64bit** last veriosn and ran into a problem.

When i use **IN PAIRS** construction in **IN PAIRS** construction with array data i got with ~50 % chance exeption in KernaleBase.dll.
Naive construction is fine

![vs](https://user-images.githubusercontent.com/10529536/93898910-0daeca00-fcf4-11ea-82e0-a7b0421b5b36.png)

### broken code

![inapire2](https://user-images.githubusercontent.com/10529536/93897586-8ad93f80-fcf2-11ea-972b-6853a3eb402f.png)

### naive no problems

![inpaire1](https://user-images.githubusercontent.com/10529536/93899015-29b26b80-fcf4-11ea-80d1-bdcb946855d6.png)

**I really like this syntax. Pls help somebody**

**Comment by GitSparTV** [comment]
Your code suspiciosly looks like a cheat. This doesn't look like a LuaJIT problem since the error is from luabridge or even the game itself.

**Comment by MikePall** [comment]
First, the code is not equivalent. `ipairs` stops at the first nil -- it doesn't need the table length. This may make a difference with sparse arrays.

But, anyway, this doesn't seem to be related to LuaJIT directly. It would be highly surprising if `ipairs` were broken in general.

You need to send an isolated, pure Lua testcase without any external dependencies to file an issue here.

**Comment by DLdota** [comment]
Yes LuaJit is fine. I tested. Such problem only in callback. Something is wrong with my c++ code and luabridge.
![image](https://user-images.githubusercontent.com/10529536/93935447-ec1a0680-fd24-11ea-9900-2961cce3f4ac.png)
This exeption is confused me. sry. Good luck!
