### ISSUE TITLE
ARM64 patchexit cache sync

### ISSUE THREAD

**Issue by CarlZhongZ** [LuaJIT/LuaJIT#623]
traceback: __aarch64_sync_cache_range (/usr/local/google/buildbot/src/android/gcc/toolchain/build/../gcc/gcc-4.9/libgcc/config/aarch64/sync-cache.c:54)[arm64-v8a] 
lj_asm_patchexit [arm64-v8a] 

on current latest 2.1 branch version

**Comment by MikePall** [comment]
Fixed.
