### ISSUE TITLE
about sparse array 

### ISSUE THREAD

**Issue by stone-wind** [LuaJIT/LuaJIT#627]
luajit is newest luajit v2.1(1d8b747)

array.lua:
```
collectgarbage("stop")
local pos = {0, 2^22, 2^42, 2^46, 2^50}

local q, s, e, we
local head, tail
for i, p in ipairs(pos) do
    s = os.clock()
    q = {}
    for i = p + 1, p + 1000 do
        q[i] = 1
    end
    e = os.clock()

    head, tail = p + 1, p + 1000
    -- walk 1000000
    for i = tail + 1, p + 1000000 do
        q[i], q[head] = q[head], nil
        head = head + 1
    end
    we = os.clock()
    print("pos:", p, "  init 1000 elms:", e-s," walk 1000000:", we - e)
end
```

➜  test lua5.1 array.lua
pos:    0               init 1000 elms: 3.4e-05         walk 1000000:   0.108796
pos:    4194304         init 1000 elms: 0.00014399999999999             walk 1000000:   2.050922
pos:    4398046511104           init 1000 elms: 0.00010900000000014             walk 1000000:   0.091717
pos:    70368744177664          init 1000 elms: 0.00012600000000029             walk 1000000:   0.090888
pos:    1.1258999068426e+15             init 1000 elms: 0.00012100000000004             walk 1000000:   0.090723
➜  test **lua5.3** array.lua
pos:    0               init 1000 elms: 3.4e-05         walk 1000000:   0.05676
pos:    4194304.0               init 1000 elms: 0.000122                walk 1000000:   0.091261
pos:    4398046511104.0         init 1000 elms: 0.000113                walk 1000000:   0.092228
pos:    70368744177664.0                init 1000 elms: 0.00011299999999997             walk 1000000:   0.091801
pos:    1.1258999068426e+15             init 1000 elms: 0.000114                walk 1000000:   0.091028
➜  test **lua5.4** array.lua
pos:    0               init 1000 elms: 2.9e-05         walk 1000000:   0.052886
pos:    4194304.0               init 1000 elms: 9.3000000000003e-05             walk 1000000:   **0.080405**
pos:    4398046511104.0         init 1000 elms: 0.00010400000000002             walk 1000000:   **0.080535**
pos:    70368744177664.0                init 1000 elms: 9.5000000000012e-05             walk 1000000:   **0.080212**
pos:    1.1258999068426e+15             init 1000 elms: 8.9000000000006e-05             walk 1000000:   **0.08119**
➜  test **luajit** array.lua
pos:    0               init 1000 elms: 6.4e-05         walk 1000000:   **1.361391**
pos:    4194304         init 1000 elms: 0.000135                walk 1000000:   **1.684024**
pos:    4398046511104           init 1000 elms: 0.0013030000000001              walk 1000000:   **32.325059**
pos:    70368744177664          init 1000 elms: 0.00019900000000206             walk 1000000:   **5.713668**
pos:    1.1258999068426e+15             init 1000 elms: 6.4999999999316e-05             walk 1000000:   **1.560658**

**In this scenario, Lua performs better than luajit, and luajit is not stable when number > 2^32 . could this be optimized?**

![20201016115934](https://user-images.githubusercontent.com/10290180/96211527-20d95080-0fa7-11eb-8aac-0a584667cf0e.png)
![20201016110931](https://user-images.githubusercontent.com/10290180/96211534-26369b00-0fa7-11eb-83a3-bd2a529c2180.png)

**Comment by MikePall** [comment]
Contrary to the title, this has nothing to do with sparse arrays. The code effectively only uses the hash part of Lua tables. The array optimization for Lua tables doesn't apply here. Permanently changing the set of active hash table keys either causes rapid memory growth or excessive rehashing.

This is not what Lua tables are optimized for. It's trivial to find other cases where either the Lua or the LuaJIT implementation of hash tables will trigger worst-case behavior, when abused.

Anyway, this is not how to implement a circular queue. You'll find plenty of examples how to properly map a queue to an array in introductory programming courses.
