### ISSUE TITLE
Weak valued table entry disappear before `__gc` is called

### ISSUE THREAD

**Issue by yshui** [LuaJIT/LuaJIT#632]
Is `__gc` guaranteed to be called before values are removed from a weak table? Because I observed behavior where `table[idx]` is `nil`, but the corresponding `__gc` hasn't been called. The same doesn't seem to happen with regular Lua.

Is this an expected behavior of LuaJIT?

**Comment by GitSparTV** [comment]
Maybe it was moved to gray zone, just a thought

**Comment by yshui** [comment]
@GitSparTV I'm not that familiar with LuaJIT GC, can you explain what that means? Thanks.

**Comment by yshui** [comment]
So IIUC, the weak table entries are clear here, in the atomic GC step
https://github.com/LuaJIT/LuaJIT/blob/050466552bf7eb8b7944aa52c93b45326ae14d7a/src/lj_gc.c#L600

But the finalizer is called later, in the finalize GC step

I think this answers my question.

**Comment by GitSparTV** [comment]
Checked Lua 5.4.1 and 5.1.4, at the time __gc is called, the value doesn't exist in weak table anymore.
So yeah, this behavior is different LuaJIT.

**Comment by MikePall** [comment]
The interaction between weak tables and (userdata) finalizers is not guaranteed. But e.g. the following test has the same result for the current GC implementations in LuaJIT and Lua 5.1 - 5.4.

```Lua
-- We abuse the FILE userdata __gc for this test, since newproxy is gone since Lua 5.2.
local ogc = getmetatable(io.stdin).__gc

do
  local t = setmetatable({}, { __mode = "v" })
  local u = io.open("/dev/null") or io.open("NUL")
  getmetatable(u).__gc = function(u)
    print("inside __gc: weak value", t[true] and "exists" or "gone")
  end
  t[true] = u
  u = nil
  collectgarbage()
end

do
  local t = setmetatable({}, { __mode = "k" })
  local u = io.open("/dev/null") or io.open("NUL")
  getmetatable(u).__gc = function(u)
    print("inside __gc: weak key  ", t[u] and "exists" or "gone")
  end
  t[u] = true
  u = nil
  collectgarbage()
end

getmetatable(io.stdin).__gc = ogc 
```

Result:
```
inside __gc: weak value	gone
inside __gc: weak key  	exists
```
