### ISSUE TITLE
Support for Apple Silicon Mac

### ISSUE THREAD

**Issue by mikelxc** [LuaJIT/LuaJIT#634]
Thank you for creating this package. As Apple Silicon Macs have released, I've built the 2.1.0 beta 3 on my local machine, and it works as expected. 

To save building time, attached please find the binary file.
[luajit-2.1.0-beta3.zip](https://github.com/LuaJIT/LuaJIT/files/5551833/luajit-2.1.0-beta3.zip)

**Comment by MikePall** [comment]
LuaJIT ARM64 Mac support has already been added to v2.1 on June 23 2020.

Please **do not post binaries** here. Nobody should run untrusted binaries they found on an issue tracker, anyway.

**Comment by clason** [comment]
@MikePall Now that ARM64 Macs are widely available, would it be possible to make a `beta-4` release? That would be quite helpful for neovim to add official support for building on ARM64 Macs.
