### ISSUE TITLE
Crash when try to resume a dead coroutine from c side

### ISSUE THREAD

**Issue by sunzhuo** [LuaJIT/LuaJIT#635]
the host application will crash if it tries to resume a dead coroutine from c side.

**Comment by MikePall** [comment]
A 'dead' coroutine is just that: dead. You cannot resume it from the Lua side and resuming it from the C side is a Lua/C API violation.
The Lua/C API is generally unforgiving and doesn't check for misuse. It may crash or do undefined things. Though you may get an assertion, if you care to enable them.
