### ISSUE TITLE
luaL_newstate with LuaJIT crashes, while normal Lua works on Windows x86_64

### ISSUE THREAD

**Issue by MarioSieg** [LuaJIT/LuaJIT#638]
Hello,
when I just call luaL_newstate() it crashes the program with an access violation.
I'm using Windows x86_64.
![image](https://user-images.githubusercontent.com/49988901/100204774-94567200-2f04-11eb-85a3-72467c4f1513.png)
Here is a screenshot. It happens at the call
 if (lj_vm_cpcall(L, NULL, NULL, cpluaopen) != 0) {
    /* Memory allocation error: free partial state. */
    close_state(L);
    return NULL;
  }
to "j_vm_cpcall". Since this is an assembly function I don't have any idea how to fix this.
Any help would be appreciated :) 
My Laptop stats:
CPU: Intel Core i7 9750H 6 Cores
RAM: 32 GB 26667 Mhz
OS: Windows 10 Pro 64-Bit
GPU: RTX 2060
Lua: Lua JIT 2.1 from this repo

**Comment by MikePall** [comment]
Well, LuaJIT certainly works on Windows. This looks like the build went wrong.

Build it with the provided instructions, using `msvcbuild.bat`. Do not, under any circumstances, try to emulate the build system yourself or use any external CMake or other nonsense instructions you may find on the Internet.

**Comment by MarioSieg** [comment]
Hey,
okay thanks I'll try that. You are right I was using some CMake version.
But I think official CMAKE support would be amazing - it makes many things easier.

**Comment by sonoro1234** [comment]
CMake has been refused previously so I did wrap LuaJIT build system for being called from cmake: https://github.com/sonoro1234/anima/tree/master/LuaJIT
