### ISSUE TITLE
table.insert doesn't check for NaN

### ISSUE THREAD

**Issue by GitSparTV** [LuaJIT/LuaJIT#639]
Following code freezes LuaJIT for few minutes.
```lua
table.insert({}, 0/0, 0)
```
Lua 5.3 and higher don't have this problem because of `number has no integer representation` error happening on casting into the integer.
Does it have sense to fix on LuaJIT?

LuaJIT HEAD (5de5ec2).

**Comment by MikePall** [comment]
Given the compatibility requirement with Lua 5.1 one cannot simply reject all non-integers or all negative numbers. Some people rely on this working, though they really shouldn't. In this sense, most Lua library functions have a 'you get what you feed it'  attitude. E.g. `table.insert({}, -1e9, 0)` freezes in plain Lua 5.1, too.
