### ISSUE TITLE
x86_64arch on android build error

### ISSUE THREAD

**Issue by mdyshad0w** [LuaJIT/LuaJIT#641]
android x86_64 error: ./lj_def.h:370:47: error: size of array ‘STATIC_ASSERTION_FAILED’ is negative. But there is no issue on arm64,why?and how to do...

**Comment by MikePall** [comment]
You're hitting a static assertion, but you only showed the definition, but not the place where it happens.

Are you using the v2.1 install instructions from the repo? I just tried an x86_64 build with the latest android NDK and it works fine.

**Comment by mdyshad0w** [comment]
i have sole this problem.if i use function in build bash, this error will happen, otherwise will be ok. i don't know why, but thanks!
