### ISSUE TITLE
assembler local symbol not defined

### ISSUE THREAD

**Issue by mdyshad0w** [LuaJIT/LuaJIT#642]
macOS:10.14.6
xcode:9.41
build_ios.sh:
#!/bin/sh

export MACOSX_DEPLOYMENT_TARGET=10.14
LIPO="xcrun -sdk iphoneos lipo"

cd src
DESTDIR=../ios
mkdir -p $DESTDIR 2>/dev/null
rm "$DESTDIR"/*.a 2>/dev/null

CFLAGS="-DLUAJIT_ENABLE_LUA52COMPAT -DLUAJIT_DISABLE_JIT"

ISDKP=$(xcrun --sdk iphoneos --show-sdk-path)
ICC=$(xcrun --sdk iphoneos --find clang)

ISDKF="-arch armv7 -isysroot $ISDKP -mios-version-min=8.0"
make clean
make -j8 CCOPT="" BUILDTYPE=static BUILDMODE=static CC="clang" HOST_CC="clang -m32 -arch i386" CROSS="$(dirname $ICC)/" TARGET_FLAGS="$ISDKF" TARGET_CFLAGS="$CFLAGS" TARGET_SYS=iOS
cp ./libluajit.a $DESTDIR/libluajit_arm7.a

ISDKF="-arch arm64 -isysroot $ISDKP -mios-version-min=8.0"
make clean
make -j8 BUILDTYPE=static BUILDMODE=static CC="clang" CROSS="$(dirname $ICC)/" TARGET_FLAGS="$ISDKF" TARGET_CFLAGS="$CFLAGS" TARGET_SYS=iOS
cp ./libluajit.a $DESTDIR/libluajit_arm64.a

ISDKP=$(xcrun --sdk iphonesimulator --show-sdk-path)
ICC=$(xcrun --sdk iphonesimulator --find clang)

ISDKF="-arch i386 -isysroot $ISDKP -mios-simulator-version-min=8.0"
make clean
make -j8 BUILDTYPE=static BUILDMODE=static CC="clang" HOST_CC="clang -m32 -arch i386" CROSS="$(dirname $ICC)/" TARGET_FLAGS="$ISDKF" TARGET_CFLAGS="$CFLAGS" TARGET_SYS=iOS
cp ./libluajit.a $DESTDIR/libluajit_x86.a

ISDKF="-arch x86_64 -isysroot $ISDKP -mios-simulator-version-min=8.0"
make clean
make -j8 BUILDTYPE=static BUILDMODE=static CC="clang" CROSS="$(dirname $ICC)/" TARGET_FLAGS="$ISDKF" TARGET_CFLAGS="$CFLAGS" TARGET_SYS=iOS
cp ./libluajit.a $DESTDIR/libluajit_x86_64.a

LUAJIT_LIB=libluajit.a
$LIPO -create "$DESTDIR"/libluajit_*.a -output "$DESTDIR"/$LUAJIT_LIB
$LIPO -info "$DESTDIR"/$LUAJIT_LIB

rm "$DESTDIR"/libluajit_*.a

armv7,arm64,x86_64 are success, but i386 arch has errors:
lj_vm.S:1969:1: error: assembler local symbol 'L_tan$stub' not defined
^
lj_vm.S:1969:1: error: assembler local symbol 'L_atan2$stub' not defined
^
lj_vm.S:1969:1: error: assembler local symbol 'L_cosh$stub' not defined
^
lj_vm.S:1969:1: error: assembler local symbol 'L_pow$stub' not defined
^
lj_vm.S:1969:1: error: assembler local symbol 'L_atan$stub' not defined
^
lj_vm.S:1969:1: error: assembler local symbol 'L_cos$stub' not defined
^
lj_vm.S:1969:1: error: assembler local symbol 'L_log$stub' not defined
^
lj_vm.S:1969:1: error: assembler local symbol 'L_sin$stub' not defined
^
lj_vm.S:1969:1: error: assembler local symbol 'L_tanh$stub' not defined
^
CC        lj_record.o
lj_vm.S:1969:1: error: assembler local symbol 'L_sinh$stub' not defined
^
lj_vm.S:1969:1: error: assembler local symbol 'L_exp$stub' not defined
^
lj_vm.S:1969:1: error: assembler local symbol 'L_log10$stub' not defined
^
lj_vm.S:1969:1: error: assembler local symbol 'L_acos$stub' not defined
^
lj_vm.S:1969:1: error: assembler local symbol 'L_fmod$stub' not defined
^
lj_vm.S:1969:1: error: assembler local symbol 'L_asin$stub' not defined

How to solve this problem？

**Comment by MikePall** [comment]
32 bit x86 is not a supported target for MacOS, because they don't provide any toolchain support for it since a few releases.
