### ISSUE TITLE
help : debug api issue

### ISSUE THREAD

**Issue by mdyshad0w** [LuaJIT/LuaJIT#644]
lua_sethook : mask is LUA_MASKCALL | LUA_MASKRET. the LUA_MASKRET is correct, but the LUA_MASKCALL seems has issue. get the wrong call stack info. is this a bug?i only use two functions, one is lua_sethook, another is lua_getinfo, it's ok when use Lua, but there have this problem when use LuaJIT. please help how to use it...

**Comment by MikePall** [comment]
This is as shallow as a bug report gets, without a freestanding example, not even with a precise description what you think is wrong. This is an issue tracker and **not** a Lua help forum.

Anway, you seem to be new to Lua, yet messing with the debug API. You should probably use an existing debugger. If you're using the debug API for anything else, you're unlikely to get any speed benefits of LuaJIT. Anyway, you should probably start embedding plain Lua first and only switch to LuaJIT if you see any performance problems.
