### ISSUE TITLE
Compatibility with MacOS/ARM64 Rosetta 2 x64 emulation

### ISSUE THREAD

**Issue by LostVector** [LuaJIT/LuaJIT#648]
Hi,

We're trying to run some x86_64 executables which use luajit under Rosetta 2 on the new Apple Silicon Mac's.  They all fail with an illegal hardware instruction error before even starting.  I tore out luajit on a hunch and the exe's at least managed to start up.

Obviously I don't expect this to work immediately, but it would be nice to have:

A. An official statement on compatibility
B. some idea of whether or not there is a simple workaround or fix that can be made.

For various reasons, a full aarch64 port is quite a bit further off for us, so Rosetta 2 compatibility is specifically what we're investigating.

Thanks.

**Comment by MikePall** [comment]
Rosetta is not open source and made by Apple. So, if you want an official statement, then better ask them. Might be they don't even plan to support emulation of x64 JIT compilers. I have no idea -- I can't even test this nor debug this.

You could try to turn off the jit compiler (`-j off` option or jit.off() early in Lua code). But, yes, this will incur another slowdown.

**Comment by LostVector** [comment]
Thanks, we will experiment with those flags.  The “official” bit was more in reference to understand how compatibility is perceived from the luajit side.  It sounds like “untested and unknown” at this time without any known workarounds.

Once we isolate the issue a bit more, I will file an issue with Apple as well to see if they have any plans or capability to address things.

**Comment by fxcoudert** [comment]
Rosetta 2 does not support AVX instructions, so if your x86_64 binary is compiled with those enabled unconditionally (for example because they're supported on the compiling machine) then this could be a cause.

**Comment by MikePall** [comment]
This can't be it. LuaJIT auto-detects instruction set availability on x86/x64 based on CPUID. If Rosetta 2 doesn't announce certain capabilities, then LuaJIT won't use them.

I'm more inclined to believe it's something about the JIT compiler and Rosetta's instruction cache management.

Or maybe an old LuaJIT x64 version that was built without GC64 mode enabled, which required the `-image_base` linker flags. In that case, please use a current version and drop those flags.

**Comment by LostVector** [comment]
OK ... I've managed to get it running.  At some point, tearing out one of the associated libraries we had lua wrapper code in did the trick ... it's not immediately obvious what part of that code was at fault and will take some time to sort out, but bringing back luajit in for the rest of the code worked.  So I think this is actually a sign the compatibility is working.

I will be updating to the latest luajit and removing the image_base and pagezero flags (fantastic to hear that is no longer necessary!).  We have been running off a luajit commit around the march/april timeframe, so it sounds like the GC64 mode is in that build already.

As a side note, Luajit x86_64 binary at the command line does run a simple script under Rosetta2, so that was another sign that things at the luajit level are working.

**Comment by fxcoudert** [comment]
Asking for Homebrew: is there a timeframe for a 2.1.0 release? If 2.0 is hopeless for Apple Silicon support, and there is no 2.1.0 release in sight, we're probably going to deprecate luajit and formulas that depend on it. We each macOS release we need to patch it more and more, and it's not sustainable.

**Comment by MikePall** [comment]
@fxcoudert Use v2.1 git HEAD, like everyone else does.

**Comment by fxcoudert** [comment]
> Use v2.1 git HEAD, like everyone else does

That doesn't actually answer my question. And we won't, because we have no way to know if a specific commit is stable enough for production or broken.

**Comment by SMillerDev** [comment]
https://repology.org/project/luajit/versions seems to indicate that only about half of all projects that ship a luajit package do that.

**Comment by bfredl** [comment]
@MikePall even a v2.1-beta4 would be very useful for us in the neovim project. We want to support ARM64 macs in our upcoming 0.5 release, and a tagged version (even if it is "beta") would seem much more confident that asking our downstream to use an arbitrary commit on HEAD.

**Comment by DemiMarie** [comment]
> > Use v2.1 git HEAD, like everyone else does
> 
> That doesn't actually answer my question. And we won't, because we have no way to know if a specific commit is stable enough for production or broken.

My suggestion would be to see what versions major Linux distros are shipping.

**Comment by SMillerDev** [comment]
> My suggestion would be to see what versions major Linux distros are shipping.

The beta tag, a 2.0 tag or they made their own version by just picking a random date when they used master.

There is a lot fragmentation here and confusion among distros. But we're solving the problem in homebrew by moving to a fork that does have stable tags, maybe that will be a way forward to other distros too.
