### ISSUE TITLE
GitHub repository housekeeping

### ISSUE THREAD

**Issue by ido** [LuaJIT/LuaJIT#65]
See also pull request #64 and #66  for some other minor changes.  I've added some minimal continuous integration support for pull requests and pushes.

* [ ] Consider renaming the GitHub repository from "Mirror of..." to "Official LuaJIT Git repository", if you so desire.
* [ ] Consider adding another CI such as CircleCI or a custom Jenkins/Buildbot server that has workers/buildslaves for various architectures (X86, X64, ARM, MIPS, PPC, PPC64, etc.).

**Comment by ido** [comment]
@MikePall: I noticed you currently seem to be merging/possibly using the green "Merge Pull Request" button in GitHub and thus creating a somewhat overcomplicated/nonlinear Git history (in my opinion).  

Do you care about preserving a linear Git history for this repository?  If so, as a policy, you may want to turn off the green button and instead do something like the below, assuming `github` is the name of the Git remote you use for the GitHub LuaJIT repo (for users who cloned the GitHub repo directly it would be `origin` instead):
```
git pull --rebase github pull/<PR_ID#>/head:<LOCAL_BRANCH_NAME>
<do code review and tests here>
git push github
```
...replace `PR_ID#` with the number of the pull request (e.g. my PR_ID# was 64 and 66 for the Travis-CI changes),
...replace `LOCAL_BRANCH_NAME` with the local branch you're rebasing the pull request onto (e.g. `prtest`),
...feel free to use `git rebase -i` before pushing to squash commits and edit commit messages as needed, if you so desire.

Reference: https://help.github.com/articles/checking-out-pull-requests-locally/ scroll down to the section on "Modifying an inactive pull request locally".

Hope this helps!

**Comment by MikePall** [comment]
Thanks!

My repo is still the master. The GitHub repo will become the master only after the 2.1-final release.

I'm not merging pull requests, at this time. I'm rewriting and applying them by hand in my master and then pushing to the mirror here. I'm not going to change this workflow until this repo becomes the master.

**Comment by ido** [comment]
Okay, no problem.  Thanks again for the amazing work you're doing on LuaJIT. :+1:
