### ISSUE TITLE
Mac OS X build failure: missing: export MACOSX_DEPLOYMENT_TARGET=XX.YY

### ISSUE THREAD

**Issue by programmingkidx** [LuaJIT/LuaJIT#653]
When trying to build LuaJIT 2.1 on Mac OS 10.8, I see this error message:

==== Building LuaJIT 2.1.0-beta3 ====
make -C src
Makefile:319: *** missing: export MACOSX_DEPLOYMENT_TARGET=XX.YY.  Stop.
make: *** [default] Error 2

My Info:
OS: Mac OS 10.8.5
LuaJIT: 2.1.0 beta 3

**Comment by programmingkidx** [comment]
A fix for this issue is to comment out the "MACOSX_DEPLOYMENT_TARGET" condition in the src/makefile file:

ifeq (Darwin,$(TARGET_SYS))
#  ifeq (,$(MACOSX_DEPLOYMENT_TARGET))
#    $(error missing: export MACOSX_DEPLOYMENT_TARGET=XX.YY)
#  endif

I was able to build LuaJIT successfully with the above change.

**Comment by MikePall** [comment]
This check is deliberate, because you **must** set this variable to the correct value (or most OSX toolchains will break).
The v2.1 docs mention this in the install section.

**Comment by programmingkidx** [comment]
Could a feature be added that automatically sets this value to the current Mac OS version if none is provided?

**Comment by fabiom91** [comment]
So what is the solution?

**Comment by sonoro1234** [comment]
you must set this variable to the correct value

**Comment by fabiom91** [comment]
> you must set this variable to the correct value

Yep sorry, I realised it later: `make MACOSX_DEPLOYMENT_TARGET=10.14`
or I also found this way to be easier: `brew install luajit`

**Comment by razzius** [comment]
Here's a one-liner to build for the current MacOS version:

```bash
env MACOSX_DEPLOYMENT_TARGET=$(sw_vers -productVersion) make
```

This could be added to the Makefile if there is interest.
