### ISSUE TITLE
[Windows] Android Build

### ISSUE THREAD

**Issue by XxXSVVPXxXx** [LuaJIT/LuaJIT#655]
How to compile for android on Windows?
I followed the tutorial below (according to the documentation):
```
NDKDIR=/opt/android/ndk
NDKBIN=$NDKDIR/toolchains/llvm/prebuilt/linux-x86_64/bin
NDKCROSS=$NDKBIN/arm-linux-androideabi-
NDKCC=$NDKBIN/armv7a-linux-androideabi16-clang
make HOST_CC="gcc -m32" CROSS=$NDKCROSS \
     STATIC_CC=$NDKCC DYNAMIC_CC="$NDKCC -fPIC" \
     TARGET_LD=$NDKCC
```
In Windows the folder "linux-x86_64", does not exist.
How to proceed?

**Comment by MikePall** [comment]
These are the instructions to cross-compile from a Linux host to Android.

For a Windows host you need to adapt the paths -- check what's installed in your NDK folders. And you need a host build environment, too, e.g. MinGW or MSYS2. And you need to add `TARGET_SYS=Linux`.
