### ISSUE TITLE
Android Compiling SO file

### ISSUE THREAD

**Issue by XxXSVVPXxXx** [LuaJIT/LuaJIT#657]
I think now I built it the right way (Windows + Github bash + Chocolatey Make).

```
cd LuaJIT
NDKDIR=C:/AndroidSDK/ndk/21.4.7075529
NDKBIN=$NDKDIR/toolchains/llvm/prebuilt/windows-x86_64/bin
NDKCROSS=$NDKBIN/arm-linux-androideabi-
NDKCC=$NDKBIN/armv7a-linux-androideabi21-clang
make CROSS=$NDKCROSS STATIC_CC=$NDKCC DYNAMIC_CC="$NDKCC -fPIC" TARGET_LD=$NDKCC TARGET_SYS="Linux"
```

Everything goes well. However, in the libluajit.so file if we analyze in IDA PRO
![image](https://user-images.githubusercontent.com/73304497/106400641-6c9cf200-63fe-11eb-97bb-4784b5c25bc3.png)

Why does it depend on libc.so, libdl.so, libm.so?

**Comment by XxXSVVPXxXx** [comment]
....and if i use ARM64..

```
HOSTLINK  host/buildvm
BUILDVM   lj_vm.S
Error: pointer size mismatch in cross-build.
Try: make HOST_CC="gcc -m32" CROSS=...
make[1]: *** [Makefile:649: lj_vm.S] Error 1

```

Command Line:
```
cd LuaJIT
NDKDIR=C:/AndroidSDK/ndk/21.4.7075529
NDKBIN=$NDKDIR/toolchains/llvm/prebuilt/windows-x86_64/bin
NDKCROSS=$NDKBIN/aarch64-linux-android-
NDKCC=$NDKBIN/aarch64-linux-android21-clang
make HOST_CC="gcc -m32" CROSS=$NDKCROSS STATIC_CC=$NDKCC DYNAMIC_CC="$NDKCC -fPIC" TARGET_LD=$NDKCC HOST_SYS="Linux" TARGET_SYS="Linux"
```

**Comment by MikePall** [comment]
Those libraries are required basic dependencies. I mean ... that's just the minimum, so what are you complaining about? Check the dependencies of `/system/lib/libstagefright.so` on your Android target and you're in for a shock.

As the error says and the docs explain, the host and target compilers need to be either both 32 bit or both 64 bit. Your `HOST_CC` is definitively wrong for a 64 bit target.
You need a 64 bit native compiler for the 64 bit build and a 32 bit native compiler for the 32 bit build. If you were to use a Linux host, the system compiler is usually a mixed 32/64 bit compiler and defaults to 64 bit. This means one needs that `HOST_CC` line for the 32 bit build.
