### ISSUE TITLE
Difference between ffi.gc() and __gc metamethod behaviour

### ISSUE THREAD

**Issue by Buristan** [LuaJIT/LuaJIT#659]
Hi, Mike!

First of all, I would like to express my gratitude for the hard work you have done.

I have a question about FFI finalizers.
Assuming we have the chunk of code named <gc_ffi.lua>:

```lua
local ffi = require 'ffi'

collectgarbage() -- avoid GC to be triggered spontaneously
local function fake_new()
  local ref = {}
  local cdata = ffi.new('char[1]')
  ffi.gc(cdata, function() print('cdata is collected', tostring(ref)) end)
  ref.anchor = cdata
end

fake_new()
collectgarbage()
print('End of full GC cycle and shut down VM.')
```

I've tried it on master branch (result is the same on v2.1):
```bash
$ ./luajit gc_ffi.lua
End of full GC cycle and shut down VM.
cdata is collected      table: 0x41d079d0
```

I.e. cdata is collected at shutdown of the VM, not when all _visible_ references to it are gone.

I suppose that this happens due to there is the upvalue `ref` inside the FFI finalizer.
Finalizers are kept in k-weak table, each cdata as a key references its finalizer. So, when this table is traversed, GC traverses table-upvalue `ref` and marks cdata by the key `anchor` as alive (finalizers table -> finalizer function -> `ref` table -> `anchor` value i.e. `cdata`) -- so cdata can't be garbage collected.

According to [this section](https://luajit.org/ext_ffi_api.html#ffi_gc) of ffi.\* API documenation.
> A cdata finalizer works like the __gc metamethod for userdata objects: when the last reference to a cdata object is gone, the associated finalizer is called with the cdata object as an argument.

And for the following chunk <gc_ud.lua>:
```lua
collectgarbage() -- avoid GC to be triggered spontaneously
local function fake_new()
  local ref = {}
  local ud = newproxy(true)
  getmetatable(ud).__gc = function() print('ud is collected', tostring(ref)) end
  ref.anchor = ud
end

fake_new()
collectgarbage()
print('End of full GC cycle and shut down VM.')
```

results are the following as expected:
```bash
$ ./luajit gc_ud.lua
ud is collected table: 0x412e59d0
End of full GC cycle and shut down VM.
```

Am I correctly using `ffi.gc()`? Is this an expected behaviour? As far as I can tell I am not breaking any restrictions, but `ffi.gc()` works differently from `__gc`. I suppose that this behaviour should be mentioned in the documentation if it is not a bug.

**Comment by MikePall** [comment]
There's no simple way to break the dependency cycle across the cdata finalizer table. Unlike userdata objects, which have individual metatables, it would be too inefficient to add a metatable or a finalizer field for every cdata object (because very few need any).

That said, finalizers *are* expensive, in any case. Reflect whether you really need them and consider other options.
