### ISSUE TITLE
question: luajit wiki: status

### ISSUE THREAD

**Issue by matu3ba** [LuaJIT/LuaJIT#662]
When I search for luajit performance optimisation, I get a [smaller](https://stackoverflow.com/questions/7167566/luajit-2-optimization-guide) [list](http://lua-users.org/wiki/ProfilingLuaCode) [to](https://stackoverflow.com/questions/154672/what-can-i-do-to-increase-the-performance-of-a-lua-program) [look](http://lua-users.org/wiki/OptimisationTips) at.
~~However, I dont find the luajit wiki.~~

~~1.Could you link the wiki in the README or a separate markdown/docs? It is hidden in the lua wiki under luajit and I searched for quite a while to find it.~~
2. Is the [luajit wiki](http://wiki.luajit.org/Home) fairly complete and up to date regarding that? ~~I dont find a tracking issue or label "wiki". It would also make the wiki look more reputable, when it asks for user authentication.~~

EDIT: clear out unrelevant parts

**Comment by GitSparTV** [comment]
The wiki is mentioned on LuaJIT site
