### ISSUE TITLE
Number rollover error

### ISSUE THREAD

**Issue by lfwelove** [LuaJIT/LuaJIT#663]
**LuaJIT Version:** LuaJIT 2.1.0-beta3 
**OS:** Windows 7 x64

Code:
```
-- local n = 1
-- local n = 0x7fffffffffffffff
local n = 0xffffffffffffffff
print(string.format('%x', n))
n = n + 1
print(string.format('%x', n))
n = n + 1
print(string.format('%x', n))
```

Output:
0
0
0

**What I expect?**
https://rextester.com/XSTZ48638

Output:
ffffffffffffffff
0
1

**Comment by sonoro1234** [comment]
If you add
print(_VERSION) you will get `Lua 5.3` which has 64bit integers

LuaJIT is compatible with Lua 5.1

If you do in LuaJIT

```Lua
local n = 0xffffffffffffffffULL

print(n)
n = n + 1
print(n)
n = n + 1
print(n)
```

you will get:

18446744073709551615ULL
0ULL
1ULL

**Comment by lfwelove** [comment]
@sonoro1234 Thank you, that's all I need.
