### ISSUE TITLE
debug.sethook seems to ignore thread argument

### ISSUE THREAD

**Issue by euclidianAce** [LuaJIT/LuaJIT#666]
The following code's behavior differs in LuaJIT from PUC 5.1 to 5.4

```lua
-- test.lua
local t = coroutine.create(function()
   print("[in thread] this will never be executed")
end)

debug.sethook(t, function()
   print("[in hook] this should not be executed")
end, "l")

print(_VERSION, jit == nil)
```

With a freshly pulled and compiled luajit from the `v2.1` branch:
```
$ luajit test.lua 
[in hook] this should not be executed
Lua 5.1 false
```

With PUC Lua 5.1 - 5.4:
```
$ lua test.lua
Lua 5.1 true
```
```
$ lua test.lua
Lua 5.2 true
```
```
$ lua test.lua
Lua 5.3 true
```
```
$ lua test.lua
Lua 5.4 true
```

The hook just seems to be set on the main lua thread rather than the provided one.

I know the debug library's behavior shouldn't be relied upon, but this seems to be a bug

**Comment by MikePall** [comment]
It's a feature, not a bug. Otherwise a debugger cannot catch newly created coroutines. See: https://luajit.org/status.html
