### ISSUE TITLE
LuaJIT 2.1 still requires "-pagezero_size 10000 -image_base 100000000" on macOS

### ISSUE THREAD

**Issue by nalzok** [LuaJIT/LuaJIT#667]
I cloned the latest LuaJIT repository to `/tmp` to reproduce the issue without affect other packages that depend on my site-wide LuaJIT installation. Specifically, I executed the following commands on a x86 MacBook Pro running macOS 10.14 Mojave.

```
cd /tmp
git clone https://github.com/LuaJIT/LuaJIT.git
cd LuaJIT
MACOSX_DEPLOYMENT_TARGET=10.14 make
```

I came up with the following minimal example

```
$ cat /tmp/example.c
#include <stdio.h>
#include <lua.h>
#include <lualib.h>
#include <lauxlib.h>


int main(int argc, char *argv[]) {
    lua_State *L = luaL_newstate();
    if (!L) {
        fputs("Nope! :(\n", stderr);
        return 1;
    }
    lua_close(L);
    fputs("Yep! :)\n", stderr);
}
```

According to [this page](https://luajit.org/install.html), the `-pagezero_size 10000 -image_base 100000000` flags isn't necessary since LuaJIT 2.1, so I did

```
/tmp $ cc /tmp/example.c -I/tmp/LuaJIT/src -L/tmp/LuaJIT/src -lluajit-5.1
/tmp $ ./a.out
Nope! :(
/tmp [1] $
```

As you can see, `luaL_newstate` returned a null pointer. However, the program works smoothly with the extra flags.

```
/tmp $ cc /tmp/example.c -pagezero_size 10000 -image_base 100000000 -I/tmp/LuaJIT/src -L/tmp/LuaJIT/src -lluajit-5.1
/tmp $ ./a.out
Yep! :)
/tmp $
```

**Comment by MikePall** [comment]
That's weird. There must be some other reason why it doesn't work on your system.
I need to see the last few lines of output of `dtruss ./a.out` for the failing case. Actually only the `mmap` for 128K or the equivalent syscall on macOS.

**Comment by nalzok** [comment]
I'm not familiar with the output format of `dtruss`, so here is the full output

[dtruss_output.txt](https://github.com/LuaJIT/LuaJIT/files/6056612/dtruss_output.txt)

Let me also upload the binary in case you find it useful :)

[a.out.zip](https://github.com/LuaJIT/LuaJIT/files/6056614/a.out.zip)

**Comment by MikePall** [comment]
The trace shows it's trying (and failing) to allocate memory below the first 2GB. Which means GC64 mode is not enabled. But GC64 nide is the default in v2.1. So this is definitely not running the latest version.
The binary shows it's linked against `/opt/local/lib/libluajit-5.1.2.dylib`, which is probably some older version and not the library you just compiled.
