### ISSUE TITLE
VS2017 cannot generate the luajit.exe file

### ISSUE THREAD

**Issue by lugenheng** [LuaJIT/LuaJIT#669]
![image](https://user-images.githubusercontent.com/31931585/109960539-de30ce80-7d23-11eb-9739-ad12058afaf7.png)

**Comment by corsix** [comment]
You're going to have to translate that error message into English for us.

**Comment by MikePall** [comment]
[The translated message says that `cl` is not an executable command.]

You ought to be able to run the `cl` command in the developer command prompt. If not, then your installation of VS2017 is defective. See the [microsoft help page](https://docs.microsoft.com/en-us/cpp/build/walkthrough-compiling-a-native-cpp-program-on-the-command-line?view=msvc-150#open-a-developer-command-prompt
) about this issue.

**Comment by GitSparTV** [comment]
'cl' is not an internal or external command, nor is it an executable program
Or batch file.
