### ISSUE TITLE
CData allocation recording

### ISSUE THREAD

**Issue by sergos** [LuaJIT/LuaJIT#672]
[ffinew.lua.txt](https://github.com/LuaJIT/LuaJIT/files/6161651/ffinew.lua.txt)

Trace recording is aborted due to NYI for the case of a struct with aggregate allocation.
Ironically, it works for the array of the same structs - see the test in attach.

The VLA/VLS machinery was added in f1f7e4031 on the v2.1 branch, closing NYI for array of aggregates around line [1013](https://github.com/LuaJIT/LuaJIT/blob/787736990ac3b7d5ceaba2697c7d0f58f77bb782/src/lj_crecord.c#L1013)
I believe it could be also applied for the case of struct with aggregates at line [1042](https://github.com/LuaJIT/LuaJIT/blob/787736990ac3b7d5ceaba2697c7d0f58f77bb782/src/lj_crecord.c#L1042) since it handles zero init, failing with initializers list anyways.

The test attached shows the following 500x uplift with initial state
```
$ ./luajit ../../test/ffinew.lua 
Median time for struct allocation: 0.021003 sec
Median time for array allocation: 4.6000000000213e-05 sec
```
turned into
```
$ ./luajit ../../test/ffinew.lua 
Median time for struct allocation: 4.8e-05 sec
Median time for array allocation: 4.8000000000001e-05 sec
```
with 
```
--- a/src/lj_crecord.c
+++ b/src/lj_crecord.c
@@ -1039,7 +1039,7 @@ static void crec_alloc(jit_State *J, RecordFFData *rd, CTypeID id)
          dc = ctype_rawchild(cts, df);  /* Field type. */
          if (!(ctype_isnum(dc->info) || ctype_isptr(dc->info) ||
                ctype_isenum(dc->info)))
-           lj_trace_err(J, LJ_TRERR_NYICONV);  /* NYI: init aggregates. */
+            goto special;
          if (J->base[i]) {
            sp = J->base[i];
            sval = &rd->argv[i];
```

**Comment by MikePall** [comment]
The fix is not that simple, since some stores may already have been emitted.

I've added a proper workaround that helps the zero-fill struct-of-NYI case.
