### ISSUE TITLE
string.format doesn't take current locale decimal separator into account.

### ISSUE THREAD

**Issue by MikuAuahDark** [LuaJIT/LuaJIT#673]
Tested both in Linux and Windows, this code fails in LuaJIT but not in Lua 5.1.5.

```lua
os.setlocale("id_ID.UTF-8")
assert(string.format("%.1f", 1.2) == "1,2")
```

I wonder if this is by design (custom `string.format` implementation?) or a bug.

**Comment by MikePall** [comment]
https://luajit.org/extensions.html#tonumber
