### ISSUE TITLE
Undefined behavior vs. Lua 5.1

### ISSUE THREAD

**Issue by Buristan** [LuaJIT/LuaJIT#674]
Hi, Mike!

There are two different misbehaviours regarding  Lua 5.1 discovered in the scope of tarantool/tarantool#5790:

**The first one**:
```bash 
$ lua -e 'print(#("x"):rep(1024*1024*10000))'
Killed
$ luajit -e 'print(#("x"):rep(1024*1024*10000))'
0
$ luajit -e 'print(("x"):rep(1024):sub(1024*1024*1024*2):len())'
1024
$ luajit -e 'print(("x"):rep(1024):sub(1024*1024*1024):len())' 
0
```
The root cause relates to integer conversion of Lua numeric values in scope of [`lj_lib_checkint`](https://github.com/LuaJIT/LuaJIT/blob/787736990ac3b7d5ceaba2697c7d0f58f77bb782/src/lj_lib.c#L238), that yields a 32-bit integer value. 

**The second**:

```bash
$ lua    -e 'n = 0xfffffffe u = -0x80000000 t = {} t[u] = "surprise" t[-2] = -2 t[-1] = -1  t[0]  = 0  t[n] = "test" print(unpack(t, n, n+2))'
-2      -1      0

$ luajit -e 'n = 0xfffffffe u = -0x80000000 t = {} t[u] = "surprise" t[-2] = -2 t[-1] = -1  t[0]  = 0  t[n] = "test" print(unpack(t, n, n+2))'
surprise
```

The reason is inside [`lj_num2int`](https://github.com/LuaJIT/LuaJIT/blob/787736990ac3b7d5ceaba2697c7d0f58f77bb782/src/lj_obj.h#L990) used `cvttsd2si` instruction. It yields indefinite `80000000H` integer value, that leads to inconsistency with Lua 5.1 behavior.
The same issue was raised in #31 in a contest of FFI.

**Comment by MikePall** [comment]
It's undefined behaviour, when you pass out-of-range doubles to functions expecting integers.
I have no intent to precisely replicate undefined behavior of Lua (of any version). Particularly, since Lua actually behaves very inconsistently, depending on the version or platform.
