### ISSUE TITLE
rawequal of ctypes

### ISSUE THREAD

**Issue by sonoro1234** [LuaJIT/LuaJIT#680]
Hi,

It prints false and true

```Lua
local ffi = require"ffi"

ffi.cdef [[
typedef struct vec2 { double x, y;       } vec2;
]]

local metav2 = {
    __eq = function(a,b) return a.x == b.x and a.y == b.y end,
    __tostring = function(v) return '<'..v.x..','..v.y..'>' end
}
metav2.__index = metav2
local vec2 = ffi.metatype('vec2',metav2)

local a = vec2(1,2)

local ty = ffi.typeof(a)

print(rawequal(vec2,ty))
print(vec2==ty)
```

shouldnt it be true, true?

**Comment by GitSparTV** [comment]
In theory they are compared like two table objects, by pointer.
> return gcrefeq(o1->gcr, o2->gcr);

**Comment by sonoro1234** [comment]
Not having metamethods shouldn`t be the same using `==` and `rawequal`?

**Comment by MikePall** [comment]
I'm not sure what you want to achieve there. You're comparing two ctypes, not two cdatas. Your `__eq` metamethod is never invoked.

Also, `rawequal` is just that: 'raw'. It only compares the pointers. A ctype object is really just a cdata object with a special kind of enum ctype. And two distinct cdata objects compare 'raw-unequal'.

**Comment by sonoro1234** [comment]
> I'm not sure what you want to achieve there. You're comparing two ctypes, not two cdatas. Your `__eq` metamethod is never invoked.

I know that: it comes from https://github.com/gvx/bitser/blob/master/bitser.lua#L232 where `==` is used to know if it is `cdata` or `ctype` but it is failing when `cdata` has `__eq` metamethod as above. I expected rawequal to solve the issue. Another solution would be `tostring(cdata_or_ctype):match"^ctype"`.
