### ISSUE TITLE
LuaJIT 2.1 no longer compiles under Alpine Linux with default grep

### ISSUE THREAD

**Issue by ymph** [LuaJIT/LuaJIT#682]
I do not know if this is a real issue, but this information can be useful to someone.

Since the commit b9d523965b3f55b19345a1ed1ebc92e431747ce1, LuaJIT 2.1 no longer compiles under Alpine Linux with the default grep.

This seems to come from the introduction of the grep option `U` which is not recognized with the default alpine `grep` command.

This can be tested with the following Dockerfile:

```
FROM alpine:3.13

RUN mkdir -p /usr/src/LuaJIT && \
    apk add --no-cache build-base

COPY . /usr/src/LuaJIT/

WORKDIR /usr/src/LuaJIT

RUN make && \
    make install && \
    ln -sf luajit-2.1.0-beta3 /usr/local/bin/luajit
```

This is solved by adding the `grep` package that install `GNU grep`, replacing the `BusyBox grep`.

```
FROM alpine:3.13

RUN mkdir -p /usr/src/LuaJIT && \
    apk add --no-cache build-base grep

COPY . /usr/src/LuaJIT/

WORKDIR /usr/src/LuaJIT

RUN make && \
    make install && \
    ln -sf luajit-2.1.0-beta3 /usr/local/bin/luajit
```

**Comment by MikePall** [comment]
Fixed. Thanks!
