### ISSUE TITLE
LUAJIT2.1 Memory More than 1g crash

### ISSUE THREAD

**Issue by dengchenjin** [LuaJIT/LuaJIT#685]
Error: Not enough memory is still present in my process using LuAjit 2.1
Insufficient memory error, but crash, Luajit2.1 has not solved the memory limit problem

**Comment by dengchenjin** [comment]
Have to use LJ_GC64

**Comment by dengchenjin** [comment]
Have to use LJ_GC64 in X64 linux ,But there will still be out-of-memory crashes

**Comment by yamaken93** [comment]
@dengchenjin you can disable LJ_GC64 in the makefile i believe.

**Comment by MikePall** [comment]
Use the latest versione *BEFORE* reporting issues. Also, learn how to behave on an issue tracker.
