### ISSUE TITLE
redis-server rsync not updating in rdb files

### ISSUE THREAD

**Issue by SelviRaju** [LuaJIT/LuaJIT#686]
Hi,

Using redis db adding data to rdb files,so whwnever updation happen will give bgsave to save in rdb .

while running stress test having limitation for 150 entries,if more than 150 entries coming then will remove first entry and add 151 entry,likewises will do for all entry.

In this case in rdb files removed entries are still present,it is not removing from rdb file, is there any changes have to add

so rdb file size is keep on increasing more than MB.

Thanks & Regards,
R.Selvi

**Comment by MikePall** [comment]
You commented on the wrong repo.

**Comment by SelviRaju** [comment]
Please provide me the exact path

**Comment by sindrom91** [comment]
https://github.com/redis/redis
