### ISSUE TITLE
Bug: Unbalanced Stack After Hot Instruction error on table concatenation

### ISSUE THREAD

**Issue by fmanana** [LuaJIT/LuaJIT#690]
I came across a bug that occurs in the recording stage of LuaJIT, where table concatenation results in an unbalanced stack error.

## How to Reproduce

In order to provoke LuaJIT optimisations, a for loop was added around a table concatenation instruction in one of the test files, [events.lua](https://github.com/LuaJIT/LuaJIT-test-cleanup/blob/lua-51-testsuite/lua5.1-tests/events.lua), in the [LuaJIT-tests-cleanup](https://github.com/LuaJIT/LuaJIT-test-cleanup/tree/lua-51-testsuite) repo. The scope of the for loop that still provokes the error was reduced to a single [line](https://github.com/LuaJIT/LuaJIT-test-cleanup/blob/6fe6fbe777a01c2e700937081090b1cd6ae23686/lua5.1-tests/events.lua#L252), resulting in the following code:

```lua
...
for i = 1,100 do
    x = 0 .."a".."b"..c..d.."e".."f".."g"
end
...
```

Running LuaJIT on this modified test case throws the error:
```
lj_dispatch_call: unbalanced stack after hot instruction
```

I managed to reduce some dependencies in the original `events.lua` file and attached a simplified test file, `reduced.lua`, that also provokes the error for easier debugging.

## Suggested Fix

The stack trace lead me to the source file [lj_record.c](https://github.com/LuaJIT/LuaJIT/blob/v2.1/src/lj_record.c), where I believe there is a logical error on the following line:

https://github.com/LuaJIT/LuaJIT/blob/de772054904054af077d6f448681810e8cc1520d/src/lj_record.c#L1020

I believe this line should instead read:

```lua
emitir(IRTG(mt ? IR_NE : IR_EQ, IRT_TAB), ix->mt, lj_ir_knull(J, IRT_TAB));
```
Since my understanding of the source code is quite limited this suggestion should be carefully considered by the authors, as I found the following line also mitigates the error:

```lua
emitir(IRTG(mt ? IR_NE : IR_EQ, IRT_TAB), ix->tab, lj_ir_knull(J, IRT_TAB));
```
## Attachments

[reduced.zip](https://github.com/LuaJIT/LuaJIT/files/6349678/reduced.zip)

**Comment by MikePall** [comment]
Thank you for the reduced test case! Fixed.

The quoted original code is correct. The actual issue is the problematic interaction between the tracing and delayed execution of a tailcall to `setmetatable()` and the non-delayed tracing of the `MM_concat` continuation handler.
