### ISSUE TITLE
How can I change the source code to start jit engine much earlier?

### ISSUE THREAD

**Issue by csbinghu** [LuaJIT/LuaJIT#692]
In some websites said after the path is operated 500 times, then the jit engine will start to optimize the path.

How can I change 500 times to 50 times, so that  the script will be optimized much earlier?

**Comment by MikePall** [comment]
1. This is wrong. Optimization sets in much earlier with LuaJIT.
2. You could just **read the documentation**, which would tell you how to do this without changing the source code.
3. **You do not need to care about this.** All compiler parameters are well tuned and you should not change anything, unless you have very special needs and a deep insight into how the compiler works.
4. Do not trust random 'websites' that give you advice on compilers.
5. **Read the documentation** before opening an issue.

**Comment by csbinghu** [comment]
Sorry to bother you. 
Because I did not find enough useful information about when the jit engine will start from the wiki http://wiki.luajit.org/Home.  And then, I found some websites said after 500 times used the branch, the jit engine will be started.
In my scene, the jit engine started  the earlier,the better. 
So I thought I need to decrease 500 to 50 times to start jit engine much earlier.
Can you give me the url  about jit engine start information.
Thanks a lot.

**Comment by GitSparTV** [comment]
It's 56 not 500.
http://luajit.org/running.html

**Comment by csbinghu** [comment]
> It's 56 not 500.
> http://luajit.org/running.html

Thanks a lot !
