### ISSUE TITLE
for in pairs table, order is NOT the same each running

### ISSUE THREAD

**Issue by CatDroid** [LuaJIT/LuaJIT#693]
with the lastest commit , "
75ee3a6159f1831fa57992df3caf5a2c303c281a"

local tbl = {}
tbl["abc"] = 1 
tbl["abd"] = 2 
tbl["abe"] = 3
tbl["abf"] = 4

for k, v in pairs(tbl) do
    print(k, v)
 end

the order will change each time to run ?  is it ok ?  in beta-2 , the order will not change

**Comment by CatDroid** [comment]
print log :
first time : 
abe     3
abf     4
abc     1
abd     2

second time  
abc     1
abd     2
abe     3
abf     4

this behavior is correctly ??   not my compile issue ?

**Comment by GitSparTV** [comment]
Who said hashing is stable? It was never defined and predicted

**Comment by MikePall** [comment]
https://luajit.org/faq.html#order

**Read the documentation** before opening an issue.
