### ISSUE TITLE
Id cannot find luajit 

### ISSUE THREAD

**Issue by abirbensoltane** [LuaJIT/LuaJIT#697]
I installed lua and luajit ! both works fine but ld can't find -lluajit . I intend to use them with c++. always the cmake command get blocked because it can't find the luajit. I thought it's a prob of symlink I tried to make link but doesn't work.

**Comment by MikePall** [comment]
The library is called `libluajit-5.1.so`, so you need to use: `-lluajit-5.1`

You may want to consider using `pkgconfig`. LuaJIT installs the `*.pc` file and `pkgconfig` makes sure you get all of the compile and link options right. How to integrate `pkgconfig` into your build process is out of the scope of this issue tracker, though.

**Comment by abirbensoltane** [comment]
I just figure out the prob ! the symlink was ignored
