### ISSUE TITLE
Question: Usage of jit.off() for FFI Lua callbacks

### ISSUE THREAD

**Issue by lewis6991** [LuaJIT/LuaJIT#699]
Hi, 

We are currently trying to use FFI with a version of libxdiff for running diffs in neovim. We recently discovered this issue in neovim (https://github.com/neovim/neovim/issues/14487) and I am pretty sure it is due to the below code.

The function we want to use (`xdl_diff`) via FFI requires a callback (`xdemitconf_t.hunk_func`) which gets called for every hunk that gets generated.

I've read the FFI documentation best I can to abide by all the recommendations on using FFI with Lua callbacks, however, people are still getting the error `PANIC: unprotected error in call to Lua API (bad callback)` very occasionally. For me, I get it like once every two weeks so it is very rare.

Could someone take a look to make sure the usage of `jit.off()` is correct here? Or if possible any general advice? Could there be another reason that could result in this error other than jit compiling? Any insights would be greatly appreciated.

Sorry for pasting a wall of code. I've tried to reduce it as much as possible whilst providing enough context.

```lua
local ffi = require("ffi")

ffi.cdef([[
  typedef struct s_mmbuffer { const char *ptr; long size; } mmbuffer_t;

  typedef struct s_xpparam {
    unsigned long flags;
    char **anchors;
    size_t anchors_nr;
  } xpparam_t;

  typedef int (__stdcall *xdl_emit_hunk_consume_func_t)(
    long start_a, long count_a, long start_b, long count_b, void *cb_data
  );

  typedef struct s_xdemitconf {
    long ctxlen;
    xdl_emit_hunk_consume_func_t hunk_func;
  } xdemitconf_t;

  typedef struct s_xdemitcb {
    void *priv;
    int (__stdcall *outf)(void *, mmbuffer_t *, int);
  } xdemitcb_t;

  int xdl_diff(
    mmbuffer_t *mf1,
    mmbuffer_t *mf2,
    xpparam_t const *xpp,
    xdemitconf_t const *xecfg,
    xdemitcb_t *ecb
  );
]])

local function run_diff(fa, fb, diff_algo)
   local results = {}

   local jit_status = jit.status()

   jit.off()

   local hunk_func = ffi.cast('xdl_emit_hunk_consume_func_t', 
      function(start_a, count_a, start_b, count_b)
         table.insert(results, { start_a, count_a, start_b, count_b })
         return 0
      end
   )

   local emitconf = ffi.new('xdemitconf_t')
   emitconf.hunk_func = hunk_func

   ffi.C.xdl_diff(
       ffi.new('mmbuffer_t', fa, #fa),
       ffi.new('mmbuffer_t', fb, #fb),
       ffi.new('xpparam_t', 1),
       emitconf,
       ffi.new('xdemitcb_t')
   )

   hunk_func:free()

   if jit_status then
      jit.on()
   end

   ...   -- Code for processing results

end
```

Thanks in advance. LuaJIT is really an impressive project.

**Comment by MikePall** [comment]
Not even close.

`jit.off()/jit.on()` turn the whole JIT compiler off and on. That's **really** expensive and you should **never** do this in any code, except during debugging. You really want to call `jit.off(func)` (once!) and pass the Lua function that calls a C function which may invoke a callback.

Also, don't create and destroy the same callback on every call. And don't keep allocating structs that can be recycled.

Untested solution:
```Lua
local mmba = ffi.new('mmbuffer_t')
local mmbb = ffi.new('mmbuffer_t')
local xpparam = ffi.new('xpparam_t', 1)
local hunk_results
local hunk_func = ffi.cast('xdl_emit_hunk_consume_func_t', 
   function(start_a, count_a, start_b, count_b, _)
      hunk_results[#hunk_results+1] = { start_a, count_a, start_b, count_b }
      return 0
   end
)  
local emitconf = ffi.new('xdemitconf_t')
emitconf.hunk_func = hunk_func
local emitcb = ffi.new('xdemitcb_t')

local function run_diff_xdl()
   hunk_results = {}
   local ok = ffi.C.xdl_diff(mmba, mmbb, xpparam, emitconf, emitcb)
   local results = hunk_results
   hunk_results = nil
   return ok == 0 and results 
end

jit.off(run_diff_xdl)

local function run_diff(fa, fb, diff_algo)
   mmba.ptr = fa; mmba.size = #fa
   mmbb.ptr = fb; mmbb.size = #fb
   local results = run_diff_xdl()

   ...   -- Code for processing results

   if not results then ... error handling ... end

   ...

end
```

**Comment by MikePall** [comment]
Sigh. You're worsening this with every try. Please give someone else a chance to fix this, who knows more about Lua **and** C **and** the FFI.

And, no, please don't ask here.
