### ISSUE TITLE
dpdk   + luajit  error

### ISSUE THREAD

**Issue by cunixc** [LuaJIT/LuaJIT#706]
Reference dpdk-20.0

Reference luajit-2.1

Single process program, the content is as follows

t.c

....

rte_ eal_ init(argc, argv);

...

lua_ call(L, 2, 0);

.....

GCC compiles and executes normally in the virtual environment, but it compiles correctly on the hardware platform and runs to Lua_ Call() is empty and the process enters sleep state

**Comment by MikePall** [comment]
I do not have the slightest clue what this is supposed to mean. If you do not provide a complete, isolated, short and stand-alone (zero dependencies) testcase in pure Lua code, then do not open an issue here.
