### ISSUE TITLE
f-stack(dpdk)  Lua_Call()  error 

### ISSUE THREAD

**Issue by cunixc** [LuaJIT/LuaJIT#707]
Reference f-stack-1.21  [https://github.com/F-Stack/f-stack](url)

Reference wrk-master [https://github.com/wg/wrk](url)

Single process program, the content is as follows

int main(****)
....

ff_ init(argc, argv);

...

GCC compiles and executes normally in the virtual environment, but it compiles correctly on the hardware platform and runs to script_resolve() -> Lua_ Call() is empty and the process enters sleep state
[diff.patch.gz](https://github.com/LuaJIT/LuaJIT/files/6552166/diff.patch.gz)

wrk code diff patch

**Comment by MikePall** [comment]
This is your second nonsense issue. You have been blocked.
That diff.patch.gz is a file full of zeroes packed inside a .tar.gz. Your descripition is incomprehensible. You did not provide a testcase.
