### ISSUE TITLE
Why can a number type variable perform 2 ^ 53 operations, instead of 2 ^ 52 corresponding to double?

### ISSUE THREAD

**Issue by chinahuangdada** [LuaJIT/LuaJIT#708]
test code:

-- single digit test
local a = -9007199254740992                    -- print result is right: -9007199254740992
print(string.format("-9007199254740992: %20.0f",a))
local a = -9007199254740993                    -- print result is wrong: -9007199254740992
print(string.format("-9007199254740993: %20.0f",a))

local a = 9007199254740992                     -- print result is right: 9007199254740992
print(string.format("9007199254740992: %20.0f",a))
local a = 9007199254740993                     -- print result is wrong: 9007199254740992
print(string.format("9007199254740993: %20.0f",a))

-- traverse from 2^52 (4503599627370496)
local x = 4503599627370496
local last = x + 1
while true do
    if (x - last) ~= -1 then
        print("x -> " .. string.format("%20.0f",x) .. "    " .. (x - last))    --  print result is x ->     9007199254740992    0
        break
    end
    last = x
    x = x - 1
    if 0 == x%100000000 then
        print("x 00 -> " .. string.format("%20.0f",x))
    end
end

**Comment by MikePall** [comment]
This is an issue ttracker for LuaJIT, not a place to ask beginner questions about floating point numbers.
The behavior is correct. Read [Wikipedia](https://en.wikipedia.org/wiki/Floating-point_arithmetic).

**Comment by chinahuangdada** [comment]
Sorry, thank you.
