### ISSUE TITLE
Null byte in frontier pattern set throws "malformed pattern"

### ISSUE THREAD

**Issue by supbish** [LuaJIT/LuaJIT#709]
A null byte in frontier pattern set is supposed to signify the beginning or end of the string being searched.

> %f[set], a frontier pattern; such item matches an empty string at any position such that the next character belongs to set and the previous character does not belong to set. The set set is interpreted as previously described. The beginning and the end of the subject are handled as if they were the character '\0'. 

This works in PUC Lua 5.2:

```
> return ("foo"):match("foo%f[\0]")
foo
```

However in LuaJIT the null byte seems to terminate the string:

```
> return ("foo"):match("foo%f[\0]")
malformed pattern (missing ']')
```

**Comment by GitSparTV** [comment]
LuaJIT is ABI-compatible to lua 5.1.

**Comment by supbish** [comment]
Ah damn, thought we had 5.2 compat by now :(

**Comment by DarkWiiPlayer** [comment]
This sure sounds like something that should be a 5.2 extension though. The 5.2 behaviour of frontier-patterns is very useful and it's driving me insane that they can't be used in LuaJIT because of this dumb inability to handle null-bytes (which, by the way, affects character sets in general).
