### ISSUE TITLE
Wrong function in error message when passing nil as first argument to ffi.cast

### ISSUE THREAD

**Issue by ChliHug** [LuaJIT/LuaJIT#71]
When passing `nil` as the first argument to `ffi.cast`, I get an error message that in some cases names the wrong function. Sometimes it's also the wrong argument number and expected type.

Calling the function on its own, the correct error gets thrown: `bad argument #1 to 'cast' (C type expected, got nil)`.
However, I get the following instead for the code below: `bad argument #1 to 'Xor8' (C type expected, got nil)`.

Here's a test case that should show such an error with LuaJIT 2.0.4. It uses the builtin functions `bit.bxor` and `ffi.cast` in succession. The result of the XOR operation gets passed into the the cast as an init value, but the first argument (the ct value) is nil and causing the error.

```lua
local ffi = require("ffi")
local cast = ffi.cast

local bxor = bit.bxor
local iowrite = io.write

local function CastToUint8(v)
	return cast(THIS_IS_NIL, v)
end

local function Xor8(a, b)
	return CastToUint8(bxor(a, b))
end

iowrite(Xor8(1, 2))
```
Full error message:
```
error_issue.lua:15: bad argument #1 to 'Xor8' (C type expected, got nil)
stack traceback:
        [C]: in function 'Xor8'
        error_issue.lua:15: in main chunk
        [C]: at 0x7ff65a212700
```
Example of error message with wrong function name, argument number and expected type:
```
.\aes.lua:41: bad argument #2 to 'bxor' (number expected, got nil)
stack traceback:
        [C]: in function 'bxor'
        .\aes.lua:41: in function 'xor8'
        .\aes.lua:380: in function 'KeySchedule_Core'
        .\aes.lua:427: in function 'KeySchedule'
        aes_test.lua:255: in main chunk
        [C]: at 0x7ff65a212700
```
Pretty sure that LuaJIT tries to complain about the nil value to the cast, because the values passed to bxor are two Lua numbers. This was really confusing.

**Comment by Sh4rK** [comment]
This has been discussed before, the cause of this are the tail calls in your code.

Previous discussion: http://www.freelists.org/post/luajit/Bad-stack-trace-from-lua-getstack-and-lua-getinfo,1

If you don't want tail calls, put the returned calls in parentheses like this:
```lua
local ffi = require("ffi")
local cast = ffi.cast

local bxor = bit.bxor
local iowrite = io.write

local function CastToUint8(v)
    return (cast(THIS_IS_NIL, v)) -- HERE
end

local function Xor8(a, b)
    return (CastToUint8(bxor(a, b))) -- AND HERE
end

iowrite(Xor8(1, 2))
```

**Comment by ChliHug** [comment]
Oh, I see. Thanks.

I guess this isssue can be tagged as invalid or wontfix.
