### ISSUE TITLE
luajit: unknown luaJIT command or jit.* modules not installed

### ISSUE THREAD

**Issue by stefanos82** [LuaJIT/LuaJIT#714]
I was reading `luajit`'s man pages and tried the following command `luajit -jv -e "for i=1,10 do for j=1,10 do for k=1,100 do end end end"` to see what it does and threw the error message in the title.

Is this the expected behavior?

My compiled luajit git version is `7d267973e20c94c98ff4cd88a2a28dad0c3f7dad` under GNU / Linux Debian testing 64-bit.

**Comment by MikePall** [comment]
Well, I'm wondering how I could improve that error message: what part of that error message is unclear?

I'm sure you're aware what 'installing' a program means and/or you have read the 'Install' Page of the documentation. Correct?

This error message tells you that you did not install the `jit.*` modules. Have you done `make install`?

And are you sure that the `luajit` command you are executing is the binary you have installed (and not some other version in your `PATH`). Try `which luajit`, then look in the neighboring `share/lua/5.1/jit` directory for the modules, in particular `v.lua`, which is called by `-jv`.

**Comment by stefanos82** [comment]
> Well, I'm wondering how I could improve that error message: what part of that message is unclear?
> 

No need to be harsh here mate, I'm just reporting an issue.

> I'm sure you're aware what 'installing' a program means and/or you have read the 'Install' Page of the documentation. Correct?
> 

Yes, that is correct.

> This error message tells you that you did not install the `jit.*` modules. Have you done `make install`?
> 
Yes. I executed

```
$ make
$ sudo make install
```
Was there anything else I should have done in the first place?

> And are you sure that the `luajit` command you are executing is the binary you have installed (and not some other version in your `PATH`). Try `which luajit`, then look in the neighboring `share/luajit-*/jit` directory for the modules, in particular `v.lua`, which is called by `-jv`.

```
$ command -v luajit
/usr/local/bin/luajit
```

The path for `/usr/share/luajit-*/jit/` is `/usr/local/share/luajit-2.1.0-beta3/jit`.

When we successfully compile the code, it lets us know that we can symlink it to `luajit`.

```
==== Successfully installed LuaJIT 2.1.0-beta3 to /usr/local ====

Note: the development releases deliberately do NOT install a symlink for luajit
You can do this now by running this command (with sudo):

  ln -sf luajit-2.1.0-beta3 /usr/local/bin/luajit
```

The question is: would it be the `-2.1.0-beta3` part that causes the problem?

Please advice.

Cheers.

**Comment by MikePall** [comment]
OK, so you performed that symlink command? Then that binary should have the above path compiled in and should be able to find the `jit/v.lua` module aka `-jv`.

Maybe you have set an environment variable `LUA_PATH` from a former installation of Lua? Then unset it or modify it accordingly.

**Comment by stefanos82** [comment]
Ah yes, the good ol' `$(luarocks path)`!

So, should I append the `/usr/local/share/luajit-2.1.0-beta3/jit/` to it to make it work?

**Comment by MikePall** [comment]
Append: `/usr/local/share/luajit-2.1.0-beta3/?.lua`

**Comment by stefanos82** [comment]
Thank you @MikePall :+1:
