### ISSUE TITLE
Deterministic table iteration order

### ISSUE THREAD

**Issue by Xottab-DUTY** [LuaJIT/LuaJIT#719]
> Due to improved VM security, LuaJIT 2.1 may even use a different order
on separate VM invocations or when string keys are newly interned.
If your program relies on a deterministic order, it has a bug. Rewrite it,
so it doesn't rely on the key order. Or sort the table keys, if you must.

Unfortunately, the old game we are working on and the mods for this game rely on this old behaviour and we have strong requirement to not modify original game scripts to be compatible with it and thousands of mods. (no one will ever fix them)

Is it possible to return deterministic order for tables?
Can you give any hint, please? :) e.g. what should be changed or which commit should be reverted, altered?

**Comment by Xottab-DUTY** [comment]
Fixing bugs in Lua scripts is just not possible. Files cannot be changed. Only workarounds from the game engine or LuaJIT side are possible.

Being stuck with something old is where we at already. (I already did some changes for compatibility with LuaJIT 1.1.4)
That's why I asked for any hint, including the commit where bug with deterministic order was fixed to revert or alter it in our own custom LuaJIT.

**Comment by slime73** [comment]
You could write a custom iterator in Lua which reproduces the iteration order you expect.

**Comment by GitSparTV** [comment]
1.
Iterate table you need, save all keys into separate array in a sequence, do table.sort on it.
Now iterate array of keys and in the loop use `v` as key for your table.

2.
Make a proxy table with __newindex function, make it so when you add a new key it saves this key in separate table as order of keys, make __pairs to use that table

**Comment by Xottab-DUTY** [comment]
@slime73, @GitSparTV, thanks, but are you guys kidding me or you just didn't read my messages?))))
I'll repeat: NO LUA CODE ALLOWED. I cannot change the already written Lua scripts, even if there are bugs in them. Only workarounds from C/C++ side allowed.

**Comment by GitSparTV** [comment]
Ok, do you realize hashing doesn't have order? Even PUC Lua.

**Comment by GitSparTV** [comment]
You can always decompile, edit bytecode, detour, etc

**Comment by Xottab-DUTY** [comment]
> You can always decompile, edit bytecode, detour, etc

Why do I need to do that if I can just revert to older LuaJIT commit? This is all I need... I just need to know the commit hash..


Maybe, it is de48d000941f58a8d4d816e9d227de8a4f3c9de6, but I'm not sure.

**Comment by GitSparTV** [comment]
You want to leave a bug in the code on purpose

**Comment by slime73** [comment]
> I'll repeat: NO LUA CODE ALLOWED. I cannot change the already written Lua scripts, even if there are bugs in them. Only workarounds from C/C++ side allowed.

I was suggesting overwriting the `pairs` function with a custom implementation before the Lua scripts you want to use are loaded. You could either do this via Lua code directly, or in C by using Lua's C API. Either way you wouldn't need to edit the existing Lua scripts that have bugs in them, unless I'm missing something.

That being said, this issue tracker is not the right place to discuss this topic.

**Comment by Xottab-DUTY** [comment]
We have managed to find the problematic commit and revert it – ff34b48ddd6f2b3bdd26d6088662a214ba6b0288.
After this, scripts started to work correctly, as before.

I hope this revert is temporary and we will find alternative fix, but for now we need stable scripts.

**Comment by jgm** [comment]
<https://babelmark.github.io/?text=____a__!__!___>
shows commonmark.js 0.28.1 giving the output with `<em>`.  So I suspect some relatively recent change to the parsers is responsible for this.
Possibly https://github.com/commonmark/cmark/issues/383
