### ISSUE TITLE
\u escapes aren't compatible with Lua 5.3's \u escapes

### ISSUE THREAD

**Issue by SoniEx2** [LuaJIT/LuaJIT#72]
`"\u{d800}"` works under Lua 5.3 but doesn't work under LuaJIT.

**Comment by MikePall** [comment]
Surrogates are [forbidden in UTF-8](http://unicode.org/faq/utf_bom.html#utf8-4). Lua 5.3 fails to check for that, LuaJIT does.

**Comment by SoniEx2** [comment]
Reading material:

https://en.wikipedia.org/wiki/UTF-8#Derivatives

https://en.wikipedia.org/wiki/UTF-8#Invalid_code_points

**Comment by SoniEx2** [comment]
Also the Lua 5.3 reference manual only says it checks the range.
