### ISSUE TITLE
Plans for change LUA_NUMBER

### ISSUE THREAD

**Issue by MaryWan1982** [LuaJIT/LuaJIT#721]
@MikePall 
Is there any plan to support  "change LUA_NUMBER"?

for example LUA_NUMBER to int64

**Comment by MikePall** [comment]
No. Changing the core number type would need a complete rewrite of the whole VM. Apart from breaking almost every Lua script out there ...

Also, you can already use int64 with the FFI. Just write `1LL` or `1ULL`.
