### ISSUE TITLE
Terminate lua code

### ISSUE THREAD

**Issue by codeservice** [LuaJIT/LuaJIT#723]
I have lua code with endless cycle:
**while true do end**

Trying to terminate it in C code:
static void lstop(lua_State* L, lua_Debug* ar) {
    (void)ar;
    lua_sethook(L, NULL, 0, 0);
    luaL_where(L, 0);
    lua_pushfstring(L, "%sinterrupted!", lua_tostring(L, -1));
    lua_error(L);
}
lua_sethook(lua->l, lstop, LUA_MASKCALL | LUA_MASKRET | LUA_MASKLINE | LUA_MASKCOUNT, 0);

This C code doesn't stop LuaJIT while cycle code, but did stop in original Lua.

C code works in LuaJIT as soon as I add additional command in while cycle: **while true do print('test') end**

**Comment by MikePall** [comment]
JIT-compiled code doesn't check for hooks by default. Please see the end of `src/lj_record.c` for a workaround (but it does come at a cost).

Please note that this will not help you to stop Lua code that's stuck inside a C function (but neither does this work in plain Lua).

**Comment by codeservice** [comment]
>> doesn't check for hooks by default

I did use:
@set LJCOMPILE=cl /nologo /c /O2 /W3 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_STDIO_INLINE=__declspec(dllexport)__inline /DLUAJIT_ENABLE_LUA52COMPAT /DLUAJIT_ENABLE_CHECKHOOK

Still the same problem, maybe wrong place for flag

**Comment by ChaseCarlson** [comment]
I know this is super late, but this isn't a compile-time issue.

Look at the count parameter in this call of yours:
```c
lua_sethook(lua->l, lstop, LUA_MASKCALL | LUA_MASKRET | LUA_MASKLINE | LUA_MASKCOUNT, 0);
```
If the count parameter is 0, the hook will not fire. Set it to one as such and remove the other mask flags (just doing count):
```c
lua_sethook(lua->l, lstop, LUA_MASKCOUNT, 1);
```

Should work wonders. Let me know if it works.
