### ISSUE TITLE
ITERN deoptimization might skip elements

### ISSUE THREAD

**Issue by XmiliaH** [LuaJIT/LuaJIT#727]
The `ITERN` optimization checks with the `ISNEXT` instruction in the beginning of the loop that the iterator is `next` and uses the key slot of the for loop for the index into the table. This value is a userdata 0xFFFE7FFFXXXXXXXX whereby the lower 32 bit denote the index into the table. The upper bits are the userdata tag and some dummy pointer bytes. With the use of `lua_pushlightuserdata` it is possible to get such userdata pointers too (at least on GC64).
The problem now arises if the `ITERN` instruction is deoptimized while the loop is running since the userdata is passed as key into the real `next` function and the userdata used as index might be in the table too, skipping some elements.
This can be seen in the following example, which uses buffers to get the pointer to not require a native lua module.

```lua

-- The code below is just to get the tagged double user pointer 0xFFFE7FFF00000002.
-- This could also be done via lua_pushlightuserdata.

local buffer = require"string.buffer"

local up

for i = 0, 255 do
    local ok, ptr = pcall(buffer.decode, "\x05\x02\x00\x00\x00\xFF\xFF\xFF" .. string.char(i))
    if ok then
        up = ptr
    else
        break
    end
end

-- We now have the tagged double user pointer 0xFFFE7FFF00000002 in up.

-- These pointers are special in for loop keys as they are used in the INTERN optimization to denote the current index in the array.
-- If the ITERN is then patched to ITERC because of deoptimization the key is actually found in the array and some elements are skipped.

local real_next = next
local next = next

function itern_test(t, c)
    for k,v in next, t do
        c(k, v)
    end
end

itern_test({1, 2, 3, 4, 5, 6, 7, k=1, v=2, s=4, t=4, h=5, [up] = 345}, function(k, v)
    print(k, v)
    if next == real_next then
        next = function(t, k)
            print(k)
            return real_next(t, k)
        end
        -- Deoptimise
        --[[Deoptimize]] itern_test({s=3}, function()end)
    end
end)
```
The first itern_test will not print all the keys and values if the deoptimization happen since it will jump to the `up` entry skipping elements.

**Comment by MikePall** [comment]
Fixed. Thanks!
