### ISSUE TITLE
Question about md5 benchmark on the Luajit website

### ISSUE THREAD

**Issue by zcaudate** [LuaJIT/LuaJIT#728]
There is a comparison benchmark of Luajit vs PUC lua and what stood out was the performance of `md5` 

https://luajit.org/performance_x86.html - 134x
https://luajit.org/performance_arm.html - 64x

Is there a reason why it's so quick? especially on x86?

**Comment by MikePall** [comment]
The MD5 benchmark consists mainly of bit operations. In plain Lua these are C function calls from the `bit` library (and run from an interpreter). The JIT compiler can inline those to a single instruction, which explains the huge difference.

Also, the JIT-compiled code of MD5 is close to the optimal case for an out-of-order CPU. The ARM CPU under test has inferior OOO execution capabilities compared to the tested x86/x64 CPU, which limits the potential gain.
