### ISSUE TITLE
Is there a better way to convert hexadecimal strings to numbers?

### ISSUE THREAD

**Issue by baby0o01999** [LuaJIT/LuaJIT#729]
```lua
Is there a better way?
local function hex2number(hex)
    return loadstring("return " .. hex)()
end

local hexstr = "0x7fe5e840a94LL"

local val = hex2number(hexstr)
print(bit.tohex(val))   --ok

print(tonumber(hexstr))  --- nil

```

```lua
000007fe5e840a94
nil
```

**Comment by waruqi** [comment]
please trim trailing `LL`

```console
> print(string.format("%x", tonumber("0x7fe5e840a94")))
7fe5e840a94
```

**Comment by baby0o01999** [comment]
> please trim trailing `LL`
> 
> ```
> > print(string.format("%x", tonumber("0x7fe5e840a94")))
> 7fe5e840a94
> ```

tonumber() converts to the Lua number type, which is a floating-point double. Don't do that, if you want to keep 64 bits of precision.

https://github.com/LuaJIT/LuaJIT/issues/703

**Comment by baby0o01999** [comment]
> please trim trailing `LL`
> 
> ```
> > print(string.format("%x", tonumber("0x7fe5e840a94")))
> 7fe5e840a94
> ```

tonumber() converts to the Lua number type, which is a floating-point double. Don't do that, if you want to keep 64 bits of precision.

https://github.com/LuaJIT/LuaJIT/issues/703

**Comment by waruqi** [comment]
```lua
function hex2num(s)
    s = s:sub(3)
    n = #s
    s2 = s:sub(n - 7)
    s1 = s:sub(1, n - #s2)
    return tonumber("0x" .. s1) * 0x100000000LL + tonumber("0x" .. s2)
end
```

**Comment by MikePall** [comment]
Call `strtoull()` via the FFI.
