### ISSUE TITLE
dynasm.lua: Can misparse a logical OR C expression

### ISSUE THREAD

**Issue by spc476** [LuaJIT/LuaJIT#73]
The following is legal C:

    if (
          isdigit(*parse->t)
          || ((*parse->t == '-') && isdigit(*(parse->t + 1)))
        )

But dynasm.lua will mistakenly convert this to:

    if (
          isdigit(*parse->t)
          ((*parse->t == '-') && isdigit(*(parse->t + 1)))
        )

Which is not legal C.  I can work around the issue, but it violates the coding standard I use (admittedly I might be the only one to use said standard, but still ... )

**Comment by corsix** [comment]
In any context, lines starting with `||` are useful to get dynasm pre-preprocessor identifiers expanded, as in:
```
||#if ((defined(_M_X64) || defined(__amd64__)) != X64) || (defined(_WIN32) != WIN)
#error "Wrong DynASM flags used: pass `-D X64` and/or `-D WIN` to dynasm.lua as appropriate"
#endif
```
Hence the potential suggestion of "don't recognise `||` outside of `.macro`" isn't particularly viable. Similarly, the potential suggestion of "warn if a `||` line isn't changed by pre-preprocessor expansion" isn't particularly viable, as in some cases it is expected that the above example will be unchanged by the pre-preprocessor.

I guess another potential suggestion is "dynasm should be aware of C syntax, and realise when it is in a context where `||` is valid C, and not recognise `||` as a dynasm-directive in such places". This suggestion has zero mileage: dynasm is currently totally blind to C syntax, and making it sufficiently aware would require a full C preprocessor and frontend. It would also be a bit of pig to then document when `||` at the start of a line has a dynasm effect or not.

While I don't always agree with @MikePall's assessments of if-it-hurts-don't-do-it, I feel like this is very much an if-it-hurts-don't-do-it scenario.

**Comment by spc476** [comment]
Yeah, I came across some unofficial documentation that stated as much (although much to my chagrin, I didn't bother to bookmark it, and now I can't seem to locate it).  So I guess this bug is more a "documentation is obtuse" than "an actual bug in the code".  

It's a pity that Mike didn't use one of three symbols not used by C.  I can understand why he might not have picked the "`" as it could be too easily overlooked, but that still leaves "$" or "@" (my pick as it's very obvious when seen).  But I suppose it's too late to change.

**Comment by corsix** [comment]
> and now I can't seem to locate it

http://corsix.github.io/dynasm-doc/

**Comment by spc476** [comment]
Ah, that's why I couldn't find it.  I was searching for "|" and instead it's

"Lines from the DynASM source file that do not start with a vertical bar are copied verbatim to the output file. Lines that start with one vertical bar can contain assembly instructions or assembler directives, and will generally be rewritten to C lines of the form dasm_put(Dst, ...). Lines that start with two vertical bars are treated as C code, but undergo prepreprocessor substitutions created by .define, and can be part of .macro definitions."

i.e. it was spelled out.

Thanks.
