### ISSUE TITLE
a bug abort table.sort

### ISSUE THREAD

**Issue by cnoder** [LuaJIT/LuaJIT#730]
`local tbl = {
    {
        sort = 1,
    },
    {
        sort = 4,
    },
    {
        sort = 2,
    },
    {
        sort = 3,
    },
}

table.sort(tbl, function(a, b)
    return a['sort'] <= b['sort']
end)

for _, v in ipairs(tbl) do
    print(v['sort'])
end
-- print 1 2 4 3`

expect print 1 2 3 4,
or throw an error like lua5.4.3 "invalid order function for sorting" when 2 equal item return false in anonymous function.

**Comment by MikePall** [comment]
You're violating the contract for the sorting function as specified in the Lua `table.sort()` reference. Anything can happen. The algorithm for detecting an invalis sorting function is heuristic, so it may or may not catch it.

Anyway, Lua 5.1 behavior is identical, so not a bug.
