### ISSUE TITLE
Remove lualib and everything but c code binding?

### ISSUE THREAD

**Issue by Shadowblitz16** [LuaJIT/LuaJIT#731]
Is there a way to remove luajit's default lua libraries but leave in c code binding?

I want to mess around with os dev for raspberry pi and I would like to build these libraries for myself

**Comment by MikePall** [comment]
No, not really. The standard libraries and the JIT compiler are integrated, that's part of the reason why LuaJIT is fast. You can choose not to load some libraries, but the impact on memory usage would be quite small.

The JIT compiler cannot do anything for you, if you're using the classic Lua/C binding. You might as well use plain Lua then.

**Comment by Shadowblitz16** [comment]
@MikePall 
I just find the libc's naming convention awful.
also in os dev libc isn't available by default.
