### ISSUE TITLE
how support int64 integer?

### ISSUE THREAD

**Issue by RPG3D** [LuaJIT/LuaJIT#732]
any mod to support full int64?

**Comment by GitSparTV** [comment]
Yes it's called ffi.

Type `ffi.new("int64_t", 0)` or `0LL`

**Comment by RPG3D** [comment]
> Yes it's called ffi.
> 
> Type `ffi.new("int64_t", 0)` or `0LL`.
> Don't forget to `require("ffi")`for the first variant

this needs modify exists lua files, I want to find some luajit mods to avoid changing exist lua files.

**Comment by GitSparTV** [comment]
Change they bytecode on the fly or detour lua_loadstring.
All numbers all doubles by default
