### ISSUE TITLE
how to use macro in lua script with lua-ffi ?  

### ISSUE THREAD

**Issue by LightSun** [LuaJIT/LuaJIT#738]

**Comment by XmiliaH** [comment]
As stated in https://luajit.org/ext_ffi_api.html#ffi_cdef no pre-processor tokens are allowed, except for `#pragma pack`. Instead you should replace `#define` in existing C header files with enum, static const or typedef and/or pass the files through an external C pre-processor (once).

**Comment by LightSun** [comment]
@XmiliaH ok , how about parse '#define' in ffi_cdef.

**Comment by XmiliaH** [comment]
This would need to be implemented and would increase the complexity of the parser. Since this is unlikely to happen you should remove the `#define` either by using a C pre-processor or by hand.
