### ISSUE TITLE
issue for os.execute in Windows

### ISSUE THREAD

**Issue by hyee** [LuaJIT/LuaJIT#74]
Seems that when a command line starts/ends with quote("), os.execute sometimes would trim the quotes, thus the command fails to execute. For example:

    os.execute('"d:\\java\\bin\\java" "safdsa"')        ==> Command becomes d:\java\bin\java" "safdsa
    os.execute([["d:\\java\\bin\\java" "safdsa"]])      ==> Same to above
    os.execute('"d:\\java\\bin\\java" safdsa')          ==> This is correct:  "d:\java\bin\java" safdsa
    os.execute('"d:\\java\\bin\\java" "safdsa" ssdf') ==> Command becomes d:\java\bin\java" "safdsa" ssdf

If it is a problem, hope it can be fixed. Thanks

**Comment by pkulchenko** [comment]
This is a feature of Windows shell interpreter cmd.exe as discussed [here](http://lua-users.org/lists/lua-l/2013-11/msg00367.html) and [here](http://www.freelists.org/post/luajit/What-issues-does-the-LuaJIT-user-community-consider-the-most-important,3). The solution is to apply another set of quotes around the entire command (`os.execute([[""d:\\java\\bin\\java" "safdsa""]])`) or to prepend `type NUL &&` (`os.execute('type NUL && "d:\\java\\bin\\java" "safdsa"')`).

**Comment by hyee** [comment]
Note with thanks.
