### ISSUE TITLE
Mac os Big sur M1 build error

### ISSUE THREAD

**Issue by leobowu** [LuaJIT/LuaJIT#742]
LuaJIT version : LuaJIT-2.1.0-beta3
mac os version: 11.5.1
MacBook Pro (13-inch, M1, 2020)
xcode version : Version 12.5.1 (12E507)

    _loadjitmodule in luajit.o
  "_lua_setfield", referenced from:
      _pmain in luajit.o
  "_lua_sethook", referenced from:
      _laction in luajit.o
      _lstop in luajit.o
  "_lua_settop", referenced from:
      _main in luajit.o
      _pmain in luajit.o
      _dotty in luajit.o
      _loadjitmodule in luajit.o
      _runcmdopt in luajit.o
      _pushline in luajit.o
  "_lua_toboolean", referenced from:
      _print_jit_status in luajit.o
  "_lua_tolstring", referenced from:
      _main in luajit.o
      _pmain in luajit.o
      _print_jit_status in luajit.o
      _dotty in luajit.o
      _traceback in luajit.o
      _lstop in luajit.o
      _loadjitmodule in luajit.o
      ...
  "_lua_type", referenced from:
      _main in luajit.o
      _pmain in luajit.o
      _dotty in luajit.o
      _traceback in luajit.o
      _loadjitmodule in luajit.o
      _runcmdopt in luajit.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [luajit] Error 1
make: *** [default] Error 2

**Comment by MikePall** [comment]
This is either not using the latest git commit or not using the provided Makefile.

**Comment by leobowu** [comment]
export PATH=/usr/bin:/bin:/usr/sbin:/sbin  helps me slove the problem.

**Comment by AlexandreCA** [comment]
I reopen this topic because I have the same problem, except that I am under Monterey.

Here is the error code:

alexandremate@AirdeAlexandre build % make
[  3%] Built target detour
[  6%] Built target spdlog
[  9%] Built target common
[ 11%] Built target topaz_connect
[ 51%] Built target packets
[ 54%] Built target ai_controllers
[ 56%] Built target ai_helpers
[ 61%] Built target ai_states
[ 64%] Built target entities
[ 68%] Built target items
[ 72%] Built target lua_bindings
[ 79%] Built target utils
[ 79%] Built target ai
[ 80%] Linking CXX executable ../../../topaz_game
ld: warning: dylib (/usr/local/lib/libluajit-5.1.dylib) was built for newer macOS version (12.0.1) than being linked (12.0)
ld: warning: dylib (/usr/local/lib/libluajit-5.1.dylib) was built for newer macOS version (12.0.1) than being linked (12.0)
undef: _lua_seti
undef: _lua_compare
undef: _lua_len
undef: _lua_pcallk
undef: _lua_rotate
undef: _lua_geti
undef: _lua_absindex
undef: _lua_isinteger
undef: _lua_callk
undef: _lua_getglobal
undef: _lua_setglobal
Undefined symbols for architecture arm64:
  "_lua_seti", referenced from:
      sol::basic_table_core<false, sol::basic_reference<false> >& sol::basic_table_core<false, sol::basic_reference<false> >::traverse_set<int&, int&>(int&, int&) in lto.o
      luautils::GetMagianTrial(sol::variadic_args) in lto.o
  "_lua_compare", referenced from:
      bool sol::operator==<false, false>(sol::basic_reference<false> const&, sol::basic_reference<false> const&) in lto.o
  "_lua_len", referenced from:
      CLuaBaseEntity::pathThrough(sol::basic_table_core<false, sol::basic_reference<false> > const&, sol::basic_object<sol::basic_reference<false> > const&) in lto.o
  "_lua_pcallk", referenced from:
      CCommandHandler::call(sol::state&, CCharEntity*, signed char const*) in lto.o
      sol::protected_function_result sol::basic_protected_function<sol::stack_reference, true, sol::basic_reference<false> >::invoke<true>(sol::types<>, std::__1::integer_sequence<unsigned long>, long, sol::detail::protected_handler<true, sol::basic_reference<false> >&) const in lto.o
      sol::protected_function_result sol::basic_protected_function<sol::stack_reference, true, sol::basic_reference<false> >::invoke<false>(sol::types<>, std::__1::integer_sequence<unsigned long>, long, sol::detail::protected_handler<false, sol::basic_reference<false> >&) const in lto.o
      sol::protected_function_result sol::basic_protected_function<sol::basic_reference<false>, false, sol::basic_reference<false> >::invoke<true>(sol::types<>, std::__1::integer_sequence<unsigned long>, long, sol::detail::protected_handler<true, sol::basic_reference<false> >&) const in lto.o
      sol::protected_function_result sol::basic_protected_function<sol::basic_reference<false>, false, sol::basic_reference<false> >::invoke<false>(sol::types<>, std::__1::integer_sequence<unsigned long>, long, sol::detail::protected_handler<false, sol::basic_reference<false> >&) const in lto.o
  "_lua_rotate", referenced from:
      sol::protected_function_result::~protected_function_result() in lto.o
      decltype(auto) sol::basic_protected_function<sol::stack_reference, true, sol::basic_reference<false> >::call<>() const in lto.o
      call_onRecordTrigger(CCharEntity*, unsigned short, std::__1::vector<RoeDatagram, std::__1::allocator<RoeDatagram> > const&) in lto.o
      sol::basic_table_iterator<sol::basic_reference<false> >::~basic_table_iterator() in lto.o
      decltype(auto) sol::basic_protected_function<sol::basic_reference<false>, false, sol::basic_reference<false> >::call<CLuaBaseEntity, CLuaStatusEffect>(CLuaBaseEntity&&, CLuaStatusEffect&&) const in lto.o
      decltype(auto) sol::basic_protected_function<sol::basic_reference<false>, false, sol::basic_reference<false> >::call<CLuaBaseEntity>(CLuaBaseEntity&&) const in lto.o
      CBattleEntity::takeDamage(int, CBattleEntity*, ATTACK_TYPE, DAMAGE_TYPE) in lto.o
      ...
  "_lua_geti", referenced from:
      decltype(auto) sol::basic_table_core<true, sol::basic_reference<false> >::traverse_get_deep_optional<true, false, (sol::detail::insert_mode)0, sol::optional<int>, char const (&) [6], unsigned short&, char const (&) [5], char const*&>(int&, int, char const (&) [6], unsigned short&, char const (&) [5], char const*&) const in lto.o
      CLuaBaseEntity::atPoint(sol::variadic_args) in lto.o
      CLuaBaseEntity::pathThrough(sol::basic_table_core<false, sol::basic_reference<false> > const&, sol::basic_object<sol::basic_reference<false> > const&) in lto.o
      CLuaBaseEntity::setPos(sol::variadic_args) in lto.o
      CLuaBaseEntity::addItem(sol::variadic_args) in lto.o
      CLuaBaseEntity::storeWithPorterMoogle(unsigned short, sol::basic_table_core<false, sol::basic_reference<false> > const&, sol::basic_table_core<false, sol::basic_reference<false> > const&) in lto.o
      decltype(auto) sol::basic_table_core<false, sol::basic_reference<false> >::get<sol::optional<unsigned int>, int&>(int&) const in lto.o
      ...
  "_lua_absindex", referenced from:
      sol::protected_function_result::~protected_function_result() in lto.o
      sol::state_view::do_file(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, sol::load_mode) in lto.o
      sol::basic_protected_function<sol::stack_reference, true, sol::basic_reference<false> >::basic_protected_function(lua_State*, int, sol::basic_reference<false>) in lto.o
      decltype(auto) sol::basic_protected_function<sol::stack_reference, true, sol::basic_reference<false> >::call<>() const in lto.o
      sol::stack::push_popper<false, sol::basic_table_core<true, sol::basic_reference<false> >&, void>::push_popper(sol::basic_table_core<true, sol::basic_reference<false> >&) in lto.o
      int sol::stack::unqualified_pusher<sol::detail::as_value_tag<CLuaBaseEntity>, void>::push_fx<sol::stack::stack_detail::undefined_metatable&, CLuaBaseEntity>(lua_State*, sol::stack::stack_detail::undefined_metatable&, CLuaBaseEntity&&) in lto.o
      call_onRecordTrigger(CCharEntity*, unsigned short, std::__1::vector<RoeDatagram, std::__1::allocator<RoeDatagram> > const&) in lto.o
      ...
  "_lua_isinteger", referenced from:
      CCommandHandler::call(sol::state&, CCharEntity*, signed char const*) in lto.o
      sol::stack::qualified_getter<sol::optional<int>, void>::get(lua_State*, int, sol::stack::record&) in lto.o
      decltype(stack_detail::unchecked_get<unsigned short>(fp, fp0, fp1)) sol::stack::get<unsigned short>(lua_State*, int, sol::stack::record&) in lto.o
      decltype(stack_detail::unchecked_get<unsigned int>(fp, fp0, fp1)) sol::stack::get<unsigned int>(lua_State*, int, sol::stack::record&) in lto.o
      decltype(stack_detail::unchecked_get<unsigned char>(fp, fp0, fp1)) sol::stack::get<unsigned char>(lua_State*, int, sol::stack::record&) in lto.o
      decltype(stack_detail::unchecked_unqualified_get<long>(fp, fp0, fp1)) sol::stack::unqualified_get<long>(lua_State*, int, sol::stack::record&) in lto.o
      decltype(stack_detail::unchecked_get<int>(fp, fp0, fp1)) sol::stack::get<int>(lua_State*, int, sol::stack::record&) in lto.o
      ...
  "_lua_callk", referenced from:
      void sol::detail::handle_protected_exception<true, sol::basic_reference<false> >(lua_State*, sol::optional<std::exception const&>, char const*, sol::detail::protected_handler<true, sol::basic_reference<false> >&) in lto.o
  "_lua_getglobal", referenced from:
      CCommandHandler::call(sol::state&, CCharEntity*, signed char const*) in lto.o
      sol::basic_protected_function<sol::stack_reference, true, sol::basic_reference<false> >::get_default_handler(lua_State*) in lto.o
      void sol::detail::handle_protected_exception<true, sol::basic_reference<false> >(lua_State*, sol::optional<std::exception const&>, char const*, sol::detail::protected_handler<true, sol::basic_reference<false> >&) in lto.o
      void sol::detail::handle_protected_exception<false, sol::basic_reference<false> >(lua_State*, sol::optional<std::exception const&>, char const*, sol::detail::protected_handler<false, sol::basic_reference<false> >&) in lto.o
      sol::basic_protected_function<sol::basic_reference<false>, false, sol::basic_reference<false> >::get_default_handler(lua_State*) in lto.o
      sol::detail::lua_cfunction_trampoline(lua_State*, int (*)(lua_State*)) in lto.o
      call_onRecordTrigger(CCharEntity*, unsigned short, std::__1::vector<RoeDatagram, std::__1::allocator<RoeDatagram> > const&) in lto.o
      ...
  "_lua_setglobal", referenced from:
      CCommandHandler::call(sol::state&, CCharEntity*, signed char const*) in lto.o
      sol::basic_table_core<true, sol::basic_reference<false> >& sol::basic_table_core<true, sol::basic_reference<false> >::traverse_set<std::__1::tuple<char const (&) [16]>, sol::function_arguments<sol::function_sig<>, void (*)(sol::basic_table_core<false, sol::basic_reference<false> > const&)> >(std::__1::tuple<char const (&) [16]>&&, sol::function_arguments<sol::function_sig<>, void (*)(sol::basic_table_core<false, sol::basic_reference<false> > const&)>&&) in lto.o
      sol::basic_table_core<true, sol::basic_reference<false> >& sol::basic_table_core<true, sol::basic_reference<false> >::traverse_set<std::__1::tuple<char const (&) [14]>, sol::function_arguments<sol::function_sig<>, void (*)(sol::basic_table_core<false, sol::basic_reference<false> > const&)> >(std::__1::tuple<char const (&) [14]>&&, sol::function_arguments<sol::function_sig<>, void (*)(sol::basic_table_core<false, sol::basic_reference<false> > const&)>&&) in lto.o
      CLuaBaseEntity::Register() in lto.o
      CLuaStatusEffect::Register() in lto.o
      luautils::init() in lto.o
      luautils::CacheLuaObjectFromFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool) in lto.o
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [../topaz_game] Error 1
make[1]: *** [src/map/CMakeFiles/topaz_game.dir/all] Error 2
make: *** [all] Error 2

**Comment by bferguson3** [comment]
> export PATH=/usr/bin:/bin:/usr/sbin:/sbin helps me slove the problem.

No idea why but this fixed my problem as well.
