### ISSUE TITLE
Xbox Original

### ISSUE THREAD

**Issue by UkooLabs** [LuaJIT/LuaJIT#746]
Hi,

Im currently thinking of switching my lua engine to LuaJit, however the platforms other than windows, linux i need to support are...

1) XBOX Original
2) XBOX 360
3) UWP (XBOX One)

Now I know you have 360, and I think UWP in the works but wondering about XBOX Original. On assumption you dont plan on supporting it, can you provide me some pointers on how I would get started?

Thanks in advance

**Comment by MikePall** [comment]
For the newer XBoxes, use LuaJIT v2.1 git and the provided `xedkbuild.bat` and `xb1build.bat`.

But the XBox Original doesn't have SSE2, so you need to stay with LuaJIT v2.0 git. You need a mix of a native compile (plain MSVC 32 bit (!)) and a cross-compile (the compiler from the XBox DevKit). Start modifying a copy of `msvcbuild.bat` according to the two-phase compile you can find e.g. in the `xedkbuild.bat`, but of course stay with x86 32 bit. Then fix `lj_arch.h` until it compiles. You certainly need to add `#define LJ_TARGET_CONSOLE 1` and `#define LUAJIT_DISABLE_FFI` and maybe some others.

**Comment by MikePall** [comment]
Closing for now. May reopen later, in case you report progress.
