### ISSUE TITLE
Compiler warning for implicit cast

### ISSUE THREAD

**Issue by fmanana** [LuaJIT/LuaJIT#749]
https://github.com/LuaJIT/LuaJIT/blob/cb0f124f8f8717eb235989f9c86168140fbf96fd/src/lj_asm.c#L1031

The implicit conversion on this line causes the following compiler warning:
```
warning C4244: '=': conversion from 'ptrdiff_t' to 'uint16_t', possible loss of data
```

The variable `ofs` should be explicitly cast to `uint16_t` and have a sanity check to ensure no loss of data

**Comment by MikePall** [comment]
Fixed. Thanks!
