### ISSUE TITLE
error: 'O_CLOEXEC' undeclared (first use in this function)

### ISSUE THREAD

**Issue by shubham95** [LuaJIT/LuaJIT#751]
https://github.com/LuaJIT/LuaJIT/blob/e4b4d9451402be704d5b47a359f640a29db4977f/src/lj_prng.c#L221

Hi @MikePall this error is coming one of old LInux distro(RedHAT) cannot check version

Error is error: 'O_CLOEXEC' undeclared (first use in this function)

Is there fallback if O_CLOEXEC is not defined

**Comment by MikePall** [comment]
The `O_CLOEXEC` flag was introduced 14 years ago in Linux. Not sure why anyone would want to run a distro that old.

You could define the flag yourself, in case the kernel supports it, but the distro headers don't: `#define O_CLOEXEC 0x80000`

But if the kernel also doesn't support it (< 2.6.23), then: `#define O_CLOEXEC 0`
