### ISSUE TITLE
Question about disabling the jit on compiling and performance

### ISSUE THREAD

**Issue by yamaken93** [LuaJIT/LuaJIT#752]
I have a huge monolitic codebase(they all run in the same lua state) which is not jitable(too much branching, huge call stacks, closures, lua c api functions, pairs, etc) so i think the jit subsystem is trying to jit a codebase that is not jitable. If i disable the jit subsystem in the makefile will i get more performance in general? I use lua 2.0.5 since i had issues(crashs) with 2.1.

**Comment by MikePall** [comment]
You can also manually disable the JIT compiler at runtime with `jit.off()`, if you are sure it does not provide a benefit. But the VM already falls back to the interpreter when needed. Without benchmarking this yourself, it's hard to provide a general answer. Anyway, the LuaJIT interpreter is still a lot faster than the Lua interpreter.

If you have issues with LuaJIT 2.1 then you should test with v2.1 git HEAD and then open an issue with a reduced and isolated pure-Lua testcase that clearly shows the problem.

But the most likely cause are issues with C bindings. Temporarily enable assertions in `src/Makefile`, which will point out some common violations of the classic Lua/C API.
