### ISSUE TITLE
String buffer methods may be called one extra time after loop

### ISSUE THREAD

**Issue by vfprintf** [LuaJIT/LuaJIT#755]
```lua
local buffer = require "string.buffer"
local tab = {}
for i=1, 100 do tab[i] = i end
local buf = buffer.new()
for _ in ipairs(tab) do
	buf:put(".")
end
print(#buf)
```

With `-joff` the above code prints `100`, with JIT on it prints `101`. Adding something that creates a snapshot after `buf:put()` "fixes" it. For example, inserting a write in the loop works:
```lua
for _ in ipairs(tab) do
	buf:put(".")
	x = 0 -- write to global variable
end
```

I think the cause is that `recff_buffer_method_*` functions don't set `J->needsnap = 1`, so it won't create a snapshot after the `BUFPUT` instruction. Then when the vm exits from the loop to interpreter, it restores the snapshot before the `put`, and the interpreter re-executes the `put` call.

**Comment by MikePall** [comment]
Fixed. Thanks!
