### ISSUE TITLE
why init the char[?] VLA with the suffix 0x when the init value is a Lua string

### ISSUE THREAD

**Issue by doujiang24** [LuaJIT/LuaJIT#758]
In the following case, the cdata's length is 3, but init it with 4 bytes, with the suffix `0x0`.
```
local t_char = ffi.typeof("char[?]")
local str = "ABC"
local cdata = t_char(#str, str)
```

I didn't find specific instructions in the documentation, but it feels a bit counter-intuitive.
So I got this question. Thanks!

I have checked the source code here:
https://github.com/LuaJIT/LuaJIT/blob/v2.1/src/lj_cconv.c#L591

originally reported from https://github.com/openresty/luajit2/issues/134

**Comment by MikePall** [comment]
Quoting https://luajit.org/ext_ffi_api.html#init

> Byte arrays may also be initialized with a Lua string. This copies the whole string **plus a terminating zero-byte**. The copy stops early only if the array has a known, **fixed** size.

A VLA does not have a fixed size. So you need to use `t_char(#str+1, str)` in your code.
