### ISSUE TITLE
Use .dylib instead of .so in package.cpath on Mac OS X

### ISSUE THREAD

**Issue by kostja** [LuaJIT/LuaJIT#76]
Currently the shared library extension is hard coded in the build files, so Mac OS X native libraries don't work in 'require'.

**Comment by slime73** [comment]
.so is also (weirdly) used in PUC Lua's package.cpath in OS X. Maybe LuaJIT could look for both .so and .dylib?

**Comment by kostja** [comment]
What's the point in looking for both?

**Comment by slime73** [comment]
Programs might be relying on the .so extension being searched for in OS X.
