### ISSUE TITLE
Is it possible to use symbol table ?

### ISSUE THREAD

**Issue by synxroform** [LuaJIT/LuaJIT#763]
Currently LuaJIT ffi use symbols from export table of the executable (__declspec(dllexport)). Is it possible to use entries from symbol table instead ? I know it's impossible with dlsym/GetProcAddress, but maybe some custom dlsym_like function can help. This feature is helpfull when plumbing large API's to LuaJIT, primarily on Windows because compiler options like -rdynamic or --export-all-symbols don't affect the resulting executable export table.

**Comment by fsfod** [comment]
You could use this Lua C API I created to bind non exported APIs using ffi for LuaJIT that takes an array of function pointers and ffi function definitions strings and returns a ffi clib userdata https://github.com/fsfod/LuaJIT/commit/c8fbcb95a6bb4dbec6ea79746bc17d40fd5dc78d . The other option is to just pass an array of pointers to Lua and cast them to FFI function pointers.

**Comment by synxroform** [comment]
Wow, thank you !!!
