### ISSUE TITLE
OSX building

### ISSUE THREAD

**Issue by gummybear17** [LuaJIT/LuaJIT#764]
ld: warning: -seg1addr not 16384 byte aligned, rounding up
LINK      luajit
Undefined symbols for architecture x86_64:
  "__Unwind_DeleteException", referenced from:
      _lj_err_unwind_dwarf in libluajit.a(lj_err.o)
  "__Unwind_GetCFA", referenced from:
      _lj_err_unwind_dwarf in libluajit.a(lj_err.o)
  "__Unwind_RaiseException", referenced from:
      _lj_err_throw in libluajit.a(lj_err.o)
  "__Unwind_SetGR", referenced from:
      _lj_err_unwind_dwarf in libluajit.a(lj_err.o)
  "__Unwind_SetIP", referenced from:
      _lj_err_unwind_dwarf in libluajit.a(lj_err.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [luajit] Error 1
make: *** [src/luajit] Error 2

and im on macos

**Comment by Buristan** [comment]
You [must](https://luajit.org/install.html) set environment variable `MACOSX_DEPLOYMENT_TARGET` directly  to a value supported by your toolchain, when build LuaJIT on macos. For example:
```
MACOSX_DEPLOYMENT_TARGET=11.6 make
```
See also #484, #653.

**Comment by gummybear17** [comment]
but what file do i put the line of code?

**Comment by linan0827** [comment]
set it before invoke make. something like this:

MACOSX_DEPLOYMENT_TARGET=12.0 make

jonnycat ***@***.***> 于2021年11月10日周三 下午11:26写道：
