### ISSUE TITLE
string.buffer's put function appends an additional "0" when used in conjuction with gsub

### ISSUE THREAD

**Issue by estama** [LuaJIT/LuaJIT#769]
Bug reproduction code:

buffer = require('string.buffer')
a = buffer.new()
print( a:put(string.gsub('\"',"\\", "\\\\")) )
-- OUTPUT --
"0

**Comment by corsix** [comment]
`string.gsub` returns multiple values. If you only want the first return value, wrap the call to `string.gsub` in an extra pair of parentheses, as in:
```
print( a:put((string.gsub('"',"\", "\\"))) )
```

**Comment by estama** [comment]
Yes you are write. This is a problem in my understanding. Many many thanks for the correction.
