### ISSUE TITLE
Mac os Monterey M1 build error 

### ISSUE THREAD

**Issue by AlexandreCA** [LuaJIT/LuaJIT#771]
I retake this topic, https://github.com/LuaJIT/LuaJIT/issues/742 because I have the same problem, except that I am under Monterey.

Here is the error code:

alexandremate@AirdeAlexandre build % make
[ 3%] Built target detour
[ 6%] Built target spdlog
[ 9%] Built target common
[ 11%] Built target topaz_connect
[ 51%] Built target packets
[ 54%] Built target ai_controllers
[ 56%] Built target ai_helpers
[ 61%] Built target ai_states
[ 64%] Built target entities
[ 68%] Built target items
[ 72%] Built target lua_bindings
[ 79%] Built target utils
[ 79%] Built target ai
[ 80%] Linking CXX executable ../../../topaz_game
ld: warning: dylib (/usr/local/lib/libluajit-5.1.dylib) was built for newer macOS version (12.0.1) than being linked (12.0)
ld: warning: dylib (/usr/local/lib/libluajit-5.1.dylib) was built for newer macOS version (12.0.1) than being linked (12.0)
undef: _lua_seti
undef: _lua_compare
undef: _lua_len
undef: _lua_pcallk
undef: _lua_rotate
undef: _lua_geti
undef: _lua_absindex
undef: _lua_isinteger
undef: _lua_callk
undef: _lua_getglobal
undef: _lua_setglobal
Undefined symbols for architecture arm64:
"_lua_seti", referenced from:
sol::basic_table_core<false, sol::basic_reference >& sol::basic_table_core<false, sol::basic_reference >::traverse_set<int&, int&>(int&, int&) in lto.o
luautils::GetMagianTrial(sol::variadic_args) in lto.o
"_lua_compare", referenced from:
bool sol::operator==<false, false>(sol::basic_reference const&, sol::basic_reference const&) in lto.o
"_lua_len", referenced from:
CLuaBaseEntity::pathThrough(sol::basic_table_core<false, sol::basic_reference > const&, sol::basic_object<sol::basic_reference > const&) in lto.o
"_lua_pcallk", referenced from:
CCommandHandler::call(sol::state&, CCharEntity*, signed char const*) in lto.o
sol::protected_function_result sol::basic_protected_function<sol::stack_reference, true, sol::basic_reference >::invoke(sol::types<>, std::__1::integer_sequence, long, sol::detail::protected_handler<true, sol::basic_reference >&) const in lto.o
sol::protected_function_result sol::basic_protected_function<sol::stack_reference, true, sol::basic_reference >::invoke(sol::types<>, std::__1::integer_sequence, long, sol::detail::protected_handler<false, sol::basic_reference >&) const in lto.o
sol::protected_function_result sol::basic_protected_function<sol::basic_reference, false, sol::basic_reference >::invoke(sol::types<>, std::__1::integer_sequence, long, sol::detail::protected_handler<true, sol::basic_reference >&) const in lto.o
sol::protected_function_result sol::basic_protected_function<sol::basic_reference, false, sol::basic_reference >::invoke(sol::types<>, std::__1::integer_sequence, long, sol::detail::protected_handler<false, sol::basic_reference >&) const in lto.o
"_lua_rotate", referenced from:
sol::protected_function_result::~protected_function_result() in lto.o
decltype(auto) sol::basic_protected_function<sol::stack_reference, true, sol::basic_reference >::call<>() const in lto.o
call_onRecordTrigger(CCharEntity*, unsigned short, std::__1::vector<RoeDatagram, std::__1::allocator > const&) in lto.o
sol::basic_table_iterator<sol::basic_reference >::~basic_table_iterator() in lto.o
decltype(auto) sol::basic_protected_function<sol::basic_reference, false, sol::basic_reference >::call<CLuaBaseEntity, CLuaStatusEffect>(CLuaBaseEntity&&, CLuaStatusEffect&&) const in lto.o
decltype(auto) sol::basic_protected_function<sol::basic_reference, false, sol::basic_reference >::call(CLuaBaseEntity&&) const in lto.o
CBattleEntity::takeDamage(int, CBattleEntity*, ATTACK_TYPE, DAMAGE_TYPE) in lto.o
...
"_lua_geti", referenced from:
decltype(auto) sol::basic_table_core<true, sol::basic_reference >::traverse_get_deep_optional<true, false, (sol::detail::insert_mode)0, sol::optional, char const (&) [6], unsigned short&, char const (&) [5], char const*&>(int&, int, char const (&) [6], unsigned short&, char const (&) [5], char const*&) const in lto.o
CLuaBaseEntity::atPoint(sol::variadic_args) in lto.o
CLuaBaseEntity::pathThrough(sol::basic_table_core<false, sol::basic_reference > const&, sol::basic_object<sol::basic_reference > const&) in lto.o
CLuaBaseEntity::setPos(sol::variadic_args) in lto.o
CLuaBaseEntity::addItem(sol::variadic_args) in lto.o
CLuaBaseEntity::storeWithPorterMoogle(unsigned short, sol::basic_table_core<false, sol::basic_reference > const&, sol::basic_table_core<false, sol::basic_reference > const&) in lto.o
decltype(auto) sol::basic_table_core<false, sol::basic_reference >::get<sol::optional, int&>(int&) const in lto.o
...
"_lua_absindex", referenced from:
sol::protected_function_result::~protected_function_result() in lto.o
sol::state_view::do_file(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, sol::load_mode) in lto.o
sol::basic_protected_function<sol::stack_reference, true, sol::basic_reference >::basic_protected_function(lua_State*, int, sol::basic_reference) in lto.o
decltype(auto) sol::basic_protected_function<sol::stack_reference, true, sol::basic_reference >::call<>() const in lto.o
sol::stack::push_popper<false, sol::basic_table_core<true, sol::basic_reference >&, void>::push_popper(sol::basic_table_core<true, sol::basic_reference >&) in lto.o
int sol::stack::unqualified_pusher<sol::detail::as_value_tag, void>::push_fx<sol::stack::stack_detail::undefined_metatable&, CLuaBaseEntity>(lua_State*, sol::stack::stack_detail::undefined_metatable&, CLuaBaseEntity&&) in lto.o
call_onRecordTrigger(CCharEntity*, unsigned short, std::__1::vector<RoeDatagram, std::__1::allocator > const&) in lto.o
...
"_lua_isinteger", referenced from:
CCommandHandler::call(sol::state&, CCharEntity*, signed char const*) in lto.o
sol::stack::qualified_getter<sol::optional, void>::get(lua_State*, int, sol::stack::record&) in lto.o
decltype(stack_detail::unchecked_get(fp, fp0, fp1)) sol::stack::get(lua_State*, int, sol::stack::record&) in lto.o
decltype(stack_detail::unchecked_get(fp, fp0, fp1)) sol::stack::get(lua_State*, int, sol::stack::record&) in lto.o
decltype(stack_detail::unchecked_get(fp, fp0, fp1)) sol::stack::get(lua_State*, int, sol::stack::record&) in lto.o
decltype(stack_detail::unchecked_unqualified_get(fp, fp0, fp1)) sol::stack::unqualified_get(lua_State*, int, sol::stack::record&) in lto.o
decltype(stack_detail::unchecked_get(fp, fp0, fp1)) sol::stack::get(lua_State*, int, sol::stack::record&) in lto.o
...
"_lua_callk", referenced from:
void sol::detail::handle_protected_exception<true, sol::basic_reference >(lua_State*, sol::optional<std::exception const&>, char const*, sol::detail::protected_handler<true, sol::basic_reference >&) in lto.o
"_lua_getglobal", referenced from:
CCommandHandler::call(sol::state&, CCharEntity*, signed char const*) in lto.o
sol::basic_protected_function<sol::stack_reference, true, sol::basic_reference >::get_default_handler(lua_State*) in lto.o
void sol::detail::handle_protected_exception<true, sol::basic_reference >(lua_State*, sol::optional<std::exception const&>, char const*, sol::detail::protected_handler<true, sol::basic_reference >&) in lto.o
void sol::detail::handle_protected_exception<false, sol::basic_reference >(lua_State*, sol::optional<std::exception const&>, char const*, sol::detail::protected_handler<false, sol::basic_reference >&) in lto.o
sol::basic_protected_function<sol::basic_reference, false, sol::basic_reference >::get_default_handler(lua_State*) in lto.o
sol::detail::lua_cfunction_trampoline(lua_State*, int ()(lua_State)) in lto.o
call_onRecordTrigger(CCharEntity*, unsigned short, std::__1::vector<RoeDatagram, std::__1::allocator > const&) in lto.o
...
"_lua_setglobal", referenced from:
CCommandHandler::call(sol::state&, CCharEntity*, signed char const*) in lto.o
sol::basic_table_core<true, sol::basic_reference >& sol::basic_table_core<true, sol::basic_reference >::traverse_set<std::__1::tuple<char const (&) [16]>, sol::function_arguments<sol::function_sig<>, void ()(sol::basic_table_core<false, sol::basic_reference > const&)> >(std::__1::tuple<char const (&) [16]>&&, sol::function_arguments<sol::function_sig<>, void ()(sol::basic_table_core<false, sol::basic_reference > const&)>&&) in lto.o
sol::basic_table_core<true, sol::basic_reference >& sol::basic_table_core<true, sol::basic_reference >::traverse_set<std::__1::tuple<char const (&) [14]>, sol::function_arguments<sol::function_sig<>, void ()(sol::basic_table_core<false, sol::basic_reference > const&)> >(std::__1::tuple<char const (&) [14]>&&, sol::function_arguments<sol::function_sig<>, void ()(sol::basic_table_core<false, sol::basic_reference > const&)>&&) in lto.o
CLuaBaseEntity::Register() in lto.o
CLuaStatusEffect::Register() in lto.o
luautils::init() in lto.o
luautils::CacheLuaObjectFromFile(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator >, bool) in lto.o
...
**### ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [../topaz_game] Error 1
make[1]: *** [src/map/CMakeFiles/topaz_game.dir/all] Error 2
make: *** [all] Error 2**

**Comment by zach2good** [comment]
Header mismatch on our end, false alarm 🙏
