### ISSUE TITLE
Memory write may produce weird behavior

### ISSUE THREAD

**Issue by Rerumu** [LuaJIT/LuaJIT#775]
The JIT will sometimes produce odd behavior when doing writes to 64 bit pointers. To be specific, the code below should never print, but it will sometimes print out `huh?? 1 == 0`. If the JIT is disabled, the issue disappears.

This is the smallest form of the bug I could reproduce, but my actual test file is a monstrous 3MB file where it initially showed up. Sadly in reducing the test case it's also much harder to get the behavior to show up because it looks like the JIT must already be under some pressure to get a reliable result.
```Lua
local ffi = require('ffi')
local cast = ffi.cast

-- maybe related?
-- jit.opt.start("maxsnap=1000", "loopunroll=500", "maxmcode=2048")

local mem = ffi.new('uint8_t[?]', 0x20000)

local ptr_i32 = ffi.typeof('int32_t *')
local ptr_i64 = ffi.typeof('int64_t *')

function store_i64(memory, addr, value)
	cast(ptr_i64, memory + addr)[0] = value

	local sliced = cast(ptr_i32, memory + addr)[0]
	local expected = tonumber(bit.band(value, 0xFFFFFFFF))

	if sliced ~= expected then io.write('huh?? ', sliced, ' == ', expected, '\n') end
end

for i = 0, 0x20000 - 9 do store_i64(mem, i, 4294967296LL) end
```

**Comment by MikePall** [comment]
This is probably due to use of undefined behavior (casts between Lua numbers and FFI numbers outside of their domain) or breaking the strict aliasing rules (see FFI semantics).

But the example as given will always 'fail', because this:
```
local expected = tonumber(bit.band(value, 0xFFFFFFFF)) sliced = 1
```
... are two statements. The seond one unconditionally sets `sliced` to 1.

**Comment by Rerumu** [comment]
My bad, I added `sliced = 1` while testing that I had not broken something else. Without it, the code can still read `slice` as `1` if the JIT is under enough pressure (I presume).

**Comment by Rerumu** [comment]
```
The JIT compiler implements strict aliasing rules: accesses to different types do not alias, except for differences in signedness (this applies even to char pointers, unlike C99). Type punning through unions is explicitly detected and allowed.
```
It appears this might've been a strict aliasing issue. `cast(type, memory + offset)` may lead to aliasing issues that creep once in a blue moon. Wild.
