### ISSUE TITLE
Sunway architecture support

### ISSUE THREAD

**Issue by sinjoywong** [LuaJIT/LuaJIT#777]
lj_arch.h:69:2: error: #error "No support for this architecture (yet)"
 #error "No support for this architecture (yet)"

**Comment by sinjoywong** [comment]
I am try to compile LuaJIT in sw64 arch, but it is seems that has not been  supported. 
I try to build it with LUAJIT_ARCH_ARM64, but it not work properly，either:
==== Building LuaJIT 2.1.0-beta3 ====
make -C src
make[1]: In to “/data/csp/sher/LuaJIT/src”
ASM       lj_vm.o
buildvm_arm64.dasc: Assembler messages:
buildvm_arm64.dasc:266: Error：unknown opcode `bl'
buildvm_arm64.dasc:472: Error ：unknown opcode `bl'
...

What should I do? Thanks!

**Comment by MikePall** [comment]
The Sunway architecture is not supported and there are no plans to add it.
