### ISSUE TITLE
Is there a way to interrupt the execution of JIT code

### ISSUE THREAD

**Issue by libing0526** [LuaJIT/LuaJIT#779]
when I set a LUA_MASKLINE hook(or other hook)，if code is in JIT，the hook callback will be not called；if code is not in JIT，callback works fine；
I know，when code is in JIT，it is excuted with Assembly code，but sometimes I want interrupt lua Execution process, including jit code。
Someone knows how to do?

**Comment by MikePall** [comment]
Carefully read the comments at the end of `src/lj_record.c` and run `make XCFLAGS=-DLUAJIT_ENABLE_CHECKHOOK` to enable this (unsupported). Also, use `LUA_MASKCOUNT` -- never use `LUA_MASKLINE`, except for a debugger.

**Comment by libing0526** [comment]
thank you very much, Pall, it runs good，but I still have a problem:
"This is a compile-time option and disabled by default, since the
  ** hook checks may be quite expensive in tight loops."
if hook is not set，it is just a check（not call hook callback），why do you say “ hook checks may be quite expensive in tight loops”？
i made a test, this is code:
`local function test2()
	for i = 1, 1000000 do
		test1()
	end
end

local function test3()
	for i = 1, 1000000 do
		test2()
	end
end

test3()
`
DLUAJIT_ENABLE_CHECKHOOK switch is on or off，The time spent is basically the same。

**Comment by MikePall** [comment]
It does matter in loops that actually compute something. The execution bandwidth of the CPU has a limit and the hook check counts against that.
Whether that matters for your actual use case, you will need to find out.
