### ISSUE TITLE
can not find "trunc" function when cross-compiling (mips)

### ISSUE THREAD

**Issue by BalckCat** [LuaJIT/LuaJIT#78]
when I cross compile with shell code : make HOST_CC="gcc -m32" CROSS=mips-linux-gnu- ,
then failed and show error tip : lj_dispatch.c:43: error: 'trunc' undeclared here (not in a function).
my gcc version is 4.3.2,and I find "trunc" in tr1_impl/cmath.h,but there is undef tr1 Math(_GLIBCXX_USE_C99_MATH_TR1) by default.
Is there any way to fix the compile error whitout reinstall gcc?

**Comment by MikePall** [comment]
Try running the cross-compiler in C99 mode: `TARGET_CFLAGS=-std=c99`

**Comment by BalckCat** [comment]
I had tried as you said ,but there is other error.After some search ,I complie succeed with command : make HOST_CC="gcc -m32" CROSS=mips-linux-gnu- TARGET_CFLAGS="-D_GNU_SOURCE -std=c99 -fms-extensions",so it can work now,thanks a lot
