### ISSUE TITLE
ffi.C.open issue on M1

### ISSUE THREAD

**Issue by bungle** [LuaJIT/LuaJIT#780]
I have this example program (`test.lua`):

```lua
local ffi = require("ffi")
ffi.cdef("int open(const char *, int, int);")
ffi.cdef("int close(int);")
ffi.C.close(ffi.C.open("/tmp/test", 512, 416))
```

I tried different LuaJIT versions:
```shell
# LuaJIT Latest `2.1` branch code (including recent M1 patches):
rm -f /tmp/test; ./luajit test.lua; ls -l /tmp/test;
rm -f /tmp/test; ./luajit -j off test.lua; ls -l /tmp/test;
# LuaJIT 2.1.0-beta3:
rm -f /tmp/test; luajit test.lua; ls -l /tmp/test;
rm -f /tmp/test; luajit -j off test.lua; ls -l /tmp/test;
```

Results:
```shell
-r-xr----- 0 Dec 14 01:02 /tmp/test
-r-xr----- 0 Dec 14 01:02 /tmp/test 
-r-x------ 0 Dec 14 01:02 /tmp/test
-r-x------ 0 Dec 14 01:02 /tmp/test
```

I have seen different outputs too, but this is from the last run.

My `umask` is `022`. My OS is `macOS 12.1` and processor is `M1` (AArch64).

On `Intel` machines (macs and linux) the output is always:
```shell
-rw-r----- 0 Dec 14 00:12 /tmp/test
```

**Comment by vanc** [comment]
I could confirm the behavior on a Apple M1 Mac-mini, running macOS 11.6.0 (BigSur).

The following C code produced correct result.
```
#include <fcntl.h>
#include <unistd.h>

int main()
{
    close(open("/tmp/test2", 512, 416));
    return 0;
}
```

**Comment by MikePall** [comment]
You're using the wrong prototype for `open`. It's a vararg function and it **must** be declared as such for correct operation on all systems:
```Lua
ffi.cdef[[
int open(const char *file, int oflag, ...)
]]
```
The third argument is optional due to historic reasons.

Do not rely on manual pages for declarations -- only use the exact declarations from the system headers.

**Comment by bungle** [comment]
Thanks @MikePall,

here is the corrected code that works:
```
local ffi = require("ffi")
ffi.cdef("int open(const char *file, int oflag, ...)")
ffi.cdef("int close(int);")
local mode = ffi.new('int', 416)
ffi.C.close(ffi.C.open("/tmp/test", 512, mode))
```
