### ISSUE TITLE
Crash on lua_rawget

### ISSUE THREAD

**Issue by resolritter** [LuaJIT/LuaJIT#785]
First of all, sorry I don't have more context on this crash. When it happened some time ago, I left the backtrace - quite short as you'll see further down - in my notes, hoping that I would be able to revisit it someday. At this point I don't remember exactly what I was doing back then and so I don't have a clue for how to reproduce it.

The following has all I could salvage from the core dump on GDB:

```
Backtrace stopped: Cannot access memory at address 0x7f28b62a85a0
Thread 2 (LWP 1473764):
#0  0x0000560823970501 in lua_rawget (L=0x7f28b5231380, idx=-2) at lj_api.c:828
  t = <optimized out>
  __func__ = "lua_rawget"
Backtrace stopped: Cannot access memory at address 0x7f28b5a4d778
```

Given some explanations of how the crash could happen, I can try to relate them to what was being executed at the time.

Thank you for your time.

**Comment by MikePall** [comment]
The most likely cause for crashes in Lua/C API calls is mishandling of the Lua stack. The C API is very unforgiving in that regard. You should always try to repro this with a LuaJIT build with assertions enabled.

Given there's no stand-alone reproducible test case, I can only close this as invalid.
