### ISSUE TITLE
build for Android/aarch64 failed

### ISSUE THREAD

**Issue by leleliu008** [LuaJIT/LuaJIT#786]
I wanna cross-compile this project for Android/aarch64, error logs say `lj_arch.h:55:2: error: "No support for this architecture (yet)"`

does really not support aarch64? 

https://developer.android.com/ndk/guides/cpu-features

**Comment by MikePall** [comment]
Follow the instructions at https://luajit.org/download.html and use the v2.1 git branch. Also follow the build instructions from the checked out tree.

**Comment by leleliu008** [comment]
@MikePall it works indeed, thanks!
