### ISSUE TITLE
tonumber produces wrong results for large exponents

### ISSUE THREAD

**Issue by XmiliaH** [LuaJIT/LuaJIT#788]
Large exponents in numbers are cut of by https://github.com/LuaJIT/LuaJIT/blob/a91d0d9d3bba1a936669cfac3244509a0f2ac0e3/src/lj_strscan.c#L464 without handling the cut. This can result in wrong numbers as is the case in
```lua
print(tonumber("0." .. string.rep("0", 99999) .. "1e100000"))
print(tonumber("0." .. string.rep("0", 999999) .. "1e1000000"))
```
where the second number should be `1` but is calculated as `0`.

**Comment by MikePall** [comment]
Fixed. Thanks!
