### ISSUE TITLE
Split LEN opcode

### ISSUE THREAD

**Issue by SoniEx2** [LuaJIT/LuaJIT#79]
Instead of changing the behaviour of the LEN opcode when -DLUAJIT_ENABLE_LUA52COMPAT is used, add a separate LEN opcode that respects __len and change the behaviour of the parser/lexer/compiler.

This could become useful in the future. It'd also increase compatibility for programs after compilation. (e.g. running `-DLUAJIT_ENABLE_LUA52COMPAT`-compiled bytecode in non-`-DLUAJIT_ENABLE_LUA52COMPAT`-compiled VM)

**Comment by MikePall** [comment]
Not helpful.
