### ISSUE TITLE
Invalid DCE of buffer instructions

### ISSUE THREAD

**Issue by XmiliaH** [LuaJIT/LuaJIT#791]
The following code
```lua
local a, b = "", ""
local c

for i = 1, 1000 do
    c = a .. "a"
    a = "l" .. b
    b = "u"
end

print(c)
```
will generate the following loop IR code
```
0015 rdi      p64 BUFHDR 0010  APPEND
0016 rdi   >  p64 BUFPUT 0015  "a" 
0017 rax   >+ str BUFSTR 0016  0015
0018          p64 BUFHDR [0x7f6afd6cb4a8]  RESET
0019       >  p64 BUFPUT 0018  "lu"
0020 rbp    + int ADD    0012  +1  
....              SNAP   #3   [ ---- ---- "lu" "u"  0017 ]
0021       >  int LE     0020  +1000
```

The problem is that buffer instructions 18 & 19 are marked as side effect free and do not have registers assigned. Therefore, these instructions are assumed dead and are not emitted by the assembler which results in a buffer for the append instruction which is not reset.

Using `-O-dce` will result in the expected output.

**Comment by MikePall** [comment]
Fixed. Thanks!
