### ISSUE TITLE
Consistent assertion failures on x86_64 MacOS with -DLUA_USE_ASSERT

### ISSUE THREAD

**Issue by xiaocang** [LuaJIT/LuaJIT#793]
I've noted that on <del>Aarch64 Linux</del> MacOS 11.6, enabling -DLUA_USE_ASSERT to build the latest v2.1 branch (commit a91d0d9d) would lead to assertion failures for even the simplest Lua script. It is a recent regression.

I built LuaJIT like this:

```
make Q= CC=gcc CCDEBUG=-g -j$(nproc) XCFLAGS='-DLUA_USE_ASSERT'
```

and then run a hello world Lua one-liner:

```
$ ./src/luajit -e 'print "hello"'
LuaJIT ASSERT lj_err.c:484: lj_err_verify: broken build: external frame unwinding enabled, but missing -funwind-tables
Abort trap: 6
```

I'm on MacOS 11.6 x86_64.

Without the `-DLUA_USE_ASSERT` flag, it seems to work fine, at least according to the luajit test suite running results.

**Comment by corsix** [comment]
> I've noted that on Aarch64 Linux

> I'm on MacOS 11.6 x86_64

These statements seem in contradiction.

**Comment by xiaocang** [comment]
> These statements seem in contradiction.

@corsix Sorry, here's a typo, I've edited it.

**Comment by MikePall** [comment]
This is a build failure then. The compiler you use (where does `gcc` point at?) probably does not match with the `MACOSX_DEPLOYMENT_TARGET` setting.

**Comment by xiaocang** [comment]
Here's the compiler:

```
$ gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by MikePall** [comment]
Looks like Apple really likes to mess with unwind handling on every release. Assertion removed. Thanks!
