### ISSUE TITLE
buffer.decode() may produce ill-formed cdata resulting in invalid memory accesses

### ISSUE THREAD

**Issue by ImagicTheCat** [LuaJIT/LuaJIT#795]
(as of commit a91d0d9d3b)

To reproduce:
```lua
local buffer = require("string.buffer")
local data = buffer.decode(from_hex("112A00000000000000")) -- hex result of buffer.encode(42ULL)
print(data) -- print a "typeless" cdata
```

When the buffer decodes a cdata, without prior (or followed) loading of the FFI library or the use of a cdata literal, it results in a "typeless" cdata that will cause invalid memory accesses on garbage collection or calls to `tonumber()`, etc.

**Comment by MikePall** [comment]
Fixed. Thanks!

[Lazy-loading the FFI library doesn't work here, so the only solution is to throw an error. I've documented this, too.]
