### ISSUE TITLE
Assertion failure 'rec_check_slots: slot type mismatch' during `pairs` iteration

### ISSUE THREAD

**Issue by Marukyu** [LuaJIT/LuaJIT#796]
Iterating over tables containing values of different TREF-types via `pairs` and writing these values to a new table allocated within the loop body causes an assertion violation, leading to occasional crashes in JIT-compiled code.

The following snippet reproduces the issue as of commit 7306ba78d62b55a64f25231df1d5697345a5572e:

```lua
local jit = require "jit"
for i = 1, 1000 do
	local result
	for key, value in pairs {true, false} do
		result = result or {}
		result[key] = value
	end
	jit.flush(true, true)
end
```

The assertion failure message is:
`LuaJIT ASSERT lj_record.c:167: rec_check_slots: slot 12 type mismatch: stack type 1 vs IR type 2`

The above example was tested on Linux Mint (64-bit, x86). LuaJIT was compiled with GCC 7.5.0, and the only modification to the Makefile is `XCFLAGS+= -DLUA_USE_ASSERT`.

**Comment by MikePall** [comment]
Fixed. Thanks!

**Comment by Marukyu** [comment]
Thank you very much for the speedy fix! I've just tested the latest version and can confirm that the issue no longer occurs in our application.
