### ISSUE TITLE
DynASM: encoding issue with labels as offsets on x64

### ISSUE THREAD

**Issue by undingen** [LuaJIT/LuaJIT#801]
I'm one of the [Pyston](https://github.com/pyston/pyston) developers and I just tried upgrading DynASM to the latest revision from the about 1 year old ec6edc5c39c25e4eb3fca51b753f9995e97215da which we are currently using.

I run into an issue when encoding for AMD64:
```asm
| mov r9d, [rdi*2 + ->opcode_addr_begin]
```

We use it to resume a python function (`rdi * 2` is the index of the bytecode instruction to execute and `->opcode_addr_begin` marks the start of a table which points to the machine code address of specified bytecode instruction).

It now encodes into garbage (`->opcode_addr_begin = 0x400004ce`):
```asm
   0x0000000040000033:	44 8b 0c 7d ce 04 00 40	mov    0x400004ce(,%rdi,2),%r9d
=> 0x000000004000003b:	00 00	                add    %al,(%rax)
   0x000000004000003d:	00 00	                add    %al,(%rax)
```
It seems the problem is that it now always want to encode the global label as a 8 byte immediate instead of the 4 byte long required.

I guess using a label as an immediate is kind of unusual/(maybe even unsupported?) usage - it works for us because the JIT memory is always allocated in 32bit address space.

Is there a workaround / new syntax to get it working on newer DynASM?

Else we will have to use something like this:
```asm
    | lea r9, [->opcode_addr_begin]
    | mov r9d, [r9 + rdi*2]
```

BTW: Big thanks for DynASM! super useful tool to have - we got very good results using it.

**Comment by MikePall** [comment]
One could support this with two extra actions `IMM_LG32` and `IMM_PC32`. But this seems a bit excessive, given the limited use case. Closing as WONTFIX.

Maybe I should add an error for the x64 + table case in `wputdarg()`. But I haven't checked this catches all bad uses of it.

In case anyone doesn't want the 8-byte label behavior at all, then patch out the two checks for `sizeof(ptrdiff_t) == 8` in `dasm_x86.h`.
