### ISSUE TITLE
Continuation of trace assembling after panic in mcode_protfail

### ISSUE THREAD

**Issue by Buristan** [LuaJIT/LuaJIT#802]
If `mprotect()` is failed by some reason, `panic` is called in `mcode_protfail()`.
https://github.com/LuaJIT/LuaJIT/blob/4077f0c3d66ee9d74c705e605038271ceb39238e/src/lj_mcode.c#L171-L179
But after that there is no `exit(EXIT_FAILURE);` as expected, so trace is recorded with invalid protection on a region of memory.

I assume there are 2 options:
1) Add `exit(EXIT_FAILURE);` to stop execution at this moment, like a usual way after the panic is called.
2) Just throw an error in this place. So all traces to record will be blacklisted as far it is impossible to protect memory for them, but the traces recorded already will run, and user application continues work.

**Comment by MikePall** [comment]
Fixed. Thanks!
