### ISSUE TITLE
PGP sign releases

### ISSUE THREAD

**Issue by hendursaga** [LuaJIT/LuaJIT#807]
I know on the download page there's a list of SHA256 hashes, but it would be great if they or the binaries were signed with PGP or something similar.

**Comment by daurnimator** [comment]
LuaJIT no longer does releases; see https://github.com/LuaJIT/LuaJIT/issues/665#issuecomment-784452583

**Comment by GitSparTV** [comment]
If luajit doesn't do releases, then perhaps luajit.org should mention that?

**Comment by MikePall** [comment]
It does on the download page.
