### ISSUE TITLE
Ephemeron tables

### ISSUE THREAD

**Issue by SoniEx2** [LuaJIT/LuaJIT#81]
Can we get ephemeron tables? They make weak tables a lot more useful. Shouldn't break most programs. (except maybe programs that rely on the 5.1 GC, which would break anyway with the addition of the new GC...)

See also:

- Lua 5.2 weak tables: http://www.lua.org/manual/5.2/manual.html#2.5.2
- Lua 5.1 weak tables: http://www.lua.org/manual/5.1/manual.html#2.10.2

It's probably legal to add ephemeron tables.

This would be useful for emulating __gc on tables.

**Comment by MikePall** [comment]
Part of #38.
