### ISSUE TITLE
`lua_rawget` / `lua_rawset` is not catched by `lua_pcall`

### ISSUE THREAD

**Issue by hyee** [LuaJIT/LuaJIT#810]
With below function
```C
static void test(lua_State *L) {
    lua_pushnil(L); //simulate an exception where a table is expected here
    lua_pushstring(L,"abcd");
    lua_rawget(L,-2);
}
```
If call this function with `lua_pcall`, the program directly crashes. And if change `lua_rawget` as `lua_gettable`, the program correctly catches the error `attempt to index a nil value`. The same issue happens on `lua_rawset`.

My OS is Win10 and LuaJIT is up to date, is this behaviour expected? Thanks.

**Comment by MikePall** [comment]
First, the behavior is the same with Lua, so the question does not belong here.

The Lua/C API is a low-level API. It assumes certain arguments on the stack to be of the correct type. You can enable API checks in the Makefile to catch (some) of this API misuse in your programs.

**Comment by hyee** [comment]
Noted with thanks, I didn't realize `-DLUA_USE_APICHECK` can be used for debug.
