### ISSUE TITLE
Too strict limit for long string delimiters

### ISSUE THREAD

**Issue by Buristan** [LuaJIT/LuaJIT#812]
This issue follows [this commit](https://github.com/LuaJIT/LuaJIT/commit/16e5605e).

Assume we have the following Lua code in a file named `/tmp/t.lua`:

```lua
local evals = "return ["

-- Valid but too long string (see lj_lex.c)
local ls = string.rep("=", 0x30000000)
evals = evals..ls.."["
evals = evals.."]"..ls.."]"
local f, e = loadstring(evals)
if not f then
  print(e)
else
  print(f()=="")
end
```

For Lua and LuaJIT before the aforementioned commit the long string is parsed as expected:
```sh
lua  /tmp/t.lua &> /tmp/t.log; head -c 120 /tmp/t.log; rm /tmp/t.log
true
```

But after the patch LuaJIT raises the following error:
```sh
src/luajit  /tmp/t.lua &> /tmp/t.log; head -c 120 /tmp/t.log; rm /tmp/t.log
[string "return [=====================================..."]:1: invalid long string delimiter near '[====================
```

I suggest a patch like the following:
```diff
diff --git a/src/lj_lex.c b/src/lj_lex.c
index 463a87ce..c7950886 100644
--- a/src/lj_lex.c
+++ b/src/lj_lex.c
@@ -142,7 +142,7 @@ static int lex_skipeq(LexState *ls)
   int count = 0;
   LexChar s = ls->c;
   lj_assertLS(s == '[' || s == ']', "bad usage");
-  while (lex_savenext(ls) == '=' && count < 0x20000000)
+  while (lex_savenext(ls) == '=' && count < INT_MAX)
     count++;
   return (ls->c == s) ? count : (-count) - 1;
 }
```

Also, `LJ_MAX_STR` may be used here, but for really long delimiters user will see an error like `not enough memory` due to additional cost of error message body.

**Comment by MikePall** [comment]
Your change will cause an overflow later on.

Anyway, I've used a conservative, yet very high limit for the delimiter length. I could have used (say) 100 and nothing would break in practice. Annoying the parser with a long string delimiter of a gigabyte is a pointless exercise.
