### ISSUE TITLE
Incorrect getn result

### ISSUE THREAD

**Issue by KionX** [LuaJIT/LuaJIT#813]
```
a={}
a[2]=true
print(table.getn(a))
```
=2 instead of 0
```
a={}
a[2]=true
a[3]=true
print(table.getn(a))
```
=3 instead of 0

**Comment by GitSparTV** [comment]
The behavior of length operator (which is used inside table.getn) is undefined if the table is not sequential.

**Comment by KionX** [comment]
The length of a table t is defined to be any integer index n such that t[n] is not nil and t[n+1] is nil; moreover, **if t[1] is nil, n can be zero**.

Lua 5.1 implements this as =0. So it's quite documented. LuaJIT selectively implements compatibility.

**Comment by GitSparTV** [comment]
Confused with the pairs function

**Comment by XmiliaH** [comment]
> **if t[1] is nil, n can be zero**.

It can be zero but does not have to.
```
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
> =table.getn({nil, 1})
2
```
So Lua 5.1 does not implement this as =0.

**Comment by KionX** [comment]
It's convincing.
