### ISSUE TITLE
pow() inaccuracy

### ISSUE THREAD

**Issue by vanc** [LuaJIT/LuaJIT#817]
Before revision 9512d5c1, the following code produces correct output.

```
print(string.format('%.99e', 2^-1074))
-- should output 4.940656458412465441765687928682213723650598026143247644255856825006755072702087518652998363616359924e-324
```

With the revision, the output became all zeros.

```
0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e+00
```

PUC Lua 5.1 gives correct output.

**Comment by vanc** [comment]
Tested on both Linux x86_64 and macOS with Apple M1, got the same result.

**Comment by vanc** [comment]
Turn out that after revision 9512d5c, LuaJIT can only hold values between 2^-1023 to 2^1023.

**Comment by MikePall** [comment]
This is not about number formatting (BTW: %a is the format code to use for debugging). The issue is with the power operator evaluation.
Already reported under: https://github.com/LuaJIT/LuaJIT-test-cleanup/issues/19 https://github.com/LuaJIT/LuaJIT-test-cleanup/issues/20
Fixed. Thanks!
