### ISSUE TITLE
CMake Support

### ISSUE THREAD

**Issue by dangyajun** [LuaJIT/LuaJIT#818]
Is there any CMakeLists.txt to compile luajit on plllatform(including windows, linux, ios, android)

**Comment by neomantra** [comment]
I use Neovim's CMake module, but have only tried it on OSX and Linux:

https://github.com/neovim/neovim/blob/master/cmake/FindLuaJit.cmake

```
include( ./FindLuaJit.cmake )
include_directories( ${LUAJIT_INCLUDE_DIRS} )
target_link_libraries( myapp ${LUAJIT_LIBRARIES} )
```

**Comment by neomantra** [comment]
@dangyajun Sorry -- I misread that as *compile using* LuaJIT from Cmake, not *building* LuaJIT itself.    

The neovim link above is only for including an already built LuaJIT into a project.
