### ISSUE TITLE
random lua errors with jit enabled (where jit.off() fixes it)

### ISSUE THREAD

**Issue by CapsAdmin** [LuaJIT/LuaJIT#82]
in META:TransformVector (see code below) sometimes the members (m00, m20, etc) might be nil. This shouldn't be possible because self in this case is a float[16]

attempt to perform arithmetic on field 'm13' (a nil value)
attempt to perform arithmetic on field 'm03' (a nil value)

sometimes surface.ScreenToWorld seems to return nil because self.MousePosition.x = x errors with unable to cast nil to float. Sometimes further down that code I get errors about comparing booleans with numbers.

This does not happen if I call jit.off() jit.flush() and seems to not happen again if i call jit.on() and jit.flush() again.

This is the code involved from top down:

```
-- https://github.com/CapsAdmin/goluwa/blob/master/src/lua/libraries/graphics/gui/base_panel.lua#L1364-L1367
local x, y = surface.ScreenToWorld(gui.mouse_pos.x, gui.mouse_pos.y)

self.MousePosition.x = x
self.MousePosition.y = y
```

```
-- https://github.com/CapsAdmin/goluwa/blob/master/src/lua/libraries/graphics/surface/surface.lua#L128-L130
function surface.ScreenToWorld(x, y)
	return render.camera_2d:ScreenToWorld(x, y)
end
```

```
-- https://github.com/CapsAdmin/goluwa/blob/master/src/lua/libraries/graphics/render/camera.lua#L156-L177
function META:ScreenToWorld(x, y)
	local m = (self:GetMatrices().view * self:GetMatrices().world):GetInverse()

	if self:Get3D() then 
		x = ((x / self.Viewport.w) - 0.5) * 2
		y = ((y / self.Viewport.h) - 0.5) * 2

		local cursor_x, cursor_y, cursor_z = m:TransformVector(self:GetMatrices().projection_inverse:TransformVector(x, -y, 1))
		local camera_x, camera_y, camera_z = m:TransformVector(0, 0, 0)

		--local intersect = camera + ( camera.z / ( camera.z - cursor.z ) ) * ( cursor - camera )

		local z = camera_z / ( camera_z - cursor_z )
		local intersect_x = camera_x + z * ( cursor_x - camera_x )
		local intersect_y = camera_y + z * ( cursor_y - camera_y )

		return intersect_x, intersect_y
	else
		local x, y = m:TransformVector(x, y, 1)
		return x, y
	end
end
```

```
-- https://github.com/CapsAdmin/goluwa/blob/master/src/lua/libraries/structs/matrix44.lua#L414-L421
function META:TransformVector(x, y, z)
	local div = x * self.m03 + y * self.m13 + z * self.m23 + self.m33

	return
		(x * self.m00 + y * self.m10 + z * self.m20 + self.m30) / div,
		(x * self.m01 + y * self.m11 + z * self.m21 + self.m31) / div,
		(x * self.m02 + y * self.m12 + z * self.m22 + self.m32) / div
end
```

So there's obviously a problem here and this is probably not enough information. What should I do?

**Comment by mraleph** [comment]
First of all - which version of LuaJIT are you running?

Do you have a runnable reproduction (even if it reproduces the problem infrequently)? If you do - please attach instructions for hot to run it so that we could debug this locally. 

Otherwise to provide more information you can attach output of `-jdump=+sXT`. It might contain enough information to figure this out.

**Comment by CapsAdmin** [comment]
Right sorry, I'm latest using 2.1 on linux. This also happens on windows IIRC.

One way to reproduce is to download https://github.com/CapsAdmin/goluwa as zip and run "sh launch_client.sh". (this will download and execute luajit binaries that I've hosted here on github) Once the menu is loaded just spam click the menu and it should happen randomly.

I'll see if I can attach a log because you might run into other unrelated issues downloading this to reproduce the error.

**Comment by CapsAdmin** [comment]
https://dl.dropboxusercontent.com/u/244444/jdump.txt.xz

**Comment by mraleph** [comment]
When I launch it - I see a blue screen with falling snow and a menu on top - I just tried opening collapsing top level menus - that did not reproduce it. Any other ideas?

**Comment by CapsAdmin** [comment]
try to type "open resource_browser" in terminal, move and resize the window that pops up

**Comment by mraleph** [comment]
This doesn't execute. It says "failed to execute command open: no such file"

**Comment by CapsAdmin** [comment]
There might be some issues with the text input that I didn't bother to fix yet. Alternatively you can go to goluwa/src/lua/tests/resource_browser.lua and drag drop this file onto the window.

Did you look at the dump file?

**Comment by mraleph** [comment]
I somehow had a space in the end of the "open resource_browser". Dragging it around reproed the issue.

**Comment by mraleph** [comment]
Ok, found it. Sorry, for the delay: I was initially looking for the bug  the wrong place :)

Bug is in the replay of the sunk stores: `snap_sunk_store2` function uses the wrong IR to determine whether something is a sunk store - and as a result if fast path check fails you'll fail the slow path check too and will *not* replay the store leaving garbage inside the object. For cdata you might end up with things inside the object that when loaded back will look like tagged values to LuaJIT instead of numbers, hence these strange `nil`s returned when loading floats.

I have a reduction and a fix, I will make a patch.

**Comment by mraleph** [comment]
@CapsAdmin try building LuaJIT from https://github.com/mraleph/LuaJIT/tree/fix82 and see if you problem is fixed.

**Comment by CapsAdmin** [comment]
Yeah the fix works. Thanks! I'm really glad you took the time to look into this given how vague the error was and how big the "test case" was.

**Comment by MikePall** [comment]
Merged.
