### ISSUE TITLE
LuaJIT failed to build with MSVC on windows ARM64

### ISSUE THREAD

**Issue by YangYang129** [LuaJIT/LuaJIT#820]
LuaJIT failed to build with "This version of F:\LuaJIT\src\minilua.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher." with MSVC on windows. It can reproduces on version https://github.com/LuaJIT/LuaJIT/commit/c4fe76d50cda24f3529604448f80ff14754599dd. Could you please help look at this issue? Thank you very much
**Environment**
Compiler version: VS2019 (16.11.9)
Operating system: Windows server 2019
**Steps to reproduce:**
1. open VS2019 x64 tools command
2. git clone https://github.com/LuaJIT/LuaJIT F:\LuaJIT
3. cd F:\LuaJIT\src
4. "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=arm64
5. Replace "x64" to "arm64" in msvcbuild.bat fold
6. msvcbuild.bat

Error log:
![image](https://user-images.githubusercontent.com/86757616/158566038-64170209-b62e-4083-b033-edb9fbb42864.png)
This version of F:\LuaJIT\src\minilua.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

**Comment by MikePall** [comment]
Dup of #593
