### ISSUE TITLE
Wrong require return

### ISSUE THREAD

**Issue by XmiliaH** [LuaJIT/LuaJIT#823]
Since `KEY_SENTINEL` is a number Lua chunks returning this number will confuse the require function which will return `true` instead.

*a.lua*
```lua
return -5.6817549271743e-322
```
*test.lua*
```lua
print(require("a"))
```
will print `true` instead of `-5.6817549271743e-322`.

**Comment by MikePall** [comment]
I'm not worried about this. This is a classic case of "if it hurts, don't do this". The previously used sentinel was a lightuserdata, which could be faked with some effort, too.
