### ISSUE TITLE
JIT produces invalid code on x64

### ISSUE THREAD

**Issue by savilli** [LuaJIT/LuaJIT#829]
We had rare crashes under unknown circumstances. I examined one of the crashes and found out that x64 assembly produced by LuaJIT is invalid.

```asm
0x7fffee9769d0: call   0x7ffff7d45c6f <lj_vm_next> ; returns TValue * in eax
0x7fffee9769d5: xchg   edx,eax ; erases higher 32 bits
0x7fffee9769d6: mov    rdi,QWORD PTR [rsp+0x28]
0x7fffee9769db: lea    rsi,[r14+0x2578]
0x7fffee9769e2: mov    r11,QWORD PTR [rdx+0x8] ; crash
0x7fffee9769e6: ror    r11,0x2f
0x7fffee9769ea: cmp    r11w,0xfffb
0x7fffee9769ef: jne    0x7ffff7fb4050
0x7fffee9769f5: shr    r11,0x11
```

After some debugging I'm sure that xchg instruction was inserted from here https://github.com/LuaJIT/LuaJIT/blob/96d6d5032098ea9f0002165394a8774dcaa0c0ce/src/lj_asm.c#L850
I don't know how to force JIT to use swap after next(), so I don't have a good testcase.

**Comment by MikePall** [comment]
Fixed. Thanks!
