### ISSUE TITLE
Assertion about IRCONV_TRUNC

### ISSUE THREAD

**Issue by ssdr** [LuaJIT/LuaJIT#833]
The bug was introduced in this commit in 2016, which may bump copyright date only, but also remove IRCONV_TRUNC macro:

https://github.com/LuaJIT/LuaJIT/commit/db1b399af134e715b8ba9a0e4ad9cbafbe06ecb1#diff-4bb81b58a6904dde4e2232d33c9a6aa9211e45ff75fa56a3d2040938c849b6e7

![image](https://user-images.githubusercontent.com/270285/163682776-dcf65c93-95b1-4d63-9786-6bd66cc1034f.png)

This bug may cause process abortion, and emit this error:
`li_opt_fold.c:685: fold_kfold_conv_knum_i64 num: Assertion '((&J->fold.ins)->0p2 & 0x0400)' failed.`

**Comment by MikePall** [comment]
It's not the code that's wrong -- it's the assertion. Fixed. Thanks!
