### ISSUE TITLE
Original git repo is down

### ISSUE THREAD

**Issue by 999pingGG** [LuaJIT/LuaJIT#835]
[https://luajit.org/git/luajit.git](url) returns error 403 since a few days ago. I thought it was temporal but to this day still no luck.

**Comment by MikePall** [comment]
Nope. A git clone works perfectly fine.

The [download page](https://luajit.org/download.html) clearly states this is the intended behavior for a browser:
> Note: this is not a browsable resource, the repository is only accessible with a git client.

**Comment by 999pingGG** [comment]
Sorry, I swear my git client was erroring today and the last week, too; but now it is working. I was trying to open it with the browser just to check if I get anything but now I think that's not how it works. Then I think the problem is with my Internet connection.
