### ISSUE TITLE
unexpect band result for the uint64

### ISSUE THREAD

**Issue by zhuizhuhaomeng** [LuaJIT/LuaJIT#837]
```
local bit = require("bit")
local band = bit.band

print(tostring(band(1ull, -1)))
```
the result is expected to be "1ULL", but got "0ULL".

**Comment by zhuizhuhaomeng** [comment]
need add -DLUAJIT_NUMMODE=2 option

**Comment by vanc** [comment]
If you change "-1" to "-1ull", you would get correct result even without the option.
```
LuaJIT 2.1.0-beta3 -- Copyright (C) 2005-2022 Mike Pall. https://luajit.org/
JIT: ON SSE3 SSE4.1 BMI2 fold cse dce fwd dse narrow loop abc sink fuse
> print(bit.band(1ull, -1))
0ULL
> print(bit.band(1ull, -1ull))
1ULL
>
```

**Comment by MikePall** [comment]
Converting a negative Lua number (which is a floating-point double) to an unsigned cdata type is (currently) undefined behavior. This may change in the future. Related: #415
