### ISSUE TITLE
Segfault occurs when using non-ascii inputs

### ISSUE THREAD

**Issue by YvesCjl** [LuaJIT/LuaJIT#847]
To reproduce:
`./luajit - < 1.lua`
[minimal.zip](https://github.com/LuaJIT/LuaJIT/files/8796127/minimal.zip)

**Comment by MikePall** [comment]
Bytecode input is [unsafe](https://luajit.org/faq.html#sandbox). Please do not submit fuzzer-generated input of this kind.
