### ISSUE TITLE
Incorrect format string passed to os.date crashes LuaJIT on Windows

### ISSUE THREAD

**Issue by igor725** [LuaJIT/LuaJIT#851]
Affected versions: <= 2.1.0-beta3
LuaJIT crashes on `strftime` call
Minimal steps to reproduce:
1.Build LuaJIT on Windows/x64 using **MSVC Compiler** v19.31.31107
2.Run `.\luajit.exe -e "os.date'%0'"`
3.LuaJIT crashes

**Comment by MikuAuahDark** [comment]
I don't think there's LuaJIT can do about this. IIRC the behavior of `strftime` when encountering unknown format string is platform-dependent.

**Comment by igor725** [comment]
> I don't think there's LuaJIT can do about this. IIRC the behavior of `strftime` when encountering unknown format string is platform-dependent (and specifically MSVC, it will just crash).

Yes, but this behavior can lead to serious problems if the function somehow receives user input as an argument. This issue can be fixed in the same way [as it was done in Lua 5.2](https://www.lua.org/source/5.2/loslib.c.html#checkoption).

**Comment by vanc** [comment]
I cross compiled LuaJIT HEAD with MinGW and ran on Windows 11 Pro/x64, I didn't see any crashes. 

```
E:\>luajit -e "print(jit.version)"
LuaJIT 2.1.0-beta3

E:\>luajit -e "os.date'%0'"

E:\>luajit -e "print(os.date'%c')"
06/11/22 15:18:51
```

**Comment by igor725** [comment]
> I cross compiled LuaJIT HEAD with MinGW and ran on Windows 11 Pro/x64, I didn't see any crashes.
> 
> ```
> E:\>luajit -e "print(jit.version)"
> LuaJIT 2.1.0-beta3
> 
> E:\>luajit -e "os.date'%0'"
> 
> E:\>luajit -e "print(os.date'%c')"
> 06/11/22 15:18:51
> ```

Because MinGW uses its own `strftime` implementation, not from VCRuntime library.

**Comment by MikePall** [comment]
Complain to Microsoft, not me.
Also, untrusted input should **never** be used for format strings.

**Comment by igor725** [comment]
well, fair enough
