### ISSUE TITLE
FFI typedef of struct with __attribute__((aligned(n))) yields "invalid C type" upon ffi.metatype()

### ISSUE THREAD

**Issue by folays** [LuaJIT/LuaJIT#861]
Hi,

LuaJIT seems to incorrectly figure out something when using in the SAME declaration, both a typedef and a __attribute__ ((aligned(n))) spec.

**In C :**
```
struct __attribute__((aligned(32))) w_t {
    char __opaque[8];
};
typedef struct w_t w_t;

typedef struct __attribute__((aligned(32))) x_t {
    char __opaque[8];
} x_t;

typedef __attribute__((aligned(32))) struct y_t {
    char __opaque[8];
} y_t;

typedef struct z_t {
    char __opaque[8];
} __attribute__((aligned(32))) z_t;

int main() {
	printf("W_T : %ld %ld\n", __alignof__(struct w_t), __alignof__(w_t));
	printf("X_T : %ld %ld\n", __alignof__(struct x_t), __alignof__(x_t));
	printf("Y_T : %ld %ld\n", __alignof__(struct y_t), __alignof__(y_t));
	printf("Z_T : %ld %ld\n", __alignof__(struct z_t), __alignof__(z_t));
}
```
yields :
```
W_T : 32 32
X_T : 32 32
Y_T : 1 32    // only the typedef has specific alignment, not the "base" type
Z_T : 32 32
```
Which IMHO seems normal / expected to me, from what I understood of things involved.
Maybe it's the C compiler used, but it seems that in C, a typedef is more than "just an alias" ;
I seem to observe that typedefs can be "a little different", because the typedef can have its "own aligned attribute".

Also I think that are 100% equal in ALL aspects those cases : struct w_t / w_t / struct x_t / x_t / struct z_t / z_t, **BUT** I'm not even sure. (with w_t being standard, x_t being preferred style for "typedef at the same time than aligned", and z_t being alternative-not-portable style for the same effects than x_t)

It seems legit, since I guess this below can also have its utility :
```
typedef int more_aligned_int __attribute__ ((aligned (8)));
```

WHEREAS, in LuaJIT 2.1.0-beta3 @ current HEAD e3bae12f :
```
-- ####### BELOW CASE 1 : some "int" typedef to a more stricly aligned typedef.
ffi.cdef[[
typedef int more_aligned_int_t __attribute__ ((aligned (8)));
]]
print(ffi.typeof("more_aligned_int_t"))              -- yields ctype<int>
print(ffi.alignof(ffi.typeof("int")))                -- yields 4
print(ffi.alignof(ffi.typeof("more_aligned_int_t"))) -- yields 8


-- ####### BELOW CASE 2 : a struct with a specific alignment, and the typedef is declared after
ffi.cdef[[
struct __attribute__((aligned(8))) a_t {
    char __opaque[64];
};
typedef struct a_t a_t;
]];
--ffi.metatype("struct a_t", {})             -- WORKS
--ffi.metatype(ffi.typeof("struct a_t"), {}) -- WORKS
ffi.metatype("a_t", {})                      -- WORKS


-- ####### BELOW CASE 3 : some attempt of C-like at the same time, declare both the "base" type and the typedef
ffi.cdef[[
typedef struct __attribute__((aligned(8))) b_t {
    char __opaque[64];
} b_t;
]]
--ffi.metatype("struct b_t", {})             -- WORKS
--ffi.metatype(ffi.typeof("struct b_t"), {}) -- WORKS
--ffi.metatype(ffi.typeof("b_t"), {})        -- DO NOT WORK
--ffi.metatype("b_t", {})                    -- DO NOT WORK
local b_t = ffi.typeof("b_t")                -- WORKS
ffi.metatype(b_t, {})                        -- DO NOT WORK : bad argument #1 to 'metatype' (invalid C type)
local b = b_t()                              -- WORKS (so... its not really an "invalid C type" after all...?)
```

In nearly all aspect, it seems that LuaJIT consider the "base" type and the "typedef'ed" one the sames.
It is probably false though, but there is not really any statement on this in the LuaJIT docs and Wiki.

LuaJIT nearly seems to coalesce all use of a `cdecl` typedef everywhere, as if we directly used the `cdecl` of a "base" type,
(because when we `print(ffi.typeof("a typedefed type"))`, this print the "base" type, not specifying the typedef'ed name)
It feels like if LuaJIT would convert every `cdecl` we pass it, to the `ctype` of the "base" type.

In this regards, it would differs from C.

On another hand, I think that's not really the case, since as shown above, `ffi.alignof()` outputs differentiate on whereas it is done on a `int` "base" type, or on it's typedef'ed `more_aligned_int_t`.

But it seems that there is maybe a "parser" bug in LuaJIT regarding "typedef'ing struct and __attribute__((aligned(n))" at the same time.

I would have expected the CASE 3 to works.
I understand that `ffi.metatype()` does **NOT** accept all `ctype`s : "_Only struct/union types_" as per the doc.
But `ffi.metatype()` works on a typedef of a struct.
So, that's not clear if it's allowed or not to `ffi.metatype()` on a "typedef with specific alignment to the typedef **only**".
I mean, the CASE 3 should be the same that the above C-case of struct x_t, and NOT struct y_t :

- (a) I seem in CASE 3 to have attempted to "align" the base type (and so the typedef'ed type would inherit this alignment) (like in x_t)
- (b) I seem in CASE 3 to **NOT** have attempted to "align" _**only**_ the typedef'ed type (like y_t would have done)

I guess that (a) is allowed, and the documentation does not explicitly tell if (b) is allowed or not.

So, in CASE 3, (where I defined AND typedef at the same time), if I'm right, the "alignment" is NOT specified on the **typedef'ed** type, but is really defined on the "base" type.

So CASE 3 is more of a situation (a), and I expected `ffi.metatype()` to allow it.

Do you have any insight of what happens here, or maybe does parser have a bug ?

1. Why LuaJIT complains that "invalid C type" on `ffi.metatype(t_t, {})`
2. If we can in LuaJIT "at the same time" : both "define a struct with specific aligment" AND "typedef the whole of it (inherit aligment in the typedef)"

Thanks

For amusement, my use case is this one:

1) I have some Go code, which has a .go file with some C-code helper for what's LuaJIT does not support : preprocessing headers.
```
/*
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <pthread.h>

uint32_t pthread_mutex_size() {
	return sizeof(pthread_mutex_t);
}

uint32_t pthread_mutex_align() {
    return __alignof__(pthread_mutex_t);
}
*/
import "C"
```

Which somehow leverage what's LuaJIT does not handle : preprocessing header files.
(I need sizeof() of "pthread_mutex_t", and the alignment is a bonus for sake of portability on != x64 platforms...)

2) I have some LuaJIT code, "providing" some mutex ops (like a library)

```
ffi.cdef[[
    uint32_t pthread_mutex_size();
    uint32_t pthread_mutex_align();
]]

local mutexSize = ffi.C.pthread_mutex_size() -- LuaJIT is incapable of preprocessing .h sizeof(), so get it from some C-compiled code.
local mutexAlign = ffi.C.pthread_mutex_align() -- same as above, for __alignof__()

-- Here below I defined in LuaJIT the "pthread_mutex_t" opaque type, which is "sized" and "aligned" with info recovered from C helpers above
ffi.cdef([[
typedef struct __attribute__((aligned($))) pthread_mutex_t   {
    char __opaque[$];
} pthread_mutex_t;
//typedef struct pthread_mutex_t pthread_mutex_t;
]], mutexAlign, mutexSize)

local mt = {
    __new = function(ctype)
        local mtx = ffi.new(ctype)
        ffi.C.pthread_mutex_init(mtx, nil)
        return mtx
    end,
    __index = {
        lock = function(mtx)
            ffi.C.pthread_mutex_lock(mtx)
        end,
        unlock = function(mtx)
            ffi.C.pthread_mutex_unlock(mtx)
        end,
    }
}
ffi.metatype("pthread_mutex_t", mt) <<< HERE IT DOES NOT WORK
```
(As said above, it works OKAY if first declare the "base" type with specific alignment, and **only** after typedef it)

3) And then use it like this (in some user-code example)
```
ffi.cdef[[
struct myStruct {
    pthread_mutex_t mtx; // aligned to 0x0 of struct, so malloc() will have a correct alignment even without __attribute__ ((aligned(n)) of pthread_mutex_t...
    int mydata1;
    int mydata2; // ... or whatever datas
    char mydata3; // for the sake of pretending that the next field could be NOT aligned to 4

    pthread_mutex_t mtx2; // possibly miss-aligned if my `ffi.cdef` of pthread_mutex_t did not have __attributed__ ((aligned(n))) spec
    int mydata4; // pretend that it is protected by mtx2 rather than mtx...
};
]])

local myData = ffi.C.malloc(ffi.sizeof("struct myStruct"))
ffi.C.pthread_mutex_init(myData.mtx, nil)
ffi.C.pthread_mutex_init(myData.mtx2, nil)

myData.mtx2:lock()
[...] do some stuff [...]
myData.mtx2:unlock()
```
For what's it's worth, I DON'T use ffi.new("myStruct") and rather I prefer to ffi.C.malloc() it, because I want it "un-managed" (outside of LuaJIT gc scope), so I will malloc() and initialize **ONLY** one time, and then share this struct between multiple per-cpu-core LuaJIT threads. I'm doing some weird stuff.

And lastly, another thing :
```
print(ffi.alignof("pthread_mutex_t"))   -- yields the expect result (the __atribute__((aligned(n)))
print(ffi.alignof("pthread_mutex_t &")) -- yields 8 or whatever
```
I don't know if it is intended or have been considered, that when we get a ref to type, we cannot get its alignment, so if we wanted, we are not able to allocate+copy an useful copy, since we cannot guarantee correctness of the copy alignment.
(Agreed, there is no real use case for "allocating a copy of a mutex", but it stands for non-mutex-standard-struct stuff)

A possible scenario :

- an user ffi.C.malloc() some buffer,
- it ffi.cast("struct anotherStruct &") and that's a REFERENCE because it cannot be cast to ffi.cast("struct anotherStruct") which would yield `bad argument #1 to 'cast' (invalid C type)`,
- pass it around by reference since its a reference,
- one of the callee function want to DUPLICATE its content for whatever reason,
- the callee does another ffi.C.malloc(), by using ffi.sizeof(cdata) or ffi.sizeof(ffi.typeof(cdata))
- the callee is unable to figure out the needed alignment, ffi.alignof() return 8 on a reference, instead of whatever alignment of the original ctype (without reference)
- (anyway ffi.C.malloc() does not support alignment so that's a dumb point in 99% of cases ?)
- after allocation, the callee copy the original content for example with ffi.C.memcpy() of ffi.copy() byte-per-byte or whatever
- but the "duplicated" instance could have some of its data miss-aligned if we do not try to "align" the "duplicate".

(And I agree that in reality ffi.C.malloc should always have a pratical minimal alignment of 8 on x64 platforms, so unless doing weird stuff, it should always be sufficiently aligned, but in theory we could have a custom memory allocator supporting custom alignment specification, like a `myMalloc(size_t size, int aligment)`...)

Example of this scenario :
```
ffi = require("ffi")

ffi.cdef[[
void *malloc(size_t size);

struct __attribute__((aligned(32))) s {
  uint8_t x;
  uint8_t y;
};
]]

function myMalloc(size, align) -- pretend that we have a custom allocator supporting custom alignment
    print("allocating with size/", size, "and align/", align)
    return ffi.C.malloc(size)
end

local a = ffi.cast("struct s &", myMalloc(ffi.sizeof("struct s"), ffi.alignof("struct s")))
-- print : allocating with size/	32	and align/	32
a.x = 7

-- CASE 1 : copy, but alignment is "lost" : ffi.alignof() on the "ref" returns 8...

function copy_unknown_data_case_1(old)
    local typeOf = ffi.typeof(old)

    local new = ffi.cast(typeOf, myMalloc(ffi.sizeof(typeOf), ffi.alignof(typeOf)))
    ffi.copy(new, old, ffi.sizeof(typeOf))
    return new
end

local b = copy_unknown_data_case_1(a)
-- print : allocating with size/	32	and align/	8 <<< missaligned
b.x = 8
print(a.x, b.x) -- result : 7,8 ; so we didn't overwrote `a` (good)

-- CASE 2 : copy, but by leveraging "parameterized types" in a weird way

function copy_unknown_data_case_2(old)
    local bleededType = ffi.typeof("struct s") -- here we "bleed" "unknown information.
    -- this is because LuaJIT does not provide a way to dereference a ctype reference.
    -- instead of bleeding, we could use http://corsix.github.io/ffi-reflect/
    -- somewhat like : bleededType = reflect.typeof(old).element_type

    -- I would also like to be at least be able to index [0] on ctype reference,
    -- so that we could ffi.typeof("$", reference[0])

    ffi.cdef([[
    struct wrapper {
        uint8_t version;
        $ version_data;
    };
    ]], bleededType)

    print("wrapper size : ", ffi.sizeof("struct wrapper")) -- 64 (good)
    local new = ffi.new("struct wrapper", 42, old) -- copy (good)
    return new
end

local c = copy_unknown_data_case_2(a)
print("offsetof : ", ffi.offsetof(c, "version_data")) -- yields 32 (good)

c.version_data.x = 9
print(a.x, c.version_data.x) -- result : 7,9 ; so we didn't overwrote `a` (good)
```

Sorry that's a long post, but with some points all converging to `alignment` stuff :

- some possible issues regarding LuaJIT and `typedef struct __attribute__((aligned(n)) myStruct { fields ... } myStruct` for which then the "typedef'ed" `myStruct` does not allow ffi.metatype()
- some possible difficulty obtaining `ffi.alignof()` from a ctype "ref" (from a `ffi.typeof("$ &", ctype`), which in turn yields some difficulty to "reporting/duplicating" the correct "alignment" of an original "ctype ref" to wanted copies. (this is solvable with http://corsix.github.io/ffi-reflect/) though, with which we "de-reference" the "ctype ref" and thus can get hold of the "original ctype" and thus get the correct ffi.alignof()) : maybe LuaJIT's `ffi.alignof()` should report the "de-referenced alignment" of the referenced type ?
- when "compositing" new types using "parameterized types" : If we have a ctype (a reference to a struct), we cannot usefully "parameterize" a new type including the "unreferenced base struct" (without the `&`). Doing this would solve not being able to get alignment info from ffi.alignof() on a reference. Maybe we could allow to index [0] on a ctype reference to yield the "base" type, so that we can on the base type both ffi.alignof() it and use it in "parameterized types" ?

Kind Regards,

**Comment by MikePall** [comment]
Attributes in C type declarations are a GCC invention and AFAIK not formally specified. It's not fully clear how they should interact with struct and typedef declarations and where they end up being attached to (*). 

The LuaJIT C parser always interprets a `typedef` simply as giving a name to a type. All attributes are propagated to the underlying type:
* With a combined struct and typedef declaration, the attribute ends up attached to the struct and the typedef also points to it.
* When you declare the typedef separately with an attribute, you're actually creating a new variant of the struct and the typedef just gives it a name.

Wrapping  up:
1. Using `ffi.metatype()` on such a typedef ought to work and has just been fixed.
2. I've also fixed `ffi.alignof()` of a reference type. 
3. I have no good solution for the "de-ref" issue. It appears in multiple contexts. And `ctype[x]` already has a meaning -- it resolves per-struct constants or calls the `__index` metamethod of the metatype.

(*) There are 'interesting' differences on the placement of attributes e.g. with functions and their return types.
