### ISSUE TITLE
How are build systems meant to detect the exact LuaJIT version?

### ISSUE THREAD

**Issue by sfan5** [LuaJIT/LuaJIT#862]
Situation: You write software, other people compile it from source, you have no control over which LuaJIT versions they use. This is the standard situation for open source software that runs on Linux.

To make sure it actually works in the end our build system still contains these two workarounds:
* `-pagezero_size 10000 -image_base 100000000` on macOS
* something similar with `-Wl,--image-base` on Linux/ARM64 due to the 47-bit lightuserdata limit

Now these two have no longer been necessary for a while, ee855749a mentions the macOS workaround to only apply to 2.0 and lightuserdata was fixed in e9af1abec. I'd like to get rid of these workarounds where not necessary.
The issue is that there has been no change¹ in version numbers of preprocessor defines since then that'd directly allow detecting if they're still needed.

From LuaJIT's point of view, how are build systems intended to deal with this?

---

¹: I suppose `LUAJIT_VERSION_NUM` works for the macOS one actually

**Comment by MikePall** [comment]
Obsolete with switch to rolling releases.

**Comment by sfan5** [comment]
luajit.h now:
```c
#define LUAJIT_VERSION          "LuaJIT 2.1.1692583405"
#define LUAJIT_VERSION_NUM      20199  /* Deprecated. */
#define LUAJIT_VERSION_SYM      luaJIT_version_2_1_1692583405
```

Thanks.
