### ISSUE TITLE
Adding api changes from redis lua to luajit

### ISSUE THREAD

**Issue by zcaudate** [LuaJIT/LuaJIT#868]
I have a redis fork working with the luajit interpreter (also another fork). I did the bare minimum to get it working (only adding missing files)

However, between redis 6.2.6 and 6.2.7, new functionally was added to the redis `lapi.c` and `lua.h` and has broken the fork. It's be great if someone with more experience can outline what options I have and whether it's even worth trying to get the new commits working with the fork. 

The issue is here:
https://github.com/redis/redis/issues/11009#issuecomment-1188562720

**Comment by MikePall** [comment]
The LuaJIT 2.x code base is very different from Lua. Adapting those changes would be a major rewrite affecting all parts of the VM.

Anyway, these 'readonly' changes look more like a makeshift measure to silence the CVE industry. If one allows running Lua scripts inside Redis one can trivially crash or hang it with a one-liner. And some of the crahes can likely be turned into RCEs. This has been known for years and the one-liners are floating around -- not posting here, ask privately if interested.

In other words: if you allow Lua scripting in Redis, you're pretty much hosed, anyway.

So your options drill down to:
* Back out those changes or stay at 6.2.6. If you have different privilege levels (and/or ACLs) then rename the scripting commands to hide them from clients with lower privilege levels.
* Stop using LuaJIT inside Redis. Considering the way Redis is used and the way Lua is integrated, I doubt it provides any measurable speedup (it's unlikely you're running, say, a matrix multiplication inside a Redis query).

**Comment by zcaudate** [comment]
@MikePall thanks for that. I'll send an email.

**Comment by zcaudate** [comment]
@MikePall Did you ever get my email. I sent it to the one listed on luajit.org website.

**Comment by MikePall** [comment]
I replied the same day. Since you're using a consumer mail provider (outlook.com), you really need to check your spam folder regularly. Just like gmail.com they blackhole all my mails (actually all smaller self-hosted mail domains).

**Comment by zcaudate** [comment]
oh shit. that's really strange - it's not in my junk folder. can you resend and let me know here as well?

**Comment by MikePall** [comment]
Just sent again.

**Comment by zcaudate** [comment]
it's not arrived. that's really annoying. I'm put that email on the safe list and it's still not coming through. Can I ask you to try one last time and if it doesn't work, I'll create a private repo and chat there.

**Comment by MikePall** [comment]
Sorry, no time for chat. Anyway, the mail contained nothing of importance. Staying at Redis 6.2.6 is your best option then.

The comment about the one-liners was really more intended for the Redis developers. Maybe they want to fix these issues in their copy of Lua.

**Comment by zcaudate** [comment]
Yep will do. Redis 5.0 is most performant for me atm. I wanted to see if it’s worth keeping up with the newer stuff but it’s easier to stick with what works.

I’m still really curious about the one liners. It’s a bit silly to allow random EVAL on a production system but besides mistakes like `while true…` and calling external modules, I haven’t found any serious examples.

On 27 Jul 2022, at 5:42 pm, Mike Pall ***@***.******@***.***>> wrote:



Sorry, no time for chat. Anyway, the mail contained nothing of importance. Staying at Redis 6.2.6 is your best option then.

The comment about the one-liners was really more intended for the Redis developers. Maybe they want to fix these issues in their copy of Lua.
