### ISSUE TITLE
DynASM: dynamic register allocation

### ISSUE THREAD

**Issue by DemiMarie** [LuaJIT/LuaJIT#87]
Dynamic register allocation is only supported on x86 for now.

However, other JIT compilers for other languages use DynASM as the backend, because it is so much easier than generating machine code by hand.  The [MoarVM JIT compiler developers](http://brrt-to-the-future.blogspot.com/2015/03/advancing-jit-compiler.html) have wanted this for a while.  Furthermore, dynamic register allocation might make DynASM usable in LuaJIT's backend once more and is essential if DynASM is to be part of the solution to #39 (provide user-definable intrinsics).  This would make DynASM more usable for a wide range of purposes.

**Comment by MikePall** [comment]
Fixed for x64 in PR #119

**Comment by MikePall** [comment]
VREG support for ARM64 is there since d1132afb.

Closing here because demand for other architectures is dwindling quickly.

**Comment by DemiMarie** [comment]
> Closing here because demand for other architectures is dwindling quickly.

I could see demand for POWER and RISC-V arising, but it probably isn’t there yet.
