### ISSUE TITLE
Cross compile LuaJIT for QNX 32bit

### ISSUE THREAD

**Issue by QianYizhou** [LuaJIT/LuaJIT#870]
I'm trying to build LuaJIT for QNX 32bit system for intel CPU.
- branch: LuaJIT v2.1
- host: Ubuntu 20.04 64bit
- target: QNX7.0 32bit, x86
- build command:
```shell
make HOST_CC="i586-pc-nto-qnx7.0.0-gcc -m32 -march=haswell --sysroot=/qnx700/target/qnx7/x86" CROSS=i586-pc-nto-qnx7.0.0- TARGET_SYS=others
```

And I got the error below
```shell
==== Building LuaJIT 2.1.0-beta3 ====
make -C src
make[1]: Entering directory '/media/qianyizhou/Data/open_src/luajit/luajit_v2.1_qnx/src'
HOSTCC    host/minilua.o
HOSTLINK  host/minilua
DYNASM    host/buildvm_arch.h
make[1]: host/minilua: Command not found
Makefile:645: recipe for target 'host/buildvm_arch.h' failed
make[1]: *** [host/buildvm_arch.h] Error 127
make[1]: Leaving directory '/media/qianyizhou/Data/open_src/luajit/luajit_v2.1_qnx/src'
Makefile:112: recipe for target 'default' failed
make: *** [default] Error 2
```

It seems the error is cased by the built binary `host/minilua`. minilua (build for QNX 32bit) would failed to run on my host (64bit Ubuntu).
Not sure how to fix this issue. Do I have to build the project on target QNX OS? Could you help me for this part and give me some hints? Thanks!

**Comment by MikePall** [comment]
The host compiler must be the compiler for the OS you're running the build on (i.e. Ubuntu), not the target OS. Quoting the docs:

> E.g. if you want to cross-compile to a 32 bit target on a 64 bit host, you need to install the multilib development package (e.g. `libc6-dev-i386` on Debian/Ubuntu) and build a 32 bit host part (`HOST_CC="gcc -m32"`).

**Comment by QianYizhou** [comment]
Thanks a lot for your help, I can now build the project on my host (Ubuntu 20.04)! Here're my steps:

1. Modify the code a little (not sure if I set `TARGET_SYS` correctly) for QNX
2. Then run the command below:
``` shell
sudo apt install libc6-dev-i386
make HOST_CC="gcc -m32" CROSS=i586-pc-nto-qnx7.0.0- TARGET_SYS=POSIX
```

Haven't check the build result on target yet. And thanks again @MikePall !
