### ISSUE TITLE
I see my issues have been fixed, I tested it and it doesn't seem to work

### ISSUE THREAD

**Issue by ccagml** [LuaJIT/LuaJIT#873]
# I see my issues are fixed
- https://github.com/LuaJIT/LuaJIT/issues/869
# I see the corresponding fix is this commit
- https://github.com/LuaJIT/LuaJIT/commit/32984282ddae666b3c94cd27538e1c78b49a1877
# I checked that the code I checked out also contains the fix code
```
  case BC_ITERL:
    if (bc_op(pc[-1]) == BC_JLOOP)
      lj_trace_err(J, LJ_TRERR_LINNER);
    lj_assertJ(bc_op(pc[-1]) == BC_ITERC, "no ITERC before ITERL");
```
# I recompiled luajit, but the problem of the previous issues still occurs, did I make a mistake?

**Comment by MikePall** [comment]
Opening a separate issue for the same problem is not a good idea. This here will be closed as a duplicate.

That said, I ran your code 100 times with the current version (compiled by myself) and it never failed. So you need to 1. reduce your example to a simpler test case and 2. make it more easily and faster reproducible. And only then 3. add a comment with a link to the new code to the original issue.
