### ISSUE TITLE
Expressions don't work in the REPL, only statements

### ISSUE THREAD

**Issue by Melchizedek6809** [LuaJIT/LuaJIT#874]
When I start the LuaJIT REPL, pretty much everything I type produces the following error:
```
> 1
stdin:1: unexpected symbol near '1'
```

Tried it with multiple versions of LuaJIT on 3 separate Linux systems and with multiple Terminals.  PUC-Lua seems to work fine with the same setups.

Versions I tried:
- v2.1 branch = 3065c910ad6027031aabe2dfd3c26a3d0f014b4f (amd64 / Arch Linux)
- v2.0 branch = 899093a9e0fa5b16f27016381ef4b15529dadff2 (amd64 / Arch Linux)
- v2.1 branch = 3065c910ad6027031aabe2dfd3c26a3d0f014b4f (arm64 / Raspberry PI OS)
- 2.1.0-beta3 (the one that is included with Raspberry PI OS) (arm64 / Raspberry PI OS)
- v2.1 branch = 3065c910ad6027031aabe2dfd3c26a3d0f014b4f (amd64 / MacOS 12.04)

I tried using mlterm,xterm, xfce4-terminal and Terminal.app all had the same issue.

**Comment by UncombedCoconut** [comment]
Disclaimer: I'm a random internet person, not a LuaJIT team member.
Does it work fine if you enter _statements_ such as `print(1)` or `x = 1` as opposed to `expressions`?
(In other words, treat it as an interactive execution environment rather than a read-eval-print loop.)

**Comment by Melchizedek6809** [comment]
Great Idea, and yes, statements seem to work just fine.

**Comment by GitSparTV** [comment]
LuaJIT is compatible with Lua 5.1 which doesn't print values without a proper statement.

This feature appeared only in Lua 5.3.

**Comment by Melchizedek6809** [comment]
@GitSparTV Interesting, do you know if there is any chance that this will be supported in LuaJIT?  Or that a pull request implementing it would be merged?

**Comment by GitSparTV** [comment]
Just type `=` before your value (`= 1`)

**Comment by UncombedCoconut** [comment]
FYI, You can also get a much nicer REPL than any language runtime can/should provide by turning to the ecosystem, starting here for instance: http://lua-users.org/wiki/LuaRepl
(IMHO it's best to close this issue as an answered question, not a problem for a focused project like LuaJIT to solve.)

**Comment by Melchizedek6809** [comment]
Thanks you for recommending LuaRepl.
Apart from that would there be any interest in/chance of merging a PR adding that feature?
Maybe there are others who are suprised by this as well.

**Comment by GitSparTV** [comment]
No, just make your own REPL if you want
