### ISSUE TITLE
lj_cf_package_loader_preload call dlsym with null handle 

### ISSUE THREAD

**Issue by CatDroid** [LuaJIT/LuaJIT#878]
I use luajit on ios applicaiton.
```
static int lj_cf_package_loader_preload(lua_State *L)
{
  const char *name = luaL_checkstring(L, 1);
  lua_getfield(L, LUA_ENVIRONINDEX, "preload");
  if (!lua_istable(L, -1))
    luaL_error(L, LUA_QL("package.preload") " must be a table");
  lua_getfield(L, -1, name);
  if (lua_isnil(L, -1)) {  /* Not found? */
    const char *bcname = mksymname(L, name, SYMPREFIX_BC);
    const char *bcdata = ll_bcsym(NULL, bcname);  // --- Here --- 
    if (bcdata == NULL || luaL_loadbuffer(L, bcdata, ~(size_t)0, name) != 0)
      lua_pushfstring(L, "\n\tno field package.preload['%s']", name);
  }
  return 1;
}
```
I found that the first time call "require xxx" in lua file,  it will take much times on dlsym as shown above "--Here--"
The cpu time is about 11ms, but the wall time is 100ms. It means the applcaiton blocked for 100-11=89ms. 

After profile, it spends much time  on "Virtual memory file backed Page".

I think 'dlsym with nullhandle' will walk through the appllcation to find the symbol . reference: [stackoverflow](https://stackoverflow.com/questions/56993565/calling-dlsym-with-a-null-handle-doesnt-return-null-but-rather-returns-a-ran)

Is it possible to delete this 'll_bcsym' section ? what's the side effect ?

**Comment by MikePall** [comment]
See: https://luajit.org/running.html#opt_b

> To statically embed the bytecode of a module in your application, generate an object file and just link it with your application. 
> [...]
> `require()` tries to load embedded bytecode data from exported symbols [...]

If you don't need this feature, remove the three lines after the `lua_isnil()` in `lj_cf_package_loader_preload`. But keep the `lua_pushfstring()`.
If you don't need the preload feature at all, just remove `lj_cf_package_loader_preload` from the `package_loaders` array.
