### ISSUE TITLE
[Compatibility] Android 4.4 fails on `ll_bcsym`

### ISSUE THREAD

**Issue by gudzpoz** [LuaJIT/LuaJIT#880]
There is an ancient bug on Android API level 19 (Android 4.4): https://android.googlesource.com/platform/bionic/+/ebd506c69e12b6dcaf5be94cc8ed1b53af299f9f .

In short, invoking `dlsym(RTLD_DEFAULT, "non_exsistent_symbol")` throws `SIGFPE` on Android 4.4. And `require('lua.file.library')` always crashes the whole program since `lj_cf_package_loader_preload` is the first package loader.

It *is* a bug on the Android side, fixed in later builds, but it still haunts Android API level 19 (and maybe 20). Is it possible to offer the users a way to change the default value from `RTLD_DEFAULT` to `NULL`? (`dlsym(NULL, "non_exsistent_symbol")` works fine.) For example:

```diff
static const char *ll_bcsym(void *lib, const char *sym)
{
- #if defined(RTLD_DEFAULT)
+ #if defined(RTLD_DEFAULT) && !define(NO_RTLD_DEFAULT)
  if (lib == NULL) lib = RTLD_DEFAULT;
#elif LJ_TARGET_OSX || LJ_TARGET_BSD
  if (lib == NULL) lib = (void *)(intptr_t)-2;
#endif
  return (const char *)dlsym(lib, sym);
}
```

P.S. FFI may be also affected since it uses `dlsym`.

**Comment by MikePall** [comment]
Fixed. Thanks!
