### ISSUE TITLE
Issue with lua_concat

### ISSUE THREAD

**Issue by JCash** [LuaJIT/LuaJIT#881]
I have a case where I try to concatenate a string with a userdata struct, using `lua_concat(L,2)`.
It works in Lua 5.1.5, but with latest LuaJIT, it seems to consume 2 _extra_ items from the stack, which of course is very bad.

I've created a small repro case where I push 5 strings, and a userdata struct to the stack.
Then I concatenate the last two items (the string `Aa` and the userdata struct).
In the case of LuaJIT, it concatenates 4 items, not 2!?

Here's the stack before the concatenation call:
```
1	string	Ee
2	string	Dd
3	string	Cc
4	string	Bb
5	string	Aa
6	userdata	0x105bc3038 : Info.value=7
```

Here's the output after the concatenation.

```
    // Expected stack, from Lua 5.1.5:
    // CONCAT: 'Aa[Info.value=7]'
    // 1   string  Ee
    // 2   string  Dd
    // 3   string  Cc
    // 4   string  Bb
    // 5   string  Aa[Info.value=7]

    // What I get with LuaJIT 2.1
    // CONCAT: 'CcBbAa[Info.value=7]'
    // 1   string  Ee
    // 2   string  Dd
    // 3   string  CcBbAa[Info.value=7]
    // The stack size is not expected! Expected 5, is 3
```

I'm running this test on macOS.
I've attached a small repro case which works for Lua 5.1.5, but not latest LuaJIT.

See build instructions in compile-luajit.sh (there's a similar compile-vanilla.sh):
```
#!/usr/bin/env bash

set -e

# Download LuaJIT
#   $ git clone git@github.com:LuaJIT/LuaJIT.git
# Build LuaJIT (e.g for macosx)
#   $ MACOSX_DEPLOYMENT_TARGET=10.9 make -j8
# Install locally
#   $ make install PREFIX=$(pwd)/install
# Use LUAJIT_PATH to build test:
#   $ LUAJIT_PATH=/projects/external/LuaJIT/install ./compile-luajit.sh
# Run test
#   $ ./a.out

INCLUDES=${LUAJIT_PATH}/include/luajit-2.1
LIBPATH=${LUAJIT_PATH}/lib
DEFINES="-DUSE_LUAJIT"

clang test.c -O0 -g ${DEFINES} -I$INCLUDES -L$LIBPATH -lluajit-5.1
```

[test.zip](https://github.com/LuaJIT/LuaJIT/files/9301470/test.zip)

I hope someone can help shed som light into this issue.
Is it a bug in LuaJIT or some misconfiguration/misunderstanding on my part?

Regards,
Mathias

(Ps. thanks for an awesome library!)

**Comment by MikePall** [comment]
Fixed. Thanks!
