### ISSUE TITLE
🥚 What is the "\xFF" setlocale category for?

### ISSUE THREAD

**Issue by TurkeyMcMac** [LuaJIT/LuaJIT#886]
This code throws an error with the latest LuaJIT version, as it should:

```lua
os.setlocale("C", "\xFE")
```

However, this code does not:

```lua
os.setlocale("C", "\xFF")
```

I have looked at the implementation of `os.setlocale`, and it seems that the above code will end up calling the C function `setlocale(5, "C")`, with implementation-defined consequences.

**Comment by MikePall** [comment]
Congratulations, you're the first one who found this easter egg in the LuaJIT code base! It only took 13 years.
Here's your virtual easter egg award:
# 🥚 TurkeyMcMac
If you dig further, you'll find out why and you will receive the second one.

**Comment by XmiliaH** [comment]
The `collectgarbage` function has a similar option `print(collectgarbage"\xff")` which prints the `LUA_COUNTB`.
I would guess these are used to as placeholders to allow the option index to be the actual value to allow the compiler in the normal case to remove all the if instructions as they just reassign the same value and makes them redundant.

**Comment by TurkeyMcMac** [comment]
I checked the generated machine code and you're right, the return value of `lj_lib_checkopt` is passed directly to `setlocale`.

**Comment by MikePall** [comment]
I guess XmiliaH couldn't resist and took the 2nd easter egg award. Anyway, congratulations to both of you!
# 🥚 XmiliaH

**Comment by TurkeyMcMac** [comment]
Thanks for the egg!
