### ISSUE TITLE
Nearly all CRT functions from stdio are exported by lua51.lib

### ISSUE THREAD

**Issue by z16166** [LuaJIT/LuaJIT#889]
Windows 11 x64 + VS2019 x64 build, vcpkg triplet: luajit:x64-windows-static.

If I statically linking to lua51.lib, my dll/exe export table will contain 170+ CRT functions such as "sprintf/sscanf/fprintf" etc.

What I do to resolve this:

modify src\msvcbuild.bat,
change "/D_CRT_STDIO_INLINE=__declspec(dllexport)__inline" to "/D_CRT_STDIO_INLINE=__inline"

If you have better solution, please do it. thanks.

vcpkg issue ref:
https://github.com/microsoft/vcpkg/issues/26511

**Comment by MikePall** [comment]
This is the result of some completely unnecessary Microsoft extravaganza. I suggest you complain at the original repo, so their staff hears about the bad decisions of their colleagues.

Without this definition, the FFI cannot reach any of the stdio functions. [Original report](https://www.freelists.org/post/luajit/cannot-resolve-symbol-printf-with-ffi-msvc-140) with the `_CRT_STDIO_INLINE` workaround.
