### ISSUE TITLE
Compiled GC

### ISSUE THREAD

**Issue by SoniEx2** [LuaJIT/LuaJIT#90]
The GC should play nice with the JIT. Maybe write it in pure Lua?

**Comment by linkerlin** [comment]
Not a good idea.
Pure lua will be slower.

**Comment by SoniEx2** [comment]
Not when it's JITted.

**Comment by kirbyfan64** [comment]
But then won't the GC require a GC to run?

In addition, writing it in Lua implies JIT overhead, doesn't it?

**Comment by SoniEx2** [comment]
It won't require a GC! Just access to some LuaJIT internals and especially the allocation function.

Altho it will be a major pain... If not to maintain then at least to develop...

Also the pros of JITted garbage collection outweight the cons. The LJ JIT is pretty efficient.

**Comment by TheNuke** [comment]
Do it on your own; see above issues. Also, if I'm correct, it is intended to merge the allocator and GC. It sounds like a neat experiment but not something for LuaJIT core.

**Comment by Neopallium** [comment]
Execution of Lua code has to be paused during garbage collection.  Executing Lua code during collection would change the GC state, which would be difficult to correctly handle.

I also don't think the JIT would improve the speed of the GC.

**Comment by SoniEx2** [comment]
> Executing Lua code during collection would change the GC state, which would be difficult to correctly handle.

Ok so LJ uses NaN-tagging. This means everything will use a single register space. This means everything is pass-by-value.

Let's say we expose a `free(value)` so when you wanna use something other than integers in the GC all you have to do is free(value) it after you're done. E.g.

```lua
local reg -- allocate the register
reg = 3 -- put a number in it, by-value.
reg = 5 -- put another number in it, no need to free.
reg = "String" -- this allocates a new string and puts a tagged NaN in reg
-- reg = "another string" -- uncomment to leak memory
free(reg) -- free it
-- print(reg) -- uncomment to segfault
reg = 0 -- safe to do now that we free()d it
```

For tables this is more complex as you have to free() each element first.

```lua
local function freetable(t)
  local tabs = {} -- contains "emptied" tables
  for k,v in pairs(t) do
    local ktype = type(k)
    local vtype = type(v)
    if ktype == "table" and not tabs[ktype] then -- compare with constant, no need to free (should probably check for functions and coroutines tho)
      tabs[k] = true -- true nil and false are all safe
    else
      free(k)
    end
    if vtype == "table" and not tabs[vtype] then
      tabs[v] = true
    else
      free(v)
    end
    -- we don't want to set t[k]=nil because that'd break pairs()
    free(ktype) free(vtype) -- those we need to free
  end
  for k,v in pairs(tabs) do -- now we free everything in tabs
    free(k)
  end
end

**Comment by Neopallium** [comment]
Here are some issue with that example:

1. Those strings are referenced by the code and can't be freed.
2. pairs() creates a closure (a collectable object with an upvalue that points to the table).  Also pairs() is [NYI](http://wiki.luajit.org/NYI).  So that freetable function wouldn't be compiled.
3. type() returns strings that can't be freed.
4. The 'tabs' table would also have to be freed.

But the main issue is that the GC would be creating objects (mutating the GC state) while it is traversing all objects in the Lua state marking the live values.

**Comment by SoniEx2** [comment]
@Neopallium except pairs() is guaranteed to return next, t, nil in Lua 5.1.

And yeah I just quickly put it together as an example. And the way I see it is that the GC would run in an isolated "state" without a GC state attached (it's the bloody GC! you can't GC the GC!).

**Comment by Neopallium** [comment]
One way to try implementing a GC in Lua is to replace the GC of the standard Lua VM.  It would be easy to modify that VM to allow the main GC functions to be replaced.  Then use FFI to bind to the Lua VM's API and import the internal C structure to be used by the GC.

This would at least allow testing the performance of a GC written in Lua vs one written in C code.

**Comment by mraleph** [comment]
There is absolutely no good reason to rewrite LuaJIT's GC in Lua. I am going to close this issue.
