### ISSUE TITLE
couldn't build on mac 

### ISSUE THREAD

**Issue by ItsyourboyJonnycat** [LuaJIT/LuaJIT#901]
![Screen Shot 2022-09-20 at 10 40 54 PM](https://user-images.githubusercontent.com/107599365/191423298-a1f93317-3449-4b30-bb7c-67c7c6f7c743.png)

**Comment by ItsyourboyJonnycat** [comment]
![Screen Shot 2022-09-20 at 10 42 06 PM](https://user-images.githubusercontent.com/107599365/191423464-39c18aa8-0143-4fd9-b17c-03c2e58bdfa0.png)
here is the invocation

**Comment by MoNTE48** [comment]
https://github.com/MultiCraft/MultiCraft/blob/main/build/macOS/deps/luajit.sh
