### ISSUE TITLE
wiki.luajit.org has been shutdown almost 2 months

### ISSUE THREAD

**Issue by M1NGS** [LuaJIT/LuaJIT#902]
all requests are redirected to www.luajit.org, will it be fixed?

**Comment by MikePall** [comment]
The Wiki will not come back. I may resurrect some of the old content as a collection of articles on the main site, whenever I get around to it.

**Comment by kress95** [comment]
@M1NGS 

If you need to read content from the old wiki, I've restored an old backup from wayback machine here: https://kress95.github.io/luajit-wiki/

**Comment by M1NGS** [comment]
> @M1NGS
> 
> If you need to read content from the old wiki, I've restored the last backup from wayback machine here: https://kress95.github.io/luajit-wiki/

Thanks

**Comment by thomastay** [comment]
@kress95 This is really helpful, i wanted to refer back to the bytecode reference and this was the only place that had it!

**Comment by thomastay** [comment]
@MikePall I know you said the wiki won't come back, but would you consider uploading the docs to the Github repo?

**Comment by Buristan** [comment]
For our convenience in usage, we copy a part of the LuaJIT Wiki pages from [the web archive](http://web.archive.org/web/20220625023254/http://wiki.luajit.org/Home) to [our Wiki on GitHub](https://github.com/tarantool/tarantool/wiki/Old-LuaJIT-Wiki). Feel free to use it :)!

I suppose Mike can copy (with some modifications) these markdown notes to the Wiki for this repo too, if he wants, of course.
