### ISSUE TITLE
ARM64: IR_SLOAD assembly

### ISSUE THREAD

**Issue by Gate88** [LuaJIT/LuaJIT#903]
This issue happens with the latest 2.1 commit (dad04f1754723e76ba9dcf9f401f3134a0cd3972) on my M1 Macbook Pro.

I've been making a game in Love2d, and when testing it on my M1 Macbook Pro I noticed some visual bugs/differences compared to what I was seeing on my 64 bit Windows machine. I'm not very well-versed in how LuaJIT operates so it took me a few hours of tedious guesswork to narrow it down to a (somewhat) concise example that is reproducible _without_ Love2D.

I'm not sure exactly which parts of the file are strictly relevant -- I was just trying to mirror the structure of what my Love2d program was doing so I could actually reproduce the issue. When I tried to guess what was relevant, I could not reproduce it. It might be an issue with how values are passed between the rotate() or inBounds() function, but I honestly have no idea. If you io.write(x,y) before the return statement in the inBounds() call the problem goes away, and it seems like the Static2.rotate() call is necessary for the bug to happen too.

```lua
local Static = {}
local Static2 = {}

local Room = {}
Room.__index = Room

function Room:inBounds(x, y)
    return x >= 0
        and y >= 0
        and x < self.width
        and y < self.height
end

local RoomView = {}
RoomView.__index = RoomView

local EditorView = {}
EditorView.__index = EditorView

function Static2.rotate(x, y, rot, width, height)
    rot = rot % 1
    if rot == 0 then return x, y end
    if rot == .25 then return y, width - 1 - x end
    if rot == .5 then return width - 1 - x, height - 1 - y end
    if rot == .75 then return height - 1 - y, x end
    error("rot: " .. rot .. "is not a cardinal direction")
end

function Static.drawRoomPreview(room, rotation)
    local width, height = room.width, room.height

    for i = 0, width * height - 1 do
        local tileX, tileY = (i % width), math.floor(i / width)
        local tileX2, tileY2 = Static2.rotate(tileX, tileY, -rotation, width, height)

        assert(room:inBounds(tileX2, tileY2))
    end
end

function RoomView:draw()
    for index = 0, #self.roomCache - 1 do
        local room = self.roomCache[index + 1]
        Static.drawRoomPreview(room, 0)
    end
end

function EditorView:draw()
    self._roomSelectionView:draw()
end

local maxWidth = 10
local maxHeight = 10


local function draw()
    local rooms = {}
    math.randomseed(0)
    for x = 1, maxWidth do
        for y = 1, maxHeight do
            local room = setmetatable({
                width = math.random(1, maxWidth),
                height = math.random(1, maxHeight),
            }, Room)
            rooms[#rooms + 1] = room
        end
    end

    local roomView = setmetatable({
        roomCache = rooms
    }, RoomView)


    local editorView = setmetatable({
        _roomSelectionView = roomView
    }, EditorView)

    local gs = {
        isEditMode = true,
        editorView = editorView
    }

    for r = 1, 2000 do
        if gs.isEditMode then
            gs.editorView:draw()
        end
    end

    io.write("finished successfully\n")
end

draw()
```

If I run the above file on my M1 Macbook Pro, the assertion gets triggered. If I run with jit off or on my Windows PC, it finishes successfully.

```
luajit % ./luajit m1bug.lua 
./luajit: m1bug.lua:36: assertion failed!
stack traceback:
    [C]: in function 'assert'
    m1bug.lua:36: in function 'drawRoomPreview'
    m1bug.lua:43: in function 'draw'
    m1bug.lua:48: in function 'draw'
    m1bug.lua:87: in function 'draw'
    m1bug.lua:94: in main chunk
    [C]: at 0x01004a1500
luajit % ./luajit -joff m1bug.lua
finished succesfully
```

I'm also experiencing some inconsistent Segfaults on my M1 that I don't experience on Windows. I have an example segfault with a Love2D dependency that happens about 8% of the time I run it (I unfortunately have no idea how to make it more consistent). Would you accept an issue with a Love2D dependency or should I try to do more work to separate it out? If you have any advice on how to narrow down segfaults with or without Love2D that would be very helpful for me, too.

Thanks!
-John

**Comment by MikePall** [comment]
Fixed. Thanks!

And, no, I can only accept test cases without dependencies, such as this one.
