### ISSUE TITLE
Segmentation fault (core dumped) when Generate buildvm_libbc.h

### ISSUE THREAD

**Issue by libing0526** [LuaJIT/LuaJIT#905]
brahch : LuaJIT v2.1
arch：linux 3.10.0 x86_64
Probability of occurrence：100%
when I excute “./luajit host/genlibbc.lua lib_*.c”，it crashed。I add some prints in genlibbc.lua，It is clear that it crashed after “find_defs” “table_move”。I found LJLIB_CF(table_concat) function has no return value，after adding "return 1”，it works normally。Is this a problem of LuaJIT？

**Comment by MikePall** [comment]
You should never need to run `genlibbc.lua` yourself. Use the pre-built `buildvm_libbc.h`.
Also, `LJLIB_CF(table_concat)` of course *does* have a `return 1`. If not, then you're not using the code from this repo.

**Comment by libing0526** [comment]
Yes.  you are right, Thanks.
before，I use v2.1.0-beta3 branch；now I changed to v2.1，so there is no need to run genlibbc.lua（it‘s a greate change）
