### ISSUE TITLE
Compiled bytecode loading

### ISSUE THREAD

**Issue by SoniEx2** [LuaJIT/LuaJIT#91]
Because why not? Then we can implement the parser/lexer/compiler in Lua/bytecode and have it JIT.

**Comment by Neopallium** [comment]
I like the idea of having the Lua parser written in Lua.  It would allow people to implement there own language extensions (bitwise operators, etc...) easily.  Could even allow hooks to be registered.

I had been thinking about creating a Lua compiler frontend (parser/lexer/ast) written in Lua as the start of a complete re-design of my [slua](https://github.com/Neopallium/slua) project.

slua is a static compiler that compiles Lua code into C code (it is a re-write from my [llvm-lua](https://code.google.com/p/llvm-lua/) project).  Both of those projects used the standard Lua compiler and only worked on the bytecode.  This put some limits on the type of optimizations that could be done.

I think a generic Lua compiler frontend written in Lua would be very useful, even outside of LuaJIT.

For LuaJIT it could be compiled and embedded into LuaJIT during the build.  This would also allow it to be optimized for the enabled features (FFI support, Lua 5.2 support, etc..).

Lua compilers/parsers written in Lua:

* [MetaLua](https://github.com/fab13n/metalua/blob/master/README-parser.md), I am not sure if it is written in pure Lua code (might use language extensions).
* [lua-parser](https://github.com/andremm/lua-parser), requires LPeg

**Comment by gaoxiaojun** [comment]
see https://github.com/franko/luajit-lang-toolkit.git
The LuaJIT Language Toolkit is an implementation of the Lua programming language written in Lua itself

**Comment by Neopallium** [comment]
Nice.  I wonder how fast it is compared to LuaJIT's parser/compiler.

**Comment by stepelu** [comment]
On 7 December 2015 at 06:36, Robert Gabriel Jakabosky <
notifications@github.com> wrote:

> Nice. I wonder how fast it is compared to LuaJIT's parser/compiler.
>
The compiler it's to LuaJIT code / bytecode, the execution is always done
by LuaJIT.

On the topic I found this a while ago (chapter 4):
http://www.diva-portal.org/smash/get/diva2:732351/FULLTEXT01.pdf


Stefano

**Comment by mraleph** [comment]
To be honest, I don't think this really needed to be a core feature. A generic extensible front-end capable of emitting LuaJIT bytecode can easily exist outside of LuaJIT itself because LuaJIT is capable of loading bytecode. "Why not?" is not an argument for inclusion of something into LuaJIT. Enumerating benefits this inclusion can yield *would* be an argument.

**Comment by SoniEx2** [comment]
I'd be able to write a fully JITted JIT compiler in LuaJIT (e.g. for an emulator). Having to emit LuaJIT bytecode is fine by me, and implementing JITted bytecode loading is much easier than implementing JITted Lua code loading.
