### ISSUE TITLE
Q: lua_atpanic discrepancy between Lua 5.1 and LuaJIT v2.1

### ISSUE THREAD

**Issue by JCash** [LuaJIT/LuaJIT#916]
Hi!
I'm wondering if anyone else has experienced this behavior.
It seems like LuaJIT behaves differently regarding `lua_atpanic`.

Depending on lua runtime, I get different number of items left on the stack, which seems odd.

My repro is this:
* Push an value (`123`)
* Throw an error (`Argument -1 must be a boolean`)

Then after returning to the call site, the number of items differ.
In Lua, the item is simply the lua error:
```
TEST: Stack size after panic 1
1	string	Argument -1 must be a boolean
```

In LuaJIT, the stack looks like this:
```
TEST: Stack size after panic 3
1	number	123
2	string	Argument -1 must be a boolean
3	string	Argument -1 must be a boolean
```

Question is, am I doing something wrong with my setup?
Or is this an actual discrepancy between Lua/LuaJIT?

I'm testing on macOS, using Lua 5.1.5.
(A colleague confirmed the same behavior on Linux)

Full test code and compile scripts here:
[panictest.zip](https://github.com/LuaJIT/LuaJIT/files/10093029/panictest.zip)

**Comment by XmiliaH** [comment]
While this might be a difference in implementation it is fully compliant with the Lua [manual](https://www.lua.org/manual/5.1/manual.html#lua_atpanic) which states that the panic function can access the error message at the top of the stack where the error message is located in both cases.

The difference might be there to be more compatible with version 5.2 where the panic function runs as if it were a [message handler](https://www.lua.org/manual/5.2/manual.html#4.6) which has the current stack still in tact.

**Comment by MikePall** [comment]
After a panic, the Lua state is unrecoverable and the only thing allowed is to get the error message from the stack top. It doesn't really matter what else is left on the stack, so I would consider this an implementation detail.
