### ISSUE TITLE
function lj_ctype_intern bug?

### ISSUE THREAD

**Issue by elmknot** [LuaJIT/LuaJIT#920]
line 195:
```
lj_mem_growvec(cts->L, cts->tab, cts->sizetab, CTID_MAX, CType);
```
should be:
```
#ifdef LUAJIT_CTYPE_CHECK_ANCHOR
    CType *ct = lj_mem_newvec(cts->L, id+1, CType);
    memcpy(ct, cts->tab, id*sizeof(CType));
    memset(cts->tab, 0, id*sizeof(CType));
    lj_mem_freevec(cts->g, cts->tab, cts->sizetab, CType);
    cts->tab = ct;
    cts->sizetab = id+1;
#else   
    lj_mem_growvec(cts->L, cts->tab, cts->sizetab, CTID_MAX, CType);
#endif  
```

**Comment by MikePall** [comment]
This function itself does not have a bug -- it's rather an improvement of the internal checks.

That said, carefully inspecting all callers, I did find a related bug. But not by using this check, since there's no easy repro for it.

Thanks!

**Comment by sonoro1234** [comment]
In which cases should be LuaJIT compiled with LUAJIT_CTYPE_CHECK_ANCHOR defined?

**Comment by MikePall** [comment]
Only if you modify the C type parsing and interning logic. I.e. never. It's slow and also leads to a deliberate malfunction or crash (and not an assert), if you get something wrong.
