### ISSUE TITLE
luajit - ffi c call with multiple return values

### ISSUE THREAD

**Issue by libing0526** [LuaJIT/LuaJIT#921]
The return value of the c function of luajit ffi is the same as the standard C, which can only be one value. The function of lua can return multiple values, which is a major feature of lua. Is there any good way to make the c function of ffi return multiple values.（Maybe modifying the luajit source code can solve the problem, but it is not compatible with the previous code）

**Comment by GitSparTV** [comment]
To return multiple values for ffi the C language needs to support this.
The proper way (if we think about std::pair or std::tuple) is just a struct with your values returned by the function. This way you can return any values

**Comment by w4454962** [comment]
You can use parameters to pass pointers and then write data to the address of the pointer.

**Comment by libing0526** [comment]
@GitSparTV @w4454962 you are rigtht. Using structures or pointers is a common approach. But in my scenario, I want to write lua code that supports both the interface exported by lua register and the ffi call. So I want to know if there is a way to meet my needs.

**Comment by libing0526** [comment]
@GitSparTV @w4454962 you are rigtht. Using structures or pointers is a common approach. But in my scenario, I want to write lua code that supports both the interface exported by lua register and the ffi call. So I want to know if there is a way to meet my needs.

**Comment by MikePall** [comment]
The LuaJIT FFI is a low-level interface to the platform ABI. Which is predominantly a C ABI. And C doesn't support multiple return values.
I have no intention to add some incompatible feature to the mess that platform ABIs already are. I.e. you're left with the above suggestions.
