### ISSUE TITLE
LuaJIT NaN tagging - retrospect

### ISSUE THREAD

**Issue by dibyendumajumdar** [LuaJIT/LuaJIT#924]
Hi @MikePall 

I was wondering if you were to restart LuaJIT today would you still implement the Nan-tagging approach to values in the interpreter stack? I am curious if you have any insights based on the experience - and whether you would choose an alternative design today.

I remember a post from you regarding this at some point, but I cannot find it anymore, and maybe I am remembering incorrectly.

Regards

**Comment by agladysh** [comment]
@dibyendumajumdar is this the post you're referring to? https://www.freelists.org/post/luajit/Few-questions-about-LuaJIT-internals-on-64-bit,6

**Comment by dibyendumajumdar** [comment]
@agladysh  yes indeed thank you!

**Comment by dibyendumajumdar** [comment]
Thanks for sharing that.
