### ISSUE TITLE
error of compiling luajit for windows

### ISSUE THREAD

**Issue by AlexandrKozlovskiy** [LuaJIT/LuaJIT#925]
Hello. I use latest cyguin, with latest make and gcc. When i try to compile luajit using make command,i get an error. Please,fix this issue.

$ cd c:/users/ksash/luajit

ksash@WIN-EKSJFRPE1RL /cygdrive/c/users/ksash/luajit
$ make
==== Building LuaJIT 2.1.0-beta3 ====
make -C src
make[1]: вход в каталог «/cygdrive/c/users/ksash/luajit/src»
CC        lj_ffrecord.o
In file included from lj_ffrecord.c:1545:
lj_recdef.h:247:1: ошибка: «recff_rawlen» не описан здесь (не в функции); имелось в виду «recff_rawset»?
  247 | recff_rawlen,
      | ^~~~~~~~~~~~
      | recff_rawset
make[1]: *** [Makefile:689: lj_ffrecord.o] Error 1
make[1]: выход из каталога «/cygdrive/c/users/ksash/luajit/src»
make: *** [Makefile:117: default] Error 2

ksash@WIN-EKSJFRPE1RL /cygdrive/c/users/ksash/luajit
$

**Comment by MikePall** [comment]
You need to `make clean` before rebuilding, if you change anything in the Makefile.
