### ISSUE TITLE
Backport `coroutine.close` from Lua 5.4

### ISSUE THREAD

**Issue by ccuser44** [LuaJIT/LuaJIT#926]
The `coroutine.close` function should be backported to LuaJIT from Lua 5.4.
This would make working with coroutines easier and make backwards compatibility easier.
I am not sure though if Lua 5.4 features should be backported here

I couldn't find this from `lib_base.c` so I suspect it's not backported yet.

**Comment by MikePall** [comment]
This is pointless, since it would only close to-be-closed variables, which LuaJIT does not have (nor need).

**Comment by ccuser44** [comment]
> This is pointless, since it would only close to-be-closed variables, which LuaJIT does not have (nor need).

`coroutine.close` could be implemented with the same behavior expect that regarding to-be-closed variables.
Here is RFC of how the Lua dialect Luau implemented `coroutine.close:` [luau/rfcs/function-coroutine-close.md](https://github.com/Roblox/luau/blob/master/rfcs/function-coroutine-close.md)

**Comment by MikePall** [comment]
But the semantics of this are not useful. Whether a coroutine is declared dead or not resumed anymore is irrelevant for the VM.
If you consider the coroutine to be dead, then why bother calling a no-op function? Just remove the last reference to it and the GC will take care of it.

In other words, here's the full implementation (for your personal use):
```Lua
coroutine.close = function() end
```
