### ISSUE TITLE
Undefined behavior with negation of INT64_MIN

### ISSUE THREAD

**Issue by minoki** [LuaJIT/LuaJIT#928]
UBSanitizer detected some UBs regarding negation of `INT64_MIN`:

* [lj_carith.c:210](https://github.com/LuaJIT/LuaJIT/blob/8625eee71f16a3a780ec92bc303c17456efc7fb3/src/lj_carith.c#L210)
* [lj_ctype.c:585](https://github.com/LuaJIT/LuaJIT/blob/8625eee71f16a3a780ec92bc303c17456efc7fb3/src/lj_ctype.c#L585)
* [lj_parse.c:971](https://github.com/LuaJIT/LuaJIT/blob/8625eee71f16a3a780ec92bc303c17456efc7fb3/src/lj_parse.c#L971)
* [lj_strfmt.c:290](https://github.com/LuaJIT/LuaJIT/blob/8625eee71f16a3a780ec92bc303c17456efc7fb3/src/lj_strfmt.c#L290)

`git grep '(uint64_t)-'` reveals other occurrences of `(uint64_t)-(int64_t)x`.

They should be done in `uint64_t`.

Test code:

```lua
X=-9223372036854775808LL;print(X,-X);string.format("%d",X)
```

**Comment by MikePall** [comment]
Thanks! I found and fixed many more cases of this.

And a few of them did affect the code generated by the C compiler. E.g. the meaning of expressions like (k == -k) has completely changed in recent C compilers.
