### ISSUE TITLE
enhancement: Increase max jump length to stop LJ_ERR_XJUMP

### ISSUE THREAD

**Issue by TheGreatSageEqualToHeaven** [LuaJIT/LuaJIT#931]
Currently the max range that can be jumped is [65535](https://github.com/LuaJIT/LuaJIT/blob/7306ba78d62b55a64f25231df1d5697345a5572e/src/lj_bc.h#L28) and anymore will [error](https://github.com/LuaJIT/LuaJIT/blob/a04480e311f93d3ceb2f92549cad3fffa38250ef/src/lj_parse.c#L324).

I am using LuaJIT to automate devirtualization on large programs and some programs can't be run with LuaJIT due to the lower limit compared to PUC Lua. I believe this could be done by implementing a larger `E` register and `BCMAX_E` but I might be missing something.

**Comment by MikePall** [comment]
The limit cannot be raised easily. And the JIT compiler punts way earlier.
You need to make the generated code look more like human-written Lua code. Otherwise you won't get any benefit out of LuaJIT.
