### ISSUE TITLE
Android: Don't Check if C Module Shared Object is Readable

### ISSUE THREAD

**Issue by MikuAuahDark** [LuaJIT/LuaJIT#933]
https://github.com/LuaJIT/LuaJIT/blob/a04480e311f93d3ceb2f92549cad3fffa38250ef/src/lib_package.c#L328

In Android, a path like `/data/app/random_text/com.example.mypackage-random_text/base.apk!lib/arm64-v8a/module.so` can be loaded by Android `dlopen` when certain conditions are met but will fail at `readable` check.

Perhaps a simple `strstr(filename, ".apk!lib/")` would suffice but I havent' fully read the code for the other implication when `dlopen` fails.

**Comment by MikePall** [comment]
You might get away with that. But in general, it's not that simple to change the whole logic for module searching. Also, probing only with `dlopen()` can be very expensive.

I was under the impression that on mobile, embedded and console platforms one usually links LuaJIT and all bundled libraries into a single native binary, anyway. Which avoids that issue, of course.

**Comment by MikuAuahDark** [comment]
Yeah, but unfortunately linking to single massive binary in Android leads to #285 happening more often.
