### ISSUE TITLE
Return value of a function is dereferenced without checking for NULL, but it is usually checked for this function

### ISSUE THREAD

**Issue by ProjectMutilation** [LuaJIT/LuaJIT#949]
Hi! I found suspicious snippet of code
https://github.com/LuaJIT/LuaJIT/blob/d0e88930ddde28ff662503f9f20facf34f7265aa/src/lj_vmevent.c#L23
  https://github.com/LuaJIT/LuaJIT/blob/d0e88930ddde28ff662503f9f20facf34f7265aa/src/lj_vmevent.c#L24
Usually res of lj_tab_getstr checked against null ptr  
For example,  
```
    o = lj_tab_getstr(fs->kt, lj_str_newlit(ls->L, "next"));
    if (o && tvhaskslot(o) && tvkslot(o) == bc_d(ins))

```
Сan you tell me if the check is not required here or if it was skipped by mistake?

**Comment by MikePall** [comment]
The check is not required here. Arguably this is a bit non-obvious:
* `lj_vmevent_prepare()` is only called via the `lj_vmevent_send()` macro.
* This macro checks for a non-zero bit in `g->vmevmask`.
* The bitmask is only set by `lj_cf_jit_attach()` (`jit_attach` in `lib_jit.c`) *after* using `luaL_findtable()`.
* This function makes sure the string key exists in the table.

**Comment by ProjectMutilation** [comment]
@MikePall thanks!
