### ISSUE TITLE
FFI `ffi.typeof("struct $", DYNAMIC_NAME)` parameterised types does not work

### ISSUE THREAD

**Issue by folays** [LuaJIT/LuaJIT#950]
Tested on latest branch v2.1 (`d0e8893`) and some previous `e3bae12` from last July ;

```
> ffi.cdef("struct $", "MyStruct") -- forward declaration

> print(ffi.typeof("struct MyStruct"))
ctype<struct MyStruct>

> print(ffi.typeof("struct $", "MyStruct"))
stdin:1: undeclared or implicit tag 'MyStruct'
stack traceback:
	[C]: in function 'typeof'
	stdin:1: in main chunk
	[C]: at 0x010b6e5afc
```

My point is that I am **defining** some structs dynamically.
To handle cyclic loops (some deep struct having a pointer to one of its "ancestors"), I :
- I forward **declare** any struct encountered (let's say `MyStructA`) with `ffi.cdef("struct $", DYNAMIC_NAME)`
- I _WISH_ to set `table[DYNAMIC_NAME] = ffi.typeof("struct $", DYNAMIC_NAME)`
- I loop on all `MyStructA` members to build the `DYNAMIC_DEFINITION` of the struct which I will have to `ffi.cdef()` later.
  - One of its member has a pointer to `MyStructB` so I recursively start again with `MyStructB`
    - One of its member has a pointer to `MyStructC` so I recursively start again with `MyStructC`
      - One of its member has a pointer to `MyStructA`, so I skip the infinite recursion by returning `table[MyStructA]`
- I finish to "figure out" the definition of `MyStructA`, so I prepare (via some `sprintf()`-alike) the "inside-{}" definition
- I **define** `MyStructA` with its "complete" definition from above via `ffi.cdef("struct $ { DYNAMIC_DEFINITION }", "MyStructA", unpack(DYNAMIC_LIST_OF_CTYPES))`

Above the `DYNAMIC_DEFINITION` would contains some `$` so that's why I `unpack(DYNAMIC_LIST_OF_CTYPES)` to provide them to `ffi.cdef()`.

--

That works well because I can just replace `ffi.typeof("struct $", DYNAMIC_NAME)` with `ffi.typeof(sprintf("struct %s", DYNAMIC_NAME))`.

But would `ffi.typeof()` should not have the same semantics than `ffi.cdef()` ?

http://luajit.org/ext_ffi_semantics.html
> PARAMETERIZED TYPES
>
> [...]  the two functions `ffi.typeof` and `ffi.cdef` support parameterized types in C declarations.
> Any place you can write a :
> - typedef name,
> - an identifier,
> - or a number in a declaration,
> you can write $ (the dollar sign) instead. [...]
>
> Caveat: this is not simple text substitution! :
> - A passed ctype or cdata object is treated like the underlying type,
> - a passed string is considered an identifier
> - and a number is considered a number.

So I would expect my `ffi.typeof("struct $", DYNAMIC_NAME)` to be valid ?

Thanks.

Kind Regards,

**Comment by MikePall** [comment]
`ffi.typeof()` *does* support parameterized types. But it doesn't support implicit tags, since the result must be a finished type.
Use anonymous structs instead:
```Lua
local ffi = require("ffi")
local struct_a = ffi.typeof("struct { int x; }")
local struct_b = ffi.typeof("struct { $ *ptr_a; }", struct_a)
local a = ffi.new(struct_a, 42)
local b = ffi.new(struct_b, a)
print(b.ptr_a.x) --> 42
```
