### ISSUE TITLE
64bit struct Bit Fields invalid value near ':'

### ISSUE THREAD

**Issue by baby0o01999** [LuaJIT/LuaJIT#951]
```lua
local ffi = require("ffi")

ffi.cdef[[
typedef union{
    uint64_t u;
    int64_t s;
    struct
    {
        uint64_t offset:12;--error invalid value near ':' at line 6
        uint64_t pt_index:9;
        uint64_t pd_index:9;
        uint64_t pdpt_index:9;
        uint64_t pml4_index:9;     
    }u;
} IA64_LIN_ADDR;
]]
```

Whether 64-bit Fields are supported

**Comment by MikePall** [comment]
64 bit bitfields are a GCC/Clang extension to C99 and the FFI has no support for it (at this time).

**Comment by jgouly** [comment]
Having support for this would fix running neovim unittests on macOS 14 (which would give arm64 coverage in CI).

`mach/vm_types.h` has structs with bitfields that can't be parsed:
```
    typedef struct {
    	mach_vm_range_flags_t   flags: 48;
```

On a similar note, it also has enum definitions of the form:
```
    typedef enum : uint32 {
```
This is a C++11 feature which Clang supports in C as an extension. There doesn't seem to be a flag to disable that, but it can be hacked around by #define-ing __has_extension.

**Comment by MikePall** [comment]
I've added this to the v3.0 wishlist.
