### ISSUE TITLE
Trace stitching crash issue

### ISSUE THREAD

**Issue by Vladislavik36** [LuaJIT/LuaJIT#952]
Hello. I have encountered an issue with the LuaJIT 2.1.0 beta 3 on the MSVC x86.
```
lua_State* L = luaL_newstate();
void __fastcall TestFunc(int idx) {
    lua_getglobal(L, "print");
    lua_pushnumber(L, 12345);
    lua_call(L, 1, 0);
}
static auto test_fn_addr = &TestFunc;
int main()
{
    luaL_openlibs(L);

    std::string code = R"#(
        local ffi = require("ffi")
        local fn = ffi.cast("void(__fastcall**)(int)", fn_ptr)
        local ofunc = fn[0]

        function hook_fn()
            ofunc(4565)
        end
        
        fn[0] = ffi.cast("void(__fastcall*)(int)", hook_fn)
    )#";

    lua_pushlightuserdata(L, &test_fn_addr);
    lua_setglobal(L, "fn_ptr");

    luaL_loadbufferx(L, code.data(), code.size(), nullptr, nullptr);
    lua_call(L, 0, 1);

    while(true)
        test_fn_addr(555);
}
```
Description: Lua script attempts to hook the native C++ function that calls the lua:print function

The provided snippet causes the application to crash after a few "test_fn_addr" function calls.

![image](https://user-images.githubusercontent.com/24935177/215544640-a4b2510e-bcbb-431b-9737-33323c7726fa.png)

The crash seems to be gone after disabling the trace stiching (by setting "minstitch": 1000). Also, it's not a thing in the LuaJIT 2.0.5, because there's no trace stitching.

**Comment by XmiliaH** [comment]
It is not allowed to call into LuaJIT from a FFI call with callbacks being the only exception (see http://lua-users.org/lists/lua-l/2011-10/msg01075.html).
The `TestFunc` is violating this requirement and so crashes should be expected.
