### ISSUE TITLE
compile error if not enable '#XCFLAGS+= -DLUAJIT_ENABLE_LUA52COMPAT'

### ISSUE THREAD

**Issue by elmknot** [LuaJIT/LuaJIT#953]
linux version:CentOS Linux release 7.9.2009 (Core)
gcc output:
==================================================
In file included from lj_ffrecord.c:1545:0:
lj_recdef.h:247:1: error: ‘recff_rawlen’ undeclared here (not in a function)
 recff_rawlen,
 ^
make[1]: *** [lj_ffrecord.o] Error 1

**Comment by MikePall** [comment]
You need to `make clean` if you pass different flags or change anything in the Makefile.
