### ISSUE TITLE
Encode all SSE instructions using VEX prefix if applicable

### ISSUE THREAD

**Issue by MarioSieg** [LuaJIT/LuaJIT#955]
Since the AVX instruction set on AMD-64 these is a new encoding scheme called VEX (vector extension).
The VEX encoding is already used by LuaJIT to encode BMI 2 instructions such as RORX or SARX:
XV_660f38
XV_f20f38
etc..
The VEX encoding allows non destructive 3-operand code where the source register != destination register:
vaddss %xmm0, %xmm0, %xmm1
This lowers the register pressure and allows for more flexibility.

I would be interested to modify the x86 code generator that,
all SSE instructions are encoded in the 3-operand VEX form if  CPUID  >= AVX is detected at runtime,
which removes pressure from the register allocator.
see: https://fgiesen.wordpress.com/2013/03/13/extra-registers-and-3-operand-instructions/

Because we still use no ymm* regs we do not need to care about SSE-AVX transitions penalties or dirty upper states (vzeroupper).

I would like to know if this implementation would be welcome or not?
@MikePall

**Comment by MikePall** [comment]
Yes, I might take such a change. Though I'm not convinced it will make a measurable difference. The register allocator handles 2-operand constraints pretty well. We'll find out.
Note that the minimum requirement is AVX2 (and not AVX), because of the use of doubles.

**Comment by MarioSieg** [comment]
> Yes, I might take such a change. Though I'm not convinced it will make a measurable difference. The register allocator handles 2-operand constraints pretty well. We'll find out. Note that the minimum requirement is AVX2 (and not AVX), because of the use of doubles.

Alright nice :)
Yeah the difference needs to be measured.
I'll do some tests with hand-written assembler...
Will start the implementation then over the next weeks - have to write my thesis currently.
Also I think that we don't need AVX 2?
https://docs.oracle.com/cd/E36784_01/html/E36859/gntbd.html#scrolltoc
There are IEEE 754-binary double precision instructions in AVX 1 such as:
vaddsd
VEX ADD SCALAR DOUBLE
AVX 2 just expands with many packaged integer instructions and AVX allows most SSE* {2,3,41,42 etc..) instructions
in 3-operand form.

I'll come back to you when I have some tests.

**Comment by MarioSieg** [comment]
<h2> So the general implementation is done: </h2>

![image](https://user-images.githubusercontent.com/49988901/217932771-9b462328-8a2d-4c7a-8dc3-b016ab9ecd17.png)

What I've done so far:
Patch all SSE instructions to 3-byte VEX instructions, if a macro is set (current compile time, will be runtime).
Add additional information to the SSE opcodes if an instruction has 3 opcodes in VEX mode or not.
(See code below or in my [fork](https://github.com/MarioSieg/LuaJIT/blob/amd64-sse2vex/src/lj_target_x86.h)).

But a couple of things need to be done by me:
* Test the correctness of ALL opcodes
* Use 2-byte VEX if applicable - results in smaller code size and less icache usage
* Use the VEX encoding if AVX is detected at runtime - maybe add a flag to disable it?
* Adjust the register allocator to use the 3rd operand. Not ALL instructions use the 3rd operand tough.

@MikePall while I'm doing the rest would have an good idea on how to implement the 3rd operand handling into the register allocator?

if we have done that, we can see the actual performance benefits.

Best Regards from Germany too,

Mario


Some code if you are interested:

Additional opcode info using XOR "encryption" - could be replacted by a specific bit set:

```c
/*
  Construct VLA SSE/AVX opcodes.
  `v3` = AVX_VEX_3_OPERANDS means that the instruction can have 3 operands when encoded using VEX. e.g. vaddsd %xmm0, %xmm0, %xmm1
  `v3` = AVX_VEX_2_OPERANDS means that instruction has 2 operands. e.g. vmovaps %xmm0, %xmm1
*/
#define XO_SSEAVX_0f(o, v3)	  ((uint32_t)((0x0f00fd^v3)|(0x##o<<24)))
#define XO_SSEAVX_660f(o, v3)	((uint32_t)((0x0f66fc^v3)|(0x##o<<24)))
#define XO_SSEAVX_f20f(o, v3)	((uint32_t)((0x0ff2fc^v3)|(0x##o<<24)))
#define XO_SSEAVX_f30f(o, v3)	((uint32_t)((0x0ff3fc^v3)|(0x##o<<24)))
```

SSE to VEX patcher:
```c
#define PREFER_VEX 1 /* currently compile time only - encode all SSE instructions using VEX prefix */

/* pack 2-bybte vex prefix fields: r = ~REX.R, vvvv = regs, l = 256-bit ? 1 : 0, pp = opcode ext */
#define PACK_VEX2(r,vvvv,l,pp) (uint16_t)((0xc5<<8)|(((r)&1)<<7)|(((vvvv)&15)<<3)|(((l)&1)<<2)|(((pp)&3)))

/* pack 3-byte vex prefix fields: r = ~REX.R, x = ~REX.X, b = ~REX.B, m-mmmm = opcode bytes, w = ~REX.W, vvvv = regs, l = 256-bit ? 1 : 0, pp = opcode ext */
#define PACK_VEX3(r,x,b,m_mmmm,w,vvvv,l,pp) (uint32_t)((0xc4<<16)|(((((r)&1)<<7)|(((x)&1)<<6)|(((b)&1)<<5)|((m_mmmm)&3))<<8)|(PACK_VEX2(w,vvvv,l,pp)&0xff))

static LJ_AINLINE int sse2vex_patch(x86Op *xo, Reg rr, Reg rb, Reg rx, MCode **mpx)
{
  int n = (int8_t)*xo; /* extract count and VEX marker in our case */
  int v3 = 0;
  if (n == -13 || n == -14) { /* -(len+1) ^ AVX_VEX_3_OPERANDS */
      *xo ^= AVX_VEX_3_OPERANDS; /* clear VEX marker - revert original value */
      v3 = 1;
#if !PREFER_VEX
      return 0;
#endif
  } else if (n != -3 && n != -4) {
    return 0;
  }
#if !PREFER_VEX
    return 0;
#endif
  MCode *p = *mpx;
  if (((*xo >> 16) & 0xff) != 0x0f) return 0; /* no SSE instructions*/
  MCode opc = (*xo>>24) & 0xff;  /* store opcode */
  /* some vex encoded VMOV* scalar instructions merge instead of move, so we don't encode them with VEX as they don't have the same semantic.
  ** MOVSD xmm1, xmm2 -> Move scalar double-precision floating-point value from xmm2 to xmm1 register.
  ** VMOVSD xmm1, xmm2, xmm3 	-> Merge scalar double-precision floating-point value from xmm2 and xmm3 to xmm1 register. <- MEH we don't want this
  ** Only scalar/low moves affected e.g. movaps and friends are not affected!
  ** so let's check agains them and exclude:
  */
  MCode pp = (*xo>>8) & 0xff;    /* store SSE mode prefix */
  uint32_t rex = 0x40|((rr>>1)&(4|(FORCE_REX>>1)))|((rx>>2)&2)|((rb>>3)&1); /* pack default long-mode REX prefix */
  switch (pp) { /* create compressed VEX.pp field value */
    case 0x66: pp = 1; break;
    case 0xf3: pp = 2; break;
    case 0xf2: pp = 3; break;
    default:   pp = 0; break;
  }
  MCode vvvv = v3 ? ~rr & 0xf : 0xf;
  uint32_t vex3 = PACK_VEX3(
    ~((rex>>2)&1),  // ~REX.r
    ~((rex>>1)&1),  // ~REX.x
    ~((rex>>0)&1),  // ~REX.B
    1,              // m_mmmm
    0,              // W
    vvvv,           // vvvv = regs
    0,              // 128-bit vector length
    pp              // opcode prefix type
  );
  vex3 = lj_bswap((vex3<<8)|opc);
  *(uint32_t *)(p - 5) = vex3;
  p -= 5;
  *mpx = p;
  return 1;
}
```

**Comment by MikePall** [comment]
Umm, I wouldn't mind regular conditionals to emit the different code paths. There are not that many places that emit (relevant) FP ops. On a quick grep I found ~13. While a post-fixup step is really cool from an implementation perspective, I think this won't lead to a full solution.
The 2-operand magic in the register allocator is in `ra_left()`. For the 3-operand archs, there's `ra_leftov()` and `ra_alloc2()`. The latter should really be unified and moved to common code (I'll do that on the merge, just copy the code for now).
I suggest to compare `asm_fparith()` for x86/x64 vs. ARM64.

**Comment by MikePall** [comment]
I think the best would be a complete rewrite to convert the x86/x64 interpreter and JIT-compiler backend to AVX only. However this will have to wait until after 3.0. There are still too many non-AVX CPUs running. Closing here.
