### ISSUE TITLE
How to use .capture and .dumpcapture in dynasm

### ISSUE THREAD

**Issue by PeterYang12** [LuaJIT/LuaJIT#958]
Could you give me some examples how to use .capture and .dumpcapture these directives? I couldn't find useful example, since I want to dump some information about jitted code.

**Comment by MikePall** [comment]
This is a misunderstanding. These directives are for capturing code into separate sections.

If you want to inspect the JIT-generated code, you could:
1. Dump it to a file and then use `objdump -b binary -D`
2. Link a disassembler C library (there are many) and run it for each generated code segment.
3. Use one of the disassemblers from LuaJIT. But they are written in Lua, so you'd need to link to it, too. This is essentially what the `-jdump` option of LuaJIT does.

**Comment by PeterYang12** [comment]
Thank you!
