### ISSUE TITLE
what commit fixed this error?

### ISSUE THREAD

**Issue by OldWorldOrdr** [LuaJIT/LuaJIT#959]
when I cross compile 2.1.0-beta3 for iOS 3 (jailbroken) and enable JIT for iOS with `TARGET_CFLAGS="-DLUAJIT_ENABLE_JIT"` I get a bunch of these errors:
```
./lj_dispatch.h:103:31: error: ‘GG_State’ has no member named ‘J’
```
however, when i build the latest git version I don't get the errors, since I'm shipping this in a public repo I would like to use a stableish version, not a git version, so I would like to know the commit that fixed this particular error so I can apply just that commit to the 2.1.0-beta3 source.

**Comment by MikePall** [comment]
The JIT-compiler backend doesn't work properly for iOS, anyway. Don't enable it.
Also, see [this page](https://luajit.org/download.html), which tells you to use the git version in any case.

**Comment by OldWorldOrdr** [comment]
> The JIT-compiler backend doesn't work properly for iOS, anyway. Don't enable it.

it does if you're jailbroken
