### ISSUE TITLE
Distinguish BSDs

### ISSUE THREAD

**Issue by moon-chilled** [LuaJIT/LuaJIT#960]
jit.os/ffi.os is simply 'BSD' on any bsd-like operating system.  It should be possible for code to tell which OS it's actually running on.

**Comment by MikePall** [comment]
This would break compatibility. Call e.g. `uname()` via the FFI, if you need to know details about your OS.

**Comment by moon-chilled** [comment]
For compatibility, how about giving it a separate name (eg os_full)?
