### ISSUE TITLE
Is the clone syscall valid for use by ffi?

### ISSUE THREAD

**Issue by 1lumin** [LuaJIT/LuaJIT#963]
I am experiencing some intermittent segfaults in a LuaJIT application which only occur when JIT is enabled.

I suspect that the root of the unexpected behavior is due to a clone call with the stack pointer in particular being of interest since I do not know if LuaJIT expects the stack to have a certain layout.

Below is a code snippet of the clone call I am mentioning:
```lua
local ffi = require "ffi"

ffi.cdef[[
    typedef struct {
        char stack[4096] __attribute__ ((aligned(16)));
        char ptr[0];
    } clone_stack;

    int clone(int (*fn)(void *), void *stack, int flags, void *arg);
    int waitpid(int pid, int *status, int options);
]]

function context(indata)
    return 0
end

local stack = ffi.new("clone_stack")
local pid = ffi.C.clone(context, stack.ptr, 17, nil)

local status = ffi.new("int[1]", 0)
ffi.C.waitpid(pid, status, 0)
```
(The reason I must use clone instead of fork is to be able to access the flags which are not exposed in fork)

The actual segfault in my application happens because of a premature garbage collection of a `ffi.new("char[1000]")` when the offending code is run within a clone context similar to the above.

Is the above code invalid or should I look elsewhere for the root cause?

**Comment by tsafin** [comment]
My bet that in the cases when `local stack = ffi.new("clone_stack")` is not allocating 16-byte aligned (but rather 8-byte aligned) you have problems. You may check with `mmap` (which is guaranteed to be 4K-aligned).

**Comment by MikePall** [comment]
The child needs to anchor the Lua object that holds the stack. Umm ... and this is a rather small piece of memory and not a growable stack map, which may cause issues later on.
Anyway, I think you're better off using the underlying `clone` syscall. This works just like `fork()` -- it returns back to the caller in the child and the stack argument can be NULL.
The libc `clone()` wrapper does all of the stack and callback stuff, which only complicates matters. Check the `clone` man page for details. Note that `__NR_clone` depends on the target architecture (56 for x64).

**Comment by MikePall** [comment]
> My bet that in the cases when `local stack = ffi.new("clone_stack")` is not allocating 16-byte aligned (but rather 8-byte aligned) you have problems. You may check with `mmap` (which is guaranteed to be 4K-aligned).

Nope, `ffi.new()` *does* respect the alignment. But 4K is small and not growable.
