### ISSUE TITLE
Bytecode determinism

### ISSUE THREAD

**Issue by huachangmiao** [LuaJIT/LuaJIT#966]
I use lastest version.
The result of compiling the binary is different every time.
v2.1.0-beta3 2017.5.2 is correct.

**Comment by huachangmiao** [comment]
local battleInfo = 
    {
        time = 0,
        frame = 0,
        maxhp1 = 0,
        maxhp2 = 0,
        hp1 = 0,
        hp2 = 0,
        aliveAgent1 = 0,
        aliveAgent2 = 0,
    }
init a lua table like this.

**Comment by MikePall** [comment]
There is no guarantee for deterministic bytecode generation, because [table iteration order is undefined](http://luajit.org/faq.html#order). This is not a bug.
