### ISSUE TITLE
Incompatible bytecode error

### ISSUE THREAD

**Issue by Source61** [LuaJIT/LuaJIT#967]
Hey.

Ever since I upgraded LuaJIT on my debian 12 WSL distro about 6-9 months ago I started getting this error: incompatible bytecode.
I'm running a modified version of https://github.com/edubart/otclient/ but with the same (untouched) Lua/LuaJIT system.
I didn't do any changes to my client at the time that could have caused this in my estimation.
I've had no issues for years, but started getting this error 6-9 months ago.

When Googling I found that some other people had the same issue with neovim in 2022 around the same time, no other relevant mentions that I could find.

How to reproduce:
* Compile otclient.
* Compile the bytecode of any lua module such as /modules/corelib/math.lua and overwrite the uncompiled module using LuaJIT 2.1.0-beta3 (Debian Bookworm) -t raw.
* Run otclient.exe or otclient ELF depending on which OS you compiled the client for and check otclient.log when the client fails to load.

**Comment by GitSparTV** [comment]
Make sure they all have the same LuaJIT version and architecture

**Comment by sonoro1234** [comment]
It seems an otclient issue!!!

**Comment by Source61** [comment]
> Make sure they all have the same LuaJIT version and architecture

I forgot about upgrading the vcpkg libraries.
I've upgraded everything now and unfortunately it didn't help. I also have the latest LuaJIT version that Debian 12 (testing) distributes.
Otclient is compiled to a x86 binary, so I've tried -a x86 and -o windows. It hasn't helped any :/

**Comment by Source61** [comment]
> Did you file an issue to Otclient?

Yes, sort of. I wrote about it on the forums (otland.net) a few months ago, no response.
OTLand is the forums that all the developers hang out at, most people don't use github/edubart/otclient anymore because its maintainer is not serious and otclient isn't actively maintained anymore so there's almost no point filing an issue there.
However it's solidly built and code doesn't deprecate in many years without changes, except for this LuaJIT issue.

I will file an issue there just in case, but I doubt much will come from it unfortunately.

**Comment by fengyd2006** [comment]
> Make sure they all have the same LuaJIT version and architecture

It means that the bytecode compiled on x64 cannot be executed on arm?
