### ISSUE TITLE
[Syntax Extensions] #...

### ISSUE THREAD

**Issue by SoniEx2** [LuaJIT/LuaJIT#97]
`#...` should emit an opcode which returns the number of varargs. `select('#',...)` should use `#...` internally.

**Comment by daurnimator** [comment]
please no; this sort of request should go via normal lua first.

**Comment by corsix** [comment]
For a start, `#...` already has a meaning, and so any change of meaning would break language semantics:
```
> function f(...) return #... end
> =f("hello")
5
```

**Comment by SoniEx2** [comment]
Oh, I thought that errored... Oh well :/
