### ISSUE TITLE
LuaJIT asks allocator for "invalid next size"

### ISSUE THREAD

**Issue by 1lumin** [LuaJIT/LuaJIT#974]
Around 8 seconds after launching a relatively large LuaJIT application a segmentation faults occurred with a default LuaJIT build. Recompiling with `-DLUAJIT_USE_SYSMALLOC` stopped the segfaults from happening but on rare occasion runs would produce an error of `malloc(): invalid next size (unsorted)` at around the same time that the segfaults were happening. The application does make use of FFI but every ffi.new that is used has a fixed size or is using default C size.

Is it possible that the memory limit is being exceeded even though "not enough memory" is not hit or could this be something else?

**Comment by MikePall** [comment]
The message from malloc indicates a buffer overrun, i.e. you're overwriting unrelated memory with the FFI. Check for off-by-one errors.
