### ISSUE TITLE
Mismatching -0 and 0 IR constants in load forwarding

### ISSUE THREAD

**Issue by Buristan** [LuaJIT/LuaJIT#981]
This issue is a follow-up for the commit 1e6e8aaa20626ac94cf907c69b0452f76e9f5fa5 ("Fix narrowing of unary minus.").
Since this commit -0 is stored as well as 0 IR constant.

The problem was originally reported by @ligurio.

The following code leads to the assetion failure.

```sh
LUA_PATH="src/?.lua;;" src/luajit -jdump=i -Ohotloop=1 -e '
local r
for _ = 1, 4 do
  r = ({[-0] = "x", k = "v"})[0]
end
'
---- TRACE 1 start (command line):3
LuaJIT ASSERT lj_opt_mem.c:226: fwd_ahload: mismatched type in constant table
Aborted
```

As far as -0 isn't folding to 0 (see [`bcemit_unop()` in `<src/lj_parse.c>`](https://github.com/LuaJIT/LuaJIT/blob/505e2c03de35e2718eef0d2d3660712e06dadf1f/src/lj_parse.c#L975)), resulting table template has no 0 field initiated. It is set via the following bytecode:
```
0006 => TDUP     5   1
0007    KSHORT   6   0
0008    UNM      6   6
0009    KSTR     7   0      ; "x"
0010    TSETV    7   5   6
```

Same time, during recording -0 initialization is equal to the `p64 NEWREF 0002 -0` and loading by 0 index is implemented via `p64 HREFK  0010 +0`. Since -0 and 0 are different IR constants [alias analysis declares that they can't be aliased](https://github.com/LuaJIT/LuaJIT/blob/505e2c03de35e2718eef0d2d3660712e06dadf1f/src/lj_opt_mem.c#L126) and misses the NEWREF by -0 index, leading to the aforementioned assertion failure.

The similar case with `IR_TNEW` instead `IR_TDUP` doesn't lead to assertion due to the d4c0c6e17ef7edf1f2893bc807746b80612e63e9 ("Fix TNEW load forwarding with instable types."), but the -0 NEWREF is still occuring in the `jit.dump()`:
```sh
LUA_PATH="src/?.lua;;" src/luajit -jdump=i -Ohotloop=1 -e '
local r
for _ = 1, 4 do
  r = ({[-0] = "x",})[0]
end
'
```

<details>
  <summary> jit.dump() output for TNEW </summary>

```
---- TRACE 1 start (command line):3
---- TRACE 1 IR
0001    int SLOAD  #3    CI
0002 >  tab TNEW   #0    #1  
0004    p64 NEWREF 0002  -0  
0005    str HSTORE 0004  "x" 
0006    int FLOAD  0002  tab.asize
0007 >  int ULE    0006  +0  
0008    int FLOAD  0002  tab.hmask
0009 >  int EQ     0008  +1  
0010    p64 FLOAD  0002  tab.node
0011 >  p64 HREFK  0010  +0   @0
0012 >+ str HLOAD  0011
0013  + int ADD    0001  +1  
0014 >  int LE     0013  +4  
0015 ------ LOOP ------------
0016 >  tab TNEW   #0    #1  
0017    p64 NEWREF 0016  -0  
0018    str HSTORE 0017  "x" 
0019    int FLOAD  0016  tab.asize
0020 >  int ULE    0019  +0  
0021    int FLOAD  0016  tab.hmask
0022 >  int EQ     0021  +1  
0023    p64 FLOAD  0016  tab.node
0024 >  p64 HREFK  0023  +0   @0
0025 >+ str HLOAD  0024
0026  + int ADD    0013  +1  
0027 >  int LE     0026  +4  
0028    int PHI    0013  0026
0029    str PHI    0012  0025
---- TRACE 1 stop -> loop
```
</details>

[During indexed key lookup recording](https://github.com/LuaJIT/LuaJIT/blob/505e2c03de35e2718eef0d2d3660712e06dadf1f/src/lj_record.c#L1427) +-0 is canonicalized to +0, but this TRef doesn't update `ix->key`, which [is used again](https://github.com/LuaJIT/LuaJIT/blob/505e2c03de35e2718eef0d2d3660712e06dadf1f/src/lj_record.c#L1600) without canonicalization.

<details>
  <summary> Suggested patch: </summary>

IINM, `ix->key` is mostly kept the same (I found 3 places where it is changed) as at the moment of initialization, so I suggest the following patch:

```diff
diff --git a/src/lj_record.c b/src/lj_record.c
index 79ee6172..7fb10885 100644
--- a/src/lj_record.c
+++ b/src/lj_record.c
@@ -1598,7 +1598,9 @@ TRef lj_record_idx(jit_State *J, RecordIndex *ix)
       lj_assertJ(!hasmm, "inconsistent metamethod handling");
       if (oldv == niltvg(J2G(J))) {  /* Need to insert a new key. */
         TRef key = ix->key;
-        if (tref_isinteger(key))  /* NEWREF needs a TValue as a key. */
+        if (tref_isnumber(key) && numberVint(&ix->keyv) == 0 && tref_isk(key))
+          key = lj_ir_knum_zero(J);  /* Canonicalize 0 or +-0.0 to +0.0. */
+        else if (tref_isinteger(key))  /* NEWREF needs a TValue as a key. */
           key = emitir(IRTN(IR_CONV), key, IRCONV_NUM_INT);
         xref = emitir(IRT(IR_NEWREF, IRT_PGC), ix->tab, key);
         keybarrier = 0;  /* NEWREF already takes care of the key barrier. */
```
</details>

<details>
  <summary> IR dump after patch: </summary>

```
---- TRACE 1 start (command line):3
---- TRACE 1 IR
0001    int SLOAD  #3    CI
0002 >  tab TDUP   {0x7fd5a7002478}
0004    p64 NEWREF 0002  +0  
0005    str HSTORE 0004  "x" 
0006    int FLOAD  0002  tab.asize
0007 >  int ULE    0006  +0  
0008  + int ADD    0001  +1  
0009 >  int LE     0008  +4  
0010 ------ LOOP ------------
0011 >  tab TDUP   {0x7fd5a7002478}
0012    p64 NEWREF 0011  +0  
0013    str HSTORE 0012  "x" 
0014    int FLOAD  0011  tab.asize
0015 >  int ULE    0014  +0  
0016  + int ADD    0008  +1  
0017 >  int LE     0016  +4  
0018    int PHI    0008  0016
---- TRACE 1 stop -> loop
```

Dump for `IR_TNEW` is the same (just TDUP is changed to the TNEW).
</details>

Issue #980 demonstrates the same assertion, but for a different reason.

**Comment by MikePall** [comment]
Fixed. Thanks!
