### ISSUE TITLE
luajit with uWSGI/WSAPI not working anymore after ~ April changes

### ISSUE THREAD

**Issue by poznir** [LuaJIT/LuaJIT#985]
when running uWSGI (compiled with luajit support) loading lua (WSAPI) app fails (worked perfectly before).
even the simplest app from uWSGI websites example, with command line fails with:

"Can't find WSAPI entry point (no function, nor a table with function'run')."

when taking older version before april, everything works,
1. i have to say i do not use the latest versions of uwsgi or wsapi, but i did used the latest luajit 2.1 branch
2. mac m1 pro, in docker env.

**Comment by MikePall** [comment]
Nobody here is going to debug third-party applications.

**Comment by poznir** [comment]
@MikePall 
Sure i understand
