### ISSUE TITLE
error: “bad light userdata pointer” On AArch64 when Enable Memory Tagging Extension  feature

### ISSUE THREAD

**Issue by OttoX** [LuaJIT/LuaJIT#986]
```
void *lj_lightud_intern(lua_State *L, void *p)
{
  global_State *g = G(L);
  uint64_t u = (uint64_t)p;
  uint32_t up = lightudup(u);
  uint32_t *segmap = mref(g->gc.lightudseg, uint32_t);
  MSize segnum = g->gc.lightudnum;
  if (segmap) {
    MSize seg;
    for (seg = 0; seg <= segnum; seg++)
      if (segmap[seg] == up)  /* Fast path. */
	return (void *)(((uint64_t)seg << LJ_LIGHTUD_BITS_LO) | lightudlo(u));
    segnum++;
    /* Leave last segment unused to avoid clash with ITERN key. */
    if (segnum >= (1 << LJ_LIGHTUD_BITS_SEG)-1) lj_err_msg(L, LJ_ERR_BADLU);
  }
  if (!((segnum-1) & segnum) && segnum != 1) {
    lj_mem_reallocvec(L, segmap, segnum, segnum ? 2*segnum : 2u, uint32_t);
    setmref(g->gc.lightudseg, segmap);
  }
  g->gc.lightudnum = segnum;
  segmap[segnum] = up;
  return (void *)(((uint64_t)segnum << LJ_LIGHTUD_BITS_LO) | lightudlo(u));
}
```

On AArch64 when enable MTE, it will result in many different up-tag value for the virtual address of memory and It will cause the value of segnum to quickly increase to 254，then raise the error  LJ_ERR_BADLU.
is there a correct way to fix this issue?

**Comment by MikePall** [comment]
Do not use lightuserdata. It's a remnant of the classic Lua/C API. It's slow, has very limited applications and any use of it prevents JIT compilation. The FFI provides a much better API and it has no issues with full 64 bit pointers.
OpenResty should have migrated away from lightuserdata for a long time. There's zero reason they still keep using it.

**Comment by elmknot** [comment]
I'm having the same issue too.
