### ISSUE TITLE
Hitting a limit on accessing unique structs with ffi, table overflow error

### ISSUE THREAD

**Issue by davidcpayette** [LuaJIT/LuaJIT#987]
When using `ffi.cdef` while working with a large struct of structs, there seems to be a limit to how many of those structs can be uniquely accessed. There also seems to be a limit to how big a single `ffi.cdef` struct can be (it appears to be 21,813 structs in a single big struct), and, conversely, a limit to how many times we can pass single structs to `ffi.cdef`, one at a time (in an attempt to circumvent the previous limit), which appears to be 32,720. 

If we make a big struct of structs that doesn't exceed the 21,813 struct limit, say 20,000 structs in a single big struct, then there seems to be a limit on how many unique structs we can access before hitting a table overflow error. 

Here's an example code that when run with the most recent luajit, throws a table overflow error:

```lua 
local ffi = require 'ffi'
local structs = {}
local numstructs = 20000

--create a table of strings each representing a different struct titled test..i 
for i = 1, numstructs do 
  structs[#structs + 1] = [[struct {
    int16_t value;
  } test]]..i..';'
end

--concatenate all the structs into a big struct 
local big = [[typedef struct big {
]]..table.concat(structs, '\n')..[[
} big_t;]]

ffi.cdef(big) --this call throws a table overflow at 21,813 structs 

local struct = ffi.new('big_t')

for i = 1, 20000 do --accessing the same struct 20000 times does not throw an error
  local str = struct['test1']
end

for i = 1, 5438 do --accessing 5,438 unique structs throws a table overflow error, 5437 does not
  local str = struct['test'..i]
end
```

Are these limits expected? Splitting the big struct of structs into smaller groups does not solve the issue with a table overflow on unique access.

**Comment by MikePall** [comment]
There are various limits in the FFI, but they rarely affect real-world use cases. This looks like some synthetic test.

That said, unique structs are distinct types and not assignment-compatible. Neither in C nor in the FFI. It's pointless and wasteful to create different structs with identical fields. Also, the JIT compiler specializes to each type, which means you wouldn't get any benefit of using LuaJIT at all.

**Comment by davidcpayette** [comment]
You're right this is a synthetic test, but we did hit this barrier in our real-world use case. This was just an effort to show the simplest possible example that hits this limit, but our use case is more complex than this, and our structs do use different fields, and this limit is a big problem for us.

**Comment by MikePall** [comment]
You still haven't explained *why* you'd want tens of thousands of structs (at the same time). And *what* you're doing with them in the Lua code. Then I might be able to help you.

**Comment by davidcpayette** [comment]
The struct of structs represents the state of a system that has thousands of individual pieces that need be tracked. The state is represented in Lua tables, but then shared via shared memory. The data is marshalled between the Lua tables and the struct. The struct was used because it was easier than serialization, not for a performance benefit. We just didn't expect to hit a limit like this so soon.

**Comment by matthewburk** [comment]
What is the limit that is hit here?  Number of unique structs?
