### ISSUE TITLE
multi thread ffi  callback

### ISSUE THREAD

**Issue by t59688** [LuaJIT/LuaJIT#996]
My code involves calling Lua functions within a multi-threaded environment, as shown in the code snippet below:
```lua
ffi.cdef [[
    typedef struct thpool_ *threadpool;
    threadpool thpool_init(int num_threads);
    int thpool_add_work(threadpool, void (*function_p)(void *), void *arg_p);
    void thpool_wait(threadpool);
    void thpool_pause(threadpool);
    void thpool_resume(threadpool);
    void thpool_destroy(threadpool);
    int thpool_num_threads_working(threadpool);
]]
thpool:add_work(function ()
    print("cb1")
end,nil);
thpool:add_work(function ()
    print("cb2")
end,nil);
while true do
    sys.sleep_ms(10000)
end
```
This may cause errors such as segmentation faults or 'PANIC: unprotected error in call to Lua API (attempt to compare string with nil)'.
Is there any advice  to help resolve this issue? And  is there a better solution for calling Lua callbacks in a multi-threaded environment with a C library?

**Comment by MikePall** [comment]
A Lua state (i.e. what's created with `luaL_newstate` aka `lua_open`) must not be used from different threads.
But you can create multiple independent Lua states and use them concurrently.

You can even do this from within LuaJIT with the help of the FFI:
* 1st state: Create a 2nd state with `luaL_newstate` and initialize it with `luaL_openlibs`.
* 1st state: Push a string with some Lua code to create an FFI callback to the 2nd state.
* 1st state: Load the code from the string with `lua_load` and run it with `lua_pcall` on the 2nd state.
* 2nd state code: Create an FFI callback by casting a Lua function and `return tonumber(ffi.cast('intptr_t', fptr))`.
* 1st state: Get the integer from the 2nd state with `lua_tointeger` and cast it back to a function pointer.
* 1st state: Hand the function pointer to the library function which expects a thread callback.

Further communication across these states must be done via the FFI, e.g. some shared piece of memory (pass a pointer to the thread function) and proper locking.

All of that said, going the async route is often the easier and more performant approach, unless you're doing heavy computations in those threads.
