### ISSUE TITLE
Slowdown under strange conditions

### ISSUE THREAD

**Issue by semyon422** [LuaJIT/LuaJIT#997]
I tried to write a discrete fourier transform using my complex number library and found that under certain conditions the code is very slow.
If you run the below code, then the second part (between 2 and 3) is much slower than the first. If you uncomment the if-else part in the dft function, then the code starts to run quickly. In this case, the execution logic does not change.
I showed it on the video.
Tested on the version of luajit provided in arch linux, as well as on the one compiled from the repository.

https://youtu.be/LIK2dDlkDco

```lua
local ffi = require("ffi")

-- subset implementation of https://github.com/semyon422/aqua/blob/master/cmath.lua
local complex = ffi.typeof(1i)

local function tocomplex(v) return ffi.istype(complex, v) and v or complex(v) end

local mt = {}

local function exp(z) return complex(math.exp(z[0]) * math.cos(z[1]), math.exp(z[0]) * math.sin(z[1])) end
local function abs2(z) return z[0] ^ 2 + z[1] ^ 2 end

function mt.__add(z, c) return complex(z[0] + c[0], z[1] + c[1]) end
function mt.__sub(z, c) return complex(z[0] - c[0], z[1] - c[1]) end
function mt.__mul(z, c) return complex(z[0] * c[0] - z[1] * c[1], z[0] * c[1] + z[1] * c[0]) end
function mt.__div(z, c) return complex(
	(z[0] * c[0] + z[1] * c[1]) / abs2(c), (z[1] * c[0] - z[0] * c[1]) / abs2(c)
) end

for k, v in pairs(mt) do
	mt[k] = function(z, c) return v(tocomplex(z), tocomplex(c)) end
end

complex = ffi.metatype(complex, mt)

--------------------------------------------------

local wave = {}
for i = 0, 8192 - 1 do
	wave[i] = 0
end

-- discrete fourier transform
local function dft(x, N, inv)
	local w = (inv and -1 or 1) * 2 * math.pi / N * 1i
	local X = {}
	for k = 0, N - 1 do
		io.write(".")
		io.flush()
		local x_n = 0

		-- strange behaviour here

		-- if inv then
			for n = 0, N - 1 do
				x_n = x_n + x[n] * exp(k * n * w)
			end
		-- else
		-- 	for n = 0, N - 1 do
		-- 		x_n = x_n + x[n] * exp(k * n * w)
		-- 	end
		-- end

		X[k] = x_n
		if inv then
			X[k] = X[k] / N
		end
	end
	io.write("\n")
	return X
end

local size = 1024
print(1)
local spectre = dft(wave, size)  -- FAST
print(2)
local spectre_inv = dft(spectre, size, true)  -- FAST or SLOW, depending on strange behaviour
print(3)
```

**Comment by XmiliaH** [comment]
You are mixing lua numbers and complex numbers. This is bad for the JIT compiler as it expects the same type to be used. Changing `wave[i] = 0` to `wave[i] = 0i` and `local x_n = 0` to `local x_n = 0i` will only use complex numbers making the JIT happy and the code faster.

**Comment by semyon422** [comment]
the problem is not that the code is fast or slow, the problem is that in this case it does not depend on the choice of the type of the variable, but on the presence or absence of a certain construct in the code.

**Comment by semyon422** [comment]
makes sense, it's super non-obvious, thanks for the clarification, I've never encountered this before.
it's unusual that calling a function can change its performance for next calls
```lua
-- with if/else block
---------------
dft(wave, size, true)  -- FAST
dft(wave_complex, size)  -- FAST
dft(wave_complex, size, true)  -- SLOW
---------------
dft(wave, size)  -- FAST
dft(wave_complex, size, true)  -- FAST
dft(wave_complex, size)  -- SLOW
```

**Comment by XmiliaH** [comment]
> it's unusual that calling a function can change its performance for next calls

When a trace is compiled it will use the current knowledge to compile the trace. This includes the types from the current iteration. When the trace is compiled and the types change this will cause a trace exit which has performance penalties.

**Comment by semyon422** [comment]
Thanks again for the clarification, I close the issue.
